src/content/docs/vulnerability-management/integrations/intro.mdx

Remove .net agent roadmap from VM docs

fix(vm): Remove .net roadmap

---

src/components/NavFooter.js

feat(sonic): change external io to internal io

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/introduction-alerts.mdx

Removing a redirect that is hiding a doc from the nav.

fix(alerts): removing redirect

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration.mdx

New date will be agreed together with the EOL team

Removed EOL callout

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx

Updated versions supported

---

src/content/docs/more-integrations/grafana-integrations/get-started/grafana-support-prometheus-promql.mdx

Added Prometheus Agent

---

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx

Fixed links

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

Remove old deprecation callout

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx

Now the 3 Zookeeper hosts have different CLUSTER_NAME and URL

Improving example

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1361.mdx

Release notes for infrastructure agent 1.36.1: https://github.com/newrelic/infrastructure-agent/releases/tag/1.36.1

docs: infra agent 1.36.1 release notes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/powerdns-monitoring-integration.mdx

Now that we are already [supporting](https://github.com/newrelic/newrelic-prometheus-exporters-packages/releases/tag/nri-powerdns-0.0.9) ARM, this callout is no longer necessary.

Remove not supporting ARM callout

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-5-0.mdx

Release notes for .NET Agent v10.5.0

Add Release Notes for .NET Agent v10.5.0

---

src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/parent-child-account-structure.mdx
src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx
src/content/docs/apm/agents/c-sdk/get-started/otel_cpp_example.mdx
src/content/docs/data-apis/manage-data/manage-your-data.mdx
src/content/docs/errors-inbox/errors-inbox.mdx
src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent.mdx
src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/get-pixie-integration-version.mdx
src/content/docs/mobile-monitoring/mobile-monitoring-ui/network-pages/http-errors-network-failure-analysis.mdx
src/content/docs/new-relic-solutions/get-started/glossary.mdx
src/content/docs/new-relic-solutions/new-relic-one/ui-data/basic-ui-features.mdx

Assorted fixes, including fixing wrong UI text, wrong pathing, adding link, and more.

Assorted small fixes

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
src/nav/accounts.yml

fix(auth domain): UI changes

---

src/components/NavFooter.js

Add extra level of data tracking for this CTA for VSU experimenting.

Add tessen tracking to NavFooter CTA

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx

chore: Update workflow variables

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx

even though this is clarified in the page message-templates.mdx this page comes first and customer complained they didn't know what it was.

clarifying that the new payload is handlebar

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx

Adding windows support docs for nri-ibmmq

feat(ibmmq): adding windows support

---

src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx

Add more information regarding the destination status

fix(Destinations): Add more information regarding destination statuses

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
src/content/docs/logs/ui-data/parsing.mdx
src/content/docs/release-notes/org-user-mgmt-release-notes/org-users-22-11-08.mdx
src/content/docs/release-notes/org-user-mgmt-release-notes/org-users-22-11-22.mdx

Work done: 
Add release note from Nov release
Add log parsing video

Assorted small edits

---

src/content/docs/apis/rest-api-v2/get-started/list-application-id-host-id-instance-id.mdx
src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx
src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx
src/content/docs/apm/agents/net-agent/other-installation/net-agent-install-resources.mdx
src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-windows.mdx

Some small edits to .net install

fix(branch .net): some small agent edits

---

src/i18n/content/jp/docs/apm/agents/net-agent/install-guides/install-overview.mdx
src/i18n/content/kr/docs/apm/agents/net-agent/install-guides/install-overview.mdx

Deleting some files for i18n mismatch

.NET install: delete couple files for i18n

---

gatsby-config.js
src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx

Hot fix release

---

src/install/dotnet/installation/linuxInstall1.mdx
src/install/dotnet/installation/linuxInstall2.mdx

Fixed some linux-related wording and headings

fix(branch net): edit linux content

---

src/i18n/translations/en/translation.json
src/pages/index.js

Looking for feedback on my admittedly lazy flavor text
Waiting on terraform link!

feat(vsu): update front page tiles

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1221.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1222.mdx

This PR adds release notes for v1222 of the Browser Agent

Browser Agent release v1222

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Style guide addition to Usage page

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring.mdx
src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring.mdx
src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/linux-agent-running-modes.mdx
src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx

No functional changes, just add language identifiers for syntax highlighting the terminal commands

chore: add syntax highlighting to terminal cmds

---

src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx

Apparently there's some confusion about what to do if you're using Azure and New Relic and you're logging in for the first time.
I've assigned @zuluecho9 as the reviewer on this one.

feat(Azure): Clarified how youlog infor the first time if you're using Azure Native

---

src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/new-azure-monitor-metrics-integration.mdx

* Added a new entry in https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/ about the new Azure Monitor metrics integration

New release note about Azure Monitor

---

src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx

Work done: 
Add link to MS Azure docs
Clarify how to log into NR
typo

Some Azure Native edits: add Azure docs link, more

---

src/content/docs/style-guide/writing-strategies/introduction-style-guide.mdx

Fix link to "Organize your page" doc

---

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-3.mdx

Release notes for go agent version 3.20.3

feat: (go agent release notes)

---

src/content/docs/apis/rest-api-v2/application-examples-v2/application-error-rate-example-v2.mdx

chore: add language identifiers

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-plugin-602.mdx

Cordova 6.0.2
* Fixed issue where attributes were not reporting correctly for custom events and breadcrumbs.

docs: update EOL and release notes for cordova 6.0.2

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx

Update supported version for .NET MySQL compatibility

Update supported version for .NET MySQL compatibility

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions.mdx

fix(alerts): remove circular redirect

---

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/soc2.mdx

Added [this URL](https://us.aicpa.org/interestareas/frc/assuranceadvisoryservices/aicpasoc2report) to the SOC 2 Type 2 documents.

feat(Security): Added SOC 2 url

---

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx

Fixed broken links

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup.mdx
src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx

* This updates our documentation to be more accurate regarding OTLP Metrics and our support for FedRAMP accounts. 
* N/A
* N/A

docs: updating OTLP metrics support for FedRAMP

---

gatsby-node.js
package.json
plugins/gatsby-plugin-generate-doc-json/gatsby-node.js
scripts/actions/utils/handlers.js
src/templates/docPage.js
src/utils/constants.js
yarn.lock

This pr
* updates the theme giving access to new step components
* adds resolvers for serializing and deserializing (both tested and working as expected)
* adds an isTutorial frontmatter key
* adds a tutorial meta tag on pages with isTutorial: true
* filters pages with isTutorial frontmatter from json generation

Add step components

---

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx
src/content/whats-new/2022/04/whats-new-4-14-data-updates.md

Assorted liaison improvements to Azure Native doc

Azure Native: some liaison improvements

---

src/content/docs/apm/agents/java-agent/installation/include-java-agent-jvm-argument.mdx

Doing some cleanup on the backend

fix(Java): adding toc frontmatter

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed.mdx

Title still contained the word "violation" even though it has been converted to "incident" throughout the doc.

Update title of document

---

src/content/docs/mlops/bring-your-own/getting-started-byo.mdx

Updating a broken link

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx

Azure native - add limitations and notes about Data Plus features that are unavialable.

Azure native   add link to azure docs, more

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx

Update supported version range for PostgreSQL

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5050.mdx

* release notes for New Relic's Android app

release notes for New Relic's Android app v5.0.5

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-8-0.mdx

Node.js Agent v9.8.0 Release Notes

Node.js Agent v9.8.0 Release Notes

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx

instead of the official handlebars docs

modifying handlebars links to internal page

---

src/content/docs/network-performance-monitoring/troubleshooting/ktranslate-cpu-usage.mdx
src/nav/network-performance-monitoring.yml

Added a troubleshooting doc for network monitoring

Network cpu troubleshooting

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/alerts-ai-overview-page.mdx

customers needs to understand where the metadata is coming from so they can best utilize it in their workflows filters.

Adding details about metadata origin

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx

fixing a simple spelling mistake

Fixing spelling

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx

This PR:
* Updates the demo app source code to the latest version
* Updates some of the terms used

Modify code changes from latest version

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-6-0.mdx

Release notes for .NET Agent 10.6.0

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-activemq.mdx

JIRA Ticket: https://issues.newrelic.com/browse/NR-82724
Updating the configuration files present on Step 1 and Step 2 of the configuration process

ActiveMQ - Configuration file updates

---

src/content/docs/mlops/bring-your-own/getting-started-byo.mdx

Changing from Boston to California dataset

Update getting-started-byo.mdx - Changing from Boston to California dataset

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

feat(sonic): restructuring page

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx

Changed the example CSS selector from .clazz to .class

Correction in By.className description

---

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx

fix: new section links were duplicates, breaking links

---

src/content/docs/change-tracking/change-tracking-introduction.mdx
src/content/docs/change-tracking/ci-cd/change-tracking-github-actions.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-as-code-guide.mdx
src/nav/change-tracking.yml

Let's follow the capitalization in GitHub's docs.

Capitalize GitHub Actions

---

src/content/docs/errors-inbox/error-external-services.mdx

Adding a note about expected errors to notification section.

Noon Release 1/25: Update error-external-services.mdx

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-8-1.mdx

Release notes for Node.js agent v9.8.1

Node.js Agent v9.8.1 Release Notes

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx

Add Flex to infra agent tarball setup

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx

NR-82405
recreation of https://github.com/newrelic/docs-website/pull/10836

fix(stream data): new azure addition

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

Add create user documentation for Multitenant DB

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx

Reverts newrelic/docs-website#11182

Revert "fix(stream data): new azure addition"

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx

This contains what is hopefully the final tutorial instruction revisions after user testing.

Modifies instructions after user testing

---

src/nav/alerts-applied-intelligence.yml

Fixing an unnecessary nav listing.

fix(alerts ): fixing nav

---

src/content/docs/infrastructure/prometheus-integrations/view-query-data/view-query-your-prometheus-data.mdx

Fix a link typo which leads to a link with bad formatting

Fix a link typo which leads to a link with bad formatting

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-800.mdx

Please release for 8.0.0 Java agent release on 1/26/2023.

Create java-agent-800.mdx (Publish ETA is 1/26/2023)

---

src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx

Please release for 8.0.0 Java agent release on 1/26/2023.

Update java-agent-eol-policy.mdx (Publish ETA: 1/26/2023)

---

src/content/docs/browser/new-relic-browser/guides/guide-to-monitoring-core-web-vitals.mdx

daily-release/Jan-26--2023-3_58

---

src/content/docs/service-level-management/alerts-slm.mdx

Update the alerts section in Service Levels to include the concept of maximum burn rate

docs(servicelevels): Update alerts section

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications.mdx

Fix spots where "incident" was used to describe an "issue" Made a few minor other fixes

Change "incident" to "issue" in appropriate places

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx

NR-82405
Reverts newrelic/docs-website#11220 to add back the Azure streaming data additions.  Has already gotten peer review in last PR.

Azure addition to 'Streaming data from NR' doc

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts.mdx

clarifying these limits are for legacy

channel limits are legacy, adding workflows

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/introduction-azure-monitoring-integrations.mdx

Some liaison improvements to make it more clear the delineations of the Service and what you get and don't get.

Improve azure intro doc 

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/bottom-funnel-analysis-customer-journey-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/customer-experience/customer-experience-quality-foundation-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/innovation-growth/development-release-quality-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/innovation-growth/improving-development-quality-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-as-code-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-coe.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/service-characterization-optimize-telemetry-data-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/diagnostics-beginner-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide.mdx

[NR-78268](https://issues.newrelic.com/browse/NR-78268)

fix(om guide): added new sections

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx

Support K8s v1.26

---

src/content/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview.mdx

Adds information about passing flags to the CLI install

Add information about guided install CLI flags

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1370.mdx

Infra Agent 1.37.0 Release Notes

Infra Agent 1.37.0 Release Notes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-activemq.mdx

Updated the configuration file name jvm-metrics.yml and also added few notes which could be helpful.

Updated the configuration file - ActiveMQ

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-configuration-management-tools.mdx

Fixed the Elastic Beanstalk and Puppet URLs.

fix(Infrastructure): Fixed URL for Elastic Beanstalk and Puppet

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/funnels-evaluate-data-series-related-events.mdx

We transition to an estimate when uniqueCount is 256 or more
https://issues.newrelic.com/browse/NR-66276

fix: uniqueCount is exact up to, not including, 256

---

src/content/docs/logs/get-started/logging-best-practices.mdx
src/nav/apm.yml
src/nav/browser.yml
src/nav/infrastructure.yml
src/nav/mobile-monitoring.yml
src/nav/synthetics.yml

Fixing some best practice guide entries in the nav that weren't working, and some random edits to logging best practice guide

fix(nav): some fixes to guide navs

---

src/content/docs/more-integrations/terraform/terraform-intro.mdx
src/content/docs/more-integrations/terraform/terraform-modules.mdx
src/content/docs/more-integrations/terraform/terragrunt.mdx

fix(terraform): remove <intro> and add isTutorial frontmatter

---

package.json
yarn.lock

Bump theme for minor CSS fixes, eslint. Also changes default language  in alt `link` `hreflang` to `x-default` to possibly fix issue where localized pages with only English content surface in english search results.

chore: bump theme

---

src/content/docs/accounts/accounts-billing/account-setup/domain-capture.mdx

from customer feedback NR-71412

fix(domain capture): add more about verification

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx

This is a new feature that delays evaluation of signals for the configured number of minutes.
Screenshot:

Morning Release 1/30: Description about delayed evaluation feature

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/redmine-integration.mdx

Fixed a typo on the sql query on line 54

Fixed typo on sql query

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-208.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-209.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-210.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-211.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-212.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-213.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-215.mdx
src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.28.mdx
src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.29.mdx
src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.30.mdx
src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.31.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.75.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.76.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.77.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.78.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.79.mdx

Updates release notes for Synthetics Job Manager, Node Browser Runtime, and Node API Runtime.

Synthetics: add release notes for synthetics products

---

src/content/docs/accounts/accounts-billing/account-setup/multiple-logins-found.mdx

from customer feedback NR-70121

fix(mult users); add info about deleting

---

src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx

feat: explain why AWS Config Service is important

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1223.md
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1223.mdx

This PR adds release notes and EOL item for v1223 release of the Browser Agent

Browser agent 1223 release notes

---

src/content/docs/vulnerability-management/integrations/security-data-api.mdx
src/i18n/content/jp/docs/vulnerability-management/integrations/security-data-api.mdx
src/i18n/content/kr/docs/vulnerability-management/integrations/security-data-api.mdx

Updating format of findings for Security API to match internal API format

fix: Updates Security API docs to reflect internal API

---

src/content/docs/logs/ui-data/obfuscation-ui.mdx

Added additional obfuscation expressions for our customers.

Additional Obfuscation Expressions

---

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx

fix(Azure): Fixed a misspelling

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-800.mdx

Reference an issue that may occur, resulting in the failure of the JVM.
The Java Agent Team has been made aware of an issue that could occur, which could cause the eventual failure of the JVM. While we work on a fix, we want to acknowledge the issue that could occur, etc.

Update the 8.0.0 release notes

---

src/content/docs/change-tracking/change-tracking-introduction.mdx

Removes iframe element from mdx file so the Smartling workflows can run

fix: remove iframe for Video component

---

src/data-dictionary/events/ServiceLevelSnapshot/ServiceLevelSnapshot.event-definition.md
src/data-dictionary/events/ServiceLevelSnapshot/entity.guid.md
src/data-dictionary/events/ServiceLevelSnapshot/entity.name.md
src/data-dictionary/events/ServiceLevelSnapshot/remainingErrorBudget.md
src/data-dictionary/events/ServiceLevelSnapshot/sliCompliance.md
src/data-dictionary/events/ServiceLevelSnapshot/timestamp.md

Add the ServiceLevelSnapshot event to the data dictionary

Add the ServiceLevelSnapshot event

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx

docs: correct typo in nerdgraph docs

---

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx

Updated a few module versions in the Node 16.10 and Chrome 100 runtimes.

chore(synthetics): updated module versions

---

src/content/docs/kubernetes-pixie/kubernetes-integration/uninstall-kubernetes.mdx

style(K8s): Fixed anchor links

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx

chore: add language identifiers/format code

---

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx

- update script to match recent platform changes
- add missing awaits
- add a second page
- improve comments and script log output
- fix `err` object which should have been named `exception`

fix scripted browser best practices example

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

Just adding a CTA to NRQL syntax so we can see if it can generate any signups with just a simple addition. Looking at a collapser format for this test.

feat(Sonic): adding CTA to NRQL syntax

---

src/content/docs/infrastructure/elastic-container-service-integration/understand-use-ecs-data.mdx

fix(ECS integration): Updated steps to match the new UI

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

Related to NR-76430 user feedback

fix(NRQL): Fixed what seems like a typo

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-x-ray-monitoring-integration.mdx

chore: add syntax highlighting

---

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx

Fixes a broken Markdown link.
N/A
N/A

docs: Fixed a broken link due to invalid Markdown syntax.

---

src/content/docs/style-guide/structure/steps.mdx
src/nav/style-guide.yml

Adds a style guide doc for our new `step` component

feat(style-guide): add steps guide

---

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
src/content/docs/url-obfuscation/configure-url-obfuscation-nodejs.mdx

* adds documentation for [url obfuscation](https://github.com/newrelic/node-newrelic/pull/1485) for nodejs agent (to be released with v 9.9.0)

(docs): nodejs agent regex url obfuscation

---

src/content/docs/style-guide/capitalization/capitalization.mdx
src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
src/content/docs/style-guide/ui-writing/capitalization.mdx

We are moving to title case in three types of content.

style change- UI writing capitalization

---

src/content/docs/change-tracking/ci-cd/change-tracking-github-actions.mdx

updating Change Tracking documentation for GitHub Action to align with recent update to [GHA marketplace docs](https://github.com/marketplace/actions/new-relic-application-deployment-marker)

chore: update change tracking gha documentation

---

src/nav/root.yml

Our nav casing should match the capability title casing in the UI

style(Nav): Updated nav to match title casing in UI

---

src/i18n/content/kr/docs/apm/agents/php-agent/installation/php-agent-installation-overview.mdx

fix: remove extra install feedback form

---

src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-manage-groups.mdx
src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx

Work done: 
Added context about managing groups/accounts via NerdGraph based on NR-75351 
Added clarity for .NET agent update based on NR-79319

Assorted customer feedback changes

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-9-0.mdx

Node.js Agent v9.9.0 Release Notes

Node.js Agent v9.9.0 Release Notes

---

src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/start-interaction.mdx

feat(content): update typo

---

src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx

Add two links to the .NET for Docker doc.

fix(.net); add links to Docker installs

---

src/content/docs/logs/ui-data/obfuscation-ui.mdx

updated the india expressions so they are not as broad as before.

updated expressions

---

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx
src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
src/content/docs/accounts/accounts/account-maintenance/set-session-timeouts.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Some liaison-related edits to declutter/simplify 'pricing model' mentions

fix(pricing): edits to 'pricing model' mentions

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx

Applying the new steps component to "Create your first alert."

fix(alerts): improving create your first alert

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/create-edit-or-find-alert-policy.mdx

fix(Alerts): Fixed some broken links

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration.mdx

After the agreement with the EOL team here is the new EOL date that fits in the time windows provided by them.

EOL callout for POMI in K8s

---

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx

Documenting a new feature of the ktranslate config
https://github.com/kentik/ktranslate/issues/447

Added trap_only to network config example

---

src/content/docs/new-relic-solutions/get-started/implementation-guide-organize-data.mdx

Related to NR-86475 docs feedback

fix(Solutions): Fixed broken link

---

src/content/docs/change-tracking/ci-cd/change-tracking-jenkins.mdx

Remove the old preview language from the Jenkins doc.

Remove wording from beta.

---

src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_set_appname.mdx

It was a doozy. Related to some customer feedback NR-80222

style(PHP APM): Rewrote a sentence for clarity

---

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/iso.mdx

Adding CodeStream to the ISO page for unapproved services

Updating the ISO page with info

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1224.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1225.mdx

- These release notes correspond with a repo release to be made today, February 9.
- Also updating EOL policy table.

Release notes and EOL update for browser agent v1225

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-10-0.mdx

Node.js Agent v9.10.0 Release Notes

Node.js Agent v9.10.0 Release Notes

---

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.90.mdx

Adding these release notes for changes seen here -> [commits](https://source.datanerd.us/synthetics/synthetics-node-browser-runtime/compare/release-159...release-162)
Adds context for some new changes we have.
changes seen here -> [commits](https://source.datanerd.us/synthetics/synthetics-node-browser-runtime/compare/release-159...release-162)
The link to the repo referenced here is connected to commits above.

chore: addd release notes for browser runtime.

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/anomaly-detection/anomaly-detection-applied-intelligence.mdx

Anomaly detection typo fixes

---

src/content/docs/service-level-management/alerts-slm.mdx

Removed duplicate instance of "up"

Service levels alerts typo

---

src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-proxy-support.mdx

Updated proxy config requirements for .NET agent

---

src/i18n/translations/kr/translation.json

Updated KR translation file to match English.

Updated KR file

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-10-1.mdx

Node.js Agent v9.10.1 Release Notes

Node.js Agent v9.10.1 Release Notes

---

src/content/whats-new/2023/02/whats-new-02-14-newrelic-mobile-app.md

Publish date and time: 02/14 morning
I'm a PMM, this post does not need review by a PMM. Thanks!

feat(whats-new): new relic mobile app intro - 02/14 morning

---

src/content/whats-new/2023/02/whats-new-02-14-newrelic-mobile-app.md

minor changes for New Relic style

---

src/content/docs/apm/apm-ui-pages/monitoring/apm-summary-page-view-transaction-apdex-usage-data.mdx

It doesn't solve NR-88762, but it's related to it.

fix(APM): Fixed minor pathing issue

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

Added a redirect in the [MongoDB monitoring integration (new version)](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/)

chore(MongoDB): Added a redirect

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-101.mdx

Hotfix release for React Native agent 1.0.1. Pushing release notes and updating EOL policy

docs: React Native Agent release 1.0.1

---

src/content/docs/apm/agents/ruby-agent/installation/ruby-agent-heroku.mdx

chore: add syntax highlighting to code

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
src/content/docs/apm/agents/ruby-agent/troubleshooting/no-data-appears-ruby.mdx
src/content/docs/infrastructure/host-integrations/infrastructure-integrations-sdk/get-started/compatibility-requirements-infrastructure-integrations-sdk.mdx
src/content/docs/logs/logs-context/disable-automatic-logging.mdx
src/content/docs/logs/logs-context/get-started-logs-context.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/interpret-nrdiag-output.mdx

A few things, including: 
Some wording improvement to logs addition
Note about historical data export EU limitation

Small edits feb 15

---

src/content/docs/infrastructure/prometheus-integrations/integrations-list/argocd-integration.mdx
src/content/docs/infrastructure/prometheus-integrations/integrations-list/harbor-integration.mdx
src/content/docs/infrastructure/prometheus-integrations/integrations-list/integrations-list-intro.mdx
src/content/docs/infrastructure/prometheus-integrations/integrations-list/velero-integration.mdx
src/content/docs/infrastructure/prometheus-integrations/troubleshooting/no-data-appears-prometheus-integration.mdx
src/nav/infrastructure.yml

Fixed these requests coming from the help-documentation channel (@mangulonr):
- Add these 3 new pages from [this PR](https://github.com/newrelic/docs-website/pull/11156) from yesterday to the left menu
- Include them also in the [Prometheus integrations list](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/integrations-list-intro/)
- Fix the [Harbor](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/harbor-integration/) document format, it looks like the format is broken.

fix(Prometheus): Fixing some errors, urls, typos, etc.

---

src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx

Fixed typo in introduction-apm.mdx

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/ansible-controller-integration.mdx

Observed text changes which can be made.

updates on ansible automation controller

---

src/content/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/uninstrumented-entities-service-maps.mdx

fix: Update uninstrumented-entities-service-maps.mdx

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1372.mdx

docs: infra agent 1.37.2 release notes

---

src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx

Simplify links and user journeys

chore(welcome-nr): Remove video, clean up links

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-data-partition-rules-tutorial.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

fix: replace html tags with markdown syntax

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx

Change origin to origins
Origin exist but it's too often empty
Source is inaccurate
Should be sources

Listing possible values

---

src/components/NavFooter.js
src/components/SubNavigation.js

Changes the color of the bottom left I/O CTA from blue to green.

feat(sonic): update bottom left CTA color

---

src/content/docs/apm/agents/python-agent/configuration/distributed-tracing-python-agent.mdx

This PR documents new configuration settings added in Python agent v8.7.0.
This PR should be merged along with its corresponding release notes: https://github.com/newrelic/docs-website/pull/11537

2/17/22 Add Python infinite tracing batching and compression settings. (Python v8.7.0 release)

---

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx

It renders really strangely https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#overview-keys

fix(sonic): Weird license key component

---

gatsby-config.js

Merge this in once the embeds are live in the help experience in the product (step 3)

Remove generate doc json

---

src/templates/docPage.js

accidentally removed when removing the doc banner

Add back missing media query

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

This PR add configuration steps and example configuration for MongoDB Atlas.
Few minor corrections as well

Add config steps and example for MongoDB Atlas support.

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx

In Kubernetes integration install Get Start page

Add/Link info to UnPrivileged/Privileged modes

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx

Updating the recommended field mappings to match the mappings used during automatic migrations

docs: update field mappings for Workflows

---

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-segment-your-data-buckets.mdx

Created this PR because the user can't sign the CLA in [11635](https://github.com/newrelic/docs-website/pull/11635).

fix(NRQL): Updated buckets ceiling typo

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx

Correct wording about how user type interacts with access control configuration.

Correct user type wording

---

src/content/docs/apm/agents/net-agent/other-installation/net-agent-install-resources.mdx

I removed the indentation in the lists of env vars, I think that was just a cut/paste thing, it didn't serve a purpose. I also added language identifiers for syntax highlighting.

chore: formatting code

---

src/content/whats-new/2023/01/whats-new-1-31-change-tracking.md

Per PMM, this post has been featured long enough.

Remove isFeatured flag for change tracking post

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
src/content/docs/apm/agents/net-agent/troubleshooting/technical-support-net-framework-40-or-lower.mdx
src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx

fix: + incompatible versions to ServiceStack.Redis

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-10-2.mdx

Node.js Agent v9.10.2 Release Notes

Node.js Agent v9.10.2 Release Notes

---

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx

Updating link to intro to synthetics

updating link in get started tutorial

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx

Removed a floating link to a random GH repo.

(fix) remove unnecessary GH link

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1226.mdx

Release notes for Browser Agent release 1226

(Publish February 22nd) docs: Browser Agent Release 1226

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

Add reference to scrape interval in the K8s helm in stallation doc

---

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx

fix(downgrade): improve explanation

---

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx

Testing something @akristen and I are toying with

style(sonic): Try h3s in synth stepper

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-801.mdx

Streamline the PR links on the various fixes referenced.
This PR just cleans up the references to the specific fix PRs in the notes so they look cleaner

Update the 8.0.1 release notes to clean up the PRs

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4060.mdx

Adds in release notes for the latest version of the New Relic iOS App.

Add in 4.6.0 release notes for the iOS app

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx

I also corrected the `attributes` casing, wrapped a couple code things in backticks, and made the json indentation consistently 4 spaces

chore: add syntax highlighting to code blocks

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/upgrading-kubernetes.mdx

Add a troubleshooting when upgrading K8s bundle

---

src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx

Updates EOL table, removing unsupported versions and adding latest release.

chore(Java): Updating eol document

---

src/i18n/translations/en/translation.json
src/pages/index.js

Changing vuln management tile to browser monitoring

feat(Sonic): Updating homepage tile (88204)

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

* What problems does this PR solve? Provides some hints to configure the MongoDB exporter in a containerized environment

feat(mongodb): containerized environment hints

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/anomaly-detection/custom-anomalies.mdx
src/content/docs/alerts-applied-intelligence/overview.mdx

Reported by @northyg on [11761](https://github.com/newrelic/docs-website/issues/11761):
Broken link on this page https://docs.newrelic.com/docs/alerts-applied-intelligence/overview/#detect-intro
This is the broken link https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/create-anomaly-alert-conditions/

chore(Alerts): Fixed broken link

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
src/install/config/java.yaml

Fixed broken links.
See [11786](https://github.com/newrelic/docs-website/issues/11786)

chore(Java agent): Fixed broken links

---

src/content/docs/mobile-monitoring/new-relic-mobile-ios/troubleshoot/swiftui-appdelegate.mdx

There was a typo in my code sample on a previous PR, this fixes that.

Docs iOS There was a typo in my sample code on a previous PR

---

src/content/docs/data-apis/ingest-apis/event-api/incident-event-rest-api.mdx

state acknowledge is not supported

Updating State correct values and description

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/data-apis/custom-data/sap-integration.mdx

Work done: 
* Remove 'included free' limits for different editions

fix(SAP): remove included limits

---

src/content/docs/logs/forward-logs/cloudflare-logpush-forwarding.mdx

Adds a statement in the Cloudflare logs page that echoes the announcement that Cloudflare recently made, which notified customers of upcoming changes in the Cloudflare network logs.
Context already included in the introduced changes.
None.

Adds callout announcing Cloudflare changes in logs happening on February-August 2023

---

src/content/whats-new/2023/02/synthetic-monitor-table-whatsnew-post.md

Product team wanted me to add info about the issue page specifically

Updates for whatsnew post

---

src/content/docs/style-guide/ui-writing/numbers-dates-and-times.mdx

Note that we avoid 24:00 to use 00:00 instead.

update(docs): add note about 00:00 to time options

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx

related to query based pricing, i'm improving our docs around 'inspected count limits'.

fix(inspected count): edit to definitions

---

src/content/docs/data-apis/manage-data/manage-data-retention.mdx

Note to hero: can go out whenever. 
Added note to data retention rule enforcement.

Hero - please merge when ready. Fix(retention): edit to enforced rules

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx

Updates the field name which contains the requesting accountId in the sample response.

Hero - merge when ready - Update accountId in response

---

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-230.mdx

Adding release notes for the new version of the Diagnostics CLI 2.3.0

chore: Add release notes for diag cli v2.3.0

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-api-nrql-condition-alerts.mdx

NerdGraph: Correct alerts query based on SME feedback

---

src/components/HomepageVideo.js

Trying out some alternate positioning for the text

chore: Update welcome text styles

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-how-nrql-works.mdx

typo: Update typo in NRQL Introduction

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Added "lifecycle" spelling to usage dictionary.

Addition to Usage dictionary

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5100.mdx

Release notes for the NewRelic Android App v5.1.0

Android app release notes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx

Added link to performance metrics config sample

---

src/pages/install/{installConfig.agentName}.js

To get around some hydration issues we previously only rendered the page on mount, but this broke our site indexing. I'm experimenting with wrapping only the steps with this logic

Display steps on mount

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx
src/i18n/content/jp/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx
src/i18n/content/kr/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx
src/nav/infrastructure.yml

Reverts newrelic/docs-website#10577

Revert "fix(infra): remove aws intregration"

---

src/components/NavFooter.js

add product and text fields to the instrumentation
clicks now send this data: (example)
```
component: "navFooterCta",
product: "browser",
text: "Go to browser monitoring UI",
```

chore: add individual instrumentation to nav cta's

---

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-12-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-13-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-14-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-14-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-15-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-15-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-15-2.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-16-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-16-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-17-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-2.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-19-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-19-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-19-2.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-0.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-1.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-2.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-3.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3100.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3110.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-340.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-350.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-360.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-370.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-380.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-381.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-390.mdx

Added the following fields to front content with changes made in the release
`features: []`
`security: []`
`bugs: []`

Go agent release metadata update

---

src/data-dictionary/events/SyntheticCheck/deviceOrientation.md
src/data-dictionary/events/SyntheticCheck/deviceType.md
src/data-dictionary/events/SyntheticCheck/hasUserDefinedHeaders.md
src/data-dictionary/events/SyntheticCheck/isMuted.md
src/data-dictionary/events/SyntheticCheck/monitorExtendedType.md
src/data-dictionary/events/SyntheticCheck/runtimeType.md
src/data-dictionary/events/SyntheticCheck/runtimeTypeVersion.md
src/data-dictionary/events/SyntheticCheck/scriptLanguage.md
src/data-dictionary/events/SyntheticCheck/secureCredentials.md

Added documentation for multiple attributes that have been added recently

fix(SynthCheckAttrs): Documented additional attributes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/lighttpd-integration.mdx

Making changes requested by SME's on the I/O team.

fix(lighttpd): making changes to syntax

---

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/lighttpd-integration.mdx

Daily release/mar 6  2023 8 03

---

src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx

Based on internal request: 
* Add 'enrichments' to free tier limitations
* Fix up some style stuff noticed in workflow doc
* in 'factors affecting access' doc, move up edition to permissions-related section

Add 'enrichments' to free tier limitations

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-verified-access-monitoring-integration.mdx
src/nav/infrastructure.yml

Jira created for this: NR-92109.
Documentation on how to connect AWS Verified Access logs to New Relic, and how to view and explore them in New Relic.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202991622110486

AWS Verified Access integration - new doc

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

This is based on a hero discussion.

New Relic Solutions: Add container registry

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1380.mdx

Infra Agent 1.38.0 Release Notes

---

src/data/popovers.json

this JSON will populate the soon-to-be-added InlinePopover component. the top-level keys are the different `type`s that can be used

create popovers.json for different popover types

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx

Update Java Agent Compatibility Page

---

src/content/docs/codestream/troubleshooting/security.mdx

Adds information for users to understand how and where NR is collecting data in the CodeStream extensions
n/a
https://github.com/newrelic/node-newrelic/issues/1524

Adds topic about CodeStream NodeJS agent

---

src/templates/docPage.js

fixes the giant instruqt iframe issue (example https://docs.newrelic.com/docs/infrastructure/infrastructure-monitoring/get-started/identify-root-causes-guide/#objectives)

Use max-width on iframes

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx

Simply updates the latest iOS agent release and adds to tr to table for 7.4.2 and 7.4.3

Update EOL page for iOS agent 7.4.3

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-distributed-trace-data-tutorial.mdx

chore: format graphql & add syntax highlighting

---

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx

found an error with the sign up banner and ** **

chore(sonic): markdown error

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-11-0.mdx

Node.js Agent v9.11.0 Release Notes

Node.js Agent v9.11.0 Release Notes

---

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3072.mdx

* Added the right release date for latest cpm release.

Fix: release date for last cpm release

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-227.mdx
src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.38.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.102.mdx
src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.13.0.mdx
src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.14.0.mdx

Adding new synthetics release notes after a deploy. 

Adding new synthetics release notes after a deploy

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4071.mdx

* Adds new release note for the latest version of the iOS mobile app

docs: Add in mobile app for iOS release 4.7.1

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx
src/nav/synthetics.yml

(Merge 3/9 afternoon) feat(content): adding redirect

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Added "skill set" to Usage dictionary.

Added term to Usage dictionary

---

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
src/content/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-4.mdx

Feature release for go agent 3.20.4 release

(Merge 3/9 in afternoon) Feat: go agent 3-20-4 release

---

src/content/docs/apm/apm-ui-pages/events/record-deployments.mdx

docs: fix typos in change tracking links

---

src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-metrics.mdx

chore: Update ruby-custom-metrics.mdx

---

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/new-relic-lookout-monitor-your-estate-glance.mdx

Was in the area, saw that this experience was a little confusing. Spruced up content:
- Deep linked to NR Lookout
- Spruced up intro 
- Deleted callout
- Updated pathing

feat(sonic): updating NR Lookout

---

src/components/DocTile.js

add new `animation` and `forceLightMode` props to
`DocTiles` and `DocTile` respectively
[springy doc tiles.webm](https://user-images.githubusercontent.com/14365008/224364436-4d4f5586-6aae-40c4-8dda-a722ef587158.webm)

feat: add animation to `DocTile`s

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

removed content about Alert Condition Consolidation

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/view-entity-health-status-find-entities-without-alert-conditions.mdx

fix(alerts): Fixed broken link

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring.mdx

Updates docker instrumentation requirements, including the latest engine version.

feat: update docker compatibility requirements

---

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx

This corresponds to our recent release.
https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-11-0/

fix(node agent): add Prisma supported version to table

---

src/content/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices.mdx

Mostly I just wanted to get away from "easily" and "wisely"

style(Alerts): Made some changes to the intro sentences

---

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-2-0-314.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-3-0-315.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-4-0-316.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-5-0-317.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-6-0-318.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-1000312.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-1010313.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9100262.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9101263.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9110267.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9120268.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9130270.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9170300.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9171301.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9181303.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9190309.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9200310.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9210311.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-980259.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-990260.mdx

Implements Agent Metadata for all currently supported releases of the PHP Agent .

Php Agent Metadata

---

src/content/docs/network-performance-monitoring/troubleshooting/change-ktranslate-versions.mdx
src/nav/network-performance-monitoring.yml

Added a new troubleshooting doc and nav link to network monitoring

Feat: New network troubleshooting doc

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx

Updates for .net agent release: https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v10.8.0

Updates for .NET Agent 10.8.0

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx

Updates the compatible version list for Restsharp to match the versions that have been or are being tested with the agent.
* What problems does this PR solve? Adds newer Restsharp versions to the compatibility list.

Add more supported Restsharp versions

---

.github/workflows/manual-add-files-to-translation-queue.yml

request to make prompt more clear

chore: add more clear prompt to workflow description

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

fix: Broken links on NRQL reference page

---

src/content/docs/business-observability/introduction-business-observability.mdx

changes for New Relic style and brand voice

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/overview-user-models.mdx

Liaison work: clarify the best way to know which user model you're on. 
And some assorted clean-up/simplification i noticed as I did that.

fix(user model): clarify how u know which on

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/alert-coverage-gaps.mdx

Related to customer feedback NR-98569

fix(Alerts): Fixed typo

---

src/i18n/content/jp/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx

Updated page to respond to user feedback.

Update to file

---

gatsby-config.js
package.json
yarn.lock

doing this to keep search engine bots from crawling the staging site

fix: add robots.txt plugin and configure in gatsby-config

---

src/content/whats-new/2023/03/whats-new-03-15-jfrog-integration.md

after talking to PMM, removing 'for free' wording that applied to 'full platform user'

fix(jfrog): tiny edit

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx

Update supported versions as agreed with @mangulonr on the format.

NR-92492: Update nri-PostgreSQL supported versions

---

src/content/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices.mdx

Add a new best practice to the Improve alert quality section on the [Alerts best practices](https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices/#alert-quality) page.
This is the ticket: [NR-96628](https://issues.newrelic.com/browse/NR-96628)

feat(Alerts): Added a new best practice

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx

fix: missing word

---

src/content/docs/mlops/get-started/intro-mlops.mdx

Fine tune for open AI Apps doc

---

src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx

fix: type in method name

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1391.mdx

infra agent release notes 1.39.1

infra agent release notes 1.39.1

---

src/content/docs/apm/agents/ruby-agent/installation/ruby-agent-installation-rails-plugin.mdx

Completes customer issue: https://issues.newrelic.com/browse/NR-87816

chore(Ruby agent): Mention Rails credentials

---

src/content/docs/apm/agents/java-agent/troubleshooting/application-server-jmx-setup.mdx

Fix broken JBoss links. Reorder entries alphabetically. Added Wildfly link. NR-85948

NR-85948 - Update application-server-jmx-setup.mdx

---

src/nav/errors-inbox.yml

This is a draft. Please do not review just yet!

fix(errors inbox): nav

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration.mdx

* 2 new metrics for Lambda Response Streaming added

metrics for Lambda Response Streaming

---

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80701.mdx

Add release notes for Python Agent v8.7.1 and document new config setting.

Add new release for python agent 8.7.1 - Please release 3/21 AM.

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4072.mdx

Adds latest release note for the iOS mobile app

doc: Add in release note for iOS mobile app 4.7.2

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx

Update historical export docs

---

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx

Add the missing reference to `host`. NR-80924

NR-80924 - Update java-agent-configuration-config-file.mdx

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx

From hero work, an ask to add a little more detail in the set up instructions

fix(azure monitor): more detail on setup

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx

Added link to Quickstart

---

src/content/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/aws-lambda-sending-logs-s3.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
src/content/docs/logs/get-started/get-started-log-management.mdx
src/content/docs/logs/get-started/logging-best-practices.mdx

chore: add lang identifiers

---

src/components/Persona/PersonaSignup.js
src/layouts/HomepageLayout.js

This fixes the footer bug we had and also makes the inline signup banner small/expandable on tablet width
I also adjusted the mobile header because it had some weird inconsistencies in light/dark

Homepage tweaks

---

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx

Wanted to include all Exporters that are Supported

Supported Prometheus Exporters

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-tvos-release-notes/newrelic-tvos-2022.mdx

Adds in release 2.2.2 of the New Relic tv app.

docs: Add in latest tv app release note

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-9-0.mdx

This PR updates the release notes for the Kubernetes integration docs.

Add release notes for Kubernetes integration v.3.9.0

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
src/content/docs/apis/rest-api-v2/basic-functions/api-overload-protection-handling-429-errors.mdx
src/content/docs/apis/rest-api-v2/troubleshooting/301-response-rest-api-calls.mdx
src/content/docs/apm/new-relic-apm/troubleshooting/cpu-usage-mismatch-or-usage-over-100.mdx
src/content/docs/browser/new-relic-browser/browser-pro-features/javascript-errors-page-detect-analyze-errors.mdx
src/content/docs/infrastructure/prometheus-integrations/view-query-data/supported-promql-features.mdx
src/content/docs/mlops/get-started/intro-mlops.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-apps-gradle-android-studio.mdx
src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-logs.mdx

Added 10 files for HT for Korean.
1. /docs/apis/rest-api-v2/basic-functions/api-overload-protection-handling-429-errors/
2. /docs/browser/new-relic-browser/browser-pro-features/javascript-errors-page-detect-analyze-errors/
3. /docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-logs/
4. /docs/infrastructure/prometheus-integrations/view-query-data/supported-promql-features/
5. /docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/
6. /docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts/
7. /docs/apm/new-relic-apm/troubleshooting/cpu-usage-mismatch-or-usage-over-100/
8. /docs/apis/rest-api-v2/troubleshooting/301-response-rest-api-calls/
9. …

Jmira nr kr ht 0322

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

Updates Oracle Integration docs to state the lower and upper supported versions.

docs: update oracle compatible versions

---

src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx

Couple of minor formatting tweaks

style(flutter): Bolding path, `Http` casing

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-13-0.mdx

Node.js Agent v9.13.0 Release Notes

Node.js Agent v9.13.0 Release Notes

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-14-1.mdx

Node.js Agent v9.14.1 Release Notes

Node.js Agent v9.14.1 Release Notes

---

src/content/docs/business-observability/introduction-business-observability.mdx
src/nav/business-observability.yml
src/nav/root.yml

Reverts newrelic/docs-website#12278
Reverting this because we didn't have CLA signature on this. Will re-implement this change later, and also we need to think about where this content lives as we don't want to add a new top-level nav entry for this necessarily.

Revert "chore: changed the intro to business observability as per review"

---

src/content/docs/business-observability/introduction-business-observability.mdx
src/nav/business-observability.yml
src/nav/root.yml

Reverts newrelic/docs-website#12299. Some edits to business observability section. @zuluecho9 will later remove this doc out of the top-level nav but for now we'll leave it.

Changes to the intro to business observability 

---

gatsby-config.js
package.json
yarn.lock

this will only show up in the production build

Update theme + osano

---

src/layouts/HomepageLayout.js
src/layouts/MainLayout.js
src/pages/index.js

This adds instrumentation to the nav being opened or closed and also adds more specific categories to the various searches we have (sidebar, persona view, default view)

Instrument nav collapse clicks and various searches

---

src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx

Reverts newrelic/docs-website#12334

Revert "feat: .NET Agent ITransaction API has a new SetUserId method"

---

src/content/docs/security/security-privacy/data-privacy/new-relic-personal-data-requests.mdx

Clarifies further how NewR assists with DSARs

Clarify process

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-229.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-230.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.105.mdx

Release notes for Synthetics Private location Images. 

Adding Private location release notes.

---

src/content/whats-new/2023/03/whats-new-3-29-K8s_dashboard.md

fixing release date for this What's New Post: https://github.com/newrelic/docs-website/pull/12354/files

fix(what's new ): updated release date

---

src/content/docs/data-apis/custom-data/sap-integration.mdx

liaison work; adding SAP req details

fix(sap): add more reqs/definitions

---

src/content/docs/data-apis/understand-data/metric-data/query-apm-metric-timeslice-data-nrql.mdx

Explain the timeslice overview metrics

docs: explain overview metrics

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx

Updates compatibility requirements for Kafka integration.

chore: update kafka integration compatibility message

---

src/content/docs/apis/nerdgraph/examples/async-queries-nrql-tutorial.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
src/content/docs/apis/nerdgraph/get-started/nerdgraph-explorer.mdx
src/content/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api.mdx
src/content/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api.mdx

Also fixed some broken docs / code

chore: add syntax hightlighting

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/alert-custom-violation-descriptions.mdx

fixing NRQL to GraphQL confusion

---

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx

We're adding this feature on March 31, can publish morning of.

March 31 - Azure native, add private offers

---

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80800.mdx

Note: This PR is to be merged on March 31 AM in conjunction with https://github.com/newrelic/docs-website/pull/12404/files.  Thanks!

March 31, AM - Add release notes for Python agent v8.8.0

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.229.0.mdx

Browser Agent v1.229.0 Release Notes

Browser Agent v1.229.0 Release Notes

---

src/content/docs/mlops/bring-your-own/mlops-byo.mdx

This is a duplicate of PR #12242 that had a broken CLA job.

Fix broken link in MLOps topic

---

src/content/docs/data-apis/understand-data/metric-data/cumulative-metrics.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/cumulative-metrics-transition-guide.mdx

* This PR is just updating the GA and EoL date for the Cumulative Metrics GA.

(chore) Updating ga and eol date

---

src/content/docs/apm/new-relic-apm/troubleshooting/errors-while-using-other-apm-software.mdx

clarify supportability

---

src/content/docs/data-apis/understand-data/metric-data/cumulative-metrics.mdx
src/content/docs/data-apis/understand-data/metric-data/metric-data-type.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/cumulative-metrics-transition-guide.mdx
src/data/whats-new-ids.json
src/nav/integrations.yml

NR-91197
Related to whats-new post: https://github.com/newrelic/docs-website/pull/11918 
Work done: 
New transition guide
Removed 'you might have this or that' wording
Additions of callouts/links to transition guide

(Publish date: on hold)  - Cumulative metrics transition guide

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx
src/nav/infrastructure.yml

New integration
with AWS Security Lake 
N/A

security lake monitoring integration

---

src/content/docs/style-guide/writing-strategies/introduction-style-guide.mdx

I made this edit as part of Rookie Relics.

I removed the exclamation point and mentioned some other repositories

---

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-241.mdx

This adds release notes for the Diagnostics CLI 2.4.1 along with supporting documentation on the new installation methods available for the Diag CLI.

feat: Install the Diag CLI and release 2.4.1

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-15-0.mdx

Node.js Agent v9.15.0 Release Notes

Node.js Agent v9.15.0 Release Notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx

Add several AI-related ones. Add a 'data sources' one.

User mgmt capabilities edits

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/set-user-id.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/set-user-id.mdx

I updated the iOS and Android API documentation to better describe that setUserId works with all mobile events.
https://issues.newrelic.com/browse/NEWRELIC-6359

Changed the setUserId description for iOS and Android

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

It makes the mongodb relabel config example easier to apply.

feat: improve mongodb relabel example

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1392.mdx

Release notes for infrastructure agent 1.39.2

docs: infra agent 1.39.2 release notes

---

src/components/SEO.js

the environment env var is set to staging for docs-dev so it should pick this up

Add noindex for staging env

---

src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-9-0-324.mdx

Release Notes and EOL Matrix update for the PHP Agent 10.9 release.

PHP agent release 10.9 - [04/05]

---

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-242.mdx

Release notes for nrdiag 2.4.2

feat(nrdiag): 2.4.2 release

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-222.mdx
src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-231.mdx

feat: 4-4 Synthetics release notes

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/kubernetes-integration-troubleshooting-error-messages.mdx
src/content/docs/logs/forward-logs/aws-lambda-sending-security-logs-s3.mdx
src/nav/logs.yml

aws-security-lake-monitoring-integration update

---

src/content/docs/security/security-privacy/information-security/security-bulletins.mdx

style(security): Remove stray period

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction.mdx

- There was a misspelling in the OpenTelemetry docs, and this change corrects that misspelling.
- Not needed.
- N/A

simple typo fix

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-232.mdx

Adds release notes for SJM release-232

chore: Add docs for sjm release-232

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx

Liaison work; clarifying full platform user downgrades/upgrades rule for contracts

fix(user count): clarifying user upgrade rules

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

Clarify LIKE operator

---

src/content/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument.mdx

Fixes [this issue](https://github.com/newrelic/docs-website/issues/12533).

fix(Java): adding redirect

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-how-nrql-works.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

new(NRQL comments): new docs, & link

---

src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx

Updates the Java agent's supported logging frameworks and documents some known caveats.

Update Java supported logging frameworks

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

fixed line break error on last PR

fixed line break error on last PR

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.230.0.mdx

Browser Agent v1.230.0 Release Notes

Browser Agent v1.230.0 Release Notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx

Liaison work: updating data plus info

fix(billing ingest): new data plus table

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-9-1.mdx

Updates release notes and EOL for .NET Agent v10.9.1

feat: Dotnet agent 10.9.1 release

---

package.json
yarn.lock

Issue that was breaking our install pages and some random release notes pages

fix: revert react-spring version

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-233.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.108.mdx

Adds release notes for release-133 of Synthetics Job Manager and 1.1.108 of Synthetics-Node-Browser-Runtime.

[Synthetics Job Manager] adds release notes for sjm and node-browser-runtime

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

Related to https://github.com/percona/mongodb_exporter/pull/633
Clarifying when direct_connect should be set to false 
@sigilioso take a look if you want :)

feat(mongoDB): loadbalance=true support

---

src/content/docs/journey-performance/guide-to-monitoring-core-web-vitals.mdx

Fixing the redirect issue that was originally fixed in [this PR](https://github.com/newrelic/docs-website/pull/12539/files).

fix(core web vitals): updating redirect

---

src/content/docs/apm/agents/net-agent/configuration/name-your-net-application.mdx

the example is a little basic, but I send it to customers often. I also made some extra spaces in the xml which is unconventional

chore: add example to app pool section

---

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx

Fixed all the links on the [Introduction to scripted browser monitors](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitor) page.

fix(Synthetics): Fixed all urls

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-810.mdx

Release notes for Java agent 8.1.0

(4/13) chore(java): java agent 8.1.0 release notes

---

src/content/docs/network-performance-monitoring/troubleshooting/different-entity-same-ip.mdx
src/nav/network-performance-monitoring.yml

Adding a new troubleshooting doc

Chore: Add NetMon troubleshooting doc - Duplicate IP

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx

1. several minor text edits
2. collapsable table added for multiple log types

chore: update info for sec lake

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx

* This adds relevant documentation for new `infrastructure-agent` config option.
* Please see https://github.com/newrelic/infrastructure-agent/pull/1614

Add new cloud_provider option for infrastructure-agent config

---

src/content/docs/new-relic-solutions/business-observability/configure-pathpoint.mdx

Updated the tags and `metaDescription` to be more in line with recent improvements to docs.

fix: update tags and metaDescription (configuring Pathpoint Page)

---

src/content/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api.mdx
src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
src/content/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx

Fix two broken links related to Go fingerprinting

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx

Updated comparison table: Codestream and number of integrations

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx

Documents elastic search master only config
[NR-106992](https://issues.newrelic.com/browse/NR-106992)

documenting elastic search master only config (NR-106992)

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

Add troubleshooting section for MongoDB new integration.

Add troubleshooting section for MongoDB

---

src/content/docs/query-your-data/explore-query-data/query-builder/introduction-query-builder.mdx

Current link seems to be broken.

fix(QueryBuilder): Update PromQL link

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hivemq.mdx
src/nav/integrations.yml

This PR include HiveMQ monitoring as an additional example of monitoring using the Opentelemetry Collector.

feat: include otel-collector hivemq docs

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx

fixing some broken links via 97471

fix(Synthetics): fixing broken links

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/data-dictionary/events/Transaction/http.statusCode.md
src/data-dictionary/events/Transaction/httpResponseCode.md

Edit to Data Plus table (remove 'user type')
Update a http response code related attribute in data dict

Small changes apr 17

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-coe.mdx

Added 1 file to human translation.

Added file to HT

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1401.mdx

Release notes for infrastructure agent 1.39.2

Release notes for infrastructure agent 1.40.1

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

This PR includes some clarifications regarding the integration running in containerized environments and it also includes steps to set it up using Docker and Prometheus Openmetrics integration for Docker.

feat: include mongodb docker-openmetrics guide

---

src/content/whats-new/2023/04/ whats-new-04-13-spring-kafka-streams

Support for updated Spring framework and Kafka streams

feat(whats-new): support for new instrumentation

---

src/content/docs/logs/troubleshooting/no-log-data-appears-ui.mdx

fix(logs in context): updating based on solutions feedback

---

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx

feat(accounts): update deletion info

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-744.mdx

iOS agent 7.4.4 release notes (publish 4/18 evening merge)

---

src/nav/infrastructure.yml

This doc was published, but not added to the nav.

fix(Infrastructure integrations): Add doc to the nav

---

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx

chore: code in backticks & lang identifiers

---

src/components/MDXContainer.js
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hivemq.mdx
src/i18n/content/kr/docs/apis/intro-apis/new-relic-api-keys.mdx
src/i18n/content/kr/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx
src/i18n/content/kr/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
src/i18n/content/kr/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
src/i18n/content/kr/docs/logs/forward-logs/enable-log-management-new-relic.mdx

remove all instances of the <LicenseKey /> component for the appropriate <InlinePopover> component

Remove instances of LicenseKey component

---

src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-10-0-0.mdx

chore: Adds Node.js agent v10.0.0 release notes.

---

src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx

Description:
This pull request fixes a broken link in the Start Using New Relic homepage. The original link was pointing to a page that no longer exists, so I updated it to the new URL. The new link directs users to the correct page with the relevant information.
Changes Made:
Updated the broken link to the new URL
Tested the link to ensure it is working as expected
Testing:
Clicked on the updated link to verify it directs to the correct page.

Updated broken link ref.

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-apps-gradle-android-studio.mdx

Came in as customer feedback: NR-105377

fix(Mobile monitoring): Fixed broken link

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-squid.mdx
src/nav/integrations.yml

This is a guide to monitor squid using the Opentelemetry Collector, the squid exporter and the prometheus receiver.
This is the issue we created for this: https://issues.newrelic.com/browse/NR-83161

style(OpenTelemetry): Added some modifications

---

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx

Fix for formatting of previous [PR](https://github.com/newrelic/docs-website/pull/12711) to use commas to be consistent with other parts of the table.

chore(PHP agent): Improve formatting

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx

~Do not merge please.
This is pending to be released yet.~
Documents new integration flags released on [v2.11.0](https://github.com/newrelic/nri-rabbitmq/releases/tag/v2.11.0)

Rabbitmq max queue workaround

---

src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx

Inform users about the typical impact of turning on change tracking.

Add ingest guidance

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx

nodejs18.x is supported

---

src/data-dictionary/events/VulnerabilityManagement/VulnerabilityManagement.event-definition.md
src/data-dictionary/events/VulnerabilityManagement/cve.md
src/data-dictionary/events/VulnerabilityManagement/cvss.score.md
src/data-dictionary/events/VulnerabilityManagement/cvss.vector.md
src/data-dictionary/events/VulnerabilityManagement/description.md
src/data-dictionary/events/VulnerabilityManagement/disclosureUrl.md
src/data-dictionary/events/VulnerabilityManagement/entity.guid.md
src/data-dictionary/events/VulnerabilityManagement/entityGuid.md
src/data-dictionary/events/VulnerabilityManagement/entityLookupValue.md
src/data-dictionary/events/VulnerabilityManagement/entityType.md
src/data-dictionary/events/VulnerabilityManagement/issue.id.md
src/data-dictionary/events/VulnerabilityManagement/issue.type.md
src/data-dictionary/events/VulnerabilityManagement/issue.vendor.id.md
src/data-dictionary/events/VulnerabilityManagement/issueId.md
src/data-dictionary/events/VulnerabilityManagement/issueInstanceKey.md
src/data-dictionary/events/VulnerabilityManagement/issueType.md
src/data-dictionary/events/VulnerabilityManagement/message.md
src/data-dictionary/events/VulnerabilityManagement/package.md
src/data-dictionary/events/VulnerabilityManagement/package.version.md
src/data-dictionary/events/VulnerabilityManagement/rawPayload.md
src/data-dictionary/events/VulnerabilityManagement/remediation.exists.md
src/data-dictionary/events/VulnerabilityManagement/remediation.upgradeAction.md
src/data-dictionary/events/VulnerabilityManagement/remediationExists.md
src/data-dictionary/events/VulnerabilityManagement/scan.id.md
src/data-dictionary/events/VulnerabilityManagement/severity.md
src/data-dictionary/events/VulnerabilityManagement/source.md
src/data-dictionary/events/VulnerabilityManagement/timestamp.md
src/data-dictionary/events/VulnerabilityManagement/title.md

Replaced "VulnerabilityManagement" with "vulnerability" in the dictionary.
See [NR-110616](https://issues.newrelic.com/browse/NR-110616).

fix(Dictionary): Replaced "VulnerabilityManagement" with "vulnerability"

---

src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx

Fixing a broken link in the intro to browser page

chore(browser): fix broken link

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Adding style usage for when to use the new and preview badges in the UI. Also describing when those terms apply.

Added new or preview usage info

---

src/content/docs/data-apis/understand-data/metric-data/cumulative-metrics.mdx

fixing a spelling typo on a sub-heading ++ a few wording changes in the top paragraphs

fix: spelling and various wordsmithing

---

src/content/docs/apm/agents/net-agent/azure-installation/debugging-agent-azure.mdx
src/nav/apm.yml

What problems does this PR solve?
This PR contains a new doc that attempts to provide a comprehensive troubleshooting resource similar to the ones we have for [Windows](https://docs.newrelic.com/docs/apm/agents/net-agent/troubleshooting/debugging-net-windows/) & [Linux](https://docs.newrelic.com/docs/apm/agents/net-agent/troubleshooting/debugging-net-core-agent-linux/) environments.
The .NET agent engineering hero reviewed and approved the doc per [this Slack post](https://newrelic.slack.com/archives/C28S389EG/p1681499093809669).

new azure debug doc

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-10-0.mdx

Release notes for .NET Agent 10.10.0

.NET Agent 10.10.0 Release Notes

---

src/content/docs/errors-inbox/error-users-impacted.mdx

Added mobile entry since the mobile agent supports this too

Adding mobile entry

---

src/data-dictionary/events/K8sCronjobSample/K8sCronjobSample.event-definition.md
src/data-dictionary/events/K8sCronjobSample/concurrencyPolicy.md
src/data-dictionary/events/K8sCronjobSample/createdAt.md
src/data-dictionary/events/K8sCronjobSample/cronjobName.md
src/data-dictionary/events/K8sCronjobSample/isActive.md
src/data-dictionary/events/K8sCronjobSample/isSuspended.md
src/data-dictionary/events/K8sCronjobSample/label.LABEL_NAME.md
src/data-dictionary/events/K8sCronjobSample/lastScheduledTime.md
src/data-dictionary/events/K8sCronjobSample/metadataResourceVersion.md
src/data-dictionary/events/K8sCronjobSample/namespaceName.md
src/data-dictionary/events/K8sCronjobSample/nextScheduledTime.md
src/data-dictionary/events/K8sCronjobSample/schedule.md
src/data-dictionary/events/K8sCronjobSample/specStartingDeadlineSeconds.md

We recently added the `K8sCronjobSample` event to New Relic. This PR adds that info to the data dictionary.

feat(data dictionary): Add K8sCronjobSample

---

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.40.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.115.mdx
src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.18.0.mdx

Adds release notes for recently deployed Synthetics runtimes

chore: Release notes for the Synthetics runtimes

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-241.mdx

Adds release notes for recent deploy of synthetics job manager

chore: add release notes for synthetics job manager release-241

---

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp-moderate.mdx

Adding NR Mobile App to out-of-scope for FedRAMP

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-textract-monitoring-integration.mdx
src/nav/infrastructure.yml

Textract doc

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-translate-monitoring-integration.mdx
src/nav/infrastructure.yml

Translate doc

---

src/content/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx
src/content/docs/data-apis/ingest-apis/metric-api/introduction-metric-api.mdx
src/content/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes.mdx
src/content/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api.mdx
src/content/docs/data-apis/ingest-apis/metric-api/troubleshoot-nrintegrationerror-events.mdx

Chore: add language identifiers to Metrics API section

---

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx

Change made as requested by Jackie Opel

Updating per changes in the CA org

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring.mdx
src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide.mdx
src/nav/browser.yml

Fixing a few random this and thats which came up while on hero duty

fix(Browser): fixing some things brought up on hero duty

---

src/content/docs/apm/agents/net-agent/azure-installation/azure-pipelines-wipes-out-newrelicazurewebsitesextension-directories.mdx

this slipped through when a previously built PR got merged

Change png to webp

---

src/content/docs/accounts/accounts-billing/account-setup/login-options.mdx

Slated May 1, but we will confirm day of.
Added that Google accounts can now be used to log into New Relic (effective 5/1/2023)

May 1: Update login-options.mdx

---

src/content/docs/accounts/accounts-billing/account-setup/domain-capture.mdx

Slated for May 1 but we will confirm. To go live when we release Google authentication (aka 'social sign up') https://github.com/newrelic/docs-website/pull/12799.

~May 1: Add google auth limitation for domain capture

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

Work to update Networks doc with missing info, and to reorganize it a bit. NR-109222

Networks doc: add missing info and reorganize

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx

The values that were used in the previous documentation were partial.
In addition, the description of each variable was not clear enough.

chore: Update workflow variables state and status

---

src/content/docs/apm/agents/java-agent/async-instrumentation/introduction-java-async-instrumentation.mdx
src/content/docs/apm/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications.mdx
src/content/docs/apm/agents/java-agent/async-instrumentation/troubleshoot-java-asynchronous-instrumentation.mdx
src/content/docs/apm/agents/java-agent/attributes/java-agent-attributes.mdx
src/content/docs/apm/agents/java-agent/custom-instrumentation/custom-jmx-yaml-examples.mdx
src/content/docs/apm/agents/java-agent/custom-instrumentation/java-agent-custom-jmx-instrumentation-yaml.mdx
src/content/docs/apm/agents/java-agent/custom-instrumentation/java-instrumentation-xml.mdx
src/content/docs/apm/agents/java-agent/custom-instrumentation/java-xml-instrumentation-examples.mdx
src/content/docs/apm/agents/java-agent/custom-instrumentation/troubleshooting-java-custom-instrumentation.mdx

chore: add language identifiers to java custom inst

---

src/content/docs/apm/agents/python-agent/python-agent-api/acceptdistributedtraceheaders-python-agent-api.mdx

fix: typos & add lang identifiers

---

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3083.mdx

Adds release notes for a no-op release for the CPM, but we want customers to know what it does when they see it in Quay.io and DockerHub

chore: Release notes for CPM 3.0.83

---

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-group-results-across-time.mdx

Two datetime functions were undocumented, and none of them documented their format argument
https://issues.newrelic.com/browse/NR-112909

fix: NR-112909 Add missing datetime functions and format argument

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx

Adding several changes that were missed in the initial post.

Adding several known changes

---

src/content/docs/logs/forward-logs/mux-video-streaming-firehose.mdx
src/nav/logs.yml

* New Documentation for getting Mux data into New Relic using Kinesis Firehose. A new doc will be created for GCP customers of Mux as well.

feat: docs for amazon kinesis mux streaming

---

src/content/docs/style-guide/images/screenshots-images.mdx

* Use dark mode for screenshots
* Clarified a few other image guidelines
* Also re-ordered collapsers to put screenshots section first

feat(style guide): Dark mode for screenshots

---

src/content/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api.mdx
src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx

chore: fix code block, +language identifier

---

src/content/docs/apm/agents/ruby-agent/troubleshooting/incorrect-data-unicorn.mdx
src/nav/apm.yml

This PR shares a solution a Ruby agent customer recently found related to this GTSE: https://issues.newrelic.com/browse/NR-96043 (Internal)
I'd like to add this to our Troubleshooting documentation in case other customers experience a similar issue.

chore(ruby): Add unicorn troubleshooting doc

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx

Ticket URL:https://issues.newrelic.com/browse/NR-113368 
Would it be possible to consider incorporating the instructions directly onto the docs page? It would be very helpful to have the instructions easily accessible in one place.

Updated the snowflake docs

---

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-102.mdx

* 1. Kotlin library has vulnerability in certain versions, reference [here](https://security.snyk.io/package/maven/org.jetbrains.kotlin:kotlin-stdlib)
* 2. This release is simply updating to a version that has addressed the vulnerability
* 3. Target to release 5/4/23

Android NDK agent v1.0.2 release notes(Target to release: 5/4/23)

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Removed the collapser group so the system requirements are front and center on the doc. We've received several questions/tickets on what is/isn't supported so we need this section to always be expanded on this page.

Updated System Reqs

---

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx

Some people seem confused about how to disable this feature. Since I've sent this info to a few customers I decided to add it to the docs.

chore: add example of how to disable app logging

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-246.mdx

- What problems does this PR solve?
- Adds release notes for the latest release of the Synthetics Job Manager

chore: add release notes for synthetics job manager release-246

---

src/nav/browser.yml

* The link for `New Relic's impact on your app's performance` was dead because the parameter in the `browser.yml` Nav file was `page` instead of `path`

fix: change page to path so link works

---

src/content/docs/browser/browser-integrations/flutter-web-integration.mdx

**Ticket Url:** https://issues.newrelic.com/browse/NR-114577
**Description:** Flutter Web monitoring docs under Step 2 point 7 has be updated. The browser code snippet has to be copied and pasted into the head tag of the index.html file instead of the body tag.

Updated Flutter Web monitoring docs

---

src/content/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx
src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx
src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-metrics.mdx
src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
src/content/docs/apm/agents/ruby-agent/api-guides/third-party-instrumentation.mdx

chore: add syntax highlighiting to ruby

---

package.json
scripts/actions/check-job-progress.js
yarn.lock

currently some needed outputs aren't getting logged in our github workflow which is causing the translation workflow to skip committing and PRing. this should make them output

Use @actions/core to set github output from script

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/setup-prometheus-agent.mdx

Updated line 207 to change the typo from cat to at

[chore] Update setup-prometheus-agent.mdx

---

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/diagnostics-beginner-guide.mdx

fix(oma): typo fix

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx

it wasn't clear to reader how to convert a slide by query.

clarifying how to convert a slide by NRQL to alert

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration.mdx

Solves [this issue](https://github.com/newrelic/docs-website/issues/8887).

fix(infrastructure): editing nri-prometheus

---

src/content/docs/errors-inbox/error-users-impacted.mdx

Adding the Browser method

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/changes-since-v3.mdx

Suggestion to update the grammar in the `Migration Guide` paragraph

[chore] Update changes-since-v3.mdx

---

src/content/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx
src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx

Updated paths to broken links.

Fix some links to apm methods

---

src/content/docs/browser/browser-integrations/nuxt-js-integration.mdx

**Ticket URL**: https://issues.newrelic.com/browse/NR-113964
**Description**: Nuxtjs docs under Step 4 i have updated title for easy understanding to paste the  code snippet.

Updated the Nuxt-js docs

---

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/interpret-nrdiag-output.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx

We are releasing a new version of the Diagnostics CLI which includes a new command line flag `-api-key`.  This PR includes the updates to the relevant docs to document the new flag, and the release notes for the new cli version.

feat: Diagnostics CLI 2.5.0 new features and release notes

---

src/content/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking.mdx

- This PR updates the behavior of a session to match the new definitions used by the browser agent.
- These changes will go live with Browser Agent v1.232.0, released Monday May 8, 2023
- https://issues.newrelic.com/browse/NEWRELIC-8005

feat:update session behavior description

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx

This PR updates the browser agent EOL list to include v1.232.0
https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1.232.0

fix:update browser EOL list

---

src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx

* Adds absent Security section in "Understand and manage data ingest" page
* [NR-108868](https://issues.newrelic.com/browse/NR-108868)

feat: Adds Security to list of data ingest sources

---

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx

Replaced the old syntax with the latest recommended format per Kentik.

Update syntax for AWS secret manager settings

---

.github/workflows/check-translations-and-deserialize.yml

addresses workflow deprecation warnings from third party action

bump create-pull-request action to v5

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-6110.mdx

* What problems does this PR solve? - v6.11.0 release notes and EOL update

Android agent v6.11.0 release notes (Target to release 5/11/23)

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload.mdx

feat(ai): updated example

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1410.mdx

* Added better explanation for features included in release 1.41.0 of the infra agent.

infra-agent release notes 1.41.0 patch

---

src/content/docs/vulnerability-management/dev-workflow.mdx

chore: Typo in dev-workflow.mdx

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx

Repositories:
- https://github.com/newrelic/java-aws-lambda
- https://github.com/newrelic/newrelic-lambda-tracer-java
- https://github.com/newrelic/newrelic-dotnet-agent/tree/main/src/AwsLambda

Chore: SDK reference

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx

Add channel status URL

---

package.json
scripts/convertPNGs.mjs
yarn.lock

we shouldn't have two seperate command line arg parsing libraries
sorry `meow` 😿

replace `meow` with `commander`

---

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx

Quick update to address jira feedback NR-110490

chore(azure): added syntax highlighting

---

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/apollo-server-plugin-nodejs.mdx

I noticed we had some out of date information around libraries we support for apollo server.

docs: updated readme to include more libraries we support

---

.github/workflows/check-images.yml
package.json
scripts/convertPNGs.mjs
yarn.lock

- deletes unused images no longer needed by i18n files
- converts non webp images
- runs weekly and commits to develop
see it working (without commit) [here](https://github.com/newrelic/docs-website/actions/runs/4963007858/jobs/8881766983):

Create image check workflow

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx

* Adding docs for a new setting released with infra-agent 1.40.1

infra-agent new setting: async_inventory_handler_enabled

---

.github/workflows/agent-release-notes.yml
scripts/releaseNotes.mjs

just a simple job to run the upload script. i also added an `--upload` option to the script. omitting it means the script won't attempt to upload to S3 but just outputs to stdout
i used console.error, which outputs to stderr, for info messages so we can do useful stuff with the actual output

release notes action/job

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration.mdx

Add logging options since New Relic logging isn't yet supported on Fargate Nodes.

EKS Fargate: Add logging options

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-6111.mdx

* What problems does this PR solve? - Android agent v6.11.1 release notes

Android agent v6.11.1 release notes and EOL(target release 5/16/23)

---

src/content/whats-new/2023/03/whats-new-03-14-cumulative-metrics.md

Noticed this link was broken and updated it

fix(Metrics): Fix broken link

---

src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx

More info about SCIM users only being able to use SCIM

SCIM is required after SCIM setup

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx

Added notes for SQS queue and Subscriber creation

chore: sec lake updates

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx

Update .NET EOL policy doc for 10.10.0 release.

Update EOL doc for 10.10.0 release

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-environment-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-application-insights-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-automation-account-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cdn-profile-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cloud-services-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cognitive-search-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-data-box-edge-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-data-explorer-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-data-lake-analytic-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-data-lake-storage-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-data-share-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-device-provisioning-service-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-hdinsight-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-integration-service-environment-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-iot-hub-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-peering-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-peering-service-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-purview-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-stream-analytics-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-synapse-analytics-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-time-series-insights-monitoring-integration.mdx
src/nav/infrastructure.yml

- releasing documentation for newly added Azure entities (cohort 3) supported by Azure Monitor integration

feat: add documentation for new Azure entities (cohort 3) supported by Azure Monitor

---

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql.mdx

Resolving a thread in #help-documentation.

fix(infra): known limitations

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx

This PR addresses [this issue.](https://github.com/newrelic/docs-website/issues/9711)

fix(workflows): adjusting capabilities

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.232.1.mdx

Browser Agent v1.232.1 Release Notes

Browser Agent v1.232.1 Release Notes

---

src/content/docs/network-performance-monitoring/advanced/snmp-profiles.mdx

Updating language on the SNMP profiles page clarifying expectations, SLAs, and the process for requesting changes
Documentation on the decision process handled via Confluence DACI

Update SLA language for SNMP profiles

---

src/content/docs/mobile-monitoring/new-relic-mobile-cordova-phonegap/get-started-with-cordova-monitoring.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx
src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-plugin-120.mdx
src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-plugin-620.mdx
src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-100.mdx
src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-120.mdx

Hybrid mobile agent release notes:
- Errors will now be reported on Handled Exception tab
- Added shutdown method

Hybrid mobile agent releases may 17 2023

---

src/content/docs/journey-migration/migrating-apm.mdx

Change "User" to "Use" in 
* Use New Relic with open source tools such as OpenTelemetry

fix: address typo in migrating-apm.mdx

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5010.mdx
src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5011.mdx

Adds in 5.1.0 and 5.1.1 release notes for the iOS mobile app.

Adds in iOS mobile app release notes

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1420.mdx

Release notes for the infra agent 1.42.0

docs: add release notes for infra agent 1.42.0

---

src/content/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx

fix: broken section link ID, & +.NET to section

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Opening a PR to try to clarify how to refer to AWS product names.

chore(usage dictionary): Clarify AWS product naming

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx

Fixed typo word 'Inteligence' to 'Intelligence'

[chore]Update incident-workflows.mdx

---

src/content/whats-new/2023/05/whats-new-05-22-systems-manager-distributor.md

AWS Systems Manager Distributor for enforcing New Relic Observability on full fleet of EC2 and/or on-premise instances. Can be published to What's New as soon as it's reviewed. This integration is already launched and live.

feat (what's new): AWS Systems Manager Distributor

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-version2-kubernetes-integration-windows.mdx

Update reference link in k8s windows integration.
Reference PR - https://github.com/newrelic/docs-website/pull/13078

(Fix) Update reference link in k8s windows integration

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/redpanda-integration.mdx

Ticket URL: https://issues.newrelic.com/browse/NR-109940
Description: Syntax error in code snippet.

Updated redpanda docs

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx

Azure Monitor GA is going GA on May 23rd. Please approve this change on May 23rd.

May 23 - Azure Monitor integration for the Azure Monitor release 

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx

Add wmi_enable_proc_data flag to infrastructure agent configuration

Add wmi_enable_proc_data flag to infrastructure agent configuration

---

src/content/docs/apm/agents/net-agent/attributes/net-attribute-examples.mdx

I think this was just a cut/paste remnant, it wasn't functional

chore: remove indentation in example output

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

This PR includes the changes from #13169 to allow edits by maintainers.
Includes an additional configuration parameter description and more metrics in oracledb integration. The changes were introduced in this PR: https://github.com/newrelic/nri-oracledb/pull/118

feat: include SYS PDB metris support in oracledb docs

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1421.mdx

Release notes for infrastructure agent 1.42.1: https://github.com/newrelic/infrastructure-agent/releases/tag/1.42.1

docs: infra agent 1.42.1 release notes

---

src/content/whats-new/2023/05/whats-new-05-24-apm-summary-tiles.md

An image in a whats new post isn't appearing. Updated the image name so something appears on the post

fixing image name

---

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-251.mdx

These are the release notes for the Diagnostics CLI 2.5.1

feat(nrdiag): 2.5.1 release

---

src/content/docs/journey-demand/autoscale-your-infra.mdx

Fixes a very annoying and hard to fix bug with some example code in the following doc: https://docswebsitedevelop-bradleycamachopatch17.gatsbyjs.io/docs/journey-demand/autoscale-your-infra/

Fix code example rendering

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx

The PR adds a new MongoDB version to the list of supported versions for the dotnet agent.

Adds new MongoDB version to dotnet agent compatibility pages

---

src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-9-2-2.mdx

Reverts newrelic/docs-website#13220

Revert "Ruby Release Notes"

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-chatbot-monitor-integration.mdx

Asana Task - https://app.asana.com/0/1202974982230192/1202975068291765
Partnership Engineering Team -
- Added AWS-chatbot Entity support
- AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud.
- https://github.com/newrelic/entity-definitions/pull/1083
- https://source.datanerd.us/entity-platform/entity-type-ui-definitions-service/pull/370

[Product-Partnerships] Updated AWS Chatbot Monitor Integration

---

src/components/ToggleView/ToggleSelector.js
src/components/Tooltip.js
src/hooks/usePosition.js

this won't update the Tooltip's position if the page is resized, but since it only shows briefly i think this is okay

fix homepage tooltip cut off, add usePosition hook

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.233.0.mdx

Browser Agent v1.233.0 Release Notes

Browser Agent v1.233.0 Release Notes

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/container-infrastructure-monitoring.mdx

Fix containerd socket mount option

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/lampy-integration.mdx

Ticket URL: https://issues.newrelic.com/browse/NR-121083
Description: LAMPy docs under Step 4 updated format line and Updated step 5.

Updated lampy-integration docs

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx

Added the introductory paragraph to the [How to enrich data](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/#enrichments) section to have it similar to the UI.

feat(Alerts): Added introductory paragraph to enrichment

---

src/content/docs/journey-app-slow/external-services.mdx
src/content/docs/journey-app-slow/root-causes.mdx

There were a few docs with funky image sizing. These have to use adjusted widths, but I'm altering the weights to see if they render nicely now.

feat(sonic): fix image sizing

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-13-0.mdx

This PR updates the release notes for the Kubernetes integration docs.

Add release notes for Kubernetes integration v.3.13.0

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-components.mdx

chore: typo in kubernetes-components.mdx

---

src/nav/infrastructure.yml

Asana Task - https://app.asana.com/0/1202974982230192/1202975068291765
Partnership Engineering Team -
- Added AWS-chatbot Entity support
- AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud.
- https://github.com/newrelic/entity-definitions/pull/1083
- https://source.datanerd.us/entity-platform/entity-type-ui-definitions-service/pull/370

[Product Partnerships] Corrected Typo For AWS Chatbot Entity

---

src/content/docs/tutorial-large-logs/filter-large-logs.mdx
src/content/docs/tutorial-large-logs/get-started-managing-large-logs.mdx
src/content/docs/tutorial-large-logs/organize-large-logs.mdx

fix(sonic): fix log tutorial tiles

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

Update kubernetes versions supported 

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.233.1.mdx

Browser Agent v1.233.1 Release Notes

Browser Agent v1.233.1 Release Notes

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lex-monitoring-integration.mdx
src/nav/infrastructure.yml

[Product-Partnerships] Create aws-lex-monitoring-integration.mdx

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-version2-kubernetes-integration-windows.mdx

Correcting config file name in windows V2 integration

(Fix) Correcting config file name in windows V2 integration

---

src/data-dictionary/events/NrConsumption/GigabytesIngested.md

somehow this file got out of date with main, pulling in main's version

Bring in changes from main

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5020.mdx

Adds in the latest New Relic iOS mobile app release note

docs: Add in Mobile app for iOS 5.2.0 release note

---

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx

Update minimum agent versions for new api params/methods

---

src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx

HOLD FOR PUBLISH AFTER NOON PDT ON 6/1
support date for java agent 8.3.0

6/1 afternoon: Update java-agent-eol-policy.mdx

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-830.mdx

HOLD FOR PUBLISH AFTER NOON PDT ON 6/1
java agent 8.3.0 release notes

6/1 afternoon: Create java-agent-830.mdx

---

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
src/content/docs/logs/logs-context/configure-logs-context-go.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-22-0.mdx

Go agent release changes for 3.22.0 release
Expected agent release time: eod today

EOD June 1: Go agent release 3.22.0

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-276.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.12.mdx

Adds Synthetics release notes :D 

docs: SJM + Browser release notes

---

src/content/docs/apm/agents/java-agent/additional-installation/install-java-agent-java-2-security.mdx
src/nav/apm.yml

Adding back doc we deleted in https://github.com/newrelic/docs-website/pull/9681/files

fix(java 2 security): re-add doc

---

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
src/content/docs/logs/logs-context/configure-logs-context-go.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-22-1.mdx

Hotfix release of the APM go agent. Expected to ship EOD today.

feat: APM go-agent release 3.22.1

---

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.15.mdx

* Adds release notes for synthetics node browser runtime v 2.0.15

docs: Synthetics node browser runtime release notes

---

src/content/docs/licenses/end-of-life/notification-changes-new-relic-saas-features-distributed-software.mdx

Edits to EOL table 
Preview build: https://docswebsitedevelop-changestoeoltable.gatsbyjs.io/docs/licenses/end-of-life/notification-changes-new-relic-saas-features-distributed-software/#lead-time

fix(EOL table): major changes

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx
src/content/docs/new-relic-solutions/get-started/networks.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql.mdx

Assorted work based on customer feedback:
Fix couple links/refs in Networks doc
Clarifying some wording about what infrastructure event data is
NerdGraph nrql doc: making it a little clearer how to run queries

Fix links in networks doc, and other work

---

src/content/docs/agile-handbook/appendices/ticket-best-practices.mdx

Clarification for https://issues.newrelic.com/browse/NEWRELIC-6875

chore(agile handbook): Clarify jira shortcut link (NEWRELIC-6875)

---

src/content/docs/new-relic-solutions/get-started/glossary.mdx
src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Make RUM guidance a little easier to parse

chore(style guide): Clarify RUM guidance

---

src/components/SEO.js

Per Jason Chen and VWO engineers, they think weird issue we saw re: VWO on four pages was because the script was not added to all pages across site. Adding to all pages in docs-dev for them to test further.
- follow up to this https://github.com/newrelic/docs-website/pull/13312

feat: add vwo to all pages

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/lighttpd-integration.mdx

Ticket : https://issues.newrelic.com/browse/NR-121818
Description: Based on testing analysis, I have modified this document.

Lighttpd : updated doc content based on testing analysis

---

src/content/docs/new-relic-solutions/new-relic-one/workloads/use-workloads.mdx

UI description was wrong, updating it

fix(workloads): adjust for new dashboard UI

---

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-database-page.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-segment-your-data-buckets.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests-legacy.mdx

Fixes include: 
fix(.net config): fixing some precedence wording about config
Adding context about why you'd use NRQL buckets

Assorted fixes: .NET config precedence fix, NRQL bucket fix

---

src/i18n/content/jp/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx

manually deserialize file for release deadline

chore: manually deserialize file 

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx

Based on customer feedback, making link to CLI repo more obvious and adding some links to troubleshooting stuff on forum

fix(lambda): some additions to install

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.234.0.mdx

Browser Agent v1.234.0 Release Notes

Browser Agent v1.234.0 Release Notes

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-14-0.mdx

Add release notes for Kubernetes integration v.3.14.0

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-vpc-lattice-monitoring-integration.mdx
src/nav/infrastructure.yml

AWS VPC Lattice can be monitored as part of our CloudWatch offering, as well as Access Logs on their own. I detailed both in the same doc since they are related to the same feature.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202991511420634

feat: aws lattice docs

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/accounts/original-accounts-billing/product-based-pricing/overview-data-retention-components.mdx
src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-database-page.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-transactions-page.mdx

Work: 
Clarifying some OTel span details based on customer feedback
Adding detail about how aggregated data works for ingest billing purposes

Small fixes June 6

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx

.NET Agent 10.11.0 release

---

src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
src/content/docs/logs/get-started/logging-best-practices.mdx
src/content/docs/logs/get-started/new-relics-log-management-security-privacy.mdx
src/content/docs/logs/logs-context/configure-logs-context-go.mdx
src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
src/content/docs/logs/logs-context/configure-logs-context-php.mdx
src/content/docs/logs/logs-context/configure-logs-context-python.mdx
src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
src/content/docs/logs/logs-context/get-started-logs-context.mdx
src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
src/content/docs/logs/logs-context/logs-in-context.mdx
src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
src/content/docs/logs/logs-context/upgrade-to-automatic-logs-context.mdx
src/install/python/python-agent-whats-next.mdx

feat(tutorials): add links towards log tutorial

---

src/content/docs/accounts/accounts/billing/view-or-change-account-tax-information.mdx

fix(taxes): add some states

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx

The .NET agent team has successfully tested some newer versions of libraries we instrument and want to update our compatibility and support documentation accordingly.

.NET Agent: update supported versions of instrumented libraries

---

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx

Update licenses used by the iOS Mobile App.

docs: Remove unused core dependencies from iOS app

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1425.mdx

docs: infra agent 1.42.5 release notes

docs: infra agent 1.42.5 release notes

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-chatbot-monitoring-integration.mdx
src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-transcribe-monitoring-integration.mdx

[Product Partnerships] Updated AWS Chatbot & Transcribe Docs

---

src/nav/infrastructure.yml

[Product Partnerships] Azure fixes

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/container-instrumentation-infrastructure-monitoring.mdx

* Adding a note explaining how to disable this capability since it's a FAQ in our support channels.

chore: explain how to disable container monitoring (ContainerSample)

---

src/content/docs/distributed-tracing/troubleshooting/infinite-tracing-trace-configuration-conflicts.mdx
src/content/docs/distributed-tracing/troubleshooting/missing-trace-data.mdx

fix(DT): add refs to instrumentation status UI

---

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx
src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/tvos-application-licenses.mdx

Update to latest New Relic tv app licenses.

docs: Update NewRelic tv app licensese

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-sqs-monitoring-fix

NR-97779 - Fixes a missed capitalization in the "ApproximateNumberOfMessagesVisible" query

fix(amazon sqs monitoring): capitalization

---

src/content/docs/mobile-monitoring/new-relic-mobile-cordova-phonegap/get-started-with-cordova-monitoring.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx
src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-plugin-121.mdx
src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-plugin-621.mdx
src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-101.mdx
src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-121.mdx

Updating Flutter, Cordova, Capacitor, and React Native agents.

hybrid mobile releases for jun 9 2023

---

src/content/docs/apm/apm-ui-pages/events/record-deployments.mdx

Browser can now use Deployment Markers

feat: Update record-deployments.mdx

---

src/content/docs/style-guide/images/embed-images.mdx

Replaced png with webp

---

src/content/docs/codestream/how-use-codestream/pull-requests.mdx

Updates docs to reflect that the PR integration now supports Bitbucket PRs.

Add Bitbucket support

---

src/content/docs/agile-handbook/appendices/backlog-review.mdx
src/content/docs/agile-handbook/appendices/project-scoping-cheatsheet.mdx
src/content/docs/agile-handbook/appendices/ticket-best-practices.mdx
src/content/docs/agile-handbook/heroing/managing-the-github-boards.mdx
src/content/docs/agile-handbook/heroing/what-is-a-hero.mdx
src/content/docs/agile-handbook/key-concepts/agile-roles.mdx
src/content/docs/agile-handbook/key-concepts/agile-sprints-profusion-of-terms.mdx
src/content/docs/agile-handbook/key-concepts/key-agile-principles.mdx
src/content/docs/agile-handbook/sprint-mechanics/liaisonships.mdx
src/content/docs/agile-handbook/sprint-mechanics/meetings-and-ceremonies.mdx
src/content/docs/agile-handbook/sprint-mechanics/planning-poker.mdx
src/content/docs/agile-handbook/sprint-mechanics/sprint-workflow-and-jira-boards.mdx

Edits to agile handbook to reflect one-week sprints. 
I've requested three reviewers because I want something different from each of you:
* @homelessbirds : You always ask good questions and help ensure we say "why." Please take a look with a view to that.
* @paperclypse : Would this answer a new hire's questions? Does it describe your and my roles in this new weekly structure?
* @bradleycamacho : Does this accurately reflect how we've done one-week sprints in practice?

One week sprints

---

src/content/whats-new/whats-new-06-13-wpm.md

What's New post for new capability. The youtube video is private until June 13th. 
Links will be available around 9am PST. Publish any time after that. 
Thank you!
---

feat (whats-new): web performance monitoring AM 6/13

---

package.json
scripts/actions/utils/handlers.js
scripts/actions/utils/serialization-helpers.js
src/components/MDXContainer.js
src/components/UserJourneyControls.js
yarn.lock

This component is used by adding props for the previous and next steps like so: 
```
<UserJourneyControls
nextStep={{path: "/", title: "Next Step", body: "do this third"}}
previousStep={{path: "/", title: "Previous step", body: "do this first"}}
/>
```
I added a custom serializer/deserializer so we can get the props translated
https://github.com/newrelic/docs-website/assets/39655074/d5c90068-84a7-4edd-ac58-1088fdc19523

Add user journey buttons

---

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-278.mdx
src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.20.mdx

Adds release notes for synthetics job manager and node-browser-runtime releases on 6/13/2023.

add release notes for synthetics job manager and node-browser-runtime

---

src/content/docs/style-guide/writing-strategies/five-questions-help-write-docs.mdx

Deploy preview: https://docswebsitedevelop-austinschaeferpatch720216.gatsbyjs.io/docs/style-guide/writing-strategies/five-questions-help-write-docs/
* Improve formatting
* Cut less than useful section on other sites

chore(style guide): 5Qs minor copyedits

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/azure-extensions-infrastructure.mdx

* Expanding the tip section to explain that customers can optionally customize the agent default settings via environment variables.

Note about configs for azure vm extension

---

src/components/UserJourneyControls.js

currently this component expects both a previous and next step, this makes either optional.
tested with serializing/deserializing and all was well 🎉

Make user journey steps optional

---

src/content/docs/licenses/license-information/referenced-policies/security-guide.mdx

Reverts newrelic/docs-website#13524

Revert "fix(docs): Add table row, edits from other commit"

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1430.mdx

Infra Agent 1.43.0 Release Notes

Infra Agent 1.43.0 Release Notes

---

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx

docs: Update browser-agent-eol-policy.mdx

---

src/content/docs/style-guide/ui-writing/capitalization.mdx

Fixed for UI writing Update capitalization.mdx

---

src/content/docs/style-guide/ui-writing/numbers-dates-and-times.mdx

We found that teams are putting in the space, and also that our guidelines are contradictory on different pages.

Changes for UI Update numbers-dates-and-times.mdx

---

src/content/docs/logs/ui-data/parsing.mdx

Currently if you search for "GeoIP" you won't find this page.  Added to the section title per suggestion by John Withers.

fix: Add "GeoIP" to relevant section so it's searchable

---

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx

Had to revise these queries once more after some additional validation in our test environment.  They are confirmed to be correct now.

fix: fixed AQM KPI queries again

---

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-chef.mdx

* The previous version of the resource primarily supported infrastructure agents, whereas the updated version now includes support for logs and APM. The document has been revised to direct customers to the actively maintained and supported resource.
* Related jira: https://issues.newrelic.com/browse/NR-125513

fix(chef-install): Updated the content.

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

fix: Remove obsolete JOIN reference

---

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-chef.mdx

* Minor fixes related to the document
* https://issues.newrelic.com/browse/NR-125513

fix(chef-install): minor fixes

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-840.mdx
src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-10-3-0.mdx

* Updated the java agent and node agent release notes to include link to IAST user guide.

Release notes updated to add IAST user guide

---

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-23-0.mdx

Release notes for the 3.23.0 release of the Go APM agent.

06-20 - release notes for the Go APM agent

---

src/content/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx
src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx

Adds current release (3.23.0) to supported version matrix.

feat(go agent): update supported version matrix

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Ordered the list of integrations on the [Alerts and applied intelligence notification integrations](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/) page

chore(Alerts): Ordered alphabetically the list of integrations

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5300.mdx

Release notes for NR's Android app

Release notes for Android App v5.3.0

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-15-0.mdx

update nri-kubernetes release notes

---

src/content/whats-new/2023/06/whats-new-06-22-opslevel-integration.md

* What problems does this PR solve?: 
**Adding whats new post for integration announcement**
**Will link to a quickstart that has not yet published as of June 20th https://github.com/newrelic/newrelic-quickstarts/pull/1847/**

(Pub date: 6/22) WHAT'S NEW: Add opslevel integration post

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1431.mdx

docs: infra agent 1.43.1 release notes

docs: infra agent 1.43.1 release notes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

Add Prometheus exporters info in OHIs using them

---

src/content/whats-new/2023/06/whats-new-06-23-synthetics-horde-ip-changes.md

Publish: 06/23 afternoon
I'm a PMM, this doesn't need PMM review. Thanks!

06/23 afternoon feat(whats-new): synthetics horde ip changes

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx

* Added a note explaining the alternative way to import GPG key on SLES to solve some compatibility issues in older versions.

chore: added SLES note with alternative command

---

src/content/whats-new/2023/06/whats-new-06-26-apm360.md

What's new post for the APM 360 launch
Publish date : 06/26/2023 AM
No PMM review needed
Is it possible to ensure the wistia link embedded works before posting ?

Monday 06/26: Whats new apm360

---

src/data/whats-new-ids.json

daily-release/Jun-26-2023-9_30

daily-release/Jun-26-2023-9_30

---

src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/install-infrastructure-monitoring-agent-windows.mdx

* Adding additional params that are available (and were not documented) for infra-agent windows scripted install.

infra-agent: adding additional params for windows install

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-12.0.mdx

Updates EOL docs and adds Release Notes for .NET Agent 10.12.0

docs: EOL updates and Release Notes for .NET Agent 10.12.0

---

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx

Ruby agent 9.3.0 released and introduced some config changes. This PR updates the config page to match the current version of the agent.

Config updates for Ruby agent release 9.3.0

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

Added a callout to the synthetics private location IP section pointing to upcoming IP address changes.

chore(SynthHordeIPs): Added callout

---

src/content/whats-new/2023/06/whats-new-06-22-opslevel-integration.md

**Please publish update on Tuesday, June 27th **
Added embedded video (which will be made publicly viewable on Tuesday June 27th)

June 27th - Update whats-new-06-22-opslevel-integration.md

---

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80801.mdx

* Add release notes and update EOL table.

Python agent release 8.8.1-PLEASE RELEASE June 26 PM

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-functions-workflow-monitoring-integration.mdx
src/nav/infrastructure.yml

[Product Partnerships] Added Azure Function Workflow

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx

Typo on line 2392:
usted --> used

[chore]Update infrastructure-agent-configuration-settings.mdx

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-workmail-monitoring-integration.mdx
src/nav/infrastructure.yml

[Product Partnerships] Added Amazon WorkMail

---

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-23-1.mdx

Release of go agent, publish by EOD

feat(APM:Go-agent): release 3.23.1

---

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
src/content/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2.mdx
src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
src/content/docs/data-apis/ingest-apis/event-api/introduction-event-api.mdx
src/content/docs/distributed-tracing/concepts/introduction-distributed-tracing.mdx
src/content/docs/logs/log-api/introduction-log-api.mdx
src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx
src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx
src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
src/i18n/translations/en/translation.json
src/nav/apm.yml
src/nav/browser.yml
src/nav/dashboards.yml
src/nav/distributed-tracing.yml
src/nav/logs.yml
src/nav/telemetry-data-platform.yml

NR-125812 - Updated the top 10 intro doc titles to be more descriptive/actionable. (leaving the .yml files alone in this pass)

fix(titles): update t10 intro doc titles

---

src/content/docs/mlops/integrations/openai-integration.mdx

Fixes a popover that was wrapped in code

fix(AI): fix popover

---

src/i18n/translations/en/translation.json

Fixes a styling issue and closes #12047

fix(components): fix capitalization

---

src/content/whats-new/2023/06/Query_enhancements.md

fix(what's new): changed date

---

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-instrumentation.mdx

fix: typos

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration.mdx

Updated EOL date

---

src/content/docs/tutorial-app-performance/guide-to-monitoring-core-web-vitals.mdx
src/content/docs/tutorial-app-performance/performance-benchmarks.mdx

Early edits to performance benchmarks doc
- Reshuffling content
- Plan on adding screenshots

performance benchmarks edits

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-datasync-monitoring-integration.mdx
src/i18n/content/jp/docs/service-level-management/alerts-slm.mdx
src/nav/infrastructure.yml

[Product Partnerships] Added DataSync Entity

---

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-licensing-security.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-260.mdx

Release notes and additional documentation for the Diagnostics CLI 2.6.0 which adds the option to upload results to EU based accounts.

feat: Diagnostics CLI  2.6.0 region selection

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1432.mdx

Release notes for infrastructure agent 1.43.2

docs: infra agent 1.43.2 release notes

---

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-11232.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-11233.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-11235.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-200.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-210.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-220.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-221.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-225.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-230.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-240.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-241.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-242.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-250.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-260.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-261.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-11030.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-11131.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1418.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1419.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1520.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1521.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1522.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1523.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1524.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1625.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1626.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1727.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1828.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1929.mdx

Release notes for Diag CLI 2.6.1.
We found an issue with release 2.6.0 so we are pulling that release. This adds a note to the release notes that 2.6.0 contains an issue and adds new release notes for 2.6.1
Also removed all of the old defunct download links (we only keep the latest version and 1 previous version available for download)

feat: Diag CLI 2.6.1

---

src/content/docs/browser/new-relic-browser/getting-started/browser-apps-index.mdx

Issue where a page was unreachable in the nav as it was trying to redirect to itself.

fix: remove circular redirect

---

src/content/docs/change-tracking/change-tracking-view-analyze.mdx

chore: language identifiers & format code

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/lampy-integration.mdx

Ticket URL: https://issues.newrelic.com/browse/NR-141517
Description: Configuration indentation has to be fixed.

Updated lampy-integration.mdx

---

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/android-application-licenses.mdx

Update the android mobile app 3rd party dependencies licenses to reflect the current version of the app 5.4.1
edit as needed

update 3rd party licenses to reflect current release 5.4.1

---

src/content/docs/browser/browser-integrations/mexn-integration.mdx

Ticket URL: https://issues.newrelic.com/browse/NR-142159
Description: Updted Vue Application along with ReachJS and Angular application in step 4

Updated mexn-integration.mdx

---

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx

Updated icon and parameter in the TV mode section

fix(Dashboards): Updating icon and parameter in the TV mode section

---

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx

Update text, links, add table of endpoints.

Update FedRAMP Compliance Endpoints

---

src/content/docs/data-apis/understand-data/metric-data/query-metric-data-type.mdx

Inspired by https://issues.newrelic.com/browse/NR-140318

Clarify timeslices & dimensional metrics can't be in the same query

---

src/content/whats-new/2023/07/summer_series_WN.md

This is a WN post to promote our NR User Group Meetup Summer Series. It is an experiment to see if this is an effective place to advertise Event information. Please post on 7/19. The time of day is not important for this post, but if we are sharing any product launch announcements on 7/19, please post it before the launch information so that the launch information is ranked higher/more recently in Whats New (in product). We want to make sure that this announcement does not cannibalize views of product launch info.
It is written by Anna Alfano, a PMM - so it does not require PMM review. Thank you!

whats-new: NRUG Summer Series

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1440.mdx

Release notes for infrastructure agent 1.44.0: https://github.com/newrelic/infrastructure-agent/releases/tag/1.44.0

docs: infra agent 1.44.0 release notes

---

src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx

Added details on the recent Migrate to AWS Cloudwatch Metric Streams Button. Please note that this change has to go live on July 14th to make sure it is in sync with the feature availability.

PUBLISH: 7/18 Migrate from polling to AWS metric streams

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

* _What problems does this PR solve?_ :  
* Improved the purpose of webhooks
* Improved the webhook notifier section, so that devs can quickly try out webhook payloads. Many developers (like me) do not understand how to start development against a webhook. This improvement shall help them. 
* Fixed typos.
* _Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.:_ Not needed
* _If your issue relates to an existing GitHub issue, please link to it._ : N/A

Added a section on how to test webhooks without writing code

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-13-0.mdx

Release notes for .NET Agent release 10.13.0.

chore: .NET Agent release 10.13.0

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx

* infrastructure agent 1.44.0 has a fix for known issue, workaround is no longer needed.

fix: SLES signature validation improvements

---

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
src/content/docs/data-apis/understand-data/event-data/default-events-reported-new-relic-products.mdx
src/content/docs/data-apis/understand-data/event-data/events-reported-browser-monitoring.mdx

NR-126911
Work done: 
Add browser details in a collapser below main data retention table

fix(retention): clarify browser

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx

Clarifying the relationship between user type and roles.

fix(user type): rewording 'override' wording

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx

Additions related to making it more clear that the timing for adding/adjusting user's billable aspects can be important

fix(billable users): tip on time zone

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx

see yaml example here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html

fix: invalid yaml example

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-squid.mdx

Fix a typo in opentelemetry-collector-squid docs

chore(typo): fix typo in opentelemetry-collector-squid

---

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx

fix(azure): highlighted line

---

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx

goes along with Tyler's fix here: https://github.com/newrelic/docs-website/pull/13952

fix: browser monitoring is off by default

---

src/nav/alerts-applied-intelligence.yml
src/nav/apm.yml
src/nav/browser.yml
src/nav/logs.yml
src/nav/new-relic-solutions.yml
src/nav/root.yml
src/nav/tutorial-create-alerts.yml

chore(nav): update nav for tutorials

---

src/announcements/docs-q2-survey.mdx

Create a survey banner. Banner will run from today(7/21)-next friday(7/28).

feat(survey): add survey banner

---

src/announcements/docs-q2-survey.mdx

Changes the banner survey link

fix(survey): change survey link

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1450.mdx

Infra Agent 1.45.0 Release Notes

Infra Agent 1.45.0 Release Notes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx

Add an step to configure logs as part of the manual install.

chore: Add log configuration (NR-127868)

---

src/content/docs/mobile-monitoring/new-relic-mobile-ios/installation/spm-installation.mdx
src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-746.mdx
src/i18n/content/kr/docs/mobile-monitoring/new-relic-mobile-ios/installation/spm-installation.mdx

-  address typo in 7.4.0+ Run Script phase instructions

NewRelic iOS Agent 7.4.6b (release notes script fix)

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx

Work done: 
* Historical data export: now only lacks metric timeslice data 
* Add detail about how the email verification works for adding users

Couple small changes July 24

---

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-103.mdx

* adds release notes for [hotfix release 1.0.3](https://github.com/newrelic/newrelic-ndk-agent/releases/tag/1.0.3)
* resolves [NR-144189]( https://issues.newrelic.com/browse/NR-144189)

docs: Adds release notes for Android NDK agent version 1.0.3

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8.5.0.mdx

Release notes for Java Agent 8.5.0. 
If possible, can this be merged the morning of 7/27/2023?

Create  java-agent-8.5.0.mdx - Java agent Release 8.5.0 release notes

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

The cdfPercentage() and getCdfCount() NRQL functions are moving from Beta to GA.  Adding documentation.
https://issues.newrelic.com/browse/NR-145431

feat: Document cdfPercentage and getCdfCount NRQL functions

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/enable-fedramp-endpoints.mdx
src/nav/kubernetes-pixie.yml

Adding docs for enabling FedRAMP endpoints during K8s integration installation.

add fedramp docs for k8s

---

src/components/MDXContainer.js

Reverts newrelic/docs-website#13980

Revert "Add max height on MDX images"

---

src/content/docs/style-guide/formatting/hyperlinks.mdx

Workflow for testing deep links

feat(content): adding deep link docs

---

src/content/whats-new/2023/07/whats-new-7-27-labs-widget-packs.md

Please publish this on July 27 in the morning.
This post doesn't need a review by a PMM as it has already been reviewed and approved by PMM.

"What's new" Widget Packs 

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/postfix-monitoring-integration.mdx

Ticket: https://issues.newrelic.com/browse/NR-144788 
Changes are based on suggestion.

Postfix: Update postfix-monitoring-integration.mdx based on testing

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

NR-145977 - Update domain whitelist for CodeStream client

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80900.mdx

This PR contains the release notes for Python Agent v8.9.0.

Python Agent v8.9.0 release notes

---

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx

Missing space
Anchor was incorrect and cause the navigation pane on the right to display incorrectly. See other sections in the navigation pane such as "Feature details"

Fix migration-from-polling anchor

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.237.0.mdx

Browser Agent v1.237.0 Release Notes

Browser Agent v1.237.0 Release Notes

---

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-103.mdx

fix(release notes): fixed heading

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/zookeeper-monitoring-integration.mdx

Ticket URL: https://issues.newrelic.com/browse/NR-146922
Description: Changes are based on testing inputs.

Updated zookeeper-monitoring-integration.mdx

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-elastictranscoder-monitoring-integration.mdx
src/nav/infrastructure.yml

[Product Partnerships] Added AWS Elastic Transcoder Entity

---

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx

fix(entity): fix link

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/postfix-monitoring-integration.mdx

Changes are based on findings. 
Ticket : https://issues.newrelic.com/browse/NR-146687  
Description: On the top right of the page, there is a section named "On this page". This section is empty. Updated the page so that the content is not empty.

Postfix: Update postfix-monitoring-integration.mdx based on findings
