newrelic/docs-website

scripts/actions/__tests__/__snapshots__/serialize-mdx.test.js.snap, scripts/actions/__tests__/serialize-mdx.test.js, scripts/actions/utils/serialization-helpers.js
- `yarn serialize src/content/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui.mdx -o test`
- `cat test` should look like some HTML
- `yarn deserialize test`
=> use `eval` to parse MDX prop object string

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5032.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5033.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5035.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5036.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5037.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-tvos-release-notes/newrelic-tvos-2030.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-tvos-release-notes/newrelic-tvos-2032.mdx
Updates a few missing release notes for the iOS mobile app
=> docs: Updates release notes in the 5.3.x series

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-statsd.mdx, src/nav/integrations.yml
It includes a guide to configure the OpenTelemetry Collector with the StasD receiver and report the metrics to New Relic.
=> NR-120579: include OpenTelemetry collector StatsD docs

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.237.1.mdx
Browser Agent v1.237.1 Release Notes
=> Browser Agent v1.237.1 Release Notes

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-15-3.mdx
This PR updates the release notes for the Kubernetes integration docs for v3.15.3
=> chore: Add kubernetes release notes 3.15.3

src/content/docs/tutorial-large-logs/get-started-managing-large-logs.mdx, src/nav/tutorial-large-logs.yml
Renames title of logs tutorial series.
=> fix(logs): rename tutorial

src/content/docs/mobile-monitoring/new-relic-mobile-maui-dotnet/monitor-your-net-maui-application.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-121.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-130.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-622mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-623.mdx, src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-102.mdx, src/content/docs/release-notes/mobile-release-notes/net-maui-release-notes/net-maui-agent-002.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-130.mdx
=> hybrid agent release notes, EOL update and .net maui support change

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3085.mdx, src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3091.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-286.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.50.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.29.mdx
Release notes for Synthetics owned services. 
=> Synthetics Release Notes

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-gamelift-monitoring-integration.mdx, src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-workspaces-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Documentation For AWS GameLift & AWS WorkSpace

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/service-characterization-optimize-web-telemetry-guide.mdx
=> remove redirect

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
iOS agent 7.4.6 EOL policy page update
=> iOS agent 7.4.6 EOL policy page update

src/content/docs/new-relic-solutions/get-started/networks.mdx
Based on discussions with Network Engineering and Cloud Integrations teams, agreed that the documentation needs to be updated to resolve escalations.
* * updates IPs that customers need to whitelist
=> Update networks.mdx include IPs for whitelisting

src/content/docs/tutorial-create-alerts/create-an-alert.mdx
Found a deadlink posted externally. wanted to update it with a redirect
=> link redirect

src/content/docs/service-level-management/create-slm.mdx
We added documentation for the cdf functionality in service levels, now that it is open.
=> feat: Add documentation for cdf functionality in service levels

src/content/docs/errors-inbox/errors-inbox.mdx
=> fix(errors inbox): added suggestions

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-81000.mdx
This PR contains the release notes for Python Agent v8.10.0
=> Release notes for Python Agent v8.10.0

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-291.mdx
Gives a description for the private SJM release 291.
Proof we are at version 291: 
Here is the Public release showing 291:
Production: https://onenr.io/0gR70LyyXjo
EU: https://onenr.io/0VRVoObbxja
Here is the Private release showing 291:
https://hub.docker.com/layers/newrelic/synthetics-job-manager/release-291/images/sha256-865db0f682ace06b3601e465c4d23953ba4b22dbb665e81c4951887613c79f44?context=repo
Showing the changes that were added.
Here are the changes between 286 -> 291: …
=> Synthetics Release Notes for SJM Release-291

src/content/docs/style-guide/writing-strategies/guidelines-documenting-ui.mdx, src/nav/style-guide.yml
=> New style guide doc on documenting UI components/page

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx, src/content/docs/browser/new-relic-browser/troubleshooting/missing-data-on-errors-inbox-page.mdx, src/content/docs/browser/single-page-app-monitoring/troubleshooting/nextjs-app-router-links-broken.mdx, src/nav/browser.yml
Adding new browser agent troubleshooting docs.
=> adding browser troublshooting docs

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Adds new MySQL, MongoDB, and NLog versions to the list of verified library versions for the .NET agent.
=> Update .NET agent compatibility docs with new compatible library versions

src/content/docs/kubernetes-pixie/kubecost/get-started-kubecost.mdx, src/nav/kubernetes-pixie.yml
We wanted to add Kubecost integration documentation to the Kubernetes docs so users can monitor their Kubernetes costs along with normal observability with New Relic.
=> feat: Add Kubecost documentation to docs

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/nav/telemetry-data-platform.yml
This PR fixes a few typos from a previous doc page addition
=> Fixing typos in saved views nerdgraph docs

src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-configuration.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes.mdx
This is related to Jira NR-99281.
=> JMX: Clarify wording about Kubernetes

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-get-started-intro.mdx
Add Python to get started page.
=> OpenTelemetry: Update getting started section to include Python

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-131mdx
=> capacitor agent release

src/content/docs/apm/agents/manage-apm-agents/configuration/high-security-mode.mdx
=> chore: add language identifiers to codeblocks

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5040.mdx
Updates to latest release notes for the New Relic iOS mobile app.
=> docs: Add in release notes for version 5.4.0 of the iOS app

src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx, src/content/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent.mdx, src/content/docs/apm/agents/ruby-agent/instrumented-gems/roda-instrumentation.mdx, src/nav/apm.yml
=> Roda instrumentation docs

src/content/whats-new/2023/08/whats-new-08-15-preserved-traces.md
Fixes an image for a whats new post
=> Fix whats new image

scripts/actions/utils/docs-content-tools/i18n-exclusions.yml, src/components/SEO.js, src/content/docs/mdx-test-page.mdx
test page is viewable at `/docs/mdx-test-page`
=> MDX component kitchen sink test page

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-inspector-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added AWS Inspector Entity

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-300.mdx
This is for the Diagnostics CLI version 3.0.0 which is releasing tomorrow, Aug 17.
=> Publish: August 17, 2023 (Morning) Diag CLI 3.0.0

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.238.0.mdx
Browser Agent v1.238.0 Release Notes
=> Publish August 17 with 14269: Browser Agent v1.238.0 Release Notes

src/content/docs/browser/new-relic-browser/performance-quality/browser-monitoring-performance-impact.mdx
Updating the browser agent size stats for the upcoming 1.238.0 release.
=> Publish August 17 with 14286: update browser agent size stats

src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
Fixes spelling errors in the docs.
=> fix: Spelling in monitor-your-react-native-application.mdx

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
=> fix: One more attempt to differentiate ORDER BY and FACET ... ORDER BY

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-sagemaker-monitoring-integration.mdx, src/nav/infrastructure.yml
=>  [Product Partnerships] Updated Amazon Sagemaker

scripts/actions/utils/docs-content-tools/i18n-exclusions.yml, src/i18n/content/jp/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx, src/i18n/content/jp/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx, src/i18n/content/jp/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx, src/i18n/content/jp/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx, src/i18n/content/jp/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx, src/i18n/content/jp/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/i18n/content/jp/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx, src/i18n/content/jp/docs/infrastructure/infrastructure-monitoring/get-started/infrastructure-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx, src/i18n/content/kr/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/i18n/content/kr/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx, src/i18n/content/kr/docs/infrastructure/infrastructure-monitoring/get-started/infrastructure-agent-eol-policy.mdx
Fixes all of the EOL pages that were broken by translation workflow
=> fix: Update i18n EOL pages

src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx
* Adding more details to explain how to check the infra agent versions running in the customer environment and how to identify agents running older versions.
=> fix: details about identifying infra agent versions in the customer environment

src/content/docs/accounts/accounts-billing/account-setup/login-options.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
Add detail about how unique users are determined by user ID.
=> fix(user mgmt): detail about user records

src/content/whats-new/2023/08/whats-new-08-08-automatic-ec2-monitoring-through-nr-agent.md
Some PMM edits to whats-new post . No PMM review needed.
=> fix(whats-new): ec2 edits

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx
=> [Product Partnerships] Update aws-sys-dist.mdx

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-puppet.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-chef.mdx, src/nav/infrastructure.yml
Edits related to: 
* Making it more clear which api key to use (the user key)
* Various improvements as I noticed them
=> Chef/ansible config mgmt: various readability improvements 

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx, src/content/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes.mdx, src/install/mysql/default-install-linux.mdx, src/install/mysql/linux/install-linux.mdx, src/nav/infrastructure.yml
Some edits to OHI docs after talking to SMEs
=> fix(OHI): some SME edits

src/content/docs/accounts/accounts-billing/account-setup/login-options.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
Reverts newrelic/docs-website#14307
=> Revert "fix(user mgmt): detail about user records"

src/content/docs/codestream/how-use-codestream/performance-monitoring.mdx
=> chore: add identifiers to graphql

src/content/docs/new-relic-solutions/get-started/networks.mdx
Updated the doc to use new IP ranges for synthetics private locations. This change will be made later today, do not merge this docs PR until I comment that the change is complete.
=> chore(HordeIPs): Updated IP ranges

src/data/whats-new-ids.json
daily-release/Aug-23-2023-1_17
=> daily-release/Aug-23-2023-1_17

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
=> kubernetes 1.27 is supported pt. 2 

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
=> kubernetes 1.27 is now supported

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration.mdx, src/nav/kubernetes-pixie.yml
Updates the values.yaml file example as many a parameters were using deprecated names.
=> Update values.yaml example in install-fargate-integration.mdx

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-81100.mdx
* Release notes for Python agent v8.11.0
=> Python release 8.11.0 - Please release Aug 23 PM

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-codebuild-monitoring-integration.mdx
=> [Product Partnerships] Updated Amazon Codebuild 

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1460.mdx
Release notes for infra agent 1.46.0
=> docs: infrastructure agent 1.46.0 release notes

src/content/docs/browser/single-page-app-monitoring/troubleshooting/nextjs-app-router-links-broken.mdx
Update to browser agent troubleshooting docs for Next.JS framework.
=> chore: Update browser troubleshooting

src/i18n/nav/jp.json, src/i18n/nav/kr.json
Updated JP and KR nav for new items.
Source Nav from 08/14/2023.
=> Jmira nr patch 3 20230828

src/content/docs/new-relic-solutions/get-started/networks.mdx
Change single quote for backticks.
Using backticks (`) rather than single quotes (') displays new IP ranges in a more suitable way, and preserves the existing style.
=> Use backticks

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-81000.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90000.mdx
=> Add release notes for python 9.0.0 - Please merge Aug 28 PM

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1470.mdx
Release notes for infrastructure agent 1.47.0
=> docs: release notes for infra agent 1.47.0

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.52.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.32.mdx
** adds release notes for a recent deploy
** Not very much, sorry.
* If your issue relates to an existing GitHub issue, please link to it
=> chore: release notes for runtimes deploy on 8/21

src/content/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/version-trends-compare-user-adoption-metrics-performance.mdx
Version trends is being replaced by release versions.
New feature - Release versions, available for mobile. 
https://staging.onenr.io/0M8jqA7Avjl
=> New-Release-Versions

src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx
* Jira ticket: NR-139772
* This updates the documentation for streaming export to include the new compression flag, as well as automatic decompression options.
* The streaming export compression feature is not live yet, and until it is, DO NOT MERGE.
=> [DO NOT MERGE] feat: Add documentation for streaming export compression

src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx
Reverts newrelic/docs-website#14279
=> Revert "[DO NOT MERGE] feat: Add documentation for streaming export compression"

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
https://github.com/newrelic/infrastructure-agent/pull/1717 Sles 15.5 was added.
=> Sles 15.5 was added.

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
=> Network monitoring: Add supported Linux versions

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
Updating configuration options on network monitoring/meraki and changing some formatting to enable collapsible sections.
=> chore: update meraki options and formatting

src/content/docs/licenses/license-information/product-definitions/new-relic-one-pricing-definitions.mdx, src/content/docs/licenses/license-information/usage-plans/new-relic-usage-plan.mdx
Updates to savings plan in usage plan doc.
=> fix(savings plan): updates

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* Added missing references to Oracle Linux next to RHEL (it's the same install process)
=> fix: added missing references to Oracle Linux

src/content/docs/data-apis/understand-data/metric-data/query-apm-metric-timeslice-data-nrql.mdx
```FROM Metric
SELECT metricUnit
WHERE appName = 'YOUR_APP_NAME'
AND metricName = 'METRIC_NAME'
```
Should be:
```
FROM Metric
SELECT unit
WHERE appName = 'YOUR_APP_NAME'
AND metricName = 'METRIC_NAME'
```
=> fix(nrql): fix select statement

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5050.mdx
* Adds latest iOS mobile app release note
=> docs: Add in release note for version 5.5.0 of the NR for iOS app

src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-intro.mdx
=> fix(tutorials): small fixes

src/content/docs/service-level-management/create-slm.mdx
We updated the suggested query for bad events in the success SLI for APM entities. This is just an update to reflect that.
=> fix: update the query for suggested success sli

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5703.mdx
Release notes for new relic android update 5.7.3
=> release note for 5.7.3

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx, src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-251.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-261.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-262.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-310.mdx
- Release notes and new documentation for Diagnostics CLI 3.1.0
- Removed download links for unsupported versions of the CLI
=> feat(diag-cli): Diagnostics CLI 3.1.0

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
updating some small settings tweaks introduced by Kentik yesterday in [kentik/ktranslate #605](https://github.com/kentik/ktranslate/pull/605)
=> chore: update to reflect changes to agent

src/content/docs/accounts/accounts/account-maintenance/query-account-audit-logs-nrauditevent.mdx
This closes GitHub issue 14371
=> Accounts: Add target type query

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration.mdx
=> fix(fargate): Update EKS Fargate documentation

src/content/whats-new/2023/09/whats-new-09-06-ui-enhancements.md
Publish date and time: 09/06 morning or afternoon
I'm a PMM, this does not need PMM review. Thanks!
=> (09/06/2023) Whats new: UI enhancements

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app.mdx, src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
*  All FedRAMP OTLP data is now able to use any port. This PR updates our documentation to reflect that change.
* Followup to this PR: https://github.com/newrelic/docs-website/pull/10975
* N/A
=> docs: update OTLP FedRAMP support

src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-intro.mdx
Removing stray <p> tags that were causing serialization to fail.
=> fix: remove stray p tags

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-860.mdx
Release notes and new documentation for Java agent 8.6.0.
=> chore(java): Java agent release 8.6.0

src/content/docs/logs/ui-data/parsing.mdx
* I had a customer issue around this problem, thought it would be good to tell all customers about
=> Add note about Grok multiline

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration.mdx
* What problems does this PR solve? changes to update docs for Tanzu Nozzle 2.8.0 version.
=> Updated docs for VMware Tanzu Firehose Nozzle integration version 2.8.0.

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates latest verified compatible versions of NLog and ElasticSearch in the .NET Agent compatibility list.
=> chore: Update .NET Agent Compatibility List

src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-intro.mdx, src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-layers.mdx, src/nav/tutorial-understand-k8s.yml
=> feat(tutorials): k8 iteration

src/content/docs/apm/agents/java-agent/troubleshooting/jboss-and-wildfly-incomplete-telemetry.mdx
This provides documentation for troubleshooting using the Java Agent with JBoss EAP and Wildfly
=> add a Jboss troubleshooting doc for classloading errors

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-300.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-320.mdx
Release notes for Diagnostics CLI 3.2.0
=> feat(diag-cli): Diagnostics CLI 3.2.0

.github/workflows/webdriver.yml, scripts/actions/webdriver-desktop.mjs
This PR does 3 things to test why the webdriver tests might be failing:
1. Increases the sleep duration
2. Adds logging to the function to ensure selectors are working
3. Adds ability to manually fire the action in github
=> Webdrive Testing

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-machine-learning-monitor-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Azure Machine Learning Integration 

src/content/docs/apm/agents/ruby-agent/background-jobs/sidekiq-instrumentation.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
Hello from the New Relic Ruby agent dev team!
We are ready to release version 9.5.0 of the Ruby agent and in addition to the auto-generated configuration changes we have authored this content related to our newly added instrumentation for Stripe and our enhanced instrumentation for Sidekiq.
=> Ruby agent 950 updates

src/content/docs/logs/ui-data/lookup-tables-ui.mdx
Ready for review - please merge this at a time that it will get applied to the public docs no earlier than 2023-09-13. 
Previously, when querying NRQL Lookup, an attempt was made to interpret values as numbers, strings, or boolean values.  This update defines the rules behind the parsing of table values.
=> [MERGE 9/13] feat(lookup tables): Add CSV Value Parsing section

src/content/whats-new/2023/09/whats-new-09-13-recommended-dashboards.md
* What problems does this PR solve? ** What's New post for "Recommended Dashboards Personalizations"
=> (Publish on 9/13/2023) What's new:  add recommended dashboards post

src/content/docs/infrastructure/host-integrations/host-integrations-list/sonarqube-monitoring-integration.mdx
**Ticket:** https://issues.newrelic.com/browse/NR-160327
**Description:** Updated the integration document changes for Sonarqube.
=> Updated the Sonarqube integration document.

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
adding new setting introduced by [kentik/ktranslate #606](https://github.com/kentik/ktranslate/pull/606)
=> chore: add details on meraki_config.preferences.hide_uplink_usage setting

.github/auto_assign.yml
Removes writer from auto-assign
=> remove Z.E

src/content/docs/tutorial-app-slow/root-causes.mdx
Optimizes My App is Slow for SEO
=> chore(tutorials): SEO optimization

src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-platform.mdx
=> fix(shortcuts): fix global search key

src/content/docs/tutorial-dd-migration/installing-monitor.mdx, src/content/docs/tutorial-dd-migration/migrating-from-dd.mdx
Fixes a broken button identified in a hero request
=> fix(tutorials): fix broken button

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs/
=> chore: add logging library version numbers

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/newrelic-metrics-adapter.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/deprecation-notice-v1.22-and-lower.mdx, src/content/docs/tutorial-peak-demand/autoscale-your-infra.mdx
Updates the Kubernetes integration documentation to reflect the current version support
Addresses NR-156858
=> feat(kubernetes): Update KSM documentation

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-16-0.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-17-0.mdx
=> feat: Added release notes for Kubernetes integration

src/content/docs/apm/distributed-tracing/trace-api/troubleshooting-missing-trace-api-data.mdx
=> Fixed wrong cutoff time for Trace API span ingestion

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1471.mdx
Release notes for infrastructure agent 1.47.1: https://github.com/newrelic/infrastructure-agent/releases/tag/1.47.1
=> docs: infra agent 1.47.1 release notes

src/content/whats-new/2023/09/whats-new-09-13-recommended-dashboards.md
Reverts newrelic/docs-website#14571
=> (Publish TBA) What's new:  add recommended dashboards post

docs-website.iml, src/content/docs/accounts/accounts/account-maintenance/query-account-audit-logs-nrauditevent.mdx, src/content/docs/apm/agents/c-sdk/instrumentation/instrument-your-app-c-sdk.mdx, src/content/docs/browser/browser-monitoring/page-load-timing-resources/new-relic-cookies-used-browser.mdx, src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx, src/content/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details.mdx, src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-11030.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-11145.mdx, src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1153.mdx, src/content/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx
This updates old attribute dictionary links that we no longer redirect
=> Fix attribute links

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-traffic-server-monitoring-integration.mdx
**Ticket:** https://issues.newrelic.com/browse/NR-162136
**Description:**  Updated the example query event name.
=> Updated apache-traffic-server integration doc's

src/content/docs/apm/agents/java-agent/instrumentation/extension-additional-instrumentation-modules.mdx, src/content/docs/apm/agents/java-agent/instrumentation/ignore-transactions-using-api.mdx, src/content/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx, src/content/docs/apm/agents/java-agent/instrumentation/monitor-deployments-java-agent.mdx, src/content/docs/apm/agents/java-agent/instrumentation/transaction-naming-protocol.mdx
=> chore: add language identifiers to code blocks

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- add Monitor Analysis
- add charts to highlight queue durations and abnormal durations
- demo use of variables
- compatibility with the new Synthetics Job Manager
- general improvements
=> feature: update dashboard example json

src/content/docs/style-guide/writing-docs/docs-translation.mdx
I'm always forgetting what to do with mdx files lol
=> Adding to style guide

.github/workflows/validate-release-notes-json.yml
trying to resolve duplicate checks that get hung up
=> chore: add explicit workflow triggers

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx
This doc had too many callouts. Did a quick pass to reduce callout fatigue.
=> chore(entity): fix callout fatigue

src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx
give the windows-supported section its own unique id
=> [chore] Update default-infrastructure-monitoring-data.mdx

src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-132.mdx
=> react native agent release

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
Added content at the end of "Set up a Slack destination" on the [Alerts and applied intelligence notification integrations](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#slack) page.
=> feat(Alerts): Added content in the "Set up a Slack destination" section

src/nav/kubernetes-pixie.yml
Adds the k8s tutorial to the k8s nav
=> chore(tutorials): add k8s tutorial to k8s doc

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx
Ticket: https://issues.newrelic.com/browse/NR-160141
* What problems does this PR solve? - Android agent release notes
=> (Publish on 09/25/2023) Android agent v7.1.0 release notes

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-cloudsearch-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Amazon CloudSearch Entity

src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-133.mdx
=> added release notes for react native agent

src/content/docs/query-your-data/explore-query-data/dashboards/prebuilt-dashboards.mdx, src/nav/dashboards.yml
The correct screenshot wasn't showing. Made an adjustment to the important statement. Changed the nav.
=> sd-recommended-dashboards

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/android-application-licenses.mdx
No longer using this library, updating accordingly.
=> Remove Segment IO from dependency list

src/i18n/content/jp/docs/synthetics/synthetic-monitoring/getting-started/monitor-limits.mdx
=> Update monitor-limits.mdx in Japanese

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
=> chore(NRQL): Formatting for aparse

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-machine-learning-monitor-integration.mdx
=> [Product Partnerships] Updated Azure Machine Learning Doc

src/content/whats-new/2023/08/whats-new-08-15-preserved-traces.md, src/content/whats-new/2023/08/whats-new-08-23-ei-fingerprinting.md
Screenshot appears to be busted https://docs.newrelic.com/whats-new/2023/08/whats-new-08-15-preserved-traces/
=> chore(WN): Fix preserved traces screenshot

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/view-entity-health-status-find-entities-without-alert-conditions.mdx
* Edit removes some outdated information on exceptions around entity status, and attempts to provide clarification on meaning of the gray status indicator based on questions asked in customer tickets and GTSEs.
=> fix: Removes outdated info, clarifies meaning of gray status

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
updating the 3 primary install pages for network monitoring to align styling and refresh data to current standards around the netmon agent.
* [Set up network flow data monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring/)
* [Set up network syslog monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring/)
* [Set up SNMP data monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/)
=> chore: updating multiple netmon pages

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1472.mdx
Infra Agent 1.47.2 Release Notes
=> Infra Agent 1.47.2 Release Notes

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda.mdx
Refers to: https://github.com/newrelic/docs-website/issues/14635
=> adding a line per gh issue

src/content/docs/tutorial-large-logs/get-started-managing-large-logs.mdx
Not a ton of updates but here's that
=> SEO updates

src/content/docs/apis/lookups-service-api/lookups-service-api.mdx, src/content/docs/logs/ui-data/lookup-tables-ui.mdx, src/content/whats-new/2023/10/whats-new-10-02-nrql-lookups-api.md, src/data/whats-new-ids.json, src/nav/telemetry-data-platform.yml
=> Whats-new Announce the GA of Lookups API

src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/host-name-changes.mdx, src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/incorrect-host-name-reported.mdx, src/nav/infrastructure.yml
* Added new troubleshooting entry for the infra agent based on feedback from support (FAQ).
=> added infra agent troubleshooting for entity name change

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-747.mdx
Adds iOS agent 7.4.7 release notes.
=> iOS agent 7.4.7 release note (Please merge on 10-02-2023)

src/content/docs/tutorial-innovation-and-growth/innovate-with-new-relic.mdx
Fixed a typo on the title of this page: [Improve your code and release quality with New Relic](https://docs.newrelic.com/docs/tutorial-innovation-and-growth/innovate-with-new-relic/)
=> fix(Tutorial): Fixed a typo

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-310.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-321.mdx
These are the release notes for the Diagnostics CLI version 3.2.1
=> feat: Diagnostics CLI 3.2.1 release

src/content/docs/more-integrations/terraform/terraform-modules.mdx, src/content/docs/more-integrations/terraform/terragrunt.mdx
=> Terraform: Fix broken links and edit text

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx
adding a commonly needed example using facet value.
+ fixing a typo above
=> adding facet example

src/content/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs.mdx
This is why we don't love documenting external systems.
Related to NR-138896
=> fix(AWS): Fixed incorrect AWS steps

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/couchbase-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/f5-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/memcached-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nagios-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/powerdns-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/redis/redis-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/varnish-cache-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx
Remove the need of restarting infrastructure agent
=> Remove the need of restarting infrastructure agent

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-296.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-297.mdx
* Adds release notes for the latest released versions of the Synthetics Job Manager
=> chore: Add Job Manager release notes for release 296, 297

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-320.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-322.mdx
These are the release notes for the Diagnostics CLI 3.2.2
=> feat(nrdiag): Diagnostics CLI 3.2.2 Release

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.0.35.mdx
- What problems does this PR solve?
- Adds release notes for the latest release of the node browser runtime
=> Synthetics node-browser-runtime-2.0.35 release notes

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-keyspaces-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Amazon Keyspaces Entity

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
=> Add restrictions for percentiles to HistEx docs

src/content/whats-new/2023/10/whats-new-10-02-incident.md
=> Add video to whats new

src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-agent.mdx, src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
=> Daily release/oct 10  2023 9 36

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-transfer-family-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Amazon Transfer Entity

src/content/docs/apm/agents/manage-apm-agents/app-naming/name-your-application.mdx
Added explanation to clarify UI note
=> feat(apm): added explanation to clarify note in APM UI

src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx
Clarified some copy and added an example
=> feat(apm): clarified action for containerized environment with example

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx
adding more clarity to the apache monitoring integration docs to remove barriers to customers.
* What problems does this PR solve? Reduces confusion about where files are and what command needs ran.
* Added the folder location for the linux configuration file section.
* Clarified what the apache integration binary name is so that there is no confusion when they jump to the respective pages to install the integration. 
=> UPDATE: apache-monitoring-integration.mdx to add clarity

src/i18n/translations/en/translation.json
@rahulbasu-nr I updated this for you!
=> fix(homepage): updated the number of quickstarts

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-298.mdx
Release notes for Synthetics Job Manager release-298
=> [synthetics] add release notes for synthetics job manager release-298

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-299.mdx
* What problems does this PR solve? **Adds release notes for the latest Private SJM release**
=> chore: add release notes for synthetics job manager release-299

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx, src/content/docs/network-performance-monitoring/advanced/ktranslate-container-management.mdx
adding new callout and option for passing an environment variable into the meraki integration for the api key
=> chore: update env var options for meraki

src/data/external-redirects.json
Updates Jira short link for new jira
=> chore(admin): Change jira shortcut link

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-prometheus.mdx
=> Update prometheus install docs

src/content/docs/browser/new-relic-browser/browser-apis/actiontext.mdx, src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx, src/content/docs/browser/new-relic-browser/browser-apis/addrelease.mdx, src/content/docs/browser/new-relic-browser/browser-apis/addtotrace.mdx, src/content/docs/browser/new-relic-browser/browser-apis/createtracer.mdx, src/content/docs/browser/new-relic-browser/browser-apis/end.mdx, src/content/docs/browser/new-relic-browser/browser-apis/finished.mdx, src/content/docs/browser/new-relic-browser/browser-apis/getcontext.mdx, src/content/docs/browser/new-relic-browser/browser-apis/ignore.mdx, src/content/docs/browser/new-relic-browser/browser-apis/interaction.mdx, src/content/docs/browser/new-relic-browser/browser-apis/noticeerror.mdx, src/content/docs/browser/new-relic-browser/browser-apis/onend.mdx, src/content/docs/browser/new-relic-browser/browser-apis/save.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setApplicationVersion.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setattribute.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setcurrentroutename.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setcustomattribute.mdx, src/content/docs/browser/new-relic-browser/browser-apis/seterrorhandler.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setname.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setpageviewname.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setuserid.mdx, src/content/docs/browser/new-relic-browser/browser-apis/start.mdx
This PR updates the callout at the top of the browser api docs pages to include a note about which agent feature is needed for the api to function when using the npm package.
https://issues.newrelic.com/browse/NR-141636
=> feat: Update browser api docs for npm

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-321.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-323.mdx
Release notes for the Diagnostics CLI 3.2.3
=> feat(diagcli): Diagnostics CLI Release 3.2.3

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-104.mdx
* What problems does this PR solve? - Android NDK release notes
=> (Target: 10/19/23) Android NDK release notes 

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
adding a sample of the minimal config required for Meraki API polling
=> chore: add minimal config example

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90101.mdx
This PR adds release notes for Python Agent v9.1.1
=> Release notes for Python Agent v9.1.1

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This backfills a few configuration options we've neglected to document.  It also adds a new configuration option to 11.3.0 of agent `worker_threads.enabled`.
=> chore: Node.js configuration updates

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5071.mdx
Adds latest release notes for the iOS mobile app
=> docs: Add in release notes for iOS mobile app 5.7.1

src/content/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx, src/i18n/content/jp/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx, src/i18n/content/kr/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx
Ticket: https://issues.newrelic.com/browse/NR-160945
=> NR-160945: Update snippet for Magento Business Insights

src/content/docs/logs/forward-logs/vector-output-sink-log-forwarding.mdx
I formated the toml config how [vector does in their docs](https://vector.dev/docs/reference/configuration/), and added the `toml` language identifier -  but that would likely need to be added to our prisma config to work like github shows
=> chore: update code examples

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1480.mdx
Release notes for the infrastructure agent 1.48.0
=> docs: release notes for infra agent 1.48.0

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx, src/content/docs/network-performance-monitoring/troubleshooting/meraki-controller-no-data.mdx, src/content/docs/network-performance-monitoring/troubleshooting/snmp-discovery-no-devices.mdx, src/content/docs/network-performance-monitoring/troubleshooting/snmp-polling-missing-metrics.mdx
updating multiple troubleshooting pages with more accurate information, repairing a few typos, and overhauling the styling on the advanced config page
=> chore: netmon docs updates

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
=> (Hero) Update global-technical-support-offerings.mdx

src/content/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx, src/content/docs/apm/agents/ruby-agent/features/http-client-tracing-ruby.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx, src/content/docs/apm/agents/ruby-agent/instrumented-gems/roda-instrumentation.mdx
=> Updates for Ruby agent release 9.6.0

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
We've tested some recently released versions of our core tech libraries and verified agent compatibility.  This PR updates our documentation to add those versions.
=> .NET agent: update verified compatible versions of core tech libraries

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction.mdx
Updating outdated doc information regarding the stability of OTLP metrics as well as [our support for cumulative](https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/cumulative-metrics/) histograms.
=> Update OTLP support

src/content/docs/data-apis/understand-data/metric-data/metric-data-type.mdx
Make clear what metric types are supported by which metric APIs
=> Update what APIs support what metric types

src/content/docs/apm/agents/java-agent/installation/update-java-agent.mdx, src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
=> Aardvark branch akri

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
A Customer requested for help with integrating NR and Fresh Service. When an alert comes in NR, this integration will create a ticket in FreshService.
=> Add FreshService Notification Integration steps

src/content/docs/apm/agents/c-sdk/get-started/otel_cpp_example.mdx
the yaml had incorrectly indented sections. I cleaned the examples up for readability too
=> fix: yaml syntax, add lang identifiers

src/content/docs/mobile-monitoring/new-relic-mobile-ios/configuration/enable-swift-interaction-traces.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/mobile-sdk-api-guide.mdx
https://new-relic.atlassian.net/browse/NR-176087
=> NR-176087: add list of auto inst class+method, fix link from swift int trace

src/content/docs/errors-inbox/apm-tab.mdx, src/i18n/content/jp/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx, src/i18n/content/jp/docs/apm/agents/java-agent/features/real-time-profiling-java-using-jfr-metrics.mdx, src/i18n/content/kr/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx, src/i18n/content/kr/docs/apm/agents/java-agent/features/real-time-profiling-java-using-jfr-metrics.mdx
=> Daily release/nov 3  2023 8 42

src/content/docs/logs/get-started/new-relics-log-management-security-privacy.mdx
updated the docs to call out our default obfuscation only applies to the message attribute.
=> obfuscation update

src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx, src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx, src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx, src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
@meda123 let me know if this is what you were expecting!
=> fix(errors inbox): added agent version tracking

src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx, src/content/docs/apm/agents/php-agent/advanced-installation/use-newrelic-install-script-php.mdx
=> Fixing customer feedback

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Update the .NET agent compatibility and support documentation to include our new instrumentation for MassTransit, a message queue and service bus library.
=> feature: Add MassTransit to .NET supported library lists

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
I also attempted to update versions where I could find it in the agent release notes
=> chore: moved some messy lists into tables

src/content/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx
**Ticket URL:** https://new-relic.atlassian.net/browse/NR-170865
**Description:** Updated the flex configuration file for Magento Business Insights docs
=> Magento Business Insights - Updated flex config file

src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx
Found some small typos and non-unique ids in this doc
=> chore: Update introduction-new-relic-ionic-capacitor.mdx

src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx
To note to FedRAMP users that the CLI is not supported and to use the manual install instead.
=> [Chore] Added important callout

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5080.mdx
* Add in release note for New Relic for iOS version 5.8.0.
=> Add in release note for New Relic for iOS version 5.8.0.

.github/workflows/auto-assign-reviewer.yml
Updating to get rid of deprecation warning
=> Update auto-assign action

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
=> style(NPM): Alphabetical order table

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1481.mdx
Release notes for infra agent 1.48.1
=> docs: release notes for infra agent 1.48.1

src/content/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx
Made changes to address Data Privacy Framework.
=> chore Update data-privacy-new-relic.mdx

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
=> (fix)[Agent]: Update infrastructure-agent-configuration-settings.mdx

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90102.mdx
=> Add python agent release notes v9.1.2 (Merge Nov 13th PM)

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
small fix for a broken link to a 3rd party site
=> fix: broken link on netflow setup doc

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-19-1.mdx
Release notes for .NET Agent 10.19.1
=> .NET agent 10.19.1 release notes

src/content/docs/change-tracking/change-tracking-webhooks.mdx
This lists the user permissions required for different actions with the change tracking notification settings page. 
=> feat(NR-162979): Add change tracking notification settings permissions

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-14-0-3.mdx
Fast follows for a feature release
=> feat(php): copy edits and structuring to logs in context section

src/content/docs/apm/reports/apm-sla-reports.mdx, src/content/docs/logs/forward-logs/azure-log-forwarding.mdx, src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx, src/install/java/intro.mdx
Some <10 minute fixes from burndown
=> Install java guided install

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-new-relic-gradle-plugin.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-720.mdx
[NR-177332]
* adds Android 7.2.0 release notes
* updates agent plugin configuration page to add `excludePackageInstrumentation()` feature
=> chore: add, update Android docs

src/i18n/nav/jp.json
=> Updated Japanese Nav - Update jp.json

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/add-tracked-headers.mdx, src/data/attribute-dictionary.json, src/nav/mobile-monitoring.yml
https://new-relic.atlassian.net/browse/NR-174411
https://new-relic.atlassian.net/browse/NR-174410
=> Added an article on a new mobile agents api for tracking http headers

src/content/whats-new/2023/11/whats-new-11-11-new-metrics.md
=> cloud host metrics

src/content/docs/apm/agents/python-agent/python-agent-api/addcustomattribute-python-agent-api.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setcustomattribute.mdx, src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
=> chore(agents): Broken/confusing links 

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-28-0.mdx
=> Go Agent release 3.28.0

src/content/docs/query-your-data/explore-query-data/use-charts/chart-types.mdx
Changing some more stuff to remove "preview feature" verbiage.
=> chore(Hero): remove preview feature

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-322.mdx, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-324.mdx
These are the release notes for the Diagnostics CLI version 3.2.4
=> feat: Diagnostics CLI 3.2.4 release notes

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90200.mdx
* Add docs for new package_reporting.enabled setting
* Add docs for v9.2.0 release notes
=> Python release 9.2.0 (Merge Nov 16th 2023 PM)

src/content/docs/accounts/accounts/account-maintenance/account-email-settings.mdx
https://docs.newrelic.com/docs/style-guide/word-choice/usage-dictionary/#black-white
=> chore(accounts): Tweak ID to remove dated term

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
removing redundant links in netmon instrumentation docs
=> chore: remove redundant links to network prereqs

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Update the .NET agent compatibility and support docs to add latest tested and verified compatible versions of some core tech libraries.
=> chore: Update latest tested versions of .NET core tech libraries

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Updating the compatibility of the Java agent with Mule server.
=> chore(Java): updating Mule compatibility

src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_add_custom_parameter.mdx
This is to address customer feedback in NR-79484.
=> PHP agent: Clarify multiple call behavior

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
Announcing .NET agent support for .NET 8 (released last week).
=> Update .NET core agent compatibility/support doc for .NET 8

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
Previous set of commands used to script the export of NRQL data broke on the parsing of the JSON. These new commands have been tested and verified to work.
=> Fix: Script export commands verified and fixed.

src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx, src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-maintenance-monitoring.mdx
=> chore: update private job-manager log levels

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/deprecation-notice-v1.23-and-lower.mdx
=> fix(Kubernetes): Fix typo in heading

scripts/actions/update-attribute-dictionary-json.mjs
adds some more logging to `update-attribute-dictionary-json.mjs` to better cover the error states
also updates the API URL to point at the prod endpoint
=> better logging and response handling, point at prod API

.github/workflows/release.yml
Remove workflow until we have proper access for it to run
=> Remove deployment marker workflow

src/content/docs/tutorial-create-alerts/create-new-relic-alerts.mdx
Fixing grammar error per #15316
=> Fixing grammar typo per #15316

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
default setting is `obfuscated`, not `off`
=> update content per hero request

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx
This PR updates the CSP guidelines for the browser agent.
=> feat: Update browser agent CSP guidelines

.github/workflows/verify-mdx.yml, scripts/README.md
Update script docs and add new script sections
also updates this workflow step name to say `Run verify-mdx` oops
(☞ﾟヮﾟ)☞
=> document new scripts

src/content/docs/distributed-tracing/ui-data/related-trace-entity-signals.mdx
* Users operate under different definitions of upstream and downstream, so we try not to use those terms in the UI or docs. This definition will match the new tooltip we are adding to the UI.
=> Update definition of upstream and downstream

src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
**Jira Ticket:** https://new-relic.atlassian.net/browse/NR-183814
**Description:** I have updated the Nextcloud integration steps in the documentation.
=> Updated the nextcloud integration document.

src/content/docs/apm/agents/java-agent/async-instrumentation/introduction-java-async-instrumentation.mdx
A test of the new Netlify thing
=> style(Java): Removed redundant additional/also netlify test

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
=> chore(nrql): change "initiative" to "initiated"

src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx, src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-platform.mdx, src/content/docs/style-guide/structure/tabs.mdx, src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
Removes all vertical tabs from the site
=> Remove vertical tabs

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx, src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Added interlink between time grouping functions across NRQL docs
Excised broken link about custom incident description in NRQL alert conditions
=> fix(NRQL): customer feedback

src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/network-connection-issues.mdx, src/nav/infrastructure.yml
* Adding concrete network troubleshooting steps when dealing with connectivity issues from the host running the infrastructure agent and New Relic endpoints.
=> feat: infrastructure agent network issues troubleshooting

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
Additional info about GKE support
=> GKE support information update

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
=> feat: Add Monitor Downtime Docs

src/content/docs/infrastructure/amazon-integrations/connect/eks-add-on.mdx
=> AWS EKS add on update

src/content/docs/data-apis/understand-data/metric-data/cumulative-metrics.mdx
Update cumulative documentation to link to client side cardinality limit configuration.
=> Update OTLP limits doc

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Missed @rhetoric101 's suggestion on the previous PR for improving this PHP page.
=> fix(php): update phrasing on compatibility page

src/content/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations.mdx
Remove a few confusing, circular x-refs.
=> fix(ohi): Remove confusing links

src/content/docs/network-performance-monitoring/setup-performance-monitoring/cloud-flow-logs/aws-vpc-flow-log-monitoring.mdx
=> chore(npm): add eu guided install link

src/content/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx
**Ticket :** https://new-relic.atlassian.net/browse/NR-170865
**Description:** Updated Magento Business Insights docs
=> Updated Magento Business Insights docs

src/content/docs/mobile-apps/alerting-new-relic-mobile-apps.mdx
=> feat(mobile): add missing redirect

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-325.mdx
I am adding the Release Notes for the 3.2.5 release of the New Relic Diagnostics CLI.  It is planned to be release on Thursday, December 7th.
=> Release date December 11th: Create diagnostics-cli-325.mdx

src/content/whats-new/2023/12/whats-new-12-12-transaction-traces-ui.md
Publish time: 12/12 morning
I'm a PMM, this does not need PMM review. Thanks!
=> [Publish 12/12 AM] feat(whats new): transaction traces UI

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
=> feat(php): fix table cell formatting and grammer

src/content/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration.mdx
* Updating integration docs based on feedback, default event name is different. 
* Added link to example source.
=> fix: nvidiagpu integration default event name

src/content/whats-new/2023/11/whats-new-11-17-synthetic-locations.md
Clarified the what's new post describing what action will be taken with legacy Horde IPs on January 15, 2024.
=> chore(HordeIPs): Update post

src/content/docs/apm/agents/go-agent/installation/install-new-relic-go.mdx, src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx, src/content/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx, src/content/docs/apm/agents/php-agent/getting-started/introduction-new-relic-php.mdx, src/content/docs/apm/agents/python-agent/getting-started/introduction-new-relic-python.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/ansible-controller-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/couchbase-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/memcached-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nagios-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/redis/redis-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/varnish-cache-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-chef.mdx, src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx, src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/install-infrastructure-monitoring-agent-windows.mdx, src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
=> Cross-product updates: Begin to update guided installation URLs

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-7110.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-7111.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-760.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-800.mdx
=> chore(java): fixing typos in attribute name

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-tutorial.mdx
Un-indented code block to get block to render correctly without image and callout
=> Fix codeblock indent

src/content/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx
=> chore: put long cli command in codeblock

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3.24.0
=> new nri-bundle release

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6000.mdx
* Updates with latest release note for the Mobile app for iOS.
=> Add in 6.0.0 release note for iOS mobile app

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.1.10.mdx
Adds release notes for the recent node-browser-runtime deploy
=> release notes for node-browser runtime deploy 2.1.10

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/monitor-downtimes-disable-monitoring-during-scheduled-maintenance-times.mdx, src/content/whats-new/2023/12/whats-new-12-13-monitor-downtime-updates.md
- What's new post to highlight new monitor downtime capabilities
- Minor documentation tweaks
=> feat(monitorDowntime): Synthetics monitor downtime updates

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
=> feat(support): update wording from delete to rotate

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx, src/content/whats-new/2023/11/whats-new-11-17-synthetic-locations.md, src/content/whats-new/2023/12/whats-new-12-13-monitor-downtime-updates.md
Fixes multiple markdown links that I broke over the last few days in other PRs.
=> fix(links): Fix multiple markdown links

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5901.mdx
Quick release note for our latest android app update release
Edit as needed
=> Release note for android update v5.11.1

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
* What problems does this PR solve? To fix issue #15521
=> Update manage-your-dashboard.mdx to fix issue #15521

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
- Remove bogus feature
- Clearly name saved views
- Consistently refer to Data Plus
=> Clean up Logs features by user type

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
Added a query example to retrieve a monitor entity GUID using the monitor ID
=> chore(monitorIDMapping): Added example query

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Some minor updates to reflect our current testing.
=> Some minor .NET Agent compatibility updates

.github/workflows/check-for-keys.yml
Adds `pull_request_target` to be the action trigger for this workflow to ensure this check runs on forked PRs
=> Update 'check for keys' action

src/content/docs/apm/agents/ruby-agent/background-jobs/monitor-ruby-background-processes.mdx
* Properly format the ruby code
=> Fix: ruby code block

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-15-0-4.mdx
PHP Agent Release Notes for Release 10.15.0.4.
Planned release date: 12/20/23
=> feat(php-agent): Release 10.15.0

src/content/whats-new/2023/12/whats-new-12-21-errorsinbox-mobilegrouping.md
* Text for what's new information related to errors inbox mobile grouping
* Target publish date of 12-21-2023 in the morning
* This is a minor release created by the PMM so it does NOT need review by other PMMs
=> (Publish on 12-21-2023?) What's new: errors inbox mobile grouping

src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx
We should check the rendering on the new procedure; they may not get rendered as coherent steps
=> chore(MS SQL): Clarify permissions steps (NR-167084)

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx, src/content/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring.mdx
some small fixes from today's burndown session
=> fix(Burndown): burndown fixes

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-iot-twinmaker-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added AWS IOT Twinmaker

src/content/docs/apm/agents/ruby-agent/attributes/enable-disable-attributes-ruby.mdx, src/content/docs/apm/agents/ruby-agent/attributes/ruby-attribute-examples.mdx, src/content/docs/apm/agents/ruby-agent/configuration/connect-hosts-your-account.mdx, src/content/docs/apm/agents/ruby-agent/configuration/custom-ssl-certificates-ruby.mdx, src/content/docs/apm/agents/ruby-agent/features/http-client-tracing-ruby.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/migration-7x-guide.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/new-relics-github-repository.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/content/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent.mdx, src/content/docs/apm/agents/ruby-agent/installation/uninstall-ruby-agent.mdx, src/content/docs/apm/agents/ruby-agent/instrumented-gems/rack-middlewares.mdx
During a documentation audit with @homelessbirds last year, [we identified](https://docs.google.com/spreadsheets/d/1waNtEyvfsYrX74WQaMK7Inry5weUzNkWvzKnwHLLWE0/edit#gid=0) some docs that needed updates. 
Changes to some of the outdated docs are included in this PR. 
Relates to https://github.com/newrelic/newrelic-ruby-agent/issues/2235
=> chore(ruby): Update outdated documentation

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
=> Added Autopilot support to GKE compatibility info

src/content/docs/tutorial-create-alerts/create-new-relic-alerts.mdx
Changed the positioning of the image in the doc to be less confusing
=> (chore)Alerts: update image positioning

src/content/docs/data-apis/convert-to-metrics/analyze-monitor-data-trends-metrics.mdx
=> (chore): Feedback from burndown

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-310.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-315.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-321.mdx
Attempting to consolidate job manager and fix the non-updating overview list
=> fix(Hero): fixing job manager release note submissions

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.12.mdx
Adds release notes for the latest node api runtime deploy!
Adds needed release notes :)
=> chore: add release notes for node api runtime 1.2.12

src/content/docs/style-guide/writing-docs/processes-procedures/create-release-notes.mdx
Updating release notes doc to prevent left-nav issues from mismatched subject fields across release notes series
=> (chore)Style guide: updating release notes section

.github/workflows/check-for-keys.yml, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.12.mdx
=> Daily release/dec 28  2023 11 59

src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
This PR updates the latest PostgreSQL supported version to v16. The latest version is used in [integration tests](https://github.com/newrelic/nri-postgresql/pull/146) and Core Integration internal canaries.
=> feat: update last supported PostgreSQL version

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Update mongodb-monitoring-integration supported versions
Updates the supported versions of the integration
=> Update mongodb-monitoring-integration supported versions

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
=> chore: add language identifier

src/content/docs/alerts-applied-intelligence/applied-intelligence/anomaly-detection/custom-anomalies.mdx
Hero request to update typo. 
Did a sweep for this typo and did not find other occurrences.
=> chore(typo): update 'anomoly' typo

src/content/docs/apm/apm-ui-pages/monitoring/external-services/external-services-setup.mdx, src/content/docs/data-apis/custom-data/aws-privatelink.mdx, src/content/docs/distributed-tracing/ui-data/trace-details.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx, src/content/docs/network-performance-monitoring/advanced/snmp-profiles.mdx, src/content/docs/network-performance-monitoring/get-started/network-monitoring-best-practices.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/meraki-api-polling.mdx, src/content/docs/tutorial-create-alerts/create-an-alert.mdx, src/content/docs/tutorial-dd-migration/installing-monitor.mdx, src/content/docs/tutorial-troubleshoot-infra-hosts/diagnose-app-infra-data.mdx
This work updates the tabs components for any tab ids that are 1) duplicative; or 2) use only numerals for IDs.
=> Updating duplicative tabs IDs and naming numbered tabs IDs

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-backup-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added Amazon backup

src/content/docs/new-relic-solutions/get-started/networks.mdx
Per feedback ticket, added a contributor note ahead of any section that lists endpoints. Need to get approval on whether it should appear before every instance of endpoint lists, or just the first time endpoints appear in doc.
=> chore(add note): Added contributor note 

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx, src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
=> Fix: add tested versions back to Log in Context (.NET) docs

src/content/whats-new/2024/02/whats-new-02-05-nrql-limit-increases.md
This is the advance announcement for query result limit increase which will go live on Feb 5. This is cleared to be merged early next week, the week of Jan 8.
This supersedes [this similar PR](https://github.com/newrelic/docs-website/pull/15072) which can be closed.
=> [PUBLISH - 1/8] What's New post for limit increase

src/content/docs/apm/agents/python-agent/python-agent-api/getbrowsertimingfooter-python-agent-api.mdx, src/content/docs/apm/agents/python-agent/python-agent-api/getbrowsertimingheader-python-agent-api.mdx, src/content/docs/apm/agents/python-agent/supported-features/browser-monitoring-python-agent.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90400.mdx
* Add Python Agent v9.4.0 release notes
* Update Python Agent API documentation for new versions
=> Python Agent Release v9.4.0

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.15.mdx
Adds release notes for `Synthetics Node API Runtime` after a release that happened today. 
=> feat: Release notes for Synthetics 1/8

src/content/docs/new-relic-solutions/solve-common-issues/troubleshooting/metric-grouping-issues.mdx
This PR adds a new feature that can be used to help customers to prevent MGI
Its related to this task  [NR-174308](https://new-relic.atlassian.net/browse/NR-174308), item # 1
The feature is now available for all customers.
=> feat: add one more feature that helps to prevent MGI

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Mention the percona exporter along with the Bitnami one since our docs suggest people use the percona exporter standalone.
Thanks @adittoNR
=> [chore] Update mongodb-monitoring-integration-new.mdx

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
Updated Chrome version from 112 to 117.
=> feat(ChromeVersion): Updated to 117

src/content/docs/logs/ui-data/timestamp-support.mdx
=> chore - small grammar improvements

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations-large-kubernetes-environments.mdx
=> Remove POMI callout

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-iot-twinmaker-integration.mdx
=> [Product Partnerships] Updated The AWS IoT Twinmaker Document

src/content/whats-new/2024/01/whats-new-01-09-nrql-limit-increases.md
=> fix(whatsNew): change release date, move to January folder

src/content/docs/infrastructure/elastic-container-service-integration/introduction-amazon-ecs-integration.mdx
Adds a current missing requirement 
=> Adding a ECS requirement

package.json, yarn.lock
includes the fix for tabs not linking on MDX pages
=> bump theme to 9.2.3

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/lookups.mdx
=> [Docathon] Content refresh/Updating and adding examples for lookups

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nested-aggregation-make-ordered-computations-single-query.mdx
This PR adds another example query to the nested aggregation public docs.
=> [docathon] add examples for nested aggregation

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-cluster-explorer.mdx
Added new entities to group, metrics to sort by and attributes to group by.
=> Add missing information in the K8s navigator

src/content/docs/network-performance-monitoring/troubleshooting/understanding-snmp-utilization-calculations.mdx
clarifications and adding a new calculation for interface throughput
=> chore: update snmp calculation docs

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/add-tracked-headers.mdx, src/content/docs/tutorial-create-alerts/create-an-alert.mdx
If the TabPageItems aren't in the same order as the TabsBarItems then the animation doesn't work properly. This is to fix a couple that we know of but ultimately we'll need to code against this in tabs component itself by sorting the children
=> \Make tab page order match bar item order

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Adds documentation for the `convert()` function to the NRQL functions reference.
=> [Do not merge until mid-Jan] feat: Document convert in NRQL functions

src/content/docs/network-performance-monitoring/advanced/ktranslate-container-management.mdx, src/content/docs/network-performance-monitoring/get-started/network-monitoring-best-practices.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx, src/content/docs/network-performance-monitoring/troubleshooting/network-flow-missing-data.mdx
multiple updates to cover new options enabled in kentik/ktranslate#647
=> chore: update netflow docs

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Added blob, encode, and decode to the syntax doc
Fixing branch conflicts from https://github.com/newrelic/docs-website/pull/15346
@maddie-boisvert
=> feat(NRQL): add blob, decode, encode

src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx
https://github.com/newrelic/docs-website/issues/15826
=> Replacing nginx with mssql

src/content/docs/browser/new-relic-browser/page-load-timing-resources/page-load-timing-process.mdx
Fixing a broken link reported in the help channel
=> (fix)Hero: fixing broken link

src/content/docs/vulnerability-management/integrations/aws.mdx
Add <Steps> component to this doc to smooth out the instructions. This is for NR-179359.
=> Vulnerability management: Add step components

src/content/whats-new/2024/01/whats-new-01-22-deprecating-ic-limits.md
- This What's New post should be published as soon as possible, ideally today, latest tomorrow. The time window is less relevant than urgency in posting.
- It does not need review by a product marketing manager, because it was submitted by a PMM.
=> "What's New" deprecating IC limits post

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-16.0.5.mdx
These are the release notes for an upcoming PHP release.
We would like them reviewed but **please wait to merge and push these changes to the docs website**.  We will let you know when we are ready for these changes to go live.
=> chore(PHP): Adds release notes for 10.16.0.5 release

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx, src/content/docs/apm/agents/php-agent/frameworks-libraries/wordpress-specific-functionality.mdx
New Relic PHP Agent v10.16 adds new configuration settings that help fine tune what data is reported for WordPress application. This PR documents those new settings and how to use them.
=> feat(php): add `newrelic.framework.wordpress.hooks.options` description

src/content/docs/apm/agents/net-agent/custom-instrumentation/add-detail-transactions-xml-net.mdx
=> chore: correct indentation

src/content/docs/style-guide/writing-strategies/contribute-to-site.mdx
Readding content for adding new doc. I think the original content is a little obvious, so maybe it could be rewritten to highlight the relevant step (#2) which tells people where to find content in our directory. I'll defer to the reviewer tho
=> readding content to style guide

src/content/whats-new/2024/01/whats-new-01-25-codestream.md
No PMM Review required
What's new post for unified identity for codestream that lets users login using NR credentials
=> feat(whats-new): codestream unified identity

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-app-launch-time-android-apps.mdx
Reverts newrelic/docs-website#15938
=> Revert "fix(Mobile monitoring): Fixed a wrong query"

src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/updated-azure-monitor-behaviour
Release notes for upcoming change on the Azure Monitor integration.
=> Create updated-azure-monitor-behaviour release notes

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-29-1.mdx
=> Go Agent v3.29.1 release

src/content/whats-new/2024/01/whats-new-01-18-nrql-q3-functions.md
=> Fix a typo

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-333.mdx
Updates release notes for Synthetics Job Manager release-333 from 1/29/2024
=> [Synthetics Job Manager] chore(release notes): update release notes for synthetics-job-manager release-333

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5130.mdx
=> Release notes for New Relic Android v5.13.0

src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx, src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-890.mdx
…ate.
Please release as soon as possible. Thanks!
=> Java agent 8 9 0 release

src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-config.mdx
Clarifying behaviour of COLLECTION_LIST and COLLECTION_IGNORE_DATABASE_LIST
=> fix(postgresql): clarify collection_list

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx, src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
Updates the private Docker Synthetics Job Manager docs to include environment variables that are available to users. Also updates the recommended resource request/limit values for private Kubernetes SJM.
=> chore(docs): add synthetics job manager env var documentation and update kubernetes resource recommendations

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates verified compatible versions of several libraries instrumented by the .NET Agent.
=> chore: Update .NET Agent compatibility requirements.

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx, src/content/docs/network-performance-monitoring/advanced/snmp-profiles.mdx
updating to add a new config option
=> chore: add new config option

src/content/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-logs/infrastructure-agent-logging-behavior.mdx
Infrastructure agent integration log management, filtering integrations logs.
=> Infrastructure agent integration log management, filtering integrations

src/content/docs/synthetics/synthetic-monitoring/using-monitors/alerts-synthetic-monitoring.mdx
- Updated alert URLs
- Removed unnecessary callout
- Updated alert creation steps
- Added references to Monitor Downtime and Muting Rules for muting an alert
- Added a callout for the upcoming muted monitor status EOL
=> fix(SyntheticsAlerts): Multiple updates

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-721.mdx
* What problems does this PR solve? - Release notes for a minor version android agent release
=> Target 2/5/24 - [NR-215814] android agent v7.2.1 release notes

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
A couple of the updates for NR-175214 & NR-175229 (updating NRQL result limits from 2k to 5k) got lost in the merge
https://new-relic.atlassian.net/browse/NR-175214
https://new-relic.atlassian.net/browse/NR-175229
=> feat: Remaining updates for NRQL result limit change to 5k

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6010.mdx
Add in latest iOS release notes for version 6.1.0
=> docs: 6.1.0 - Adds in latest ios release notes

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-337.mdx
Updates Synthetics Job Manager release notes for release-337
=> chore(docs): add release notes for synthetics job manager release-337

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1485.mdx
add release notes for infra agent 1.48.5
=> docs: add release notes for infra agent 1.48.5

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.2.22
* release notes for synthetics node browser runtime!
=> chore(synthetics): Update node-browser-runtime release notes (v2.2.22)

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-workspaces-web-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added AWS Workspaces Web

src/content/docs/change-tracking/change-tracking-webhooks.mdx, src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx, src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx
=> chore: add language identifiers and cleanup

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
Fixed typo: 
"You can't increased this limit" to "You can't increase this limit."
=> CHORE: Fix Typo Update incident-workflows.mdx

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
- Added NrMTDConsumption details
- Indicated that NrDailyUsage may not match the usage UI or NrMTDConsumption events
- Replaced some examples so they use NrMTDConsumption
=> fix(SynthUsage): Added clarifications

src/content/docs/nrql/using-nrql/subquery-joins.mdx
Addressing a customer feedback request about adding an example of multiple joins in one subquery.
=> adding example of two joins in a subqery

src/nav/nrql.yml
Curious for your thoughts on this @jeff-colucci !
=> style(nav): Surface NRQL getting started at L1 lvl

.github/workflows/trigger-i18n-merge.yml
Accidentally made up a script name 😅
=> Use actual name of script

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-certificate-manager-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added AWS Certificate Manager

src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/queries-nrql_screenshot-full_nrql-alert-conditions.mdx, src/content/docs/apis/intro-apis/new-relic-api-keys.mdx, src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/apm/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs.mdx, src/content/docs/apm/agents/php-agent/troubleshooting/using-phpinfo-verify-php.mdx, src/content/docs/apm/agents/python-agent/getting-started/introduction-new-relic-python.mdx, src/content/docs/browser/browser-integrations/nuxt-js-integration.mdx, src/content/docs/change-tracking/ci-cd/change-tracking-jenkins.mdx, src/content/docs/distributed-tracing/concepts/introduction-distributed-tracing.mdx, src/content/docs/infrastructure/elastic-container-service-integration/introduction-amazon-ecs-integration.mdx, src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/container-infrastructure-monitoring.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/installation/reduce-ingest.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx, src/content/docs/logs/forward-logs/aws-lambda-sending-logs-s3.mdx, src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx, src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx, src/content/docs/logs/ui-data/query-syntax-logs.mdx, src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-get-started-intro.mdx, src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx, src/content/docs/more-integrations/terraform/terragrunt.mdx, src/content/docs/network-performance-monitoring/get-started/network-monitoring-best-practices.mdx, src/content/docs/new-relic-solutions/get-started/networks.mdx, src/content/docs/new-relic-solutions/tutorial-landing-page.mdx, src/content/docs/nrql/get-started/charts-and-dashboards-with-nrql.mdx, src/content/docs/security/security-privacy/information-security/security-bulletins.mdx, src/content/docs/tutorial-improve-app-performance/root-causes.mdx
Update KR human translation metadata.
**Removed:** 
1. docs/apm/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs/
2. docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose/
3. docs/new-relic-solutions/get-started/networks/
4. docs/distributed-tracing/concepts/introduction-distributed-tracing/
5. docs/logs/logs-context/java-configure-logs-context-all/
6. docs/infrastructure/install-infrastructure-agent/linux-installation/container-infrastructure-monitoring/
7. docs/logs/ui-data/query-syntax-logs/
8. docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/
9. docs/logs/forward-logs/aws-lambda-sending-logs-s3/
10. docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model/
11. …
=> Update KR human translation metadata

package.json
=> Update script path

src/content/docs/new-relic-solutions/get-started/glossary.mdx, src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-platform.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
=> Dashboards: Add permalink pruning routine.

scripts/actions/trigger-i18n-merge.js
=> Use opensource bot token instead of github

src/content/docs/logs/logs-context/configure-logs-context-go.mdx
Feature: Go agent release of new integration package
This code has shipped, would prefer to release this asap
=> feat(go-agent): support for standard library structured logging

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
These new text changes reflect a program update to the Observability for good offering.
=> Update to the O4G offering docs page

src/content/docs/accounts/accounts-billing/account-setup/student-program.mdx, src/nav/accounts.yml
=> Accounts: Add student program

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1491.mdx
Infra Agent 1.49.1 Release Notes
=> Infra Agent 1.49.1 Release Notes

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
We no longer use Techsoup as a Validation partner for our program, hence the removal needed.
=> Spelling error correction - removed Techsoup

src/components/FeedbackModal/FeedbackModal.js
This removes the free text option from the survey and increases the chance of it appearing from 1/20 to 1/10
=> Remove freetext and increase chance to show

.github/workflows/trigger-i18n-merge.yml, scripts/actions/trigger-i18n-merge.js
the github response is coming back undefined. can't test with the bot token so trying the github token (working in other workflows)
=> Try github token for api call

src/content/docs/iast/introduction.mdx
https://github.com/newrelic/docs-website/pull/16211 due to some cache issues, recreating this PR to make simple updates rather than bug eng for a cache clear
=> chore: update version numbers

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-17-0-7.mdx
These are the release notes for an upcoming PHP release. We will let you know once these changes are ready to go live. This PR is co-dependent on PR #16224. Thanks!
=> PUBLISH: TBDchore(PHP): Adds release notes for 10.17.0.7 release

src/content/docs/infrastructure/elastic-container-service-integration/install-ecs-integration.mdx
https://github.com/newrelic/docs-website/issues/16236 Per this issue
=> Updating link about AWS sidecar

src/content/docs/new-relic-partnerships/partner-integration-guide/getting-started/partners-contact-new-relic.mdx
=> fix(partners): Remove old support email alias

src/components/EsNav.js, src/components/PtNav.js, src/components/RootNavigation.js, src/i18n/nav/es.json, src/i18n/nav/pt.json
This includes temp nav json, you can check out the first nav item under 'start here' and see it change in each language
=> Add pt and es navs

src/content/docs/apm/apm-ui-pages/monitoring/view-slow-query-details.mdx
=> feat(APM): Clarified slow response time is in milliseconds

src/content/docs/infrastructure/infrastructure-alerts/infrastructure-alert-conditions/create-infrastructure-host-not-reporting-condition.mdx
PR needed a cache clear, but it was easier to make a new PR instead: https://github.com/newrelic/docs-website/pull/16259
=> feat(infra): add anchor tag, update language for clarity

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90700.mdx
=> Add python release notes for v9.7.0 -- merge Feb 22 PM

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
=> Upgrade GKE Autopilot instructions

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-network-firewall-monitoring-integration.mdx, src/nav/infrastructure.yml
=> [Product Partnerships] Added AWS Network Firewall

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
Document v1.0.0 configuration and set up instructions for the security agent
=> feat(apm):go security agent v1.0.0 documentation

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app.mdx
Per customer feedback, adjusting language for clarity
=> Update vague language in otel doc

src/install/config/ibm-mq.yaml, src/install/ibm-mq/appInfo.mdx, src/install/ibm-mq/default-install.mdx, src/install/ibm-mq/default-requirements.mdx, src/install/ibm-mq/find-data.mdx, src/install/ibm-mq/install-infra.mdx, src/install/ibm-mq/intro.mdx, src/install/ibm-mq/linux/install-apt.mdx, src/install/ibm-mq/linux/install-linux.mdx, src/install/ibm-mq/linux/install-tarball.mdx, src/install/ibm-mq/linux/install-yum.mdx, src/install/ibm-mq/linux/install-zypper.mdx, src/install/ibm-mq/linux/requirements-linux.mdx, src/install/ibm-mq/linux/requirements-tarball.mdx, src/install/ibm-mq/whatsNext.mdx, src/install/ibm-mq/windows/install-msi.mdx, src/install/ibm-mq/windows/install-windows.mdx, src/install/ibm-mq/windows/requirements-windows.mdx, src/nav/infrastructure.yml
Added the branching doc structure for this page: [IBM MQ monitoring integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration).
This is the ticket: NR-217451
This PR comes from this [PR: 16140](https://github.com/newrelic/docs-website/pull/16140)
=> feat(OHI IBM MQ): Added branching doc structure

src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx
Related to NR-184668 customer feedback.
Confirmed with Browser team.
=> fix(Browser): Updated JavaScript and Ajax frequency

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide.mdx
NR-191347
Removed at request of one of our solutions architects
=> feat(OMA): Removed data quality collapser

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.2.33.mdx
* Synthetics Node Browser Runtime 2.2.33 release notes
=> Synthetics Node Browser Runtime 2.2.33 release notes

.github/workflows/attribute-dictionary-comment.yml, .github/workflows/check-images.yml, .github/workflows/check-translations-and-deserialize.yml, .github/workflows/trigger-i18n-merge.yml, .github/workflows/update-attribute-dictionary-json.yml, .github/workflows/update-whats-new-ids.yml, src/data/attribute-dictionary.json
replaces token associated with old opensource bot user
=> replace token name used in action workflows

.github/workflows/attribute-dictionary-comment.yml, .github/workflows/check-images.yml, .github/workflows/check-translations-and-deserialize.yml, .github/workflows/trigger-i18n-merge.yml, .github/workflows/update-attribute-dictionary-json.yml, .github/workflows/update-whats-new-ids.yml
Reverts newrelic/docs-website#16338
=> Revert "replace token name used in action workflows"

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/add-on-billing.mdx
This suggestion was from a writing review.
=> Accounts: Alphabetize add-ons

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-316.mdx
* Adds release notes for the latest version (3.1.6) of the Synthetics Containerized Private Minion
=> chore(synthetics): Synthetics Containerized Private Minion Release Notes v3.1.6

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-317.mdx
* Release notes for Synthetics Minion 3.1.7
=> Synthetics Minion 3.1.7 release notes

src/content/docs/new-relic-solutions/get-started/glossary.mdx
=> Update "signal" description

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-720.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-721.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-730.mdx
* What problems does this PR solve? - Android v7.3.0 release notes and few fixes
=> [NR-180970] Android release notes v7.3.0 and few fixes

src/content/docs/errors-inbox/otel-tab.mdx
Removes extra apostrophe in Otel error docs
=> Remove extra apostrophe

src/i18n/content/es/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx, src/i18n/content/pt/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
Small edit to Spanish and Portuguese title.
=> Jmira nr patch 3 20240304

src/install/java/license.mdx
=> Clarify which "copy key" button

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-341.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.39.mdx, src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.40.0.mdx
Updates release notes for latest public releases of Synthetics Job Manager, Ping Runtime, and Node Api Runtime.
=> Synthetics: release notes for SJM, ping-runtime, & node-api-runtime

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app.mdx
I needed an anchor on the table so I could link directly to it from another page.
=> chore(OTEL): Add table header/anchor

src/content/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument.mdx
We're documenting a specific tech stack where the agent doesn't work.
=> chore(java): adding incompatibility note

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-network-firewall-monitoring-integration.mdx
=> [Product Partnerships] Updated AWS Network Monitoring Document

src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/migration-guide.mdx
metricName should not be in the list as is reported by Dimensional Metrics.
=> Fixing error in the removed metadata section

src/nav/infrastructure.yml
=> Remove subcategories from OHI nav

src/content/docs/codestream/start-here/install-codestream.mdx
Support for VS 2019 is going away.
=> Remove support for VS 2019

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.54.mdx
We pushed up a new node api runtime version: https://hub.docker.com/r/newrelic/synthetics-node-api-runtime/tags
These are the release notes for that version
Here is the change log on github for the release: https://source.datanerd.us/synthetics/synthetics-node-api-runtime/compare/release-134...release-150
=> feat: Update release notes.

src/data/whats-new-ids.json
This is the follow-up to the early afternoon merge that will generate "What's new" IDs. We have some other PRs that were included.
=> Daily release/03/11/2024/noon 2

src/@newrelic/gatsby-theme-newrelic/components/Logo.js
before:<img width="327" alt="Screenshot 2024-03-13 at 11 40 38 AM" src="https://github.com/newrelic/docs-website/assets/39655074/653be620-33b1-4586-8dc3-d2f59afe55c3">
after: <img width="327" alt="Screenshot 2024-03-13 at 11 39 04 AM" src="https://github.com/newrelic/docs-website/assets/39655074/d97a1336-4427-4db6-ad5f-d15ae6cbfda2">
=> Remove hexagon background in docs logo

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* Updating supported SUSE versions based on latest supported version by the manufacturer (https://endoflife.date/sles)
=> chore(infra-agent): updating supported SUSE/SLES versions

src/pages/attribute-dictionary.js
before:<img width="413" alt="Screenshot 2024-03-13 at 3 24 42 PM" src="https://github.com/newrelic/docs-website/assets/39655074/53b04006-1164-4dd6-87cb-f6d0bde9a48e">
after:<img width="410" alt="Screenshot 2024-03-13 at 3 24 48 PM" src="https://github.com/newrelic/docs-website/assets/39655074/e6751b4c-3aab-4b8a-80f7-2bd183e44c5d">
=> Remove code tag on event names

src/layouts/MainLayout.js, src/pages/attribute-dictionary.js
Button Update:
Attribute Dictionary Update:
=> fix: update colors

src/i18n/content/pt/docs/accounts/install-new-relic/partner-based-installation/rightscale-users-new-relic.mdx
=> Typo fix in PT

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
fix spelling of "integrations"
=> [chore] Update infrastructure-agent-configuration-settings.mdx

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5160.mdx
=> (Publish 18 March 2024) Release notes for v5.16.0 of New Relic for Android

src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
=> Logs: Add example of multiple log sources to Fluent Bit code snippet

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
This updates our Synthetics docs to reflect the new modules added to the both the Synthetics Node API Runtime and Synthetics Node Browser Runtime. 
This PR is part of the work in this ticket - https://new-relic.atlassian.net/browse/NR-221425
Just updating our docs to reflect changes made in these 2 PRs - 
- https://source.datanerd.us/synthetics/synthetics-node-api-runtime/pull/178
- https://source.datanerd.us/synthetics/synthetics-node-browser-runtime/pull/421
=> chore: updating modules list to reflect the new modules added

src/content/whats-new/2024/03/whats-new-03-18-lambdacommunityplus.md
Add a what's new post for Lambda extension which is in community plus tag and maintained and improved by New Relic engineers
=> (Publish 18 March 2024) lambdacommunityplus

src/content/docs/logs/get-started/live-archives.mdx
Add section for how to search via Nerdgraph API
=> live_archives_api_search

src/@newrelic/gatsby-theme-newrelic/components/NavItem.js, src/@newrelic/gatsby-theme-newrelic/components/NavLink.js, src/components/Navigation.js
current changes:
- bolding on current doc only
- selected category and all its children white/font color
- non selected items 70% opacity
- replaced blue colors with gray
- hover color
=> Nav design updates

src/content/docs/release-notes/docs-release-notes/docs-3-15-2024.mdx, src/content/docs/release-notes/docs-release-notes/index.mdx, src/content/docs/release-notes/index.mdx
=> Docs release notes

src/content/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration.mdx
=> fix(NVIDIA): updating based on hero request

src/content/docs/more-integrations/open-source-telemetry-integrations/statsd/statsd-monitoring-integration.mdx
* Adding troubleshooting hints for the statsD integration (feedback from support escalation NR-218398).
=> statsD integration troubleshooting docs

src/content/docs/release-notes/docs-release-notes/docs-3-15-2024.mdx, src/content/docs/release-notes/docs-release-notes/index.mdx, src/content/docs/release-notes/index.mdx
=> Daily release/mar 18  2024 7 08

src/content/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration.mdx
Ticket: https://new-relic.atlassian.net/browse/NR-249093
Description: Updated the Temporal integration document.
=> Updated the temporal integration docs.

src/content/docs/apm/agents/net-agent/net-agent-api/seterrorgroupcallback-net-agent-api.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/missing-net-async-metrics.mdx, src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-errors-inbox-page.mdx
=> chore: wrap attributes in backticks

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-347.mdx
Adds release notes for Synthetics Job Manager release-347.
=> [synthetics job manager] chore: adds release notes for sjm release-347

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-7410.mdx
Release notes for the mobile iOS agents 7.4.10 release.
=> iOS agent 7.4.10 release notes

src/content/docs/security/security-privacy/information-security/software-development-lifecycle.mdx
Removed reference to HackerOne as we are switching to BugCrowd
=> Text changed as we no longer use HackerOne

src/layouts/MainLayout.js
=> fix: update button colors

src/nav/serverless-function-monitoring.yml
I did this to match the file I renamed in a previous PR.
=> AWS Lambda: Change left navigation from legacy to layerless

src/content/docs/infrastructure/amazon-integrations/connect/eks-add-on.mdx
This is for NR-247445 where a customer asked for EKS version compatibility information.
=> AWS: Add link to EKS supported versions

src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/migration-guide.mdx
making on behalf of @mangulonr - original PR https://github.com/newrelic/docs-website/pull/16614
=> Removed POMI's EOL date

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Documenting a new feature of the .NET Agent for disabling specific instrumentation via the config file
=> Adding new .NET config option

src/content/docs/apis/nerdgraph/examples/nerdgraph-issues-api-via-github.mdx
@crshanks I needed to redo your PR because of some errors. Does this look okay to you?
https://github.com/newrelic/docs-website/pull/16598/files
=> fix(nerdgraph): redoing work for a contributor

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1510.mdx
Infra Agent 1.51.0 Release Notes
=> Infra Agent 1.51.0 Release Notes

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.56.mdx
Making on behalf of @lromer22 , we're having some issues with our build previews and need to make some new PRs.  This replaces https://github.com/newrelic/docs-website/pull/16606
=> node-api-runtime-1.2.56 release notes

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-350.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.57.mdx
We are releasing a new SJM and node api runtime version. These tell customers what we are updating.
Changes:
https://source.datanerd.us/synthetics/synthetics-kevin/compare/release-348...release-350
https://source.datanerd.us/synthetics/synthetics-node-api-runtime/compare/release-152...release-153
=> feat: Update release notes for job manager and api runtime

src/nav/infrastructure.yml
Updated the nav file for the RabbitMQ monitoring integration.
=> fix(OHI rabbitmq): Updated the nav file

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
Reworded Docker version support and removed "or higher".
=> fix(CPM): Clarified docker engine support

src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx
- Clarified custom modules with CPM are supported in both scripted API and scripted browser monitors
- Updated Selenium links
- Removed Selenium links where the content is no longer available (legacy API versions)
=> fix(links): Clarified custom module support and modified links

src/install/config/snowflake.yaml, src/install/snowflake/appInfo.mdx, src/install/snowflake/configure-integration.mdx, src/install/snowflake/find-data.mdx, src/install/snowflake/install-infra.mdx, src/install/snowflake/intro.mdx, src/install/snowflake/whatsNext.mdx, src/nav/infrastructure.yml
Added the branching doc structure for this page: [Snowflake monitoring integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration/).
This is the ticket: NR-217452
=> feat(OHI Snowflake): Added branching doc structure

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90800.mdx
* Add release notes for Python Agent v9.8.0.
* Note this release contains AI support and is dependent on links to docs being added in https://github.com/newrelic/docs-website/pull/16670.
=> Python agent 9.8.0 -- MERGE 3/28 AM(3/28 AM)

src/content/whats-new/2024/03/whats-new-03-26-aimonitoringga.md
No PMM review needed
What's new post for AI Monitoring GA.
=> MERGE 03-28 AM: AI monitoring what's new

package.json, yarn.lock
=> fix: removing extra slug portion of redirect urls

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8100.mdx
Release notes for the new version of the Java agent.
Compatibility updates.
=> chore(Java): 8.10.0 Release notes, compatibility update

src/@newrelic/gatsby-theme-newrelic/components/MDXLink.js
Reverts newrelic/docs-website#16749
=> Revert "Release/mdx link fix"

src/@newrelic/gatsby-theme-newrelic/components/MDXLink.js
Reverts newrelic/docs-website#16744
=> Revert "fix: update asset prefixing workaround"

src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
* Fix the python agent version that supports AI monitoring.
=> Change python agent version to 9.8.0 -- MERGE Wed April 2 PM

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx, src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications.mdx, src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx, src/content/docs/alerts-applied-intelligence/notifications/message-templates.mdx, src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
=> chore: add some language identifieres and minor styling updates to workflow docs

src/content/docs/alerts-applied-intelligence/notifications/message-templates.mdx
=> fix: typo with array name

src/content/whats-new/2024/04/whats-new-04-04-cloudwatchmetrics
No PMM review required.
Add what's new post for updated Cloudwatch metrics support
=> feat(whats-new): Add cloudwatch metrics post

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-32-0.mdx
=> New Go Agent Release

src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- Removed limitations section, some of which were previously removed but got squashed
- Added version requirements for several features
=> feat(RemovedLimitations): Job Manager updates

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
=> fix(sessionReplay): incorrect anchor link

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
=> fix(sessionReplay): remove april 8 reference

src/content/docs/network-performance-monitoring/troubleshooting/understanding-snmp-utilization-calculations.mdx
cleaning up some wording to better explain a measurement in network monitoring
=> chore: clean up language in throughput section

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
I missed this codeblock in my previous PR: https://github.com/newrelic/docs-website/pull/16827
=> fix: uncomment yaml example

src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-spanner-monitoring-integration.mdx
What problems does this PR solve?
Adds new metrics to the GCP Spanner integration to be made available during the day.
The content has been partly human generated, so if you spot any wronging do let me know.
=> feat(GCP): adding more metrics to the gcp spanner cloud integration

src/content/docs/synthetics/synthetic-monitoring/using-monitors/intro-synthetic-monitoring.mdx
Added link to the Synthetics Quickstarts library on github pages Updated Broken Link and Certificate Check API types Added rows for Nerdgraph, Terraform under additional features, noted REST API deprecation
=> Fix: Updated/Added details around APIs and include quickstarts

src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
Helps clarify customers on how trace session works in head sampling
=> Add head sampling trace session details

src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
=> chore(java): Remove duplicative links

src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx, src/nav/accounts.yml
This includes a change of the left navigation node name.
Note that I didn't rename the filename. Let me know if you think this is distracting, and I can rename it and insert a redirect.
=> Accounts: Rename awkward title and h2

src/content/docs/infrastructure/prometheus-integrations/integrations-list/node-exporter-integration.mdx, src/nav/infrastructure.yml
=> Infrastructure: Add Prometheus Node Exporter doc

src/content/whats-new/2024/04/whats-new-04-11-mobile-user-journeys.md
duplicated PR for https://github.com/newrelic/docs-website/pull/16892 since i cannot push commits to this PR for some reason
=> PUBLISH: 4/11, 9AM - Mobile user journeys whats new

src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx, src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8110.mdx
Add docs for the java agent 8.11.0 release
=> (Chore) Java Agent release 8.11.0

src/content/docs/security/security-privacy/information-security/security-bulletins.mdx
=> chore(security bulletins): Clarify NR23-01 end date

src/components/MachineTranslationCallout.js, src/components/PageTitle.js, src/layouts/MainLayout.js, src/templates/docPage.js
Adjusts the top padding in doc pages
=> Padding adjustments

src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
Updated line 61 from `Project Viewer` to `Viewer`
=> [chore] Update connect-google-cloud-platform-services-new-relic.mdx

src/content/docs/logs/ui-data/drop-data-drop-filter-rules.mdx
=> style(logs): Drop filter structure improvement

src/content/docs/release-notes/docs-release-notes/docs-4-12-2024.mdx
Docs release notes for week ending April 12, 2024
=> feat(release notes): Docs RN for 4-12-24

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
Added an example query for monitor downtime configurations.
=> feat(DowntimeExample): Added query example for monitor downtimes

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
=> fix: use mdx formatter to fix file

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
=> Update configuration options - agent v9.9.0 release

src/install/mongodb/install-infra.mdx
Default text showed referenced wrong integration
=> Fix integration reference

src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/integrations-custom-roles.mdx
Updated line 18 from `Role Viewer` to `Viewer`
=> [chore] Update integrations-custom-roles.mdx

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-druid-integration.mdx
Description: Updated the Apache Druid Documentation syntaxs, Replace config file and  logging step description
=> Updated Apache Druid Documentation

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
=> fix(sessionReplay): add limited preview to banner

src/i18n/content/es/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx, src/i18n/content/es/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx, src/i18n/content/es/docs/accounts/accounts-billing/new-relic-one-user-management/user-permissions.mdx, src/i18n/content/es/docs/new-relic-solutions/observability-maturity/innovation-growth/development-release-quality-guide.mdx
=> few changes to Spanish files

src/content/docs/infrastructure/host-integrations/host-integrations-list/nfs-monitoring-integration.mdx
=> NFS rewrite

src/content/docs/apm/agents/java-agent/configuration/java-agent-error-configuration.mdx
Added clarifying language when error reporting
=> Clarify Error Reporting

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp-moderate.mdx
Adding AI Monitoring to out-of-scope on our FedRAMP page
=> Adding AI Monitoring to out-of-scope on our FedRAMP page

src/install/cassandra/intro.mdx
=> quick integration fix

src/i18n/nav/es.json, src/i18n/nav/pt.json
=> fix: add new es/pt navs

src/content/docs/logs/logs-context/configure-logs-context-go.mdx
=> fix:go logs in context slog passing txn

src/content/docs/iast/introduction.mdx
- Update csec-go-agent support-matrix link
=> Update csec-go-agent support-matrix link

src/i18n/content/es/docs/nrql/nrql-syntax-clauses-functions.mdx
Fixes the deployment issue we had for the es site
=> fix: replace slashes with curlies

src/content/docs/style-guide/capitalization/capitalization.mdx, src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
What do you think @mmfred and @bhecknr? Did I help to clarify things?
=> style(Docs): Clarified some capitalization guidelines

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3110.mdx
Adds release notes for latest CPM release
=> chore: add release notes for minion 3.1.10

src/content/docs/new-relic-solutions/tutorials/build-hello-world-app.mdx
=> Tutorials: Fix broken links to developer site

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8111.mdx
Release notes for Java Agent 8.11.1
=> Create  java-agent-8111.mdx

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-731.mdx
* What problems does this PR solve? - Android agent v7.3.1 release notes
=> Target release 4/25 - Android agent v7.3.1 release notes

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
Update the agent config page to include trim_stats under *General Configuration Setting*
=> Update Config with Trim Stats Info

src/content/docs/infrastructure/microsoft-azure-integrations/getting-started/polling-intervals-azure-integrations.mdx
Fixed a broken link.
This comes from this `docs feedback` ticket: NR-262347
=> fix(Azure infra): Fixed a broken link

src/content/docs/browser/new-relic-browser/browser-apis/noticeerror.mdx
Discussed this with engineering, and they offered this change to update the Browser limitations section. There is also a Jira ticket for this: https://new-relic.atlassian.net/browse/NR-256523
Thanks!
=> Update Browser limitations section noticeerror.mdx

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/alert-custom-incident-descriptions.mdx
link to `#substitution-format` went nowhere, maybe linking this doc would be helpful but I just removed it for now
- https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/message-templates/#handlebars-syntax
=> chore: add language identifiers, remove dead link

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-7411.mdx
iOS agent 7.4.11 release notes
https://new-relic.atlassian.net/browse/NR-252373
=> iOS agent 7.4.11 release notes [Release 04-29-24 or 04-30-24]

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-367.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.3.15.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.3.21.mdx, src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
Adds WASM environment variable for Synthetics Job Manager for Docker and Kubernetes private locations.
=> feat: Add WASM for SJM private locations

src/content/docs/network-performance-monitoring/troubleshooting/snmp-polling-missing-metrics.mdx
=> feat(Network performance monitoring): Added apt-get codeblock as alternative to docker command

src/content/whats-new/2024/04/whats-new-04-30-otellambda.md
Fixing an error in the markdown.
=> fix(whats new): fixing mdx error

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx, src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration.mdx, src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx, src/content/docs/nrql/using-nrql/query-time-range.mdx, src/content/docs/vulnerability-management/understanding-prioritization.mdx
- added newlines between paragraph text and `<table>` tags should prevent translated content coming back with the `<table>` tag on the same line as the paragraph, which causes errors
- deindented some codeblocks
=> adjustments to prevent MDX issues in translations

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
=> Kubernetes: Add persistence setting

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates latest compatible version for several frameworks supported by the .NET agent.
=> chore: Update compatible versions for several supported frameworks

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-33-0.mdx
=> Go agent 3.33

src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
Updates webassembly minimum version to be used synthetics job manager version and node browser runtime
=> update: Webassembly syntax

src/i18n/nav/jp.json
=> Update JP nav file: jp.json

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/containerized-images.mdx
=> fix(serverless): adding redirect

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1521.mdx
=> docs: infrastructure-agent 1.52.1 release notes

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
there are examples of some of these methods in the codebase for the agent, I moved those here too
https://github.com/newrelic/node-newrelic/blob/main/api.js
=> feat: added examples of API usage

src/components/Layout/Sidebar.js, src/layouts/MainLayout.js
=> fix: make content right padding wider, remove border on nav, fix footer

src/content/docs/more-integrations/java-integrations/vertx-eventbus-integration.mdx, src/content/docs/more-integrations/java-integrations/vertx-extensions-integration.mdx
Added pages for java Vertx-eventbus and Vertx-extensions integration
These community integrations are managed by expert services Team at New Relic .
=> feat: Added pages for java Vertx-eventbus and Vertx-extensions integration

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
=> fix: broken link, reformat some code blocks

src/content/docs/codestream/observability/query-builder.mdx
=> fix: Fix "CodeLense" typo

src/content/docs/query-your-data/explore-query-data/dashboards/dashboard-template-variables.mdx
We received a GTSE related to Variables (https://new-relic.atlassian.net/browse/NR-265923) which was actually related to documentation. We want to make sure the usage of uniques and their limits are clear for customers and refer them to the `uniques` documentation if needed.
=> Update dashboard-template-variables rules

src/content/whats-new/2024/05/images/whats-new-05-08-sessiontraces.md
No PMM review required.
What's new post to inform customers about the billing update to session traces
=> (WHAT'S NEW: 5/8; time TBD): session traces

package.json, src/components/InstallFeedback.js, src/pages/attribute-dictionary.js, src/pages/install/{installConfig.agentName}.js, src/templates/docPage.js, yarn.lock
Apply styles from shape up week design mocks on the PageTools component. 
Refresh styles on the InstallFeedback component
Removes `Edit this doc` button from data dictionary JS page
=> Update feedback and PageTools styles

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
Made edits for a release on May 9th.
=> fix(global support): made first round of edits to this support doc

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
adding notes to support the equivalent of a negative lookahead regex pattern.
=> chore: add notes on creating negative lookahead

src/nav/infrastructure.yml
Adds a few missing install paths to the infra nav
=> Add missing install paths to nav

scripts/actions/webdriver-desktop.mjs, scripts/actions/webdriver-mobile.mjs
nav id's are now being slugified, so those references need to be updated in our webdriver tests.
=> fix: update nav id in webdriver references

src/content/docs/errors-inbox/otel-tab.mdx
2 of the urls don't have the leading / needed to link correctly.
=> fix: Correct urls

src/content/docs/apm/agents/go-agent/installation/install-new-relic-go.mdx
=> fix: wrap import in `""`

src/content/docs/logs/ui-data/parsing.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/containerized-images.mdx
fixing tab component
standardizing sub-steps in md format
=> Various hero edits

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
We added gov-aws-api.newrelic.com a little while ago to our endpoints, so this commit updates the docs to reflect that change as well.
=> Add gov-aws-api.newrelic.com to fedramp endpoints

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1522.mdx
=> Infra Agent 1.52.2 Release Notes

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6020.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6030.mdx
Adds in the latest release notes for the iOS mobile app.
=> Add in iOS apps release notes for 6.3.0 and 6.2.0

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90901.mdx
* Add release notes for Python Agent Release v9.9.1
=> docs: Python Agent Release v9.9.1 (merge 5/14 AM)

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
Reverts newrelic/docs-website#17254, to be published during the evening merge
=> Revert "(PUBLISH: 5-14) Session replay GA"

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
This PR is to re-add the changes from https://github.com/newrelic/docs-website/pull/17254/ that were reverted earlier this morning
=> (MERGE 5/15 9AM) feat(Browser): re-added session replay GA doc changes

src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx
Feels weird to not have "What's next?" as the last section in a doc
=> style(k8s): Make "What's next?" the last section of doc

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/apm-monitoring/opentelemetry-apm-intro.mdx
=> Fix typos on OpenTelemetry APM Monitoring page

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3112.mdx, src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3113.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-380.mdx
Adds patch notes for Synthetics Job Manager release-380, CPM releases 3.1.12 and 3.1.13, thank you!
=> Adding patch notes for Synthetics Job Manager release-380, CPM releases 3.1.12 and 3.1.13

src/content/docs/new-relic-solutions/tutorials/add-time-picker.mdx, src/content/docs/new-relic-solutions/tutorials/attach-nerdlet-entity.mdx, src/content/docs/new-relic-solutions/tutorials/customize-nerdpacks.mdx, src/content/docs/new-relic-solutions/tutorials/manage-app-permissions.mdx, src/content/docs/new-relic-solutions/tutorials/map-pageviews-region.mdx, src/nav/new-relic-solutions.yml
=> feat(Docs): Migrated content from developer to docs site

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
Best practices example for scripted API monitors.
=> add scripted api test

src/content/docs/security/security-privacy/data-privacy/security-controls-privacy.mdx
NR-265888
NR customer facing docs currently make reference to our de-provisioned Chicago hosts, IBM data centers, and state we solely use mysql datastores. The New Relic Database Team has been asked to update the copy to accurately reflect the state of our data storage layers.
=> Update NR Customer-Facing Docs Hosting and data storage Sections

src/content/docs/security/security-privacy/data-privacy/security-controls-privacy.mdx
Adjusting an H2 and fixing a link
=> fix(security): fixing header and docs link

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
The user count queries section was missing a link label that leads to the usage UI docs, so it was incomplete.
=> User count queries section was missing a link label

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-5180.mdx
Create new-relic-android-5180.mdx for update release in playstore
edit as needed
=> Create release note for android app update 5.18.0

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-on-aws-elastic-beanstalk.mdx, src/nav/apm.yml
Adds instructions for installing the .NET agent on AWS Elastic Beanstalk.
=> docs: Adds instructions for installing the .NET agent on AWS Elastic Beanstalk

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-11-17-0.mdx
Our bot failed so I'm posting these release notes from last week.
=> chore: Adds Node.js agent v11.17.0 release notes.

src/content/docs/logs/get-started/live-archives.mdx
=> fix(logs): fixing typo

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1523.mdx
Adding new release https://github.com/newrelic/infrastructure-agent/releases/tag/1.52.3
=> chore: add infra agent release

src/content/docs/infrastructure/host-integrations/installation/secrets-management.mdx
Added instructions for using CyberArk REST API for Microsoft SQL Server using Windows Authentication
This was previously undocumented
=> add: instructions for CyberArk REST API for MSSQL

src/i18n/translations/en/translation.json
=> Lowercase started

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
small edits to existing doc to increase readability
=> chore: add links and update some wording

src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
Replaced DoNotTranslate with an important note on this page: [Use your charts](https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/use-your-charts/)
=> style(Charts): Replaced DoNotTranslate with an important note

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
Tweaked language to resolve customer confusion
=> docs: Update snmp-performance-monitoring.mdx

src/content/docs/new-relic-solutions/tutorials/add-tables.mdx
Fixed New Relic name:
Reli. => Relic.
=> Fixed New Relic name

src/content/docs/logs/get-started/live-archives-billing.mdx
Added missing header id to one you worked on
=> fix(Logs): Added missing header id

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
@ally-sassman Requested your review because you looked at this most recently. Added missing header ID. Also, I noted the Markdown table, which we may want to fix/update to our standard table format at some point
=> fix(Node.js APM agent): Added missing header ID

src/content/docs/new-relic-solutions/build-nr-ui/contribute-nr-io/build-quickstart/add-alerts.mdx, src/content/docs/new-relic-solutions/build-nr-ui/contribute-nr-io/build-quickstart/add-dashboard.mdx, src/content/docs/new-relic-solutions/build-nr-ui/contribute-nr-io/build-quickstart/add-data-source.mdx, src/content/docs/new-relic-solutions/build-nr-ui/contribute-nr-io/build-quickstart/contribute-quickstart.mdx, src/content/docs/new-relic-solutions/build-nr-ui/contribute-nr-io/build-quickstart/understand-quickstart.mdx, src/nav/new-relic-solutions.yml
Migration of the Contribute to quickstarts docs category - part 2 from the developer site to the docs site.
This is the ticket: NR-264905
=> feat(Migration developer): Added the build quickstart section

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
NR-256456
@nbaenam @homelessbirds Verified the UI and updated text, letting you both know because you both worked on the Jira ticket.
=> fix(Alerts): Updated text to match UI

src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx, src/content/docs/style-guide/structure/tables.mdx
=> Daily release/may 24  2024 3 09

src/content/docs/mlops/integrations/openai-integration.mdx
Per request in #help-documentation
=> fix(MLOps): Link AIM doc from OpenAI doc

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.77.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.3.28.mdx
Adds release notes for recently deployed Synthetics runtimes
=> chore: Release notes for Synthetics runtimes

src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx
=> chore: add syntax identifiers

src/content/docs/nrql/using-nrql/query-time-range.mdx
=> feat: Add millisecond query time duration

src/content/docs/apis/nerdgraph/examples/apm-config-nerdgraph.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-data-partition-rules-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-issues-api-via-github.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx, src/content/docs/apm/agents/java-agent/troubleshooting/update-java-config-legacy-agent-versions.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/ansible-controller-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-druid-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-hadoop-monitoring-integration.mdx, src/content/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs.mdx, src/content/docs/logs/forward-logs/aws-lambda-sending-logs-s3.mdx, src/content/docs/logs/forward-logs/fluentd-plugin-log-forwarding.mdx, src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx, src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx, src/content/docs/logs/logs-context/configure-logs-context-go.mdx, src/content/docs/logs/logs-context/configure-logs-context-php.mdx, src/content/docs/logs/logs-context/configure-logs-context-python.mdx, src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx, src/content/docs/vulnerability-management/integrations/aws.mdx, src/install/apache-flink/check-metrics.mdx, src/install/apache-flink/configure-prometheus-apache.mdx, src/install/apache/default-configuration.mdx, src/install/apache/default-install-linux.mdx, src/install/nginx/default-configuration.mdx, src/install/nginx/default-install-linux.mdx, src/install/vm/whatsNext.mdx
=> chore: add lang identifier

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-kafka-confluentcloud-k8s.mdx, src/nav/opentelemetry.yml
=> Confluent on kubernetes

src/content/docs/nrql/using-nrql/rate-function.mdx
=> NRQL: Remove spurious callout

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-apm-ui.mdx
cc @ally-sassman 
Small improvement I came across when reviewing the newly deployed changed.
=> Make link to OpenTelemetry APM Monitoring more prominent

src/install/apache/default-install-linux.mdx, src/install/apache/linux/install-linux.mdx, src/install/apache/windows/install-msi.mdx, src/install/apache/windows/install-windows.mdx, src/install/elasticsearch/default-configuration.mdx, src/install/elasticsearch/default-install-linux.mdx, src/install/elasticsearch/linux/install-linux.mdx, src/install/elasticsearch/whatsNext.mdx, src/install/f5/default-install-linux.mdx, src/install/f5/linux/install-linux.mdx, src/install/f5/whatsNext.mdx, src/install/f5/windows/install-msi.mdx, src/install/f5/windows/install-windows.mdx, src/install/haproxy/default-configuration.mdx, src/install/haproxy/default-install-linux.mdx, src/install/haproxy/linux/install-linux.mdx, src/install/haproxy/whatsNext.mdx, src/install/haproxy/windows/install-msi.mdx, src/install/haproxy/windows/install-windows.mdx
=> fix: indentation in yml

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/automatically-instrument.mdx, src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/manually-instrument.mdx, src/nav/opentelemetry.yml
Migration of the two OTel tutorials:
- [Automatically instrument OpenTelemetry data](https://developer.newrelic.com/collect-data/opentelemetry) 
- [Manually instrument OpenTelemetry data](https://developer.newrelic.com/collect-data/opentelemetry-manual)
This is the ticket: NR-261816
=> feat(Migration developer): Added automatically and manually docs

src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-on-aws-elastic-beanstalk.mdx
Found as part of release notes writing
=> fix(.NET agent): Added missing anchor tags to headers

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Found while writing release notes
=> fix(Node.js APM agent): Added missing header tag

src/install/nginx/default-configuration.mdx
=> fix: typo I introduced last week

src/content/docs/accounts/accounts/billing/view-or-change-account-tax-information.mdx
Fixes NR-270301. Verified this new link is correct per nonprofit program peeps.
=> fix(accounts): Fix nonprofit signup link

src/content/whats-new/2024/05/whats-new-05-13-nrvm-change-status-to-ignore.md
* Creates a what's new for the ignore vulnerabilities feature
* Content created by Michael McPherson
* Ticket NR-274449
=> feat(whats-new): Add ignore update for NRVM

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
=> Update support case section

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
=> fix: 4.6.2+ requires v10+ of the agent

src/content/docs/style-guide/punctuation.mdx
Clarified that only the product UI uses an ampersand.
=> Update -- called out UI-only guideline on punctuation.mdx

src/content/docs/ai-monitoring/view-ai-data.mdx
[preview link](https://deploy-preview-17537--docs-website-netlify.netlify.app/docs/ai-monitoring/view-ai-data/)
=> workaround for stretched images inside `SideBySide`

src/content/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx, src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx, src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-hivemq.mdx, src/i18n/content/es/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx, src/i18n/content/es/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-hivemq.mdx, src/i18n/content/jp/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx, src/i18n/content/jp/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-hivemq.mdx, src/i18n/content/kr/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx, src/i18n/content/kr/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-hivemq.mdx, src/i18n/content/pt/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx, src/i18n/content/pt/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hivemq.mdx, src/i18n/content/pt/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-hivemq.mdx
Replaced `<Callout variant="note">` with `<Callout variant="important">`.
=> fix(Docs site): Replaced callout note with important

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6040.mdx
Adds in the latest release notes for the iOS mobile app.
=> docs: 6.4.0 - iOS mobile app release notes

src/i18n/content/kr/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx
I have corrected typos in the content. Please review the file changes.
=> Fixed typos in aws-firelens-plugin-log-forwarding.mdx file

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1523-fb-304.mdx, src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr24-01.mdx, src/content/docs/security/security-privacy/information-security/security-bulletins.mdx, src/nav/new-relic-security.yml
=> feat(Security): NR24-01 security bulletin

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1523-fb-304.mdx, src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr24-01.mdx, src/content/docs/security/security-privacy/information-security/security-bulletins.mdx, src/nav/new-relic-security.yml
=> daily-release/Jun-8-2024-noon

src/content/docs/new-relic-solutions/get-started/networks.mdx
Added endpoint 'pa-api.newrelic-external.com' to the User-facing domains table.
Customers have made inquires regarding the 'pa-api.newrelic-external.com' endpoint.
=> docs: Update networks.mdx

src/content/docs/vulnerability-management/change-vulnerability-status.mdx
This refactor is related to this Jira: NR-267083
=> fix(vulnerability management): First refactor of status doc

src/content/docs/data-apis/convert-to-metrics/create-metrics-other-data-types.mdx
* There was a broken link to additional documentation. This PR fixes the broken link. 
=> fix(metrics): Fix link to multiple metrics anchor

src/content/docs/infrastructure/infrastructure-ui-pages/infrastructure-inventory-page-search-your-entire-infrastructure.mdx, src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx, src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr24-01.mdx
=> feat(Security): Added info about how to check current versions of fluent bit

src/content/docs/infrastructure/infrastructure-ui-pages/infrastructure-inventory-page-search-your-entire-infrastructure.mdx, src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx, src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr24-01.mdx
=> Daily release/jun 14 2024 10 21

src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-109.mdx
There was a mismatch between filename version and version in title
=> fix(Flutter): Fixed version mismatch

src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-141.mdx
There was a mismatch between the version number in the title and in the file name.
=> fix(Capacitor agent): Fixed incorrect version number

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Looked in GA, no one has clicked any links in this section in last 30 days.
=> stylefix(NRQL): Remove extraneous get started flow

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Trying to fix a broken anchor link?
=> fix(logs): fixing anchor link

src/content/docs/data-apis/custom-data/aws-privatelink.mdx
Add a row for api.newrelic.com to the docs. This only exists in us-east-2 for the moment.
=> Add api.newrelic.com to privatelink docs

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
=> feat(oracledb): updating version

src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx, src/install/haproxy/default-requirements.mdx
This PR updates the requirements section in the haproxy integration because the integration has already been tested with haproxy 3.0
=> chore: update supported version of haproxy integration

src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx, src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx
Added in response to infosec-10264
=> feat(Kubernetes): Add helm install instructions

src/content/docs/infrastructure/host-integrations/host-integrations-list/linkerd-integration.mdx
=> feat:Update linkerd-integration.mdx

src/content/whats-new/2024/06/whats-new-06-12-aimodelinventory.md
This PR captures fast follows related to what's new copy for model inventory
=> updating copy for whats new post

src/content/docs/new-relic-solutions/build-nr-ui/custom-visualizations/add-to-dashboard-nerdgraph.mdx
=> chore: add graphql identifiers & formatted codeblocks

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
=> add job manager admin endpoints

src/content/docs/errors-inbox/mobile-tab.mdx, src/nav/mobile-monitoring.yml
Added redirects to deleted docs.
=> fix(errors inbox): added redirects

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1530.mdx
New infrastructure agent release 1.53.0 releae notes
=> New infrastructure agent release 1.53.0 releae notes

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
removed the `<var>`s, tried to complete the missing env vars and make things more  consistent with the rest of our docs
=> chore: updates to .NET config docs

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Added validator service url  required by security agents to connect with security engine for Fed environment
=> Update fedramp-compliant-endpoints.mdx with IAST endpoints

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-740.mdx
* What problems does this PR solve? - minor changes due to PM request. The reason for taking the configuration out is this configuration will be controlled from UI config of NR1, so we wouldn't need the agent side config.
=> Android v7.4.0 release notes minor changes

src/content/docs/security/security-privacy/compliance/data-encryption.mdx
Updating some verbiage to be more accurate
=> Update Data Encryption

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6050.mdx
Adds in release notes for the latest iOS mobile app version 6.5.0.
=> docs: Add latest ios release notes

src/install/java/frameworkInstallation/springboot.mdx
=> update pathing per feedback in github issue 17727

src/content/docs/alerts/create-alert/create-alert-condition/create-nrql-alert-conditions.mdx
Added redirect based on feedback in the hero channel
=> fix(alerts): added redirect

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Found as part of my release notes review
=> fix(node.js agent): Added missing header ID

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
Found during my release notes review.
=> fix(Infra): Added missing header tag

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-741.mdx
* What problems does this PR solve? - android agent v7.4.1 release notes
=> Target release 6/24/24: Android agent v7.4.1

src/content/docs/infrastructure/host-integrations/host-integrations-list/nvidia-jetson-integration.mdx
**Description:** Updated flex config for NVIDIA Jetson documentation
=> fix: Updated NVIDIA Jetson flex-config file

src/content/whats-new/2024/04/whats-new-04-09-eol-synthetics-runtime-cpm.md, src/content/whats-new/2024/06/whats-new-06-26-eol-synthetics-runtime-cpm.md
1. Add EOL post for legacy synthetics runtime
2. Updating previous post, as advised by docs team
=> Whats new 06 25 eol synthetics runtime cpm

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-327.mdx
Release notes for the Diagnostics CLI v3.2.7
=> feat(nrdiag): Diagnostics CLI v3.2.7 Release Notes

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
I tested this and confirmed with the agent team this is `recordMetric` working as intended
=> chore: clarify the recordMetric keys allowed

src/content/docs/release-notes/agent-release-notes/php-release-notes/src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-22-0-12.mdx
This PR contains the release notes for the next PHP Agent release (10.22.0.12)
=> feat(php): PHP Agent 10.22.0.12 Release

src/content/docs/data-apis/ingest-apis/event-api/incident-event-rest-api.mdx
=> fix: cmd needs to be continued with `\`s

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/changes-since-v3.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-otel-applications-kubernetes.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx
=> chore: format the yaml

src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/platform-apis/logger.mdx
Deleted section at the request of the UI-Core team
=> fix(SDK components): Deleted logger.debug section

src/content/docs/ai-monitoring/compatibility-requirements-ai-monitoring.mdx, src/content/docs/ai-monitoring/intro-to-ai-monitoring.mdx
This captures a reference to NVIDIA NIM in our intro to AI monitoring doc
=> Update intro AI monitoring copy to include a section about NVIDIA NIM

src/content/docs/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-intro.mdx
=> OpenTelemetry: Add missing redirect.

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-750.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-110.mdx
* What problems does this PR solve? - Release notes for NDK v1.1.0 & Android agent v7.5.0, log forwarding docs
=> Target 6/28 -  NDK v1.1.0 & Android agent v7.5.0

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-386.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.80.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.3.41.mdx
New release notes for Synthetics Private location Job Manager, Node browser, and Node API runtimes
Private images are deployed, just need these notes to go out
=> feat: Synthetics 6-27 Release Notes

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Provides indication that we now support Node.js 22.
=> chore: updated node version support table to include node 22

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
Modified a callout type and fixed indentation on the Kubernetes agent operator page.
=> fix(K8s): Modified a callout type and fixed indentation

src/content/whats-new/2024/07/images/whats-new-07-02-apmk8s.md
No PMM review required
What's new post for New Relic Kubernetes agent operator that automates instrumentation for APM and K8s
=> Whats new 07 02 apmk8s

src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/platform-apis/logger.mdx
The UI-Core team requested I delete these methods
=> fix(Component SDK): Removed private methods

package.json, src/components/HomepageBanner.js, src/layouts/MainLayout.js, yarn.lock
this PR consolidates our search page actions to all use the `swiftypeSearchInput` event name. it also pulls in the updates in the theme which record more information about search results
=> update search instrumentation

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-33-1.mdx
=> Go Agent Release

src/content/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration.mdx
**Jira ticket:** https://new-relic.atlassian.net/browse/NR-283746
**Description:** Added the temporal logs integration steps in the documentation.
=> (fix): Updated the temporal docs.

package.json, yarn.lock
removes `Developer` link from site header
=> theme bump

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.84.mdx
Adds release notes for synthetics-node-api-runtime released on 7/08/2024.
=> chore: Add release notes for node-api runtime
