- src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
This PR removes some configurations from the fluent-bit examples that:
1. [Are not supported since 1.3](https://github.com/newrelic/newrelic-fluent-bit-output#configuration-parameters) ([deprecated on 2020](https://github.com/newrelic/newrelic-fluent-bit-output/releases/tag/1.3.0))
2. Are not properly set (they should go inside the OUTPUT section)
> Remove not supported fluent-bit config options

- .github/workflows/vale-lint.yml
Its possible the version of Vale we were using has been deprecated. All the docs point to the `reviewdog` version vs `v1`. The docs for `v2` are using the reviewdog configs anyways, so I am just running with that one. 
I got the `reviewdog` configurations to run successfully in [this PR](https://github.com/newrelic/docs-website/pull/14989)
TODO:
> Fix vale linter checks

- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/simple-scripted-or-scripted-api-non-ping-errors.mdx
Ticket: https://issues.newrelic.com/browse/NR-103587
Context:
We got notified by our GTSE team that our documentation for this area is not correct. The reason behind this is that Script API monitors don't use the $browser tag they use the $http tag. In addition, this error isn't something that occurs when trying to run a Script API monitor. It was determined by our team within this slack thread that this section of the docs is misleading, so it is better off being removed: https://newrelic.slack.com/archives/C7HGFUXMH/p1680203101399849.
An issue with unnecessary documentation.
* Add any context that will help us …
> fix: Remove irrelevant job timeout error drop down.

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-dynamodb-monitoring-integration.mdx
Remove invalid one from metric list of AWS DynamoDB API Polling.
'userErrors' metric is region/account specific, it is not included dynamoDbTable provider.
The metric should be in dynamoDbRegion, which is already listed.
AWS Docs: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html#UserErrors
> fix(infra): remove invalid metric from metrics list of AWS DynamoDB Integration

- src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install.mdx
- src/i18n/content/jp/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install.mdx
- src/i18n/content/kr/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install.mdx
This PR fixes the path to nri-jmx downloader (currently points to an old version)
> nri-jmx: fix downloader path

- gatsby-config.js
Removes the ability for images in What's New posts to be opened in new tabs, as it was causing issues in the NR UI.
> fix: remove whats new image links feature

- src/content/docs/data-apis/understand-data/metric-data/metric-data-type.mdx
[gauge](https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api/#json-payload-keys) is the default metric type used by the Metric API and should definitely be supported.
> fix: correct support of gauge types in the metric api

- src/content/docs/network-performance-monitoring/troubleshooting/understanding-snmp-utilization-calculations.mdx
adding a missing conversion option to this troubleshooting doc
> chore: adding the 'tag' conversion

- src/content/docs/kubernetes-pixie/kubecost/get-started-kubecost.mdx
Notes that kubecost integration with NR is currently in preview.
Kubecost integration for NR is not thoroughly tested; this makes that clear to readers.
> chore: Update get-started-kubecost.mdx to not preview status

- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/apm/agents/net-agent/custom-instrumentation/create-transactions-xml-net.mdx
- src/content/docs/apm/agents/net-agent/custom-instrumentation/custom-instrumentation-attributes-net.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/set-transaction-uri.mdx
- src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx
- src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx
- src/content/docs/apm/agents/net-agent/troubleshooting/missing-net-async-metrics.mdx
- src/content/docs/apm/agents/net-agent/troubleshooting/net-agent-reports-handled-errors.mdx
Replace any `http://` links in the .NET agent documentation with `https://`.  Also updated some links based on redirections and 4xx errors.
> Update links in .NET agent documentation to be https

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Adds `Confluent.Kafka` to the list of messaging systems supported by the .NET Agent.
> docs: Add Confluent.Kafka to the .NET Agent compatibility list.

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx
Updates the .NET Agent compatibility docs to add support for automatic browser injection in ASP.NET Core 6+ web applications. Also adds support for automatic instrumentation of ASP.NET Core 6+ Razor Pages.
> docs: Updates .NET Agent documentation to include support  for automatic browser injection in ASP.NET Core 6+ web applications

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Adds a link to the exporter source code as a hyperlink on existing text.
The existing "Browse your source code" link in this document leads to the root of the repository, which can make it a challenge to find the related code.
"Browse your source code" link to repo: https://github.com/newrelic/newrelic-prometheus-exporters-packages
Direct mongodb3 exporter codebase link: https://github.com/newrelic/newrelic-prometheus-exporters-packages/tree/main/exporters/mongodb3
> [chore] Update mongodb-monitoring-integration-new.mdx

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/uninstall-kubernetes.mdx
K8s nav was pointing to the old file location of the uninstall k8s doc. Pointed it to the right location and added a redirect from the old link
> feat: point k8s nav to correct uninstall doc location

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/logs/logs-context/configure-logs-context-php.mdx
This PR contains updates documentation for the PHP agent for the added support of log context attributes for the Monolog library.
I would like this PR reviewed but please do not merge until I let you know.
> feat(PHP): Adds log context data documentation

- src/content/docs/apm/agents/ruby-agent/troubleshooting/transactions-named-routeset.mdx
- src/nav/apm.yml
This adds a troubleshooting guide for customers to learn more about what causes generically named transactions in their APM UI and some possible ways to solve the issue.
> Add new troubleshooting guide for ruby agent

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/install/dotnet/installation/dockerWindows.mdx
- src/install/dotnet/installation/windowsNonIisInstall-2.mdx
- Config: Add 32-bit profiler env vars since we set them up for 64-bit installs on IIS and the DLL is already there.  Added as a collapser under option env vars. 
- Monitor your .NET app: For Windows non-iis no Docker call out needing INSTALLLEVEL=50 for Framework apps.
- Monitor your .NET app: For Windows non-iis Docker add missing INSTALLLEVEL=50 and mention required config changes for Framework.
> Chore: Update .NET Agent installation and configuration docs to improve install experience.

- src/content/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
- Removed references to the public SLA report. This was functionality was EOLed. 
- Removed deprecation warnings for $browser and $driver objects. These will continue to be supported. 
- Clarified new runtime transition guides and related docs for $browser and $driver object usage
> chore(synthetics): Removed EOLed feature and deprecation warnings

- src/nav/apm.yml
Removes the errors tutorial from the install section of the APM category. We noticed this in a feedback burndown session and agreed this isn't the right place for a link to live.
> feat(apm): remove errors tutorial from apm category

- src/content/docs/infrastructure/amazon-integrations/get-started/aws-integrations-metrics.mdx
This brings AWS metric naming section up to speed with its Azure counterpart.
> AWS Metric naming revamp

- src/content/docs/new-relic-solutions/get-started/networks.mdx
It corrects an endpoint address for the EU `cloud-collector`.
`cloud-collector.eu01.newrelic.com` does not exist or match the pattern of other domains, which are either in `eu01.nr-data.net` or `eu.newrelic.com`.  `cloud-collector.eu.newrelic.com` does resolve/respond.
> fix: correct endpoint address

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
Fix grey block formatting, [example](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks/#databases). The style and rowSpans seem to be the outliers where colors are messed up, so I'm hoping the removal will fix this issue.
> Fix grey block formatting

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
This change introduces a `<Tabs>` component and adds the EU endpoints to the documentation on configuring New Relic to use AWS PrivateLink.
> Document EU PrivateLink Endpoints

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests.mdx
Secure credentials need exist prior to a monitor trying to use them.
> [Ready to merge after Doc Freeze] Add tip about order of operations

- .github/workflows/verify-mdx.yml
- scripts/addFreshnessFrontmatter.mjs
- scripts/docsAndLastDateEdited.mjs
- scripts/utils/__tests__/frontmatter.js
- scripts/utils/frontmatter.js
- scripts/verify_mdx.js
- src/content/docs/apis/nerdgraph/examples/nerdgraph-log-parsing-rules-tutorial.mdx
* creates script that adds `freshnessValidatedDate` field to frontmatter. Equals a date if document has been created/renamed in the last 180 days. Otherwise sets the field to `never`
* update csv script
* now includes headers
* new column that grabs value from `freshnessValidateDate`
* new column of authors and dates of all commits on that file in the last 180 days
* both scripts ignore `release-notes`, `whats-new`, and `security-bulletin` dirs
* add verify-mdx as github action
* modify mdx frontmatter verification to also check for newly required `freshnessValidatedDate` field and validate its value.
* frontmatter script tests were updated to add coverage for new function
```bash
Error:  Frontmatter field error: /home/runner/work/docs-website/docs-website/src/content/docs/...mdx …
```
> NR-180031 - docs freshness utils

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx
- src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/airflow/monitoring-airflow-ot.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
- src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-layers.mdx
- src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-orchestrated.mdx
- src/content/docs/tutorial-kubernetes-learn/tutorial-k8s-services.mdx
- src/content/docs/tutorial-manage-large-log-volume/get-started-managing-large-logs.mdx
- src/content/docs/tutorial-optimize-telemetry/detect-anomalies.mdx
- src/i18n/content/jp/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx
- src/i18n/content/jp/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
- src/i18n/content/jp/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
- src/i18n/content/jp/docs/tutorial-kubernetes-learn/tutorial-k8s-layers.mdx
- src/i18n/content/jp/docs/tutorial-kubernetes-learn/tutorial-k8s-orchestrated.mdx
- src/i18n/content/jp/docs/tutorial-kubernetes-learn/tutorial-k8s-services.mdx
- src/i18n/content/jp/docs/tutorial-manage-large-log-volume/get-started-managing-large-logs.mdx
- src/i18n/content/jp/docs/tutorial-optimize-telemetry/detect-anomalies.mdx
- src/i18n/content/kr/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-security-lake-monitoring-integration.mdx
- src/i18n/content/kr/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
- src/i18n/content/kr/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
- src/i18n/content/kr/docs/tutorial-kubernetes-learn/tutorial-k8s-layers.mdx
- src/i18n/content/kr/docs/tutorial-kubernetes-learn/tutorial-k8s-orchestrated.mdx
- src/i18n/content/kr/docs/tutorial-kubernetes-learn/tutorial-k8s-services.mdx
- src/i18n/content/kr/docs/tutorial-manage-large-log-volume/get-started-managing-large-logs.mdx
- src/i18n/content/kr/docs/tutorial-optimize-telemetry/detect-anomalies.mdx
Clean up from a minor bug that allowed an image to be imported anywhere in the MDX content, and it will render with that const as an img src in a file without needing to be imported there. This has probably happened by cut+pasting content to a new doc and accidentally leaving the import statements behind. 
This doesn't effect functionality, but is throwing errors in our verify-mdx script, so we want to remove this noise. Now that verify-mdx is a required github check on PR's this shouldn't continue to happen as these would get flagged in the review process.
> Resolve image import and MDX errors

- src/content/docs/apm/transactions/transaction-traces/transaction-traces-trace-details-page.mdx
This section is not currently true - used to exist in the old Seldon UI but has been gone for some time. We intend to add the logs link *back*, but it won't be until early 2024 so we should remove this in the meantime.
> Remove outdated section from transactions UI docs

- src/content/docs/apm/agents/c-sdk/get-started/apm-security-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/get-started/introduction-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/install-configure/install-c-sdk-compile-link-your-code.mdx
- src/content/docs/apm/agents/c-sdk/install-configure/uninstall-remove-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/instrumentation/distributed-tracing-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/instrumentation/guide-using-c-sdk-api.mdx
- src/content/docs/apm/agents/c-sdk/instrumentation/instrument-transactions-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/troubleshooting/generate-logs-troubleshooting-c-sdk.mdx
I know this agent is deprecated, so I just added basic code styling and didn't check most things
> chore: add language identifiers to C docs

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Frameworks table was labeled Logging Libraries. 
I also removed an old note which was no longer relevant because the table was more up to date
and added a new row in the database instance table for `mysql2`
> fix: mislabeled table

- src/content/docs/apm/agents/java-agent/troubleshooting/java-agent-identified-with-security-vulnerabilities.mdx
This PR addresses [java agent docs issue 1510](https://github.com/newrelic/newrelic-java-agent/issues/1510). In a snippet of solution code, it:
- closes an unclosed xml node
- corrects a regex string
I tested these changes locally to verify the corrected solution works.
> chore: correct typos in java-agent-identified-with-security-vulnerabilities.mdx

- src/components/FeedbackModal/FeedbackModal.js
Our survey modal wasn't being dismissed as expected if a user navigated to another page. This was because the variables with the cookie evaluation were outside the react component and would only be updated upon a page refresh. This should fix that so even if a user doesn't dismiss the modal it will go away upon route change
> Fix modal not being dismissed upon route change

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* Updated supported version of the infrastructure agent on macOS, which is aligned with Apple & Brew support on the most recent 3 major versions.
> infra-agent macos version support

- src/content/docs/apm/agents/java-agent/additional-installation/aws-elastic-beanstalk-installation-java.mdx
This PR addresses [java agent issue 1580 ](https://github.com/newrelic/newrelic-java-agent/issues/1508)
The previous installation instructions for the Java Agent on AWS Elastic Beanstalk were incorrect. This PR provides up-to-date instructions for AWS Elastic Beanstalk users on two different Java platforms. 
The changes were tested and verified locally for both platforms.
> chore: Update aws-elastic-beanstalk-installation-java.mdx

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* This PR remove the duplicated `Collapser` element in the Infrastructure [Agent Configuration documentation](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/) on the `logging_retry_limit`. All other information in both collapsers is identical except of the description.
* I merged the description of both collapsers into one.
> fix: Remove duplicated section for logging_retry_limit in Infrastructure Agent Configuration Docs

- src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- src/content/docs/apm/agents/java-agent/features/java-codestream-integration.mdx
- src/content/docs/apm/agents/net-agent/other-features/net-codestream-integration.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/codestream-integration.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
- src/content/docs/apm/agents/php-agent/features/php-code-level-metrics.mdx
- src/content/docs/apm/agents/python-agent/supported-features/python-codestream-integration.mdx
- src/content/docs/apm/agents/ruby-agent/features/ruby-codestream-integration.mdx
Update the links to Code-level Metrics from all the APM agent docs.
> Update agent links to Code-level Metrics

- src/content/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx
> chore: add language identifiers and fix some syntax

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-compression.mdx
* New Relic OTLP endpoint added support for `zstd` compression. Adapting the compression best practices explaining how to enable the different compression algorithms.
> feat: OTel zstd compression support

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Updated the individual compatibility docs for Core and Framework. I replaced the known compatible versions with minimum versions and agent versions. Known compatible version lists are really tough to keep up to date and I'm not sure they are as valuable as a list of minimums or versions with known issues.
I also replaced the confusing bullet point list of compatibility info in the LIC doc with a table that is easier to read.
> Update .NET logging framework compatability info

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
meraki recently updated their URL paths from `.../api-latest/...` to `.../api/...`; this PR fixes referenced links in our docs.
also adding one new setting introduced today via kentik/ktranslate#642
> fix: repairing broken meraki links

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
Resolves https://github.com/newrelic/newrelic-dotnet-agent/issues/2141 by adding .NET 8.0/ASP.NET 8.0 support statements in a few places missed previously.
> chore: additional .NET agent support for .NET 8.0/ASP.NET Core 8.0

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-29-0.mdx
> go agent release notes v3.29.0

- src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
I am not sure why [this change](https://github.com/newrelic/docs-website/commit/7bd25c0996076b0517b2448cd19087a55f72de49) made it, but the plugin is actually named `newrelic`.
> The output is named `newrelic`

- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
Now that the NerdGraph experience has moved into the New Relic UI and has some other minor internal layout changes, I'm removing the link to the outdated video.
> APIs: Remove link to outdated video.

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
Clarify references to hostmetrics and filelog receivers. Capitalize Linux
The code block name for the receivers `hostmetrics` and `filelog` did not match the receiver name in the collector.yaml config.
Capitalized "Linux" in one place.
The collector.yaml example in the same doc shows the receiver names.
n/a
> [chore] Update opentelemetry-collector-infra-hosts.mdx

- src/content/docs/logs/forward-logs/fluentd-plugin-log-forwarding.mdx
Add section to provide directions for UTF-16LE -> UTF-8 transform.
In some Windows environments, the Microsoft SQL Server error logs are written to disk in UTF-16LE encoding. Sending them directly to New Relic can result in formatting and display issues for the data stored to NRDB, since New Relic's API requires UTF-8 encoding ([reference](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data/#general)).
Configuration is required in order to send any UTF-16 logs as UTF-8. Fluentd supports the required transformation between encodings ([reference](https://docs.fluentd.org/input/tail#encoding-from_encoding)).
> Document UTF-16LE handling

- src/content/docs/synthetics/synthetic-monitoring/getting-started/monitor-limits.mdx
The existing link pointed to the Usage Plan correctly, but was not expanding the list prices section. I also added a clarification that you will need to scroll down to view Add-On pricing for Synthetics since we cannot link directly to this content inside of a collapser.
> fix(SynthListPrice): Fixed link to list price collapser

- .github/workflows/check-for-keys.yml
Remove the `pull_request_target` flag in this action to ensure it cannot run for all parties
> fix: remove pull request target from check for keys workflow

- src/nav/alerts-applied-intelligence.yml
Removed the "Introduction to" from the nav title of this page: [REST API calls for alerts](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts/)
> style(Alerts): Removed "Introduction to" from the nav title

- src/content/docs/infrastructure/install-infrastructure-agent/macos-installation/install-infrastructure-monitoring-agent-macos.mdx
Per customer feedback ticket, added some content to address the lack of directory when running through these steps literally
> Added clarifying instructions to macos infra install

- .github/styles/new-relic/ComplexWords.yml
Add an exception for the use of `IP address` so vale doesn't think it is the verb form of `address`
> Add exception to vale linted words

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
* Specify that the `cl_role` attribute is empty for Atlas instances. Discovered by @kang-makes  while giving support in a GTSE.
> fix(nri-mongodb): specify Atlas as special as of MongoDB metric attribute

- package.json
- plugins/gatsby-remark-autolink-headers-custom/index.js
- src/components/HeaderLink.js
- yarn.lock
This moves the header anchor link to the right of headers (to match the positioning in collapser headers) and also adds copy functionality to collapser headers via the theme update
> Update header anchor position and add collapser header copy button

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
I tried to use this guide to try out infra host monitoring via the otel collector locally, and ran into multiple issues. I used the dockerized collector as outlined in the linked guide on the opentelemetry website.
* This configuration will throw 2 `Error: invalid configuration` due to the missing `logging` and `otlp` sections which are referenced later in the config
* I also added a configuration to make sure that `host.id` is added to data points that don't already have it. This is important with how this guide is structure now with advising customers to check the Infra UI first to see this data ("By using the recommended configuration in the collector, you can view data through the standard features in the [Infrastructure UI](https://docs.newrelic.com/docs/infrastructure/infrastructure- …
> Corrections for Otel Collector for host monitoring guide

- src/content/docs/alerts-applied-intelligence/overview.mdx
Added a redirect to the [Introduction to alerts and applied intelligence](https://docs.newrelic.com/docs/alerts-applied-intelligence/overview/) page. [This link](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/new-relic-ai/get-started-incident-intelligence/) included in the New Relic's incident intelligence text doesn't work on the [Choose your data center (US or EU)](https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/#regions-availability) page.
This is a request from the #help-documentation channel, from Víctor Pérez.
> fix(Alerts): Added a redirect

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/data-apis/manage-data/query-limits.mdx
- src/content/docs/data-apis/manage-data/view-system-limits.mdx
- src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/remote-write-errors-error-messages.mdx
- src/content/docs/logs/get-started/logging-best-practices.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
These are changes migrated from the private site. It needs to be included in the morning build on 01/10/2024 to coordinate with PMM.
> (Publish: 1/10/2024) Accounts: Delete inspected count references

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
The documentation incorrectly indicated that the standard user role is essentially a read only role. That is not true for many products in the platform.
> fix(StandardUser): Clarified standard user permissions

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
- src/i18n/content/jp/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
The Node Agent dropped instrumentation for ElasticSearch prior to v716.0. This updates the supported version information.  Previously, New Relic's Node Agent instrumented ElasticSearch as early as v7.13.0, which was susceptible to crashing when using ElasticSearch's `.helper` API. ElasticSearch [fixed this bug in v7.16.0](https://github.com/elastic/elasticsearch-js/pull/1594), so we now support instrumentation from that version onward, and previous versions are noops.
> chore: Updated Node Agent supported-version for ElasticSearch

- src/content/docs/logs/ui-data/timestamp-support.mdx
Small typo correction: "vale" -> "value"
> Small typo correction: "vale"->"value"

- src/content/docs/apm/agents/net-agent/attributes/custom-attributes-net.mdx
- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/guide-using-net-agent-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/set-user-parameters.mdx
- src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
Updating custom attribute links related to .NET to link to the doc that explains how to add them, rather than the links to conceptual docs that explain custom attributes in general. I chose the docs by:
- Sweeping for the top 10 docs in Google Analytics for .NET
- Addressing the specific docs in the jira
- Doing a ctrl+f for all mentions of "custom attributes", then finding the relevant spots for .NET. 
I believe this captures everything
> Dotnet custom attributes pr

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1483.mdx
Release notes for infrastructure agent 1.36.1: https://github.com/newrelic/infrastructure-agent/releases/tag/1.48.3
> docs: infra agent 1.48.3 release notes

- src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql.mdx
Adding a known limitation for the shimming, keyset cannot be used with timeseries
* What problems does this PR solve? Document a known limitation for the shimming, keyset cannot be used with timeseries.
links to related docs, screenshots, etc.: https://new-relic.atlassian.net/browse/NR-129404
> Adding a known limitation for the shimming, keyset cannot be used with timeseries

- src/content/docs/infrastructure/host-integrations/host-integrations-list/install-apache-flink.mdx
**Ticket:** https://new-relic.atlassian.net/browse/NR-216087
**Description:** Removed the external link from the [Apache Flink](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/install-apache-flink/) documentation that guides users to download a harmful file
> chore: Updated the Apache flink documentation

- src/content/whats-new/2024/01/whats-new-01-18-nrql-q3-functions.md
This PR includes a What's New post for the Q3 NRQL functions GA.
> add whats new for q3 nrql ga

- src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
The markup for the link to newrelic.addCustomAttribute was missing the closing ')' so it did not display correctly in the docs.
> FIX: Update collect-custom-attributes.mdx

- src/content/docs/tutorial-optimize-telemetry/data-optimize-techniques.mdx
Answers the question mentioned in the [post](https://forum.newrelic.com/s/hubtopic/aAXPh0000000SU9OAM/drop-random-75-sample-of-event) and adds additional information to the doc
Image 1 shows 100% of the data. Image 2 shows the result of mentioned expression in the commit. Visibly the given expression `r'.*[a-b0-9]'` returns approximately 75% of the data (8.49k is ~75% of 11.4k) 
No
> refactor(data): optimize techniques in data-optimize-techniques.mdx

- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
Added an additional error that customers may encounter when upgrading to the newest API runtime.
> fix(MonitorUpgrade): Added JSON.parse error section

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-permissions.mdx
* A new capability has been added to manage access to new relic security products. We want to update the docs to include the 'vulnerabilities' capability that is already added.
Capability mentioned
> fix(user-permission): Update to include security capability

- src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx
- We got feedback that the docs are misleading to setLoglevel for android agent [here](https://newrelic.slack.com/archives/C01FKANDWJU/p1705663571167449)
- I have updated our docs to match with the code.
> Doc updates: correct misleading description for mobile android agent

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Moving some things from the reference doc as the second half of https://github.com/newrelic/docs-website/pull/15346/files work
> chore(NRQL): moving stuff in the reference doc

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Removing compatibility list from JVM section to prevent customer confusion on supported Java versions.
> fix(Java): removing compatibility list from JVM section

- package.json
- yarn.lock
the step container needed just a smidge more padding to avoid overcrowding as a child component (like within tabs)
> Update theme & fix padding issue on steps

- package.json
- yarn.lock
> fix: theme bump for content width

- src/content/whats-new/2024/01/whats-new-01-24-javaagent8.md
This post talks about the impact of upgrading to Java agent version v8.0.0-v8.7.0. Java agent v8.0.0-v8.7.0 introduced new standard attributes that impacts alerts/dashboards for customers. This is re-introduced in Java agent v8.8.0 for compatibility purpose.
> Whats new 01 24 javaagent8

- src/content/docs/infrastructure/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs.mdx
Updated this page: [Monitor services running on Amazon ECS](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs/).
There were 2 code sections that were blank.
This is a request from the [help-documentation channel.](https://newrelic.slack.com/archives/C0DSGL3FZ/p1706086034547939)
> style(OHI): Fixed 2 code sections that were blank

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/query-time-range.mdx
The colon after the anchor was making it visible as part of the heading. Removing the colon properly hides the anchor definition.
> Fix anchors defined in query-time-range.mdx

- src/content/docs/apm/agents/go-agent/configuration/go-agent-logging.mdx
Fixed a wrong URL on this page: [Go agent logging](https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-logging/).
This comes from this service docs-feedback ticket: NR-217243.
> fix(Go agent): Fixed a wrong URL

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
I recently followed this document to instrument a .NET Lambda with OpenTelemetry, and I ran into a few hiccups, which I've attempted to correct with these changes.
First, the previously referenced `OpenTelemetry.Contrib.Instrumentation.AWSLambda` package has been deprecated in favor of `OpenTelemetry.Instrumentation.AWSLambda`.  
Secondly, I made the need to add the OTLP exporter package and configuration more explicit (it's shown in the full example function, but was not called out during the step-by-step instructions).
Thirdly, I made more clear that the configuration steps need to happen in the function's constructor, and that the constructor needs to be static (and why).  Thanks to @nrcventura for helping me understand that one.  Again, this was in the sample code but not the …
> Update instructions for monitoring .NET Lambda functions with OpenTelemetry

- src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-app-launch-time-android-apps.mdx
Fixed the query on this page: [Configure app launch times](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-app-launch-time-android-apps/)
This is the ticket: NR-217916
> fix(Mobile monitoring): Fixed a wrong query

- src/nav/alerts-applied-intelligence.yml
#15700 had a small mistake where the `Alerts and applied intelligent overview` link in the left nav shot to a 404. This point it to the right file.
> Fix broken overview link from #15700

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90600.mdx
* Add release notes for python version 9.6.0.
> Add release notes for python v9.6.0 -- PLEASE merge Jan 25th PM

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
The .NET agent team has successfully tested the latest version of a library the agent instruments, Elastic.Client.ElasticSearch v8.12.0.  This PR adds that version to the list of versions we support.
Additionally, I found that some incorrect versions had somehow made it into the list for one of the two compatibility docs; this fixes it.
> .NET agent: update verified compatible versions of Elastic.Clients.ElasticSearch

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
The table was overcomplicated trying to list both the range of versions that support a given version of Java and the range that supports that version of Java but is no longer supported by NR.
So the third column was removed, and instead a note at the bottom of the table was added with a link to the list of supported versions.
Also, versions of Java that are not long term support were removed.
> fix(java): cleaning up JVM compatibility table

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/alert-custom-incident-descriptions.mdx
To use tags in a custom description, the syntax 'tags.<tagname> is incorrect. The correct syntax is 'tag.<tagname>. This update fixes that.
> Update alert-custom-incident-descriptions.mdx - documentation bug

- src/content/docs/data-apis/manage-data/view-system-limits.mdx
The 5000 infra agent account limit is not being enforced. Having it documented creates unnecessary concerns.
> Update view-system-limits.mdx - Removed unused limit

- src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx
Helm chart has been moved to a new repository: https://github.com/prometheus-operator/prometheus-operator/tree/main/helm
Code blob's YAML path was incomplete and required the rest of the `remoteWrite` key's path to be added.
> docs: Promethus CRD example code is incomplete

- src/content/docs/apis/insights-apis/query-insights-event-data-api.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
- src/content/docs/apm/agents/manage-apm-agents/agent-data/collect-custom-metrics.mdx
- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
- src/content/docs/nrql/using-nrql/subqueries-in-nrql.mdx
- src/content/docs/nrql/using-nrql/subquery-joins.mdx
This PR changes references to the previous max query limit of 2000 results to 5000 results.
> Update Limits Value

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Add example for multiple clusters/exporters in k8s. This is to set different `mongodb_cluster_name` values based on the name of the `percona/mongodb_exporter` pod that is being scraped.
Fix reference to newrelic_remote_write (see https://github.com/newrelic/newrelic-prometheus-configurator/blob/main/charts/newrelic-prometheus-agent/values.yaml#L141)
> Chore: Update mongodb-monitoring-integration-new.mdx

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
- Removed step monitors from limitations of new Synthetics runtime
- Added minimum version section
- Updated Chrome 100 references to Chrome 100+
> feat(StepMonitors): Supported in Chrome 100+ runtime

- src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.30.0.mdx
- src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.38.0.mdx
* What problems does this PR solve? Adds release notes for ping-runtime 1.38.0
> chore: Add release notes for ping-runtime:1.38.0

- src/content/docs/apm/agents/net-agent/troubleshooting/no-data-appears-net.mdx
A .NET agent customer had a problem using the agent with .NET 8 with runtime diagnostics disabled; this was caused by a change in how .NET 8 interprets a particular environment variable setting.  This PR adds info to the .NET agent "no data appears" troubleshooting doc about this particular pitfall.
> Update .NET agent troubleshooting doc with .NET 8 diagnostics settings info

- src/content/docs/new-relic-solutions/get-started/networks.mdx
Removed a callout about previous changes to Horde IP ranges that occurred in August 2023. This notice is no longer necessary.
> fix(HordeIPRanges): Removed old callout

- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/go-agent-attributes.mdx
- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- src/content/docs/apm/agents/java-agent/instrumentation/instrument-browser-monitoring-java-agent-api.mdx
- src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-app-engine-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-bigquery-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-load-balancing-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-pubsub-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-spanner-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-sql-monitoring-integration.mdx
- src/content/docs/mobile-crash-rest-api-v1.mdx
- src/content/docs/style-guide/formatting/ui-paths.mdx
We have a number of docs that have `<dd>` tags to indent content. This isn't the convention we're following on the site, and we can't guarantee how the translation engine will handle these (per development). So, I'm removing these.
This is for NR-220635.
> Remove <dd> and </dd> tags across site

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
updating a setting option in the snmpv3 config for netmon
> fix: update typo on snmpv3 setting

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
- src/content/docs/network-performance-monitoring/advanced/ktranslate-container-management.mdx
updating netmon docs to include examples of using cloud provider secret managers to retrieve secrets
> chore: update docs on using cloud secrets

- src/content/docs/logs/ui-data/parsing.mdx
Add an additional example to show how to write Grok rule with both noPrefix and keepAttributes.
> Add_example_for_json_parsing

- src/content/docs/errors-inbox/errors-inbox.mdx
Adds the PHP Agent to the list of APM agents that support error fingerprinting (error grouping).
> feat(php-agent): add php to list of agents supporting error fingerprinting

- src/content/docs/iast/introduction.mdx
Updated the APM agent versions to the latest GA license on the [Introduction to IAST](https://docs.newrelic.com/docs/iast/introduction/) page.
This request comes from the #help-documentation channel (02/15/2024)
> fix(IAST): Updated APM versions on the intro page

- src/content/docs/infrastructure/amazon-integrations/get-started/aws-integrations-metrics.mdx
Breaks apart AWS metrics into individual collapsers per integration.
> Nr 101608: break apart AWS metrics tables

- netlify.toml
When we migrated to Netlify we didn't set the `Referrer-Policy` response header to expose referrer page to signup page so it can report where signup originated. This is useful in attributing new signups to docs.
Also brought over the `Content-Security-Policy` response header for keepsakes for time being in case we ever want to iframe embeds or other content in other NR domains. This was previously done to support docs library service content in NR UI.
[Relevant options for gatsby cloud in gatsby-config.js](https://github.com/newrelic/docs-website/blob/7425a0363356a56355fb92cea5ec55d7a01e9b8f/gatsby-config.js#L330-L331)
https://github.com/newrelic/docs-website/assets/2952843/a61ae450-742f-44c9-bbb3-4ba6065bcbb4
No build preview necessary. Will need to test when on NR subdomain by clicking …
> Fix: add response headers to ensure referrer it sent to signup page events

- src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.38.0.mdx
- src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.39.0.mdx
due to some cache issues in the original PR, i've gone ahead and made the fix separately here.
original PR:
https://github.com/newrelic/docs-website/pull/16227
> updating caps for ping release notes

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
If extra spaces exist, the following error will occur:
```sh
docker: invalid reference format.
See 'docker run --help'.
```
- list all available options
- can remove runtimes as needed
- can utilize `DESIRED_RUNTIMES` to run specific tags of runtime images like `newrelic/synthetics-ping-runtime:1.39.0`
> docs: DESIRED_RUNTIMES

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
This PR adds information about the new INI configuration: `newrelic.vulnerability_management.package_detection.enabled`. This PR is co-dependent on PR #16223 and should be merged at the same time as PR #16223. Thanks!
> PUBLISH: TBD chore(PHP): update configuration page with new package detection INI option

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/add-on-billing.mdx
- src/content/docs/licenses/license-information/product-definitions/new-relic-one-pricing-definitions.mdx
This is a small follow-up fix to the recent Compute Add On docs.
> Accounts: Correct anchor link and fix add-on wording

- scripts/actions/__tests__/__snapshots__/serialize-mdx.test.js.snap
- scripts/actions/utils/handlers.js
Adds `class="notranslate"` to `<InlinePopover />` during serialization.
```mdx
This is an example of an inline popover component for<span data-type="component" data-component="InlinePopover" data-props="W3sidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJ0eXBlIiwidmFsdWUiOiJhcG0ifV0=" class="notranslate"></span>
```
> Add notranslate class to InlinePopover component

- .github/workflows/build-notification.yml
- .github/workflows/manual-deploy-comment.yml
the manual deploy workflow consists of three parts:
a build can be triggered by commenting 'netlify build' on a PR. this will send a request to Netlify to build the most recent commit and leave a comment on the PR. the workflow defined in `manual-deploy-comment.yml` handles this
after Netlify receives a build request, it will POST to a URL we define with the status of that build. not included in this PR is a AWS Lambda that receives this request, parses some information out of it, then POSTs a request to Github to kick off step 3
the workflow defined in `build-notification.yml` is only manually triggered and requires several inputs. the Lambda from step 2 will POST to Github with the required fields, triggering this workflow to run. this workflow will update the comment on the PR left by …
> workflows for manual Netlify builds & notifications

- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration.mdx
NR-178984 customer feedback that we didn't do an adequate job differentiating between messages and activemessages. My update confirmed via Azure docs: https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-counters
> feat(Azure): Added clarification about what an activemessage is

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
Updating the list of required permissions for the AWS CW Metric Streams integration.
Part of NR-63143
> Add new permission elasticache:DescribeCacheClusters

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-python.mdx
This PR changes some wording for two steps in Tutorial 3 to eliminate confusion (the lines readers were told to add were already added in a previous step).
> Clarify instrumentation steps in Tutorial 3

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/update-or-disable-policies-conditions.mdx
After the changes to the Alerts UI, the steps to copy an alert condition are different. I have updated the instructions.
> Updated steps to "Copy a condition"

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
Documentation was missing Docker mount arguments required for external config files to be copied to container and read correctly.
> docs: Added missing `docker run` mount arguments to External Config Files section

- src/content/docs/iast/install.mdx
Fixed the URLs for the config file on the [Install IAST](https://docs.newrelic.com/docs/iast/install/) page.
Requested from Jayant (02/22/2024)
> fix(IAST): Fixed urls for config file

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx
Closes NR-163604
* Clarifies the pathing needed to use CloudFormation templates while migrating metric stream.
* Clarifies that the options under the header are parallel procedures and users must choose one or the other
https://deploy-preview-16379--docs-website-netlify.netlify.app/docs/infrastructure/amazon-integrations/connect/aws-metric-stream/#migration-steps
>  Fix Amazon CloudWatch Metric Streams integration pathing instructions

- src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
add note about tablespace usage metrics for read-only standby databases
Users of the integration may expect tablespace usage metrics for their standby metrics, however these metrics are not available from the source. We should clarify this edge case in documentation.
https://support.oracle.com/knowledge/Enterprise%20Management/2972740_1.html notes the following:
>  DBA_TABLESPACE_USAGE_METRICS is responsible for fetching metrics data for tablespace utilization and it is executed on primary database only.  By monitoring the tablespace usage on the primary database and performing corrective actions (if required), the changes will get automatically replicated onto the standby database through the shipped redo logs.
Hence no calculation on standby …
> [chore] Update oracle-database-monitoring-integration.mdx

- src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx
This PR fixes some inconsistencies in metrics units for haproxy integration. It should not be merged until [newrelic/nri-haproxy#116](https://github.com/newrelic/nri-haproxy/pull/116) is released (It will be kept as 'Draft PR' until them). We plan to release it next week.
> fix: haproxy integration metrics description and naming

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx
AWS has released an option to stream metrics that are 48hrs in the past https://aws.amazon.com/about-aws/whats-new/2024/03/cloudwatch-metric-streams-streaming-daily-metrics/
This limitation is no longer valid.
> Update Metrics Streams available metrics

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-python.mdx
The goal is to make the Python tutorial similar to the Java tutorial that already has tabs and step components.
Also, add links in the OpenTelemetry Java tutorial's table of contents that lead readers to each tab.
Here are the specific changes in the Python tutorial:
* Removed the side-by-side component in the introduction, so the image now follows the text.
* Added a new heading "Tutorials" that has a streamlined mini-table-of-contents with links to tutorial tabs.
* Revised the text of the first tip under "Tutorials."
* Updated the introductory information in the third (manual) tutorial.
> OpenTelemetry: Add tabs and step components to Python tutorial

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
* The PrivateLink integration has been updated to also support non-ingest related endpoints for the infra-agent and integrations (identity and command-api endpoints).
> feat(private-link): add new infra endpoints

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Fluent bit packages for version v2.2.2 are GA, so we think it makes sense to update our docs to use that version in the examples.
> Examples: Use latest fluentbit version avaialble

- src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
Adding important box on line 135 to let customers know to enable the Cloud Monitoring API. If not this error will not show up in customers account.
> [chore] Update connect-google-cloud-platform-services-new-relic.mdx

- src/pages/attribute-dictionary.js
Moves the permalink to after heading instead of before.
It seems there are style rules available via `gatsby-plugin-autolink-headers`.
Closes https://new-relic.atlassian.net/browse/NR-248153
> fix: move permalink to after heading

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
On March 1st, 2024 several PHP frameworks were EOL'd and this PR updates the PHP agent compatibility page to reflect these changes.
> chore(PHP agent): Updates compatibility based on 3/1/24 EOLs

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90701.mdx
* Add support notes for Python release 9.7.1.
* Fix incorrect default setting.
> Python release 9.7.1 -- MERGE March 11 PM

- src/components/InlinePopover/layouts/TwoButton.js
Improves text design in `InlinePopover` component.
before
after
> Increase InlinePopover text size

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* infra-agent 1.50.0 added an additional setting for the agent to configure the temp directory for integrations sync.
> feat(infra-agent): configurable integrations tmp dir

- src/content/docs/codestream/observability/code-level-metrics.mdx
- src/content/docs/logs/ui-data/use-logs-ui.mdx
Two changes:
1. Add a query to Code-Level Metrics section so users can check their coverage.
2. Add a link to CS from Logs, as an additional way to view logs.
> Update CLM and add link from Logs

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- Job manager releases always start with a lowercase `r`. https://hub.docker.com/r/newrelic/synthetics-job-manager/tags
- The releases page refers to the `Node browser runtime v2.2.22` https://docs.newrelic.com/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.2.22/
cc @bpeckNR
> Align with semantic conventions

- src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
Wording of `custom npm modules` should be changed to `custom node modules`, which makes more sense and is how this feature is referred to in SJM docs. Also update `npm modules` to `hosted modules` which makes more sense in the context of `local` versus `hosted` modules.
cc @bpeckNR @kondracek-nr
> align wording with synthetics job manager

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
The .NET agent team has verified that several new versions of our instrumented libraries are compatible with our agent, and we are updating our docs accordingly.
> chore: update .NET agent verified compatible versions of core tech libraries

- src/content/docs/tutorial-improve-app-performance/root-causes.mdx
This doc had a weird issue with a callout containing an image within a side/side component. Played around with it a bit, and I couldn't come up with a good way to keep the image in there, so I decided to just cut the image and give directional info within the callout.
> Fix callout image sizing

- src/templates/docPage.js
Hides page tools from smaller screens (<1240px) because they aren't very useful at the bottom of the page and doing something more sophisticated is currently out of scope.
> Hide pageTools on small screen widths

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
* Adding the new supported endpoint for Synthetics in the AWS private link integration. It has the same limitations as the new endpoints for infrastructure monitoring.
> aws-private-link: add synthetics endpoint

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
…ration indentation for logging exporters
Fix collector configuration indentation for logging exporter
> Fixes the indentation problem with the provided collector configuration.
> The logging exporter configuration is not properly aligned and fails the collector service. 
> Fix: Collector configuration sample in opentelemetry-collector-infra-hosts.mdx; 

- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-19-0-9.mdx
Updates for the PHP agent v10.18.0:
Add 'PHP agent v10.18.0' release notes
> PHP Agent 10.19.0 release (March 18th)

- .github/workflows/auto-comment.yml
- .github/workflows/build-notification.yml
- .github/workflows/manual-deploy-comment.yml
- CONTRIBUTING.md
this updates the workflow so the manual build preview will kick off automatically the first time a PR is opened. it also moves the conditional higher so the entire job will skip if the conditions aren't met. also fixes the input choice from `failed` to `error`
> manual build preview on PR open

- src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx
Feel free to rework how this is included, but I wanted to include the fact that you can now also run NRQL queries from within CodeStream in your IDE.
> Add reference to CodeStream's query builder

- gatsby-config.js
- src/components/Layout/Sidebar.js
- src/templates/docPage.js
changes the spacing around the main content. see [newrelic/gatsby-teme-newrelic#1024](https://github.com/newrelic/gatsby-theme-newrelic/pull/1024) for the changes to line spacing
> adjust content and sidebar spacing

- src/data/attribute-dictionary.json
Added detail about core counts in SystemSample.
From the Windows docs:
> NumberOfLogicalProcessors
Data type: uint32
Access type: Read-only
Qualifiers: [MappingStrings][1] ("WMI")
Number of logical processors for the current instance of the processor. For processors capable of hyperthreading, this value includes only the processors which have hyperthreading enabled. For more information, see Remarks.
https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor
> infra_agent: detail core count calculation

- .gitignore
- netlify.toml
- netlify/edge-functions/osano-country.js
When users in the EU load the site this function will run and replace the osano script's variant 1 with variant 2 which is gdpr friendly. with htmlrewriter I wasn't totally sure if we wanted to use the [element](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/#element) over the [text](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/#text-chunks) option but even loading the site on slow 3g the script seems to come in with the correct variant from the start which seems adequate
to test:
set the ENVRIONMENT env var to production in your .env file to get osano to show up. download the netlify cli and run `netlify dev` to run the edge function locally. in osano-country.js you can add the US to the list of countries to get the variant=two to show up in …
> Add edge function to load eu osano variant when in eu

- src/content/docs/new-relic-solutions/solve-common-issues/troubleshooting/log-audit-all-data-your-new-relic-agent-transmits.mdx
creating on behalf of @brnhensley because of netlify issues
this link also looks dead, it redirects to the link before it, but I don't know what the correct one might be:
```md
To customize your query, use any of the available [`NrAuditEvent` attributes](/docs/insights/insights-data-sources/default-data/nrauditevent-default-attributes-examples)
```
> fix: update broken links

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
(opening on behalf of @lartita)
Fixed typo under Example configurations > Basic configuration. UR was missing the I. 
Also added a note under Basic configuration to note that if the users password has special characters in it, then they will need to add single quotes to their URI. 
I then added single quotes to all examples that had a `username:password` in their URI.
> [chore] mongodb-monitoring-integration-new.mdx

- src/content/docs/logs/ui-data/timestamp-support.mdx
Made some updates to the Grok examples for custom timestamp parsing.
> Couple fixes to examples

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
Added a note that the CPM will not support Docker 26+. Customers should migrate to Synthetics Job Manager instead.
> fix(CPMDockerSupport): Clarified Docker 26+ support

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-permissions.mdx
Replace permissions screen shot with steps for viewing permissions in roles.
Also, remove the reference to a role that is being retired: "Manage v1 users" (per SME).
> Accounts: Remove permissions screenshot

- src/content/docs/apm/agents/ruby-agent/api-guides/ruby-ai-monitoring.mdx
- src/content/docs/browser/new-relic-browser/browser-apis/start.mdx
This fixes broken links in a browser doc and an incorrect file name in our ruby API doc for ai monitoring
> Fix broken links pr

- src/content/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details.mdx
- src/content/docs/tutorial-improve-site-performance/guide-to-monitoring-core-web-vitals.mdx
Removed an old screenshot (containing first input delay) and addressed title case references of core web vitals
> chore(browser): post-release core web vitals updates

- src/content/docs/ai-monitoring/customize-agent-ai-monitoring.mdx
The links to API methods for Node.js agent regarding AIM were transposed. This PR fixes it.
> fix: Updated api doc links for Node.js AIM

- src/content/docs/release-notes/docs-release-notes/docs-3-29-2024.mdx
I'm approaching this a little different than previous weeks: I skipped over minor wording updates and reorganizations so it's easier to find things that matter. 
Examples of what I omitted:
* Small tweak to NRQL docs
* Indent fixing sweep
* Link tweaks to synthetics docs
* Mobile API alpha ordering issues
> feat(release notes): Docs release notes 3-29-2024

- src/content/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api.mdx
- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
- src/content/docs/apm/agents/go-agent/features/cross-application-tracing-go.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/instrument-go-segments.mdx
- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-instrument-external-calls-messaging-datastore-web-frameworks.mdx
- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/apm/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
- src/content/docs/apm/agents/python-agent/supported-features/cross-application-tracing.mdx
- src/content/docs/apm/agents/ruby-agent/features/cross-application-tracing-ruby.mdx
- src/content/docs/apm/transactions/cross-application-traces/introduction-cross-application-traces.mdx
Mark cross application tracing (CAT) as deprecated and slated for removal in all documentation.
This is part of the prep work needed to EOL CAT.
> Mark cross application tracing as deprecated -- Merge April 1 2024 AM

- package.json
- yarn.lock
After merging a theme update localized links no longer show up as external but have an odd prefix. This reverts that theme update which means localized links will appear external again but will at least be functional
> Revert theme change

- src/content/docs/infrastructure/elastic-container-service-integration/introduction-amazon-ecs-integration.mdx
- src/content/docs/infrastructure/elastic-container-service-integration/understand-use-ecs-data.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/container-instrumentation-infrastructure-monitoring.mdx
- src/data/attribute-dictionary.json
A new method to scrape metrics from DockerAPI has been added to nri-docker unblocking the use of the ecs integration when EC2 nodes are running on cgroups v2.
The feature is still WIP and has not been released so is not ready to publish.
> feat: Add support for Docker API metrics fetch (NR-221195)

- package.json
- yarn.lock
Some line height adjustments from theme updates [here](https://github.com/newrelic/gatsby-theme-newrelic/pull/1040) and [here](https://github.com/newrelic/gatsby-theme-newrelic/pull/1037) for some more examples
- ### table of contents items
- ### code block lines
- ### h2's
[inline code in h2](https://deploy-preview-16818--docs-website-netlify.netlify.app/docs/ai-monitoring/drop-sensitive-data/)
> theme bump

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8100.mdx
When the Java agent 8.10.0 release notes were created, the security agent updates were added to the list of security updates.
Removing those as those show with a high priority on the update agent widget inside NR.
> chore(java): removing security agent updates from security updates

- gatsby-config.js
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- src/content/docs/more-integrations/terraform/terraform-modules.mdx
there were a lot of cut/paste errors in here, like stray characters that make no sense or commented out code samples
I added `[output]` to some code blocks so it formats as terminal output, those strings won't be rendered literally. It looks like people were commenting out the code you should run to highlight the output, but that's something you can do with the codeblock with `[output]`.
I also lined up some code comments because I think it's easier to read
* If your issue relates to an existing …
> fix: typos and codeblocks

- src/content/docs/infrastructure/infrastructure-integrations/cloud-integrations/hcp-consul-monitoring.mdx
The text `&lt;YOUR_CONSUL_DATACENTER_NAME_HERE&gt;` appeared in the codeblock, looks like a cut/paste error. I also replaced bold `**` with `code` formatting which is more consistent for code/variables/filenames in our other docs
> fix: removed html showing in codeblock

- src/content/docs/ai-monitoring/customize-agent-ai-monitoring.mdx
- src/content/docs/ai-monitoring/drop-sensitive-data.mdx
The id link for the .NET AI section was incorrect. There was also a typo, `record_content.enabled` not `record_content_enabled`. I also add regex identifier, I don't know if prisma will need `regex` added to the config options
> fix: link and typo

- src/nav/root.yml
> feat(Docs): Swapped the location of security and licenses category in top-level nav

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8110.mdx
The Java agent team was alerted by the APMS team that they were not able to parse the metadata on the release notes.
I believe it was due to the smart quotes that were used instead of the regular quotes.
> chore(java): removing smart quotes from metadata in release notes 8.11

- src/content/docs/nrql/using-nrql/rate-function.mdx
Requests:
* The first is a warning that when [FACETing by time](https://docs.newrelic.com/docs/nrql/nrql-references/nrql-group-results-across-time/#cohorts), or when using a time function in the WHERE clause, the rate() function will still return data for the entire time range specified.  FACET and WHERE do not scope the data down.
* The second is just a typo.  In the [last example](https://docs.newrelic.com/docs/nrql/using-nrql/rate-function/#average-appname-errors) it should say "over the past half hour" not "over the past hour".
> fix(NRQL): address fixes from a #help-documentation request

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8100.mdx
- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-5-0.mdx
This PR replaces the `<Callout variant="warning">` with `<Callout variant="caution">`.
This is a help-documentation request (04/15/2024).
> fix(Release notes): Fixed callout, replaced warning with caution

- src/content/docs/data-apis/understand-data/metric-data/query-metric-data-type.mdx
* This PR expands on the examples for `getField()` to include both the long-hand and short-hand versions of the queries. It also changes the order of the examples, moving the wildcard (`%`) query as the second example since it may have been contributing to user confusion. The form `%[field_name]` is a more complex query.
> chore(metrics): Expand getField examples to include long hand queries

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
We maintain https://github.com/newrelic/newrelic-opentelemetry-examples with various working code examples which support our docs. There are several collector related examples in there, but the host monitoring documentation was done before we established the pattern of having a supporting example.
I've added a supporting example in https://github.com/newrelic/newrelic-opentelemetry-examples/pull/575, and this PR synchronizes the configuration, and links back to the code example for improved usability.
> Synchronize otel host monitoring example with example repository

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
Changed the minimum version of Job Manager that supports custom node modules from release-360 to release-363.
> fix(CustomNodeModules): Updated minimum version

- src/content/docs/codestream/start-here/what-is-codestream.mdx
- src/content/docs/tutorial-dd-migration/making-the-switch.mdx
The CodeStream section was way out of date so I updated it, and also tweaked the corresponding section in the "What is CodeStream" article.
> Update CodeStream section. in DD migration article

- src/content/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx
Eng confirmed the correct version on slack here https://newrelic.slack.com/archives/C0MQ534AD/p1713306862888449?thread_ts=1713306193.528189&cid=C0MQ534AD
> I’m not sure where the [OpenAI Library] 3.4.0 is from. But the correct one is 1.19.4
> sashabaranov/go-openai version 3.4.0 doesn’t even exist. 
> fix: wrong openAI version

- src/content/whats-new/2024/04/whats-new-04-09-eol-synthetics-runtime-cpm.md
Adding what's new post to announce the EOL of legacy synthetics runtimes and Containerized Private Minion on October 9th, 2024. To be published on April 9th.
> [WHAT'S NEW]: PUBLISH 4/22. Add Synthetics EOL post

- src/content/docs/iast/install.mdx
Fix for indentation in "validator_service_url" property of IAST config for EU and FED region.
> Fixed indentation for iast config

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-layerless.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-example.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
Ruby based AWS Lambda functions are now automatically supported by New Relic
> Update the serverless content for Ruby

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/apm/agents/python-agent/supported-features/python-runtime-metrics.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90900.mdx
This PR adds the release notes for the Python Agent v9.9.0 as well as a new configuration option
> Python release notes v9.9.0

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
This PR fixes the jump link for the `compressed-content-encoding` setting within the Python Agent's configuration page.
> Fix jump link for compressed content encoding

- src/content/docs/new-relic-solutions/get-started/networks.mdx
We had some legacy syntax in our ingest URLs that used an astrisk. This PR removes three instances of those asterisks.
Also, we clarified the private note to writers about whom to contact for future requests about changing endpoints.
> Networks: Remove legacy syntax

- src/content/docs/vulnerability-management/understanding-prioritization.mdx
* We want to provide users a location where they can read more about EPSS model and link to the source of where EPSS data originates from.
> fix(link): Add first.org link to NRVM

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx
- Removed Windows as a supported deployment option for K8s
- Included that Linux containers can only be run on Linux K8s nodes
> fix(K8s): Clarified K8s support

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
I'm not sure if `elixir` will be recognized by the docs site, but the current identifier was not and github only recognizes this one.
> chore: elixir identifier

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Looks like the initial publication of this doc last year had an error that mentioned elasticsearch instead of mongodb.
> Remove accidental elasticsearch mention

- src/nav/apm.yml
Inspired by frequent confusion when I watch people navigate docs, most recently @jeff-colucci earlier today. 
Would like input from @bradleycamacho / @rhetoric101 , one of whom I believe originally made this change away from calling it APM agents?
> style(nav): `APM agents` instead of `Install`

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
Added optional runtime related fields to broken link, cert check, and step monitors to match other monitor types. Using these fields allows you to create a monitor that utilizes newer synthetics runtimes and private job managers (if applicable).
> fix(OptionalFields): Added optional fields

- src/components/Onboarding/OnboardingStep.js
- src/components/ProductTile.js
- Remove hover effect from ProductTiles on mobile so when i user clicks, the tile doesn't grow. 
- Also removed a left margin from the onboarding steps that works for desktop views, but makes the text off center in mobile layout.
https://github.com/newrelic/docs-website/assets/47728020/079935ea-892b-48f5-a718-ea47c96e3922
https://github.com/newrelic/docs-website/assets/47728020/6027e3e7-274c-4c9b-889e-b1c4fe9e1d41
> ProductTile mobile hover

- src/content/docs/nrql/using-nrql/query-time-range.mdx
We had an h3 heading without an anchor and it surfaced a bug where a random anchor is generated for anchorless headings. Until we can fix that bug, I'm adding an anchor.
> NRQL: Add missing anchor to h3 heading

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/apm/agents/php-agent/frameworks-libraries/wordpress-specific-functionality.mdx
- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-20-0-10.mdx
Updates for the PHP agent v10.20.0:
Add 'PHP agent v10.20.0' release notes and supporting documentation that was updated to reflect functionality changes.
> PHP Agent 10.20.0 release (April 30th)

- scripts/createNetlifyRedirects.mjs
this fixes links to `docs/release-notes/agent-release-notes/<agent>/current` 404ing
- run `BUILD_LANG=en node ./scripts/createNetlifyRedirects.mjs`
- check `public/_redirects`
- `docs/release-notes/agent-release-notes/<agent>/current` rewrites should exist for all agents in `src/content/docs/release-notes/agent-release-notes`
- rewrites should point to the latest release note
> add rewrites for `agent-release-notes/<agent>/current`

- src/nav/mobile-monitoring.yml
These were keeping these docs from showing up in the nav on page load
> fix(Docs): Removed trailing slashes from nav

- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
This is an effort to cross link between the storefront and our docs site.
> APM Java agent: Link to the storefront report about Java usage

- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
added a little more clarification on how metrics are displayed trim_stats config is set to false
> Trim Stats Update

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/apm/agents/php-agent/features/browser-monitoring-php-agent.mdx
- src/content/docs/apm/agents/php-agent/frameworks-libraries/drupal-specific-functionality.mdx
- src/content/docs/apm/agents/php-agent/frameworks-libraries/wordpress-specific-functionality.mdx
- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-20-0-10.mdx
Updates for the PHP agent v10.20.0:
Add 'PHP agent v10.20.0' release notes and supporting documentation that was updated to reflect functionality changes.
> PHP Agent 10.20.0 release (5/6/2024)

- src/content/docs/accounts/accounts/account-maintenance/account-email-settings.mdx
Update broken links for Alerts notifications
* This updates the two links to information on Alerts notifications, which were still pointing to locations that no longer exist due to our migration from legacy notification systems to Workflows.
> chore: Update account-email-settings.mdx

- src/content/docs/infrastructure/host-integrations/installation/secrets-management.mdx
This should be documented since the CyberArk REST API returns a JSON payload with `UserName` for username and `Content` for password.
See code here for mapping:
https://github.com/newrelic/infrastructure-agent/blob/master/pkg/databind/internal/secrets/cyberarkapi.go#L45-L50
** What problems does this PR solve?**
Helps document the correct `username` and `password` variable to use CyberArk REST API for credentials.
**Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.**
Using the CyberArk REST API, you get a JSON payload that included `UserName` and `Content` which would be natural to use in the credential variable, which is not that case since the Infrastructure Agent is mapping them to `username` and `password` instead.
* …
> update: add CyberArk REST API details

- src/pages/whats-new.js
i18n versions of this page were linking to `/<locale>/whats-new/feed.xml`, which doesn't exist, as the RSS feed isn't translated. this change makes sure we always properly link to the RSS feed
> always link to /whats-new/feed.xml

- package.json
- src/layouts/HomePageLayout.js
- src/pages/index.js
- yarn.lock
- theme bump that updates site page background color
- override homepage background to old color to maintain contrast
- double checked other components using this variable, and everything seems fine. Though DocTiles have lost some contrast, but I think the drop shadow still makes them stand out enough.
> Page background color

- src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx
There was a request to add a line to one of these tables in the help-doc channel. I noticed the tables were in markdown. Converted them and added the line.
> fix(nerdgraph): changing markdown tables to html

- src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx
Updating ibmmq permissions specifications https://new-relic.atlassian.net/browse/NR-259871, https://new-relic.atlassian.net/browse/NR-262491
> feat(ibmmq): clarify required persmissions

- src/content/docs/infrastructure/microsoft-azure-integrations/getting-started/polling-intervals-azure-integrations.mdx
- src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx
* **What problems does this PR solve?**
It includes a new section to explain how to export troubleshooting metrics from one of our Helm charts and how to display them using a template dashboard file.
* **Add any context that will help us review your changes such as testing notes,
links to related docs, screenshots, etc.**
The `newrelic-logging` Helm chart is a component that can be deployed on a Kubernetes cluster in order to forward logs from other components (pods) running in that cluster. This Helm chart is based on an open-source log forwarder named Fluent Bit. Sometimes, customers face problems when running Fluent Bit, and in this pull request we include instructions to collect metrics from Fluent Bit and represent them in a dashboard to facilitate the troubleshooting of that …
> Nr 239607 export and display fb internal metrics

- src/content/docs/logs/ui-data/parsing.mdx
We added two new configuration options to the `json` Grok action.
> feat(logs): Add descriptions of JSON action dropAttributes and isEscaped

- src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
- src/content/docs/infrastructure/host-integrations/installation/update-infrastructure-host-integration-package.mdx
- src/install/jmx/linux/install-linux.mdx
- src/install/jmx/windows/install-windows.mdx
- src/install/mysql/default-install-linux.mdx
- src/install/mysql/linux/install-linux.mdx
- src/install/mysql/windows/install-windows.mdx
This PR:
- fixes the link for the latest kafka installer pointing to the exe one
- clarify the jmx page
- removed in different places the requirement to restart the agent
> chore(docs): update kafka docs and related ones

- plugins/gatsby-plugin-whats-new-rss/gatsby-node.js
trying pointing the link at `/whats-new/feed.xml` regardless of language didn't work. this updates the whats new RSS feed generation plugin to generate the feed at the appropriate i18n path for the non-English sites
i added this as a branch deploy branch for the JP site, it can be tested [here](https://sunny-rss-feed-fix--docs-website-jp.netlify.app/jp/whats-new/)
> generate RSS feed at i18n paths

- src/content/docs/vulnerability-management/change-vulnerability-status.mdx
Legal recommended changes
* Updates new documentation per Legal's guidance
> (Update): Legal recommended changes to change-vulnerability-status.mdx

- src/content/docs/data-apis/manage-data/manage-data-retention.mdx
Restore the comparison table for retention periods. We had removed this during a revamp of this page. In consultation with an SME, we removed it, thinking the Data Plus page was sufficient. Alas, we received feedback from the field that there isn't a 1:1 relationship between the content we removed and the data plus page. So, we are restoring it.
> fix(data-apis): Restore the table for data plus comparisons

- src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
There was an instance of the word visualize misspelled as "visualalize". This PR resolves that typo.
> Fixed typo in dashboards-charts-import-export-data.mdx

- .github/auto_assign.yml
I wanted to get @nbaenam back on the auto-assign reviewer list
> Added nbaenam back to auto-assign list

- src/content/docs/logs/forward-logs/azure-log-forwarding.mdx
There is a size constraint on Azure Function uploads using the Node.js binding. This is a known issue on Azure's side. See here: https://github.com/Azure/azure-functions-host/issues/1361
This has caused a customer issue in the past and we're adding this section to make people aware of it.
> Update azure-log-forwarding.mdx with size constraint

- src/install/dotnet/installation/linuxInstall2.mdx
Minor change to the install steps for the .NET agent when using the YUM package manager. This change removes some unnecessarily manual tasks, replacing them with a single command that the user can run.
> docs: Simplify .NET agent  install steps for YUM.

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
The PR updates the Python Agent compatibility docs to include support for Python 3.12.
> Add Python 3.12 to python agent compatibility docs.

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1523.mdx
Infra agent nows support ubuntu 24.04 but logs are not supported there, this adds an extra note on the changelog and installation of infra-agent to let the user know.
Fluent-bit (the forwarder logs using) didn't release an ubuntu 24.04 version yet.
> Logs not supported yet on ubuntun 24.04

- src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-on-aws-elastic-beanstalk.mdx
Minor update to the AWS Elastic Beanstalk installation instructions for the .NET agent, brings the install steps in line with our [Linux / YUM instructions](https://docs.newrelic.com/install/dotnet/?deployment=linux&docker=noDocker#yum)
> docs: Update Elastic Beanstalk instructions for .NET agent

- gatsby-config.js
- src/content/docs/infrastructure/amazon-integrations/get-started/integrations-managed-policies.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-agent-gradle.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-unity/monitor-your-unity-application.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-custom-metrics.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/micrometer/micrometer-metrics-registry.mdx
Groovy (`.gradle` files) is similar to Java, has has some differences, so updated the language
Java in other docs tends to use 2 space indentation. 
These docs used both `<NEW_RELIC_LICENSE_KEY>` and `NEW_RELIC_LICENSE_KEY` style for the placeholders , so I removed the `<>`to make them more consistent
also added the `profile` identifier for prism for `.pro` files 
> chore: add language identifiers, minor fixes

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
Documentation updated to include information on running multiple trap containers on the same host.
> Docs: Added tip about monitoring multiple SNMP trap versions on one host

- src/content/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs.mdx
* Our team maintains [example apps](https://github.com/newrelic/newrelic-node-examples) so you can see both stock and custom instrumentaiton in action.  We have some direct links to examples but I thought it'd be good to link this on the intro page.  Same goes for our apollo server plugin and next.js instrumentation.  We get common questions around support for these and since they don't ship with our node agent, people sometimes don't know they exist.  There are links throughout the Node.js section of docs linking these but not in the intro page.
> chore: Removed a deprecated package from intro and linked to our example applications and next.js and apollo server packages

- .github/workflows/update-attribute-dictionary-json.yml
To help reduce the amount of redundant PR's that end up just being closed, changed `cron` schedule to just M - F
> fix: Update attribute dictionary update schedule to weekdays only

- src/content/docs/ai-monitoring/compatibility-requirements-ai-monitoring.mdx
This was missed with the rest of the AIM documentation rollout.
> Adding .NET agent to AIM compatibility list

- src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-on-aws-elastic-beanstalk.mdx
- src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx
- src/install/dotnet/installation/dockerLinux.mdx
Updates the .NET agent install docs in a few places to reference our recently-created code samples repository.
> docs: Update .NET agent install docs to reference the .NET agent samples repo

- src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx
- src/install/dotnet/installation/dockerLinux.mdx
This PR updates two URLs that were incorrectly modified by the reviewer in #17431. We're using specific URLs on these pages to point to the examples relative to the docs page.
> chore: Correct URLs for some references to the .NET agent samples repo.

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
We had a reference to a user planning Google Sheet that was not available to the public. Our SME said this was not a useful link, so I'm removing it.
Closes GitHub issue 16983
> Accounts: Remove the reference to Google sheet

- package.json
- scripts/actions/webdriver-mobile.mjs
- yarn.lock
the nav is no longer on the homepage, so this changes the test to check the nav on the MDX kitchen sink page instead. it also updates `@newrelic/gatsby-theme-newrelic` so we can look for the close button using its aria-label
> update mobile webdriver test

- src/content/docs/logs/ui-data/query-time-parsing.mdx
We received a new video that explains this feature. Also, we need to remove the reference to the "Formatted" tab.
> Logs: Add video and remove tab reference

- .github/CODEOWNERS
Adds the [Otel team](https://github.com/orgs/newrelic/teams/opentelemetry-community) as code owners / approvers of changes to Otel docs
Had to also add team to repo as collaborators
Closes NR-273107
> chore: add otel codeowners team

- src/content/docs/apis/lookups-service-api/lookups-service-api.mdx
- src/i18n/content/es/docs/apis/lookups-service-api/lookups-service-api.mdx
- src/i18n/content/jp/docs/apis/lookups-service-api/lookups-service-api.mdx
- src/i18n/content/kr/docs/apis/lookups-service-api/lookups-service-api.mdx
- src/i18n/content/pt/docs/apis/lookups-service-api/lookups-service-api.mdx
Fixed mismatched header and rows in lookups API example. Header has 6 values but rows only have 5 values. I removed the "text" in the header.
> Fixed mismatched header and rows in lookups API example

- src/templates/releaseNoteLandingPage.js
before:
after:
[preview link](https://deploy-preview-17493--docs-website-netlify.netlify.app/docs/release-notes/agent-release-notes/ruby-release-notes/)
> fix release note text overflowing the right side

- src/components/FeedbackModal/FeedbackModal.js
- Adds the correct location to the translation object.
- z-index needed to ensure text wasn't floating above the modal at all.
QA showing the desired view and testing i18n:
> fix: z index to prevent see through of modal, correct string variable

- src/content/docs/infrastructure/prometheus-integrations/integrations-list/node-exporter-integration.mdx
Clarify that this integration is for host monitoring (per SME).
> Prometheus: Change title

- src/content/whats-new/2024/05/whats-new-05-13-nrvm-change-status-to-ignore.md
- src/content/whats-new/2024/06/whats-new-05-13-nrvm-change-status-to-ignore.md
* Removes the usage of 'alerts' from the what's new message
* Vulnerabilities are not 'alerts'
* 'Alerts' term is used in other products and has a different set of implications when used. We have changed locations where we use the word  'alert' to 'vulnerability' in the what's new post.
> fix(whats-new): Fix ignore language for NRVM

- src/content/docs/logs/log-api/introduction-log-api.mdx
* What problems do this PR solve?
`msg` is not listed in the Log block table as a reserved attribute that is automatically mapped to the `message` attribute.
* Add any context that will help us review your changes, such as testing notes,
Infra-agent repo issue [#1780 fluent-bit config works as expected and yet it does not work in newrelic UI](https://github.com/newrelic/infrastructure-agent/issues/1780), reports a behaviour that is interpreted as a problem while it's the expected behaviour since the logs being forwarded to NR do contain …
> Add msg as a reserved attribute that is automatically mapped to the message attribute

- src/content/docs/codestream/codestream-settings/account-settings.mdx
Remove reference to toast notifications. This section will come back in a month or so when we introduce email notifications.
> Remove notifications

- scripts/actions/webdriver-mobile.mjs
this adds a loop to redo the XPath selector for the release notes div if it comes back null. it also updates the headless argument per [this article](https://www.selenium.dev/blog/2023/headless-is-going-away/) and lowers the sleep time since it doesn't seem to need to be so long
> fix intermittent webdriver failures

- src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
The Errors Inbox documentation about config options related to setting version tracking data is not currently part of the Ruby agent config doc (see https://github.com/newrelic/newrelic-ruby-agent/issues/2704).
While that's being worked on, add the content to this errors doc to help users find it.
cc @meda123
> chore(ruby-agent): Add version tracking to errors

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
We dropped support of agent v9 last week and all versions of .NET Core below 3.1. I've requested the .NET team review this for mistakes
> update: remove unsupported .NET Core versions

- plugins/gatsby-plugin-release-note-rss/gatsby-node.js
- plugins/gatsby-source-nav/gatsby-node.js
- src/content/docs/release-notes/docs-release-notes/docs-3-15-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-3-22-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-3-29-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-4-12-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-4-19-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-4-26-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-4-5-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-5-10-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-5-17-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-5-24-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-5-3-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-5-31-2024.mdx
- src/content/docs/release-notes/docs-release-notes/docs-6-7-2024.mdx
- src/templates/releaseNote.js
- src/templates/releaseNoteLandingPage.js
- src/utils/releaseNotes.js
this PR keeps the hard-coded 'v' for agent release notes and removes it for Docs release notes. it also updates the RSS feed generation code to be consistent with the release notes pages and the navigation
> remove hard-coded 'v' for docs release notes

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
The .NET agent recently added Lambda support to the agent and some associated serverless tooling.  This PR updates some serverless documentation to show .NET support where appropriate.
> .NET agent: update serverless docs with .NET support

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
Removed `Note: Logs are not yet supported on Ubuntu 24.04.` from the requirements of Ubuntu category in the Infrastructure agent. Because the logs will now support Ubuntu 24.04.
> chore: Remove note for ubuntu 24 in infra requirements

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
The .NET agent has tested some newer versions of our auto-instrumented clients for MongoDB and Elasticsearch and want to update our compatibility and support docs.
> .NET agent: update verified compatible versions of MongoDB and Elasticsearch clients

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
- src/content/docs/apm/agents/python-agent/getting-started/instrumented-python-packages.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-91100.mdx
* Document new configuration settings.
* Add release notes for v9.11.0.
* Fix broken link in Python2.7 EOL notice.
> Python release v9.11.0 -- PLEASE MERGE Friday June 14 AM

- scripts/actions/utils/handlers.js
This adds FunctionDefinition, TypeDefReference, and OptionReference to the serialization/deserialization handlers. 
here are some screenshots of a serialized/deserialized file living its best life and still rendering these components normally:
> Add new components to handlers

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Minor update to .NET agent compatibility docs to clarify that native images aren't supported.
> chore: Update .NET compatibility docs to clarify native images aren't supported

- src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
Fixes a minor error in the code sample for the `TraceMetadata` property in the .NET agent API.
> fix(dotnet): Corrects an error in the TraceMetadata code sample.

- scripts/actions/utils/docs-content-tools/i18n-exclusions.yml
Adds the sdk component doc folder to the i18n exclusions list
> Ignore sdk components in translation

- src/content/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument.mdx
- src/i18n/content/es/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument.mdx
Prisma supports `batch` but not the shorthand `bat`
- https://prismjs.com/#supported-languages
> fix: bat -> batch

- src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx
Session Replay has been GA since 5/15 so I removed references from the transition from LP to GA.
-Removed "Plan for paid consumption" heading
-The #view-consumption anchor link was broken. Updated to the correct #data-consumption
> Remove references to "planning for paid consumption" from Session Replay

- src/content/docs/apm/agents/nodejs-agent/getting-started/monitor-your-nodejs-app.mdx
- src/content/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent.mdx
- src/install/dotnet/intro.mdx
- src/install/java/intro.mdx
- src/install/python/python-agent-intro.mdx
* Add a callout into each agent's installation documentation that links to the common kubernetes agents operator installation documentation. Link TBD.
> Add a callout that links to k8s agents operator docs -- MERGE on FRIDAY w/ rest of Kubernetes doc changes

- gatsby-config.js
- netlify.toml
- package.json
Testing a deploy with just the CDN ENV variable to see if it affects how it references the images. I can't find any useful info on removing hashes from URI's in static assets.  - trying a [cache clear](https://app.netlify.com/sites/docs-website-netlify/deploys/667d8ce1343796256203d735) since this image related
just enabling this option and running a cache clear seemed to drastically improve lighthouse scores:
Some of these diferences could be related to the newrelic domain vs netlify tho
docs.newrelic.com vs build preview
things to note:
- performance score almost doubled
- most of the top diagnostics numbers look to be reduced by about half. 
I think these changes might be worth pushing to prod and then we can at least test if changing images causes caching issues.
We have decided not to …
> Netlify CDN / image performance testing

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
Updated doc to show that we support regions other than us-east-2 making it more clear that VPC peering is not needed if you're in the current supported regions
> [chore] Update aws-privatelink.mdx

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-layerless.mdx
Update .NET Lambda layerless approach to not require the layer. Original updated focused on using the layer only.  This new approach does not.
Closes newrelic/newrelic-dotnet-agent#2585
> chore: Update .NET Lambda layerless approach to not require the layer.

- src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
Link urls were in the plain text of the doc, also the 1,2,3 list was rendering as 1,2,1, so I increased the indentation of #2's content to maintain the list structure
> fix: broken links

- src/content/docs/apm/agents/ruby-agent/troubleshooting/control-when-ruby-agent-starts.mdx
We want to document that `Rails::Command::RakeCommand` may not be desired in all contexts. Adding a section about turning off the agent in certain contexts to this existing page seemed like a good place to do that.
However, it does provide a lot of duplication with the existing content. There may be a better way to achieve this goal.
> chore(ruby-agent): Add a section about turning off the agent 

- src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
this curl flag `-X` flag is here:
- https://curl.se/docs/manpage.html#-X
> fix: `-XDELETE` -> `-X DELETE` typo in curl cmd

- src/nav/root.yml
In a previous PR, I removed OTHER CAPABILITIES, but I put the new Video category in the wrong spot. This PR fixes that.
> Left navigation: Correct alphabetization

- src/content/docs/nrql/using-nrql/rate-limits-nrql-queries.mdx
Adding NerdGraph's default timeout of 5 seconds to the query limits document, as this isn't recorded elsewhere (except in async queries document briefly).
> NerdGraph Default Timeout rate-limits-nrql-queries.mdx

- src/content/docs/apm/transactions/transaction-traces/transaction-traces-trace-details-page.mdx
Update trace details page to add logs tab
> [Publish 7/8 AM] Update transaction-traces-trace-details-page.mdx

- src/content/docs/alerts/get-notified/incident-workflows.mdx
- src/content/docs/alerts/get-notified/notification-integrations.mdx
Added a few things that have come up recently with customers in order to make them clearer.
> Added some small info concerning third party integrations

- src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx
- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6060.mdx
* Adds in latest iOS mobile app release notes
* Updates licenses to reflect the latest iOS mobile app
> Docs: add in release notes for the iOS mobile app version 6.6.0

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8130.mdx
**WIP: DO NOT MERGE UNTIL NOTICE FROM JAVA AGENT TEAM**
These are the release notes for Java Agent version 8.13.0, which is scheduled for release 7-11-2024.
> DO NOT MERGE: Java Agent 8.13.0 Release Notes

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Adds a new version of Elastic.Clients.Elasticsearch to verified compatible versions for the .NET agent.
> .NET agent: update compatibility and support docs

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-11-23-0.mdx
We accidentally omitted bugs in 11.23.0 which produced this undefined bugs. This PR manually fixes it
> chore: Fixed front matter by creating an empty bugs array for 11.23.0

- src/content/docs/infrastructure/host-integrations/host-integrations-list/ray-integration.mdx
Stray whitespace in after the triple backticks made the codeblock render incorrectly:
> fix: codeblock not closed correctly

- scripts/actions/github-release-notes.mjs
it should've been `octokit.rest.repos.compareCommits` but also `compareCommits` is deprecated so i used `octokit.rest.repos.compareCommitsWithBasehead`
> fix method call to get commits

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* Debian 10 reached EOL 30th June, 2024.
* Removing old references to Ubuntu in manual install.
* CentOS should be referenced as CentOS Stream.
> infra-agent: EOL updates - Debian 10

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent-docker.mdx
Jira NR-287339 said it would be helpful to have a link to the main Node.js instructions from the Docker instructions.
> Node.js agent: Add link from Node docker to main Node instructions

- src/content/docs/accounts/original-accounts-billing/product-based-pricing/overview-data-retention-components.mdx
- src/content/docs/apm/reports/api-examples-sla-reports.mdx
- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-ec2-monitoring-integration.mdx
Fixed several broken links from AWS section.
This is a request from the #help-documentation channel (07-16-2024)
> fix(AWS): Fixed broken links

- src/i18n/translations/en/translation.json
This is for NR-283782. Here's what I did:
Heading: Other Capabilities > Deleted
Tile: CodeStream > Moved to Data Insights
Tile: Errors inbox > Moved to Data Insights
Tile: IAST > Moved to new Security section
Tile: Vulnerability Management > Moved to new Security section
Tile: Website Performance Monitoring > Moved to Monitor Your Data
Tile: OpenTelemetry > Moved to Monitor Your Data
Tile: Other integraitons > Deleted this grab bag tile
> Homepage: Remove "other capabilities" section

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Reworks .NET agent compatibility docs to list a single "Latest verified compatible version" rather than an ever-growing list of "Verified compatible versions" - any versions with known incompatibilities are (already) called out specifically in the docs.
> chore(dotnet): Reworks .NET agent compatibility docs

- src/content/docs/data-apis/custom-data/custom-events/report-custom-event-data.mdx
Jira NR-287391 noted that the link was to a doc about custom attributes--not events. I switched the link to a local anchor.
> Data APIs: Fix spurious link

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates the .NET Core and .NET Framework compatibility docs to include Amazon SQS as a support messaging framework.
> chore(dotnet): Add Amazon SQS support and compatibility statement

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
Removes invalid methods from Synthetics Chrome 100+ documentation.
The Selenium WebElements docs show these methods don't exist for the JavaScript API: https://www.selenium.dev/selenium/docs/api/javascript/WebElement.html
> synthetics - remove invalid webelement methods

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Our docs call out that we only support LTS versions.  We also document EOL versions after we drop support. This PR adds upcoming EOL dates from the Node.js docs and clarifies we will drop 2-4 months after the date.
> chore: Clarify our cadence of dropping EOL versions of Node.js

- src/content/docs/infrastructure/infrastructure-ui-pages/infrastructure-inventory-page-search-your-entire-infrastructure.mdx
* Adding a note based on customer feedback: inventory data for APM is not actually collected by the infrastructure agent but added in the backend once the same host is running both the infrastructure agent and APM agents.
> fix(infra-agent): Note about APM inventory data not being collected on the agent

- src/content/docs/apm/agents/php-agent/installation/php-agent-installation-ubuntu-debian.mdx
apt-key is deprecated because it adds keys to a trusted shared keyring which in turns causes apt to use all of those keys when verifying signatures of packages from any repository.  This compromises trust in package signing.  The proper way is to specify which key should be used to verify packages from which repository.
> chore(apm/php): update steps to verify apt repo signature

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* Minor update: CentOS Stream 8 reached EOL so 9 or higher is recommended / officially supported.
> fix(infra-agent): centOS stream 8 reached EOL

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* Customer feedback requesting better explanation on why this setting is enabled by default in some scenarios.
> fix(infra-agent): Explain status_server is enabled by default when using guided install (install recipe)

- src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-363.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-2.3.60.mdx
Adds release notes for new synthetics-node-browser-runtime release 2.3.60 & missed release notes for synthetics-job-manager release-363 (4/10/2024)
> Synthetics: add release notes for node-browser runtime 2.3.60 & sjm release-363

- src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
This PR adds NRQL comments as a limitation when exporting data as CSV. 
This was a relatively recent discovery reported in our help channels, and the team's decision is to document this issue pending a better Export as CSV solution in the future.
> Add NRQL comments limitation when exporting CSVs

- src/nav/apm.yml
The category "Third-party integrations" was too narrow since not all of these use the Java agent.
> Java agent: Change category to "Related integrations"

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
fix(synthetic-script-docs): Adding Callout for file system restrictions in Synthetic scripts
* Adds clarification about acceptable file storage paths to customers using Synthetics script monitors
> Adding Callout for file system restrictions in Synthetic scripts

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
- add EFS + EKS example detailing how to copy custom modules to a PV prior to launching the SJM
- fix yaml parameter names
> docs: Kubernetes example for custom node modules

- src/content/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data.mdx
Forward slashes are valid in custom event attributes, so let's include them in the documentation.
> Update custom event attribute naming syntax to include forward slash

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
The neteng team spun up some non-ingest privatelink endpoint services in us-east-1, us-west-2 and eu-central-1. This commit adds them to our docs.
We were missing privatelink endpoints for some non-ingest services. Since they are now up we can add them to docs.
> (NR-274256) Add non-ingest endpoints to privatelink docs

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
Add `NEW_RELIC_LAMBDA_HANDLER` to agents and remove from the extension since the extension only really checks to ensure it is set. The variable is actually used by our layers in the handler wrapper code.
> Clarify and fix environment variables

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
- src/content/docs/apm/agents/nodejs-agent/hosting-services/nodejs-agent-microsoft-azure.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent-docker.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx
…
We are about to release v12.0.0 of Node.js agent.  This a semver major that drops support for Node.js 16.  It also merges the standalone Next.js instrumentation (@newrelic/next) into the agent so I updated docs to reflect that as well.
> chore: Updated release date for Node 16, and removed unused `@newrelic/next`

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
The Java agent is not compatible with the newest version of Kafka. Updating docs to reflect that.
> chore(Java): update Java agent's Kafka compatibility

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/enable-serverless-monitoring-aws-lambda-layerless.mdx
This PR fixes some example code in the Python section of the AWS lambda docs.  The original code example template has been deprecated (and non-functional) in 5+ years.
> Fix example code in Python AWS lambda docs

- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-34-0.mdx
Prepares the Go agent docs for the 3.34.0 release.
Release planned for tomorrow 4PM EST.
> (PLANNED FOR 8/5) Release go 3.34.0

- src/content/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent.mdx
PHP team member here.
These instructions were recently modified and we have determined that this change needs to be made to be sure the instructions work on the Alpine Linux platform, which does not use GNU `grep` and requires using a different form of the `--only-match` option .  The change is compatible with GNU `grep` systems as well as these will accept the `-o` short form of the option.
Additionally, the `newrelic.daemon.collector_host` option was included in the original documentation.  After review we have determined this option should not be changed generally and so it was removed from the example.
> chore(PHP): Corrects Dockerfile example

- src/content/eol/2024/08/eol-08-01-24.md
A minor fix that explodes the EOL acronym in the title
> fix(Docs): Wanted to avoid using EOL in titles

- src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/content/docs/browser/new-relic-browser/browser-apis/finished.mdx
- src/content/docs/browser/new-relic-browser/browser-apis/start.mdx
- src/i18n/content/es/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/i18n/content/es/docs/browser/new-relic-browser/browser-apis/finished.mdx
- src/i18n/content/es/docs/browser/new-relic-browser/browser-apis/start.mdx
- src/i18n/content/jp/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/i18n/content/jp/docs/browser/new-relic-browser/browser-apis/finished.mdx
- src/i18n/content/jp/docs/browser/new-relic-browser/browser-apis/start.mdx
- src/i18n/content/kr/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/i18n/content/kr/docs/browser/new-relic-browser/browser-apis/finished.mdx
- src/i18n/content/kr/docs/browser/new-relic-browser/browser-apis/start.mdx
- src/i18n/content/pt/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/i18n/content/pt/docs/browser/new-relic-browser/browser-apis/finished.mdx
- src/i18n/content/pt/docs/browser/new-relic-browser/browser-apis/start.mdx
The browser agent is updating to use the entry field `generic_events` instead of `page_action`.  This PR updates the refs that point at those entry points.  The `page_action` entry will continue to work in the agent for the foreseeable future, but the preferred method of implementation going forward should be `generic_events`.
Please reach out if we need to add more by way of callouts or other disclaimers.
> feat: change page_action refs to generic_events as per new browser agent version change

- src/content/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data.mdx
We are making Entity a reseved event name. This change is to update documentation to reflect this change.
We have some upcoming changes that require us to reserve the Entity event name. This change is to update our public documentation to reflect this so we don't have conflicts down the road.
> feat: Mark Entity as reserved event

- src/content/docs/new-relic-solutions/get-started/networks.mdx
small typo changes to remove HTML tagging on links that are not needed in the doc ([current doc](https://docs.newrelic.com/docs/new-relic-solutions/get-started/networks/#user-facing-domains)) is showing the plain text with tags right now; this cleans that up:
```plain
[www.google.com](http://www.google.com) ==> www.google.com
[www.gstatic.com](http://www.gstatic.com) ==> www.gstatic.com
```
> fix: small typos on markdown links

- src/content/docs/style-guide/writing-docs/writer-workflow/swiftype-search.mdx
We used to use Swiftype to automatically surface relevant docs in the UI based on your location, but we decomissioned that capability over a year ago.
> chore(style guide): Delete docs library service info

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
I am a PHP team engineer.
This update is based on customer feedback.  The INI option `newrelic.error_collector.prioritze_api_errors` is intended to cause errors reported through the `newrelic_notice_error()` API to take precedence over other error types which occur.  However, if an uncaught error error also occurs it will have the highest priority.  This can be confusing if notice'd errors are not showing up and this setting is set to `true`.
I made it a "NOTE:" but perhaps a different formatting (callout?) would be better and I leave this to your discretion.
> chore(PHP): Adds note for API call

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
- src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
These two files were previously not serializing because of indent issues. this fixes serialization and shouldn't change the format of the live pages which can be viewed at https://deploy-preview-18342--docs-website-netlify.netlify.app/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial and https://deploy-preview-18342--docs-website-netlify.netlify.app/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
> Refactor indenting for serialization

- src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.263.0.mdx
- src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.264.0.mdx
The browser agent team's automation was discovered to have a bug that failed to post release notes for the previous two releases.  This PR adds those missing release notes.
> feat: add missing release notes

- src/content/docs/style-guide/images/embed-images.mdx
- src/content/docs/style-guide/structure/side-by-side.mdx
Updated the src attribute on these pages:
- [Embed images](https://docs.newrelic.com/docs/style-guide/images/embed-images/#labeling)
- [SideBySide](https://docs.newrelic.com/docs/style-guide/structure/side-by-side/)
> fix(Style guide): Updated the new image name convention

- src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx
Noticed that the "update" guide for MacOS incorrectly said `Uninstall the agent` as one of the steps, when in fact the step was to upgrade the agent.
> docs: Correct wording on MacOS agent update steps

- src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/content/docs/data-apis/custom-data/custom-events/report-browser-monitoring-custom-events-attributes.mdx
This PR adjusts the page action docs that mention a 120 event limit, which was changed in the latest browser agent release.
> feat: update pageaction apis that mention limit

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
In https://github.com/newrelic/docs-website/commit/23b82a175fcd78f2bb8695b6c3f23ebf991cd370 the markers we use for automating the updating of the compatibility matrix were mutated into a format that the automation tool does not recognize. Please do not change these markers.
> Fix automation markers

- src/content/docs/release-notes/logs-release-notes/logs-24-08-12.mdx
- The release notes have been updated to mention the included support for Ubuntu 24.04 and SUSE 15.5(x86_64).
- Refer to the recently merged PR - [https://github.com/newrelic/open-install-library/pull/1098](https://github.com/newrelic/docs-website/pull/url) for more details.
> NR 298654 - The Infrastructure Agent now supports Ubuntu 24.04 and SUSE 15.5(x86_64).

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* Linux RedHat 7 still has extended support..
* Adding links to Docker (Container) and Kubernetes requirements to avoid data to be out of sync.
> fix(infra-agent): Update supported OS

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
We are removing the ability to configure `replicaCount` for the Synthetics Job Manager in helm charts, and so need to update the configuration docs here to reflect this change.
Helm chart PR: https://github.com/newrelic/helm-charts/pull/1467
> fix: removing the ability to set replicaCount in helm chart, so updating docs to reflect

- src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-751.mdx
New Relic iOS agent 7.5.1 release notes.
> iOS agent 7.5.1 release notes: [Release asap on 8-21-2024]

- src/content/docs/logs/log-api/log-event-data.mdx
The support of browser and mobile logs brings a new set of reserved attributes (`instrumentation.*`)
> NR-304043: The support of browser and mobile logs brings a new set of reserved attributes (`instrumentation.*`)

- src/content/docs/logs/forward-logs/fluentd-plugin-log-forwarding.mdx
@cbehera-newrelic Found while writing release notes. In general, we want headers to have anchor tags. Once you approve this, feel free to merge it in.
> fix(logs): Added missing header anchor tag

- src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
There is an in-page link rendering as plain text:
I didn't see a syntax issue causing this, but noticed it was the only in-page link in this doc that was broken and the only one on a `###` header, the rest were on `##` headers. So I'm trying to see if this fixes it.
I also formatting some code blocks that I find tough to read
> fix: broken in page link

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
- src/content/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-maintenance-monitoring.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests-legacy.mdx
- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/runtime-upgrade-ui.mdx
- Updated all EOL callouts to make it obvious that no new legacy runtime monitors can be created as of Monday
- Added an example NerdGraph mutation that allows you to downgrade the runtime of an existing monitor
It will still be possible to downgrade monitors to the legacy runtime AND edit legacy runtime monitors until the EOL on October 22, 2024.
While we will roll out the no new legacy monitors restriction on Monday, it should be safe to merge this in at any time. It does not have to wait until Monday.
> No new legacy monitors

- scripts/actions/utils/handlers.mjs
Many `span` tags were added to use this new class in tables, and we did not have handlers set up for them causing i18n workflows to fail.
```html                      
<td>
<span class="children-nowrap">`http`</span>
</td>
```
> fix: add handler for `span`

- src/content/docs/logs/log-api/log-event-data.mdx
Reverts newrelic/docs-website#18446
This was not meant to be merged yet, the exact wording is being discussed. Sorry!
> Revert "NR-304043: The support of browser and mobile logs brings a new set of reserved attributes (`instrumentation.*`)"

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
The PHP agent team has announced support for Drupal 11.x and this PR adds it to the compatibility page.
> chore: Adds Drupal 11.x to PHP compatibility

- src/content/docs/browser/new-relic-browser/browser-apis/addtotrace.mdx
Fixing the `addToTrace` browser agent API documentation to remove reference to the `type` field. This field is not used in the agent. The documentation is misleading to customers that may think they can define a value for the `type` field. In reality the agent always set's the `type` field to a value of `api`.
https://new-relic.atlassian.net/browse/NR-302664
> fix: correct addToTrace documentation

- src/content/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx
This update adds documentation for a new customer limit mutation specifically for controlling the per-metric cardinality limit.
> Add initial customer limit mutation docs

- src/content/docs/apis/nerdgraph/examples/combining-npm-nerdgraph.mdx
The GraphQL in the "Retrieve the configuration" section is incorrect.
It returns the config as a script, not an object, as shown in the example.
This PR updates the GraphQL to fix this.
* Fixes incorrect GraphQL
* N/A
* N/A
> docs: update combining-npm-nerdgraph.mdx

- src/install/elasticsearch/default-install-linux.mdx
- src/install/elasticsearch/find-data.mdx
- src/install/elasticsearch/linux/install-apt.mdx
- src/install/elasticsearch/linux/install-linux.mdx
- src/install/elasticsearch/linux/install-yum.mdx
- src/install/elasticsearch/linux/install-zypper.mdx
- src/install/elasticsearch/whatsNext.mdx
- src/install/elasticsearch/windows/install-msi.mdx
- src/install/elasticsearch/windows/install-windows.mdx
Fixed errors in the [Elasticsearch monitoring integration](https://docs.newrelic.com/install/elastic/)
> fix(OHI Elastic): Fixed errors in the installation doc

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Make the compatibility page accurate with respect to support for Joomla framework. PHP Agent only supports Joomla up to release 3.7, which is only compatible with PHPs < 7.2, and 10.22.0.12 is the last agent version supporting those PHPs.
> chore(apm/php): update Joomla compatibility

- src/nav/style-guide.yml
Fixed the navigation file for the style guide. Removed the "/" at the end of a path. This is the file: [Frontmatter and page templates](https://docs.newrelic.com/docs/style-guide/writing-docs/processes-procedures/use-content-types-text-formats/).
> fix(Style Guide): Fixed error in the navigation file

- src/content/whats-new/2024/08/whats-new-8-01-eol-fid.md
The email notice went out late and there have been customer concerns (Verizon) about pulling support going into the holiday season, so NR will continue to report FID through the end of 2024 despite Google ending support for the metric on Sept 9, 2024.
> Extend NR's EOL of FID to end of 2024

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
- src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp.mdx
What problems does this PR solve? 
-> 
updates `stream-logs-using-kinesis-data-firehose.mdx` and `fedramp.mdx` to alert firehose integration to NR is not fedramp supported
Following are the changes made:
1. [FedRAMP doc](https://deploy-preview-18573--docs-website-netlify.netlify.app/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp/)
2. [Firehose doc](https://deploy-preview-18573--docs-website-netlify.netlify.app/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose/)
> fix: [NR-171881] Clearly indicate FedRAMP is not supported for AWS Kinesis Firehose

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors.mdx
Proxy support is available for Firefox monitors using Synthetics Private Locations. This requires the customer to use version 3.0.7 of the synthetics-node-browser-runtime container image or newer.
> feat(SyntheticsFirefox): Added proxy support

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors.mdx
@jeff-colucci Based on style guide, we use "higher or lower" and not "newer or older" when referring to versions.
> fix(Synthetics): Minor style guide edit

- src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-403.mdx
- src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-404.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.86.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.88.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.94.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.4.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.7.mdx
- src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.46.0.mdx
Updates release notes for Synthetics Job Manager, Node API Runtime, Node Browser Runtime, and Ping Runtime.
> chore: catch up release notes for sjm and runtimes

- src/content/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page.mdx
Fixed 2 small typos on the [Kubernetes summary page](https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page/) page.
> fix(K8s): Fixed typo errors

- src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error.mdx
I am a member of the PHP agent team - here is a docs update I'd appreciate having reviewed and formatted (if needed):
Based on customer feedback this PR includes some clarifications for the newrelic_notice_error() API call.
> chore: Updates PHP api docs for newrelic_notice_error()

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
This PR updates the latest versions of the .NET agent's instrumented libraries that we have tested and verified compatible.
This PR also adds a row for `AWSSDK.SQS` (Amazon Simple Queue Service) which we recently added instrumentation for in agent version 10.27.0.
This PR also fixes a few issues I found that were probably introduced by the merging of the .NET Core and .NET Framework versions of this doc into a single unified doc.
> chore: Update .NET compatibility/support docs with latest tested versions of instrumented libraries

- src/content/docs/browser/single-page-app-monitoring/get-started/browser-spa-v2.mdx
@ally-sassman We want to avoid "upgraded" because, according to our style guide, any upgrade incurs additional cost.
Also, would you please remove the (new) from the left nav for this doc? Thanks!
> fix(Browser): Swapped upgraded for updated

- src/content/docs/release-notes/logs-release-notes/logs-24-09-12.mdx
- src/install/aws-logs/cloudwatch/basic-cloudwatch.mdx
We have updated the default value of the NRLoggingEnabled parameter for the New Relic Lambda function from false to true. This change has been released and is now live. The release notes have been updated to reflect this change.
> Update to aws-logs-ingestion Lambda function

- src/content/docs/alerts/overview.mdx
The note was never completely accurate.  With recent changes, no data crosses the US/EU boundary for Alerts so it's not accurate at all.
> Removing inaccurate datacenter note

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
- src/content/docs/apis/nerdgraph/get-started/nerdgraph-explorer.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/build-ab-app/first-chart.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/custom-visualizations/build-visualization.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/nerdpack-file-structure.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/nerdstorage.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/nerdstoragevault.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/nr1-cli/nr1-common.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/query-and-store-data.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/intro-to-sdk.mdx
- src/content/docs/new-relic-solutions/get-started/glossary.mdx
- src/content/docs/new-relic-solutions/new-relic-one/build-nr-apps/serve.mdx
- src/content/docs/new-relic-solutions/new-relic-one/build-nr-apps/set-up-dev-env.mdx
- src/content/docs/new-relic-solutions/tutorials/build-hello-world-app.mdx
- src/content/docs/new-relic-solutions/tutorials/build-react-hooks-app.mdx
- src/content/docs/new-relic-solutions/tutorials/customize-nerdpacks.mdx
- src/content/docs/new-relic-solutions/tutorials/map-pageviews-region.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
- src/content/whats-new/2020/10/store-data-encrypted-storage-solution-nerdstoragevault.md
these links were ported over from the developer site and didn't get updated 
page: `/docs/new-relic-solutions/build-nr-ui/sdk-component/intro-to-sdk`
fixes: links for text field, dropdown item, radio group, and nerdgraph
> Refactor links

- src/content/docs/mobile-monitoring/new-relic-mobile-ios/get-started/new-relic-ios-compatibility-requirements.mdx
Added a small section to the iOS agent compatibility page linking to the watchOS doc. https://new-relic.atlassian.net/browse/NR-307459
> NR-307459 Added a section about watchOS compatibility

- src/content/docs/codestream/observability/code-level-metrics.mdx
- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cosmos-db-document-db-monitoring-integration.mdx
- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations.mdx
> chore: format codeblock

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
> fix(.NET): fixing links in compatibility doc

- package.json
- scripts/build.sh
You can't do a full build without the var but we don't have it set since it depends on the site in netlify. This way we get a little reminder locally
> Add bash script to check for BUILD_LANG var

- src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/chart-types.mdx
> fix(Dashboards): calling out broken billboard chart issue

- src/content/docs/infrastructure/host-integrations/host-integrations-list/couchbase-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/nagios-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/varnish-cache-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx
- src/install/postgresql/windows/install-windows.mdx
- src/install/rabbitmq/windows/install-windows.mdx
For NR-313160.
In Windows instructions, replace any occurrences of the `cp` command with `copy`.
Fix one instance where the Windows restart commands use Linux commands.
> fix(on-host): Replace cp with copy for Windows instructions

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
- src/content/docs/apm/agents/python-agent/hosting-services/install-python-agent-gae-flexible-environment.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/initialize-python-agent-api.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100000.mdx
* Add release notes for Python agent release 10.0.
* Update docs to remove Python 2.7 support.
> Add python agent release notes for 10.0.0 - PLEASE MERGE SEPTEMBER 27th 2024 AM

- src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx
Update the Ruby APM agent specific custom method tracer documentation to reference the new agent v9.14.0+ support for applying custom method tracers automatically based on configuration.
NOTE:
* I'm on the Ruby APM agent dev team
* This PR should not be merged until Ruby agent version 9.14.0 has been released
> Ruby: automatic custom method tracers

- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
Fixed a typo on the [Get started with New Relic](https://docs.newrelic.com/docs/new-relic-solutions/get-started/intro-new-relic) doc.
> fix(Get started): Fixed a typo

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/vulnerability-management/integrations/intro.mdx
New Relic PHP Agent v11.2 adds new configuration settings that enables use of [Composer's runtime API](https://getcomposer.org/doc/07-runtime.md) for package detection (vulnerability management php-agent integration). With added support for Composer's runtime API, PHP APM Agent can be configured to detect vulnerabilities in all packages managed by [Composer](https://getcomposer.org/). The section about Vulnerability Management PHP APM Agent integration needed an update to advertise this new feature.
> feat(apm/php): add `newrelic.vulnerability_management.composer_api.enabled` description

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
This has been an oversight in our docs for a while.  The .NET agent has a limited set of configuration options that can be set via standard Microsoft application configuration files (e.g. `appsetttings.json`).  One of the things that can be set is the `labels` setting, with an appsettings key of `NewRelic.Labels`.  This PR updates the docs to show that labels can be configured this way.
> Add `NewRelic.Labels` to the list of .NET agent configuration options that can be set in app settings

- src/content/docs/errors-inbox/error-users-impacted.mdx
>* Doc page is missing the equivalent set user API call for PHP
>* https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_set_user_id/
> Add missing set user id API call for PHP

- src/content/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data.mdx
We recently added a new prohibited event type, and are updating the docs accordingly.
The event type that should be excluded is `EntityRelationship`, along with `RelationshipUpdate`, `Relationship[0-9]*`.
> Add new prohibited 'EntityRelationship' event type

- .github/workflows/update-whats-new-ids.yml
we now have organization enforced branch protection which doesn't allow pushing directly to default branches, even by admins or those with permission. this updates the whats new action to make a PR with new IDs
> fix: Create PR instead of committing to develop

- src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
- src/content/docs/data-apis/manage-data/view-system-limits.mdx
There were two identical in-page link ids for `"AddCustomAttribute"`. These are linked a lot in the docs so I only changed this one so I don't have to update docs everywhere. With both having the same ID this in page link doesn't work.
> fix: new link name from ISpan.AddCustomAttribute()

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* Remove a misleading note for Windows 2012
* Compatibility explanation for older versions (not officially supported past EOL but agent might still be compatible)
> docs(infra-agent): removing misleading note for Win 2012

- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
Add reference and link to solution to common confusion point and case driver.
Many folks who migrate to Azure Monitor's dimension-heavy metrics are confused by metrics "showing up twice."
This is common case driver.
The issue is addressed in separate doc, but not one users have been likely to see before they migrate. Have added link.
The issue is confirmed in existing doc (linked), but not referenced in place where users are most likely to need it.
* If your issue relates to an existing GitHub …
> docs: Update azure-monitor.mdx to prevent dimensional metric confusion

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-30-0.mdx
Makes a minor change to the .NET agent v10.30.0 release notes related to instrumentation of Azure functions.
> chore(dotnet): Correct release notes for .NET agent v10.30.0

- src/content/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys.mdx
> chore: add syntax highting and formatting to code

- src/install/config/dotnet.yaml
- src/install/dotnet/installation/azure-linux-container.mdx
- src/install/dotnet/installation/azure-windows-container.mdx
Updates the Azure installation workflow to include containerized apps.  Also changes some of the labels and names to better match modern App Service naming as well make things a bit clearer (I hope!).
* Adds install entries for Windows and Linux containers under Azure App Services
* Includes modified dockerfiles that do not include app name or license key - these should be set in Azure
* Includes a step after the dockerfiles covering how to set the license key and app name
* Renames a few buttons to make them a bit clearer
* Moves top level NuGet install button to be first for more visibility *
> .NET Azure: Update Azure installation workflow to include containerized apps.

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-81000.mdx
Add note about dropping redis<4 support into Python agent v8.10.0 release docs.
Fixes https://github.com/newrelic/newrelic-python-agent/issues/1236.
> Add note about dropping redis<4 support

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx
- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
- Fixed a broken link on the scripted browser reference page to Selenium documentation
- Added an additional runtime upgrade troubleshooting example related to form usage. This is less common, but common enough that we should include it.
> fix(Troubleshooting): Broken link fix and additional upgrade example

- src/content/docs/apis/rest-api-v2/migrate-to-nrql.mdx
- src/nav/telemetry-data-platform.yml
We plan to deprecate the REST API that returns metric data. The API calls can be replaced by NRQL queries, which are more flexible and are better supported/documented.
This new page aims to help the customers to migrate from the legacy API to NRQL.
Note:
- I was not able to see my new page when running the app locally, I don't know if I missed a step
- Let me know if the page is not in the right folder, tell me where I should put it
- Same for the page title/content
> Create migration guide for the Rest API v2

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own.mdx
Navigation links in the page are incorrect. The PR rectifies the incorrect links. For example, 
Previously the link was - `/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/cloudwatch-fallback`
But the correct link is - `/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/cloud-watch-fallback` , this points to docs page [here](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/cloud-watch-fallback/).
links to …
> Rectify links for CloudWatch

- src/content/docs/apm/agents/python-agent/troubleshooting/testing-python-agent.mdx
> (fix)Python: changing outdated IPs

- src/content/docs/data-apis/custom-data/aws-privatelink.mdx
There are two supported endpoints for infra in the EU, and only one was included in the public docs previously. This commit adds the second endpoint.
> Add alternate privatelink endpoint for infra in the EU

- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
- src/content/docs/logs/logs-context/configure-logs-context-php.mdx
- src/content/docs/logs/logs-context/configure-logs-context-python.mdx
- src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
- src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
This PR fixes the issues when the log message is empty, customers were seeing our decorator values i.e NR-LINKING string which would be fixed by this PR and if the log message is empty they will see only empty message.
Related Jira ticket:- https://new-relic.atlassian.net/browse/NR-307785
> NR-307785 Update docs with latest bug fix if log message is empty

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests.mdx
Updated URLs for synthetic monitors on the [Store secure credentials for scripted browsers and API tests](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests) page.
This is a request from this:  [https://github.com/newrelic/docs-website/issues/18985](https://github.com/newrelic/docs-website/issues/18985)
> fix(Synthetics): Updated URLs for synthetic monitors

- src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx
This article describes the specifications for how the ServiceName is converted by the Prometheus exporter. https://github.com/prometheus-community/windows_exporter/blob/master/internal/collector/smb/smb.go#L129-L135
> The ServiceName is not exactly the same as the Windows UI.

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
A TAM pointed out that this was confusing. After digging, I found out the default value should be `false` and the description should state when `true`, it will redact error messages.
> chore: Fixed a default value and description for `strip_exception_messages`

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
This came up as a suggestion from an SME.
> fix (NRQL): Adjust consumption queries to include SINCE clause

- src/components/HomepageBanner.js
Gets rid of the old search bar
> fix: Remove old search input

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx
- **Documentation Links**: Updated links for Python and Ruby sections to align with the formatting used in the Java and Node.js documentation.
- **Containerized Examples**: Added new example links for Lambda functions in containerized environments across the Java, Python, and Node.js tabs for improved reference and accessibility.
> docs NR-305269: Updated links of layer images and Added links for examples of containerized lambda functions.

- src/content/docs/logs/forward-logs/kong-gateway.mdx
- src/content/whats-new/2024/10/whats-new-10-23-kogs-gateway-logs-integration.md
Fixed a broken link on the [Forward logs from Kong Gateway to New Relic](https://docs.newrelic.com/whats-new/2024/10/whats-new-10-23-kogs-gateway-logs-integration/) doc.
> fix(Whats new): Fixed a broken link

- src/content/docs/network-performance-monitoring/advanced/ktranslate-container-health.mdx
- src/content/docs/network-performance-monitoring/troubleshooting/change-ktranslate-versions.mdx
- src/content/docs/network-performance-monitoring/troubleshooting/ktranslate-cpu-usage.mdx
- src/content/docs/network-performance-monitoring/troubleshooting/understanding-snmp-utilization-calculations.mdx
- src/nav/network-performance-monitoring.yml
Replaced `Ktranslate` with `KTranslate`.
> fix(Doc site): Replaced Ktranslate with KTranslate

- package.json
- yarn.lock
updating gatsby theme version.
Contains the update to redirect to local sites when clicked on new relic banner
> chore: update gatsby-theme-newrelic version

- src/content/docs/nrql/nrql-tutorials/introduction-nrql-tutorial.mdx
- src/content/docs/nrql/nrql-tutorials/nrql-tutorial-advanced-dashboarding.mdx
- src/content/docs/nrql/nrql-tutorials/nrql-tutorial-advanced-functions.mdx
- src/content/docs/nrql/nrql-tutorials/nrql-tutorial-process-your-data.mdx
The backslash is an escape char, so having two in a row in plain text only renders one of the two, you need to wrap it in backticks, or do 4 in a row to render two as intended.
How this renders now:
> fix: wrap `\\` in backticks

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Adds a link in the .NET Agent requirements that offers a workaround if your chosen datastore is not supported.
> Add custom instrumentation link to .NET datastore instrumentation info

- src/content/docs/nrql/using-nrql/funnels-evaluate-data-series-related-events.mdx
Happened to notice what I assume is a typo in the docs for funnel.
> docs: typo in funnels doc

- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Jira Issue: [NR-2530](https://new-relic.atlassian.net/browse/NR-2530)
Formally documents where clause as the second argument for percentage().
(Part of backlog removal push)
[NR-2530]: https://new-relic.atlassian.net/browse/NR-2530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: updating percentage() docs

- src/content/docs/apm/agents/java-agent/frameworks/scala-installation-java.mdx
This PR adds additional details to our Scala documentation. It expands a discussion of our instrumentation for Scala futures. 
We had a [ticket](https://github.com/newrelic/newrelic-java-agent/issues/2053 ) come in recently that we looked into and wrote a detailed comment for. The issue exposed a hole in our current documentation that we thought we be good to fill for future users, and for ourselves. 
The code snippets and technical content have been reviewed for accuracy.
> chore: update scala-installation-java.mdx to include Futures section

- src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
Per a request in the help-documentation channel (10/25/2024) and following Liz advice, I've removed the ids from the nested collapsers on the [.NET agent API](https://docs.newrelic.com/docs/apm/agents/net-agent/net-agent-api/net-agent-api) doc.
> chore(Net agent): Removed ids from nested collapsers

- src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-handled-exceptions.mdx
Per a request in the help-documentation channel (10/25/2024), fixed duplicated `TabsPageItems` and anchor links on the [Record handled exception](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-handled-exceptions) doc.
> fix(Mobile monitoring): Fixed duplicated TabsPageItems and anchor links

- src/content/docs/alerts/admin/rules-limits-alerts.mdx
- src/content/docs/alerts/create-alert/condition-details/alert-custom-incident-descriptions.mdx
- src/content/docs/alerts/create-alert/create-alert-condition/alert-conditions.mdx
- src/content/docs/alerts/create-alert/examples/define-custom-metrics-alert-condition.mdx
- src/content/docs/alerts/get-notified/intro-notifications.mdx
- src/content/docs/new-relic-solutions/get-started/glossary.mdx
Per a request in the help-documentation channel (10/25/2024), fixed broken links on the [Alerting rules and limits](https://docs.newrelic.com/docs/alerts/admin/rules-limits-alerts/) doc.
> fix(Alerts): Fixed broken links

- src/content/docs/alerts/admin/rules-limits-alerts.mdx
We are adding a new limit that will be enforced on alert query registration, so this commit adds some documentation around the default limit and adds some pointers on working with it.
* This PR adds a blurb to documentation about a limit that will be added soon around alert queries (conditions).
> (NR-320588) Adding some documentation for a new query limit

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
The .NET agent just released auto-instrumentation for `AWSSDK.DynamoDBv2` which is a database client in .NET.  This PR adds info to the compatibility and requirements document for this library.
> .NET Agent: Add AWSSDK.DynamoDBv2 to the list of datastore clients instrumented

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-otel-applications-kubernetes.mdx
Added the caution note about the summary page on the [Link OpenTelemetry-instrumented applications to Kubernetes](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-otel-applications-kubernetes/).
Request (10-31-2024) from the [help-k8s-experience](https://newrelic.slack.com/archives/C043X7A8JRF/p1723651316136359) Slack channel.
> fix(K8s): Added the caution note about the summary page

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
I forgot to add this info to both section (Framework and Core) for the .NET agent yesterday.  This PR corrects the oversight.
> chore: .NET agent, forgot to add DynamoDB to the other section

- gatsby-config.js
- plugins/gatsby-source-install-config/gatsby-node.js
- scripts/actions/utils/docs-content-tools/i18n-exclusions.yml
- scripts/actions/utils/handlers.mjs
to test you'll need to edit the start script in the package.json and replace BUILD_LANG=en with BUILD_LANG=jp. then create a few folders resulting in these paths: `i18n/install/config/jp` and `i18n/install/jp`. copy the config yaml for java and plop it into `i18n/install/config/jp`. then copy an mdx file from the java mdx and put it in the `i18n/install/jp` folder. edit that file to look different in some way. finally in the i18n config yaml edit the step path that relates to that mdx file to match the i18n path, e.g. `src/i18n/install/jp/java/createDirectory.mdx`. run locally as normal and the install page should have picked up on the alternative mdx for the chosen step
> Translate install mdx

- src/components/SEO.js
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/add-on-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/licenses/license-information/usage-plans/archived-add-on.mdx
- src/content/docs/licenses/license-information/usage-plans/new-relic-usage-plan.mdx
This PR is to insert archived pricing and product descriptions for the old Add On compute option.
> fix(accounts): Migrate archived pricing to public site

- src/content/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx
- src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx
- src/content/docs/apm/agents/ruby-agent/attributes/enable-disable-attributes-ruby.mdx
- src/content/docs/apm/agents/ruby-agent/attributes/ruby-attribute-examples.mdx
- src/content/docs/apm/agents/ruby-agent/configuration/distributed-tracing-ruby-agent.mdx
- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/features/developer-mode.mdx
- src/content/docs/apm/agents/ruby-agent/features/record-deployments-ruby-agent.mdx
- src/content/docs/apm/agents/ruby-agent/installation/ruby-agent-installation-rails-plugin.mdx
Add or correct the syntax highlighting language/format for some Ruby agent code blocks
> Markdown syntax highlighting tweaks for Ruby

- src/content/docs/alerts/scale-automate/rest-api/rest-api-calls-alerts.mdx
you can't have hyperlinks in formatted codeblocks, it renders as plain text:
> fix: remove `<a>` tags from codeblocks

- src/content/docs/apm/agents/net-agent/configuration/distributed-tracing-net-agent.mdx
1. Link to the correct APIs in the API guide doc
2. Add link to buildable/runnable example in our agent's examples repo
3. Add callout regarding the need to find a "carrier" for key-value pairs in whatever message object the customer is working with
> docs: Clean up the manual distributed tracing section of the .NET agent's main distributed tracing doc

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
Edited the line within the 'Browser and mobile trace reporting' section to remove the '[' that appears to have been left in by accident:
"used in conjunction with mobile monitoring and [browser monitoring, "
> Fix: Removed an unnecessary '[' from the text.

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
The PR adds a cloud configuration section to the node.js agent configuration page. Right now, the only item in the cloud config is for `cloud.aws.account_id`.
Relates to https://github.com/newrelic/node-newrelic/pull/2691 and https://github.com/newrelic/node-newrelic/pull/2701
> feat: added cloud variables configuration section

- src/content/whats-new/2024/11/whats-new-11-11-data-explorer.md
We had a "What's new" post that was pointing to the old local `image` directory. This should correct that.
> fix(What's new): Correct the image paths

- src/content/docs/apm/agents/net-agent/configuration/distributed-tracing-net-agent.mdx
This PR fixes some links in the .NET agent's distributed tracing doc, specifically to the API guide for the manual DT APIs.  We are unable to link directly to the APIs because they are in a "collapser-nested-inside-a-collapser", specifically the `ITransaction` collapser.  This PR changes the links to go to the `ITransaction` section, from which it should be easy enough to find the specific APIs.
> Fix links in .NET agent manual distributed tracing doc

- src/content/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api.mdx
- The values for "timestamp" key in the example payloads were "CURRENT_TIME," which were invalid as per the "Required key-value pairs" table. Updated the values with some epoch time samples.
- Refactored a sentence from passive voice to active voice.
> chore(metric API): timestamp value update

- src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx
- src/content/docs/alerts/overview.mdx
* What problems does this PR solve? Since correlation services move to AWS from GCP. The Alerts (including Incident Intelligence product is not subject to region restrictions anymore. Thus removing those notes presence.
* Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.
This has been approved by SLCreview. See relevant ticket.
> Chore: remove region restriction notes on alerts product

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
* Adds PHP to the list of supported languages for the K8s Agent Operator.
* Corrects a reference to java in a ruby-specific example.
* Formatting fixes.
> chore(k8s): add PHP to k8s agent operator support

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
.NET 9 just went GA: https://devblogs.microsoft.com/dotnet/announcing-dotnet-9/
This PR:
* Adds .NET 9 to the list of runtimes the .NET agent is compatible with
* Adds ASP.NET Core 9 to the list of web frameworks the .NET agent instruments
* Attempts to clarify our support stance on out-of-support versions of .NET.  The .NET agent actively refuses to profile any .NET application targeting a .NET Core runtime older than .NET Core 3.1.  For .NET Core 3.1 and newer, the agent will likely work.  However, Microsoft no longer supports .NET versions older than .NET 8.  We can only support (as in, provide tech support and bug fixes for) the agent instrumenting older versions so far; if the issue looks like a runtime problem we won't work on it.
* Removed a stray item about an unsupported .NET …
> chore: Announce support for .NET 9 in .NET Agent compatibility document

- src/content/docs/infrastructure/infrastructure-data/default-infra-data.mdx
This PR adds add the default information for Network Sample default filtered devices.
> docs: add default information for Network Sample default filtered devices

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
correct spelling of $headers.removeMultiple()
$headers.removeMmultiple() should be $headers.removeMultiple()
> docs: corrected spelling

- src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
This PR updates the .NET agent API doc, specifically for the `SetTransactionName()` API call.  I mainly added expanded examples, one for a web app and one for a console app, that should help clarify what this API does and does not do.
> docs: .NET Agent: Add clarifying examples to SetTransactionName API doc

- src/content/docs/nrql/nrql-tutorials/nrql-tutorial-advanced-functions.mdx
> Fix typo in nrql-tutorial-advanced-functions.mdx

- src/content/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking.mdx
The docs still stated sessionStorage as being used, but it has been localStorage that has been used for quite some time now. Also corrected the mention of localStorage to start with lower case letter.
> Fix: Change from sessionStorage to localStorage

- src/content/docs/infrastructure/infrastructure-agent/requirements-infrastructure-agent.mdx
* Added callout for OS which does not support logforwarding in [infra-agent docs](https://docs.newrelic.com/docs/infrastructure/infrastructure-agent/requirements-infrastructure-agent/#os)
> Add callout for OS which does not support logforwarding

- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/simple-scripted-or-scripted-api-non-ping-errors.mdx
old: ensure that **the the** sum of the provided timeouts to these steps does not exceed 180 seconds.
update: ensure that **the** sum of the provided timeouts to these steps does not exceed 180 seconds.
> Remove duplicate word under JobTimeoutError

- src/content/docs/infrastructure/infrastructure-agent/configuration/configure-infrastructure-agent.mdx
- src/content/docs/infrastructure/infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Clarifies how setting configuration options for the infrastructure-agent with environment variables work with system services.
https://newrelic.slack.com/archives/C5A2QGLKT/p1731946333684059
> docs: clarify environment variable and system service relationship for config

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100301.mdx
This PR provides the release notes for Python Agent v10.3.1.
> Python Agent v10.3.1 release notes

- src/content/docs/apm/agents/python-agent/python-agent-api/settransactionname-python-agent-api.mdx
* Fixes missing newline in python agent api documentation example code.
> Fix missing newline in Python agent example code -- Merge Nov 27

- src/content/eol/2024/04/eol-04-24-24-polling-api.md
New Relic will end support for the Azure SQL database integration polling API, because Azure is deprecating the SDK that the polling API uses. But this date has been changed from December 1st 2024 to July 31st 2025. So, we will be extending support for the same till 31st July 2025.
> Updated the support date for Azure SQL database

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
Fixed the link that is directing to the entity definitions repo looking for all 'definition.yml' files inside the 'entity-types' repo.
Change in the page: /docs/network-performance-monitoring/advanced/advanced-config/#devices
> fix(Advance-config): Fixed the link directing to the entity definitions repo

- src/content/docs/new-relic-solutions/business-observability/intro-pathpoint.mdx
- Add a direct link to the Pathpoint catalog page
- Remove a couple of unnecessary sentences
> Add direct install link to Pathpoint

- src/content/docs/mobile-monitoring/new-relic-mobile-ios/configuration/ios-remote-logging.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx
- src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-753.mdx
- src/nav/mobile-monitoring.yml
https://new-relic.atlassian.net/browse/NR-334798
These docs changes are to add information on the newly created feature of the iOS agent to collect the stdout and stderr output of the apps it instruments. 
Do not merge this before December 3rd
> NR-334798 Created docs that explain the new auto collected logs in the iOS agent (December 3rd)

- src/content/docs/logs/logs-context/custom-tags-agent-forwarder-logs.mdx
The Node.js agent added support for tagging in agent version 12.8.0.
> fix(Node.js): Fixed docs about node agent support tagging

- src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/query-and-storage/EntitiesByDomainTypeQuery.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/query-and-storage/EntitiesByGuidsQuery.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/query-and-storage/EntitiesByNameQuery.mdx
- src/content/docs/new-relic-solutions/build-nr-ui/sdk-component/query-and-storage/EntitySearchQuery.mdx
The property `sortBy` was deprecated while ago in favor of `sortType`.
In the PR I also added some missing examples to show how `sortType` is used.
The deprecation is already over, the plan is to remove `sortBy` as soon as possible but first we have to verify that it is not used, so we are going to implement its use. In no case we are going to remove the property if it has use.
> docs: Document sortType and flag sortBy as deprecated for entities query components

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This came out of a conversation with Bob on the Node team a few months ago and I forgot to make a PR for it until now.  This config option is really confusing or a lot of customers so I think it's worth expanding with some concrete examples.
> chore: expand the query/route parameter section

- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
`application_config` is not a valid configuration option.  I believe it was meant to be `application_logging`.
> doc: fix invalid config reference for logging

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
The Ruby < 3.0 restriction is no longer accurate.
> Remove Ruby version restriction

- src/nav/mobile-monitoring.yml
The name of this file was changed right after it was first created, but the link has never updated to reflect that. This PR should fix that link. 
The target file is: src/content/docs/mobile-monitoring/new-relic-mobile-ios/installation/xcframework-installation.mdx
The commit where the filename was changed is: https://github.com/newrelic/docs-website/commit/4410df08b7bf51a6abf332fabeea1deb8931045a
> docs: Update broken xcframework-installation link in mobile-monitoring.yml

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
This document is out of date. This PR provides the following updates:
* adds support for Rails / Active Record 7.1, 7.2 and 8.0
* adds OpenSearch reference
> chore: Update ruby-agent-requirements-supported-frameworks.mdx

- src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Syslog TCP endpoint will include a new mechanism to allow customers to forward logs from platforms that doesn't allow to edit the syslog format, like AirWatch.
In this case the licenseKey will be parsed from message itself if prefixed with nrLicenseKey=
This PR document this new mechanism and how to use it.
> docs(logs): Add new syslog mechanism to send the license key

- src/content/docs/infrastructure/other-infrastructure-integrations/monitoring-jenkins-ot.mdx
The quickstart dashboard needs updated if a customer uses anything other than jenkins for the service name. This isn't obvious in the current form of the doc, so I added an additional step.
> chore: Add step to update Jenkins entity.name WHERE statements

- src/content/docs/logs/ui-data/timestamp-support.mdx
When looking into a support ticket, I noticed that the Logs API docs were confusing about which fields we'd use as a timestamp. This PR attempts to clarify that.
Note that `log_timestamp` is only used in built-in parsing rules, and we intentionally don't use that attribute as the log time, maybe because originally we weren't confident that the parsing rules could parse timestamps correctly?
> fix: Make it clear that we publicly just support `timestamp` as the log timestamp

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
I added these examples to the attributes include/exclude section recently, but I realized I added it only to the TransactionTrace include/exclude section when it should have been in the global section.
> fix: move include/exclude examples to the global section

- src/content/docs/apis/nerdgraph/examples/async-queries-nrql-tutorial.mdx
As the Dirac CAT team aims to add cancel async query to Nerdgraph, we are looking to add a block to explain to customers how to do so. We are adding onto the existing Nerdgraph async query document to keep everything cohesive and in one doc.
> feat: Add Cancel Query Nerdgraph Block

- src/content/docs/browser/new-relic-browser/browser-apis/recordCustomEvent.mdx
- src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
- src/content/docs/data-apis/custom-data/custom-events/report-browser-monitoring-custom-events-attributes.mdx
- src/content/docs/data-apis/custom-data/custom-events/report-custom-event-data.mdx
This PR adds documentation around a new API being released by the browser agent in v1.277.0.  It also updates some old docs that were out of date in some regards.
> feat: document record custom event api for upcoming Browser Agent release

- src/content/docs/apm/agents/go-agent/installation/install-automation-new-relic-go.mdx
https://github.com/newrelic/go-easy-instrumentation/releases/tag/0.5.0
Brings the docs for go easy instrumentation up to date with the latest state of the project.
> fix: update go easy instrumentation docs to 0.5.0

- src/content/docs/vulnerability-management/integrations/intro.mdx
Omitted minor version of PHP APM agent in the description, as suggested by PM. Linked to [NR-351079](https://new-relic.atlassian.net/browse/NR-351079)
[NR-351079]: https://new-relic.atlassian.net/browse/NR-351079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore(Vulnerability-integration): Omit minor version of PHP APM agent in description

- src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx
- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8170.mdx
New Java Agent docs for the 8.17.0 release. Please merge as soon as possible.
> Update java agent docs for 8.17.0 release

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx
Corrected redirect path to env vars page.
> Update containerized-images.mdx to correct link for env vars

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/env-variables-lambda.mdx
Changing the description for NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
> Update env-variables-lambda.mdx to correct description

- src/content/docs/alerts/get-notified/destinations.mdx
As per [this slack request](https://newrelic.slack.com/archives/C084BRFD831/p1734014599821469), I have add the EOL note for Microsoft Office 365 webhook-based connectors in Teams. We will remove this note once [this ticket](https://new-relic.atlassian.net/browse/NR-353569) gets closed.
> Added the Microsoft Team Webhook-based connector EOL information

- src/install/aws-cloudwatch/intro.mdx
- src/install/config/aws-cloudwatch.yaml
Fixed the broken link in the Introduction to infrastructure monitoring page for AWS as per [issue_19560](https://github.com/newrelic/docs-website/issues/19560)
> chor: fix broken link

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
* Added call out to reference domain capture feature.
* Ticket: NR-293577
> Chore(user management): Added domain capture reference

- src/content/docs/query-your-data/explore-query-data/dashboards/dashboard-template-variables.mdx
> chore: format nrql clauses

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
This restores the markdown based tables in compatibility report.  Our agent automates updating this as our deps that we certify change.  This has been around for almost a year and cannot be changed, [PR that introduced this](https://github.com/newrelic/docs-website/pull/17321/files).  It looks like this [commit](https://github.com/newrelic/docs-website/commit/f8c8f6f3ea3d6df89422ae28400aa8fca2aeeb1a) broke it. Back in august we had to fix this [here](https://github.com/newrelic/docs-website/pull/18401). Please put into your process docs that this cannot be changed.
This PR restores the begin/end markers and seeds it with our latest information. Here's an example [PR](https://github.com/newrelic/docs-website/pull/19624) that you will see in the future as …
> chore: restores the markdown based compatiblity with the begin/end markers

- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-5-0-18.mdx
Adds release notes for PHP Agent release 11.5.0.18
> feat(PHP): 11.5.0.18 Release Notes

- src/content/docs/apm/agents/java-agent/api-guides/guide-using-java-agent-api.mdx
This code block was ugly and tough to read, so I put it in a codeblock
> fix: poorly formatted code

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
This is a followup to #19711 to add another comment explaining not to change the formatting nor contents of the data between the begin/end compat-table comments.
> chore: Aded another comment explaining not to change the formatting nor contents of the markdown on the Node.js compatiblity page

- src/content/docs/logs/ui-data/parsing.mdx
This PR fixes the grok action name along with the indentation which was incorrect for one of the config parameter.
> [NR-353267] Fix Action name and indentation

- src/content/docs/change-tracking/change-tracking-view-analyze.mdx
This PR updates the content at https://docs.newrelic.com/docs/change-tracking/change-tracking-view-analyze/ with additional details around how change tracking markers are selected for inclusion on a chart.
We have received multiple queries in the past regarding the logic governing how Change tracking markers are included on a chart. This pull-request will add a bit of explanation to help demystify that logic.
> docs(NR-290692): add clarifying verbiage on how markers are included on NRQL charts

- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
The content was misleading, the section is on the right side of the platform and not on the left
> Updated the information from Left to Right

- src/content/whats-new/2025/01/whats-new-01-22-React18-upgrade.md
This "what's new" should be published immediately as aligned in https://newrelic.slack.com/archives/C088N42DH5G/p1737477671630779
The contents (https://docs.google.com/document/d/1cuV9n76ueExsi988--kkqyeSA-qllU-9oiHhJIhND4U/edit?tab=t.0) have already been aligned and reviewed and don't need any further reviews.
> "What's new" React 18 upgrade

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Updates the .NET agent configuration documentation to include the `<cloud>` element.
> docs(dotnet): Add documentation for the `<cloud>` configuration element.

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Updates documentation for the `<log>` configuration element to reflect .NET agent behavior as of version 10.35.0.
> docs(dotnet): Update log configuration documentations to reflect behavior in the latest agent version.

- src/install/mysql/whatsNext.mdx
- nri-mysql on host integration now also supports Mysql 8.0 and above.
- The query cache variables are removed from MySQL 8.0 [refer](https://dev.mysql.com/doc/refman/5.7/en/query-cache-status-and-maintenance.html) which need to be reflected in the docs after the feature gets released.
- https://github.com/newrelic/nri-mysql/commit/8a56a6331727a35a4e8e2d3931665e686dfedd9c
> docs: updated mysql whatsNext.mdx to reflect Mysql 8.0 and above support

- src/content/docs/release-notes/docs-release-notes/docs-1-24-2025.mdx
> docs release notes

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/initialize-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/i18n/content/es/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/es/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/es/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/i18n/content/es/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/es/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/initialize-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/initialize-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/initialize-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/pt/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
This PR updates the following: 
- the list of supported Python versions for the Python Agent
- the Python version that will be supported in the future (3.14) and the estimated dates for support
- links to official Python documentation to a more-up-to-date version of Python
> Python Agent: Update supported Python versions and links

- src/content/docs/new-relic-solutions/get-started/networks.mdx
Removing regional data center references because we no longer have data centers and can use this IP space in any cloud globally.  We also have globally available services vis CDN that are affected by the legacy, regional data center references.  This request is coming from the New Relic Network Engineering team, who is responsible for our public IP space.  Please DM me if there are questions.
> Update NR public IP space in networks.mdx

- src/content/docs/network-performance-monitoring/advanced/ktranslate-container-health.mdx
Added a way to check the Linux package logs locally.
> How to check the log for the Linux packaged version of KTranslate

- src/data/popovers_en.json
Fixing the broken link issue in the inline pop-up at https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/ for userKeys. We received this request in [this slack thread](https://newrelic.slack.com/archives/C0DSGL3FZ/p1738076995900659) on #help-documentation channel.
> chore: fix the broken link for inline popups

- src/content/docs/apm/agents/java-agent/instrumentation/instrument-aws-sqs-message-queues.mdx
- src/nav/apm.yml
Adds a new doc for the APM Java agent that explains how to use distributed tracing with the Amazon SQS SDK
> add sqs docs for java apm

- src/content/docs/service-level-management/consume-slm.mdx
- src/content/docs/service-level-management/create-slm.mdx
> chore: fix broken link

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
Currently used specification of environment variables to use in the yaml file is not correct. See https://opentelemetry.io/docs/collector/configuration/#environment-variables for details
> Fix convention for environment variables

- src/content/docs/opentelemetry/best-practices/opentelemetry-best-practices-resources.mdx
Supersedes #19847 and #19846.
Adds a new section that models how we want to document relationships between our Amazon CloudWatch Metric Streams integration and OpenTelemetry services.
@Sanjalee-NewRelic please review this PR. I have not personally vetted the details because I have never used our Amazon CloudWatch Metric Streams integration. I'm relying on you to ensure the information is accurate. Let's settle on the format of this PR and get it merged before you open up more PRs.
> Document relationships between AWS integrations and OTel services

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-managed-kafka-msk-integration.mdx
Currently, the link to the AWS CloudWatch Metric Streams integration in the `Important` callout box results in a 404. This PR updates the link to redirect to the appropriate page.
> Update with correct link

- src/content/docs/serverless-function-monitoring/azure-function-monitoring/compatibility-requirement-azure-monitoring.mdx
Clarifies the runtime stacks that are currently supported for Azure Functions.
> docs(azure-functions): Update supported runtimes for Azure Functions.

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-6-0-19.mdx
This PR updates the documentation to reflect the new release and features of the PHP Agent 11.6.0.19 with expected release date of noon PST on Feb 18 2025.
> PHP Agent Release 11.6.0.19 (Feb 18 2025)

- src/content/whats-new/2025/02/whats-new-02-18-new-access-management.md
feat(whats-new): new role and access grant
* What problems does this PR solve? - We are adding a new role, a new standard access grant, and updating an existing standard role with more capabilities.
links to related docs, screenshots, etc. - All of the links are in the markdown
> "What's new" new role and access grant

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
* Adds OpenAI (and Azure.AI.OpenAI) to the list of supported LLM frameworks for the .NET agent.
* Updates AWS Bedrock, OpenAI and Azure.AI.OpenAI to clarify the methods that are instrumented.
> docs(dotnet): Add OpenAI to supported LLM frameworks

- src/content/docs/serverless-function-monitoring/azure-function-monitoring/compatibility-requirement-azure-monitoring.mdx
Update Azure Function documentation to list .NET Framework 4.8 as a support Azure Function runtime stack, as of .NET agent v10.37.0.
> docs(dotnet): Add .NET Framework to supported Azure Function stacks

- .github/workflows/add-untranslated-files-to-translation-queue.yml
- package.json
- scripts/actions/add-untranslated-files-to-translation-queue.js
Adding a workflow to send n number of untranslated file. This is the high level steps code does:
1. Recursively locates translated MDX files in the i18n directory.
2. Gathering already translated or in-process files by querying the translations database.
3. Collecting all MDX files from the English content directory.
4. Filtering files for translation based on exclusion lists (i18exclusion.yml), number 3, and number 4 above.
5. Selecting a specified number of files needing translation (based on the input) and adding them to the translation queue.
> feat: adding a workflow to send n number of untranslated files

- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-register-error-group-callback-to-set-fingerprint.mdx
- src/content/docs/apm/agents/java-agent/getting-started/migration-8x-guide.mdx
- src/content/docs/apm/agents/java-agent/heroku/no-data-appears-heroku-java.mdx
- src/content/docs/apm/agents/java-agent/troubleshooting/generate-debug-logs-troubleshooting-java.mdx
- src/content/docs/apm/agents/java-agent/troubleshooting/host-links-missing-java-apps-apm-summary.mdx
- src/content/docs/apm/agents/java-agent/troubleshooting/no-data-appears-java.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx
- src/content/docs/apm/agents/php-agent/advanced-installation/install-new-relic-php-agent-gae-flexible-environment.mdx
- src/content/docs/apm/agents/php-agent/frameworks-libraries/wordpress-fullstack-integration.mdx
- src/content/docs/apm/agents/php-agent/getting-started/new-relic-daemon-processes.mdx
- src/content/docs/apm/agents/php-agent/installation/update-php-agent.mdx
- src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_add_custom_parameter.mdx
- src/content/docs/apm/agents/php-agent/troubleshooting/segmentation-faults.mdx
> chore: format code & add syntax highlighting

- src/content/docs/apis/nerdgraph/examples/manage-live-chart-urls-via-api.mdx
- src/content/docs/apis/nerdgraph/examples/manage-live-dashoard-urls-via-api.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx
- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/prerequisites-to-share-dashboards-charts.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-internally.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
- src/nav/dashboards.yml
- src/nav/telemetry-data-platform.yml
Created this new PR having all the Public Dashboard related updates in https://github.com/newrelic/docs-website/pull/19748
Due to merge conflicts in the above PR, creating this fresh PR.
> feat(fresh-public-dashboard) Feb release-Doc update for Public dashboard

- src/content/docs/browser/new-relic-browser/configuration/change-browser-agent-type.mdx
Adds a new table in "Change browser agent type" page to show differences in included agent features based on browser agent type. This is to avoid confusion from customers on what features are supported by which agent type.
JIRA: https://new-relic.atlassian.net/browse/NR-121970
> chore: Add browser agent features table

- src/content/docs/opentelemetry/best-practices/opentelemetry-best-practices-resources.mdx
@Sanjalee-NewRelic @vinaykonatala @AravindKumar8520
> Update documentation for OTel -> AWS infra relationships

- src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/iframes.mdx
- src/nav/browser.yml
Adds a new page in session replay called "Session replay and iframes". This makes it easier for users to find important information relating to how iframes behave with our session replay feature.
JIRA: https://new-relic.atlassian.net/browse/NR-312740
> chore: add iframe section page for session replay

- src/content/docs/apm/agents/python-agent/configuration/distributed-tracing-python-agent.mdx
This PR updates the links and wording of the Python Agent's Distributed Tracing page.  The Python Agent has since deprecated the create/accept payload APIs and has moved towards insert/accept headers APIs.  The docs no longer link to nor reference the old APIs
> Update Python DT page

- src/install/npm/network-flow/linux-eu.mdx
- src/install/npm/network-flow/linux-us.mdx
- src/install/npm/snmp/linux-eu.mdx
- src/install/npm/snmp/linux-us.mdx
- src/install/npm/snmp/linux-usfedramp.mdx
- src/install/npm/syslog/linux-eu.mdx
- src/install/npm/syslog/linux-us-fedramp.mdx
- src/install/npm/syslog/linux-us.mdx
Network requirements table has an old CDN endpoint listed for AWS CloudFront:
Old domain: 
```
aschneider@~/Desktop: dig  @1.1.1.1 d28dx6y1hfq314.cloudfront.net
; <<>> DiG 9.10.6 <<>> @1.1.1.1 d28dx6y1hfq314.cloudfront.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57109
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;d28dx6y1hfq314.cloudfront.net.	IN	A
;; AUTHORITY SECTION:
cloudfront.net.		60	IN	SOA	ns-418.awsdns-52.com. hostmaster.cloudfront.net. 1377556270 16384 2048 1048576 60 …
```
> Updated network dependencies table

- src/install/ai-monitoring/agent-lang/dotnet-config.mdx
Configuration examples for enabling AI Monitoring in the .NET agent were incorrect. This PR fixes that documentation.
> docs(dotnet): Fix incorrect configuration examples for AI Monitoring with the .NET agent.

- src/content/docs/nrql/using-nrql/query-time-range.mdx
I noticed one of the examples has an extra decimal before the milliseconds of a timestamp.
> Remove erroneous second decimal in query-time-range.mdx

- src/content/docs/alerts/create-alert/create-alert-condition/alert-conditions.mdx
- src/content/docs/alerts/create-alert/create-alert-condition/create-nrql-alert-conditions.mdx
- src/content/docs/apis/nerdgraph/examples/manage-live-dashboard-urls-via-api.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx
- src/content/docs/infrastructure/amazon-integrations/connect/set-up-auto-discovery-of-aws-entities.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/prerequisites-to-share-dashboards-charts.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
Final check corrections of the following PR:
https://github.com/newrelic/docs-website/pull/19667 
https://github.com/newrelic/docs-website/pull/19933 
https://github.com/newrelic/docs-website/pull/19853 
https://github.com/newrelic/docs-website/pull/20055 (https://newrelic.slack.com/archives/C089HKDB2HM/p1740484816691159)
#19937 (Only Maps part)
> chore(Fed release items): spell checks, link corrections, code snippet update

- src/content/docs/opentelemetry/best-practices/opentelemetry-best-practices-logs.mdx
- src/content/docs/release-notes/logs-release-notes/logs-25-02-17.mdx
We recently added support for complex data types (mainly KeyValueLists) in both OTLP LogRecord#attributes and LogRecord#body.
We think this doc update is required to let customers now about this extended support.
> NR-367015: Complex data types in body and attributes of OTLP Log Records

- src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/troubleshooting-session-replay.mdx
language identifiers are case sensitive `html` works, `HTML` doesn't
> fix: html syntax highlighting

- src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx
Added exceptional cases where we might see both legacy externals and uninstrumented guids
* Added the exception cases where we might see both legacy external and uninstrumented for the same externals in the entity relationships for the services.
* This occurs when the entity relationships resolves external services with uninstrumented guids is deployed to prod.
* The feature is on hold, will update this doc with more details if required after the release
> fix: Update what-entity-new-relic.mdx with the new exceptions in handling externals and uninstrumented guids

- src/content/whats-new/2025/03/whats-new-03-10-timeslices-lookups-dataexplorer.md
What's new post for new features in the data explorer. No PMM review necessary.
Please schedule for March 10th after review. Thank you!
> feat(whats-new): add data explorer post

- src/content/docs/logs/log-api/introduction-log-api.mdx
We've never clarified the difference in array processing between opentelemetry and the rest of ingestion mechanisms.
This PR aims to fix that.
Bascially, we stringify all arrays except for Opentelemetry homogeneous (one type) arrays.
> fix(logs): (NR-371436) Clarify array support for logs

- src/content/docs/alerts/incident-management/response-intelligence-ai.mdx
Removed the .NET information from the Preview callout as per the request received in this [thread](https://newrelic.slack.com/archives/C08G80APCK1/p1741348360749049)
> removed .net information from callout

- src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx
```sql
SELECT * FROM `JS Errors`
```
Is not a valid query, events can't have white space in them. The image in the doc shows the correct query
> fix: JavaScriptError

- src/content/docs/new-relic-solutions/get-started/networks.mdx
Updates to NR networks.  Removed CSP provided blocks no longer used and added a json file of NR space so it can be consumed programmatically.  I am on the New Relic Network team.  We are doing some house cleaning with our documentation.
> Update to New Relic's network document

- src/install/config/aws-cloudwatch.yaml
Added a redirect to the AWS metric stream documentation to fix a broken link issue.
> fix: Fix the broken link issue for AWS metric stream

- src/content/docs/apm/agents/java-agent/instrumentation/instrument-aws-sqs-message-queues.mdx
Update our SQS instrumentation page with a notice about required configuration for version 8.18.0 of the Java Agent.
> Update java sqs doc with config warning

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/env-variables-lambda.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/troubleshooting/troubleshoot-enabling-serverless-monitoring-aws-lambda.mdx
The Node.js lambda layer is changing behavior to support ESM.  We're deprecating the existing way. This PR updates the language to call out how to wrap lambdas using ESM. The functionality hasn't been released but will be released on March 17, 2025.
> chore: Updated language around using Node.js lambda layer with ESM

- src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
I have created this PR in response to [this JIRA ticket](https://new-relic.atlassian.net/browse/NR-381873). This PR fixes the collapser issue in the Node API doc that was causing the anchor tag to display as plain text.
> (fix) fix the collapser issue to resolve anchor tag error

- src/content/docs/browser/new-relic-browser/browser-pro-features/page-resources.mdx
This PR fixes a typo that was found by a customer that is present in an example query in our public preview of page resources capture.
> fix: fix typo in example query

- src/content/docs/new-relic-control/agent-control/authentication.mdx
The objective of this PR is adding an overview of L1/L2 Autentication process
> feat(nr-control): authentication

- src/content/docs/apis/nerdgraph/examples/nerdgraph-api-notifications-destinations.mdx
In the BASIC auth examples, both the user and password field names were wrapped in double quotes. Theses are field names, not values.
When the example is pasted as into the NerdGraph API Explorer, the following error is displayed:
> Fixed incorrect syntax in NerdGraph examples on nerdgraph-api-notifications-destinations.mdx

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
- src/content/eol/2025/03/deprecation-notice-v1.27-and-lower.md
Bumps the supported k8s version to 1.32 and adds a deprecation notice for v1.27 and lower.
> feat(kubernetes): Update docs to support k8s v1.32 and add deprecation notice for v1.27

- src/content/docs/browser/new-relic-browser/configuration/browser-settings-ui-options-apdex-geography.mdx
Step-3 has been removed as requested in the #help-documentation channel.
https://docs.newrelic.com/docs/browser/new-relic-browser/configuration/browser-settings-ui-options-apdex-geography/#apdex-settings
> Chore: Steps updated.

- plugins/gatsby-plugin-release-note-rss/gatsby-node.js
We are exposing RSS xml endpoints for Release Notes to customers  
Some Costumers might use RSS Readers like https://feeder.co/reader
and Some Customers prefer to receive Emails if any new release notes are published
For these second set of Customers The redirect links are not working properly in mail
This PR Addresses in fixing this redirection issue
[Issue](https://github.com/newrelic/docs-website/issues/18734)
[Ticket](https://new-relic.atlassian.net/browse/NR-378976)
> fix: rss redirection in email

- src/content/docs/apm/agents/ruby-agent/features/record-deployments-ruby-agent.mdx
Update help options output to include information about required keys for v1 and v2 API options
> chore: Update record-deployments-ruby-agent.mdx

- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
The `earliest()` function returns the earliest value for each facet, not the most recent.
> earliest wording

- src/content/docs/new-relic-solutions/build-nr-ui/nerdstoragevault.mdx
Description
Once we switch nerd-storage-vault to use Customer Secrets Service instead of Synthetics Locker, the secret limit per actor will no longer apply. This PR removes that note from the doc, and should be merged after the switch is made.
Related PR - https://github.com/newrelic/developer-website/pull/2282
> docs: Remove secret limit note for service migration

- src/content/docs/apm/transactions/workload-performance-monitoring/introdution.mdx
Hey docs folks -- this is a spot fix, but it needs to be made on the hundreds of spots in the docs that refer to the product as "New Relic One." That's not the name for the product that we use anymore (for at least a year). In addition, there's not a home page, so I removed the reference to home page. Getting to transaction 360 isn't straightforward and it's not part of "All Capabilities" if that's what this was referring to — you need to go to the transaction page for a service and open it from there. 
Here's the spot in the style guide that describes how to refer to New Relic: https://newrelic.atlassian.net/wiki/spaces/PD/pages/3804889254/Product+and+capabilities+capitalization+trademarks+and+usage
Note that there's also a guideline not to say "New Relic's" 
Thanks.
Please follow …
> Remove reference to New Relic One

- src/content/docs/release-notes/logs-release-notes/logs-25-04-01.mdx
- This PR is to create release note for the introduction of request ID parameter for every log message of an AWS lambda event. In some scenarios, lambda's log messages for an event have request ID only for the first and the last message, while the messages in between have it missing. Recent changes (refer to the Jira ticket [here](https://new-relic.atlassian.net/browse/NR-333638)) have introduced populating request ID to all the log messages. 
- Confluence document for reference -> https://newrelic.atlassian.net/wiki/spaces/TDP/pages/3985965195/RequestId+for+CloudWatch+logs+generated+from+Lambda+function
> feat: adding release notes for unified lambda request ID ingestion

- src/nav/apm.yml
The navigation link to [this page](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent-azure-site-extension/) is incorrect. Following it leads users to our 404 page. This corrects the link.
> chore: Updated nav link to Azure Site Extension instructions for Node

- src/content/docs/release-notes/logs-release-notes/logs-25-04-02.mdx
This adds release notes of a logging ingestion change
> feat: add release notes for logs handling of unpaired UTF surrogates

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates the .NET Agent compatibility page to expand MongoDB support to version 3.X
> chore:Update .NET agent MongoDB support to include 3.X.

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
.NET agent release 10.40.0 contains new instrumentation for AWSSDK.Kinesis and AWSSDK.KinesisFirehose.  This PR updates our support documentation to include it.
> docs: .NET Agent, add Kinesis and Firehose instrumentation support statements

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates .NET agent compatibility docs to add CouchbaseNetClient v3.x instrumentation support.
> docs(dotnet): Update Couchbase compatibility requirements

- src/content/docs/apm/agents/nodejs-agent/hosting-services/nodejs-agent-microsoft-azure.mdx
Windows Azure Web Sites has been rebranded by Microsoft as Azure App Services. It's neither Windows Azure Web Sites nor Azure Web App.
Additionally, the Azure SDK for Node.js has been deprecated and integrated into the new Azure SDK for JavaScript.
https://www.zdnet.com/article/microsoft-to-rebrand-windows-azure-as-microsoft-azure/ https://azure.microsoft.com/en-us/blog/announcing-azure-app-service/
https://github.com/azure/azure-sdk-for-js
https://github.com/Azure/azure-sdk-for-node?tab=readme-ov-file
links to related docs, …
> The ServiceName of Azure has been modified.

- src/content/docs/new-relic-control/agent-control/overview.mdx
This PR tries to clarify that installing multiple instance of Agent Control in the same k8s cluster is not supported.
> feat(agent-control): AC does not support multiple installation in the same cluster

- src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
This is to inform users that Log API limits would also apply for TPC syslog endpoints as it's the main entry point for logs.
> docs(logging): Add limitations of Log API to syslog page

- src/content/docs/infrastructure/infrastructure-alerts/rest-api-calls-new-relic-infrastructure-alerts.mdx
these commands give errors: 
```sh
curl -X POST 'https://infra-api.newrelic.com/v2/alerts/conditions' -H "Api-Key:$API_KEY" -i -H 'Content-Type: application/json' -d
'{
"data":{
"type":"infra_process_running",
"name":"Java is running",
"enabled":true,
"where_clause":"(hostname LIKE '\''%cassandra%'\'')",
"policy_id":policy_id,
"comparison":"equal",
"critical_threshold":{
"value":0,
"duration_minutes":6
},
"process_where_clause":"(commandName = '\''java'\'')"
}
}'
curl: option -d: requires parameter
```
you need `\` escape char before the line break or the command runs without the json on the next line
* Add any …
> fix: multiline curl commands need `\` escapes

- src/content/docs/new-relic-control/pipeline-control/cloud-rules-api.mdx
* This PR adds details to our pipeline control docs about how to write rules which prune attributes from dimensional metric rollups. This is a new feature which was added to our recently released pipeline control cloud rules.
* This feature ensures we have parity with the old NRQL drop rules which pipeline control cloud rules are a replacement for. The changes added in this document are very similar to the section we have in our docs for our legacy drop rules: …
> NR-368357: Add details about metric aggregate pruning rules in pipeline control cloud rules docs

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100900.mdx
This PR adds release notes for Python Agent v10.9.0.
> Add release notes for Python agent release v10.9.0.

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
Added a new mutation to relocate a scripted API monitor between VSE-enabled private locations. This PR address the  [NR-402470](https://new-relic.atlassian.net/browse/NR-402470) jira ticket.
[NR-402470]: https://new-relic.atlassian.net/browse/NR-402470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (feat): added new mutation

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
This PR updates the configuration settings page for the Python agent to include "environment variable" in settings that are also enabled through environment variables.
> Update Python agent configuration settings page

- src/content/docs/new-relic-solutions/get-started/networks.mdx
We are updating the CDN that provides `download.newrelic.com`, therefore there is a need to update the docs with the new network block.
> docs: Update download.newrelic.com networks

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
The PHP Agent 11.8.0.22 release added support for Amazon DynamoDB.  This PR updates the compatibility page for the PHP agent to reflect that.
> chore(PHP Agent): Adds Amazon DynamoDB to supported databases

- src/content/docs/infrastructure/infrastructure-agent/requirements-infrastructure-agent.mdx
add Windows Server 2025 as supported OS for the NR Infrastructure Agent
The OHAI team has recently tested and certified Windows Server 2025 as supported, and this is just adding it into the list of supported OS for the Infrastructure Agent.
> add Windows Server 2025 as supported OS for the infra agent

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
PHP team would like to update the DynamodDB support statement to include information on the specific versions which are supported.  This amends PR #20518
> chore(php): Updates DynamoDB support

- src/content/docs/apis/nerdgraph/examples/nerdgraph-api-alert-notification-channels.mdx
Deprecate alert notification channels
* Add deprecate notice to alert notification channels page here 
* Link to altered page: https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-api-alert-notification-channels/
> Deprecate alert notification channels

- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
This updates the Diagnostics CLI Documenation to include kubernetes compatability and the new command line option `-k8s-namespace`.
> feat: Update Diagnostics CLI Documentation for kubernetes

- src/content/docs/agentic-ai/agentic-integration/servicenow-integration.mdx
- src/nav/agentic-ai.yml
This PR adds the documentation support for the New Relic AI integration with ServiceNow Now Assist. It addresses WR [NR-410008](https://new-relic.atlassian.net/browse/NR-410008) by providing a comprehensive guide to setup and use New Relic AI in Now Assist.
[NR-410008]: https://new-relic.atlassian.net/browse/NR-410008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feat]: Added New Relic AI integration with ServiceNow Now Assist support docs

- src/content/docs/browser/new-relic-browser/browser-apis/start.mdx
* The start() API loads deferred features for the browser agent. The docs include a list of potential features to be deferred and how to configure this in the application
* Through testing I have discovered that if one of the features in not included, the browser agent will become active (in a lessened capacity)
* This PR adds the new feature, logging, which was introduced to the agent after the start() API was created.
> add logging to feature list under browser agent start() API

- src/content/docs/apm/agents/net-agent/troubleshooting/app-hangs-on-startup.mdx
- src/nav/apm.yml
This PR adds a short document to the troubleshooting section of the .NET agent docs.  The doc lets customers know about a workaround for a potential hang in their .NET 8 apps on startup.
> .NET agent: add troubleshooting doc for app hang on startup issue

- src/content/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-infrastructure/infra-agent-inventory-reset.mdx
- src/nav/infrastructure.yml
add a troubleshooting page to reset the infra agent inventory and metadata cache
> add a troubleshooting page to reset the infra agent inventory and metadata cache

- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
for rows with the same timestamp
Customers are sometimes confused when they have multiple events or metrics with the same timestamp and get inconsistent results from the NRQL earliest() and latest() functions.  Add a tip explaining the issue and a potential remedy.
> feat: Add tip regarding nondeterministic latest and earliest results

- plugins/gatsby-source-nav/gatsby-node.js
- src/content/docs/release-notes/index.mdx
- src/content/docs/release-notes/streaming-release-notes/index.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-browser-release-notes/index.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-mobile-release-notes/index.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-mobile-release-notes/streaming-android-agent-25-03-03.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-mobile-release-notes/streaming-android-agent-25-03-05.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-mobile-release-notes/streaming-ios-agent-25-03-03.mdx
- src/content/docs/release-notes/streaming-release-notes/streaming-others-release-notes/index.mdx
- src/templates/releaseNoteLandingPage.js
**Currently in release notes navigation section we only have one level of nesting which hinders the categorisation in release notes**
**This PR is created to enhance the categorisation of release notes , Add an additional level under the primary subject grouping. This will allow for more granular categorisation of release notes by leveraging a secondary frontmatter field Category 
Release Notes -> [Primary Subject] -> [Secondary Category] -> [Individual Release Note]**
[Jira Ticket](https://new-relic.atlassian.net/browse/NR-412539)
> feat: change Nav structure for release notes

- src/content/docs/serverless-function-monitoring/azure-function-monitoring/compatibility-requirement-azure-monitoring.mdx
- src/content/docs/serverless-function-monitoring/azure-function-monitoring/install-serverless-azure-monitoring.mdx
This PR updates our Azure Functions monitoring docs (compatibility/support and install instructions) based on testing I've recently done on various combinations of function model (isolated vs. in-process), host platform (Windows vs. Linux), hosting plan type (consumption or dedicated), function runtime (.NET Framework vs. .NET), and agent install method (Azure Site Extension vs. Agent NuGet package).
Summary of changes:
* Called out that we do not support the combination of Linux OS, Consumption plan and In-Process function model
* Called out that we only support functions using version 4 of the functions runtime
* Changed the environment variable instructions for the Windows + Azure Site Extension install method to explicitly set all of the profiling env vars, similar to the instructions …
> Draft: Update Azure Functions docs based on testing

- src/content/docs/browser/new-relic-browser/browser-apis/addtotrace.mdx
Adds a note about argument requirements in addToTrace API method. `start` and `end` must be positive Unix stamps, and `end` cannot be before `start`.
JIRA: https://new-relic.atlassian.net/browse/NR-366078
The argument requirements will be enforced for the addToTrace API method on next Browser agent release, which contain safeguards, but these requirements should be followed even without the safeguards in place.
> Add unix timestamp requirement in addToTrace

- src/content/docs/release-notes/docs-release-notes/docs-5-16-2025.mdx
The RN was from 2 to 15 May, but named by mistake as 12 to15 may. Corrected it.
> chore(docs RN): Release note date correction

- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Jira Issue: NR-417400
The [NRQL reference](https://docs.newrelic.com/docs/nrql/nrql-syntax-clauses-functions/) page should contain an exhaustive list of all of our NRQL functions. Currently this page is missing the [NRQL advanced functions](https://docs.newrelic.com/docs/nrql/nrql-tutorials/nrql-tutorial-advanced-functions/) which this PR introduces.
> Adding advanced functions to NRQL Reference page in public docs

- src/content/eol/2025/05/drop-rule-filter.md
- Request received to update this information from the #help-documentation channel.
> NRQL DROP rules EOL

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-10-0-24.mdx
Updates for the PHP agent v11.10.0:
Add 'PHP agent v11.10.0' release notes and supporting documentation that was updated to reflect functionality changes.
> Php agent release 11.10

- src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx
codeblocks have to align with the triple backticks (`) or the indentation gets off
> chore: fix indentation

- src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/nrql-predictions.mdx
We've recently updated the default behavior in how we gather historical data for training and have updated our public facing documentation accordingly so customers are aware of the changes.
Overall, we use a historical data spanning `3 * seasonality` when we have a PREDICT query with the following: 
- No `USING` clause
- A `hyperparameter` with a `seasonality` which is not `NONE` or `AUTO`
- A `seasonality` that's greater than the query duration
> Update "Historical data for training" sections  within Predict docs

- src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
- Add GRANT SELECT permissions to handle non-cdb oracle database to fetch locked accounts from standard database
> docs: Update GRANT SELECT permissions for nri-oracledb

- src/install/dotnet/installation/azure-linux-container.mdx
- src/install/dotnet/installation/dockerLinux.mdx
- src/install/dotnet/installation/linuxInstall2.mdx
This PR:
1. Updates the syntax for the `gpg` command that imports the public signing key for an APT repo to be more robust (it will handle being run multiple times)
2. Alters those commands for `Dockerfile` examples to no longer prefix the command with `sudo` as this is both unnecessary (Dockerfile commands run as root by default) and will cause the instructions to fail (sudo isn't installed or enabled by default in most Docker images)
> .NET agent: Update gpg key import commands; remove sudo from commands in Dockerfiles

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This config flag has been removed in the Node.js agent en lieu of a new config flag under utilization: `utilization.gcp_use_instance_as_host`, which will be added to the docs in a later PR.
> Remove `gcp_cloud_run.use_instance_as_host` in Node.js agent

- src/nav/telemetry-data-platform.yml
This PR removes the redundancy from the table of contents in the `telemetry-data-platform.yml` file.
> (chore): remove the redundancy from the toc

- src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
- src/content/docs/browser/new-relic-browser/browser-apis/recordCustomEvent.mdx
- src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx
- src/content/docs/browser/new-relic-browser/performance-quality/browser-monitoring-performance-impact.mdx
Adds a notice about the browser agent's harvest interval behavior. If the payload size is > 16KB or if it's been 30 seconds, we trigger a harvest for the data.
JIRA: https://new-relic.atlassian.net/browse/NR-419973
> Update public docs to describe browser agent's harvest interval behavior

- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-340.mdx
This adds the release notes for the Diagnostics CLI version 3.4.0 and adds the new command line option to the command line documenation.
> feat(diagcli): Diagnostics CLI Release 3.4.0

- src/content/docs/new-relic-control/agent-control/setup.mdx
- src/content/docs/new-relic-control/agent-control/troubleshooting.mdx
Updated the agent control docs regarding a new feature we introduced: "Split namespaces".
Now we install k8s agents in one namespace, and flux and Agent Control in a different namespace.
> docs: agent control split namespaces

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
The ktranslate agent requires the host operating system's timezone to be set to UTC to ensure accurate timestamping of flow data. If the timezone is set to a local value (e.g., JST, PST), it can lead to data ingestion issues or incorrect data visualization in the New Relic UI.
This commit adds an important callout to the "Prerequisites" section of the network flow monitoring documentation. This ensures users are aware of this critical requirement before they begin the installation process, helping to prevent common setup errors and subsequent troubleshooting.
* Add any context that will help us review your changes …
> docs(npm): Add UTC timezone requirement for ktranslate

- src/content/docs/apis/nerdgraph/examples/manage-live-chart-urls-via-api.mdx
- src/content/docs/apis/nerdgraph/examples/manage-live-dashboard-urls-via-api.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx
- src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
- src/nav/telemetry-data-platform.yml
Reorganized Public Charts NerdGraph API documentation. 
Added collapsers for create, revoke, and list the live chart URLs.
Jira ticket: https://new-relic.atlassian.net/browse/NR-439954
> feat[public dashboard]: Migrating all public sharing chart related NerdGraph queries to one page

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx
Added node agent version 13 docs to the node migration/upgrade guide.
> chore(nodejs): Updated node migration guide with version 13 docs

- src/templates/docPage.js
Implemented a mechanism to redirect all old/expired heading level urls to new urls with client side redirection 
Eg : Previous URL : [https://docs.newrelic.com/docs/browser/browser-monitoring/browser-pro-features/session-replay/#app-performance](https://docs.newrelic.com/docs/browser/browser-monitoring/browser-pro-features/session-replay/get-started/#app-performance) 
Present URL :   https://docs.newrelic.com/docs/browser/browser-monitoring/browser-pro-features/session-replay/additional-information/#app-performance
> fix: client side rendering for redirection of old urls to new urls

- src/content/docs/new-relic-control/pipeline-control/modify-agent-configuration.mdx
The Pipeline Control Gateway requires P17 from all APM Agents. This updates the table to list the minimum version to the earliest P17 version. It also specifically calls out that it does not override the existing EOL policies.
> bug: fix gateway minimum agent versions

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
This PR adds `3.21` and `3.22` as supported alpine versions.
> chore(php): update supported alpine versions

- src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
This commit revises the compatibility and requirements documentation for the Oracle integration to improve clarity and professionalism.
The primary changes include:
- Replaced technical slang like "agent box" with the more precise phrase "the same host where the infrastructure agent is running."
- Changed "distro" to the more formal "distribution."
- Clarified ambiguous phrases such as "compatible with infrastructure" and "configured to monitor from a remote connection" to be more explicit and universally understandable.
These changes do not alter the technical meaning of the requirements but ensure the documentation is clearer for a broader audience.
in your commit messages and pull request …
> docs: Refine language in Oracle integration requirements

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
This PR corrects some issues with the .NET agent's compatibility and support document regarding SQL query parameter capture.
Some form of the following statement appeared in three places in the documentation:
`By default the .NET SQL parameter capture in a query trace doesn't list parameters for a parameterized query or a stored procedure.`
1. In one case, the all-important "by default" was omitted.  This is fixed.
2. This statement appeared in one place in the document were it didn't make sense to.  This is deleted.
3. A statement about datastore instance detail collection was missing from one place, and it is added there.
> .NET agent: clarify that SQL query parameter capture is available, but not enabled by default

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
- src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/additional-information.mdx
- src/content/docs/licenses/license-information/usage-plans/new-relic-usage-plan.mdx
Updating the PAYG per GB price:
- Data plan from $0.35 to $0.40
- Data plus plan from $0.55 to $0.60
> ktlo[PAYG price revise]: Update the per GB price

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Fix obsolete documentation that claimed that nodejs exits after failing to open log file.
Inaccurate statement in documentation
This PR is based on a conversation I had with [ChatGPT o3](https://chatgpt.com/share/68916102-b7cc-8003-b048-11b81f97949b). All hallucinations are my own.
> fix(nodejs): explain failure to open log behavior

- src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
This PR adds new `npm` guided flow to the documentations to address the requirements specified in the NR-448474 JIRA tickets.
> feat: Added new npm guided flow

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8230.mdx
I notices in the doc site deploys when merging into main the release notes has errored out due to a missing quote. I fixed it.
PLEASE MERGE ASAP. We need the Java Agent release notes up by the end of the day so we can announce our release.
> Fix Typo in the release notes. PLEASE REVIEW AND MERGE ASAP.

- src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
The .NET agent's NoticeError API page doesn't explain how we determine the exception details we report up.  This expands on that to reduce customer confusion.
> chore: Add more details to the .NET agent's NoticeError page.

- src/content/docs/data-apis/manage-data/query-limits.mdx
`consumingAccountId` is no longer available, but the `accountId()` function can and should be used instead.
> Use accountId function for querying limits

- src/content/docs/alerts/your-first-nrql-condition.mdx
This editors note is in plain text.
`//` is not a comment in markdown, ``
> fix: doc writer note removed from plain text

- src/install/microsoft-sql/windows/query-level-monitoring-entra-id-service-principal.mdx
- src/install/microsoft-sql/windows/query.mdx
This PR is in response to the GitHub issue https://github.com/newrelic/docs-website/issues/21593 and [this request](https://newrelic.slack.com/archives/C0DSGL3FZ/p1756407192503689) on #help-documentation channel. It adds the supported Microsoft SQL Server version information for Database performance monitoring.
> Added the version callout for Database performance monitoring

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/env-variables-lambda.mdx
This PR updates the documentation for `NEW_RELIC_LICENSE_KEY_SECRET` and `NEW_RELIC_LICENSE_KEY_SSM_PARAMETER_NAME`.
The new descriptions clarify that users can provide either the **name or the ARN** of the secret/parameter. They also include important requirements:
* The AWS secret or parameter must be in the **same region** as the Lambda function.
* The function's execution role needs the appropriate **IAM permissions** (`secretsmanager:GetSecretValue` or `ssm:GetParameter`).
> chore: updated description for ssm and sm with role overview

- src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
- src/content/eol/2025/02/eol-01-31-25-synthetics-ip.md
This PRs adds a new date to remove old IPs from the synthetic monitors
> chor: added new eol date for synthetic monitoring IPs

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
The PHP agent team would like to change remove Red Hat RHEL 7 from the compatibility page.
> chore(PHP): Remove RHEL 7 from compatibility page

- src/content/docs/infrastructure/host-integrations/infrastructure-integrations-sdk/specifications/host-integrations-standard-configuration-format.mdx
Added infra agent integrations max interval note section 
Infra agent integration have a interval field which can have time interval in min,sec,hr, But for rate metrics we have a TTL of 5 min for comparision with the previous value, So added a Note section in the doc explaining we can have a greater time interval bt that will lead to an inaccurate metrics calculation. So 5 min is the max interval time that is suggested from NR
https://docs.newrelic.com/docs/infrastructure/host-integrations/infrast …
> docs(infra_integration_interval): Add infra agent integrations max interval note section 

- src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/additional-information.mdx
- src/content/docs/browser/new-relic-browser/lab/debug-slowness.mdx
- src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx
- src/content/docs/browser/new-relic-browser/performance-quality/browser-monitoring-performance-impact.mdx
- Add new summary as source-of-truth for harvest cycle timing + final harvest
- Add new rows for Browser logs, UserAction, and BrowserPerformance events
Per this [ticket](https://new-relic.atlassian.net/browse/NR-399281), we are updating the browser agent harvest docs.
> chore(browser): Update browser agent harvest docs

- src/install/dotnet/installation/azure-linux-container.mdx
- src/install/dotnet/installation/dockerLinux.mdx
- src/install/dotnet/installation/linuxInstall2.mdx
This PR makes the following changes to all APT-based install instructions for the .NET agent:
1. Switch from `wget` to `curl`, as curl is more likely to be installed by default on most Linux distros.
2. Signing key location moved from `/usr/share/keyrings` to `/etc/apt/keyrings` based on new information about where these keyfiles should go by convention (keys managed "manually" by users go in /etc/apt/keyrings; /usr/share/keyrings is for keys managed by packages)
3. Using `gpg --dearmor` instead of what was there before allows these instructions to work on newer distros like Debian 13 where the APT command has been upgraded to >=v3 and it uses Sequoia instead of GNUPG for its OpenPGP key verification needs.
> .NET Agent: Update all APT repo install instructions

- src/content/docs/alerts/admin/rules-limits-alerts.mdx
- src/content/docs/alerts/get-notified/notification-integrations.mdx
- Introduced validation of new email IDs added in destination for configuring email alert forkflow.
- Added the limit details on how many email IDs can be added in one destination depending on the account type
- Add the org level limit of max 1000 mail IDs cam be added in 24 hours.
https://docs.google.com/document/d/1vfk7NyhM8hBK1GbG-OPWnZEgBG_ZCIzgt7abPriVtIQ/edit?tab=t.b2ud6pp0bbq3
> feat[Alert notification workflow][DO NOT MERGE]: Added new email validation steps and limits on adding email ID to destinations

- src/content/docs/release-notes/docs-release-notes/docs-9-25-2025.mdx
We haven't added any new docs last week however RN contains an empty section for new docs. This PR removes that section.
> chor: remove the new docs section as there no new docs

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
the anchor `tracer-enabled` was reused for transaction traces and dt, so you can't link directly to the dt section
> fix: #tracer-enabled was reused

- src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
live URLs can only be managed by NerdGraph API. Updated the callout to reflect it correctly
> chore[live URLs]: live URLs can only be managed by NerdGraph API. Updated Doc

- src/content/docs/apm/agents/ruby-agent/features/record-deployments-ruby-agent.mdx
The `newrelic deployments` command is being [deprecated](https://github.com/newrelic/newrelic-ruby-agent/pull/3262/files) in the agent. We should add a warning to our docsite.
> Announce `newrelic deployments` deprecation

- src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/updated-aws-cloudformation-templates.mdx
Blog about the Cloudformation template update for the AWS Cloudwatch Metric Stream Integration in the Cloud Integrations docs. This update brings new cloudformation template with the usage of latest AWS Lambda python Runtimes.
> Blog for AWS Cloudwatch Metric Stream Integration Cloudformation template update
