src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* Add documentation for the new setting "is_integrations_only" introduced with infra agent 1.53.0
=> docs(infra-agent): add new setting

src/install/kubernetes/helm/install-helm.mdx
Added the important note about the yaml file in the installation instructions of  [Kubernetes with Helm](https://docs.newrelic.com/install/kubernetes/?dropdown1=helm) doc.
This is the ticket: NR-279785
=> feat(K8s): Added the important note about the yaml file

src/content/docs/alerts/create-alert/condition-details/alert-custom-incident-descriptions.mdx
=> fix: replace DoNotTranslate with DNT

src/content/docs/more-integrations/dbt-cloud/dbt-cloud-integration.mdx
Fixed while writing release notes
=> fix(Cloud integrations): Uncapitalized a word in the doc title

src/data/whats-new-ids.json
daily-release/Jul-10-2024-2_41
=> daily-release/Jul-10-2024-2_41

src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
=> fix: update the .NET API link

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8130.mdx
Reverts newrelic/docs-website#17976
=> DO NOT MERGE: Java Agent 8.13.0 Release Notes

src/nav/browser.yml
Fixing the menu listing for the browser `log` api.
=> fix(menu): correct browser menu api listing

src/install/kubernetes/helm/install-helm.mdx
Fixed numbering in step 4 of the [Kubernetes monitoring integration](https://docs.newrelic.com/install/kubernetes/?dropdown1=helm) page.
=> fix(K8s): Fixed numbering

src/content/docs/apm/agents/python-agent/getting-started/instrumented-python-packages.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-91200.mdx
* Add release notes for python agent release v9.12.0.
=> Add release notes for python v9.12.0

src/content/docs/infrastructure/host-integrations/host-integrations-list/flex-integration-tool-build-your-own-integration.mdx
* Adding the typical troubleshooting steps we recommend customers to follow when encountering issues with their Flex configurations.
=> docs: Flex basic troubleshooting steps

src/content/docs/apm/agents/net-agent/azure-installation/debugging-agent-azure.mdx, src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-on-aws-elastic-beanstalk.mdx, src/content/docs/apm/agents/net-agent/installation/uninstall-net-agent.mdx, src/content/docs/apm/agents/net-agent/other-installation/how-verify-checksum-net-agent-downloads.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/monitoring-airflow-ot.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-puppet.mdx
=> chore: add syntax highlighting to codeblocks

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
=> Add tested environments.mdx

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Jira issue: NR-284975
Direct preview link to updated histogram() doc: https://deploy-preview-17974--docs-website-netlify.netlify.app/docs/nrql/nrql-syntax-clauses-functions/#func-histogram
The previous documentation for histogram() was missing one of the available arguments, and had incorrect information about another. The revisits the documentation, providing a more complete description of the function to users.
n/a
n/a
=> Update histogram() documentation

.github/auto_assign.yml
Removed @homelessbirds from auto-assigned reviewers and added @cbehera-newrelic.
=> chore(Docs): Added/removed auto-assigned reviewers

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/enable-serverless-monitoring-aws-lambda-layerless.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/update-serverless-monitoring-aws-lambda.mdx
Add some spaces to the redirects in the intro file.
=> AWS Lambda: Add indentation for redirects

src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/find-build-uuids-unsymbolicated-crashes.mdx, src/content/docs/nrql/get-started/charts-and-dashboards-with-nrql.mdx
* [Updated charts and dashboard page](https://docs.newrelic.com/docs/nrql/get-started/charts-and-dashboards-with-nrql/)
* Ticket no. NR-266790
=> fix(NRQL Dashboards): Updated charts and dashboard page

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/cloud-watch-fallback.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/enable-serverless-monitoring-aws-lambda-layerless.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/update-serverless-monitoring-aws-lambda.mdx
=> chore: code cleanup in new Lambda docs

src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx
jira: https://new-relic.atlassian.net/browse/NR-292090
Description: Updated the link to Prometheus Remote Write Integration points install framework, so that it can redirect to add data not the old nerdlet. [doc link](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/#setup)
Testing recording link: https://drive.google.com/file/d/1q5DgUY9pgdeOp-5qSANtWH7zi__f321u/view?usp=sharing
=> feat(NR-292090): Updated prometheus install framework link

src/content/docs/style-guide/structure/callouts.mdx
Fixed a sentence in the preview callout on [this page:](http://localhost:8000/docs/style-guide/structure/callouts/).
=> fix(Style guide): Fixed a sentence in the preview callout

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
=> Remove KSM parameter from Helm command

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
=> broken link

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx, src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx
=> Add account deletion section.

src/content/docs/tutorial-dd-migration/installing-monitor.mdx
=> fix(tutorial): Fix broken header ID

src/content/docs/tutorial-dd-migration/installing-monitor.mdx
=> Daily release/jul 19  2024 9 49

src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
Changes requested by @khickey-newrelic
=> feat(Browser): Renamed a tab, added link to npm page

src/content/docs/apm/agents/net-agent/other-features/net-performance-metrics.mdx
* Converts bullets into tables
* Puts metric names in code
* Removes outdated version references
* Other minor style edits
=> style(NET): Style ".NET performance metrics" doc

.github/auto_assign.yml
Removed @akristen from autoassign list
=> chore(Docs): Removed person from reviewer autoassign list

.github/workflows/agent-release-notes.yml, .github/workflows/check-for-broken-links.yml, .github/workflows/check-images.yml, .github/workflows/check-translations-and-deserialize.yml, .github/workflows/release.yml, .github/workflows/send-content-to-machine-translate.yml, .github/workflows/send-content-to-translate.yml, .github/workflows/update-attribute-dictionary-json.yml, .github/workflows/update-whats-new-ids.yml, .github/workflows/validate-pr.yml, .github/workflows/validate-release-notes-json.yml, .github/workflows/verify-mdx.yml, .github/workflows/webdriver.yml
updates GH actions to use the scripts at their new mjs locations. also updates all workflows from Node 18 to 22.4
=> fix GH action script references and upgrade Node to 22.4

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1551-0.mdx
=> New infrastructure agent release 1.55.1 release notes

src/content/whats-new/2020/08/create-grafana-dashboards-prometheus-data-stored-new-relic.md
Fixes a stray link left over from #18046
=> chore(prometheus): Fix old "add data" link

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
When a dashboard or chart is exported as PDF, some features are not available and  Export as PDF have some limitations that we need to document to customers.
=> Include Export as PDF limitations

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-otel.mdx
Fixed content according to @mangulonr message.
=> fix(K8s): Fixed content according to SME

src/content/docs/logs/logs-context/logs-in-context.mdx
Quick lil PR to update the data bytes video to the new data bytes video on the page
=> Update logs-in-context video

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
…cripted monitors
Invalid method signature fixed.
Official Docs : https://www.selenium.dev/selenium/docs/api/javascript/WebElement.html#:~:text=getText()%20%E2%86%92%20(non%2Dnull)%20%7BPromise.%3Cstring%3E%7D
=> Update docs for selenium web-driver getText() method 

src/content/docs/new-relic-solutions/business-observability/intro-pathpoint.mdx
**This is a small set of fixes that I made after yesterday's major changes went live.  I got to view the docs on my large monitor and some of these issues jumped out at me.**
=> Minor cleanup of recent Pathpoint V2 doc release

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates instrumented framework versions for the .NET agent to the most recent tested versions
=> docs(dotnet): Update .NET agent compatibility versions

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-111.mdx
* What problems does this PR solve? - Android NDK agent release notes
=> Target release date: 7/25/24 - Android NDK agent release notes

src/content/docs/infrastructure/host-integrations/host-integrations-list/temporal-cloud-integration.mdx
=> chore: Minor updates for temporal cloud

src/content/docs/apm/agents/net-agent/getting-started/net-agent-approaches-lambda.mdx, src/nav/apm.yml
There are many options for monitoring .NET Lambda applications and this doc will provide a short summary of them with links for more details.  Has a nice table of features between the two main categories of instrumentation as well.
Customers are confused by all the choices, this will hopefully help.
Relates to newrelic/newrelic-dotnet-agent#2595
=> chore: Add approaches for .NET AWS Lambda monitoring.

src/content/docs/opentelemetry/best-practices/opentelemetry-manage-data-ingest-volume.mdx
=> fix: update indentation for file

src/content/whats-new/2023/10/whats-new-10-02-incident.md
This is to correct a video that only displays in the docs site--not in the UI.
=> fix(What's new): Fix embed link

src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx, src/content/docs/errors-inbox/browser-tab.mdx
=> fix(browser): broken link

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
=> fix default value case

package.json, yarn.lock
=> chore: theme update v9.7.2

src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-150.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-700.mdx, src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-110.mdx, src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-111.mdx, src/content/docs/release-notes/mobile-release-notes/net-maui-release-notes/net-maui-agent-110.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-140.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-141.mdx, src/content/docs/release-notes/mobile-release-notes/xamarin-release-notes/xamarin-agent-100.mdx
=> Docs:Hybrid Agent Log Forwarding and ANR reporting Release

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-0-0-13.mdx
PR for upcoming PHP Agent release.
Please do not merge before noon PST.
=> feat(apm): PHP Agent 11.0.0.13 Release Notes

src/content/docs/apm/agents/net-agent/azure-installation/debugging-agent-azure.mdx
=> chore: update links

src/i18n/content/jp/docs/apm/agents/ruby-agent/features/record-deployments-ruby-agent.mdx, src/i18n/content/jp/docs/distributed-tracing/other-requirements/infinite-tracing-configuring-ssl-java-7-8.mdx
Updated the mangled html from our translator and re-deserialized two files
=> Refactor html and re-deserialize

src/content/docs/alerts/get-notified/notification-integrations.mdx
Fixes indentation that was failing serialization.
=> fix: indentation issues

src/content/docs/apm/agents/net-agent/azure-installation/no-data-reporting-microsoft-application-insights.mdx
The .NET team said to add this
=> chore: + MicrosoftInstrumentationEngine_LatestPath

src/content/docs/new-relic-solutions/business-observability/intro-pathpoint.mdx
Fixed capitalization and gerunds in headers
=> fix(Pathpoint): Fixed some heading styles

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-751.mdx
* What problems does this PR solve? - Android agent v7.5.1 release notes
=> Target release date: 8/1/24 - android agent v7.5.1 release notes

src/content/docs/release-notes/mobile-release-notes/unity-release-notes/unity-agent-136.mdx, src/content/docs/release-notes/mobile-release-notes/unity-release-notes/unity-agent-140.mdx, src/content/docs/release-notes/mobile-release-notes/unreal-release-notes/unreal-engine-plugin-130.mdx
=> docs:unity and unreal release notes update.

src/content/docs/infrastructure/host-integrations/host-integrations-list/cloudfoundry-integrations/vmware-tanzu-nginx-buildpack-integration.mdx
Found this while writing release notes
=> fix(Infrastructure): NGINX should always be all-caps

src/content/docs/apis/rest-api-v2/get-started/get-app-other-ids-new-relic-one.mdx
=> fix(REST): Wrong procedure to get IDs (NR-289803)

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
the Expected errors code sample was demonstrating how to Ignore errors, I corrected it
=> fix: incorrect code sample

src/install/config/aws-logs.yaml
Fixes redirects missed in #17851
=> chore(logs): Fix missing redirects from #17851

src/content/docs/alerts/get-notified/message-templates.mdx
Added a note about handlebars to help with some confusion
=> docs(notifications): added note about handlebars

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx
- improve examples by runtime
- remove redundant Node.js example
=> chore: improve examples

src/content/docs/nrql/nrql-references/nrql-group-results-across-time.mdx
=> chore: clarify format values

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1552.mdx
=> chore: infra-agent 1.55.2 release doc

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3117.mdx
Adds release notes for minion version 3.1.17
=> Synthetics Minion 3.1.17 release notes

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx, src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3117.mdx
=> Daily release/aug 5 2024 2 34

src/content/docs/opentelemetry/best-practices/opentelemetry-manage-data-ingest-volume.mdx
=> chore: format code blocks

src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
- It might make sense to remove some of the itemized lists for clarity.
- fix for log lines to check in SJM
cc @jeff-colucci
=> fix indentation and numbering

src/content/docs/new-relic-solutions/business-observability/intro-pathpoint.mdx
Just tried to alter the language a little to incorporate the phrase business journey.
=> Fixed opening paragraphs

src/content/docs/alerts/create-alert/condition-details/title-template.mdx
* What problems does this PR solve? We got some internal [feedback](https://newrelic.slack.com/archives/CTMRYF51R/p1722925429745079) that the Title Template example provided had typos AND wasn't a very good example, so I've adjusted it accordingly.
=> fix(Title template): adjust example based on feedback

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-400.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.0.mdx
Adds release notes for Synthetics job manager and synthetics browser runner. 
=> SJM release notes

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx, src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx, src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/device-emulation.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/intro-synthetic-monitoring.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
DO NOT MERGE YET - I will post when this feature has been released.
Updated multiple documents to reflect support of an additional browser type and the ability to configure multiple device emulation configurations on a single monitor.
=> feat(MultiBrowser): Added Firefox support

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-91300.mdx
This PR adds release notes for the Python Agent, v9.13.0
=> Python Release notes v9.13.0

src/components/EolTable/EolTable.js, src/components/EolTable/TableHeader.js, src/i18n/translations/en/translation.json, src/pages/eol.js, src/templates/eolAnnouncement.js
- some copy changes
- add sort direction so headers can sort ascending and descending
- add some more padding to the right side of the page
=> EOL updates

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
- fixes for syntax, wording
- add missing steps
- improve headings for steps
- add clarifying details to help deflect support cases for common issues
=> docs: improve Lambda monitoring steps

src/content/docs/accounts/accounts-billing/account-structure/create-manage-accounts.mdx
Incorrect limit set in the docs
=> docs(billing): fixed workflows limit

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- Updated documentation to include support for Ubuntu 24.04
- Refer to the recently merged PR - [https://github.com/newrelic/open-install-library/pull/1098](url)  for more details.
=> Added support for Ubuntu 24.04

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.1.mdx
Correct node-browser-runtime version in latest release notes
=> fix: correct node-browser-runtime release notes version

src/components/SEO.js
Removes the vwo script from the site
=> Remove vwo

src/content/whats-new/2024/08/whats-new-08-12-synthetics-browsers.md
Added a what's new post for the Synthetics addition of Firefox support and easier configuration for configuring multiple emulated devices. 
This was reviewed via Slack by our PMM organization (Slack me if you need contact details).
=> feat(MultiBrowser): Whats new post

src/content/docs/ai-monitoring/drop-sensitive-data.mdx
Update the a small code block by removing AND condition as we add that programmatically and  Seems odd and inconsistent with our other filter .
Came to a conclusion by disussion with team intenally on the issure raises over internal slack . 
N/A
=> fix(aim): Removed AND condition from the drop sensitive-data file

src/content/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api.mdx
Fixing issue brought up in https://github.com/newrelic/docs-website/issues/18305
=> chore(DT): fixing API doc

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1600.mdx
infra-agent 1.56.0 release doc
=> chore: infra-agent 1.56.0 release doc

src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/agentless-monitoring-and-standardized-entity-creation.mdx
This release note was put in the wrong directory
=> fix(Infra): Fixed directory mix up

src/content/whats-new/2024/07/whats-new-7-23-OtelK8s-PP.md
Fixes malformed image path in whats new post. Was broken in NR UI > whats new as well.
https://docs.newrelic.com/whats-new/2024/07/whats-new-7-23-OtelK8s-PP/
=> fix: fix image path

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
- updating wording to account for new UI behavior
=> Instrumented view based on time picker

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1600.mdx
Fixed capitalization: [Infrastructure agent v1.56.0](https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1600/)
=> style(Release notes): Fixed capitalizaton

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Rework top-of-page PHP compatibility table and statements to improve clarity.
=> chore(php): rework php compatibility table

src/content/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations.mdx
See [18387](https://github.com/newrelic/docs-website/issues/18387)
=> style(AWS): Modified the first sentence under connect AWS and NR

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Improves the clarity and readability of the PHP Agent Framework compatibility table.
=> chore(php): rework framework compatibility table

src/content/docs/data-apis/ingest-apis/event-api/incident-event-rest-api.mdx
Reworded aggregation explanation, and reiterated it with a caution callout box
=> docs(events-api): added caution and reworded aggregation explanation

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/otel-adot-log-ingestion-serverless.mdx, src/nav/serverless-function-monitoring.yml
* First draft for ADOT lambda layer configuration for log ingestion service to New Relic
=> feat( Serverless lambda layer): Log ingestion solution for ADOT layer

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/otel-adot-log-ingestion-serverless.mdx
Let this one slip by me somehow
=> fix(Serverless): Fixed typo in title

src/content/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations.mdx
- add step monitors
- update links
=> add step monitors to VSE doc

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1561.mdx
Infra Agent 1.56.1 Release Notes
=> Infra Agent 1.56.1 Release Notes

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8140.mdx
Java agent 8.14.0 release docs
PLEASE RELEASE ASAP
=> Add Java agent 8.14.0 release notes and compatibility docs

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-112.mdx
* What problems does this PR solve? - Android NDK release notes v1.1.2
=> Target release date: 8/21/24 - Android NDK agent release notes v1.1.2

src/content/docs/security/security-privacy/information-security/report-security-vulnerabilities.mdx
Updating disclosure URL to our public bounty through Bugcrowd.
=> INFOSEC-10276 Update report-security-vulnerabilities.mdx

src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx
Found while writing release notes
=> fix(browser): Added missing header anchor tags

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Found while working on docs release notes
=> fix(PHP agent): Added missing header tag

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
Set RH minimum support to 7.9
https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance
=> infra agent: RH 7 minimum support 7.9

src/i18n/translations/es/translation.json, src/i18n/translations/jp/translation.json, src/i18n/translations/kr/translation.json, src/i18n/translations/pt/translation.json
all of the internal onboarding links were going to en sites despite being on different i18n sites
=> i18n links

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/uninstall-kubernetes.mdx
=> chore: add identifiers to codeblocks

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-1-0-14.mdx
These are release notes for an upcoming PHP release.
*** Please hold off merging this PR until I've let you know we've completed the release ***
Thanks!
=> chore(PHP): Relnotes for PHP agent release 11.1.0.14

src/content/docs/apm/agents/java-agent/related-integrations/micrometer/micrometer-metrics-registry.mdx
Fixing typo in this micrometer example code. See https://github.com/newrelic/newrelic-opentelemetry-examples/pull/665 for corresponding fix in working code example.
=> Fix OTLP endpoint in micrometer-metrics-registry.mdx

src/content/docs/apm/agents/java-agent/related-integrations/micrometer/micrometer-metrics-registry.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-1-0-14.mdx
=> Daily release/aug 26  2024 2 37

src/content/docs/apm/agents/go-agent/installation/install-automation-new-relic-go.mdx, src/nav/apm.yml
=> Golang:  Document new automation tool

src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
=> chore: format codeblock

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
- Fixed broken link
- Ticket: NR-306969
=> chore(Serverless monitoring): Fixed a broken link

src/content/docs/synthetics/synthetic-monitoring/using-monitors/view-simple-scripted-monitor-results.mdx
=> Synthetics: Update link to logging functions

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
We need to restore the connection between CodeStream and our Core user.
=> Accounts: Restore CodeStream references

src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx
This was a hero request to help users understand they need to include all the dashboard elements in a mutation--not just the ones they are changing. I worked with our SME to write this update.
=> Dashboards: Clarify update mutation

src/content/docs/new-relic-solutions/get-started/networks.mdx
Added S3 network endpoints for both the US and EU regions. The Synthetics UI may not function correctly if these endpoints are blocked.
=> fix(SyntheticsS3): Added S3 network endpoints

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1570.mdx
* Adds docs for new release of the infrastructure-agent
* https://github.com/newrelic/infrastructure-agent/releases/tag/1.57.0
=> docs: infrastructure agent v1.57.0

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- change `duration` and `nr.executionDuration` to the new `executionDuration` attribute
- add new code: 41 IEE
=> executionDuration and code 41

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-otel.mdx, src/nav/kubernetes-pixie.yml
Added the [OpenTelemetry for Kubernetes](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-otel/) doc to the navigation file.
=> feat(K8s): Added k8s-otel doc to the nav

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6070.mdx
* Add new release notes for the latest iOS mobile app
=> docs: Add in release notes for version 6.7.0 of the iOS mobile app.

src/content/docs/infrastructure/amazon-integrations/connect/aws-multi-account.mdx
https://new-relic.atlassian.net/browse/NR-309176
We intend to clarify how to set up cross account monitoring setup steps on AWS side. 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account-Setup.html
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html
=> docs: Clarify AWS cross account setup

src/content/docs/release-notes/docs-release-notes/docs-9-6-2024.mdx
Docs RNs for the week from 30 Aug through 5 Sep.
=> feat(Docs): Draft release notes

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-112.mdx
* What problems does this PR solve? - release notes update due to incompatibility.
=> [NR-298871] Android NDK agent release notes update due to incompatibility

src/content/docs/tutorial-manage-large-log-volume/organize-large-logs.mdx
Found a another section discussing partition best practice that needs to be addressed.   I want to make this section consistent with my recent revisions to the main page on log partitions.
=> Update additional section that references log partitions

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-billing-monitoring-integration.mdx, src/content/docs/infrastructure/amazon-integrations/connect/aws-multi-account.mdx
Add missing description for AWS source and monitoring account
https://new-relic.atlassian.net/browse/NR-309176
=> Describe AWS monitoring and source accounts for AWS cross account

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-application-migration-service-integration.mdx, src/nav/infrastructure.yml
AWS saw the docs page and requested a few minor changes.
=> Chore: minor changes to ams

src/content/docs/infrastructure/other-infrastructure-integrations/cloudfoundry-integrations/vmware-tanzu-firehose-nozzle-integration.mdx
We are planning a new release by Sep 9 2024 and hence updating the documentation.
=> (9/9/24) fix: Update vmware-tanzu-firehose-nozzle-integration.mdx

src/content/docs/query-your-data/explore-query-data/dashboards/dashboard-template-variables.mdx
Updated the [Template variables: dynamically filter dashboards](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboard-template-variables).
=> style(Dashboards): Added steps component and TW edits

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx, src/content/docs/nrql/using-nrql/rate-limits-nrql-queries.mdx
Per SME, we needed to streamline the max duration description
=> Accounts: Change max duration

src/content/docs/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx
=> fix(OTEL): typo

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-760.mdx
* What problems does this PR solve? - [NR-299076] Android agent v7.6.0 release notes and feature flags
[NR-299076]: https://new-relic.atlassian.net/browse/NR-299076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Target to release 9/10/24 - Android agent v7.6.0 release notes and feature flags

src/content/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page.mdx
@nbaenam It's good not to use NR as an acronym for New Relic
=> fix(K8s): Fixed a couple of minor style guide things

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-agent-gradle.mdx
=> fix(Android): removing duplicate sentence

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
=> fix(Node.js): Clarifying note

src/content/docs/infrastructure/amazon-integrations/connect/aws-multi-account.mdx
@nbaenam I ran across this while doing release notes. I think it's best if we avoid non-standard procedural steps like this.
=> fix(AWS): Fixed some non-standard procedural steps

src/content/docs/infrastructure/host-integrations/host-integrations-list/envoy-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
**Description:** Updated the Envoy and Nextcloud documentation
**Ticket:** https://new-relic.atlassian.net/browse/NR-312791
=> Updated envoy and nextcloud documentation

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx, src/content/docs/release-notes/logs-release-notes/logs-24-09-11.mdx
=> docs: updated release notes and amazon linux 2023 arm64 docs

src/content/whats-new/2024/08/whats-new-8-01-eol-fid.md
=> chore(WN): fixes to EOL announcement formatting

src/content/docs/infrastructure/host-integrations/host-integrations-list/nextcloud-integration.mdx
**Description:** Updated the Nextcloud documentation
**Attaching screenshots with changes**
=> fix: Updated nextcloud documentation

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1571.mdx
=> chore: add infra-agent 1.57.1 release notes

.github/auto_assign.yml
@akristen once this is merged in, you'll be back on the auto-assign reviewer list
=> chore(Docs): Added akristen back to auto-reviewer list

src/content/whats-new/2024/09/alerts-slack-notification-enhancements.md
Fixing some images / testing if I remember how to do this.
=> feat(whats-new): fixing md images in whats new post from 9/12

src/content/whats-new/2024/09/whats-new-09-17-chart-refresh-rate.md
What's new post for Sept 17th. Does not require PMM review
=> [9/17] feat(whats-new): add refresh rates post

src/content/docs/logs/logs-context/annotate-logs-logs-context-using-apm-agent-apis.mdx
Per hero channel request, updating links to somewhere more relevant :)
=> feat(apm): update api docs to go to helpful places

src/content/docs/alerts/get-notified/muting-rules-suppress-notifications.mdx
Reverting modifications on the [Muting rules: Suppress notifications](https://docs.newrelic.com/docs/alerts/get-notified/muting-rules-suppress-notifications/) the feature is not live yet.
=> fix(Alerts): Reverting modifications, the feature is not live yet

src/content/whats-new/2024/09/whats-new-09-11-logs-in-context-in-kubernetes-deployments.md
=> fix(K8s): last fix

src/content/whats-new/2024/09/whats-new-09-18-logs-in-context-in-kubernetes-deployments.md
=> fix(K8s): fixing date

src/nav/infrastructure.yml
Found while working on release notes
=> fix(Infra): Fixed capitalization

src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx
clarify what means associated in this context
=> chore: clarify storage sample docs (NR-312536)

src/content/docs/infrastructure/elastic-container-service-integration/ecs-integration-recommended-alert-conditions.mdx, src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts.mdx
=> chore: update alert link, backticks around nrql

src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
Added tips for a few additional common error scenarios.
=> feat(RuntimeUpgrade): Added additional troubleshooting scenarios

src/content/docs/infrastructure/other-infrastructure-integrations/databricks-integration.mdx, src/nav/infrastructure.yml
Mostly pulled from the gh readme of our databricks integration - https://github.com/newrelic-experimental/newrelic-databricks-integration
This covers how to set up the databricks integration and monitor spark clusters in New Relic.
=> feat: Added databricks integration docs

src/content/docs/infrastructure/host-integrations/host-integrations-list/ocsf-integration.mdx
Exploded the OCSF acronym in the first sentence on the [OCSF integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ocsf-integration/) page
=> feat(OHI OCSF): exploded the OCSF acronym

src/content/docs/infrastructure/amazon-integrations/troubleshooting/no-data-metric-streams.mdx
Adding some AWS official doc links to troubleshooting steps.
=> Add AWS Firehose troubleshooting docs

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1570.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1571.mdx
* Adding a post-release note explaining a known issue that's part of infra agent releases 1.57.0 and 1.57.1.
=> fix(infra-agent): failed releases note

src/content/docs/infrastructure/amazon-integrations/troubleshooting/no-data-metric-streams.mdx
Adding guidans on when to open a AWS support case when troubleshooting CloudWatch Metric Streams
=> Add AWS support guidance for metric streams

src/content/docs/alerts/get-notified/muting-rules-suppress-notifications.mdx
Updated the [Muting rules: Suppress notifications](https://docs.newrelic.com/docs/alerts/get-notified/muting-rules-suppress-notifications/) and added the How to suppress notifications section.
Ticket: NR-306174
=> feat(Alerts): Updated the Muting rules: Suppress notifications doc

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-max-offline-storage.mdx
Updating the Feature Flag enable command to correct value.
=> Update set-max-offline-storage.mdx (updating the feature flag command from disable to enable) 

src/content/whats-new/2024/09/whats-new-09-30-cardinality-management.md
What's new post 9/30/2024 for Cardinality Management UI. 
PM: Neranjan Kuppuswamy
No PMM review necessary, but would appreciate a regular review for language/formatting, etc.
Thank you!
=> feat(whats-new): add cardinality management post

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Add compatibility notes for .NET Memcached support. 
Agent just release so this is ready to merge!
Release: https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v10.31.0
Related to https://github.com/newrelic/docs-website/pull/18768
=> chore:Add compatibility notes for .NET Memcached support.

.github/CODEOWNERS, .github/workflows/check-translations-and-deserialize.yml, .github/workflows/update-attribute-dictionary-json.yml
Some of our workflows are failing trying to request our old team, this should fix that!
=> Use updated github team names in workflows

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6080.mdx
Update to latest iOS release notes
=> Add in release mobile app for iOS 6.8.0 release notes

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11.2.0.15.mdx
* Adds Release notes for PHP Release 11.2.0.15
=> feat(php): 11.2.0 Release Notes

src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-9-14-0.mdx
Fix spelling error: Acion => Action
cc @paperclypse
=> chore: Update ruby-agent-9-14-0.mdx

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-permissions.mdx
I removed the bullet point that talks about anomaly configurations with regards to permissions.  We EOL'd anomaly configurations awhile ago.
=> Removed reference to anomalies

src/content/docs/infrastructure-as-code/terraform/terraform-intro.mdx
Reworked top portion of article to integrate a tip guiding users to CodeStream.
=> Update intro article to reference CodeStream

src/content/docs/browser/new-relic-browser/troubleshooting/troubleshoot-ajax-data-collection.mdx
- Changed the numbering format for the document, following the New Relic documentation standard.
- Added an additional call out for a better readability
- Ticket: NR-307781
=> chore(browser agent): Fixed the numbering format and added a callout

.github/workflows/update-whats-new-ids.yml
=> fix: Update reviewer team name

.github/workflows/update-whats-new-ids.yml
for some reason the action is committing package.json changes, hopefully this stops that
=> Clean any other staged changes after adding json

src/content/docs/codestream/troubleshooting/client-logs.mdx, src/content/docs/codestream/troubleshooting/using-wsl.mdx, src/nav/codestream.yml
- Reword docs for gathering logs for Visual Studio
- Add troubleshooting doc for using WSL and CodeStream from Windows.
=> CodeStream Doc Updates

src/content/docs/mobile-monitoring/new-relic-mobile-android/troubleshoot/no-crash-data-appears.mdx, src/content/docs/release-notes/mobile-release-notes/unity-release-notes/unity-agent-141.mdx, src/nav/mobile-monitoring.yml
added troubleshoot for android crash not appearing in the UI. 
release notes for Unity Agent 1.4.1
=> docs:Troubleshoot and release note

src/content/docs/browser/browser-monitoring/browser-pro-features/user-actions.mdx, src/nav/browser.yml
This PR adds a general description of a new event type the Browser Agent is about to start capturing.
=> (Publish on 10/7/2024 with attribute dictionary changes) Browser agent: add user action docs

package.json, src/hooks/usePagination.js, src/pages/search-results.js, yarn.lock
You can test this out by going to this path `/search-results/?query=node%20agent&page=1`
=> Add search results page

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
* Add agent configuration documentation links and links to docker hub into the agent operator docs.
=> Add APM agent information into operator docs - PLEASE MERGE Oct 3 PM

src/pages/eol.js
unitalicizing EOL posts past their EOL date
=> chore: unitalicize EOL posts past their EOL date

src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/migration-guide.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/setup-prometheus-agent.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/troubleshooting-guide.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/argocd-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/calico-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/cockroach-db-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/core-dns-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/etcd-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/harbor-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/ingress-controller-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/node-exporter-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/redis-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/traefik-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/integrations-list/velero-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/compare-rw-data-sent-billed-bytes.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/get-logs-prometheus-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/rate-limit-errors-prometheus-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/restarts-gaps-data-kubernetes.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/filter-new-relic-one-dashboards-facets.mdx
=> chore: code formatting

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx
Added an important note about billable events on the [Query Kubernetes data](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data/#view-data) section.
Ticket: NR-317104
=> feat(K8s): Added important note about billable events

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
Removed unavailable video per hero request
=> remove 404 video

src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-114.mdx
=> docs: flutter release 1.1.4

src/pages/nr-ai-compare.js
=> use subgrid to align results

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/enable-fedramp-endpoints.mdx
=> chore: formatting code terminal output

src/content/docs/alerts/scale-automate/rest-api/disable-enable-alerts-conditions-using-api.mdx, src/content/docs/alerts/scale-automate/rest-api/manage-entities-alerts-conditions.mdx, src/content/docs/alerts/scale-automate/rest-api/rest-api-calls-alerts.mdx
I also replaced one in-json comment with a `lineHighlight`. Because comments are invalid in json and this is a case of json inside a shell command, so it won't format accurately with syntax highlighting  
=> chore: code formatting, consistancy of variable names & comment styles

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/add-tracked-headers.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/create-attribute.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/current-session-id.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/increment-session-attribute-count.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/mobile-sdk-api-guide.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/name-interaction.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/network-request-failures.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/network-request-success.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-breadcrumb.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-custom-events.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-custom-metrics.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-errors.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-handled-exceptions.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/remove-all-attributes.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/remove-attribute.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-application-build-number.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-application-version.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-custom-user-id.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-max-event-buffer-time.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-max-event-pool-size.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-max-offline-storage.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/shut-down-agent.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/start-interaction.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/stop-interaction.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/test-crash-reporting.mdx
The indented code blocks were causing the anchor tags to render as plaintext.
UPDATE: This turned up other code block indentation issues that need to be fixed.
=> fix(Mobile): Fixed codeblock issues

src/content/docs/apm/agents/python-agent/hosting-services/python-agent-microsoft-azure.mdx, src/content/docs/apm/agents/python-agent/hosting-services/python-azure-containerapps-appservice.mdx, src/nav/apm.yml
This PR adds instructions to install the New Relic Python agent when an application uses Microsoft Azure as a host
=> Python Azure: Add installation instructions for Azure in Python

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
##
Jira Issue: [NR-2524](https://new-relic.atlassian.net/browse/NR-2524)
The tip claiming that median only works in the QueryBuilder was incorrect and is thus being removed.
[NR-2524]: https://new-relic.atlassian.net/browse/NR-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Removing false tip from nrql-syntax-clauses-functions.mdx

src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.47.0.mdx
Adds release notes for the latest version of the synthetics-ping-runtime release (1.47.0)
synthetics-ping-runtime public container: [docker hub](https://hub.docker.com/layers/newrelic/synthetics-ping-runtime/1.47.0/images/sha256-48d89ea3168c8c4b96dcd91a486acce7a385f97439926600feb42492bd5030cf?context=explore)
=> docs: add synthetics-ping-runtime 1.47.0 release notes

scripts/actions/__tests__/add-files-to-translation-queue.test.js, scripts/actions/utils/constants.js, scripts/actions/utils/docs-content-tools/i18n-exclusions.yml, scripts/i18n_utility/__tests__/actions.test.ts, src/components/EolPage.js, src/components/InlinePopover/InlinePopover.js, src/data/popovers_fr.json
Updated doc file for language additions: [NR-325289](https://new-relic.atlassian.net/browse/NR-325289)
[NR-325289]: https://new-relic.atlassian.net/browse/NR-325289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: updating doc file for supporting french lang

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates .NET agent Compatibility docs for latest supported framework versions.
=> chore(dotnet): Update compatibility docs for latest supported framework versions

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-761.mdx
=> docs: android release notes (10/17)

src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.14.mdx
PR adds release notes for Lambda Extension release [v2.3.14](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.14)
NA
NA
=> Add release notes for Lambda Extension v2.3.14

src/content/docs/apm/agents/net-agent/net-agent-api/net-agent-api.mdx
PR where the feature was added: https://github.com/newrelic/newrelic-dotnet-agent/pull/2320
=> Adding RecordDatastoreSegment to .NET Agent API

src/content/docs/browser/browser-integrations/blazor-webassembly.mdx
=> fix(Blazor): fixing erroneous metadata

src/content/docs/iast/iast-configuration.mdx, src/content/docs/iast/troubleshooting.mdx
indentation needs to align with the opening backticks of the codeblock or it renders incorrectly
=> fix: indentation

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own.mdx
Add example for CDK support for Lambda instrumentation in the [page](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/instrument-your-own/)
=> Add example for CDK Lambda instrumentation

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-3-0-16.mdx
Adds release information for PHP Agent release 11.3
=> feat(php): release 11.3

src/content/docs/network-performance-monitoring/advanced/ktranslate-container-health.mdx
The severity of the Ktranslate log has been added.
=> Ktranslate log severity

src/content/docs/licenses/product-or-service-licenses/new-relic-logs/logs-plugin-licenses.mdx
While reading the OSS Litmos training, I noticed a missing word in one of the screenshots. The related sentences are updated in this PR.
=> chore: Add missing "to"

src/content/docs/licenses/product-or-service-licenses/new-relic-logs/logs-plugin-licenses.mdx
Reverts newrelic/docs-website#19024
=> Revert "chore: Add missing "to""

src/content/docs/licenses/product-or-service-licenses/new-relic-logs/logs-plugin-licenses.mdx
See https://github.com/newrelic/docs-website/pull/19024 and https://github.com/newrelic/docs-website/pull/19032
=> fix(Logs): Added missing "to"

src/content/docs/alerts/admin/rules-limits-alerts.mdx
The way alert conditions are limited is changing slightly, so this commit consolidates the infrastructure, nrql and web app response conditions into "alert conditions per account", which is how it will be metered moving forward.
=> (NR-320588) Update limits docs for alerts

src/content/docs/infrastructure/prometheus-integrations/view-query-data/supported-promql-features.mdx, src/content/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql.mdx, src/content/docs/query-your-data/explore-query-data/query-builder/introduction-query-builder.mdx
Per a hero request, fixed broken links.
=> fix(Infra Prometheus): Fixed broken links

src/content/docs/new-relic-solutions/build-nr-ui/newrelic-cli.mdx
https://github.com/newrelic/newrelic-cli/blob/main/docs/cli/newrelic.md
=> fix: link & update CLI options

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator.mdx
=> Changing one word to plural

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
=> chore: fix indentation for JS

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-35-1.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-35-1.mdx.mdx
=> go agent release 3 35 1

src/components/FrNav.js, src/components/RootNavigation.js
Adds another nav component for french, this won't be relevant until we get other changes in like the language picker from the theme, locale added to docs site, and the french nav json
=> Add french nav component

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx, src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/interpret-nrdiag-output.mdx, src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx, src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/validate-config-file-settings-nrdiag.mdx
=> chore: formatting cli commands

src/content/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql.mdx
=> fix: typo & capitalize nrql clauses

src/content/docs/alerts/create-alert/condition-details/incident-event-attributes.mdx
Addresses this question in #help-alerts https://newrelic.slack.com/archives/C0DSAFF8Q/p1729698866535889 
Notates certain attributes that are not available to description template and title template for alert conditions.
=> fix(Alerts): Update NRAI attribute information

src/data/whats-new-ids.json
=> Daily release/10 28 24 whatsnew

src/content/docs/apis/nerdgraph/examples/async-queries-nrql-tutorial.mdx
As the Dirac CAT team aims to add cancel async query to Nerdgraph, we are looking to add a block to explain to customers how to do so. We are adding onto the existing Nerdgraph async query document to keep everything cohesive and in one doc.
=> feat: Add Cancel Query Nerdgraph Block 

src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx
reference: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework/?tab=windows
=> chore: adding another conflicting profiler & aphabetizing

src/content/docs/release-notes/docs-release-notes/docs-11-01-2024.mdx
=> feat(docs): Draft rel notes for 1 Nov

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-native-crash-reporting.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-maui-dotnet/monitor-your-net-maui-application.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-unreal-engine/monitor-your-unreal-engine-application.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-xamarin/monitor-your-xamarin-application.mdx, src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
=> fix: code typos & formatting

src/content/docs/alerts/create-alert/create-alert-condition/alert-conditions.mdx, src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
Reverts newrelic/docs-website#19091
=> Revert "update fluent bit output plugin document"

src/content/docs/apis/nerdgraph/examples/async-queries-nrql-tutorial.mdx
Reverts newrelic/docs-website#19117
=> Revert "feat: Add Cancel Query Nerdgraph Block "

src/content/docs/infrastructure/infrastructure-agent/configuration/configure-infrastructure-agent.mdx, src/content/docs/infrastructure/infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx, src/nav/infrastructure.yml
Fixed the incorrect navigation link for  Infrastructure Agent > Configuration > Configuration settings
=> fix(infrastructure agent): Fixed the incorrect navigation 

src/content/docs/vulnerability-management/integrations/fossa.mdx
=> chore(Vuln): style changes to FOSSA doc

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/iso-27001.mdx
Compliance updates based on New Relic's 2024 annual assessments.
=> Compliance update to iso-27001.mdx

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-memorydb-monitoring-integration.mdx, src/nav/infrastructure.yml
This adds documentation for amazon memoryDB. The entity exists already so this is to provide documentation and info around the metrics included in the integration.
=> feat: Added memorydb documentation

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/enable-serverless-monitoring-aws-lambda-layerless.mdx
- In the last while raising PR for documentation, few of the points got merged  into 10th point and got duplicated so this removes the two duplicated points.
=> Update: Removed duplicated links for the NodeJS documentation.

src/content/docs/security/security-privacy/compliance/hitrust.mdx
Compliance updates based on New Relic's 2024 annual assessments.
=> Compliance update to  hitrust.mdx

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp.mdx
Compliance updates based on New Relic's 2024 annual assessments.
=> Compliance update to fedramp.mdx

src/content/docs/release-notes/logs-release-notes/logs-24-10-31.mdx
Draft release notes for pending Fluent Bit 3.1.9 upgrade.
=> Release notes for Fluent Bit 3.1.9 upgrade

src/nav/infrastructure.yml
URL was broken, basic fix to resolve URL issue.
=> chore: Fix url for memdb

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
Detail how/why we can use top level `await`.
=> add bullet point for advanced example

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-rds-monitoring-integration.mdx
- Updated the UI path to the document
- Ticket: NR-257304
=> Chore(AWS): updated the UI path for the configuration

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
Update query CSV export limitations to remove comments (this was fixed) and add cross-account queries
https://new-relic.atlassian.net/browse/NR-339734
=> fix: Update query CSV export limitations

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1580.mdx
=> chore: infra-agent release 1.58.0

src/content/whats-new/2024/11/whats-new-11-12-browser-apm-summary.md
Can be posted after review is approved. 
PMM Lavanya Chockalingam can review
=> feat(whats-new): add browser on apm summary post

src/content/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx, src/i18n/content/jp/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx, src/i18n/content/kr/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx, src/i18n/content/pt/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics.mdx
=> The actual limit name ends in per day

src/content/docs/mobile-monitoring/mobile-monitoring-ui/mobile-logs.mdx
=> added Unity example for logs

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates the .NET agent compatibility documentation to reflect latest supported version of several libraries.
=> chore(dotnet): Update .NET agent compatibility docs

src/content/docs/logs/logs-context/custom-tags-agent-forwarder-logs.mdx, src/nav/logs.yml
=> Updated the documents

src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Cloned the PR from https://github.com/newrelic/docs-website/pull/19239
=> Cloned the PR from https://github.com/newrelic/docs-website/pull/19239

src/content/docs/infrastructure/infrastructure-agent/linux-installation/azure-extensions-infrastructure.mdx
=> Updated the redirect link

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Created another PR for https://github.com/newrelic/docs-website/pull/19213 as there was a cli conflict
=> Updated the document

src/install/microsoft-sql/whatsNext.mdx
* Add optional parameter to run query to fetch DB instance size, the query can be slow that's why adding a param to fetch when needed.
=> Update docs to include optional parameter.mdx

src/install/microsoft-sql/whatsNext.mdx
Reverts newrelic/docs-website#19312
=> Revert "Update docs to include optional parameter.mdx"

src/content/docs/data-apis/manage-data/query-limits.mdx
attempting to follow the style guide as well
=> chore: format NRQL

src/content/docs/infrastructure/host-integrations/host-integrations-list/unix-monitoring-integration.mdx
Updated the URL and added JDK constraints.
=> fix: Update unix-monitoring-integration.mdx

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
…
Documents new configuration options that will be made available in the upcoming release of Node.js agent(12.8.0)
=> chore: Added new configuration to enable and exclude labels from being added to application logs in Node.js agent

src/content/docs/infrastructure/host-integrations/installation/secrets-management.mdx
Adding additional warning to obfuscation guide, as requested in NR-306590
Adds disclaimer as requested by Application Security (NR-306590)
=> docs: Update secrets-management.mdx

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-agent-gradle.mdx
* What problems does this PR solve? - minor doc update
=> Minor doc update

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
We have a new non-profit program partner "goodstack" (previously know as percent). I have made these changes in the document and creating this PR to reflect new name of our non-profit program partner in our docs.
=> Updated the nonprofit partner name

src/content/docs/infrastructure/infrastructure-agent/requirements-infrastructure-agent.mdx
Reverts newrelic/docs-website#19370
=> Revert "Add callout for OS which does not support logforwarding"

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
We are updating the docs as we have release supported Lambda layers & ECR images for AWS Lambda runtime `Python 3.13`. 
=> add support for python 3.13

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp.mdx, src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/iso-27001.mdx, src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/pci-dss.mdx, src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/tisax.mdx, src/content/docs/security/security-privacy/compliance/hitrust.mdx, src/content/docs/security/security-privacy/compliance/regulatory-audits-new-relic-services.mdx, src/nav/new-relic-security.yml
Add PCI-DSS and update compliance pages to include Pixie for out-of-scope
=> Add PCI-DSS and update compliance pages

src/install/ai-monitoring/agentConfigDefault.mdx
- Ticket: NR-303304
- Added a call out regarding the distributed_tracing.enabled
=> chore(AI Monitoring): Added a callout regarding the distributed_tracing.enabled

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
These links don't currently expire
=> chore: Update dashboards-charts-import-export-data.mdx

src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-platform.mdx
These links don't currently expire
=> chore: Update introduction-new-relic-platform.mdx

src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx, src/install/config/snowflake.yaml
Restored missing snowflake flex files as per the following Slack thread: [thread1](https://newrelic.slack.com/archives/C0DSGL3FZ/p1732614542325129) and [thread2](https://newrelic.slack.com/archives/C0DSGL3FZ/p1732306260430519).
I have created a [Jira NR-344579](https://new-relic.atlassian.net/browse/NR-344579) to validate the content and new updates.
=> chore[snowflake]: Restored the missing snowflake flex files

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-permissions.mdx
The first sentence used 'rolls' instead of 'roles'.
=> Fix: Change to the correct spelling for roles

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/introduction-lambda.mdx
We are updating the docs as we have released Lambda layers & ECR images for the latest AWS Lambda runtime `Nodejs 22`.
=> update support for nodejs22 lambda runtime

src/content/docs/nrql/nrql-examples/nrql-query-examples-mobile-monitoring.mdx
Updated the links for the docs
=> fix(mobile): Updated the link

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
=> updated the doc as we don't support all the azure resource for azure monitor

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/record-handled-exceptions.mdx
=> fix: code indentation

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx
=> fix broken link to Prometheus agent install

src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
Add trilogy and cleanup old entries
=> Update Instance Details table

src/content/docs/infrastructure/infrastructure-agent/windows-installation/windows-zip-assisted.mdx
=> doc: fix typo

src/content/docs/data-apis/understand-data/metric-data/metric-data-type.mdx, src/content/docs/data-apis/understand-data/metric-data/query-apm-metric-timeslice-data-nrql.mdx, src/content/docs/data-apis/understand-data/metric-data/query-metric-data-type.mdx, src/content/docs/data-apis/understand-data/new-relic-data-types.mdx, src/content/docs/infrastructure/infrastructure-data/default-infra-data.mdx
=> chore: format NRQL clauses

src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx, src/content/docs/apm/transactions/intro-transactions/monitor-background-processes-other-non-web-transactions.mdx, src/install/dotnet/installation/wcf.mdx, src/install/dotnet/intro.mdx
=> fix(wcf): added redirects for WCF

src/content/docs/logs/logs-context/configure-logs-context-go.mdx
Update the document for the following information:
- Updated as per [NR-261487](https://new-relic.atlassian.net/browse/NR-261487)
- Updated the Logging libraries and attributes tables.
[NR-261487]: https://new-relic.atlassian.net/browse/NR-261487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(GO): Added attribute information in Option1, and updated the table

src/content/docs/logs/troubleshooting/aws-log-integration-issues/log-forwarding-restrictions.mdx, src/install/aws-logs/aws_services/configure-log-forwarding.mdx
Updating the review comments from https://github.com/newrelic/docs-website/pull/19469.
=> feat(aws-log-forwarding): Implemented review comments

src/i18n/content/pt/docs/accounts/original-accounts-billing/original-product-based-pricing/original-pricing-plan-queries.mdx
Replacing CU to UC in Portuguese
=> Update to Portuguese pages

src/install/jmx/whatsNext.mdx
Adds an extra troubleshooting case
=> doc: add jmx troubleshooting

src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-154.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-704.mdx, src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-116.mdx, src/content/docs/release-notes/mobile-release-notes/net-maui-release-notes/net-maui-agent-116.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-148.mdx, src/content/docs/release-notes/mobile-release-notes/unity-release-notes/unity-agent-143.mdx
=> docs:hybrid agent releases

src/content/docs/infrastructure/infrastructure-agent/linux-installation/infra-agent-as-container.mdx
The "backslash" is commented out and the command will fail as-is. Moved "backslash" before comment so that it will execute.
=> Docker run command failure

src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Reverts newrelic/docs-website#19492
=> Revert "docs(logs): Add new syslog mechanism to send the license key"

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
=> chore: linking the global attributes section

src/content/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic.mdx
=> feat: add section for removing otel apps

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/openshift/errors.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/openshift/fluent-bit.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/openshift/ksm.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/openshift/security-context-constraints.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/overview.mdx, src/install/kubernetes/prepare-install.mdx
=> doc: Update OpenShift compatibility version and add troubleshooting steps

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
As per a help request,  fixed a broken link at Monitor private location page.
=> chore(Synthetics): fixed broken link

src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Reverts newrelic/docs-website#19515
=> Revert "Revert "docs(logs): Add new syslog mechanism to send the license key""

src/content/docs/release-notes/logs-release-notes/logs-24-12-11.mdx
Hi! 
This is just updating Logs release notes with the changes documented on #19492 
Regards!
=> docs(logs): Update release notes

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1581.mdx
=> chore: infra-agent 1.58.1 release doc

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100400.mdx
* Add release notes for v10.4.0 of Python agent.
* Add new config setting into Python config docs.
=> Add new config setting & 10.4.0 release notes for Python -- PLEASE MERGE Dec 13 AM

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
Requested to update the support case accordion through help-doc channel
=> chore(licenses): Updated support case

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6086.mdx
=> iOS App Release Notes 6.8.6

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx
=> Set the default networking mode to be used.

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
=> Added sections detailing resource requirements by component

src/content/docs/release-notes/logs-release-notes/logs-24-12-18.mdx
=> adding release notes for unified lambda

src/content/docs/mlops/bring-your-own/getting-started-byo.mdx, src/content/docs/mlops/integrations/datarobot-mlops-integration.mdx
=> chore: code in backticks

src/content/docs/release-notes/docs-release-notes/docs-12-13-2024.mdx
=> Updated the release notes as the links were not working

scripts/releaseNotes.mjs, src/utils/getAgentName.js
=> Add fluentbit agent in release-notes json

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1590.mdx
=> chore: infra-agent 1.59.0 release doc

src/content/docs/apis/nerdgraph/examples/nerdgraph-distributed-trace-data-tutorial.mdx
https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-distributed-trace-data-tutorial/#trace-metadata
=> fix: broken link markdown

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-418.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-424.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.12.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.15.mdx
=> Update release notes of SJM and Node Browser Runtime.

src/content/docs/codestream/troubleshooting/proxy-support.mdx
=> Update proxy-support.mdx to include info about extra certs

src/content/docs/release-notes/docs-release-notes/docs-12-20-2024.mdx
As per the process, creating this release notes for doc updates between Dec 13th to 19th, 2024.
=> chore[docs]: Release notes for week of 19-Dec

src/content/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api.mdx
=> fix: cleanup breaks in CURL cmd

src/content/docs/infrastructure/amazon-integrations/connect/set-up-aws-api-polling.mdx
Our Metric Streams install doc migrated to a new page with user-selectable options.
=> fix broken links

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images.mdx
Renamed urls as per new page names
=> Update containerized-images.mdx to rename urls

src/content/docs/serverless-function-monitoring/overview.mdx
=> Update overview.mdx to correct indentation

src/content/docs/vulnerability-management/integrations/fossa.mdx, src/content/docs/vulnerability-management/integrations/snyk.mdx
=> chore: capitalize NRQL clauses

src/content/docs/infrastructure/other-infrastructure-integrations/cloudfoundry-integrations/vmware-tanzu-firehose-nozzle-integration.mdx, src/content/docs/infrastructure/other-infrastructure-integrations/cloudfoundry-integrations/vmware-tanzu-nginx-buildpack-integration.mdx
Updated Platform Supported versions
=> Updated Platform Supported versions

src/content/docs/infrastructure/other-infrastructure-integrations/monitoring-jenkins-ot.mdx
Fixed an issue with a sentence that describes how resource attributes that start with tags. are handled.
=> fix(grammar): Improved grammar from my previous PR

src/content/docs/alerts/overview.mdx
Fixed the broken link in the Alert overview page.
=> [CHORE]: Fixed the broken link

src/content/docs/release-notes/docs-release-notes/docs-1-2-2025.mdx
=> chore[docs]: Release notes for week of 21-Dec to 2-Jan(2025)

src/content/docs/service-level-management/create-slm.mdx, src/content/docs/tutorial-improve-app-performance/create-benchmarks.mdx
=> chore: capitalize nrql queries

src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx
=> feat: add azure site extention update instructions

src/install/dotnet/installation/azure-app-add.mdx
=> fix: typo + code in backticks

src/content/docs/service-level-management/create-slm.mdx, src/content/docs/style-guide/structure/code-examples.mdx
per the style guide:
> Capitalize clause keywords such as FROM, SELECT, FACET, WHERE, AND, OR, AS, SINCE, ORDER BY, TIMESERIES, EXTRAPOLATE, and AUTO.
https://docs.newrelic.com/docs/style-guide/structure/code-examples/#NRQL
=> chore: capitlazie NRQL syntax  & linebreaks

src/content/docs/infrastructure/host-integrations/host-integrations-list/temporal-cloud-integration.mdx
Updating the flex yaml for Temporal.io docs.
=> chore: Update temporal yml

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx, src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/diagnostics-beginner-guide.mdx, src/i18n/content/jp/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
=> fix: convert mdx table to html

src/content/docs/logs/ui-data/parsing.mdx, src/content/docs/release-notes/logs-release-notes/logs-25-01-10.mdx
We are introducing new Grok Parsing action in Logs Parsing i.e Key Value Parsing action https://new-relic.atlassian.net/browse/NR-64972 which was in private preview till now and we want to make it Globally Available now
=> [NR-353267] Update docs with Key Value Parsing Grok Expression

src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx
the link in this page doesn't open the doc section it points too, I think the section is too far nested. I also clarified that you need to remove the extension, then re-install it which was not clear
=> fix: finish the .NET azure update/remove instructions

src/i18n/content/kr/docs/apm/agents/net-agent/troubleshooting/cocreateinstance-errors-no-profiler-log.mdx
=> Update Korean cocreateinstance-errors-no-profiler-log.mdx

src/content/whats-new/2024/11/whats-new-11-11-data-explorer.md
Update whats-new-11-11-data-explorer.md to include relevant databyte demo
=> Add databyte video to data explorer what's new

src/content/docs/release-notes/docs-release-notes/docs-1-9-2025.mdx
=> chore[docs]: Release notes for week of 3-9, Jan (2025)

src/content/docs/release-notes/docs-release-notes/docs-1-9-2025.mdx
Did a few linguistic correction on https://github.com/newrelic/docs-website/pull/19687
=> chore[docs]: 10th Jan Release note correction

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1592.mdx
=> chore: infra-agent 1.59.2 release doc

scripts/releaseNotes.mjs, src/content/docs/release-notes/index.mdx, src/content/docs/release-notes/nrdot-release-notes/index.mdx, src/content/docs/release-notes/nrdot-release-notes/nrdot-24-10-25.mdx, src/utils/getAgentName.js
Add release notes for NRDOT 0.8.5
=> docs: adding release notes for NRDOT

src/content/docs/alerts/get-notified/notification-integrations.mdx, src/i18n/content/es/docs/alerts/get-notified/notification-integrations.mdx, src/i18n/content/jp/docs/alerts/get-notified/notification-integrations.mdx, src/i18n/content/kr/docs/alerts/get-notified/notification-integrations.mdx, src/i18n/content/pt/docs/alerts/get-notified/notification-integrations.mdx
The version that the notification docs are pointing to in Service Now is outdated. This updates the link from being version 1.0.0 to version 1.1.1
=> chore: Update version of snow integration

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Update the .NET compatibility and requirements doc to reflect the latest supported versions for libraries we instrument.
=> chore(dotnet): Update compatibility doc for latest supported library versions

src/content/docs/apis/nerdgraph/examples/nerdgraph-api-cross-account-alerting-elections.mdx, src/nav/telemetry-data-platform.yml
Fulfills an internal request for API examples for how to perform the bulk updates (in NerdGraph) to cross-account alerting elections
=> docs: Add API examples for cross-account alert elections

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates the compatibility and requirements doc for the .NET agent to reflect the latest supported library versions.
=> docs(dotnet): Update compatibility docs

src/content/whats-new/2025/01/whats-new-03-01-rest-api-keys-eol.md
As directed by PM, changed the What's new publication date.
=> Correction to What's new release date

src/nav/browser.yml
Updated the left nav for browser api
=> Updated the left nav for browser api

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-x-ray-monitoring-integration.mdx
=> chore: capitalize NRQL

src/content/docs/alerts/get-notified/new-relic-webhook-for-microsoft-teams-workflow.mdx
Fix the backticks issue in the payload.
=> fix the backticks issue

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1560.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1600.mdx
=> chore: infra-agent 1.60.0 release doc and fix 1.56.0 doc

src/content/docs/apis/nerdgraph/examples/export-import-dashboards-using-api.mdx, src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx, src/content/docs/apis/nerdgraph/examples/manage-live-chart-urls-via-api.mdx, src/content/docs/apis/nerdgraph/examples/mobile-monitoring-config-nerdgraph.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-cloud-integrations-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-concurrency-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
=> chore: fix & add syntax highlighting

src/content/whats-new/2025/01/whats-new-01-16-azureserverless.md
Updated the date on the font matter from 2024 to 2025
=> Updates to the font matter

src/content/docs/logs/ui-data/lookup-tables-ui.mdx
We've raised the limit of lookup files per account to 250 from 20
https://new-relic.atlassian.net/browse/NR-358111
=> feat: We now support up to 250 Lookup files per account

src/content/docs/apis/insights-apis/query-insights-event-data-api.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-log-parsing-rules-tutorial.mdx, src/content/docs/apis/rest-api-v2/account-examples-v2/listing-users-your-account.mdx, src/content/docs/apis/rest-api-v2/basic-functions/api-overload-protection-handling-429-errors.mdx, src/content/docs/apis/rest-api-v2/basic-functions/calculate-average-metric-values-summarize.mdx, src/content/docs/apis/rest-api-v2/basic-functions/extract-metric-timeslice-data.mdx, src/content/docs/apis/rest-api-v2/basic-functions/pagination-api-output.mdx, src/content/docs/apis/rest-api-v2/basic-functions/set-custom-user-agent.mdx, src/content/docs/apis/rest-api-v2/basic-functions/specify-time-range-v2.mdx, src/content/docs/apis/rest-api-v2/browser-examples-v2/add-or-list-browser-apps-api-v2.mdx, src/content/docs/apis/rest-api-v2/browser-examples-v2/average-browser-end-user-page-throughput-example-v2.mdx, src/content/docs/apis/rest-api-v2/browser-examples-v2/average-browser-page-load-time-example-v2.mdx, src/content/docs/apis/rest-api-v2/browser-examples-v2/obtaining-browser-end-user-page-load-time-data-v2.mdx, src/content/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2.mdx, src/content/docs/apis/rest-api-v2/get-started/list-application-id-host-id-instance-id.mdx, src/content/docs/apis/rest-api-v2/labels-examples-v2/create-labels-apps-v2.mdx, src/content/docs/apis/rest-api-v2/migrate-to-nrql.mdx, src/content/docs/apis/rest-api-v2/mobile-examples-v2/mobile-crash-count-crash-rate-example-v2.mdx, src/content/docs/apis/rest-api-v2/troubleshooting/301-response-rest-api-calls.mdx, src/content/docs/apis/rest-api-v2/troubleshooting/http-200-status-api-explorer.mdx, src/content/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api.mdx, src/content/docs/apis/synthetics-rest-api/secure-credentials-examples/use-synthetics-secure-credentials-apis.mdx, src/content/docs/synthetics/new-relic-synthetics/synthetics-api/synthetics-rest-api-version-1.mdx
=> chore: syntax highlighting for code

src/content/whats-new/2025/01/whats-new-01-23-msconnector-eol.md
Created a what's new for Microsoft Office 365 EOL
=> What's New for Microsoft Office 365 Connector

src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
=> updated GCP onboarding doc for the service account issue

src/content/whats-new/2025/01/whats-new-01-22-React18-upgrade.md
Added a summary to the whatsnew section
=> Updates to the whatsnew section summary

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-36-0.mdx
This documents the 3.36.0 release of the Go Agent.
=> Go Agent release 3.36.0

src/content/docs/infrastructure/host-integrations/host-integrations-list/temporal-cloud-integration.mdx
=> chore: Temporal update

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/infrastructure-monitoring-best-practices-guide.mdx
=> (chore): fixed broken link

src/content/docs/opentelemetry/best-practices/opentelemetry-otlp.mdx
=> Update opentelemetry-otlp.mdx to indicate support for OTLP 1.4.0

package.json, scripts/actions/deserialize-html.mjs, scripts/actions/serialize-mdx.mjs, yarn.lock
=> Correct Serialization and deserialization to interpret mdx tables accuratly

src/install/kubernetes/prepare-install.mdx
Updated a missing info in the tip, reported by a customer to one of our support engineer.
=> chore: Updated a missing info in the tip

src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-08-31.mdx, src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-10-31.mdx
This PR adds new sections to the latest fluent bit doc and adds a doc corresponding to an older version of fluent bit
=> doc: added fluentbit doc for 3.1.2

src/install/ibm-mq/whatsNext.mdx
Added a missing section highlighted in https://newrelic.slack.com/archives/C0DSGL3FZ/p1738166889292739
=> (chore): Added a missing section

src/content/docs/release-notes/docs-release-notes/docs-1-31-2025.mdx
=> Doc release notes 01-31-2025

src/content/docs/alerts/get-notified/new-relic-webhook-for-microsoft-teams-workflow.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
=> fix-send-content-to-machine-translation

src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.16.mdx
Update docs for Lambda Extension [v2.3.16](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.16) release.
=> extension release v2.3.16

src/content/docs/ai-monitoring/intro-to-ai-monitoring.mdx
Adding DeepSeek as supported model
=> Add DeepSeek as supported model intro-to-ai-monitoring.mdx

src/content/docs/logs/forward-logs/azure-log-forwarding.mdx
=> chore: capitalize WHERE clause

package.json, yarn.lock
=> Update gatsby theme newrelic version

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-glue-monitoring-integration.mdx
=> Adding info about glue jobs limitation on python shell jobs

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100600.mdx
* Adds release notes for Python Agent v10.6.0
=> docs: Release Notes for Python Agent v10.6.0

src/content/whats-new/2025/02/what-new-10-02-sessions-replay.md
- https://new-relic.atlassian.net/browse/NR-367851
- Added a new whats new post for session replay
=> Whats New Post for Session Replay

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/additional-information.mdx, src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/manage-session-replay-modify-capabilities.mdx, src/content/whats-new/2025/02/what-new-10-02-sessions-replay.md
- Minor changes made to browser section.
- Work in progress, do not merge until asked to
=> Minor changes to browser

src/content/docs/serverless-function-monitoring/azure-function-monitoring/install-serverless-azure-monitoring.mdx
=> chore: cleanup code examples

src/content/docs/accounts/accounts/billing/view-or-change-account-tax-information.mdx
Updated the sate list from where NR collects Sales tax, as per the request in https://newrelic.slack.com/archives/C0DSGL3FZ/p1738164601932309
=> (Update): Updated the state list from where NR collects Sales tax.

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
=> correct indentation

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1601.mdx
Add infra-agent 1.60.1 release doc
=> chore: infra-agent 1.60.1 release doc

src/content/docs/apm/agents/java-agent/additional-installation/install-java-agent-java-2-security.mdx
=> chore: format the code blocks

src/content/docs/tutorial-troubleshoot-infra-hosts/create-metrics-dashboards.mdx
=> fix: SQL -> sql, language identifiers are case sensitive

src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-08-31.mdx, src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-10-31.mdx
=> docs: updated docs security

gatsby-config.js
=> remove french from dropdown

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-764.mdx
* What problems does this PR solve? - release notes for android agent v7.6.4
=> [NR-371135] Android agent release notes

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates .NET agent compatibility docs with latest supported framework versions.
=> docs(dotnet): Update supported framework versions for .NET agent

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/new-relic-ios-6091.mdx
=> iOS release notes forApp version 6.9.1 

src/content/docs/browser/browser-monitoring/browser-pro-features/upload-source-maps-un-minify-js-errors.mdx
=> fix: typo- missing `\`

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-custom-user-id.mdx
Adds an example of how to unset the user id for react native applications.
=> Add react native unset user id example

src/content/docs/browser/browser-monitoring/browser-pro-features/browser-logs/get-started.mdx, src/content/docs/browser/browser-monitoring/browser-pro-features/browser-logs/overview.mdx
Additional changes to the browser logs changes
=> Nr 356329 browser logs

src/content/docs/apis/nerdgraph/examples/manage-live-chart-urls-via-api.mdx, src/content/docs/apis/nerdgraph/examples/manage-live-dashboard-urls-via-api.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx, src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/prerequisites-to-share-dashboards-charts.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-internally.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx, src/nav/dashboards.yml, src/nav/telemetry-data-platform.yml
Created this new PR having all the Public Dashboard related updates in https://github.com/newrelic/docs-website/pull/19748
Due to merge conflicts in the above PR, creating this fresh PR.
other PRs created interim are here. PLEASE IGNOUR THESE: 
https://github.com/newrelic/docs-website/pull/20050 
https://github.com/newrelic/docs-website/pull/20053 
https://github.com/newrelic/docs-website/pull/20054
=> feat(PUBLIC-DASHBOARD-FINAL-PR) Feb release item

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.283.0.mdx
This PR fixes a dead link in browser agent release notes 1.283.0
=> Fix bad link in release 1.283.0

src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx, src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-10-31.mdx
This pr includes newrelic-logging chart version mapped to fluent Bit releases
=> docs: updated helm chart version mapped to fluent bit release

src/i18n/translations/en/translation.json
=> docs: changed the content of landing tile

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration.mdx
=> docs: correct grammar of Kubernetes out of the box experience

src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-08-31.mdx, src/content/docs/release-notes/fluentbit-release-notes/fluentbit-24-10-31.mdx
This document updated Fluent bit release notes features.
=> docs: updated FB features for 3.1.2 and 3.1.9

src/content/docs/release-notes/fluentbit-release-notes/fluentbit-25-02-20.mdx, src/content/docs/release-notes/logs-release-notes/logs-25-02-20.mdx
* What problems does this PR solve? - updates release notes for the new fluent bit version release
=> docs: release notes for fluent bit upgrade to 3.2.2

src/content/docs/nrql/nrql-examples/browserspa-nrql-query-examples.mdx
=> chore: capitalize SINCE & add NRQL linebreaks

src/install/config/postgresql.yaml, src/install/postgresql/create-user.mdx, src/install/postgresql/default-install-linux.mdx, src/install/postgresql/default-requirements.mdx, src/install/postgresql/find-data.mdx, src/install/postgresql/intro.mdx, src/install/postgresql/linux/install-apt-query-monitoring.mdx, src/install/postgresql/linux/install-linux.mdx, src/install/postgresql/linux/install-tarball.mdx, src/install/postgresql/linux/install-yum-query-monitoring.mdx, src/install/postgresql/query-monitoring.mdx, src/install/postgresql/requirements-amazonECS.mdx, src/install/postgresql/requirements-k8s.mdx, src/install/postgresql/whatsNext.mdx, src/install/postgresql/windows/install-windows-query-monitoring.mdx, src/install/postgresql/windows/install-windows.mdx
**Ticket:** https://new-relic.atlassian.net/browse/NR-364951
**Description:** Updated the postgresql documentation by adding manual steps for query monitoring
=> feat: Database Monitoring PostgreSQL documentation [Feb Release]

src/content/docs/browser/new-relic-browser/browser-apis/log.mdx, src/content/docs/browser/new-relic-browser/browser-apis/setcustomattribute.mdx, src/content/docs/browser/new-relic-browser/browser-apis/wraplogger.mdx
=> docs: Add custom attributes to Browser Agent logging feature

src/nav/service-architecture-intelligence.yml
=> added yml entry

src/content/docs/release-notes/fluentbit-release-notes/fluentbit-25-02-20.mdx, src/content/docs/release-notes/fluentbit-release-notes/fluentbit-27-02-20.mdx, src/content/docs/release-notes/logs-release-notes/logs-25-02-27.mdx
This PR release new Fluent bit version
=> docs: Updated FB  and logs docs

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1620.mdx, src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr25-01.mdx, src/content/docs/security/security-privacy/information-security/security-bulletins.mdx, src/nav/new-relic-security.yml
=> doc: added new security bulletin

src/content/docs/alerts/get-notified/incident-workflows.mdx
=> fix: broken anchor link & functions in backticks

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx
* What problems does this PR solve? - add data endpoint settings to match with iOS
=> [NR-373715] add data endpoint settings

src/content/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-manage-groups.mdx, src/content/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys.mdx, src/content/docs/apis/nerdgraph/get-started/nerdgraph-explorer.mdx
=> chore: api fields in backticks

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
It is stated that it is an x86_64 architecture.
=> Add CPU to Baremetal Linux Service

src/content/docs/network-performance-monitoring/get-started/network-monitoring-best-practices.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/meraki-api-polling.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx, src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
=> chore: consistant indentation

src/install/postgresql/default-install-linux.mdx, src/install/postgresql/linux/install-yum-query-monitoring.mdx, src/install/postgresql/whatsNext.mdx, src/install/postgresql/windows/install-windows.mdx
**Description:** Updated small changes in Postgres documentation
=> chore: Updated small changes in Postgres doc

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
=> Added synthetic ip allow list

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Updates the library compatibility documentation for the latest versions supported by the .NET agent.
=> docs(dotnet): Update latest supported library versions.

src/content/docs/service-architecture-intelligence/maps/advanced-maps.mdx
[DRAFT] - Added the instruction how the user can onboard to the new map experience directly from the Service Maps page.
=> feat(Advanced maps): Updated the onboarding instructions

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/nrql-predictions.mdx
Updated callouts with the definition of gamma hyperparameter.
=> chore: (NRQL Prediction): Updated the callout with the definition of gamma hyperparameter

src/content/docs/streaming-video-&-ads/installation/install-the-streaming-video-&-ads-agent.mdx
Added a space to the document as the previous changes were not reflecting
=> Updates to the media streaming document.

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
- https://new-relic.atlassian.net/browse/NR-359791
- Updated the Supported hour section in https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/#support-hours to Business hours are generally defined as 8:00 AM to 6:00 PM in the customer country, excluding holidays and weekends.
=> Updated the supported hour section

src/content/docs/service-architecture-intelligence/maps/advanced-maps.mdx
Gateway nodes nomenclature update.
=> chore(map): Gateway nodes nomenclature update in document

src/content/whats-new/2025/03/whats-new-03-07-change-to-dimensional.md
=> Whats new post

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100700.mdx
This PR adds release notes for Python agent v10.7.0.
=> Add release notes for Python agent v10.7.0.

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1620.mdx
Infra Agent 1.62.0 Release Notes
=> Infra Agent 1.62.0 Release Notes

src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.17.mdx
New Release Notes for [Lambda Extension `v2.3.17`](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.17)
=> Lambda Extension v2.3.17 Release Notes

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-754.mdx
@mbruin-NR Can you please review? 
New Relic iOS agent 7.5.4 release notes.
=> New Relic iOS agent 7.5.4

src/content/docs/mobile-monitoring/new-relic-mobile-ios/configuration/upload-dsyms-bitcode-apps.mdx
Added limitations as per NR-364345.
=> added limtations

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/env-variables-lambda.mdx
Update environment variable option for [ESM mode as per Extension PR](https://github.com/newrelic/newrelic-lambda-layers/pull/317)
=> ESM loader environment variable for Nodejs Lambda runtime

src/content/docs/apis/nerdgraph/examples/nerdgraph-rag.mdx
=> fix: correct language identifiers

src/content/docs/logs/forward-logs/fluentd-plugin-log-forwarding.mdx
=> Corrected typo in CP932.

src/content/docs/apis/nerdgraph/examples/nerdgraph-scorecards-tutorial.mdx
The Scorecard and Rule entity were migrated to `ORGANIZATION` scope after the docs were created. Fixed the docs because it doesn't support ACCOUNT scope anymore.
=> fix(NerdGraph/Scorecards): The scope must be organization

src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- Add Log Labels stanza to agent config
- Add Agent Forwarded Log Labels information to docs
=> Update Java Agent Config Docs

src/content/whats-new/2025/03/whats-new-03-13-microsoft-teams-integration.md
This is a What's New Post for Microsoft Teams integration.
=> (whatsNew): What new for Microsoft Teams Integrations

package.json, yarn.lock
=> chore(deps): update gatsby-theme-newrelic 9.11.0 to 9.11.1

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp.mdx
Add NR Agentic integrations to FedRAMP out-of-scope
=> Add NR Agentic integrations

src/content/docs/query-your-data/explore-query-data/dashboards/add-custom-visualizations-your-dashboards.mdx
Update custom visualization page link
=> chore:(broken-link): Update custom visualization page link

src/content/docs/release-notes/nrdot-release-notes/nrdot-2025-03-05.mdx
Add release notes for NRDOT 1.0.0\n\n Note: PR is auto-generated. If anything looks off, please contact the maintainers of nrdot-collector-releases.
=> Add release notes for NRDOT 1.0.0

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-428.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.24.mdx
=> updated release notes for SJM and node browser runtime

src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
Change request: https://newrelic.slack.com/archives/C0DSGL3FZ/p1742312457950979
=> doc-update: (Public Dashboard): Update customer info who can avail the feature

src/content/docs/release-notes/nrdot-release-notes/nrdot-2025-03-18.mdx
Add release notes for NRDOT 1.0.1\n\n Note: PR is auto-generated. If anything looks off, please contact the maintainers of nrdot-collector-releases.
=> Add release notes for NRDOT 1.0.1

src/content/docs/alerts/admin/rules-limits-alerts.mdx
The alerts team recently raised this limit from 500 to 1000 in order to alleviate issues for a customer. We are updating the docs to reflect the new limit.
=> docs: Update rules-limits-alerts.mdx

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-7-0-21.mdx
New Relic PHP Agent 11.7.0.21 Release.
=> chore(php): 11.7.0.21 release notes

src/i18n/translations/fr/translation.json
=> Update translation.json for FR docs

src/content/docs/opentelemetry/best-practices/opentelemetry-otlp-long-attributes-update.mdx
See [here](https://newrelic.slack.com/archives/C0DSGL3FZ/p1741898170913579) for more context.
=> Add OTLP long attributes update explanation

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-ec2-image-builder-integration.mdx, src/nav/infrastructure.yml
This is documentation for a new integration with AWS using their EC2 image builder components. The tool is already available, so this is supporting documentation to make adoption easier.
https://aws.amazon.com/marketplace/pp/prodview-7l3xgom3n4v7q?sr=0-7&ref_=beagle&applicationId=AWS-Marketplace-Console
=> feat: New page for aws ec2 image builder component

src/nav/infrastructure.yml
Simple URL fix, nav link is pointing to the wrong page.
=> bug: Fix URL bug in nav

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6091.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6092.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6093.mdx
=> iOS App Release notes for 6.9.1, 6.9.2, 6.9.3

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-38-0.mdx
=> Go Agent Release v3.38

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/nrql-predictions.mdx
This PR reworks some of the content on the NRQL Predictions and NRQL Syntax -> PREDICT pages.
=> rework content of the NRQL predictions and NRQL Syntax PREDICT pages

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx, src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx, src/content/docs/infrastructure/host-integrations/get-started/introduction-host-integrations.mdx, src/content/docs/release-notes/docs-release-notes/docs-3-15-2024.mdx, src/content/docs/release-notes/docs-release-notes/docs-4-26-2024.mdx, src/install/config/cassandra.yaml, src/install/config/haproxy.yaml, src/install/config/rabbitmq.yaml
Added redirects
JIRA: https://new-relic.atlassian.net/browse/NR-373423
=> chore: Fixing broken links

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
This updates the url to the data retention ui on [the manage data retention page](https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention/) to the new url.
=> Update data retention UI link

src/content/docs/browser/new-relic-browser/browser-pro-features/geography-webpage-metrics-location.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application.mdx, src/content/docs/vulnerability-management/integrations/fossa.mdx
=> fix: serizlisation fix

src/content/docs/change-tracking/change-tracking-view-analyze.mdx
=> chore: syntax highlighting/formatting for code samples

src/content/docs/streaming-video-&-ads/get-started-with-streaming-video-&-ads.mdx, src/content/docs/streaming-video-&-ads/update-the-media-agent.mdx, src/content/docs/streaming-video-&-ads/view-data-in-newrelic/streaming-video-&-ads-all-platform-view/overview.mdx, src/content/docs/streaming-video-&-ads/view-data-in-newrelic/streaming-video-&-ads-single-application-view/overview.mdx, src/install/android/intro.mdx, src/install/browser-media/browser-path/newapplication.mdx, src/install/browser-media/intro.mdx, src/install/media-ios/ios-path/appInfo_AC.mdx
- [NR-382663](https://new-relic.atlassian.net/browse/NR-382663)
- Updated the broken links.
- Proof read the document for spell check
[NR-382663]: https://new-relic.atlassian.net/browse/NR-382663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Streaming video broken links

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1630.mdx
=> docs: add release notes for infra-agent 1.63.0

src/content/docs/serverless-function-monitoring/azure-function-monitoring/install-serverless-azure-monitoring.mdx
Corrects formatting of environment variables for Azure Functions and adds a section to distinguish between environment variables required for "isolated" and "in process" mode functions.
=> docs(dotnet): Update azure function environment variable configuration instructions

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100800.mdx
* Add release notes for Python agent v10.8.0.
* Add additional config options for Python agent.
=> docs: Add release notes for Python agent v10.8.0

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-700.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-710.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-720.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-721.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-730.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-731.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-740.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-741.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-750.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-751.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-760.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-761.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-762.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-763.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-764.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-765.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-157.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-706.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-707.mdx, src/content/docs/release-notes/mobile-release-notes/flutter-release-notes/flutter-agent-1110.mdx, src/content/docs/release-notes/mobile-release-notes/net-maui-release-notes/net-maui-agent-119.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-153.mdx, src/content/docs/release-notes/mobile-release-notes/unity-release-notes/unity-agent-146.mdx
=> docs:android agent update for hybrid agents

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-100801.mdx
This PR has the release notes for v10.8.1 of the Python Agent
=> feat(APM): Python Agent v10.8.1 Docs

src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.25.mdx
=> updated release notes for node browser runtime

src/content/docs/logs/log-collectors/log-collector-management.mdx
=> feat(fluentbit): changes for AC/FC

src/content/docs/infrastructure/host-integrations/host-integrations-list/docker-container-monitoring-integration.mdx, src/nav/infrastructure.yml
Adds detailed info about the `nri-docker` integration
https://github.com/newrelic/nri-docker
N/A
=> feat(nri-docker): add docker integration docs page

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide.mdx
=> chore: nrql formatting

src/content/docs/message-queues-streaming/introduction.mdx
Just a silly typo I spotted while reading the docs.
=> fix: typo on Introduction to Queues and Streams monitoring

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This PR documents new configuration options in 12.17.0 of the Node.js agent.
=> chore: Added configuration for `distributed_tracing.sampler` options

src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.113.mdx
=> added release noted for synthetics-node-api-runtime release-1.2.113

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1631.mdx
=> docs: add release notes for infra-agent 1.63.1

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Update .NET agent compatibility docs to reflect latest supported library versions.
=> docs(dotnet): Update .NET agent compatibility docs to reflect latest supported library versions

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-438.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.111.mdx
=> release notes for sjm and api-runtime latest releases

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
See this .NET agent issue for details that we don't yet support 8.16+:
- https://github.com/newrelic/newrelic-dotnet-agent/issues/2938
=> update: Elasticseach 8.16+ are not supported yet

src/content/whats-new/2025/04/whats-new-04-07-promql-translator.md
What's new post for promql translator added to the new query experience.
=> feat(whats-new): add promql translator post

src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
=> chore: capiltalize nrql clauses

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
As per this slack request, updated the IP range for the Synthetics.
=> (chore): updated the IP range

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx
Update example to match changes in the page.
=> update text to check in best practices example

src/content/eol/2025/04/change-in-data-exploration.md
As part of #help-documentation request, created an EOL notification and the change in data exploration.
=> Change in data exploration

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes /new-relic-android-5289.mdx
=> NR Mobile Android App Release - 5.28.9

src/content/docs/new-relic-control/agent-control/reinstrumentation.mdx
=> bug(agent-control): fixed typos

src/content/whats-new/2025/04/whats-new-04-08-new-relic-control.md
New Relic Control post to be published April 8th. No PMM review required
=> feat(whats-new): Add nr control post

src/content/whats-new/2025/03/whats-new-03-07-change-to-dimensional.md
As per [this slack-request](https://newrelic.slack.com/archives/C0DSGL3FZ/p1743789364636259), added a new table in the What's New.
=> (chore): Added new table in What's New

src/content/docs/accounts/accounts/account-maintenance/account-email-settings.mdx
Update special characters to include all special characters allowed
=> Update email requirements

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
I am creating this PR as we have updated the dates as per the received request.
=> (chore): Update in dates

src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
include plugin.type information to identify and search for log data in an account
=> Update use-tcp-endpoint-forward-logs-new-relic.mdx with plugin.type information

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/licenses/open-source/contribute.mdx, src/content/docs/new-relic-control/fleet-control/setup.mdx, src/content/docs/new-relic-control/pipeline-control/set-up-and-deploy-pipeline-control.mdx
fix errors triggered in send-content-machine-translation workflow
=> fix:serialisation error

src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings.mdx
* What problems does this PR solve? - Documentation correction
=> [NR-401875] [NR-401879] Correct all the codes that are wrong for android feature flags

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
=> fix: indentation errors

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/response-stream.mdx
=> (chore): Fix the link issue

src/content/whats-new/2025/04/whats-new-04-10-login-logout-audit.md.md
this can go asap and does not need reviewed
=> what's new: login and logout audit events

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This documents configuration that has existed for years but was missing from the Node.js configuration docs.
=> chore: Document batching and compression settings of infinite tracing

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6094.mdx
=> iOS App 6.9.4 Release Notes

src/content/docs/infrastructure/amazon-integrations/manage-aws-data/aws-integrations-metrics.mdx
* What problems does this PR solve? Fix typo in aws-integrations-metrics.mdx
links to related docs, screenshots, etc. na
* If your issue relates to an existing GitHub issue, please link to it. na
=> fix: Remove typo in aws-integrations-metrics.mdx

src/i18n/content/fr/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph.mdx, src/i18n/content/fr/docs/apis/synthetics-rest-api/monitor-examples/payload-attributes-synthetics-rest-api.mdx, src/i18n/content/fr/docs/apm/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications.mdx, src/i18n/content/fr/docs/apm/agents/java-agent/related-integrations/micrometer/micrometer-metrics-registry.mdx, src/i18n/content/fr/docs/apm/agents/net-agent/troubleshooting/browser-injection-health-check-conflict.mdx, src/i18n/content/fr/docs/apm/agents/php-agent/other-integrations/magento-business-insights.mdx, src/i18n/content/fr/docs/apm/agents/php-agent/php-agent-api/newrelic_disable_autorum.mdx, src/i18n/content/fr/docs/apm/agents/python-agent/hosting-services/python-azure-containerapps-appservice.mdx, src/i18n/content/fr/docs/apm/agents/python-agent/hosting-services/python-azure-touchless-integration.mdx, src/i18n/content/fr/docs/browser/browser-integrations/nuxt-js-integration.mdx, src/i18n/content/fr/docs/browser/browser-monitoring/browser-pro-features/session-replay.mdx, src/i18n/content/fr/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx, src/i18n/content/fr/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx, src/i18n/content/fr/docs/browser/new-relic-browser/installation/update-browser-agent.mdx, src/i18n/content/fr/docs/mobile-monitoring/new-relic-mobile-ios/watchOS/instrument-watchos.mdx
=> Update to FR docs

src/install/microsoft-sql/linux/install-linux.mdx, src/install/microsoft-sql/whatsNext.mdx
This PR address [this request](https://newrelic.slack.com/archives/C0DSGL3FZ/p1743674133808289) received in our help channel to fix the indentation issue in the Microsoft SQL integration doc.
=> (chore): fix the indentation issue

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-766.mdx
* What problems does this PR solve? - Android v7.6.6 release notes
=> [NR-402504] Android v7.6.6 release notes

src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx, src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8200.mdx
(Ready to be merged!)
PR with Release Notes, Compatibility Doc updates, and Config updates for Java Agent v8.20.0.
=> Javaagent 8.20.0 updates

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-330.mdx
These are the release notes for the Diagnostics CLI 3.3.0
=> feat: Diagnostics CLI 3.3.0 release notes

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
=> docs: Update latest verified compatible versions of .NET libraries for the dotnet agent

src/content/docs/service-architecture-intelligence/scorecards/managing-scorecards.mdx, src/content/docs/service-architecture-intelligence/scorecards/templates.mdx, src/nav/service-architecture-intelligence.yml
Added a topic describing the six templates that users could use to build their scorecards
=> feat(scorecards): Added the scorecards templates topic

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Minor update to .NET agent browser monitoring documentation to reflect the current state of the .NET agent
=> docs(dotnet): Update browser monitoring documentation to reflect current functionality.

src/content/docs/release-notes/docs-release-notes/docs-4-21-2025.mdx
=> Release note - 21st April

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-8-0-22.mdx
Release notes for upcoming PHP agent release.   
Please merge as soon as possible.
=> chore(PHP agent): Adds 11.8.0.22 release notes

src/i18n/nav/es.json, src/i18n/nav/jp.json, src/i18n/nav/pt.json
=> chore: update nav file

src/content/docs/release-notes/pipeline-control-gateway-release-notes/index.mdx, src/content/docs/release-notes/pipeline-control-gateway-release-notes/pipeline-control-gateway-25-04-02.mdx
Fixed Navigation in PCG Release notes
=> fix: navigation of pcg release notes

src/content/docs/agentic-ai/agentic-integration/introduction-agentic-ai.mdx, src/nav/agentic-ai.yml
Decommissioning of AmazonQ integration doc.
=> Chore: AmazonQ  decommissioning

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
QLang would like the NRQL reference entry on `PREDICT` to include a description of the default behavior
=> Adding PREDICT defaults to NRQL reference

src/content/docs/infrastructure/infrastructure-agent/linux-installation/instrument-container.mdx
=> NR-403516:  remove Control Group v1 e2eTest support nri-docker

src/content/docs/alerts/alerts-ai-overview-page.mdx, src/content/docs/alerts/get-notified/incident-workflows.mdx, src/nav/alerts.yml
Adding new investigate state in the Alert doc. This ticket is in response of NR-405654 Jira
=> {chore}: Adding new investigate state in the doc

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-755.mdx
=> Changed the release notes for iOS agent 7.5.5

src/content/whats-new/2025/04/whats-new-04-23-otlp.md
What's new post to announce about the upcoming change to the OTLP ingest validation logic. 
No PMM review required.
=> Whats new 04 23 otlp

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-101000.mdx
* Release notes for Python Agent version 10.10.0.
=> Add python agent v10.10.0 release notes

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Jira Issue: NR-177571
This PR adds array function to our NRQL Reference public docs. Documentation for these functions exists today in the [Use Arrays For Organization](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql/#array-functions) page exclusively.
=> NR-177571: Add array functions to NRQL Reference

src/content/docs/release-notes/docs-release-notes/docs-4-28-2025.mdx
=> RN for 18/04-24/04

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native.mdx
Linking to Azure Native New Relic Service details section of doc.
=> correcting anchor link

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
confirmed by eng here: https://newrelic.slack.com/archives/C7HNR7WNR/p1745948057789459?thread_ts=1745943287.928029&cid=C7HNR7WNR
=> update: `attributes` config applies to Span events

scripts/utils/updateCookieConsentMessage.js
=> fix: change link color to white

scripts/utils/updateCookieConsentMessage.js
=> chore: update css for cookie consent message

scripts/utils/updateCookieConsentMessage.js
=> chore: update text color white

src/content/docs/apis/nerdgraph/examples/manage-live-chart-urls-via-api.mdx, src/content/docs/apis/nerdgraph/examples/manage-live-dashboard-urls-via-api.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx, src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
=> chore: formatting code blocks

scripts/utils/updateCookieConsentMessage.js
=> chore: remove privacy link

src/content/docs/new-relic-control/agent-control/troubleshooting.mdx
This PR documents how to execute nrdiag to troubleshoot agent-control running on k8s
=> chore: add nrdiag execution to agent-control troubleshooting

package.json, yarn.lock
=> chore: Update gatsby-theme-newrelic

src/content/docs/codestream/observability/repo-association.mdx
This PR fixes the beta repo URL
=> (chore): fix the repo URL

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx, src/content/eol/2025/02/eol-01-31-25-synthetics-ip.md
This updates the EOLs comms for new Synthetic IP ranges
=> chore: updated the date for EOLs

src/i18n/content/fr/docs/apm/agents/manage-apm-agents/agent-data/real-time-streaming.mdx, src/i18n/content/fr/docs/apm/agents/manage-apm-agents/agent-data/triage-run-diagnostics.mdx, src/i18n/content/fr/docs/apm/apm-ui-pages/monitoring/response-time-chart-types-apm-browser.mdx, src/i18n/content/fr/docs/apm/transactions/intro-transactions/transactions-new-relic-apm.mdx, src/i18n/content/fr/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details.mdx, src/i18n/content/fr/docs/infrastructure/host-integrations/host-integrations-list/couchbase-monitoring-integration.mdx, src/i18n/content/fr/docs/infrastructure/host-integrations/host-integrations-list/powerdns-monitoring-integration.mdx, src/i18n/content/fr/docs/nrql/nrql-syntax-clauses-functions.mdx, src/i18n/content/fr/docs/nrql/nrql-tutorials/nrql-tutorial-advanced-dashboarding.mdx, src/i18n/content/fr/docs/opentelemetry/best-practices/opentelemetry-otlp.mdx
=> Update to French docs

src/content/docs/opentelemetry/best-practices/opentelemetry-otlp-attributes-processing-update.mdx
=> chore: formatting improvements

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp.mdx
Add NR Control + update hyperlinks for all other not-in-scope services
=> Add NR Control + update hyperlinks

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-39-0.mdx
=> Go Agent Release v3.39.0

src/content/docs/mobile-monitoring/mobile-monitoring-ui/application-not-responding.mdx
This PR fixes the floating image issue
=> fix: Fix the image float issue

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-9-0-23.mdx
Releasing the new agent version today (May 13)
=> PHP Release 11.9

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-101200.mdx
* Add release notes for Python Agent v10.12.0
=> feat: Add Python Agent v10.12.0 Release Notes

src/content/docs/browser/browser-monitoring/browser-pro-features/browser-logs/get-started.mdx
Implemented the legal feedback and updated sampling rate description.
=> chore: implemented the legal feedback

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cosmos-db-document-db-monitoring-integration.mdx
updated the doc as we don't support Microsoft.DocumentDB/mongoClusters
=> updated the doc as we don't support Microsoft.DocumentDB/mongoClusters

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx, src/content/docs/nrql/using-nrql/subquery-joins.mdx
=> chore: code in backticks/nrql formatting

src/content/docs/new-relic-control/agent-control/troubleshooting.mdx, src/content/docs/new-relic-control/pipeline-control/modify-agent-configuration.mdx, src/content/docs/new-relic-control/pipeline-control/set-up-and-deploy-pipeline-control.mdx
=> chore: formatting terminal output

package.json, yarn.lock
=> fix: Update gatsby-theme-newrelic to 9.12.0

src/content/docs/change-tracking/change-tracking-events.mdx
This PR address the feedback from the PMs to the change tracking event documentation.
=> chor: New PM feedbacks in change tracking event doc

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1640.mdx
adding docs to add the release notes of infra-agent 1.64.0
=> docs: add release notes for infra-agent 1.64.0

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-443.mdx
=> Added release notes for SJM 443

package.json, yarn.lock
=> chore: update gatsby theme newrelic

src/content/docs/change-tracking/change-tracking-events.mdx
Fixing code example and adding feature limitation to "Important" section.
=> docs: NR-416900 Update change-tracking-events.mdx

src/content/docs/new-relic-control/pipeline-control/cloud-rules-api.mdx
The docs use the term "Select" right after two examples where the keyword "Delete" is used
=> chore: update cloud-rules-api.mdx

src/content/docs/alerts/create-alert/create-alert-condition/alert-conditions.mdx, src/content/docs/alerts/create-alert/set-thresholds/predictive-alerts.mdx, src/content/docs/nrql/nrql-syntax-clauses-functions.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/nrql-predictions.mdx, src/nav/alerts.yml
- Updated the topic title from Predictive capability to Predictive alerts.
- Fixed typeO
=> chore(Alerts): Updated the Predict alerts topic title

src/content/docs/change-tracking/change-tracking-events.mdx
We had an incorrect query example we needed to update.
=> docs: Update text for change-tracking-events.mdx

src/content/docs/alerts/admin/rules-limits-alerts.mdx
As requested on two previous PRs, this verbiage needs to remain in the alerts documentation please. :)
https://github.com/newrelic/docs-website/pull/9707
https://github.com/newrelic/docs-website/pull/18067
=> Update rules-limits-alerts to include info about interruptions.mdx

netlify.toml, netlify/edge-functions/hello.js, netlify/edge-functions/inject-country.js, package.json, yarn.lock
=> chore: Inject country as a window variable using Netlify edge functions

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-6097.mdx
=> iOS Release Notes

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-756.mdx
New Relic iOS agent 7.5.6 release notes
=> New Relic iOS agent 7.5.6 release notes

src/content/docs/agentic-ai/agentic-integration/introduction-agentic-ai.mdx
=> chore(Agentic integration): Fixed preview callout.

src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.51.0.mdx
=> release notes for ping runtime 1.51.0

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/add-mutual-tls-prometheus-endpoints.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/add-rename-or-copy-prometheus-attributes.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/ignore-or-include-prometheus-metrics.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/remote-write-errors-error-messages.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure/prometheus-high-availability-ha.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure/remote-write-drop-data.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/compare-rw-data-sent-billed-bytes.mdx, src/content/docs/infrastructure/prometheus-integrations/troubleshooting/no-data-appears-prometheus-integration.mdx
=> chore: syntax hightlighting/formatting codeblocks

src/content/docs/logs/logs-context/annotate-logs-logs-context-using-apm-agent-apis.mdx
=> fix: update python link +code in backticks

src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.51.0.mdx
* Fixing vul and suggestion to use compatible synthetics kevin version to avoid DNS issues
=> release notes 1.51.0

netlify.toml, netlify/edge-functions/hello.js, netlify/edge-functions/inject-country.js, package.json, yarn.lock
=> chore: injected user country as a window variable

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-444.mdx
=> Update SJM to release 444

src/content/docs/agentic-ai/knowledge-integration/overview.mdx
Remove specific words following legal guidance, update connector instructions
=> Update NRAI knowledge overview.mdx

src/content/whats-new/2025/03/whats-new-03-13-microsoft-teams-integration.md
This is a What's New for New Relic Native integration for Microsoft Teams.
This document provides information on how to install New Relic for Microsoft Teams app and send notifications directly to Teams channels.
We are waiting for confirmation from PM (Dharmendra) and Eng (Malleswara Rao) to merge the PR.
=> [DO NOT MERGE]: (whatsNew): What new for Microsoft Teams Integrations

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-101400.mdx
This PR has the release docs for v10.14.0 of the Python Agent
=> feat(APM): Python Agent v10.14.0 Docs

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-767.mdx
* What problems does this PR solve? - android v7.6.7 release notes
=> [NR-423794] android v7.6.7 release notes

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Update the .NET agent's compatibility and support document with latest verified compatible versions based on our testing.
=> .NET agent: update latest compatible libraries based on testing

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1651.mdx
=> docs: infrastructure-agent 1.65.1 release notes

src/content/docs/infrastructure/infrastructure-agent/new-relic-guided-install-overview.mdx
Ticket: https://new-relic.atlassian.net/browse/NR-423860
- Add docs support for specific infra agent CLI installs
=> fix: add docs support for specific infra agent CLI installs

.github/workflows/pr-comment-action.yml
=> chore: pr-comment-action

.github/workflows/gaurab-manual-preview-deploy.yml
=> chore: deploy preview URL on manual comment

.github/workflows/gaurab-manual-preview-deploy.yml
=> chore: move env to same level as with

.github/workflows/final-manual-deploy-comment.yml
=> chore: manual branch deploy on PR comment

src/content/docs/infrastructure/infrastructure-agent/new-relic-guided-install-overview.mdx
- Updated the version specific infra agent guided install docs
=> fix: updated the version specific infra agent install docs

src/content/docs/infrastructure/infrastructure-agent/linux-installation/package-manager-install.mdx
- fix linux infra-agent install guide
=> doc: Linux install guide

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
=> docs(dotnet): Update latest verified compatible versions of instrumented libraries

.github/workflows/auto-comment.yml, .github/workflows/final-manual-deploy-comment.yml, CONTRIBUTING.md
=> docs: change in readme

src/nav/kubernetes-pixie.yml
This PR addresses the request received in [this slack request.](https://newrelic.slack.com/archives/C0DSGL3FZ/p1751559480649469)
=> fixes-the-nav-k8s-issue

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
DON'T MERGE
Adding the precession argument to the UniqueCount function
=> feat(precision argument): Adding the precision argument to the UniqueCount function

src/content/docs/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-intro.mdx
=> Fixed K8s OTel link broken

src/content/docs/query-your-data/explore-query-data/dashboards/nested-variables.mdx
Added a callout mentioning to whom it is available
=> chore(nested variables): Added a callout mentioning to whom it is available

src/content/docs/apm/agents/php-agent/frameworks-libraries/analyze-phpunit-test-data-new-relic.mdx, src/content/docs/apm/agents/php-agent/frameworks-libraries/guzzle.mdx
Update PHP Agent's compatibility pages after this announcement: https://support.newrelic.com/s/hubtopic/aAX8W000000L5oM/new-relic-endoflife-eol-during-q4-fy24-and-q1-fy25.
=> chore(apm/php agent): update compatibility

src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-load-balancing-monitoring-integration.mdx, src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/gcp-integration-metrics.mdx
feat: Update GCP LB doc with newly added LBs
JIRA ticket: [NR-437033](https://new-relic.atlassian.net/browse/NR-437033)
[NR-437033]: https://new-relic.atlassian.net/browse/NR-437033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Update GCP LB doc with newly added LBs

src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx, src/content/docs/browser/new-relic-browser/browser-apis/recordCustomEvent.mdx, src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx, src/content/docs/browser/new-relic-browser/performance-quality/browser-monitoring-performance-impact.mdx
Reverts newrelic/docs-website#21161
=> Revert "Update public docs to describe browser agent's harvest interval behavior"

src/content/docs/query-your-data/explore-query-data/dashboards/dashboard-template-variables.mdx
This is the change needed to document this new feature called "Apply/Cancel" button configuration on Template Variables
Please check https://new-relic.atlassian.net/browse/NR-231677 for more details.
When enabled, it will allow customers to do this:
NOTE: this feature is already in production
=> feat: add new "apply button" config on template variables

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1640.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1650.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1651.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1653.mdx
infrastructure-agent 1.65.3 release notes
=> docs: infrastructure-agent 1.65.3 release notes

src/content/docs/infrastructure/infrastructure-agent/linux-installation/package-manager-install.mdx
Update package install steps for  Rockylinux & AlmaLinux to install infrastructure-agent
=> docs: update package manager installation

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-113.mdx
* What problems does this PR solve? - Android NDK agent v1.1.3 release notes
=> [NR-437477] android ndk agent v1.1.3 release notes

.github/workflows/netlify-build-forked-pr.yml
=> chore: Refine the branch name sanitization logic

.github/workflows/netlify-build-forked-pr.yml
=> chore: Commenting the preview link in the forked PR itself

src/content/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api.mdx
https://new-relic.atlassian.net/browse/NR-423696
* Adding new ignoreApdex API method
NOTE: in draft until release
=> docs[Publish on 16th July]: Add new API method ignoreApdex

src/content/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx
https://new-relic.atlassian.net/browse/NR-404946
* Adding an entry for Go agent MongoDB V2 support
NOTE: in draft until release
=> docs[Publish on 16th July]: Add support for MongoDB V2 driver

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-40-0.mdx
=> feat(Go Agent): Add release notes for Go Agent version 3.40.0

src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx
We no longer charge **on ingest** for `Deployment` events. 
It makes the docs reflect the new reality. 
=> feat(change tracking) Update manage-data-coming-new-relic.mdx

src/content/whats-new/2025/07/whats-new-7-22-predictive-analytics.md
What's new post for GA'ing NRQL predictions and Predictive alerting.
=> [Merge on 22nd July][feat]: What's new post for Predictive analytics features

src/install/mysql/whatsNext.mdx
This PR updates the mysql sample event.
=> chore: fixed the mysql event sample

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx
Based on our latest integration testing we are updating the latest verified compatible versions of libraries we instrument and support.
=> .NET agent: update latest verified compatible library versions

src/content/whats-new/2025/07/whats-new-07-24-db-query-performance-monitoring.md
The PR creates What's New for query performance monitoring feature
=> whats-new-db

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-757.mdx
=> Added release notes for iOS agent 7.5.7 Release EOD Jul 23 2025 PST

src/content/docs/new-relic-solutions/solve-common-issues/find-help-get-support.mdx
updated file a case procedure and create issue.
=> File a case procedure update

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-757.mdx
=> release date fix

src/install/config/microsoft-sql.yaml, src/install/microsoft-sql/whatsNext.mdx
This PR resolves the [slack requests](https://newrelic.slack.com/archives/C0DSGL3FZ/p1753724860547469) received in the #help-documentation channel.
=> chore: fix the broken links

src/content/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx
=> chore: Fixed typo in node migration guide

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-758.mdx
=> iOS agent 7.5.8 release note - release EOD 07/30/25

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements.mdx, src/data/whats-new-ids.json
=> Daily release/31 07 25 mrng

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-451.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.122.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.39.mdx, src/content/docs/release-notes/synthetics-release-notes/ping-runtime-release-notes/ping-runtime-1.53.0.mdx
SJM Release notes from #21374 PR.
=> feat: release-notes-for-sjm

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/introduction-azure-monitoring-integrations.mdx, src/content/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx
=> chore: fix-redirects

src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/configuration/setup-session-replay.mdx, src/content/docs/browser/browser-monitoring/browser-pro-features/session-replay/view-session-replays.mdx
This PR address the request received in [this thread](https://newrelic.slack.com/archives/C0DSGL3FZ/p1753818111766739) on the #help-documentation channel.
=> fix: Update the callout note

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-452.mdx
Revised the RN info for better context in consultation with the SME.
A extension of https://github.com/newrelic/docs-website/pull/21374
=> SJM release 452 notes update

src/content/docs/alerts/admin/rules-limits-alerts.mdx
This PR address the changes received in [this Slack request](https://newrelic.slack.com/archives/C0DSGL3FZ/p1753899842792549) on the #help-documentation channel.
=> chore: change in alert-limits

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1655.mdx
- Infrastructure-agent 1.65.5 release notes
=> docs: infrastructure-agent 1.65.5 release notes

src/content/docs/apis/nerdgraph/examples/nerdgraph-scorecards-tutorial.mdx, src/content/docs/service-architecture-intelligence/scorecards/managing-scorecards.mdx
=> docs: document scorecards joinAccounts

src/content/docs/release-notes/pipeline-control-gateway-release-notes/pipeline-control-gateway-25-08-05.mdx
=> Release notes for Pipeline Control Gateway v1.1.0

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-components.mdx
Attributions not currently supported. Removing references suggesting otherwise.
=> remove attributions references

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/add-on-billing.mdx
Updated the term "Vulnerability Management" to "Security RX"
=> Minor update

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-757.mdx, src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-758.mdx
fix: adds update related to agent crashing in v7.5.7 and fixed in v7.5.8
=> fix: adds update related to agent crashing in v7.5.7 and fixed in v7.5.8

src/content/docs/change-tracking/change-tracking-events.mdx
We don't mention or most popular type of change event: Deployments. This fixes that. 
=> Update change-tracking-events.mdx to include deployments

src/content/docs/apis/nerdgraph/examples/nerdgraph-scorecards-custom-tutorial.mdx
=> chore: format json and codeblocks, fix customRoleCreate param

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1655.mdx
=> docs: update infra-agent 1.65.5 release notes

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1655.mdx, src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1661.mdx
=> docs: add infra-agent 1.66.1 release notes

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx, src/content/docs/apm/agents/php-agent/features/php-code-level-metrics.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-12-0-0-24.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-12-0-0-25.mdx
Updates for the PHP agent release v12.0.0:
Add 'PHP agent v12.0.0' release notes and supporting documentation that was updated to reflect functionality changes.
=> PHP Agent release v12.0.0

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx
=> updated the doc with the new permission needed

src/content/docs/release-notes/aws-lambda-log-forwarder-release-notes/lambda-25-07-25.mdx
Adding release notes for latest release of aws unified lambda
https://github.com/newrelic/aws-unified-lambda/pull/44
=> Release notes for aws lambda

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx
Updated Step 2.4 sign-on URI string
* What problems does this PR solve? The value from documentation should match the actual in the guided install.
=> Updated activate-azure-integrations.mdx Step 2.4 sign-on URI string

src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-1510.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-158.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-159.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-708.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-709.mdx
=> chore:update capacitor and cordova release notes

src/content/docs/nrql/nrql-syntax-clauses-functions.mdx
Updating the uniqueCount() function example to use real attributes.
=> Update uniqueCount() function example to use real attributes

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-350.mdx
Release notes for the Diagnostics CLI version 3.5.0
=> feat(DiagCLI): Diagnostics CLI v.3.5.0 Release notes

src/content/docs/ai-monitoring/drop-sensitive-data.mdx
* Added drop rules EOL message in AIM docs.
=> feat: Added drop rules EOL message in AIM docs[NR-450446]

src/i18n/content/fr/docs/accounts/accounts-billing/new-relic-one-pricing-billing/compute-budgets/overview.mdx
=> Minor FR edits

src/content/whats-new/2025/08/whats-new-08-26-cardinality-control.md
What's new post for Cardinality controls
=> What's new post for cardinality controls

src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.21.mdx, src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.22.mdx, src/content/docs/release-notes/lambda-extension-release-notes/lambda-extension-2.3.23.mdx
- What problems does this PR solve?
New Release Notes for [Lambda Extension `v2.3.21`](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.21)
New Release Notes for [Lambda Extension `v2.3.22`](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.22)
New Release Notes for [Lambda Extension `v2.3.23`](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.23)
- Add any context that will help us review your changes such as testing notes,
[APM Fusion Mode: Limited Preview](https://docs-preview.newrelic.com/docs/apm-serverless-convergence)
- If your issue …
=> Lambda Extension v2.3.21

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/k8s-version2/kubernetes-windows.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/troubleshooting-windows.mdx
* Fixes broken links to k8s integration installation instructions
* Adds callout to k8s integration compatibility requirements
=> fix: correct k8s install links and add public preview callout

src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-157.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-158.mdx, src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-159.mdx
=> chore:react native release notes

src/content/docs/data-apis/understand-data/event-data/events-reported-mobile-monitoring.mdx
This PR fixes the broken link issue for raised in this [hero-request](https://newrelic.slack.com/archives/C0DSGL3FZ/p1756468007507709).
=> fix the broken link

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-463.mdx, src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.2.126.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.43.mdx
=> SJM and run times vulnerability fixes

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8240.mdx
=> Java Agent v8.24.0 Release

src/content/docs/licenses/license-information/usage-plans/new-relic-usage-plan.mdx
Updated the broken links in the Usage Plan document.
=> Updated the broken links

src/content/docs/infrastructure/other-infrastructure-integrations/cloudfoundry-integrations/vmware-tanzu-dotnet-buildpack-integration.mdx
This PR has updated release notes for TAS10.2 support for .net buildpack.
=> Updated Release notes.

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-8240.mdx
=> fix the frontmatter error

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-7510.mdx
New Relic iOS agent 7.5.10 Release Note
=> New Relic iOS agent 7.5.10

src/content/docs/new-relic-control/agent-control/configuration.mdx, src/content/docs/new-relic-control/agent-control/reinstrumentation.mdx, src/content/docs/new-relic-control/agent-control/setup.mdx, src/content/docs/new-relic-control/agent-control/troubleshooting.mdx
Update the chart from agent-control to agent-control-bootstrap in agent-control docs.
=> docs: update the chart from agent-control to agent-control-bootstrap

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-467.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-3.0.49.mdx
=> chrome upgrade from 131 to 134

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-41-0.mdx
Go Agent Release v3.41.0
* Added `DistributedTracer.Sampler` config options for controlling the sampling behavior for Inbound Requests for distributed traces
* To configure the sampler, added `ConfigRemoteParentSampled(flag RemoteParentSamplingConfig)` and `ConfigRemoteParentNotSampled(flag RemoteParentSamplingConfig)` which handles sampling behavior based on what the remote parent has flagged
* Flags added are `"always_on", "always_off", and "default"` which can be called using `RemoteParentSamplingConfig`
* `Example: newrelic.ConfigRemoteParentSampled(newrelic.AlwaysOff)`
* Added OOM Monitoring Tests
* Increased Secure Agent Test Coverage
* Updated third-party library versions due to reported security or other supportability issues:
* `github.com/gofiber/fiber/v2` from 2.52.7 to 2.52.9 …
=> Go Agent Release v3.41.0

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1690.mdx
=> Add infra-agent 1.69.0 release notes

src/content/docs/new-relic-control/agent-control/troubleshooting.mdx
This PR adds extra cases to the agent-control troubleshooting and changes the layout to be easier to navigate.
=> Improve Agent Control Troubleshooting

src/content/docs/logs/get-started/live-archives-billing.mdx
Corrected the pricing SKU from CCU to aCCU.
=> chore[live archive]: Corrected the pricing SKU from CCU to aCCU.

src/content/docs/query-your-data/explore-query-data/dashboards/share-charts-dashboards-externally.mdx
https://newrelic.slack.com/archives/CPXF9VA2Z/p1759846009232559?thread_ts=1759845411.822479&cid=CPXF9VA2Z
=> chore[public dashboard]: Updated the prerequisites as suggested by SME

src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-7511.mdx
=> iOS agent 7.5.11 release note
