- src/content/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics.mdx
Changed above to below for Example #2: Report for a particular monitor. Instead of moving the query above as the line described, I changed above to below to leave the query in a similar format as the rest of the queries.
> Change above to below

- src/content/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx
This PR adds some new regions to which we replicate our log forwarding images for Firelens.
> chore: Add new supported regions for Firelens log forwarding

- scripts/actions/translation_workflow/models/job.js
- scripts/actions/translation_workflow/models/translation.js
- scripts/actions/translation_workflow/models/typedefs.js
- scripts/actions/translation_workflow/testing/creation_and_cleanup.sql
* updated testing scripts to include new `project_id` column in translation and jobs tables
* updated models to match
Did some testing to see how we could make changes to production and work with changing code in the feature branch. As long as the `project_id` column can be null, we can add the new columns w/o impacting the current workflows. A constraint on the column would be nice, but is more difficult to work around.
Resolves: #2538
> update translation testing, models

- src/content/docs/apm/agents/ruby-agent/background-jobs/delayedjob-instrumentation.mdx
Adding a section with code samples on how to add custom attributes to DelayedJob transactions by using a DJ plugin.
With the New Relic Ruby agent, it is easy and well-documented to add custom attributes to transactions from pieces of code like Rails controllers, services, etc. However, it is not well-documented how to do the same from DelayedJob when one wants to access fields that are DelayedJob-specific, like `run_at`, etc.
This PR adds a section with code snippets demonstrating how to accomplish this.
The original discussion on this occurred in https://github.com/newrelic/newrelic-ruby-agent/issues/834, which …
> feat: Add documentation for DelayedJob custom attributes

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx
Issues around module load order are a high ticket driver and adding this require flag to their scripts can safeguard against this common issue caused by Babel. I threw it in a callout but you can use whatever layout you deem best.
> Added '-r newrelic' startup script to install docs

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
The single-quotes represent string literals in NRQL. The query `sum('foo')` will silently not produce useful results.
> fix: numeric functions should use attribute names

- .github/CODEOWNERS
The PMMs have asked that they be assigned to review any PR that touches the What's New directory. This seemed like a great time to try out CodeOwners. Let me know if I did something wrong.
> fix: add PMM codeowners

- src/content/docs/style-guide/writer-workflow/github-intro.mdx
We have run into quite a few issues with our current release process. This new release process solves two main issues:
1. Merges to develop interrupting merges to main
2. Merges to develop breaking the Gatsby cloud builds for merges to main.
By adding an additional step, creating a release branch, we should be able to completely solve the two issues above. See this image for a visual understanding of how this will work:
~~DevEn is currently working on a few dev changes needed to implement this, so we should only roll this out once those are in place. ~~
All DevEn work is now complete. This is good to go as soon as the team gives the OK.
See #4569 for more context.
> chore: Update docs release process

- src/content/docs/style-guide/writer-workflow/github-intro.mdx
Adds info to the style guide about docs issues labels
> fix: docs-issues-migrate

- src/content/docs/apis/nerdgraph/tutorials/nerdgraph-workloads-api-tutorials.mdx
> Remove beta callout in nerdgraph-workloads-api-tutorials.mdx

- src/content/docs/apm/agents/go-agent/instrumentation/create-custom-metrics-go.mdx
This documentation never got updated years ago when v3 of the Go Agent was released.
> Replace old-fashioned, pre-v3 application creation method with current method

- src/content/docs/accounts/accounts/automated-user-management/azure-ad-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/onelogin-scimsso-application-configuration.mdx
Minor fix to wording about user type in AUM docs. Originated w/ https://github.com/newrelic/docs-website/issues/5023.
> fix(AUM docs): fix user type reference

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
We're  getting ready to release version 9.2.0 of the .NET APM language agent and announce support of .NET 6, which went GA last week.  We need to update our compatibility and requirements for the .NET Core agent to reflect this.
> Nov 18 release: Add .NET 6.0 compatibility

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
`percentile()` and `average()` have their own FACET functions and this needs to be specified in the docs.
> Document percentile() and average() with FACET

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
* The original implies that customers will be monitoring their logs using Kinesis
* In fact they will monitor their logs in CloudWatch Logs and use Kinesis to transport those logs to NR1
> Corrected the meaning in Opening Sentence of Kinesis integration docs

- src/content/docs/apm/agents/go-agent/index.mdx
- src/content/docs/apm/agents/java-agent/installation/update-java-agent.mdx
- src/content/docs/apm/agents/php-agent/troubleshooting/php-installation-fails-os-x-1011-el-capitan.mdx
- src/content/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring.mdx
- src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
- src/nav/infrastructure.yml
Apple's official style is macOS, not Mac OS
* Our usage guidelines: https://docs.newrelic.com/docs/style-guide/quick-reference/usage-dictionary/#macos
* Example in use on Apple's site: https://www.apple.com/macos/monterey/
> style(whole site): Standardize macOS terminology

- .github/workflows/check-translations-and-deserialize.yml
Add Julien (stakeholder) as reviewer on translation PRs
Resolves: #3853
> chore: add stakeholders to translation prs as reviewers

- src/content/docs/using-new-relic/user-interface-functions/share-your-data/ticketing-integrations.mdx
We have an old doc about ticketing integrations that shows up in a Google search for "New Relic Jira integration" but it has no information about Jira! 
This is a PR that adds a Jira section to this ticketing doc. It simply sends users over to errors inbox, which does talk about Jira. The goal is to improve SEO.
> Add link from ticketing integrations to errors inbox

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Multiple customers requested details about costs that should be considered when evaluating the AWS CloudWatch metric stream integration. Added a reference on all services required on AWS side and links to the pricing pages.
> CloudWatch metric stream cost considerations

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Certain AWS services are global (and not per-region), in those cases, their metrics will only be available if customers connect a stream in us-east-1 region (AWS design decision). Added a note explaining this.
> fix(AWS): note about global services

- src/content/docs/apm/agents/net-agent/other-features/net-performance-metrics.mdx
As reported in #5042, added a quick note on the Metric explorer in APM.
> Added mention to metric explorer in Net agent doc

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
NRQL alert conditions may not contain SINCE or UNTIL
> Remove disallowed components from sample alert queries

- src/content/docs/apm/index.mdx
Health maps was end-of-lifed in the summer 2021.
Closes #5065
> fix(APM): Removed broken link

- src/content/docs/style-guide/writing-docs/writer-workflow/github-troubleshooting.mdx
This creates an h3 section for the yarn verify topic since it's a bit hard to find when skimming.
> create h3 for yarn verify

- src/nav/root.yml
We had a hero request to add the security section back to the left nav. Closes #5082
> fix: add security to left nav

- src/layouts/MainLayout.js
Changes background color of left nav to use same as primary background to blend in more. Also fixes issue where you could not see current page highlighted in corresponding left nav item.
Closes https://github.com/newrelic/docs-website/issues/5081
Closes https://github.com/newrelic/docs-website/issues/5093
> Fix left background color, current page highlighted

- src/nav/logs.yml
- src/nav/root.yml
Got some feedback from PMM that "log management" is generally easier to grok for folks than "logs." This is also how we refer to it in most other places on the site.
> style(homepage): Change nav to refer to "log management"

- src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx
The current Dockerfile examples for using the .NET agent in Linux reference `.NET Core 2.2`, which is pretty old and has been unsupported by Microsoft for a while now.  This PR updates the examples to use `.NET 6.0` which is the latest LTS version of the platform.  It also adds some comments to help our customers find the right container base images appropriate for their use case.
I tested these examples on my system and everything worked as expected.
> Update example (linux) Dockerfiles to use current .NET versions

- loadershim.js
- scripts/actions/__tests__/add-files-to-translation-queue.test.js
- scripts/actions/add-files-to-translation-queue.js
- scripts/actions/translation_workflow/testing/script.sh
- scripts/actions/utils/constants.js
- scripts/actions/utils/docs-content-tools/i18n-exclusions.yml
- scripts/actions/utils/helpers.js
This adds the ability to exclude files under specific paths, and of specific types which are configured using a YAML file.
This also adds tests to the add-files-to-translation-queue workflow as there weren't any before, and adds tests for excluding files/types
> feat: exclusion file and tests

- src/content/docs/style-guide/writing-docs/processes-procedures/edit-homepage.mdx
Add a section to our style guide on editing the home page left nav.
> fix: add home page left nav info

- scripts/actions/send-and-update-translation-queue.js
- scripts/actions/translation_workflow/database.js
* now only pull translation requests for a particular project_id
* when we create a job, also include project_id
* fixup comment
Resolves: #4816
> Updates to send translation script for using project_id

- src/components/HomepageBanner.js
- src/i18n/translations/en/translation.json
- src/i18n/translations/jp/translation.json
Adds home page banner text to translations.json. Fixes FSO section to match between english and jp versions.
I'll make a follow up PR to add the japanese content to `src/i18n/jp/translations.json` when it comes back via @jmiraNR 
partially closes https://github.com/newrelic/docs-website/issues/5097
Closes https://github.com/newrelic/docs-website/issues/5098
> [i18n] Update home page banner, fso translations

- src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
This callout uses an all-caps `NOTE` which is not our style, and also is a bit over-written.
> style(support offerings): Simplify and clarify callout language

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start.mdx
- This prevents users from having to click to another page to find the endpoint. 
- Also added an important Callout to the FedRamp box to highlight it, seems like it could easily be missed.
> Update FedRamp section with actual endpoint URL

- src/data/homepage.yml
The NRQL link in the popular content section was pointing to a less useful doc. It should be more useful now.
> fix(Docs homepage): Updated NRQL chart link

- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/manage-pixie-data.mdx
Missing double quote after `px-operator`
helm upgrade newrelic-bundle newrelic/nri-bundle --reuse-values -n newrelic --set newrelic-pixie.excludeNamespacesRegex="default|kube-node-lease|kube-public|kube-system|newrelic|newrelic-custom-metrics|olm|px-operator"
> Missing Double Quote in Pixie Command

- src/content/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/get-started/introduction-new-relics-open-source-telemetry-integrations.mdx
Fixes broken links to old auto-index pages. Closes #5147.
> fix(integrations): fix broken OSS sdk links

- .github/workflows/check-translations-and-deserialize.yml
- scripts/actions/check-job-progress.js
- scripts/actions/configuration.js
- scripts/actions/deserialize-html.js
* For a run, only check one project at a time.  This means we run the script once for human translations, and once for machine translations
* add environment variable which indicates translation type when running script
* created new configuration module to be central place for configuration values for scripts. This represents a single place for setting & getting configuration values. We can also write JSDOCs for such pieces of code. I think this is a future facing improvement versus just using process.env.some_value.
* use new configuration module for type to add frontmatter when deserializing content.
Resolves: #4204
> Download translation script updates

- src/content/docs/apm/agents/php-agent/getting-started/introduction-new-relic-php.mdx
- src/content/docs/logs/logs-context/annotate-logs-logs-context-using-apm-agent-apis.mdx
- src/content/docs/logs/logs-context/configure-logs-context-php.mdx
We had a contributor mention that logs in context isn't available for PHP apps directly in the Logs tab of APM. It is only supported in the distributed tracing pages.
> Clarify that logs in context isn't available in APM UI for PHP

- src/content/docs/alerts-applied-intelligence/mlops/bring-your-own/mlops-byo.mdx
I added this link https://github.com/newrelic-experimental/ml-performance-monitoring to ml-performance-monitoring, which was missing
> Link addition

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-15-2.mdx
* Strings logged via the Go Agent's built-in logger will have strings of the form `license_key=`*hex-string* changed to `license_key=[redacted]` before they are output, regardless of severity level, where *hex-string* means a sequence of upper- or lower-case hexadecimal digits and dots ('.'). This incorporates [PR #415](https://github.com/newrelic/go-agent/pull/415).
New Relic recommends that you upgrade the agent regularly to ensure that you’re getting the latest features and performance benefits. Additionally, older releases will no longer be supported when they reach end-of-life.
> Release notes for Go Agent v3.15.2

- src/content/docs/licenses/translated-documentation/translation-disclaimer.mdx
- src/nav/licenses.yml
Add new category under licenses documentation that contains the disclaimer for translations.
> Add translation disclaimer

- CONTRIBUTING.md
Here are some suggestions to clarify the use of conventional commit types and scope for our contributors. 
I removed the comment about using conventional commits in the pull request because I heard that PRs are really separate from commit processing. If you disagree, let me know.
I switched up the examples, and narrowed the focus of "chore." If you disagree, let me know.
> Clarify conventional commit types and scope for contributors

- src/content/docs/alerts-applied-intelligence/notifications/message-templates.mdx
Note from @zuluecho9: This will be deleted and the changes from it included in https://github.com/newrelic/docs-website/pull/5179. 
Adds documentation for the new `replace` helper in handlebars for Applied-Intelligence 'Notifications'
> Applied-Intelligence 'Notifications' docs - new custom helper for handlebars

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Consistently use code formatting (backticks) instead of quote marks.
> chore(style guide): Consistent punctuation in usage dictionary

- src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx
- src/content/docs/alerts-applied-intelligence/notifications/message-templates.mdx
- src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
This contains update for the Applied-Intelligence 'Notifications' docs
New docs for the new Email integration and minor phrasing changes to the 'templates' page
> Applied-Intelligence 'Notifications' docs - new Email Integration and minors

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
This link returns a 404: https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/
As best as I can determine the this link is attempting to route to: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/get-started/introduction-new-relics-open-source-telemetry-integrations/
> docs: fixed broken otel integrations link

- src/content/docs/infrastructure/amazon-integrations/troubleshooting/metric-data-delays-amazon-aws-integrations.mdx
* We detected the AWS ELB service also has an explicit delay of 5' which was not documented. Added.
> Adding one missing explicit delay for AWS ELB

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-651.mdx
- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-741.mdx
Documentation on the Java agent releases that fix the security vulnerability:
https://www.cve.org/CVERecord?id=CVE-2021-44228
> chore: Java agent release notes 6.5.1 and 7.4.1

- src/nav/accounts.yml
The data center link in the left nav was broken. A bad path in the YAML file.
> fix(Accounts): Fixed broken nav link

- src/nav/root.yml
This adds the licenses category to the left nav of the home page per hero request.
> fix(nav): add licenses directory to home page left nav

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-651.mdx
- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-741.mdx
Adding more info on the release notes related to CVE-2021-44228 about supported Java versions and workarounds.
> chore: java-agent adding more info on recent release notes

- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/codestream/start-here/codestream-new-relic.mdx
Because these APM environment variables are CodeStream-specific, I thought it was better to keep in one place, instead of documenting them in each APM agent docs.
I did add links to the CodeStream docs from the relevant APM config docs.
> feat(APM/CodeStream): Add links to CodeStream env variables DOC-7574

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Note: We will not be releasing the agent till after the holiday break (like most everyone) so this is not in anyway urgent!
Updates our listed support for NServiceBus from 5.0 only to 5.0 or higher on both Framework and Core.
Resolves newrelic/newrelic-dotnet-agent#824
> chore: Updates supported versions of .NET Agent NServiceBus

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-651.mdx
One of the proposed mitigation steps provided by log4j does not work for the Java agent.
Updating the release notes to reflect that.
> chore: java-agent - rectifying mitigation procedures

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- `linkedEntityGuids` are specific to customer's newly created dashboard, so no way to know ahead of time, just set to `null` instead and let customer choose what to filter on.
- provide more details on how to associate account IDs with each event type, especially in cases where the private locations and monitors live in different accounts.
> fix: JSON bugs and add steps

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-742.mdx
Java agent release 7.4.2 mitigates CVE-2021-45046.
> chore: Java agent 7.4.2 release notes

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
I had a customer ticket confused weather the codes should be an array of strings or nums, `["404","401"]` or `[404,401]` so I added that info. I also checked [the default value from the `lib/config/default.js`](https://github.com/newrelic/node-newrelic/blob/44b73f2b1fd549894474d1d37ab3b2f2d6e982ad/lib/config/default.js#L289) and it is an array with 404 in it, `[404]`, not just the int `404`. It's minor but I think that being explicit will help some people.
* If your issue relates to an existing …
> docs: clarify the array of status codes are ints

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Adding the latest point release to the table.
6.5.1 is not compatible with Java 7.
> chore: adding point release to the Java compatibility table

- src/content/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring.mdx
The old links to the setup instructions do not work anymore, it has been replaced with the Instrument Everything page filtered by OS, because the user may need to select an account and that depends on this page, the instructions are already scoped by account.
> fix: Replace links to Instrument Everything page

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic.mdx
The removed section creates more questions than it answers as highlighted in this thread from CNCF Slack https://cloud-native.slack.com/archives/C024DRQ63UP/p1639683781017600.
> OpenTelemetry Introduction: Confusion is not efficient

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
A link in the requirements section was pointing to 6.5.0 release. Updated the link to the latest point release.
> chore(java-agent): Updating download link to latest point release

- package.json
- scripts/actions/__tests__/send-and-update-translation-queue.test.js
- scripts/actions/check-job-progress.js
- scripts/actions/fetch-and-deserialize.js
- scripts/actions/remove-completed-batch.js
- scripts/actions/send-and-update-translation-queue.js
- scripts/actions/translation_workflow/testing/wait_for_translation.js
- scripts/actions/utils/vendor-request.js
- yarn.lock
This PR introduces a change to start caching the access token in getAccessToken. Additionally, getting the access token is now almost entirely encapsulated in vendor-request.js.
Now, most of the scripts don't have to even worry about access tokens -- getting and caching the token is handled in one spot. This is reflected with the changes to vendorRequest method signature, and removal of access token code usage.
We push the generation of access tokens deeper into the code, closer to where we actually need to use it. Rather than our high level scripts caring about getting & managing an access token, we leave that concern in our lower level vendor api code.
Now, every time vendorRequest is called, we call getAccessToken internally. getAccessToken will automatically generate & store valid …
> 5348 cache access token

- src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx
I formatted the codeblocks for readability and added language identifiers to those code blocks for when our docs site may enable syntax highlighting. 
I'm not sure what to make of this codeblock, it was one line and entirely a comment, a .NET person should probably be asked if this even makes sense or if it was supposed to be something else
```cs
//Obtain the information from the request object from the upstream caller.
//The method by which this information is obtain is specific to the transport 
//type being used. For example, in an HttpRequest, this information is
//contained in the 
header.KeyValuePair<string, string> metadata = GetMetaDataFromRequest("requestPayload");
IAgent agent = NewRelic.Api.Agent.NewRelic.GetAgent(); 
ITransaction transaction = agent.CurrentTransaction; …
```
> docs: format code blocks and fix example code error

- src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx
`<distributedTracing excludeNewrelicHeader="true" />` was written as "<`distributedTracing excludeNewrelicHeader="true" />`"
I also assed the `cs` language identifier to the one code example it was missing from.
> docs: fix typo, add last missing filetype

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-cloudtrail-monitoring-integration.mdx
* Due to performance reasons, AWS CloudTrail integration is not enabled on all AWS regions by default. This is currently enabled and monitored based on customers demand. Added a note explaining the limitation.
> chore: note about AWS CloudTrail limitation

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-743.mdx
New release of the Java agent addressing CVE-2021-45105.
> chore(java-agent): 7.4.3 release notes

- src/content/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data.mdx
Based on issue https://github.com/newrelic/docs-website/issues/5187, adding allowed characters in tag doc's requirements.
> fix(tags): adding allowed characters

- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation.mdx
I added java and yml language types to the codeblocks in this section so they can use language specific syntax highlighting if/when that is enabled on our docs. I also added a line of white-space before and after code blocks. Depending on how the md is interpreted the codeblock syntax highlighting can be broken without the white-space before it.
> docs: add language identifiers to codeblocks

- src/content/docs/apm/agents/net-agent/net-agent-api/disablebrowsermonitoring-net-agent-api.mdx
The `transaction` link didn't open to the `#transaction` section of the glossary, I think because it was an old URL that redirects. I updated the link.
I also added c# as the language identifier for the code blocks.
> docs: update link, add codeblock language

- src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx
Entity search expressions in the examples in the [View entity data tutorial](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial/) don't display best query practices, and may induce users to misuse the search. This PR is an attempt to address this.
> ESA-625 Improve entity search queries

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
We released a new version of the agent and need to update a link to point to that release.
> chore(java-agent): bumping download link to latest Java 7 agent

- src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx
I formatted the JS codeblock, added missing `;`s, corrected indentation, and this `return` was broken up onto two lines making the code unreachable:
```js
navlinks.foreach(function (val, i, arr) {
//finds and navigates to each navlink page
return
$browser.findelement($driver.by.classname(navlinks[i])).click().then(function () {
```
I also added the `js` language identifier to the codeblock so it will use the correct syntax highlighting.
* If your issue relates to an existing GitHub issue, please …
> docs: format example code & add lang identifier

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-6.5.3.mdx
The release notes for the java agent referenced the wrong CVE.
> chore(java-agent): correcting the CVE for the newest release

- src/content/docs/infrastructure/install-infrastructure-agent/manage-your-agent/infrastructure-agent-performance-overhead.mdx
* When installing the infrastructure agent on Linux, a max memory limit of 1gb is enforced by service manager settings (systemd, upstart). GTS feedback received to document this default setting so that customers are aware.
> chore: note about max memory defined by default

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
* Win 2022 was released Sep-2021, adding support after validations via Guided Install & canary servers.
> Win 2022 support for infra-agent & log-fwd

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
* updating helm repo link to parity of instructions in NR1 UI
Resolves: docs/update-cpm-helm-repo-link
* This just creates parity between the NR1 UI and the docs, as when "Create private location" call-to-action/button is clicked, a name + description have been filled out, and then the "Generate Key" button/call-to-action has been clicked - in the UI under the instructions of `helm repo add` the URL is different between the two, figured that the one in NR1 may be more accurate than the one given in the docs
**however**
I may be totally wrong with this edit 😅  - so feel free to close this if the NR1 UI actually needs it's URL to be updated instead of the docs 😅 
X-Reference Screenshot:
Please also ignore this prior 'quick' page edit via: …
> Update CPM Helm Repo Link

- src/content/docs/logs/ui-data/find-unusual-logs-log-patterns.mdx
Currently an NR Integration Error is generated when Log Patterns is short circuited due to a lack of processing time available. This error isn't something customers can do anything about; they don't control the patterns logic. All this does is create confusion with customers, who in turn ask their sales team who then ask Logging about it.
We are going to internally keep track of patterns that are super slow and could be made better, and we should do more in terms of looking at accounts that have unacceptably high levels of Patterns failing. But customers don't need to see this -- pattern matching is a "best effort" process, it's OK if we can't match …
> fix(Log management): LOGGING-6831: Log patterns is now "best effort"

- src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/incorrect-data-reported.mdx
- src/nav/infrastructure.yml
* Adding a troubleshooting page explaining how to enable log traces in the Infrastructure Agent to print all events and metrics being sent to Telemetry Data Platform (Infrastructure endpoints). This is relevant for complex troubleshooting scenarios when there's discrepancy between expected data and what's shown in the UI.
> feat(infra-agent): added how to troubleshoot with log traces

- src/content/docs/apm/agents/net-agent/net-agent-api/iagent.mdx
`getAgent` is not the same as `GetAgent`, getAgent would throw an error. I also added c# language identifiers to the code blocks
> docs: change getAgent to GetAgent

- src/content/docs/apm/agents/net-agent/net-agent-api/tracemetadata-net-agent-api-0.mdx
This is a follow up to my previous PR - https://github.com/newrelic/docs-website/pull/5435
The only change here is the namespace on line 17, the rest is duplicated from my previous PR to prevent any accidental merge conflicts.
Basil Abusamrah confirmed that the given namespace is incorrect on this doc. [Slack conversation](https://newrelic.slack.com/archives/C7HNR7WNR/p1640646166416300), [link to confirm namespace](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic.Api.Agent/TraceMetadata.cs).
Additionally, our docs use a simpler example syntax for creating an Agent instance than this doc did, [as you can see here](https://docs.newrelic.com/docs/apm/agents/net-agent/net-agent-api/itransaction/#example-2) so I changed `NewRelic.Api.Agent.IAgent Agent = …
> docs: correct TraceMetadata namespace

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
The C# and Javascript code was messy and not indented properly. I made various minor syntactical improvements to better match best practices. I also added language identifiers to code blocks since I was here. I've spoken to Shawn and Zachary about this types of edits in the past.
> docs: clean up codeblocks and add lang identifiers

- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/deprecation-notice-v1.15andlower.mdx
* Previous notes stated that v1.16 was deprecated, which is not true.
* Previous notes instructed to upgrade the integration rather than the cluster.
> kubernetes: clarify <1.16 deprecation message

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
I added `bash` to these code blocks yesterday without realizing that they would now automatically add a `$` to the beginning of the lines of code. Since we were doing that directly in this markdown it was rendering as `$ $ zip deployment.zip main` instead of `$ zip deployment.zip main`. 
> docs: remove duplicate $ from bash

- src/content/docs/apm/agents/nodejs-agent/troubleshooting/generate-trace-log-troubleshooting-nodejs.mdx
The 4 links I updated weren't going to the correct `#path` location, just redirecting to the page.
The indentation was off on the js example. I also added the `js` identifier to the codeblock for highlighting, Shawn and Zachary are aware of that change.
> docs: update links, correct code indentation

- src/content/docs/apm/agents/nodejs-agent/troubleshooting/generate-trace-log-troubleshooting-nodejs.mdx
You can set the logging level to `trace` with an env var or in the newrelic.js. Some users do not use the newrelic.js for config so these steps will not work for them.
> docs: add to step 1 option to use env vars

- src/content/docs/logs/ui-data/parsing.mdx
We support typed attributes being extracted using Grok, but documentation does not make that clear
> fix(Log management): LOGGING-6833: Grok types

- .github/workflows/validate-pr.yml
- scripts/actions/__tests__/check-for-outdated-translations.test.js
- scripts/actions/check-for-outdated-translations.js
Updates the script behind the workflow step that checks a PR for files that changed and may need to be applied to corresponding i18n files. Updates it to also check for status of `renamed` which indicates a file was moved.
Also updates the script to invoke `main()`, since I think this was never actually run 
Related to https://github.com/newrelic/docs-website/issues/4232
> Update workflow script to check for renamed files and invoke main

- src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx
Prometheus made [changes](https://github.com/prometheus/prometheus/commit/8787f0aed79c5feffb0b18b6051e8ddd91d7bbce) to the preferred way to configure remote write credentials in v2.26.
> Add remote write configuration for v2.26+

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts.mdx
Added a section for multi-location Synthetic monitoring conditions per issue https://github.com/newrelic/docs-website/issues/3009
Adds multi-location Synthetic monitor alert condition examples which previously required finding usage examples in the API explorer. This also fixes a broken link in Available data and functions via API to the synthetics-conditions section header. …
> docs: add multi-location synthetic alert conditions to API documentation

- src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
- src/i18n/content/jp/docs/alerts-applied-intelligence/overview.mdx
Adds redirect for defunct synthetics landing page that a user discovered.
https://docs.newrelic.com/docs/synthetics/
Best doc seems to be the get started intro doc:
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
> fix: add redirects for defunct landing pages

- src/content/docs/accounts/accounts-billing/general-account-settings/default-time-zone-setting.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-saml-scim.mdx
- src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
- src/content/docs/accounts/accounts/automated-user-management/azure-ad-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/onelogin-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/roles-permissions-automated-user-management.mdx
- src/content/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management.mdx
- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
- src/content/docs/release-notes/org-user-mgmt-release-notes/org-users-21-11-01.mdx
- src/content/docs/style-guide/writing-docs/processes-procedures/create-edit-content.mdx
- src/content/docs/style-guide/writing-docs/processes-procedures/understand-edit-docs-site-structure.mdx
Adding info to our internal style guide explaining how, when you edit folder/file structures (e.g., moving folders/files, or renaming folders/files) you must do equivalent edits in the i18n directory.
> Adding i18n info to style guide

- scripts/actions/check-job-progress.js
- scripts/actions/remove-completed-batch.js
On route to tackling #5485 I noticed a couple other awkward things that I thought should be fixed immediately. 
Problems I observed were:
1. jobs are being marked as completed too early.
2. the remove/cleanup script is cleaning up state for ALL completed operations, when it should be limited to its specific project (machine or human).
1. I've moved marking a job as completed to after the files have been deserialized, and the translations are marked as completed.
2. I've updated the cleanup script to only cleanup completed state for the specific project of the run.
> fix: quick updates to fix bugs, suboptimal-ness of workflow

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
Updated the helm uninstall command syntax. Prior, the command pointed to the chart and not the release so it would not run if somebody copied/pasted it as is.
> Updated K8s helm uninstall

- src/content/docs/alerts-applied-intelligence/overview.mdx
- src/content/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2.mdx
- src/content/docs/apm/agents/c-sdk/get-started/introduction-c-sdk.mdx
- src/content/docs/apm/agents/go-agent/get-started/introduction-new-relic-go.mdx
- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
- src/content/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net.mdx
- src/content/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs.mdx
- src/content/docs/apm/agents/php-agent/getting-started/introduction-new-relic-php.mdx
- src/content/docs/apm/agents/python-agent/getting-started/introduction-new-relic-python.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx
- src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
- src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
- src/content/docs/data-apis/get-started/nrdb-horsepower-under-hood.mdx
- src/content/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring.mdx
- src/content/docs/licenses/overview.mdx
- src/content/docs/logs/get-started/get-started-log-management.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring.mdx
- src/content/docs/new-relic-solutions/overview.mdx
- src/content/docs/security/overview.mdx
- src/content/docs/serverless-function-monitoring/overview.mdx
- src/data/external-redirects.json
Because taxonomy-redirects.json was deleted, there were some auto-index and landing page redirects that needed to be added elsewhere.
> fix(Docs): Added missing redirects from taxonomy-redirect.json

- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
It was shown in https://newrelic.atlassian.net/browse/GTSE-12934 that we do not fully support kafka api version 2.8 yet and only support 2.6 and below. I updated our documentation accordingly until we can test on the newer version.
> Update supported kafka api versions

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Added important callout to the .Net Agent Infinite Tracing configuration section about how spans might get limited.
> Added callout note for .net infinite tracing.

- src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-integration.mdx
* Updated JMXTerm troubleshooting section since it's no longer bundled with nrjmx.
> fix(jmx): clarification about jmxterm not bundled

- src/content/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api.mdx
This adds a step reminding users to update the timestamp when sending metric API payloads.
[Customer got tripped up](https://github.com/newrelic/docs-website/issues/4115) when using the metric api for the first time. This PR sets out to make that experience better.
N/A
https://github.com/newrelic/docs-website/issues/4115
> Issue-4115 : Clarify docs to update timestamp in api JSON

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/alert-custom-violation-descriptions.mdx
Currently, the doc only shows how to change a NRQL alert which makes it seem like it cannot be done in an infrastructure alert, despite being mentioned earlier that it can. This adds directions and more explicit confirmation.
- Clarifies process for infrastructure alerts
- Has been tested this way, can confirm this is the proper procedure. 
> Update to line 56

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-troubleshooting.mdx
Adding another query option to possible Solutions troubleshooting:
FROM Log,Metric,Span SELECT count(*) where newrelic.source='%otlp%' SINCE 1 week ago TIMESERIES MAX LIMIT MAX
> Update Possible Query Solution for checking otlp endpoint

- src/content/docs/using-new-relic/welcome-new-relic/get-started/networks.mdx
Closes #5522
`onenr.io` is the user-facing domain used for sharing permalinks from New Relic One.
> feat(UXP): Added sharing permalink user-facing domain

- src/data-dictionary/events/AjaxRequest/AjaxRequest.event-definition.md
Closes #5526.
I've updated the AjaxRequest entry in the data dictionary, @khickey-newrelic. 
Are there any other places where you think this should be updated?
> feat(Browser): Updated AjaxRequest event type to match latest feature release

- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile/maintenance/viewing-your-application-token.mdx
As part of DOC-7619, an attempt to make it more clear that you can create additional license keys.
> fix(license keys): clarify you can add them

- src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx
Currently customers are not aware sometimes there is an actual limit in the number of entities returned by API and how to paginate through results.
> [ESA-415] Document nerdgraph entitySearch limit

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1207.mdx
- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1210.mdx
[TO BE MERGED AFTER AGENT RELEASE] - https://github.com/newrelic/infrastructure-agent/releases/tag/1.21.0
- Adding missing header for 1.20.7
- Adding new release notes for 1.21.0
> Infrastructure agent release notes for 1.21.0 and update for 1.20.7

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Jedis released version 4.0.0 a couple of weeks ago and our instrumentation does not apply to the new version.
So capping the supported version.
> chore(java-agent): update jedis supported version

- src/content/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx
- src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx
- src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-metrics.mdx
- src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-820.mdx
- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-830.mdx
* Adds release notes for Ruby Agent 8.3.0
* Update release date for Ruby Agent 8.2.0
* Add warnings to documentation untested on Rails 7+
> chore: Update Ruby agent documentation to release version 8.3.0

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications.mdx
There has been some confusion about selecting both a start and end date AND a "day of the week" checkbox. Trying to be as clear here as possible, to mitigate confusion.
> Clarify weekly muting rules behavior

- src/content/docs/infrastructure/infrastructure-integrations/get-started/understand-use-data-infrastructure-integrations.mdx
- src/content/docs/infrastructure/infrastructure-ui-pages/infrastructure-events-page-live-feed-every-config-change.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/linux-agent-running-modes.mdx
As part of fixing a broken link, I deleted some 'types of infrastructure data' wording that was a) in an 'infra integrations' doc but really was more general than just integrations, and b) basically incorrect and more confusing than it needed to be.
> fix(infra): fixing link, finessing some data wording

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx
* **What problems does this PR solve?** The docs previously made it seem like anyone could delete a monitor. This makes it clear that only admins may do so.
* **Add any context that will help us review your changes such as testing notes,
links to related docs, screenshots, etc.** Information obtained from these sources
- https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/user-roles-synthetic-monitoring/
- https://discuss.newrelic.com/t/unable-to-delete-synthetics-monitor/74379
* **If your issue relates to an existing GitHub issue, please link to it.** N/A
> Clarifies permissions needed for monitor deletion

- src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
- src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Next week the EU TCP Logging endpoints are going live. These are the two references I could find in the docs indicating they were US-only.
> Logging TCP endpoint available in EU

- src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
The Java Log Extension only works with Log4J2 2.13.2 or higher.
> Update minimum version of Log4J2

- src/content/docs/apm/agents/python-agent/python-agent-api/backgroundtask-python-agent-api.mdx
This adds a sentence to the Python Agent's Background Task API to clarify the usage of the background task usage.
> Add clarifying callout for the background task usage for Python Agent

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
As reported in #5479. There's no replacement for the link, so I'm removing it.
> Removing broken link in Python config doc

- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
- This PR updates the nri-kafka supported version to 3.0. This is thanks to the release of the last version of nri-kafka that supports it.
> Bump kafka supported versions to 3.0

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Just adding this NRQL to the percentage function
```
FROM Transaction SELECT percentage(count(*), WHERE error is true ) AS 'Error Percent' Where host LIKE '%west%' EXTRAPOLATE
```
> Adding an example to Percentage function

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9300.mdx
Add a bug fix that we forgot to document in the .NET agent 9.3.0 release notes.
> Add a bug fix to .NET agent 9.3.0 release notes

- src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md
The core users release 'What's new?' post was merged to develop and then reverted, and this is a reversion to restore the post. 
Any tagged reviewers can ignore this; this doesn't need review.
> Revert "Revert "Core user type What's New post""

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring.mdx
* The image base on CentOS is not offered anymore (this was migrated long time ago).
* Removing references to old image.
> fix(docker): remove reference to old CentOS image

- src/nav/synthetics.yml
The link to the Synthetics API was broken in the left navigation. Evidently, the Synthetics API was moved to APIs, so the new navigation link point to this location: https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api/
This is from GitHub issue #5609.
> Fix broken API link in left navigation

- package.json
- plugins/gatsby-source-nav/gatsby-node.js
- yarn.lock
Updates site to gatsby v4.4 cuz why not.l
Updates the gatsby-plugin-source-nav to migrate from methods on `nodeModel` that are deprecated and will be unsupported in v5.
Related to #4571 
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#nodemodelrunquery-is-deprecated
> Update deprecated methods, upgrade to latest gatsby minor version

- src/content/docs/alerts-applied-intelligence/transition-guide.mdx
Reverts newrelic/docs-website#5640
Accidentally merged this one into develop before the checks completed. (Using a VS Code extension)
> Revert "fix(Alerts): Update EOL date"

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Work based on https://github.com/newrelic/docs-website/issues/5624. Making the 'Not supported' aspect of the compatibility table more clear.
> fix(java compat): make 'not supported' more clear

- .github/workflows/check-translations-and-deserialize.yml
- scripts/actions/__tests__/fetch-and-deserialize.test.js
- scripts/actions/__tests__/send-and-update-translation-queue.test.js
- scripts/actions/check-job-progress.js
- scripts/actions/fetch-and-deserialize.js
- scripts/actions/send-and-update-translation-queue.js
- scripts/actions/translation_workflow/database.js
Key changes:
* files are downloaded in batches of 50. previously this was limitless, and we were running into errors because of this.
* the batching change fixes the original bug, but I also added in a response check & console log for if we run into responses that aren't HTTP 200s.
* partial success & failure is now possible in the `fetch-content` jobs.
* files are deserialized individually, and errors are caught and console logged out.
* translations that download & deserialize correctly will be marked as `COMPLETED` in the DB. these will be subsequently cleaned up in the removal step / script.
* translations that do not deserialize / throw during deserialization are marked as `ERRORED`. for the moment, these require manual updates to the file and we should treat these as NOT replayable …
> changes to machine translation for handling partial success, partial failure, batching

- src/content/docs/apis/nerdgraph/examples/export-import-dashboards-using-api.mdx
Also update the `dashboard` query variable to match the mutation.
While working through this example to import a dashboard, I noticed that the type of the `$dashboard` variable declared in the mutation did not match the expected type in NerdGraph. I also noticed that the `dashboard` property in the query variables JSON needed to be updated to match the variable in the mutation.
Ideally, it would probably be good to update the corresponding screenshot as well, but I wasn't sure if y'all wanted to handle that yourselves. 🙂
> fix(NerdGraph): Use correct DashboardInput type

- scripts/actions/check-for-outdated-translations.js
- scripts/utils/constants.js
We can just remove the check for `modifiedFiles` here.
The script takes the english path of the file and checks if there is a corresponding locale file, in any of the specified locales
If an english file is removed we also want to make sure any locale versions are removed, so we flag that
This is essentially deleting a file and recreating it in a different location, so we want to check any locale versions that match the original location are deleted/moved/renamed
This is currently checking to see if the `translate` frontmatter has been removed. This is also essentially the same as deleting the file because we want to flag the locale file(s) to be removed too.
However, now we don't need to. If a file has `translate: jp` it will be `Human Translated` in japanese and `Machine Translated for …
> chore: remove check for modified translations

- src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-and-dt.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-ios/get-started/new-relic-ios-and-dt.mdx
- src/nav/mobile.yml
For historical reasons, the Android doc about DT also contained the iOS information. Now, it is time to separate the two.
I did the following:
* Created a separate iOS distributed tracing page based on the original Android page. 
* I renamed the original Android page to clarify it and added a redirect.
* Removed references in each file so they only talk about Android or iOS.
* Added a navigation link for the iOS page.
> Move iOS information out of Android DT doc and into separate doc

- src/content/docs/codestream/start-here/what-is-codestream.mdx
It seemed important to add this redirect.
> fix(CodeStream): Add redirect for top-level codestream path

- src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
Added a link to private location details in the callout about monitoring sites behind your firewall.
The current content implies that opening ports is the only option to monitor sites behind your firewall. This adds the private locations feature to the callout.
> fix(synthetics): add private locations reference

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
This was related to DOC-7619, removal of Insights insert key refs. In the synth API test docs, we had an Insights Query API example. Removed that and added a nerdgraph example.
> fix(synth api tests): remove insert key, add Nerdgraph

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
This PR removes a tip included in the Python Agent proxy setting config details. The tip is being removed because it contains outdated information and references an agent version that is nearly four years old (support window).
> Remove outdated tip from Python agent proxy config docs.

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx
Directions stated replace `YOUR_LICENSE_KEY` and command had `LICENSE_KEY` - changed the latter to match the directions and for uniformity, changed `ACCOUNT_ID` to match the same pattern. 
Double checked with the lambda team here https://newrelic.slack.com/archives/CJGUKK42D/p1642526497107600 
Thank you!
> fix: Correct directions to match command

- src/content/docs/kubernetes-pixie/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx
`nri-metadata-injector` changed to `nri-metadata-injection`
Typo in docs.  `nri-metadata-injector` should be `nri-metadata-injection`.
> Fixed typo for helm chart name

- src/content/docs/apm/agents/python-agent/python-agent-api/recordcustommetric-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/recordcustommetrics-python-agent-api.mdx
This PR adds a "View and use custom metrics" section to the Python agent `record_custom_metric` and `record_custom_metrics` API guides.
> Add custom metrics usage section to Python API guides.

- package.json
- yarn.lock
Updates the theme which brings in a change to dynamically render the copyright year in the footer
closes https://github.com/newrelic/gatsby-theme-newrelic/issues/625
> Update theme and copyright year in global footer

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start.mdx
The previous grpc exporter for Node was deprecated.
> Replace link to latest grpc exporter for Node.js

- src/content/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent.mdx
Add more info to the php docker docs page. This consolidates some important information to a page where it will be easier to find.
> feat: php docker page add extra callouts

- src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
The way to manage APM metric timeslice ingest is via metric normalization rules, not via NRQL drop rules.
Leave a pointer to the normalization rules docs in the overview page for dropping data using NerdGraph.
> Mention metric normalization rules for dropping data

- src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
A recent change added that link, but it has a typo in the document path.
> Fix typo in link to metric normalization rules page

- src/content/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic.mdx
There's an inconsistency a customer brought up this week in our documentation. A stated at the very bottom of this doc link here: https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial/, we do not mention browser entities, only APM-APPLICATION, EXT-SERVICE, and REF-REPOSITORY. 
I followed up with engineering to confirm here: https://newrelic.slack.com/archives/C28SEP2LR/p1642786630179500
It sounds like this ability may be coming soon to NerdGraph, see thread for context.
links to related docs, …
> NerdGraph will not delete browser apps

- src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
- src/content/docs/alerts-applied-intelligence/notifications/intro-notifications.mdx
- src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
- src/content/docs/apm/agents/c-sdk/install-configure/install-c-sdk-compile-link-your-code.mdx
- src/content/docs/apm/agents/c-sdk/install-configure/update-your-c-sdk-library.mdx
- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
- src/content/docs/apm/agents/java-agent/troubleshooting/gather-troubleshooting-information-java.mdx
- src/content/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net.mdx
- src/content/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs.mdx
- src/content/docs/apm/agents/php-agent/advanced-installation/use-newrelic-install-script-php.mdx
- src/content/docs/apm/agents/php-agent/getting-started/introduction-new-relic-php.mdx
- src/content/docs/apm/agents/php-agent/troubleshooting/submitting-troubleshooting-results-php.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/migration-7x-guide.mdx
- src/content/docs/distributed-tracing/troubleshooting/missing-trace-data.mdx
- src/content/docs/infrastructure/infrastructure-integrations/get-started/introduction-infrastructure-integrations.mdx
- src/content/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-infrastructure/no-data-appears-infrastructure.mdx
- src/content/docs/infrastructure/microsoft-azure-integrations/get-started/introduction-azure-monitoring-integrations.mdx
- src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
- src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
- src/content/docs/logs/troubleshooting/no-log-data-appears-ui.mdx
- src/content/docs/mlops/integrations/aporia-mlops-integration.mdx
- src/content/docs/mlops/integrations/aws-sagemaker-mlops-integration.mdx
- src/content/docs/new-relic-partnerships/partner-integration-guide/getting-started/support-resources-new-relic-partners.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/troubleshooting/not-seeing-data.mdx
DOC-7645. Attempts to remove as many references to auto-index/category URLs as possible. This was focused on troubleshooting docs but a few other things, too.
> Remove auto-index/category docs views/URLs

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
The /charts path redirects to our old chart, but that is no longer maintained.
> fix helm chart link

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-840.mdx
Updates for Ruby agent v8.4.0 release
* Added new version specific CHANGELOG info
* Listed Rails 7.x as a supported framework
> Ruby agent v8.4.0

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/noticeerror-net-agent-api.mdx
This PR adds some clarification regarding the expected behavior of custom error reporting with the `NoticeError()` API vs. agent configuration to ignore HTTP status code errors.  The API takes precedence; we had a support ticket with a customer who was expecting the opposite so hopefully this helps clear up the ambiguity.
> .NET agent: Clarify custom error priority over configured ignored status codes

- src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
Attempting to prevent customer confusion. These keywords were never supported. However, New Relic didn't prevent users from supplying them. The data demonstrates confusion on how this feature works. We are updating the documentation now and we will prevent these rules from being created in the future.
> SINCE, UNTIL, and LIMIT not supported

- src/content/docs/network-performance-monitoring/troubleshooting/snmp-polling-missing-metrics.mdx
updating one of the NPM troubleshooting docs to add notes about new logs that are available from the **ktranslate** container.
> chore: adding notes based on new ktranslate logs available

- src/content/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking.mdx
- src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx
In response to some customer feedback, this PR updates our description of how the cookies the Browser agent stores behave. It clarifies the behavior of cookies when multiple sites open on a user's browser have the Browser agent running. A corresponding change is being made in the UI to clarify this same behavior.
> Clarify the Browser agent cookie behavior

- src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx
Errors inbox is now available in the EU. This removes a reference saying it is not.
> fix(errors inbox): remove EU callout

- src/content/docs/kubernetes-pixie/kubernetes-integration/link-apps-services/tutorial-monitor-redis-running-kubernetes.mdx
Sounds like Redis is moving to using "replica" instead of "slave", see https://redis.io/commands/SLAVEOF
(This is Mary Ann from the Virtuoso team at NR, using my personal GH account.)
> * What problems does this PR solve?
Removes outdated and potentially offensive language.
> chore: Update redis tutorial to use "replica"

- scripts/actions/fetch-and-deserialize.js
- scripts/actions/utils/docs-content-tools/i18n-exclusions.yml
Fixes an issue where in the `deserializeHtmlToMdx()` the `completePath` had a trailing slash before `.mdx` like so:
```
src/content/docs/path/to/file/.mdx
```
That path won't match with that file's `slug` value in database:
```
src/content/docs/path/to/file.mdx
```
That `completePath` is returned by that method in the `slug` field to do other stuff, including updating the DB. It wasn't matching on `slug` and thus not updating the database and thus was returning an empty array that caused the error.
This also re-adds empty `excludeType` to MT exclusions YAML file because i noticed a warning in the console when trying to use that field in determining if a file should be queued up for MT.
Closes https://github.com/newrelic/docs-website/issues/5842
> [i18n] Fix erroneous slash in path used in database where clauses

- src/content/docs/logs/log-api/introduction-log-api.mdx
Authentication has been a source of confusion for users trying to directly utilise the Log API. Clarified the two available options and restructured slightly to make it clearer, as well as tidying up the examples.
> Clarified authentication options

- src/content/docs/kubernetes-pixie/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx
The list of environment variables that are required for the k8s-apm linkage is hidden at the bottom of the page as an example of what to look for. Also, the example is missing the deployment related env var because it creates a pod directly.
> feat: Add metadata injection list of env vars in link-your-applications-kubernetes.mdx

- src/content/docs/release-notes/service-levels-release-notes/service-levels-20220127.mdx
- src/content/docs/service-level-management/faqs-slm.mdx
Update the docs since now SLO periods in service levels only include complete weeks.
The changes include a new section in the release notes from the January 27 and a new question in the FAQs.
> docs(ServiceLevel): SLO periods now include complete weeks

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
User mgmt liaison work: clarifying log mgmt capabilities with improved footnote. Also removed separate 'logs in context' entry as having two logs entries was confusing IMO.
> User type capabilities: clarify log mgmt capabilities

- src/content/docs/apm/apm-ui-pages/monitoring/external-services/external-services-intro.mdx
- src/content/docs/data-apis/manage-data/view-system-limits.mdx
- src/content/docs/distributed-tracing/concepts/distributed-tracing-planning-guide.mdx
Reviewer, could you look at the following changes?
* In the introduction, I switched two sections around to highlight when you would use the feature.
* In the distributed tracing planning guide, I removed a collapser that had a warning that used to apply when you would enable DT. This is no longer applicable.
* In the limits topic, I removed an out of date comment about limit agreements for DT (per SME).
> External services fast-follow changes

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
A proposition to update the ubuntu releases to match the ones on the official site for release cycles https://ubuntu.com/about/release-cycle
The reason behind this is because as someone knew to ubuntu and using ubuntu, I am familiar with the official releases. I thought that since it confused me at first, looking at the NR docs, it may confuse others also. 
If there is a particular reason why the names are as they are on the docs please let me know. :) 
I am unsure if having the quotes is better or not. If you want them I can put them back in :) So it is consistent with the rest of the documentation. What is the reason behind the quotations? 
Thank you!
in your commit messages and pull request …
> Update Ubuntu release names to match the official

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Confusion arises when customers see that:
- We have a list of non-compliant services where Synthetics is not listed.
- We have a list of compliant endpoints where Synthetics is also not listed.
This callout helps to clarify that this list of FedRAMP compliant endpoints is for services who's main endpoint is non-compliant. If a service's endpoint is not listed here and is not a non-compliant service, then it is compliant.
If this doc edit needs approval from New Relic Security, let's do that.
> Add important callout for endpoints not listed

- jest.config.js
- package.json
- scripts/actions/__tests__/__snapshots__/serialize-mdx.test.js.snap
- yarn.lock
Downgrades `rehype-format` back to 3.1.0 to keep using CommonJS `require()`'s.
Tested uploading via `scripts/actions/translation_workflow/testing/script.sh` and it completed successfully.
Not sure we're quite in a place to switch over to ESM.
Closes https://github.com/newrelic/docs-website/issues/5905
> chore: downgrade rehype-format to fix workflow send content error

- src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-span-attribute-trace-filter.mdx
There was a question as to whether all or any rules needed to match for a filter to be applied. This aims to make that more clear.
Answers a question a real user had by clarifying how Span Attribute Filter Rules work in Infinite Tracing.
> feat(Infinite Tracing): Update Rule Priority text for span attribute filters

- src/content/docs/alerts-applied-intelligence/overview.mdx
As requested in #5897.
After checking with @paperclypse, we're only addressing the first item in the issue. As for the second comment (In the Alerts (classic) section, the Events is separate from Incidents, and in the docs it looks like it's one UI section), it's meant to look like this.
> fix(Alerts and AI): Shortening title

- src/content/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing.mdx
This PR clarifies that agents sample up to 10 traces per minute at the trace origin, not 10%.
These existing docs clarify how adaptive sampling works: [trace origin sampling](https://docs.newrelic.com/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works/#trace-origin-sampling)
> Update wording to clarify the impact of adaptive sampling in agents

- src/content/docs/licenses/overview.mdx
Fixes a broken link due to turning off index pages.
Reviewer, please double check that the new link is the best place to send users to. There wasn't a perfect location, and this seemed the best one.
> fix: broken link to category page

- .github/workflows/update-whats-new-ids.yml
This updates the whats new ID generating workflow to commit new IDs to the branch PRing main instead of develop
closes https://github.com/newrelic/docs-website/issues/5927
> Use release branch for whats new ID commits

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
Pricing docs liaison work: it was realized what we had about downgrade rules for APOF core pricing needed clarification.
> fix(core user rules): clarifying apof downgrade rules

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Changed aggregation window max value references to 120 minutes
> Agg. window now has max value of 120m

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start.mdx
- Adds new section called "A note about endpoints" that per Otel spec, when using a per-signal env var, it is required to set the endpoint URL ending in either `v1/traces` or `v1/metrics` (not doing so will result in a 404)
- Also fixes the Infinite Tracing row in the table
- Adds link to the new section in the config section above the table
> Specify condition when using per-signal env var

- src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-group-results-across-time.mdx
When charting a time function, if you don't specify "until", the StackBar chart may split time into concatenations.
I have described how to specify "today" or "this month" with until.
> Added advice on creating charts with time functions.

- src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
Removed these metrics where not being generated by the integration:
```
exchange.messagesDeliveredAcknowledged
exchange.messagesDeliveredAcknowledgedPerSecond
exchange.messagesConfirmed
exchange.messagesConfirmedPerSecond
exchange.messagesRedelivered
exchange.messagesRedeliveredPerSecond
exchange.messagesReturnedUnroutable
exchange.messagesReturnedUnroutablePerSecond
exchange.messagesPublished
exchange.messagesPublishedPerSecond
```
Added this metrics that were not documented:
```
node.fileDescriptorsTotal
node.processesTotal
node.processesUsed
node.fileDescriptorsTotalSockets
node.partitionsSeen
```
* Add any …
> Fix metrics from Rabbitmq integration

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
Added clarification that optional metadata settings in AWS = attribute/value pairs in New Relic
> fix(Logs Kinesis Firehose): CF-10272

- .github/workflows/update-whats-new-ids.yml
Reverts newrelic/docs-website#5948
we have an odd merge commit getting added by this action. we're not sure if it's causing stalled builds yet but i'm going to revert this for now. whats new IDs will go back to being committed to develop
> Revert "Use release branch for whats new ID commits"

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/streaming-alerts-key-terms-concepts.mdx
Buffer has been updated to 65m, so changed this callout
> Change callout to match reality

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
Line 41 currently doesnt show on Public Docs but I didnt add that line.
"Any optional key/value pairs you add in the AWS Management Console will result in attribute/value pairs you can use in New Relic."
> Attribute Parameters to Identify Destinations

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-windows.mdx
- src/i18n/content/jp/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
- src/i18n/content/jp/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-windows.mdx
- Replaces `K8` with `K8s` in page meta descriptions.
It was making link previews look bad.
> k8s: replace `K8` with `K8s`

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3.mdx
The page we dedicated to explain the changes for the new Kubernetes integration version did not have a section explicitly saying how to upgrade from v2. This PR adds this.
While this is slightly duplicated, as it is in fact the same command that can be found in the "install integration using helm" section, we thought it was worth adding it to encourage users to jump to action right away, rather than making them search _how_ to upgrade elsewhere.
> k8s/changes: add an upgrade from v2 section

- .github/workflows/update-whats-new-ids.yml
This is a take 2 to solve our whats new ID commit issue. Currently the workflow commits to develop but we'd like the IDs committed to the release branch. The previous attempt was adding an odd merge commit but this iteration specifies the checkout branch as the head and appears to have solved the issue in tests
- https://github.com/newrelic/docs-website/pull/5948
- https://github.com/newrelic/docs-website/pull/6034
> Update branch committed to by whats new ID workflow

- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
The optional configuration step had a dead link in the trace observer setup. This will all get replaced shortly by a larger set of doc changes, but this is a short-term fix.
I am out of the office on 2/10/2022, but if this looks good, you can publish it for me.
> Fix broken configuration link in trace observer doc

- src/content/docs/accounts/accounts/saml-single-sign/saml-service-providers.mdx
In the Original User Model all users are either authenticated via Username/Password, or via SSO. There is no option for a portion of users to auth one way and another portion to auth the other. 
the doc contained reference to "Read about an option to have users bypass SAML SSO if they use domains you own."  there is no way to bypass SSO. What users are bypassing is the requirement to verify their email address. Hopefully this PR clarifies that. :)
> fix inaccuracy

- src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
It listed "Errors inbox" twice as what not to do. It should be "Errors Inbox" and "Errors inbox"
> fix: missing capitalization use case

- src/content/docs/apis/nerdgraph/examples/apm-config-nerdgraph.mdx
This is apparently related to a change that's coming out now with NerdGraph and effects are restrained just to this doc. - @zuluecho9
> Update apm-config-nerdgraph.mdx to hoist guid to root level on update mutation.

- src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
Updating documentation ahead of general release of attribute drop rules for dimensional metric rollups.  Also adding a little more detail about why we are running the two queries in the example.
> Remove beta tag and a bit more detail in example

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
* fix a typo in the name of an option , dedupe should have been dedup
> Fix typo in no_dedup option

- src/content/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring.mdx
The installation tiles were pointing to pages in New Relic One that don't exist anymore.
> fix(Infrastructure): Removed broken installation tiles

- src/data-dictionary/events/PageView/appName.md
- src/data-dictionary/events/PageView/pageRenderingDuration.md
- src/data-dictionary/events/PageView/pageUrl.md
- src/data-dictionary/events/PageView/regionCode.md
- src/data-dictionary/events/PageView/webAppDuration.md
- src/data-dictionary/events/PageViewTiming/elementId.md
- src/data-dictionary/events/PageViewTiming/elementSize.md
- src/data-dictionary/events/PageViewTiming/elementTagName.md
- src/data-dictionary/events/PageViewTiming/elementUrl.md
- src/data-dictionary/events/PageViewTiming/firstInteraction.md
- src/data-dictionary/events/PageViewTiming/networkDownlink.md
- src/data-dictionary/events/PageViewTiming/networkEffectiveType.md
- src/data-dictionary/events/PageViewTiming/networkRtt.md
- src/data-dictionary/events/PageViewTiming/networkType.md
As part of our upcoming release, the Browser agent will now include:
* Information about the element that caused a largestContentfulPaint event
* Information about the current network connection when largestContentfulPaint and firstInteraction events occurred.
Both of these attributes give customers more context on the state of the application when these events occurred. Both new data sources also have equivalent MDN documentation, which is linked in each individual attribute description:
* Element information comes from existing LCP event we capture: https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint
* Network information is captured from the NetworkInformation API and appended to the events when they occur: …
> Add upcoming PageViewTiming network and element attributes to data dictionary

- src/content/docs/apm/agents/nodejs-agent/troubleshooting/generate-trace-log-troubleshooting-nodejs.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-aws-lambda-monitoring.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/troubleshooting/troubleshoot-enabling-serverless-monitoring-aws-lambda.mdx
As reported in DOC-7631.
This commit adds exception for `trace` logs for Lambda.
> [DOC-7631] Node.js Lamba logs

- scripts/actions/utils/handlers.js
- src/content/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal.mdx
A translation workflow ran recently to send for human translation and we discovered two files that failed to serialize due to HTML elements being used that we don't have handlers for:
- `div`
- was used to wrap an `img` with a set `width`
- unnecessary since you can style the img directly
- `sup`
- used for footnotes
- added a handler for this since it's a useful component to have
Related to https://github.com/newrelic/docs-website/issues/6150
> Fix unserializable components

- src/content/docs/apm/agents/net-agent/net-agent-api/noticeerror-net-agent-api.mdx
Some indentation was off, changed `var` to `string` which is preferred in strongly typed C# and added C# land identifiers for syntax highlighting.
> docs: add lang identifiers, clean up syntax and indentation

- src/content/docs/style-guide/formatting/code-examples.mdx
Noticed that we had lost some old `<var>` and `<mark>` info during migration so added some of that to style guide doc.
> fix(style guide): add old var & mark detail

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
- src/content/docs/network-performance-monitoring/advanced/ktranslate-container-management.mdx
- yarn.lock
adding notes for new environment monitor option on ktranslate container that supports round-trip time (RTT) monitoring
> chore: adding new env var for NPM container

- src/content/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration.mdx
EXTERNAL launch type is now referred as ECS Anywhere
FARGATE launch type is now referred as AWS Fargate
> Small changes on names

- src/content/docs/service-level-management/create-slm.mdx
We've noticed that the suggested queries for the Browser app availability service level are not working well. The reason is that one Page View event can generate more than one Javascript error event, therefore the number of bad events is not always a subset of valid events. Until we come up with a better option, we're removing this section (I'm commenting the content so we can reuse it quickly if needed).
> Remove the availability SLI for browser apps

- src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx
the code blocks were rendering incorrectly, I believe because of the indentation in the file before the triple backticks
> docs: add land identifier and fix indentation

- src/content/docs/mlops/bring-your-own/mlops-byo.mdx
A few code sections aren't using proper copy-pastable code blocks.
> style(MLOps): Use proper code blocks

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-opentelemetry-data-new-relic.mdx
This is work for Jira doc-7771. We have some new features on the OTEL JVM page.
Reviewer: Here's what I changed:
* Inserted new text to augment the existing text in the JVM page.
* I segmented some sub-tasks using new collapsers. See if those collapsers make sense.
* The final collapser has some detailed instructions. Is this clear?
> Add new OpenTelemetry JVM UI details

- src/content/docs/apm/agents/net-agent/custom-instrumentation/custom-instrumentation-attributes-net.mdx
I also made the indentation 4 spaces everywhere instead of a mix of 2 and 4. I also removed the unhelpful `<var>` stuff from codeblocks, I did that because it confuses the language syntax coloring where it's used.
> docs: add language identifiers

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Optional Vars section link went to the section above it.
> docs: fix link to Optional Vars & +lang indentifiers

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Many of the support requests that the Logging team receives are related to the Infrastructure Agent's log forwarder. The log forwarder, based on Fluent Bit, allows the customer to define a totally customizable external configuration file, which is out of the scope of the support provided by New Relic. In this PR we include a PR informing of this, as well as instructions of how to upgrade/downgrade Fluent Bit to a particular version.
> Add documentation to upgrade/downgrade Fluent Bit and support disclaimer

- src/content/docs/codestream/how-use-codestream/pull-requests.mdx
- src/content/docs/codestream/start-here/codestream-new-relic.mdx
- src/content/docs/codestream/troubleshooting/git-issues.mdx
We don't actually support open-in-IDE for lambda errors, so removed that reference. Also removed extraneous spaces in git-issues article.
> Remove reference to lambda

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx
One codeblock was missing the sql language identifier so I added it in.
> docs: added lang identifier

- src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
Clarified user types that have access to synthetics and added a link to the user comparison table for more details.
The existing documentation could cause confusion around which user types have access to synthetics. The update reflects that only full platform users will be able to access the synthetics UI.
> docs: clarified user types that have access to synthetics.

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-8-0.mdx
chore: Adds Node.js agent v8.8.0 release notes.
> chore: Adds Node.js agent v8.8.0 release notes.

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Added a section in the docs for a new option for users where they can automatically send OHI logs to NR by simply renaming an .example file. The mysql-log.yml.example file is already in the nri-mysql repo.
> Added Automatic OHI Logging

- src/content/docs/apm/agents/go-agent/instrumentation/instrument-go-segments.mdx
The `if` had a stray comma at the end of a line I removed, I also added language identifiers for go.
> docs: remove stray `,` from codeblock

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start.mdx
* We had a custy use the wrong endpoint for where their account is based, as it doesn't specify in the doc to use the endpoint for where your account is based, and were unable to see data in NR1.
> Add a note that the endpoints are region-specific

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Bad query example, since there was no actual FACET clause in the inner query. I edited it and also added quotes around the string value that must have quotes. I also used a real event type (SystemSample) for the example instead of a pretend one, as well as changing the attribute to match one on that event type.
> Query would not have worked and is not faceted

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
Update K8s 1.21+ callout to point to the 3.0.61 release of the minion or newer.
Compatibility issues with K8s 1.21+ have been resolved. The documentation should be updated to point users to an appropriate version of the containerized private minion (CPM).
> docs: Update K8s 1.21+ callout

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9600.mdx
* Adds new release notes for .NET Agent v9.6.0.0.
> Chore: Add release notes for .NET Agent v9.6.0.0

- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-850.mdx
Updates for the Ruby agent v8.5.0 release
• Added new version specific release notes
• Updated the list of supported JRubies to include v9.3.x
• Denoted configuration parameter additions and deprecations
> Ruby agent release v8.5.0

- src/content/docs/distributed-tracing/concepts/quick-start.mdx
- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
This is a PR to introduce the new EU region and to differentiate it from the previous EU region that reports to the US data centers.
As a bonus, I changed the link from the Lambda tile in distributed tracing so it links directly to the page that discusses tracing with Lambda.
> Add documentation for new trace observer region in the EU.

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
the `<var>...</var>` in the bash command was being displayed as part of the command
> docs: fix bash command

- src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx
I just had a ticket where APM Insight set the registry key to this value and I found more references to this key for APM Insight online:
https://www.manageengine.com/products/applications_manager/help/java-transaction-monitoring.html
https://pitstop.manageengine.com/portal/en/kb/articles/unable-to-see-application-after-adding-apm-insight-net-agent-and-getting-failed-to-load-profiler-error-30-11-2020
https://www.site24x7.com/help/apm/dotnet-agent/install-dot-net-core-agent-via-nuget.html
* If your …
> docs: add another profiler to table

- src/content/docs/service-level-management/create-slm.mdx
I'm bringing back the recommended SLI for browser availability. We're including a tweak on the condition, so we only count one error per session. Otherwise, the number of errors could be higher than the number of valid requests.
> Bringing back the browser availability SLI

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
The default `metrics_storage_sample_rate` value is 20
> docs: fix default value for infra agent Storage sample rate

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
This PR adds a small explanation on the buffer size limitation and the need to use GZIP compression to avoid having log messages coming from Firehose rejected.
> Firehose logs: clarification on the buffer size limitation and recommendation to use gzip

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
We are deprecating the sum of value function field for nrql alert conditions.  [See announcement.](https://discuss.newrelic.com/t/end-of-life-for-sum-of-query-results-thresholds/176182)  So we'd like to remove the related documentation.  If users want to configure a similar option, they should use `slide by` in the advanced signal section instead.
https://newrelic.atlassian.net/browse/AINTER-8207 
https://discuss.newrelic.com/t/end-of-life-for-sum-of-query-results-thresholds/176182
> feat(alerts): remove deprecated "sum of" field for nrql alert conditions

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx
There was a typo in step 5, so the header was being displayed as: 
> Step 5: View your data in the New Relic UI [view-data]
and the link to `view-data` didn't work.
> fix: typo in #5 header link

- src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-integrations.mdx
* Explanations to help customers disable AWS CloudWatch metric stream integration (requires changes on their AWS account). Feedback from support cases.
> fix(AWS) how-to disable metric streams

- src/content/docs/logs/log-api/introduction-log-api.mdx
- We support any value type for most attributes, updating text to reflect that
- Listing out supported value types
- Removing a now-obsolete restriction that attribute names not have space characters
* Just something we noticed while investigating the data types we support
> Logs API: updates about attribute types

- src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx
* Azure application client secrets can now only be defined with an expiration of 2-years (previously, the "Never" option was available and recommended). Updated with a note explaining how to rotate the secret in the UI or API.
> fix(azure): note about 2-years secret expiration

- src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-03.mdx
Included references to 6.5.4 and 7.5.0+ versions of the Java agent. Please WAIT until we confirm that 6.5.4 has been published (will be later on 3/3) before these changes go live
> Update the log4j security security bulletin to reference newer versions of the agent

- src/content/docs/logs/ui-data/built-log-parsing-rules.mdx
This commit is for the new default parsing rule for Redis. The pattern for this has already been merged.
> New Redis Default Parsing Rule

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
When CentOS 5 End of Service Life (EoSL) was announced, the same announcement should be made about Red Hat Enterprise Linux (RHEL) 5. This PR fixes this inconsistency.
> fix(apm/php-agent) Announce RHEL 5 EoSL in system requirements

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* We cannot support OS beyond the manufacturer EOL. Debian 8 LTS ended Jun-30-2020.
> fix(infra-agent): Debian 8 EOL reached

- src/content/docs/release-notes/service-levels-release-notes/service-levels-20220225.mdx
Fix typo in the service levels release note "service-levels-20220225".
> docs(servicelevels): Fix typo in service levels release notes

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
Fix a few indents to improve manual setup appearance
Link to doc on preview build: https://docswebsitedevelop-austinschaeferpatch348271.gtsb.io/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring
> style(npm): Tweak indents for manual setup

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx
We have had a number of OpenTelemetry tickets where they experienced data being dropped due to exceeding our limits on attributes, but the numbers are not documented in the OTel section. This will make it clear that NR limits also apply to OTLP-sourced data, and include the exact numbers and links to the main limit docs for further perusal.
> Add attribute limits info

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
Work done: 
Made it more clear that basic users and core users have access to a lot of alerting & AI functionality. Clarified how it works in the footnote from the 'alerts and ai' entry in table.
> fix(user type table): edit to alert/AI

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
- src/content/docs/new-relic-one/core-concepts/new-relic-lookout-monitor-your-estate-glance.mdx
Adding small clarification to the Explorer entry in the user type table to say that core users don't have access to deviating signals
> fix(user type): clarifying deviating signals

- src/content/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2.mdx
* Updated docker image examples with "latest" tag instead of 2.0.0 to avoid updating docs for every release (2.1.0 is actually the latest now).
> fix(statsd): recommend latest instead of 2.0.0

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Using `allow_all_headers` as an envvar was introduced in [#1114 of node-newrelic](https://github.com/newrelic/node-newrelic/pull/1114).
> fix(node agent): mention allow_all_headers is now also an envvar

- src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
Changed `customParameters` to `customAttributes` in `noticeError()`. In the [source code that parameter is named `customAttributes`](https://github.com/newrelic/node-newrelic/blob/556543726f350b7c72bd33db3f175b7b1aed4a45/api.js#L417), and `customParameter` is a slightly inaccurate term for the arg. I also added the blurb from the source code describing it's purpose and datatype.
> docs: specify datatype of customAttributes arg

- src/content/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api.mdx
The curl codeblock was indented a little wonky, since I was here I added the language identifiers to the examples as well
> docs: clean up code block

- src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx
Link was pointing to beta.docs and for MySQL. Updated to proper Elasticsearch Advanced Configuration page (non-beta).
> Incorrect Link to Advanced Configurations

- src/content/docs/release-notes/service-levels-release-notes/service-levels-20220311.mdx
- src/content/docs/service-level-management/create-slm.mdx
The 'availability' term has generated some confusion because it usually refers to a service being up and running and able to receive requests. This is why we're renaming the suggested SLI as Success from now on.
I haven't changed the anchor id, to prevent breaking any existing links.
We'll publish a release note as well.
> Rename availability as success (publish 03-11-22)

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
A client wanted to use the same proxy settings, but there's already a clear workaround for gRPC. This closes [#428 of
node-newrelic](https://github.com/newrelic/node-newrelic/issues/428).
> fix(node agent): clarify that proxy settings do not apply to Infinite Tracing

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx
This PR makes it clearer the config settings we recommend to avoid getting rate limited. It also adds more information to the attributes section on how to set max attribute lengths using span limits env vars. Both have been common issues with our OpenTelemetry users.
> Clarify how to avoid rate limiting

- src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-instrumentation.mdx
- src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-metrics.mdx
I added semicolons and language identifiers to the code blocks.
Three code blocks had stray `)`s which were breaking them.
`API#getTransaction` seems like it was maybe supposed to be a link? But it didn't go anywhere so I altered it to just the method name
> docs: format code blocks, fix typos

- src/content/docs/logs/get-started/get-started-log-management.mdx
- src/content/docs/logs/ui-data/data-partitions.mdx
Did this due to issue https://github.com/newrelic/docs-website/issues/6592. Clarifying how roles/permissions work for logs and pointing to that requirements section from log partitions doc.
> fix(logs): clarify roles/permissions

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Removes `ul` and `li` html tags in favor of markdown to fix this serialization error when sending file for translation.
https://github.com/newrelic/docs-website/runs/5547110228?check_suite_focus=true
> fix: remove `ul` elements in favor of markdown

- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
Mostly minor changes:
- Removed most of the anchor links back and forth across the doc in favor of just references. I'm assuming a bit more linear reading here and I worry that the links send people in a circular pattern through the doc.
- Tweak a bit of copy on headings
> style(api keys): Remove most anchor links, simlify some language

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9610.mdx
Add release notes for .NET agent 9.6.1.
> Add .NET agent 9.6.1 release notes

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Attributes config param doesn't take effect when an external Fluent Bit configuration file is specified. Added callout explaining this.
> Added callout about attributes config param

- .github/CODEOWNERS
- src/content/docs/style-guide/writing-docs/article-templates/whats-new-tech-writer-tasks.mdx
It turns out that PMMs who submit "What's new" posts don't need a review from a fellow PMM.
I also replaced on PMM with another in the CODEOWNERS list of reviewers.
> Clarify when PMM review is necessary and add PMM to CODEOWNERS

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
Adding note to API key 'license key' section about ability to restrict access to that api key. 
Also adding notes to roles/capabilities docs recommending checking out capabilities UI to better understand roles.
> fix(api keys): adding note about capabilities

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
This value can be any valid integer but the server won't handle over 10k. This note was taken from the config docs in node, the same rule applies here.
> docs: add upper limit to maximumSamplesStored

- gatsby-config.js
We left the browser agent entity for the docs site in the nr1 dev experience account, now we are moving it to our docs eng account, this updates the info
> Update browser agent creds 

- src/content/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api.mdx
One line was not indented, so of course I went in and indented the whole thing more cleanly, and added identifiers to the curl command.
> docs: indent curl block, add land identifier

- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
We've never had a list of trace observer region, so this PR adds the list in two places in the trace observer doc:
* In the APM/OTEL section
* In the browser, mobile, and lambda section
This will take some work to maintain, but I think it's easier for readers to find the information right when they need it.
REVIEWER: 
This just needs confirmation that it is readable. I don't need a review of the who document.
> Add trace observer region list

- src/content/docs/licenses/overview.mdx
The licenses doc had a few links to the old automatic index pages, I'm fixing them here.
> Licenses: fix broken links

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx
* Added explanation on APM events limits to optimization section
* Discussion with Nic Benders explained how this is used in New Relic's own monitoring practices use this to reduce volume.
> chore(oma-datagov): 

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
The xml example was pretty clear, but I specified in the text that the `name` attribute belonged to an unmentioned `application` element, not the parent `applications` element. It's `instrumentation.applications.application.name`.
> docs: application contains name attribute, not applications

- .github/CODEOWNERS
- .github/workflows/check-translations-and-deserialize.yml
- .github/workflows/update-whats-new-ids.yml
- CONTRIBUTING.md
- Created new [Docs Engineering Team](https://github.com/orgs/newrelic/teams/docs-engineering/)
- Added team as Admin to [Docs Site](https://github.com/newrelic/docs-website)
- Update `CODEOWNERS` file
- Remove references to `Developer Enablement` and updated to `Docs Engineering`
> Slightly blocked by #6566 to update the `CONTRIBUTING.md` with the correct slack channel
> Code owner changes and team reference update

- src/content/docs/licenses/product-or-service-licenses/new-relic-mobile/ios-sdk-new-relic-mobile-licenses.mdx
3rd-party component `mod-pdxproj` doesn't appear to be used anymore. Remove its reference from the [iOS docs license page](https://docs.newrelic.com/docs/licenses/product-or-service-licenses/new-relic-mobile/ios-sdk-new-relic-mobile-licenses).
> Remove license reference to unused 3rd-party lib

- src/content/docs/apm/agents/net-agent/installation/install-net-agent-linux.mdx
Two main changes to the .NET agent install instructions for Linux:
1. Switch to specifying `https://` URLs for the APT and YUM package manager configuration options instead of unsecure `http://` URLS.
2. Clarify the yum/rpm install instructions for rpm-based Linux distros (e.g. RHEL, Centos, etc.).  You can install using the package manager (YUM, which requires configuring the YUM repository) or with RPM (which requires downloading the .rpm file directly from the downloads site).  This mirrors the APT/DPKG (.deb) distinction that already exists for Debian-base distros (e.g. Ubuntu).
I hope I got the formatting right, please fix it if I didn't.
> Improve .NET agent install instructions for Linux

- src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/android-agent-configuration-feature-flags.mdx
This broken link was found by an internal contributor.
> Correct Android link to distributed tracing

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx
* Add RDS Enhanced to the list. 
* Clarifying there are other two types of integrations beyond metric streams.
> fix(aws-stream): integrations not replaced

- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
The cURL commands has `<var>` around the vars reading as plain text, I removed them and formatted the codeblock a little while I was here, also some minor indentation in the file which won't have any effect on the live page. I also replaced the text `<var>`s with just backticks which accomplish the same thing.
> docs: remove <var>s appearing as plain text

- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Adding an entry for permissions needed by the last query in the custom query file. The last query allows for query-level metrics and is critical for some customers.
> Added permissions for the custom query file

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
- src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
- src/content/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management.mdx
Work done: 
Adding Google to v2 SAML SSO doc
Correcting onelogin link in v2 SAML SSO doc
Improving some readability in the SCIM API intro
> fix(scim): adding google, other things

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
- src/content/docs/glossary/glossary.mdx
A follow-up to https://github.com/newrelic/docs-website/pull/6726. Work done: 
* Added 'account', 'account family' and 'organization' in glossary. 
* Finessed some of the DT additions. Pointed back to the architecture doc for more information from the Infinite Tracing procedure docs.
> fix(DT): add account family glossary

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
Updated default limit for span events sent up per minute from 1000 to 2000. Here is the agent code for this value:
```py
def _environ_as_int(name, default=0):
val = os.environ.get(name, default)
try:
return int(val)
except ValueError:
return default
...
SPAN_EVENT_RESERVOIR_SIZE = 2000
...
_settings.event_harvest_config.harvest_limits.span_event_data = _environ_as_int(
"NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED", SPAN_EVENT_RESERVOIR_SIZE
)
```
[I confirmed this is correct with the dev team in slack.](https://newrelic.slack.com/archives/C0511NL6X/p1648143316224569)
I also added the language types to the codeblocks while I was in the file.
* What …
> docs: update default max span value

- src/content/docs/data-apis/manage-data/view-system-limits.mdx
- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
I confirmed in slack with python devs that this value was not up to date in the python docs: https://newrelic.slack.com/archives/C0511NL6X/p1648143316224569
I have now updated the python config doc as well to reflect the 2000 value.
> docs: python agent is also 2000 spans/min

- src/content/docs/apis/rest-api-v2/labels-examples-v2/create-labels-apps-v2.mdx
Adding EOL warning to a deprecated feature. Jira ticket here: https://newrelic.atlassian.net/browse/ESA-635
> ESA-635 add EOL rest labels

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx
@bradleycamacho 
@jsgithub1 and I caught a few inconsistencies in our OpenTelemetry docs around array support that we are correcting here. Please review. This may be merged at any time.
This is a follow-up task for https://github.com/newrelic/docs-website/pull/6478. Thanks!
> fix: references to OpenTelemetry array support

- src/content/docs/infrastructure/host-integrations/host-integrations-list/f5-monitoring-integration.mdx
our `CA_BUNDLE_FILE` config setting mentions a `USE_SSL` setting that does not exist. This PR removes that.
> fix F5 integration CA_FILE_FILE setting

- scripts/actions/translation_workflow/testing/migrations/20211201221649-test.js
Minor change to the migration file that creates tables/columns in dockerized postgres when running `yarn db:start` to match the column order in AWS postgres (prod). The order matters when trying to import data from AWS into the same table locally.
> [postgres] make importing jobs table from aws db a little easier

- src/content/whats-new/2020/10/monitor-asgi-apps-using-python-agent.md
The Learn more link was pointing to a category level that we can't link directly to anymore. I linked to a prominent doc in that category.
> fix(what's new): Broken link

- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
Capabilities UI had 'user key' added, alongside license key.
> fix(api keys): user key capabilities

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Removed unsupported agent version from log_file as they tend to cause confusion and we do not support those versions of the agent anymore anyways.
> Removed unsupported agent versions from log_file

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
This PR updates the main .NET agent configuration page with new configuration options for application logging instrumentation features.  It contains a link back to a draft of a new document, note that the name and location of this document may change in the next week or so.  I'm not particularly attached to the way I've formatted these instructions so any suggestions would be appreciated.
This is a draft PR and the content should not be published until the next .NET agent release, 9.7.0, which should take place next week.
@barbnewrelic
> Add logging configuration information to main .NET agent config page (publish with 9.7.0)

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/scope-alert-thresholds-specific-instances.mdx
- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/disable-enable-alerts-conditions-using-api.mdx
- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/manage-entities-alerts-conditions.mdx
- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts.mdx
- In response to #6923 
- Amends Alerts REST API docs to refer to `X-Api-Key` (instead of `Api-Key`)
- Cross-referenced against the [API explorer](https://rpm.newrelic.com/api/explore)
> docs(Alerts): Amend 'Api-Key' header to 'X-Api-Key'

- gatsby-config.js
Removing the plugin feature that was adding links to headers via gatsby and creating icons as links that didn't go anywhere:
> fix: remove autoLinkHeaders from md files

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
This is waiting to be published until some time in April. This is documenting a NRQL function accountId() that allows you to return the accounts associated with the data queried. This is currently only for nerdgraph; query builder ability will come later (currently you can only run queries in UI query builder that are constrained by the account you're in but with nerdgraph you can cross account boundaries). 
…-website/commit/567d3b1ea5975e0e12fcdfb7c002087166bfe1c7
* If your issue relates to an …
> AccountId() NRQL function (not yet ready for publish)

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/sc-implementation-guide.mdx
Fixes 15 broken images where the image path deviated from common convention (and other variations we saw).
Related to #6908
> fix: fix markdown images to use new syntax

- src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
- src/nav/telemetry-data-platform.yml
Mostly minor language tweaks, plus inserting several references to MELT to make it clearer that this doc covers the four key observability data types.
> style(data types): Simplify language, add MELT mentions

- src/content/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui.mdx
In the image the three scenarios are labeled A/B/C but in the text they are 1/2/3. This is confusing.
Adds greater clarity by correlating letter-based labels in the image to their descriptions immediately below.
> fix: Update client span duration text labels

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup.mdx
Removing an extra "see" from the FedRAMP blurb + changing the capitalization to match the proper taxonomy/namesake of the regulation.
> Update FedRAMP blurb to fix taxonomy/typo

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71000175.mdx
This PR adds Python agent release notes for v7.10.0.175. It includes a link which has dependency on https://github.com/newrelic/docs-website/pull/6957.
> Add Python agent 7.10.0.175 release notes. (CodeStream integration)

- src/content/docs/codestream/codestream-integrations/slack-integration.mdx
Converts a .gif markdown image to jsx img syntax
> fix: convert md image to jsx img

- src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx
The example on the page 
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration/#example has invalid yaml and copying-pasting it to `winservices-config.yml` does not work
> fix indentation causing invalid yaml

- src/content/docs/apm/agents/net-agent/net-agent-api/noticeerror-net-agent-api.mdx
The comments for the `string message` parameter in the .NET Agent's NoticeError API page refers to a 1000 character limit.   This is not correct (it might have been 8 or so years ago). 
This updates the comment for that parameter to match what my testing has shown to be correct.  We will also be updating the in-code comments to reflect this as well.
> Replace incorrect message limit on NoticeError api method

- src/content/docs/infrastructure/amazon-integrations/troubleshooting/metric-data-delays-amazon-aws-integrations.mdx
We have decided to increase the AWS Cloudfront polling explicit delay to 3 minutes after pulling incorrect data for some customers.
Internal: talk to me in slack 'ihernandez' if you need to see the internal tickets.
The change will be live today in some hours.
> feat(AWS Cloudfront): Cloudfront explicit delay increased

- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
Removes rogue `h3` tags from a file to fix recent serialization error
https://github.com/newrelic/docs-website/runs/5878416593?check_suite_focus=true
> fix: remove h3 tags in favor of markdown

- src/content/docs/codestream/start-here/sign-up-codestream.mdx
Was going to replace it with one that includes the new Region drodown, but instead we'll just remove the image.
> Remove image of signup page

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
The latest Node agents have the aws-sdk bundled with them, so a separate installation and import/require are not necessary.
> Removing the requirement for installing aws-sdk

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Resolves this issue in the .NET agent repo: https://github.com/newrelic/newrelic-dotnet-agent/issues/1050
Some config elements were mis-typed in the initial version of this document.
> Fix config examples in .NET logging doc

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Fix incorrect name of config element (for log fowarding, the name of the config element is just `forwarding`, not `logForwarding`) in main .NET agent config doc.
> Fix name of log fowarding config element

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Update the new application logging feature config options for the .NET agent to include the environment variable config options.  Thanks to @Lonli-Lokli for pointing out this gap in our documentation.
> Document environment variable options for configuring .NET agent logging features

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-best-practices.mdx
Update docs to reflect our explicit lack of support for non-monotonic delta sums.
NR does not support non-monotonic delta sums
Related docs are linked in the doc change
> No support for non-monotonic delta sums

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
A community member pointed out that we fixed the bug where the .NET agent did not report total system memory usage on Linux, and that we should remove this bug from the list of known issues on the compatibility and requirements page for .NET core applications.
> Remove Linux system memory bug callout

- src/content/docs/accounts/accounts-billing/account-setup/create-your-new-relic-account.mdx
- src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx
- src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
Based on customer feedback, and talking with support, changing 'simple organization' language with 'unused organization' and making it more clear that if they don't have access to that 'delete org' button, it's because they don't meet the requirements.
> Improve 'delete simple org' wording

- src/content/docs/apm/agents/ruby-agent/background-jobs/monitor-ruby-background-processes.mdx
Adds a suggestion to update Gemfile to use `require: false` and let customers know they can set most configuration options there.
Remove the `newrelic.yml` file from an application, update the gem installation, and try to install it manually by using `manual_start` with some additional configs, such as license key.
N/A... sorta this one: https://github.com/newrelic/newrelic-ruby-agent/issues/1050
> chore: Update `manual_start` instructions

- src/i18n/content/jp/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
This should hopefully fix a 500 error we're getting on https://docs.newrelic.com/jp/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
> MDX adjustments

- src/content/docs/apis/intro-apis/introduction-new-relic-apis.mdx
Noticed that these were quite out of date in terms of recommending REST APIs prominently and not having nerdgraph mentioned in the 'product APIs' section.
> fix(nr apis): fixing out of dateness

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Just adding a bit more context on the distinctions and usage. And changing quotes into code.
> fix(style guide): Add color around agent vs integration

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Recently discovered solution for common Flex integration issue on Windows Hosts running infra agent 1.20.4+ and certain Powershell scripts. Will be adding to Flex docs as well.
> Added PATHEXT env var example for Windows Hosts

- src/content/docs/logs/ui-data/built-log-parsing-rules.mdx
Adding the doc entry for the new Mongodb default parsing rule.
> MongoDB Default Parsing Doc

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx
Link pointed to non-existent URL. Changed link to point to latest scripted browser reference page (Chrome 100, which has links to reference for previous agents as well)
> Changed URL for "Scripted browser reference"

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-baselining.mdx
I found one missing event type in the NrConsumption to Event table.  This was an glaring omission.
> fix(oma-data-gov): Added MobileRequest to NrConsumption table

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
The broken link was: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/new-runtime
To test it, go to this page https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/custom-timing-details/ in the preview and click the link in the top callout.
> fix(Synthetics): Added redirect for a broken link

- src/content/docs/infrastructure/install-infrastructure-agent/macos-installation/install-infrastructure-monitoring-agent-macos.mdx
I tried to install the infrastructure agent on my Mac using the provided steps, however, an error was raised when I tried to do them in the order originally listed: 
```
tee: /usr/local/etc/newrelic-infra/newrelic-infra.yml: No such file or directory
```
This PR changes the steps to be listed in the order that was successful for me.
I was attempting to install the infrastructure agent on my Mac to run a test for the Ruby agent.
> Change installation step order

- src/content/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data.mdx
This PR closes GitHub issue #7168 that points out we had a link to an old table of contents page for all the APIs. Since this no longer exists, I removed the link.
> Remove link to old TOC page for APIs

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/newrelic-metrics-adapter.mdx
- We have moved the chart for the metrics adapter to its own repository.
- The nri-bundle installation keeps working as it was, but the links to the chart needed to be modified.
- We spotted also a wrong path for the accountID path.
> Docs metrics adapter correct AccountID value path and modify chart links

- src/pages/attribute-dictionary.js
Right now we're filtering out the data dictionary page in the search because it has a lot of text and surfaces as a top result often when it shouldn't. This PR adds some content exclusion so we can test if the results come back better
> Limit what gets indexed in the data dictionary

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3861.mdx
Latest release note for the New Relic for iOS mobile app.
> docs: add latest NR for iOS 3.86.1 release note

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
* Local log decoration configuration details are missing from .NET Agent documentation.
* This updates the .NET Agent  configuration page to point to the how-to for setting up log decoration
* Updates the .NET Agent  how-to for log decoration to include basic examples for setting up log4net, Serilog, and Microsoft.Extensions.Logging.
> Expands out missing .NET log decoration documentation

- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
- This PR is fixing wrong name of the msi file and other places where it was pointing to MySQL instead of Kafka
- Remove a zookeeper configuration that is not doing anything in the samples and is prone to error. If the users wants to add the ZOOKEEPER_AUTH_SECRET, they need to add ZOOKEEPER_AUTH_SECRET:digest as explained in the config section, by default that flag is empty so with the provided config it was never honoured, so it's better to remove it.
> Kafka integration fixes

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx
* Im our documentation we specify the mongodb have the memory metrics in Bytes but they are in MiB.
> Add the right unit for MongoDB memory metrics as specified in the docs

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
Added a note about the removal of Selenium WebDriver promise manager / control flow and recommended monitor updates.
> feat(synthetics): Added deprecation notes

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Found a small typo listing infra agent 1.26.0 but linking to 1.20.6
> Update Typo for 1.20.6 Agent Version

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction.mdx
This came about from a user pointing out [here](https://github.com/newrelic/newrelic-opentelemetry-examples/issues/111) that the existing link to our CNCF Slack channel did not work for them, and Tyler H suggested that we make a note that users may have to first sign up for CNCF Slack to access that link. This PR adds that note and the sign-up link.
> Update with note to sign up for CNCF Slack account

- src/data-dictionary/events/NrConsumption/BytesIngested.md
- src/data-dictionary/events/NrConsumption/CoreUsers.md
- src/data-dictionary/events/NrMTDConsumption/CoreUsersBillable.md
Noticed we didn't have coreUsersBillable as attribute in data dict.
> fix(dd): add coreusersbillable

- src/data-dictionary/events/ProcessSample/commandName.md
The characters "<" and  ">" seems that was preventing the code section to be rendered correctly. In addition, the whole "tip" was not rendered, neither the link.
Do you think this would solve the issue?
> fix: full file path not shown

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
- src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx
* Release 1.24.2 of the infra agent is collecting additional EC2 metadata attributes by default. 
* Added some notes documenting which attributes are collected by the agent. Customers can also connect the AWS Cloud Integration for additional metadata (including tags).
> feat(aws): EC2 metadata from the agent

- plugins/gatsby-source-data-dictionary/gatsby-node.js
- plugins/utils/handlers.js
this is kind of a weird one but turns out it was a redux issue not a caching issue???
In the data dictionary service, we create nodes for all the data dictionary events and attributes. When they are updated, we want to make sure the redux store reflects that change. We can ensure that by running touchNode on all data dictionary files.
this section of the gatsby docs on node creation explains it: https://www.gatsbyjs.com/docs/node-creation/#freshstale-nodes
> Sticky not really cache fix for data dictionary

- .github/workflows/manual-add-files-to-translation-queue.yml
- package.json
- scripts/actions/add-files-to-translation-queue.js
- scripts/actions/manual-add-files-to-translation-queue.js
PR to create a workflow to manually add files to the translation queue! Learned about github action inputs here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
I have 0 idea what inputs look like in a github action, and I can't really test this action until after it is merged in. I tested locally by running 
```bash
yarn manual-add-files-to-translate -f "src/content/docs/codestream/how-use-codestream/discuss-code.mdx,src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx"
```
and it worked but since it is dispatched - not run on `push` or for a `pull_request` - it's hard to test the actual action with the inputs
> Create workflow to add files to translation queue by string

- src/content/docs/data-apis/manage-data/view-system-limits.mdx
* Documenting the ingest limit for AWS Kinesis Data Firehose when integrating AWS CloudWatch metric stream.
> AWS metric stream ingest limit

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Removing Fluentd examples because it confuses users and adding the infrastructure agent as default example. It is the fastest way to bootstrap this functionality. Also added link on all the options for log forwarding.
> Removing Fluentd Examples

- src/pages/attribute-dictionary.js
We're going to see how the search results go with only the page title/description and event names
> Ignore indexing of all table data in data dictionary page

- src/content/docs/apm/agents/net-agent/attributes/custom-attributes-net.mdx
Per this [GTSE](https://newrelic.atlassian.net/browse/GTSE-14535?focusedCommentId=1074117), primitive type objects will always work, custom type objects will fail if they haven't implemented `ToString()`.
https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-6.0#extending-the-objecttostring-method
> docs: custom types must implement `ToString()`

- src/content/docs/apm/agents/python-agent/supported-features/cross-application-tracing.mdx
This commit adds a note in the Cross Application Tracing docs that the functionality has been deprecated in the Python Agent.
> Add notice that CAT has been deprecated in Python Agent

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors.mdx
The setProxyAdvanced example was incorrect and would result in an err_no_supported_proxies error. The host, port, and scheme must be defined if using a non default port (varies by scheme) or a non default scheme (http).
> fix(synthetics): Fix setProxyAdvanced examples

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
Golden metrics synthesized by our platform based on public definitions don't count toward usage-based billing. This is not clearly stated anywhere and can result in confusion depending on the tool used to calculate usage. /cc @pfraziernr @jsgithub1
> Clarify billing on publicly-defined golden metrics

- src/content/docs/integration-guide/circleci-guide.mdx
- src/content/docs/logs/forward-logs/circleci-logs.mdx
- src/nav/logs.yml
New guide for circleci/new relic integration.
IMPORTANT: I need help from the dev team to decide where this lives both in the repo and in the website as a whole.
A lot of the template I used came from the existing [cloudflare doc](https://docs.newrelic.com/docs/logs/forward-logs/cloudflare-logpush-forwarding/) since this is a very similar page, only for CircleCI. 
The guide covers 2 main areas:
1. how to set up a circleCI webhook to send logs to new relic
2. what you can do in New Relic with those logs (mainly the quickstart already built)
> feat: new circleci guide (DOC-7895)

- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
Since v3.0.0, the function signature of `@newrelic/winston-enricher` has changed. It now requires passing Winston to the formatter before the formatter can be used.
Context:
- https://github.com/newrelic/newrelic-node-log-extensions/issues/36
- https://github.com/newrelic/newrelic-node-log-extensions/pull/33
> Update docs with new winston-enricher signature

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
NRQL is case-sensitive. Updating example query to correct case of `appName` attribute.
> Small update to correct case of appName example

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/choose-your-aggregation-method.mdx
* The allowable gap between data points, when using event flow, has been updated to 65 minutes.
* This change brings this page in line with the same information found [here](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/streaming-alerts-key-terms-concepts.mdx#L218).
> fix(alerts): update event flow callout

- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx
- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/manage-pixie-memory.mdx
- src/nav/kubernetes-pixie.yml
This PR adds a "Manage the memory used by Pixie" page under the Kubernetes-Pixie section. This page includes info about:
- how Pixie uses memory
- when and how to configure Pixie's memory usage. 
cc @nserrino
Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>
> feat(Pixie): add memory mgmt info

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Many customers are forced to implement infra agents using the tarball installation. Unfortunately, the tarball doesn't contain the td-agent-bit binary (or any other integration), so if a customer still wants to use the log forwarding feature - they are left alone to figure out how to do that. The process is simple enough if you know it, so why not document it :)
> Update logs doc with tarball instruction

- .github/workflows/pr-docs-eng-board-beta.yml
Adds a workflow to add relevant PRs to Docs Eng board.
Had to use different API than other related workflows to triage issues / PRs to other boards because the Docs Eng Board is a beta project board.
The gihutb doc [Automating projects (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects) was helpful
> chore: add workflow to add relevant prs to docs eng beta board

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Health status can be affected by any NRQL condition using a query that scopes signal(s) to a single entity -- this can be done using FACET, but can also be done using a very narrow WHERE clause.
> Add crucial detail to health status

- src/pages/attribute-dictionary.js
- src/utils/constants.js
The page type for the data dictionary is currently being filtered out of search results, this PR updates it to be a non filtered type
> Change data dictionary page type

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx
- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
Adding info regarding Rancher CP monitoring.
Leaving etcd out for now due to the node ip limitation
Please wait as well for a coreint approval before merging.
> feat(K8sRancher): adding info to monitor rancher CP

- src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/eol-cloud-inventory.mdx
* The inventory capability for Cloud Integrations has been deprecated. We are publishing additional details on top of the EOl announcement.
* Multiple docs update will follow-up in the next few weeks to gradually remove inventory docs from AWS/GCP/Azure integrations (this PR is focused on the FAQs).
> Cloud inventory EOL notes

- plugins/utils/handlers.js
Idk what happened but this got reverted so readding this change
> Apply correct classnames for `inline` and `block` images

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-alerts.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-attributes.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-batching.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-compression.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-logs.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-overview.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-resources.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx
Clarify that some docs are related to OTEL, by adding "OpenTelemetry" in the titles.
> Rename some best practices pages 

- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx
- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/manage-pixie-memory.mdx
Adjust wording to make it clear that the minimum memory limit is 1Gi.
> fix(Pixie): fix wording in memory docs

- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
- src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-770.mdx
Doc updates corresponding to the Java Agent 7.7.0 release, which will be published 5/3. Includes:
* New release note page
* Updates to the LiC feature page and the Config page to indicate that LiC is now enabled by default
*  Updates to the Compatibility page to reference support for Java 18
> Java Agent 7.7.0 updates (HOLD FOR 5/3 PUBLISH!)

- src/content/docs/logs/get-started/get-started-log-management.mdx
We need a reference to OpenTelemetry in the logs docs. This is a small start to increase visibility.
> Add OTEL logging references to bullet list

- src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx
Hi team, in ticket ESA-1177 we included a new field lastReportingChangeAt to filter entities. If you join with field reporting you can have this new kind of query.
> Add nerdgraph query with new fields

- src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx
- src/content/docs/data-apis/understand-data/event-data/nrauditevent-event-data-query-examples.mdx
- src/content/docs/data-apis/understand-data/event-data/query-account-audit-logs-nrauditevent.mdx
Replacing wrongful edit with original draft. 
Adding in info about NrAuditEvent and how you can track account changes with that. Added in example of querying about created accounts.
> fix(account nerdgraph): rolling back edit

- .github/workflows/pr-triage.yml
Change label this workflow looks for to `translations` so only PRs back from translation vendors are added to the [board](https://github.com/newrelic/docs-website/projects/4) so we can better keep track of them.
> Only add translation PRs to localization board

- src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
An upper limit was discovered for `application_logging.forwarding.max_samples_stored` This limit is now included in the description.
> chore: specify the maximum value for max_samples_stored

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-logs.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-overview.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx
This is a follow-up to #7043 and updates a repeated callout with new information about our intent to update our supported version of OpenTelemetry Protocol (OTLP). Further clarification to our plans and timeline will be made in subsequent PRs.
> fix: intent to upgrade OTLP notice

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
We recently found out that we don't support metrics for Kafka 3. So removing it.
> chore(java): removing feature that is not supported for those versions

- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
Removing -attachment-endpoint as that's only intended for internal testing
Removing -attachment-key as it is deprecated
> Removing deprecated/internal options

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-attributes.mdx
This is a small one, but both @jack-berg and @TylerHelmuth have noted that sending an OpenTelemetry span with an attribute value containing more than 4095 characters will result in an NrIntegrationError in practice. 🔭
> fix: correct OTLP attribute value length limit

- src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
This PR improves our oracledb OHI documentation for the skip_metrics_groups config option adding an example and link to github detailed doc
> improve oracledb ohi doc with skip metrics example

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-legacy-new-relic-exporters.mdx
The newrelicexporter has been dropped. Updating documentation to reflect status.
See [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9894).
> Update status of newrelicexporter for the collector

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-browser.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-overview.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-troubleshooting.mdx
- src/nav/integrations.yml
This PR updates a few areas to reference our support for sending JSON-encoded protobuf payloads with OTLP and discourages sending data from browser apps directly to our OTLP endpoint to avoid license key exposure.
> OTLP HTTP/JSON support

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9210311/
> docs: PHP now defaults to 2000 max spans/min

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
With automatic logs in context coming down the pipe, it's time for us to update our documentation accordingly. This PR updates the logs in context documentation to include information about enabling automatic application logging, and is based heavily on the [Ruby docs](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/) on this topic.
Closes https://github.com/newrelic/node-newrelic/issues/1154
See also:
- Project Minerva overview: https://docs.google.com/document/d/1dRmT8goKWQZ0C-x7OVIXBUAfxvhqighesnvVGltImvo/edit#heading=h.x0p81xvxgouv
This PR should **NOT** be merged yet! It will be appropriate to merge once https://github.com/newrelic/node-newrelic/issues/1142 ,  has been merged and released.
> fix: add docs re: Node.js auto logs in context (Hold for release)

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names.mdx
- We (Alerts!) just released some additional threshold operators for static NRQL conditions
- This adds those operators to the exiting documentation
- Bringing it more/less in line with what's in the Terraform provider docs: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition
> docs(Alerts): Add 3 new term threshold operators for static NRQL conditions

- src/content/docs/apm/agents/php-agent/configuration/php-directory-ini-settings.mdx
The APM PHP agent team would like to refine the guidelines for using the newrelic_set_appname() API call, including removing a previous tip which is not recommended now.
> fix(php_agent): Improve guidelines for per-directory INI config

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx
Provide additional information for instrumenting supported Node.js modules that have been already loaded using `newrelic.instrumentLoadeModule` for cases where a user may have to delay instrumenting. An example of this might be asynchronously loading and decrypting api keys from a remote location.
> docs(node.js) Add instrumenting already loaded module

- scripts/actions/translation_workflow/testing/README.md
- src/content/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data.mdx
- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1418.mdx
- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1524.mdx
- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/new-relic-diagnostics-1727.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-example.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own.mdx
- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
- src/i18n/content/jp/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data.mdx
- src/i18n/content/jp/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-example.mdx
- src/i18n/content/jp/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
References to Node.js are followed their recommended branding.  It's a peeve of mine but this is the right way. Maybe we can add it to our style guide?
> fix: updated references to Node.js to use the proper branding

- src/content/docs/apm/agents/net-agent/troubleshooting/browser-injection-health-check-conflict.mdx
The xml had the wrong syntax for a xml comment. It doesn't matter at all but I'm weird so I changed it.
> docs: add lang identifier and fix comment

- src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
Added section covering how to delete Heroku syslog log drain token mappings via UI and API. Made a few minor capitalization changes throughout.
> chore(heroku_log_forwarding) - Add deletion info

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1243.mdx
Release notes for the new agent-version [1.24.3](https://github.com/newrelic/infrastructure-agent/releases/tag/1.24.3)
> infrastructure-agent release-notes 1.24.3

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Adds a new available configuration for infra-agent log forwarding
It's just a new configuration that allows customers to use the https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log-winevtlog
The configuration remains the same as for winlog
N/A
> feat: add winevtlog to infra-agent logs forwarding

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Exclusions YAML was updated and the `kr` frontmatter was added to the NRQL file so it would be translated. But it was not queued up in postgres DB.
I looked over the code and could not figure out why that would happen. Looks like it should queue up. 
This would be the first Korean doc sent for human translation.
Trying a trivial edit to see if this file is queued up when it's merged to `main`
> chore: minor change to try and queue file up for translation

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
The only accepted runtime type version value for Scripted API monitors is 16.10, not 16.10.0
Fixes an incorrect configuration value in the docs
On the Synthetics team, we got a user writing in saying that they could not create a scripted API monitor, despite following the NerdGraph docs. After we investigated, we realized that the cause was an incorrect field (runtimeTypeVersion).
> fix: update nerdgraph-synthetics-tutorial.mdx

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
The headers 'MSMQ NServiceBus 5.0 or higher' and  'RabbitMQ 3.5 or higher' in the messaging section were being aligned with the bullet points, making it look like a single list under MSMQ. I alighted them left with the first header to illustrate the separate sections. I also added backticks around the methods lacking them.
> docs: messaging headers alignment correction

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
There were a lot of codeblocks that shouldn't have been there or contained markdown for the page. Most caused by indentation (4 spaces in md makes a codeblock). I also added language identifiers.
I suspect this part is incorrect, it says it's a `.config` file but the code example is c# not xml
**Instantiating Logger using `.config` file**
```cs
var logger = LogManager.GetLogger("NewRelicLog");
logger.Info("Hello, New Relic!");
```
* If your issue relates to an existing GitHub issue, please link …
> docs: fixed many formatting errors

- .github/workflows/manual-add-files-to-translation-queue.yml
the workflow is only running the job if a PR has been merged but we want to be able to manually trigger it outside of PRs
> Remove if  check from manual translation workflow

- src/content/docs/new-relic-solutions/get-started/glossary.mdx
It updates no longer existing link (https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/build-new-relic-one/new-relic-one-application-nerdpack-file-structure) to existing one: https://developer.newrelic.com/explore-docs/nerdpack-file-structure/
> fix(Glossary): Update broken links

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
These two sections were rendering text in codeblocks and code as text, I'm testing if changing the indentation will correct it
> docs: testing a fix for text in codeblocks

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-16-0.mdx
Shiny new release notes for the 3.16.0 version of the Go Agent.
Enjoy.
> Release Notes for Go Agent v3.16.0

- src/content/docs/apm/agents/net-agent/troubleshooting/technical-support-net-framework-40-or-lower.mdx
`[#non-IIS apps]` was showing up as plain text on the page, not as a link
> docs: fix in page link

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
`AddCustomAttribute` link was routing to `https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/docs/agents/net-agent/net-agent-api/itransaction/` which was broken, I think it's because of a missing `/` at the beginning of the URL, otherwise it looked the same as the other links on this page.
> docs: fix broken link

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
Add infra-agent installation instructions for ubuntu 22.04
> feat: agent install instructions for ubuntu 22.04

- src/content/whats-new/2022/05/whats-new-05-25-fs-recap-blog.md
In the in-app version of this post, the image is linked to this URL: https://one.newrelic.com/nr1-core/5f39d192fe7bd3f1de03301b982acf9c/1ff84/FS_Blog_Graphic_520x250.png - and returns this error message: 404 - Nerdlet "5f39d192fe7bd3f1de03301b982acf9c.1ff84" not found.
In the docs version of this post, the image is linked to this URL: https://docs.newrelic.com/static/5f39d192fe7bd3f1de03301b982acf9c/1ff84/FS_Blog_Graphic_520x250.png - which shows up correctly. 
If we link the image to the blog URL, will this send users to the blog from both locations - and eliminate the 404 error associated with the in-app version?
* What problems does this PR …
> Update whats-new-05-25: Link image to blog post

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-16-1.mdx
* Changed dependency on gRPC from v1.27.0 to v1.39.0. This in turn changes gRPC's dependency on `x/crypto` to v0.0.0-20200622213623-75b288015ac9, which fixes a security vulnerability in the `x/crypto` standard library module. Fixes [issue #451](https://github.com/newrelic/go-agent/issues/451).
* Incremented version number of the `nrawssdk-v1` integration from v1.0.1 to v1.1.0 to resolve an incompatibility issue due to changes to underlying code. Fixes [issue #499](https://github.com/newrelic/go-agent/issues/499)
New Relic recommends that you upgrade the agent regularly to ensure that you’re getting the latest features and performance benefits. Additionally, older releases will no longer be supported when they reach end-of-life.
> release 3.16.1

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-otel-applications-kubernetes.mdx
Right now `hostmetrics` being present in the collector will lead to harvesting metrics already collected by the infra agent, so I propose we remove it from the docs.
> Remove hostmetrics to avoid doubledipping metrics

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
Accidentally rolled back an update from #7460 during the branding sweep. This brings it back
> fix(npm): Revert accidental rollback

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
I've tweaked this a few times over the past couple of months.  Due to the `-` the block needs some indentation to render correctly.  Any help would be appreciated it.  I will convert it to an image if needed, but prefer a markdown code block.
> fix: Fix broken code format

- src/content/docs/apm/agents/ruby-agent/troubleshooting/incompatible-gems.mdx
Thanks to a community contribution with Ruby agent
[PR #1177](https://github.com/newrelic/newrelic-ruby-agent/pull/1177),
the Makara gem is now supported and can be removed from the incompatible
gems list.
> The Ruby agent now supports the "Makara" gem

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
- src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx
* Infra-agent release 1.26.0 added support for ZFS.
> zfs filesystem support in infra-agent (1.26.0)

- src/data-dictionary/events/Span/code.filepath.md
- src/data-dictionary/events/Span/code.function.md
- src/data-dictionary/events/Span/code.lineno.md
- src/data-dictionary/events/Span/code.namespace.md
This PR documents the four new span attributes that agents have/ will be adding to support the CodeStream code-level metrics integration within the NR  data dictionary: https://docs.newrelic.com/attribute-dictionary/?event=Span.
> Add CodeStream span attributes to data dictionary.

- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/features/ruby-codestream-integration.mdx
- src/content/docs/codestream/how-use-codestream/performance-monitoring.mdx
- src/content/docs/codestream/start-here/codestream-new-relic.mdx
- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-880.mdx
- src/nav/apm.yml
To coincide with the release of version 8.8.0 of the Ruby agent, the
following changes have been made:
* Added a new v8.8.0 release notes page (with @hannahramadan, thank you!)
* Added code-level metrics / CodeStream functionality documentation to
the Ruby agent section
* Updated existing (previously Python only) code-level metrics /
CodeStream documentation to reference the Ruby agent as well
> Release, config, and CLM content for Ruby v8.8.0

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
adding a missing config option to the network monitoring docs for `response_time` in the `devices` section of the config file.
> chore: add devices.response_time config option

- src/content/docs/apm/agents/ruby-agent/features/ruby-codestream-integration.mdx
Update the Ruby agent CodeStream feature page to reference a more
agent context based document when referring to CodeStream itself.
(as per @angelatan2's request left on #7872)
> Ruby CodeStream documentation: link update

- src/content/docs/style-guide/writing-docs/processes-procedures/delete-document.mdx
Currently style guide does not mention impact on i18n folders from deleting docs
> fix(style guide): Doc how to delete i18n equivalents

- src/content/docs/apm/agents/manage-apm-agents/app-naming/use-multiple-names-app.mdx
The path was missing an initital `/`. This came in as a hero request.
> Fix(APM): Broken link

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4000.mdx
* Adds in release note for version 4.0.0 of the New Relic for iOS app.
> doc: Add in release not for New Relic for iOS version 4.0.0.

- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/features/ruby-codestream-integration.mdx
The correct environment variable to enable/disable code-level metrics
for the Ruby agent is: `NEW_RELIC_CODE_LEVEL_METRICS_ENABLED`
Fix `enabled` -> `enable` in the configuration description.
> CLM typo fixes for the Ruby agent

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
A request came in from a contributor asking why `logging.yml` was created automatically when we tell users elsewhere in the docs to create one manually. 
I inserted a callout explaining the rationale.
> fix(Logs): Add tip about guided installation and logging.yml

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
Do not merge: RHEL 9 building files ready and tests performed on the infra-agent, but artifacts have not been released yet.
PR state will be changed once artifacts are available.
> feat: add infra-agent installation instructions for RHEL 9

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring.mdx
Includes a required field in docker examples so nri-docker integration works when running inside a container and docker is on cgroup v2. This is required because, when running in cgroup v2, [default cgroup namespace mode is private](https://docs.docker.com/config/containers/runmetrics/#running-docker-on-cgroup-v2) and the integration cannot gather other containers metrics.
[nri-docker#131](https://github.com/newrelic/nri-docker/issues/131) was opened because those fields are missing.
> fix: include cgroupsns field in privileges so examples work properly on cgroup v2

- src/nav/apm.yml
Current our APM guides category has only one doc. This makes it a standalone doc instead of living in a category.
> Quick apm best practice nav fix

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-find-entities.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-jvms-page.mdx
This is a replacement for the older PR (#7317)  on the same topic since the branch became out of date (not the content).
The OpenTelemetry Java agent version 1.13.0 and higher now allows users to avoid workarounds to view JVM metrics.
This PR states that we recommend the newer agent.
This PR also includes a small wording change for the metrics-spans toggle memory.
> Add recommended OTel Java agent version

- src/content/docs/data-apis/custom-data/custom-events/collect-custom-attributes.mdx
- src/content/docs/data-apis/custom-data/custom-events/report-custom-event-data.mdx
- src/content/docs/data-apis/custom-data/get-custom-data-from-any-source.mdx
- src/content/docs/data-apis/ingest-apis/event-api/introduction-event-api.mdx
- src/content/docs/new-relic-solutions/get-started/glossary.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
- src/nav/telemetry-data-platform.yml
Related to dev site migration: bringing over content from dev site for 'Custom attributes and events' content and 'NRQL' content, and assorted edits to clean up things a bit.
> Migrate some 'collect data' dev site content

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/logs/logs-context/configure-logs-context-python.mdx
- src/content/docs/logs/logs-context/logs-in-context.mdx
This PR adds documentation for app logging settings in the python agent as well as logs in context docs.
@barbnewrelic
> Add Python Agent Application Logging Feature Docs

- src/i18n/nav/kr.json
we accidentally translated the "title" of section-break so it fell through our check and no `<br/>`s were added to the nav in korean
> Remove translated section-break

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-health-monitoring-integration.mdx
* We added the following new attributes to the AwsHealthNotification event: startTimestamp, endTimestamp and lastUpdateTimestamp.
* We are also taking the opportunity to remove the inventory section that has been EOL (we'll do the same for all integrations  in the next few weeks).
> feat(aws-health): new fields and remove EOL

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* Infra-agent is now compatible with RHEL 9, Ubuntu 22.04 and Amazon Linux 2022 (Beta).
> Infra-agent: update supported platforms

- src/content/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2.mdx
* StatsD integration is available on arm64 archictures.
> statsd: added arm64 support

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Improved details around when we do not allow nested queries, specifically when querying timeslice data, and what that actually means (what you can't include in your nested query).
> Clarified rules around nested queries

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- change from `minionHostname` to `minionId`, which should work better for Kubernetes containers where the container name doesn't change.
> Use `minionId` changes to count restarts

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
Fix https://github.com/newrelic/nri-mysql/issues/100
Context:
We should remove from the callout in our mysql docs the deprecation of cluster.slaveRunning since [now we are calculating the metric ]( https://github.com/newrelic/nri-mysql/pull/89) in a different way.
> fix(mysql): slaveRunning has been reintroduced

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream.mdx
* Made cost considerations more prominent and added links to ways to filter data as needed. 
* Included query examples to break down the ingest data and number of metrics based on namespaces.
> AWS metric streams: notes about filters and useful queries

- src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx
A recent .NET agent support ticket involved a situation where the customer did not have any agent log files to help troubleshoot, and the cause ended up being that the agent's `logs` folder, as created when the agent is installed with the NuGet package, is created with default permissions, which means that only the user who built/published the app can write to the logs folder.  If their app is executed by a different username (a common pattern), the agent will not be able to write logs.  This PR adds a callout to the NuGet package install instructions warning of this issue.
~Initially setting PR status to "Draft" to get feedback from .NET agent team members before it's ready for docs team review~.
> .NET Agent - NuGet agent install instructions - add callout regarding logs folder permissions

- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
Two section links were duplicates of the links above them.
To add language syntax highlighting I had to remove the `<var>` tags in every codeblock. Mostly they weren't particularly helpful in my opinion, and having the syntax highlighting would be easier to read.  They only one I wasn't sure about was this example:
```go
newrelic.ConfigAppName("YOUR_APP_NAME;APP_GROUP_1;ALL_APPS"),
```
> docs: fixed section links, add language identifiers

- src/content/docs/logs/ui-data/parsing.mdx
* Fixes a typo in the log data parsing section. (untail -> until)
> fix: typo in parsing logs

- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-1-0.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-2-0.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-2-1.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-3-0.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-3-1.mdx
Release notes were forgotten for a while.
In the meanwhile they get automated this PR fixes them.
Source of the info -> https://github.com/newrelic/nri-kubernetes/blob/main/CHANGELOG.md
> fix(k8s): update release notes

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
- src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx
Related to https://github.com/newrelic/nri-kubernetes/issues/478
`Namespace` attribute has been deprecated and `NamespaceName` is the one used
Context -> https://github.com/newrelic/nri-kubernetes/blob/7741a5058e5b29121e47590a1f791217231e6a1d/src/metric/definition.go#L507
> fix(k8sDocs): pointing to correct metrics

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx
Related to https://github.com/newrelic/nri-kubernetes/issues/478 but still not closing it
> feat(k8sDocs): clarify controlPlane monitoring

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
*Using dataPointCount() instead of count(*) when counting metric updates to avoid misleading results when querying over a long period of time.
> fix(aws): use dataPointCound for raw metrics

- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
- src/content/docs/apm/agents/java-agent/getting-started/monitor-your-java-app.mdx
- src/content/docs/apm/agents/java-agent/installation/java-install-overview.mdx
- src/nav/apm.yml
I didn't realize the old generic Java installation doc had some content that wasn't anywhere else. I've restored it and added a bit of extra context for why someone might want to read it.
> fix(Java): Restores the old generic Java install doc

- src/i18n/content/jp/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
- src/i18n/content/kr/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
This seems to be part of a deserialization issue with this page specifically.  Attached is a screen cap of a time last week when we needed to fix this particular line because part of it was still encoded.
> fix: add curly braces to Inline Code string

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
We've had Node 16 support, but this documents it.
> Adding Node 16 to supported Lambda runtimes

- src/content/docs/apm/agents/ruby-agent/features/ruby-codestream-integration.mdx
for enabling CodeStream in the Ruby agent, a colon should be used to
separate the 'code_level_metrics.enabled' configuration key from the
'true' or 'false' configuration value.
> Ruby CodeStream integration: YAML syntax fix

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Customers (internal and external) are often confused that capture() doesn't work as expected, because their regular expressions are designed to only match part of the attribute value and they must match the whole thing.
> fix: add tip that capture() regex must match entire input

- src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
This PR is to remove a 200 tablespace limit, that was removed on a new integration version, adjusting the docs to this updated feature
> Remove Oracle tablespace 200 limitation

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
The Java agent team just found out that the new version of the mentioned instrumentation module will no longer work with the newly released version.
> chore(java): Capping supported r2dbc-mariadb version

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
I have added two exemplary OHIs to a statement to clarify where you may have redundant metrics between an OHI and an AWS RDS integration.
> fix: Clarify specific OHI relevant to the sentence

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
Altered text to clarify that there are to primary ways to control infra agent ingest volume...
- Configure a variety of sampling rates
- Use regular expressions for select collectors to limit what gets collected.
> fix: Clarify section in Infra agent optimization

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-batching.mdx
Fix links to compression and attribute lengths pages, which are currently dead links.
> Fix OpenTelemetry batching dead links

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx
The example that was being linked to no longer exists. Users should reference the docs of the tailsamplingprocessor, which the docs already link to.
> Remove dead link from OpenTelemetry best practices

- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
- src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
- src/content/docs/logs/logs-context/disable-automatic-logging.mdx
- src/content/docs/logs/logs-context/logs-in-context.mdx
Docs hero: @barbnewrelic will take care of this one when ready to release!
feat: logs in context for golang
this adds documentation for logs in context for the go agent. Please merge this in synchronization with the go team's release of the [logs in context feature](https://github.com/newrelic/go-agent/pull/507/files#diff-53f120c6a2a5ba988e3e06e60026b8a2e8c67884654d88e9f10e10da2c4ba72f) 
For additional context about the zerolog plugin, see the readme here: https://github.com/newrelic/go-agent/blob/2e6700e93818bef216c81635ffc4a0d0d801242f/v3/integrations/logcontext-v2/nrzerolog/Readme.md
> golang logs in context (ETA 06-29-22)

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-17-0.mdx
* Logs in context now supported for zerolog.
* This is a quick way to view logs no matter where you are in the platform.
* Adds support for logging metrics which shows the rate of log messages by severity in the Logs chart in the APM Summary view. This is enabled by default in this release.
* Adds support for forwarding application logs to New Relic. This automatically sends application logs that have been enriched to power APM logs in context. This is disabled by default in this release. This will be on by default in a future release.
* To learn more about APM logs in context see the documentation [here](https://docs.newrelic.com/docs/logs/logs-context/logs-in-context).
* Includes the `RecordLog` function for recording log data from a single log entry
* An integrated plugin for zerolog …
> go agent release v3.17.0

- src/content/docs/style-guide/images/embed-videos.mdx
I realized that I hadn't updated the instructions for embedding videos as I thought I had. So, here's an improvement:
* Added instructions for upload videos to Wistia and getting the ID.
* Divided the YouTube instructions into iframe and Video sections.
* Added some basic instructions about using the new `vertical` property for images.
> Clarify Wistia and YouTube options with Video components

- src/content/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction.mdx
- src/content/docs/apm/reports/api-examples-sla-reports.mdx
- src/content/docs/apm/reports/apm-sla-reports.mdx
- src/content/docs/apm/reports/performance-reports.mdx
Fixes redirect issues stemming from #8243.
When I moved the taxonomy around and combined/deleted pages, I missed a few redirects in the reports and apdex categories. This PR adds them in correctly.
> fix(apm): add missing redirects from apm reorg

- src/content/docs/apm/agents/java-agent/configuration/java-agent-config-file-template.mdx
Adds syntax highlighting to the big ol' java config template
Note to reviewer: I intentionally removed the links from this as I think they make it harder to maintain.
> style(java config): Add syntax highlighting

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
Fixes #6763
Ran a search and confirmed that these section headers are not referenced in other documentation,
> Remove Tracing rate limit documentation as there are no longer limits 

- src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
Out team moved some use-case docs around on the developer site, which affected a link on our MELT page. This PR replaces that link.
> Fix broken MELT link

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
Without a line between the paragraph and the table, the serialized HTML nests the `table` inside a `p` like so:
```html
<p><strong>Arista eAPI</strong>
<table data-type="component">
...
</table>
</p>
```
Adding the line closes the `p` tag like so which puts `table` on its own when deserializing it from serialized html:
```html
<p><strong>Arista eAPI</strong></p>
<table data-type="component">
...
</table>
```
converts to
```
<Collapser
id="api-polling-config"
title="オプションのAPIポーリング構成"
>
**Arista eAPI**
<table>
<thead>
```
> Fix deserialization formatting bug

- src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-proxy-support.mdx
Adds instructions on how to specify the Infinite Tracing proxy configuration for the .NET agent.
> Update InfiniteTracing proxy documentation for .NET Agent

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/choose-your-aggregation-method.mdx
Cadence should still be the recommended aggregation method when we consider clock skewed events that the New Relic user has no control of, as a single event with a skewed timestamp can trigger aggregations on windows that do not have a representative dataset available. This happens with `PageAction` but in reality could happen with any event instrumented by untrusted devices.
> Update advice on cadence alerts for clock skew

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
I'm a New Relic employee (epoley@newrelic.com). My team owns NerdGraph.
To the best of our understanding, there is a mistake in this user types comparison chart. Basic Users should be able to access NerdGraph in general (though of course some specific APIs may be restricted.)
Read this complete internal Slack discussion for more context: https://newrelic.slack.com/archives/CBHJRSPSA/p1635878905246100
If you'd like to discuss this further in a non-public setting, feel free to contact us in #help-unified-api
> fix: Basic User NerdGraph access docs

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-recommended-alert-policy.mdx
Could we add an example POD restart NRQL based Alert ? 
Alert when container restarts:
NRQL: ` from K8sContainerSample select latest(restartCount) - earliest(restartCount) where clusterName = '<YOUR CLUSTER NAME>' facet containerName, podName, reason` 
Threshold: Static
Open violation when the query returns a value > 1 at least once in 1 minute
Advanced signal settings:
- Window Duration: 1 minute
- Streaming method: Event flow
- Delay: 1 minute
- Gap-filling strategy: Last known value
* If your …
> Add an example POD/container restart NRQL Alerts

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
The correct config stanza name appears in the sample code block elsewhere in this doc.
> Fix typo in memory_limiter configuration stanza

- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
This closes [#1254 of the node-newrelic repo](https://github.com/newrelic/node-newrelic/issues/1254)
A couple of other updates are also included for other instrumented libraries.
> fix(node agent): update compatibility requirements with newer features

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
Updated the section for impact of Inspected Count limit. 
Unlike my previous update which mentioned this under Original Data Plan - this impact is actually applicable across Data Plus and Original Data Model.
* What problems does this PR solve? - Clarity in documentation
> Section update - impact of Inspected Count limit

- src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
Addressing [this GitHub issue](https://github.com/newrelic/docs-website/issues/8384). Added links to the relevant files in the "Deployment options" H2. Wanted to give customers the option to read about what they're installing before installing the agent.
> Add links to README.md and THIRD_PARTY_NOTICES.md

- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-890.mdx
This pr adds the release notes for the ruby agent upcoming release 8.9.0. We will be releasing early next week
> [JULY 11TH; NOON] Add release notes for ruby agent 8.9.0

- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-config.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
Update docs to reflect the integration's new configuration possibilities implemented in [nri-kafkfa#178](https://github.com/newrelic/nri-kafka/pull/178)
> doc: update kafka config to make consumers/producers jmx's name optional

- src/content/docs/logs/ui-data/built-log-parsing-rules.mdx
- src/content/docs/logs/ui-data/parsing.mdx
Update docs for 2 new built-in parsing rules
Linux Cron (/var/log/cron), logtype=linux_cron
Linux Messages (/var/log/messages), logtype=linux_messages
> Add linux messages built in parsing rule

- src/content/docs/apm/agents/php-agent/advanced-installation/php-agent-installation-non-standard-php-advanced.mdx
ZTS builds were deprecated as of version 9.19 and not version 9.17.
Slack conversation with ENG to confirm: https://newrelic.slack.com/archives/C05112CNH/p1657224263652059?thread_ts=1657220579.996889&cid=C05112CNH
> Correct version that ZTS builds were deprecated in the PHP agent

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
We received a customer question about the the `timingPrecision` configuration attribute and realized it doesn't actually do anything after reviewing code. To minimize customer confusion, we should remove this from our published docs.
> Remove un-used timingPrecision config attribute from .NET docs

- gatsby-node.js
This forces datasource to resolve to something (null) even if it doesn't exist on a doc. it should get rid of the error when building a folder of docs with no datasource frontmatter
> Add datasource resolution

- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
- src/i18n/content/jp/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
- src/i18n/content/kr/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
The PostgreSQL doc page makes several references to MySQL instead of PostgreSQL. My hunch is that the page was copied from the MySQL doc page, originally, and this has just never been fixed?
This PR fixes it.
> Change the MySQL references to PostgreSQL on the page talking about PostgreSQL

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Loss of Signal causes confusion because it won't do anything unless there is already a signal present to lose. This callout should help to mitigate confusion around this point.
> Add clarifying callout for LoS

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx
Added link to infra-agent instructions for tar.gz package signature verification.
> Infra Agent tar.gz package signature process link

- src/content/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-logs/infrastructure-agent-logging-behavior.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
This PR will update infrastructure-agent documentation for log rotation:
- configure builtin log rotate mechanism
> docs: added doc for infra-agent builtin log rotation

- src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71600178.mdx
To be merged on 7/21 in line with the Python agent v7.16.0.178 release.
> Add Python agent release notes and config updates for logging on by default. (Publish on 07/21/2022)

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Updating the Node.js agent configuration docs to reflect that log forwarding is now enabled by default.
> chore: updates Node agent log forwarding configuration to be enabled by default

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
> Fix typo in default value of max_segments_cli in configuration file

- src/content/docs/apm/agents/net-agent/custom-instrumentation/create-transactions-xml-net.mdx
- src/content/docs/apm/agents/net-agent/installation/install-net-agent-linux.mdx
- src/content/docs/apm/agents/net-agent/installation/uninstall-net-agent.mdx
- src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx
- src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx
- src/content/docs/apm/agents/net-agent/other-installation/net-agent-install-resources.mdx
- src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-core-agent-linux.mdx
This PR has changes to a bunch of the .NET agent documentation to support our upcoming major version release (10.0.0), mostly caused by the fact that the name (and install path) of our Linux agent installation packages is changing from `newrelic-netcore20-agent` to `newrelic-dotnet-agent`.
We have release agent version 10.0.0 as of 7/19/2022 so this should be merged as soon as practicable.
> Changes to .NET agent documentation for major version 10.0.0 release

- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
* Agent configuration instructions showed examples with hard-coded license key embedded in the project source code. This is not recommended for security and privacy reasons. This was updated to explain the risk and to show how to get that value from the runtime environment instead.
* Added additional instructions to show how one may configure a wide variety of agent parameters from the environment.
> fix(Go): update configuration instructions

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Very minor edit, but I'm just trying to clarify that the this sentence is specifically speaking about the property named `message` on the log, the data will look something like this
```json
{
    "Timestamp": "2022-06-24T09:05:51.6760737+00:00",
  "message": "Writing data to file 'some_file_location' NR-LINKING|MzM5MTg5M3xBUE|af960d|12|34|example-app|"
} 
```
> docs: `message` is a property

- src/content/docs/logs/ui-data/parsing.mdx
Updating table of built-in parsing rules in the "Parsing" section of docs.  Some new parsing rules were created but the table was not updated with all of them:
https://docs.newrelic.com/docs/logs/ui-data/parsing#rulesets
> Update list of built-in parsing rules

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Double quotes are not allowed in YAML. The current configuration example makes the infra-agent crash.
Merge asap. Thanks
> fix: remove invalid double quotes in yaml value

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
- src/i18n/content/kr/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
Fixes spelling of "account" in a few places a found "acount" was used.
> chore: replaces spelling of 'acount' with 'account'.

- src/content/docs/apm/agents/net-agent/troubleshooting/resolve-net-scom-conflicts.mdx
~~I think this command is actually broken, as you can see when it's colorized, I'm reaching out to the .NET team to see if I can get some confirmation on how to properly write it. The issue being I think these `\` are accidentally escaping the following `"`~~
I tested out the command and I was incorrect, it is working as expected, adding escape chars breaks it
> docs: add language identifiers to the shell command

- src/@newrelic/gatsby-theme-newrelic/icons/logo.js
- src/@newrelic/gatsby-theme-newrelic/icons/logo/react.js
- src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
Can be used in techtiles as 'logo-react'
I also deleted some image imports in the apm intro since they weren't being used
> Add react logo

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This was introduced [in version 8.17.0 of the Node.js agent](https://github.com/newrelic/node-newrelic/pull/1291/files).
> fix(node agent): document the new grpc.record_errors configuration option

- src/content/docs/data-apis/custom-data/custom-events/apm-report-custom-events-attributes.mdx
strings have to be in `"` not `'` or they cause an error in .NET. Also added some words in backticks since I was here
> docs: typo in C# code

- src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
- src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
Product team is updating the guided install to make it so that some steps we previously called out as optional are now the default setup.
> Chore: Update network port behaviors to match changes in guided install

- src/content/docs/infrastructure/host-integrations/host-integrations-list/redis/redis-integration.mdx
Strings with special characters need to be surrounded by quotes in YAML:
https://yaml.org/spec/1.2.2/#53-indicator-characters
Improvement to documentation
Many passwords use special characters, and not including the quotations in the documentation may cause confusion
> Fix - Added quotations to password value

- src/content/docs/apm/agents/net-agent/net-agent-api/settransactionname-net-agent-api.mdx
the customer parameters method doesn't exist anymore replaced with this:
/docs/apm/agents/net-agent/net-agent-api/itransaction/#addcustomattribute
> docs: fix deprecaded link +lang identifiers

- src/content/docs/apm/agents/net-agent/custom-instrumentation/create-transactions-xml-net.mdx
This line of code has `name` and `Name` in it
```xml
<tracerFactory name="NewRelic.Agent.Core.Tracer.Factories.BackgroundThreadTracerFactory" metricName="Name">
```
It was difficult to understand which was referred to later when `Name` is referred to, so I made `Name` `TransactionName`. I also removed a dead link and updated the text to make more sense. Then I added language identifiers
> docs: update confusing language

- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
@vuqtran88 asked that I try to add this new info about an optional env var to target older agents. Now that the agent 10x is not supporting .NET versions 9x did support this is probably going to be important info to release. I'm waiting for a build to see if my links and formatting all worked, I'm not sure this is merge-able yet.
> docs: add info about new env var

- src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx
Updates licenses used in the iOS mobile app.
We have changed to using swift package manager, and as a result have changed around some of the packages we are using. This updates to our latest set of external packages and licenses they have.
> docs: Update ios-application-licenses.mdx

- src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application.mdx
Following the Mobile Monitoring configuration tutorial, I noticed a typo in the documentation (step two).
```javascript
import * as appVesrion from './package.json';
```
Taking advantage... I used a destructuring assignment task in the import.
```javascript
import {name, version} from './package.json';
```
> fix(docs): Fixes step two of React Native setup

- src/content/docs/apm/transactions/transaction-traces/introduction-transaction-traces.mdx
Link to "harvest cycle" in glossary was broken. https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/getting-started/glossary#harvest-cycle redirects to https://docs.newrelic.com/docs/new-relic-solutions/get-started/glossary/ The anchor is lost in the redirect, so there'a probably a bunch of similar broken links.
> fix: link to "harvest cycle"

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Rename Baseline to Anomaly in create-nrql-alert-conditions.mdx. This matches the new terminology in the UI.
When you link to this page from the Create an alert condition page it is named differently in the docs and confusing. 
> fix(docs): Rename Baseline to Anomaly

- src/content/docs/apm/agents/net-agent/getting-started/8x-to-9x-agent-migration-guide.mdx
A lot of this code used the wrong unicode double quotes. `”` is not the same as `"` and  `”` is an invalid char in c#, so that code was broken.  
I also fixed some other code wonkyness like a stray `)` breaking a line of code and some lines mashed together on a single line which were tougher to read.
> docs: fix chars used for double quotes

- src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
Adding firehose endpoints for US and EU
* The endpoint for firehose is not mentioned in the docs due to which customer is using wrong endpoints leading to an intermittent invalid response. 
* This issue is related the to https://issues.newrelic.com/browse/NR-24671
> Adding firehose endpoints for US and EU

- scripts/actions/fetch-and-deserialize.js
Even though I deleted this file in the DB and the translation vendor UI it still shows up in the api call. this will temporarily ignore the file until we get through these stalled jobs
> fix: Temporarily ignore missing file

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
We support .cjs file types for Node Agent configuration as of v7.5.0 and it was not listed in our docs.
> add commonJS support note

- src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
This PR updates the NerdGraph Historical Data Export page to include information on the maximum inspected count limit.
> Document Historical Data Export max inspected limit

- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-17-0.mdx
- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-0.mdx
The last two release notes for the Go agent reflect an incorrectly-calculated oldest supported agent version. This PR corrects them.
It also adds the latest release to the EOL version table.
> Fix(Go agent): corrected EOL version in release notes

- src/content/docs/logs/forward-logs/logstash-plugin-log-forwarding.mdx
This PR just adds a link to the logstash plugin in the github repository to help the users to know which plugin are they going to use.
> Add link to logstash plugin in github

- src/content/docs/logs/ui-data/parsing.mdx
- We're adding a new feature to logs parsing that allow to parse grok matches to JSON, here we try to explain how to do it and the configurations available.
Added section is in a Collapser because it's related to the other ones from the collapser. The `json` type is added as well to the grok-types table because it's not a type as that, but the way to use those "actions" is the same as for types in Grok, and also, it could be understandable as a "type casting" as the others, you're casting your "text" into a "structured json" type.
No
> docs: Add parsing JSON mixed-up with plain text log message

- src/content/docs/apm/agents/go-agent/configuration/distributed-tracing-go-agent.mdx
- src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
- src/content/docs/apm/agents/go-agent/features/add-browser-monitoring-your-go-apps.mdx
- src/content/docs/apm/agents/go-agent/features/create-custom-events-go.mdx
- src/content/docs/apm/agents/go-agent/features/cross-application-tracing-go.mdx
- src/content/docs/apm/agents/go-agent/features/trace-asynchronous-applications.mdx
- src/content/docs/apm/agents/go-agent/installation/install-go-agent-gae-flexible-environment.mdx
- src/content/docs/apm/agents/go-agent/installation/update-go-agent.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/create-custom-metrics-go.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/go-agent-attributes.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/instrument-go-segments.mdx
Update the rest of the Go docs with language identifiers and fix various code indentation issues.
> Update the rest of the Go docs with language identifiers

- src/content/docs/apm/agents/php-agent/configuration/distributed-tracing-php-agent.mdx
The paragraph of code was hard to read, so I added codeblocks. I also added language identifiers to the page.
> docs: move paragraph into code blocks

- scripts/actions/__tests__/check-job-progress.test.js
- scripts/actions/check-job-progress.js
When downloading and deserialization was successful, we update the translation database to mark a file as COMPLETED before we then clean up and delete all completed files and jobs from database.
in rare circumstances the same file URI could be IN_PROGRESS for the same locale at the same time in two different projects. if so, we only want to delete the record for the project at hand (human or machine). otherwise both records are deleted and one of the workflows will start to fail when it can't find the relevant record for a given file for a given locale.
See jira for full details https://issues.newrelic.com/browse/NR-39576
> Fix i18n workflow bug when marking a translation as completed in translation database

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
The link to the NerdGraph information for linking AWS accounts to New Relic for Metric Streams was pointing to the section for API Polling integrations. This change fixes it to point to the Metric Streams version of the mutation.
> Fix link to Metric Streams NerdGraph mutation

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
Fixed a couple duplicate links so that they are unique and when linked will bring the user to the correct setting.
> Fix links in php-agent-configuration

- .github/workflows/auto-comment.yml
Remove Recharge Week verbiage from PR and issue auto-replies
See also #8804
> chore(.GITHUB): Remove Recharge Week info

- src/i18n/translations/en/translation.json
Lower case the `D` in home page title
> fix: lower case the d in Docs on home page

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This has been added in the following PR:
https://github.com/newrelic/node-newrelic/pull/1326
> fix(node agent): add compressed_content_encoding configuration setting

- src/content/docs/infrastructure/host-integrations/host-integrations-list/f5-monitoring-integration.mdx
In particular in the new golang version the CommonName is no longer taken into consideration while validating certificates.
>The deprecated, legacy behavior of treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default.
This could be an issue for users still relying on legacy commonName and not on Subject Alternative Name. In that case they would see an error message like:
```
[ERR] Encountered fatal error: Post [...] x509:  certificate relies on legacy Common Name field, use SANs instead
```
To overcome this issue the user should update the certificate relying on Subject Alternative Name.
In the meanwhile as a workaround they could also pass the new argument --ssl_insecure_skip_verify to skip the certificate …
> nri-f5: add info commonname deprecation

- src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/go-agent-code-level-metrics-instrument.mdx
* Existing version of the documentation misspelled `IgnoredPrefix` as `IgnorePrefix`. This corrects that typo.
* The upcoming release adds new functionality by allowing multiple string arguments to the `WithIgnoredPrefix` and `ConfigCodeLevelMetricsIgnoredPrefix` functions instead of just a single one as before. This is now documented.
* The `Config` structure's `IgnoredPrefix` member is now deprecated in favor of the new `IgnoredPrefixes` (the former being a single `string` value, the latter being `[]string` to allow multiple prefixes to be specified.
> Fix(Go Agent): corrected names of functions, added multi-string usage for IgnoredPrefix

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-0.mdx
Release 3.18.0 introduced API changes in a backwards-compatible manner to prevent this from being a breaking change for users of the Go Agent. While this is the case for what we believe to be typical usage of the agent, there is a possible edge case where a change to customer code is necessary if they wrote their own custom code around the agent.
This PR adds a notice to the release notes for 3.18.0 to point this out to users so they are fully informed of the issue.
> Fix(Go Agent): Added notes about compatibility with legacy code

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx
Added custom request headers to the advanced options for ping and simple browser monitors. This feature has been available in synthetics for a few months but was not added to the documentation when released.
> feat(custom headers): Added custom header option

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
This configuration doesn't work with the new OpenTelemetry Collector v0.57.2 and up, and returns errors like `error reading processors configuration for "cumulativetodelta"` so `include` and `match_type` was added to work with newer releases of the collector.
> Updated cumulativetodelta/metrics

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx
- Fixed multiple broken create monitor links
- Fixed link to additional response validation details
- Fixed link to monitor types in the response validation section
- Removed references to Apdex. The Apdex T value can no longer be set in the synthetics UI.
> fix(link fixes and apdex removal): Adjustments

- src/content/docs/accounts/accounts-billing/account-structure/add-accounts.mdx
- src/content/docs/accounts/accounts-billing/account-structure/new-relic-account-structure.mdx
As part of onboarding/guide work, putting in updated info into 'account/orgs' section instead of in guide.
> Add detail to orgs/accounts section about adding accounts

- src/content/docs/logs/ui-data/parsing.mdx
- Add pharagraph defining naming restrictions for GROK variables
> GROK parsing variable name restrictions

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-config.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
This PR is to fix a small discrepancy we have in our mysql settings and example docs
The correct syntax to enable TLS support is `ENABLE_TLS`
https://github.com/newrelic/nri-mysql/blob/master/mysql-config.yml.sample#L6
> Fix mysql TLS setting

- src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx
- src/content/docs/logs/forward-logs/circleci-logs.mdx
- src/content/docs/logs/forward-logs/cloudflare-logpush-forwarding.mdx
- src/content/docs/logs/troubleshooting/no-log-data-appears-ui.mdx
- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
- src/content/docs/new-relic-solutions/get-started/quick-launch-guide.mdx
- src/content/docs/new-relic-solutions/new-relic-one/install-configure/install-new-relic.mdx
- src/content/docs/new-relic-solutions/observability-maturity/innovation-growth/development-release-quality-guide.mdx
- src/content/docs/new-relic-solutions/observability-maturity/innovation-growth/improving-development-quality-guide.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-as-code-guide.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/service-characterization-optimize-telemetry-data-guide.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/troubleshooting/not-seeing-data.mdx
- src/nav/new-relic-solutions.yml
Changes: 
Added new 'quick launch guide'
Added references to this from related intro/welcome docs
Assorted changes as noticed 
Things to review: 
- the 'quick launch guide' itself (which has been on beta site for a while and gotten significant review already)
- The references to it in the 'Welcome' and 'Install' docs
- The location of the guide.
> New 'quick launch guide'

- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-1.mdx
* Extended the `IgnoredPrefix` configuration value for Code-Level Metrics so that multiple such prefixes may be given instead of a single one. This deprecates the `IgnoredPrefix` configuration field of `Config.CodeLevelMetrics` in favor of a new slice field `IgnoredPrefixes`. The corresponding configuration option-setting functions `ConfigCodeLevelMetricsIgnoredPrefix` and `WithIgnoredPrefix` now take any number of string parameters to set these values. Since those functions used to take a single string value, this change is backward-compatible with pre-3.18.1 code.  Accordingly, the `NEW_RELIC_CODE_LEVEL_METRICS_IGNORED_PREFIX` environment variable is now a comma-separated list of prefixes.  Fixes [Issue #551](https://github.com/newrelic/go-agent/issues/551).
* Corrected some small …
> release notes for Go Agent v3.18.1

- src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx
* What problems does this PR solve? - We've identified one of the version of an essential library breaks our agent functionality
> [NR-39298] AGP 7.2.1 breaks transform API, fixed in 7.2.2

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
NetworkSample was a critical omission from the list of event types that are covered under infra host bytes.  This PR adds it.
> fix: Add NetworkSample to list of event types

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
Made changes to Compatibility/Requirements docs for Python, Node.js, and .NET.
- For the Node.js doc, I restructured the page for readability. Because TypeScript is a JavaScript "dialect" / programming language, it was ~suggested that I not add it to the existing framework collapser. I decided to give it its own collapser as a band-aid solution
- For the Python doc, I added a line in the table for Python libraries for NumPy (the Frameworks row was just for frameworks)
- For .NET, I created a miscellaneous collapser for C# and ADO.NET. I can create a follow up ticket to tease this out a little bit more, but for the purposes of these tickets, this seemed like an ok solution.
> framework updates 

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
According to a conversation with Support (Cayetano Sanchez), Azul JVM 17 is supported. Updating docs to avoid confusion
> Azul JVM Support Update

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-resources.mdx
Adds info on how to add tags for OTel entities using a few different methods. 
I previously tested using the resource processor myself (see [here](https://discuss.newrelic.com/t/tagging-or-classifying-entities-in-opentelemetry/188699/5)) and also using the UI directly. 
> Add info on how to add custom tags

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
this PR adds details to the 7 parameters required by the CloudFormation template used to implement AWS CloudWatch Metric Streams.
> chore: add cf parameters to aws metric stream

- package.json
- src/components/AgentConfig.js
- src/pages/install/{installConfig.agentName}.js
- yarn.lock
Added instrumentation to begin doing this ticket ^
> set active state on hover and focus for walkthrough steps / start instrumentation

- src/content/docs/mobile-monitoring/new-relic-mobile-ios/configuration/upload-dsyms-bitcode-apps.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags.mdx
- src/content/docs/release-notes/mobile-release-notes/xcframework-release-notes/xcframework-agent-738.mdx
XCFramework 7.3.8 Release notes added @ `xcframework-agent-738.mdx` go live 08/24/22.
Updated `upload-dsyms-bitcode-apps.mdx` to reflect changes.
Add additional ff to `ios-agent-configuration-feature-flags.mdx`.
> Added iOS XCFramework Agent version 7.3.8 release notes

- src/content/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration.mdx
Fixed a broken command on the manual installation part on install-ecs-integration.mdx, added missing escaped characters
> fix: missing escaped characters on manual install

- src/content/docs/accounts/original-accounts-billing/original-users-roles/overview-user-models.mdx
We had two links to the same doc, each with their own syntax issues. This should correct the two issues.
This closed GitHub issue #8993
> Correct two broken links

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Update two document anchors. I think these were supposed to point to the next section called FedRAMP-compliant endpoints.
> Fix two anchors

- src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
- src/content/docs/apm/agents/ruby-agent/instrumented-gems/grpc-instrumentation.mdx
This is a follow-up to the Ruby agent 8.10.0 release. This PR has some minor tweaks based on team feedback.
> Make minor Ruby agent 8.10.0 edits

- gatsby-browser.js
- gatsby/should-update-scroll.js
- src/components/AppInfoConfig.js
- src/components/AppInfoConfigOption.js
- src/components/TileSelect/TileOption.js
- src/components/TileSelect/TileSelect.js
* removes scrolling issue 
* if the optionType is used more than once, it will collapse all of them (for example the framework selection and the top and bottom collapse at the same time)
> Collapser fixes for java install docs

- src/content/whats-new/2022/08/whats-new-8-25-longer-running-queries.md
* This help improve querying of large data volumes from large enterprises or customers that want to query older events
* Longer running queries is released on 08-25-2022 for Data Plus customers.
* The longer running queries extends query durations up 2x (2minutes) for normal NRQL queries and 10x (10 minutes) for New Relic's GraphQL API (NerdGraph) queries
> "Whats New": Data Plus - Longer Running Queries

- src/content/docs/apis/nerdgraph/get-started/nerdgraph-explorer.mdx
Aligns the curl example with an error response people may see.
The error is:
```
Please provide an API key via the `Api-Key` header
```
So folks may be lead to believe the `API-Key` is incorrect in the example code, when in fact they need to create a `user` API key.
> Align Api-Key header example with error response

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Removed the semicolon found after the `.WriteTo.Console(new JsonFormatter());` line which causes a syntax error when copying the code.
[Link to issue](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all#2-decorate), incorrect code found in the code sample within:
```csharp
Log.Logger = new LoggerConfiguration()
.MinimumLevel.Override("Microsoft", LogEventLevel.Information)
.Enrich.FromLogContext()
.WriteTo.Console(new JsonFormatter());
.CreateLogger();
```
> Remove semicolon from C# Serilog code example

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/specify-when-alerts-create-incidents.mdx
Warning and Critical thresholds are treated identically now. Warning incidents can open their own issues, and users can be notified on them the same as critical. The only difference now is the label ("Critical" vs. "Warning").
> Fix warning and critical behavior explanation

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes.mdx
Fix indentation on YAML.
See example at https://github.com/newrelic/nri-kubernetes/blob/37e7255299d4ae79403a1d2042a74207bb9bb19d/charts/newrelic-infrastructure/tests/configmap_integrations_test.yaml
> Chore: fix indentation in autodiscovery config

- src/content/docs/distributed-tracing/troubleshooting/missing-trace-data.mdx
I added the python code into a codeblock as well as language identifiers for it and the xml, because it looks nicer
> docs: add lang identifiers

- src/pages/install/{installConfig.agentName}.js
This removes the value of the text entered and also only submits an event once per page render
> update tessen pt. 2

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
We don't support yet the newly released r2dbc-postrgres.
> chore(java): cap supported r2dbc-postrgres version

- src/content/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits.mdx
I just prettied up the example json
> docs: add json identifier to code example

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
The table heading for the table in the Program Benefits section for standard edition had a typo, it said "Standar" instead of "Standard" -- this update adds the "d" to correct the typo in the table heading. Thank you.
> Typo on Program Benefits Table Heading: "Standard"

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
- src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-user-mgmt.mdx
Previously, the new Groups UI was released but then rolled back. So this PR reverts newrelic/docs-website#9089 so as to re-add the docs changes for the new Groups UI back to the docs site. User mgmt team will let us know when to publish this, but likely sometime week of Sept 4.
> ~ Sept 6 or so: Reinstitute the new groups UI changes 

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-troubleshooting.mdx
The original copy says that `service.id` is required for log correlation; it is `service.name`.
The doc that this one links to has the correct attribute, `service.name`. 
N/A
> Corrected required resource attribute

- src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
Since we had a broken link in the "Curated dashboards" section, we looked at the section more closely and realized that we don't actually have a quickstart with a dashboard for Metric Streams. So, we are removing this section.
> Remove section about curated dashboards

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-comparison.mdx
Here are some updates for September 2022.
* Move golden metrics statement from Summary page to each of these sections: Explorer , Navigator, and Lookout.
* Turn Time to glass section to green for OTel.
* Add new comment under Explorer explaining that OTel and New Relic are in different sections.
* Revamp the tail-based sampling with new info from @reese-lee
> Update New Relic/OpenTelemetry comparison doc

- scripts/actions/fetch-and-deserialize.js
The translation vendor has 5 files that our DB does not have, this temporarily ignores those 5 files so the workflow can run, they'll be added afterward (manually)
> Temporarily ignore files missing from db

- src/content/docs/apm/agents/net-agent/net-agent-api/ispan.mdx
Version 10.1.0 of the .NET Agent (as yet unreleased) introduces is a new method to the `ISpan` API. These changes provide documentation about how to use this API.
Please check with our team before merging this as we would like to synchronize it with the Agent Release.
> Doc: Add documentation about new `SetName()` on the agent API

- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-1000312.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9200310.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9210311.mdx
The product manager for the PHP agent team requested we put up-to-date information in the past few release notes on the policies regarding supported PHP agent versions and EOL information.  This PR changes the support information of these release notes.
> fix(php-agent): Correct release note support statement

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition.mdx
Updated terminology and removed references to deprecated items (e.g. warning thresholds can now get notifications, there is no opt-in for streaming alerts, and so forth).
> Updated with new terminology

- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8101.mdx
This PR adds the release notes for the upcoming release of 8.10.1 of the ruby agent.
> Add ruby agent 8.10.1 release notes

- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
`ipv_preference` section link ID was `ae-max_samples_stored`, same as the transaction sections `max_samples_stored` ID so the link didn't work
> Docs: fix section link

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
- The cmd SELECT count(*) FROM Log WHERE `level` = 'DEBUG' was rendering wrong because of the internal backtick. 
- The link to the Java config was broken too so fixed that. 
- Fixed some incorrect chars, `“` for `"`
- Fixed link to NGINX
- promql probably isn't recognized by our docs site
- I suspect this code block has leftover markdown for the `**name**` part, but I don't know promql so I can't say if that's valid or not
```promql
topk(20, count by (**name**, job)({__name__=~".+"}))
```
- I did a bunch of general cleaning up too and added lang identifiers to the code
The bottom of this page also has a broken link I can't make sense of: https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide/#conclusion …
> docs: fix code examples & links, etc

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-7100.mdx
**Please hold until notified by one of the Java Agent team members that agent has released.**
> HOLD FOR RELEASE: Java agent release 7.10.0

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
HOLD THIS AS A DRAFT FOR NOW.
These changes update compatibility and requirements docs' page to reflect changes in the agent version 7.10
> Updates for Pending Java Agent 7.10 release

- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
- src/content/docs/apm/agents/java-agent/features/java-codestream-integration.mdx
- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-7100.mdx
- src/nav/apm.yml
Some content related to the 7.10 release didn't go with the main PR.
Also the release notes were missing the metadata.
> chore(Java): Code level metrics and release fix

- gatsby/on-render-body.js
Adds optimizely snippet for marketing team to configure A/B tests and have them applied to site via scripts it injects.
Couldn't find any guidance on where script should be on page. They strongly suggest to not add `async` or `defer` unless absolutely needed (could cause flickering i guess).
Will try to work with marketing folks to try and test out before prod
Closes https://issues.newrelic.com/browse/NR-44970
[How the Optimizely snippet works: Order of activation](https://support.optimizely.com/hc/en-us/articles/4410289779853)
> feat(analytics): add optmizely snippet

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
This PR contains changes to the compatibility specification page for the PHP agent requested by the PM.
These changes can go live when they have been approved, there is no need to sit on them.
Thanks!
> fix(php-agent):Update PHP compatibility specs

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- add charts for the new Synthetics Job Manager (SJM)
- add link to new performance analysis spreadsheet for SJM
- change `nr.internalQueueDuration+nr.executionDuration` to `duration` to more closely match results in Synthetics UI.
> Update dashboard example JSON

- src/content/docs/errors-inbox/error-external-services.mdx
Step two said:
> Open one of your New Relic error inboxes, select the Inbox Settings icon (looks like a gear) in the top right corner.
I assume these are just out of date, currently (as the video shows too) this is **Notification Settings** with a bell icon, not a gear
> docs: update instructions

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/cloud-flow-logs/aws-vpc-flow-log-monitoring.mdx
This is Kevin Downs, Infrastructure PMM at New Relic.  I updated this doc to correct the name.
Incorrect: "AWS VPC flow logs" or "AWS VPC Flow Logs"
Correct: "Amazon VPC Flow Logs"
Note: "VPC flow logs" without "Amazon" *is* correct.
> Update to correct naming

- src/data-dictionary/events/NrConsumption/GigabytesIngested.md
Change units for GigabytesIngested from GiB to GB
This PR changes units for GigabytesIngested from GiB to GB.  This is important because NrUsage and NrConsumption metrics in New Relic are tracked via GBs, not GiBs.  There is a difference in GBs and GiBs: https://en.wikipedia.org/wiki/Gigabyte
> Change units from GiB to GB

- src/content/docs/apm/agents/ruby-agent/installation/update-ruby-agent.mdx
Fix the v8.0.0 changelog link (by adding a leading slash to convert the relative link into an absolute one) on the Ruby agent update instructions page.
> fix 8.0.0 changelog link on Ruby agent update page

- src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3066.mdx
Need to remove this from the release notes as we had to revert that change.
> fix: Remove upgrade to Java 11 from 3.0.66 Notes

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
This PR updates the Compatibility Requirements page for the Python Agent to reflect the deprecation of Python 3.6.
> Update compatibility requirements for Python Agent

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-find-entities.mdx
We have expanded the scope of the metric/span toggle so it now includes the JVMs page. This is for NR-43760 outside of the sprint process.
> Add support for JVMs page and metric/span toggle.

- src/content/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx
- src/content/docs/distributed-tracing/concepts/introduction-distributed-tracing.mdx
I changed the link in Ruby so it points to the distributed tracing setup page within the Ruby docs. Ruby users don't need to go to the general distributed tracing page (unless they click that link in the new DT instructions within Ruby). Also, I removed a duplicate redirect that was in the introduction to distributed tracing. That redirect was already over in the general distributed tracing setup page.
> Change Ruby's link to distributed tracing to point to setup

- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
Removes versions no longer supported, adds new 3.19.2 version
> Chore(Go Agent): update EOL table for agent versions

- src/content/docs/apm/agents/python-agent/installation/install-python-agent-docker.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/content/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/content/whats-new/2022/07/whats-new-07-15-July-2022-EOL-announcements.md
- src/i18n/content/jp/docs/apm/agents/python-agent/installation/install-python-agent-docker.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/jp/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/installation/install-python-agent-docker.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/externaltrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/messagetrace-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/messagetransaction-python-agent-api.mdx
- src/i18n/content/kr/docs/apm/agents/python-agent/python-agent-api/profiletrace-python-agent-api.mdx
Update New Relic docs to reflect Python Agent's deprecation of Python 3.6.
There are documents in various languages that I was not able to modify to reflect this (since I do not speak the languages), but the ones in English or with links to pages I was able to update.
> Update docs to reflect Python Agent's deprecation of Python 3.6
