newrelic/docs-website

src/content/docs/data-apis/manage-data/calculate-data-ingest.mdx

Some edits to make it clear that using an existing account to estimate data ingest was separate process from using spreadsheet.

fix(data estimator): rewriting existing account info

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9300.mdx

.net agent 9.3.0 release.

---

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx

NPM - Adding missing "

---

src/content/docs/style-guide/writing-docs/processes-procedures/create-edit-content.mdx

See jira doc for more details.
* Adding link to contributor doc from style guide
* Moving section

[DOC-7539] Contributor docs review

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

previous command grep'd for fluent-bit, but fb runs as td-agent-bit so added that grep filter instead.

Updated troubleshooting command

---

src/data/external-redirects.json

Fixes on-host redirect broken in the auto-index removal. Based on a hero request. 
Links to the I/O list.

fix(redirects): add on host redirect

---

src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx

Added links to the fluenbit installation directions for those customers starting with a fresh install.

Updated fluentbit install directions

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/new-relic-one-user-model-understand-user-structure.mdx
src/nav/style-guide.yml

fix(404s): couple fixes

---

src/content/docs/apm/agents/net-agent/troubleshooting/no-data-appears-net.mdx

fix(agents): add taxonomy redirect to doc

---

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx

Added a blurb about Pixie needing to run privileged. Also added a note on installing our K8s integration with privileged=false which prevents Pixie from running.

Updated Pixie Requirements

---

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx
src/content/docs/accounts/accounts-billing/general-account-settings/introduction-account-settings.mdx
src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
src/content/docs/glossary/glossary.mdx

Edit to Okta, adding necessary auth domain step.
Fixing some nonworking URLs

fix(accounts docs): several small edits

---

src/content/docs/errors-inbox/errors-inbox.mdx

Remove EU callout now that the inbox is live in EU.

fix(errors-inbox): remove EU callout

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-7-0.mdx

* What problems does this PR solve? Node.js release notes v8.7.0

chore: Node.js Agent v8.7.0 Release Notes

---

src/content/docs/logs/ui-data/drop-data-drop-filter-rules.mdx

* We need to mention for the users to know while creating the drop filters using the nerdgraph they need to set the source attribute in the schema to `logging`

updating drop filters schema that created using nerdgraph

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx

Infinite tracing now has support for the OTLP protocol. This removes a warning about lack of support.

Remove callout about infinite tracing OTLP support

---

src/content/docs/glossary/glossary.mdx
src/content/docs/logs/log-api/introduction-log-api.mdx
src/content/docs/mlops/bring-your-own/mlops-byo.mdx

DOC-7619. Removal of a couple insert key references.

fix(assorted docs): remove insert key

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1214.mdx

Adding release notes for Browser agent v1214, if approved this can be merged and deployed as soon as possible.

Add Browser agent v1214 release notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx

Fixing ingested data query def

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-slm.mdx
src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
src/content/docs/apm/reports/service-level-agreements/apm-sla-reports.mdx
src/content/docs/new-relic-solutions/new-relic-solutions/establish-objectives-baselines-define-team-slos.mdx
src/content/docs/service-level-management/consume-slm.mdx
src/content/docs/service-level-management/create-slm.mdx
src/content/docs/service-level-management/faqs-slm.mdx
src/content/docs/service-level-management/intro-slm.mdx
src/content/whats-new/2021/12/whats-new-12-07-service-level-management-beta.md
src/i18n/translations/en/translation.json
src/nav/root.yml
src/nav/service-level-management.yml
src/nav/telemetry-data-platform.yml

Minor renaming of SLM docs, updating nav file menus.
See more in DOC-7629.

[DOC-7629] SLM updates

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide.mdx

This change involved improving the KPI section a little. 
I ordered KPIs in order of priority.
I added information about thresholds
I put in KPIs that were in the dashboards we share but weren't documented
I added thoughts about thresholds in general

Update to kpi thresholds

---

src/content/docs/accounts/accounts-billing/account-structure/account-id.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
src/content/docs/accounts/accounts/automated-user-management/azure-ad-scimsso-application-configuration.mdx
src/content/docs/accounts/accounts/automated-user-management/onelogin-scimsso-application-configuration.mdx

Small changes related to account settings UI changing: some things that were visible under account dropdown directly are now only found under Administration.

fix(user mgmt): updating for account settings UI

---

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx

This PR adds a usage example for wildcarding to the function_trace config setting docs.

Add usage example to function_trace wildcarding docs.

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx

Some updates on supported versions of libraries

chore(java-agent): cap supported versions

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

Reviewer: Please watch the video and give me your thoughts on whether it works here. Thanks!

feat(AI/Alerts): Add Nerd Bytes video

---

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-640.mdx

* What problems does this PR solve? - release notes for android agent v6.4.0

[Mobile-7370] Release notes for android agent v6.4.0

---

src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md

This needs to go live Jan 12, 10 am PST to match with the Core user in-product experience.
Will update with the correct Nerdbyte link by 1 pm PST, Jan 11.

Core user type What's New post

---

src/data-dictionary/events/PageView/duration.md

Also chatted with Browser SME about wording

fix(PageView duration): Deleted per documentation slack 01-12-22

---

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3059.mdx

* Adds the release notes for CPM version 3.0.59

feat: CPM 3.0.59 Release Notes

---

src/data/whats-new-ids.json

This is a second evening merge to main because I forgot to merge the CPM PR.

Daily release/01-12-22 evening-2

---

src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/kubernetes-integration-troubleshooting-not-seeing-data.mdx

Removed deprecation notice callout

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx

Remove beta markers from examples and move the only remaining beta one to the bottom

Remove beta markers

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1220.mdx

Release notes for infrastructure agent 1.22.0

Infrastructure agent 1.22.0 release notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/core-users-release.mdx

Putting the free preview period in better location, under Availability section. No need for review.

fix(core): improving release availability note

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

Updated based on @henrytech's feedback

fix(Alerts): Update EOL date

---

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/aqm-implementation-guide.mdx

Fix some strangely formatted code blocks. Remove double spaces between sentences for style guide.

style(alerts quality mgmt): Fix code blocks

---

src/content/docs/apm/agents/python-agent/python-agent-api/backgroundtask-python-agent-api.mdx
src/content/docs/apm/agents/python-agent/python-agent-api/datastoretrace-python-agent-api.mdx

Added a sentence to explain that instrumentation can be done through config file (and added a link to instructions)

Add sentence to explain that instrumentation can be done through config file

---

src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/ignore-or-include-prometheus-metrics.mdx

Added additional configuration example for the `nri-prometheus` integration.

Added additional include/exclude metrics example

---

src/content/docs/codestream/codestream-integrations/msteams-integration.mdx
src/content/docs/codestream/codestream-integrations/notifications.mdx
src/content/docs/codestream/codestream-integrations/slack-integration.mdx
src/content/docs/codestream/codestream-settings/account-settings.mdx
src/content/docs/codestream/codestream-settings/team-administration.mdx
src/content/docs/codestream/codestream-ui-overview/activity-feed.mdx
src/content/docs/codestream/codestream-ui-overview/codemarks-section.mdx
src/content/docs/codestream/codestream-ui-overview/feedback-requests-section.mdx
src/content/docs/codestream/codestream-ui-overview/filter-search.mdx
src/content/docs/codestream/codestream-ui-overview/issues-section.mdx
src/content/docs/codestream/codestream-ui-overview/my-organization.mdx
src/content/docs/codestream/codestream-ui-overview/permalinks.mdx
src/content/docs/codestream/codestream-ui-overview/pull-requests-section.mdx
src/content/docs/codestream/how-use-codestream/discuss-code.mdx
src/content/docs/codestream/how-use-codestream/pull-requests.mdx
src/content/docs/codestream/how-use-codestream/request-feedback.mdx
src/content/docs/codestream/how-use-codestream/start-work.mdx

Codestream image work

---

src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx

GH hero request. Fixes https://github.com/newrelic/docs-website/issues/5662

fix(Azure Web Apps): Fix broken link

---

scripts/actions/check-job-progress.js
scripts/actions/fetch-and-deserialize.js

* remove async from extract method since its not using await keyword. simplify line which calls extract. 
* update console log to use record[0], since record is an array

chore: bugfixes, cleanup

---

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-licensing-security.mdx
src/nav/new-relic-solutions.yml

Fixes https://github.com/newrelic/docs-website/issues/5663

fix(Diagnostics CLI): Data storage

---

src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr21-04.mdx
src/content/docs/security/new-relic-security/security-bulletins/security-bulletin-nr22-01.mdx
src/content/docs/security/security-privacy/information-security/security-bulletins.mdx
src/nav/new-relic-security.yml

Info from SMEs via slack, 1/13/2022

feat(Security bulletins): NR22-01

---

src/i18n/nav/jp.json

Updating nav to fix some changes to the English that weren't reflected in the JP version.
Adding menus for MT pages.
**IMPORTANT:** to be merged with the MT content.

Updated Nav file

---

src/content/docs/browser/new-relic-browser/browser-pro-features/intro-to-browser-pro-features.mdx

feat(Browser pro): Added list of features

---

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx
src/content/docs/infrastructure/prometheus-integrations/troubleshooting/compare-rw-data-sent-billed-bytes.mdx
src/nav/infrastructure.yml

A few fixes and improvements:
* Adding auto-index redirect 
* Added lost troubleshooting doc in the nav file, and minor doc edits
Found these while starting work on DOC-7126.

Prometheus fixes

---

src/content/docs/mlops/integrations/mona-mlops-integration.mdx

As requested by Mona, they have changed some instructions in their documents which I have changed on our end as well. This includes a step simplification and a tip addition.

Update Mona Doc

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-7-1.mdx

chore: Adds Node.js Agent v8.7.1 Release Notes.

chore: Adds Node.js Agent v8.7.1 Release Notes.

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9400.mdx

Release notes for v9.4.0 of the .NET agent.

.NET agent 9.4.0 release notes

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4200.mdx

Informs users of features in new version
Just plain old release notes!

Android mobile app release notes for v4.2.0

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3820.mdx

* Adds release notes for NR for iOS version 3.82.0

docs: add release notes for NR for iOS new version

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx

Org/user mgmt liaison work. Includes: 
* Add a call out that for original user model, billable users result in billing impacts regardless of whether an account is active or inactive. 
* Some general improvements around explaining billable user-related considerations for that user model. 
* Improved references/links to that section

Clarify about v1 user's account settings page 

---

src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md

Broken embedded video, this might fix it. No need for review from PMs.

fix(what's new core users): fix video

---

src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx

There was an issue with a left nav link not working because that mdx file had a redirect listed that matched the current working path, this removes it

Remove redundant redirect

---

src/content/docs/apm/agents/net-agent/net-agent-api/guide-using-net-agent-api.mdx

Fixes a broken link mentioned in #5717

fix(APM): Add redirect for broken URL

---

src/content/docs/style-guide/writing-docs/writer-workflow/github-intro.mdx

Adds some more info about docs issues. I'd love some basic feedback to ensure it makes sense :)

Style guide updates and clarification

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

Update dates for EOLs based on new planning

---

src/content/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices.mdx

This is a common question on the forums and in support tickets, so I'm adding it to the docs in the best practices section.

Add instructions on batch job alerts

---

src/content/docs/licenses/license-information/referenced-policies/security-policy.mdx

chore(Licenses): Fixed link

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx

Add new entity query on nerdgraph describing a new filter alertable (See https://newrelic.atlassian.net/browse/ESA-851)
Link to nerdgraph
https://api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20entitySearch%28query%3A%20%22type%20%3D%20%27APPLICATION%27%20and%20alertable%20is%20true%22%29%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20query%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

[ESA-851] Update nerdgraph-entities-api-tutorial.mdx new query with alertable

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

SWA is due out on 1 Feb, there is not yet any documentation for it, and only once it's been available for 4-8 weeks do I plan on starting to announce "sum of" EOL (so folks don't link the two in their minds).
This section can be added back in pretty soon, but right now it needs to go.

Remove reference to SWA and "sum of" EOL

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70204172.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70400172.mdx

This adds the release notes for the Python Agent v7.4.0.172

Release notes for Python Agent v7.4.0.172

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

- fix capitalization
- improve memory chart

minor improvements to dashboard JSON

---

src/content/docs/apm/agents/python-agent/supported-features/certificate-bundle.mdx
src/nav/apm.yml

Co-authored-by: Lalleh Rafeei <lrafeei@users.noreply.github.com>
Co-authored-by: Uma Annamalai <umaannamalai@users.noreply.github.com>
* Add FAQ for certificate bundles in the python agent.

Add python cert bundle customer FAQ

---

src/content/docs/mlops/get-started/intro-mlops.mdx

A few fixes and naming updates.

MLOps: A few style fixes

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

Update EOL date for Outliers

---

src/content/docs/data-apis/ingest-apis/gateway-api-import-data-other-observability-platforms.mdx
src/content/docs/infrastructure/manage-your-data/data-instrumentation/host-integrations-metrics.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx
src/nav/infrastructure.yml
src/nav/telemetry-data-platform.yml

Verifying Beta/EAP/Limited release mentions and callouts.
See DOC-7561.

[DOC-7561] Beta/EAP/Limited sweep

---

src/content/docs/service-level-management/create-slm.mdx

* What problems does this PR solve? Review the recommended queries suggested for APM services and Browser apps to be aligned with the queries provided by the Service Level API.

docs(ServiceLevel): Update APM & Browser recommended queries

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

fix(user migration): fix # typo

---

src/content/docs/style-guide/images/embed-images.mdx
src/content/docs/style-guide/images/screenshots-images.mdx

Also adding a broken redirect.

fix(Style guide): Clarifying storing images

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1230.mdx

Release notes for infrastructure agent 1.23.0

infrastructure-agent release-notes 1.23.0

---

src/content/whats-new/2022/01/whats-new-errors-inbox-browser-mobile-1-20.md

* What problems does this PR solve? This updated users to new features released by the errors inbox team. Please publish ASAP.

"what's new" errors inbox post

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1215.mdx

This PR adds release notes for a small but necessary Browser Agent v1215 Release

browser-agent-v1215.mdx

---

src/content/docs/logs/logs-context/annotate-logs-logs-context-using-apm-agent-apis.mdx
src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx

* What problems does this PR solve? We recently added support for the pino log enricher. This updates our docs to advertise and give steps on how to set up

Updated Logs in Context Node.js docs to include Pino

---

src/content/docs/browser/new-relic-browser/configuration/monitor-or-block-specific-domains-subdomains.mdx

As requested in #documentation.

Browser config - Update tip

---

src/content/docs/infrastructure/host-integrations/installation/secrets-management.mdx

Fix Spacing in json payload for secret creation.

Fix Spacing in json payload

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-integration.mdx

added nrjmx usage in section related to jmxterm which we no longer package. Also added system PATH information in Advanced section.

Add PATH Variable Instruction and Troubleshooting

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

For user mgmt liaison work: 
General improvements to intro to user migration doc
Adding context about option of adjusting user type before migration

User migration improvement about rightsizing users

---

scripts/actions/utils/docs-content-tools/i18n-exclusions.yml

* Landing pages remain and need to be translated. Updating the exclusion file to allow for translation.

Removed the landing page type exclusion

---

src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags.mdx

fix(iOS): Broken link

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-apps-gradle-android-studio.mdx

`compile` has been deprecated for a while now and has been replaced by `implementation` (or `api`). 
* Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.
See [release notes for AGP 7.0](https://developer.android.com/studio/releases/gradle-plugin#dependency-configurations-removed); related [SO thread](https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-api-and-compile-in-gradle).
N/A.

docs: fixed dependency configuration

---

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-641.mdx

* What problems does this PR solve? - release notes for android agent v6.4.1

[Mobile-7423] Android Agent v6.4.1 release notes

---

src/content/docs/data-apis/manage-data/manage-data-retention.mdx

Fixing our data retention requirements because it was ambiguous/wrong on which editions allowed editing of retention.

fix(data retention): improve reqs

---

src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
src/nav/accounts.yml

The 'factors affecting access' doc is hard to find and wanted to improve title for findability/search. And related to some user permissions work I'm doing, I wanted to make that section a little clearer.

Improve the 'factors affecting access' doc 

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

OHI Oracle monitoring: Fixing query, adding warning note

---

src/content/docs/accounts/accounts/saml-single-sign/saml-service-providers.mdx

Fixing anchor links, based on issue https://github.com/newrelic/docs-website/issues/5864.

fix(saml original): fix anchor links

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

See DOC-7006 for more details.

Link to regex capture blog post

---

src/content/docs/browser/single-page-app-monitoring/use-spa-data/use-spa-api.mdx

fix(browser): fix broken link

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3830.mdx

* Adds in release notes for the new version of the New Relic for iOS app

docs: Add in NR for iOS Release notes 3.83.0

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx

CentOS, RHEL, Oracle Linux 8.x (x86)

Fixing Naming Convention

---

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx

I alphabetized this table to improve scannability.

feat(nerdgraph): Alphabetized table

---

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1215.mdx

Originated with issue https://github.com/newrelic/docs-website/issues/5884

fix(browser release): fix wrong date

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Add to usage dictionay

---

src/content/docs/alerts-applied-intelligence/overview.mdx

docs(alerts/overview): added ampersand

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/introduction-alerts.mdx

The UI term is Add a condition.

docs(intro alerts): update UI term

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx

Clarifying steps to create alert conditions

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Make downstream and upstream guidance cover additional connection types.
* This PR solve makes the guidance around downstream and upstream cover more possible connection types.
* https://newrelic.atlassian.net/browse/UIWRITE-1202

Update downstream and upstream in usage guide

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/core-users-release.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/new-relic-products-features/partner-products-pricing-billing.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partnership-accounts-users-subscriptions.mdx

Work: 
• Adjusting user type capabilities with new info about log mgmt capabilities. 
• Editing the 'core pricing transition' guide to give more context about how the free preview period takes precedence over the 7 day grace period, from customer perspective. 
• Fixed broken partnership API docs category links.

fix(user type): adjust log mgmt capabilities

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9500.mdx

.NET agent 9.5.0 release notes

.NET agent 9.5.0 release notes

---

src/content/whats-new/2022/01/whats-new-01-31-io-partner-quickstarts.md

What's new post for I/O partners who have contributed quickstarts between Oct and Dec 2021

feat(whats-new): post for new io partners

---

src/content/docs/style-guide/word-choice/product-capability-feature-usage.mdx
src/nav/style-guide.yml

This is the capitalization guide that's been compiled by people across NR.

style(prod and capability and feature): capitalization and usage guide

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-423.mdx

Fixing version Android v in RN

---

src/content/docs/logs/ui-data/use-logs-ui.mdx

Minor tweaks for some link syntax bugaboos

fix(logs): Fix some messed-up link syntax

---

src/content/docs/style-guide/word-choice/product-capability-feature-usage.mdx
src/nav/style-guide.yml

fix(style guide page): copy edits.

---

src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx
src/content/docs/data-apis/manage-data/manage-your-data.mdx
src/nav/telemetry-data-platform.yml

Tweak reference to title in sidebar and other docs for consistency

chore(manage data): Consistently refer to title on "Estimate data ingest"

---

src/content/docs/service-level-management/faqs-slm.mdx

I'm clarifying the number of SLIs supported in an account

New FAQ about maximum number of SLIs

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-0-0.mdx

This PR includes commits from #5942

kubernetes: add v3.0.0 release notes

---

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx

There are actually 2 NerdGraph tutorials for log management

fix(NerdGraph tutorials list): Add log info

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

Added links to user type and edition style guide pages

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

Added a jump link to the diagram

---

src/content/docs/browser/browser-monitoring/troubleshooting/troubleshoot-your-browser-monitoring-installation.mdx

fix(parser error message): Added another place to escape `@` for JS snippet

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9510.mdx

.NET agent 9.5.1 release notes

.NET agent 9.5.1 release notes

---

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-0-0.mdx

Fixed incorrect release date

---

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx

NFS is supported from v1.16 K8s version (which is the minimum that the integration supports)

Add nfs volumen to supported list K8sVolumeSample

---

src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx

Hi!
Fix some details on GCP logging docs page
Add configuration details for EU customers
Maybe the wording on how to reference the European region accounts is not the best.
Thanks!

Update GCP logging docs

---

src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx

Adds a known .NET async issue into the public doc.

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

super script and fix to infinite tracing.

fix(style guide): change to infinite tracing and fixed tm.

---

src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-app-engine-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-bigquery-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-functions-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-load-balancing-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-pubsub-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-spanner-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-sql-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-storage-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-compute-engine-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-kubernetes-engine-monitoring-integration.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/integrations-custom-roles.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/introduction-google-cloud-platform-integrations.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-app-service-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cosmos-db-document-db-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-mariadb-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-mysql-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-postgresql-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-functions-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-load-balancer-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-redis-cache-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-service-fabric-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-sql-database-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-storage-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-virtual-network-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-vms-monitoring-integration.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/getting-started/polling-intervals-azure-integrations.mdx

EOL callout for Google Cloud Platform, A-C

feat(EOL Q4): GCP

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3.mdx

In southern hemisphere spring is at a different time

Changed spring season by quarter

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx

Adding the missing Windows installation procedure for the Apache integration.

Add nri-apache windows installation.

---

src/nav/infrastructure.yml

See DOC-7701 for more details.

[DOC-7701] ECS: Removing duplicated links

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx

fix(Android): Made the EOL dates consistent

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx

Small addition of link from user type doc to billing/downgrade rules

fix(user type): add link to downgrade rules

---

gatsby-config.js
src/content/docs/style-guide/writing-docs/article-templates/whats-new-template.mdx

Reviewer: 
* Please confirm these two sub-bullets that should clarify what goes into the body of the "What's new" PR.
* I had to use a real tab to indent the code snippet in step 2, but the code snippet in step three used the normal two-space fake tab. This was a workaround to fix failing indentation due to something inside the code snippet. So, the code snippets should have the same indentation (in steps 2 and 3).
* I inserted warnings about using local images only. See the comments in the image section of the first large code snippet (step 2), and then the general section on images later on in the doc. Both explain that users can't link to externally hosted images (on other sites).
* I added isFeatured information in the front matter section.

Clarify "What's new" instructions

---

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx
src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx

See DOC-7696 for more details.

[DOC-7696] Dashboard's Markdown updates

---

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data.mdx

Included information on updating of charts shared using a chart link.

Wording update

---

src/content/docs/data-apis/understand-data/event-data/events-reported-apm.mdx

fix: broken link to category page

---

src/content/docs/style-guide/word-choice/nerdgraph-doc-guidelines.mdx
src/content/docs/style-guide/writing-docs/article-templates/api-tutorial-template.mdx
src/content/docs/style-guide/writing-docs/article-templates/graphql-api-tutorial-template.mdx
src/nav/style-guide.yml

DOC-7731. New doc about how to write NerdGraph docs.

fix(style guide): new nerdgraph style guide

---

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx

Chore: Update trap listener port

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration.mdx

A new version of the Apache integration was launched today which includes a new config setting.
This update reflects the new setting on our docs
Thanks!

Update new setting for Apache integration.

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide.mdx

SLO is not defined earlier in the page. Link to the page where readers can find out more.

include link to SLO page

---

src/content/docs/glossary/glossary.mdx

per agreement with style council.

update to glossary to include golden metrics entry

---

src/content/docs/style-guide/writing-docs/writer-workflow/peer-editor-workflow.mdx

Based on working group, changes to how to determine when to get a review on a PR versus when you can just merge it in.

fix(style guide): PR review workflow

---

src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx

Last week I couldn't get our contributor's collapsers to work without separating this long multi-part example into 2 collapsers. At his request I am going to try again.

chore(collapser edit): Followup previous PR

---

src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md

I noticed that the final link in this post was relative, which means it fails to resolve in the product UI.
I am out of the office on 2/10/2022, but you can publish this if it looks correct.

Make core user post relative link absolute

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

Maximum scrape interval changed from 45 to 40

---

src/content/whats-new/2022/02/whats-new-2-9-external-services.md

Can go out immediately as the feature is already live.
Post was written and approved by Scott Amerman

whats-new external services post dated 02-09-2022

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx

Need help on formatting this - namely the NRQL query. Thanks!

Cumulative histograms are not supported

---

.github/workflows/update-whats-new-ids.yml

Reverts newrelic/docs-website#6084

Revert "Update branch committed to by whats new ID workflow"

---

src/content/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics.mdx
src/nav/synthetics.yml

The title of this doc is a bit confusing/useless. Tweaking to clearly use the word SLA.

chore(synthetic): Tweak SLA report title

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

fix - style guide - update to capitalization and naming info

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

* What problems does this PR solve? Some metrics names were outdated https://github.com/newrelic/nri-oracledb/pull/14/files
links to related docs, screenshots, etc. https://github.com/newrelic/nri-oracledb/pull/14/files

fix(oracleDB): metrics name

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3.mdx

kubernetes: fix typo

---

src/content/docs/style-guide/writing-docs/article-templates/whats-new-tech-writer-tasks.mdx
src/nav/style-guide.yml

Reviewer: Please confirm that these steps for technical writers are clear.
I am out of the office on 2/10/2022, but you can publish this if you think it is clear.

Add tech writer companion steps for "What's new"

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide.mdx

Fixing broken link raised in https://github.com/newrelic/docs-website/issues/6125.

fix(best practice qual foundation): fix link

---

src/content/docs/logs/ui-data/built-log-parsing-rules.mdx

updating grok pattern to match changes pushed to prod today

chore: updating to latest grok pattern

---

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx

With assistance from Brian Hensley we have updated some code blocks for better display.
Previously looked like terminal commands.

docs: Updated code block identifier

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Reverts newrelic/docs-website#5895.
As requested by the team (@Matan2801).

Revert "Removing PagerDuty section"

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1232.mdx

infrastructure-agent release-notes 1.23.2

---

src/nav/kubernetes-pixie.yml

Now the section name is more related to its contents

Changed section name

---

.eslintrc.js
tsconfig.json

Removes eslint from yelling on js files to only yell on ts files

Updates TsConfig for docs

---

src/content/docs/data-apis/manage-data/view-system-limits.mdx

This rate limit documentation is misleading and will no longer be relevant as we move to ingest all customer data.

Remove DT max spans/min/account documentation

---

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx

style(Support): Terminology change

---

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx

As first reported in #5404, and further discussed with the team.

[DOC-7632] Detailing chart export limitations and issues

---

gatsby-config.js
src/content/docs/network-performance-monitoring/advanced/ktranslate-container-management.mdx
src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx

adding notes to NPM docs for new container registry hosting available at `Quay.io`

chore: adding quay.io hosting for NPM docs

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx

This PR is based on GitHub issue #6174.

Remove quick-start section from RabbitMQ doc

---

src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx

fix: corrected spelling of Infrastructure

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx

Based on GitHub issue #6175, I removed the quick-start section.

Remove MongoDB quick start

---

src/content/docs/apm/agents/go-agent/get-started/introduction-new-relic-go.mdx
src/content/docs/apm/new-relic-apm/troubleshooting/cpu-usage-mismatch-or-usage-over-100.mdx
src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
src/content/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action.mdx
src/content/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations.mdx

Removed redirects for pages that had redirects to themselves.

chore: remove self-referencing redirects

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

Correct the extended metrics of nri-oracledb tablespace sample

fix: Oracledb tablespace extended metrics

---

src/content/docs/infrastructure/elastic-container-service-integration/get-started/introduction-amazon-ecs-integration.mdx

Adding mentions to AWS Fargate and ECS Anywhere support in the doc

Enumerating different launch types

---

src/content/whats-new/2022/02/InfraV2-WhatsNew.md

fix(What's new): Fixing image, adding link to docs

---

src/content/whats-new/2022/02/InfraV2-WhatsNew.md

There was an error on the top image.
I added a YouTube video.
I added a One last item at the bottom around filter sets.
This is Kevin Downs - New Relic Infrastructure PMM - kdowns@newrelic.com

Update to the 02162022 infra What's New post

---

src/content/docs/apis/nerdgraph/tutorials/provisions-your-subscriptions-nerdgraph.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/getting-started/partner-integration-requirements.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/new-relic-products-features/partner-products-pricing-billing.mdx
src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partner-api-reference.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-account-object.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-keys.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-sub-account-object.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-subscription-object.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-user-object.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-billing-integration-api.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/product-buckets.mdx
src/content/docs/new-relic-partnerships/partnerships/partner-api/typical-integration-example.mdx
src/nav/new-relic-partnerships.yml

DOC-7753. I didn't end up condensing any docs but did add callouts about availability to API docs. This category is pretty messy and I think for future project we can condense a lot of these and remove some.

fix(partnership api docs): adding req callouts

---

src/content/docs/network-performance-monitoring/setup-performance-monitoring/aws-vpc-flow-monitoring.mdx

* Clarification on some pages of the AWS console

chore: minor NPM doc wording changes

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

We got feedback that our heading and description for one part of this page are confusing. This PR revises that info to help clarify what this section is really conveying.

revision - style guide - fix confusing part

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx
src/content/docs/logs/ui-data/data-partitions.mdx
src/content/docs/logs/ui-data/find-unusual-logs-log-patterns.mdx

Liaison work, includes: 
• Fix to a bad 'Owner' edit I'd made (truth is each account in v1 user model world has an Owner)
• Removed some logs-related roles/capabilities-related info

fix(user mgmt): update 'owner' issue

---

src/content/docs/accounts/accounts-billing/general-account-settings/view-our-ui-dark-mode.mdx
src/nav/new-relic-one.yml

Fixes a broken left nav link and adds a redirect in case that link exists anywhere else.

fix(ui): fix broken dark mode left nav link and add redirect

---

src/content/docs/distributed-tracing/infinite-tracing/introduction-infinite-tracing.mdx

Adds a redirect to close #6060

fix(infinite tracing): add 404 to redirects

---

src/content/docs/apm/agents/go-agent/get-started/introduction-new-relic-go.mdx

fix(go): broken instrumentation link

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3840.mdx

* Adds in latest release notes for iOS Mobile app

doc: Add in release notes for iOS mobile app version 3.84.0

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

fix(k8): update install button

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx

Org/users liaison work: new user upgrade UI now controls all aspects of user type upgrade requests (previously only controlled upgrades to full platform user).

fix(auth domain): edit to user upgrade UI

---

src/content/whats-new/2022/02/InfraV2-WhatsNew.md

The example format for WN URLs didn't work so I'm trying it with this fix

fix(video): url didn't work

---

src/content/docs/agile-handbook/heroing/what-is-a-hero.mdx
src/content/docs/agile-handbook/key-concepts/agile-roles.mdx
src/content/docs/agile-handbook/sprint-mechanics/liaisonships.mdx

Update agile handbook to reflect new liaison model.
Requesting @Broseberg as reviewer for her perspective as manager, and @akristen for her "beginner's mind" perspective as someone newer to the team.

New liaison model

---

src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx

Bullet points were inconsistent for unavailable EU options. Also cleaned up a collapser that previously had an image, with some remaining text referencing it.

Small consistency/clarity edit

---

src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx

Reverts newrelic/docs-website#6203

Revert "Small consistency/clarity edit"

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx

Just fix a small typo in CloudWatch.

docs: Fix typo in CloudWatch

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/apm-metric-alert-conditions.mdx

Edit the doc to clarify that this is also possible with Browser metrics
Since the example is specifically for one use-case, I didn't change anything about that -- only the leading text is changed

Add browser to APM metric alert condition doc

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4260.mdx

new release note for android mobile app version 4.2.6 
Edit as needed

new release note for 4.2.6

---

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx

fix(java): update default DT envvar

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

- example json fixes and improvements

improvements to dashboard example json

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Notifications: Added video for Email vide

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-managing-users.mdx

Accounts: Adding redirect for broken link

---

src/content/docs/accounts/accounts/automated-user-management/azure-ad-scimsso-application-configuration.mdx

Removed duplicate word in introduction

fix(Azure AD SCIM/SSO application configuration): typo

---

src/content/docs/apm/agents/net-agent/getting-started/8x-to-9x-agent-migration-guide.mdx

added some lines of whitespace to help format the xml code example too.

docs: indent example code & add lang identifiers

---

src/content/docs/browser/new-relic-browser/configuration/filter-ajax-request-events.mdx

AjaxRequest events now capture event data

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

We had a request to use original in place of legacy.

new term - style guide - added a preferred term

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/using-new-relic/welcome-new-relic/get-started/get-started-full-stack-observability.mdx

fix(observability): Fixed a couple of broken links

---

src/content/docs/logs/forward-logs/aws-firelens-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs.mdx
src/content/docs/logs/forward-logs/aws-lambda-sending-logs-s3.mdx
src/content/docs/logs/forward-logs/azure-log-forwarding.mdx
src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx
src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/fluentd-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
src/content/docs/logs/forward-logs/google-cloud-platform-log-forwarding.mdx
src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
src/content/docs/logs/forward-logs/kubernetes-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/logstash-plugin-log-forwarding.mdx
src/content/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose.mdx
src/content/docs/logs/forward-logs/vector-output-sink-log-forwarding.mdx

feat(Uninstall logs): Add xref to log forwarder docs

Fixes https://github.com/newrelic/docs-website/issues/4118

---

src/content/docs/apis/rest-api-v2/api-explorer-v2/introduction-new-relics-rest-api-explorer.mdx

Hero request to add a callout.

Add API  explorer callout

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx
src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx

Quick wins after running the scorecard. See DOC-7775 for more details.

Infra updates

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4270.mdx

simple release note for the latest android update
edit as needed

release note for update 4.2.7

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

as requested by style guide supporters.

slight edit - style guide - revised some language in capabilities doc

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx

fix(infra): fix broken link

---

src/data/whats-new-ids.json

The name for this auto-filled, so I'm assuming this is the 2nd merge to main to fix that What's New stuff in daily-release/02-24-22-evening1. 

chore(whats-new-ids): updated ids

---

src/content/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations.mdx

fix(AWS): Fixing links

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Initial doc push for the set up of automatic logging for our NGINX OHI.

NGINX OHI Logs

---

src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx
src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx

To do:
~- Make table more readable~ 
~- Insert `<br>` (or equivalent) to make breaks after listed IPs~ 
~- x2 check that the IPs match info given to me~
~- Write better metaDescription~
~- Ask SME if I should link to DNS information in lieu of listing DNS addresses~
~- Request review from SME~
- Ask tw for feedback on table readability

feat(synthetics): Removed old IP and inserted new IP ranges, new call out, new metadescription

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70600173.mdx

Add Release notes for Python Agent, v7.6.0.173

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx

Remove deprecation callout

---

src/content/docs/apm/agents/python-agent/getting-started/instrumented-python-packages.mdx

Update instrumented Python packages to include Aredis instrumentation

---

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx

Fixing one line in the docs to correct layout

Small update to fix the layout on the Java Agent config file

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1233.mdx

Missing HTTPS:// so was routing to internal docs which results in 404

Update CVE Links to Absolute Links

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Updated the main infra page to float the automatic OHI instructions to the top to encourage adoption. Also clarified the extra step in the corresponding OHI docs.

Updated verbiage

---

src/content/docs/release-notes/service-levels-release-notes/service-levels-20220225.mdx
src/content/docs/service-level-management/consume-slm.mdx
src/content/docs/service-level-management/create-slm.mdx

We're limiting each SLI to one SLO only.

One SLO per SLI

---

src/content/docs/alerts-applied-intelligence/transition-guide.mdx

Add 2023, since some stuff is happening in 2023

---

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-ansible.mdx

* What problems does this PR solve?: Outdated example for Ansible

chore(ansible): updated example and added optional to optional parameters

---

src/content/docs/style-guide/word-choice/nerdgraph-doc-guidelines.mdx
src/content/docs/style-guide/word-choice/usage-dictionary.mdx
src/content/docs/style-guide/writing-docs/processes-procedures/understand-edit-docs-site-structure.mdx

fixes -- style guide -- replacing or referencing terms

---

src/content/docs/apm/applications-menu/events/view-alert-history.mdx

fix(broken link): reported in documentation

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx

chore(add redirect): reported in documentation

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
src/content/docs/style-guide/writing-docs/processes-procedures/create-edit-content.mdx
src/content/docs/style-guide/writing-docs/processes-procedures/create-release-notes.mdx

Another batch of changes for inclusive language fixes.

fix - style-guide - inclusive language

---

src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-bigquery-monitoring-integration.mdx
src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/updated-gcp-bigquery-enable-tables-setting.mdx

Doc for a new configuration field under the Infrastructure GCP BigQuery configuration
Talk to me in slack (ihernandez) for details and internal tickets

feat(GCP BigQuery): added doc for new config field enable table metrics

---

src/i18n/content/jp/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

This is for the file that was pulled out https://github.com/newrelic/docs-website/pull/6376/ because  it was failing to build.
https://github.com/newrelic/docs-website/pull/6376/

chore: fix for borked file in PR 6376

---

src/nav/root.yml

fix(nav): Increase quickstart numbers

---

src/content/docs/mlops/integrations/truera-mlops-integration.mdx

fix(ai): add quickstart redirect

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-654.mdx

Java agent version 6.5.4 release notes.

chore: Java agent release notes 6.5.4

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-cloudtrail-monitoring-integration.mdx

fix(infra): fixes broken link

---

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/soc2.mdx

Updating line item to reflect new certification for Pixie Community Cloud.

Update Pixie: Community Cloud achieving SOC2Type2

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4280.mdx

Release note for NewRelic Android update 4.2.8 
edit as needed

release note for version 4.2.8

---

src/content/docs/security/security-privacy/compliance/hitrust.mdx

Adding content to the HITRUST page.

Adding HITRUST content

---

src/content/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page.mdx

Modified some verbiage for the K8s Summary page docs

Minor verbiage updates

---

src/content/docs/logs/forward-logs/cloudflare-logpush-forwarding.mdx
src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx
src/nav/logs.yml

Adding documentation for Cloudflare Logpush integration.

feat(cloudflare logpush): add new documents

---

src/content/docs/apm/agents/net-agent/net-agent-api/noticeerror-net-agent-api.mdx

Update link to `AddCustomAttribute()` docs

Update link to AddCustomAttribute docs

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx

slide-by interval can also reset condition evaluation

Added extra detail about SWA

---

src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx

Added redirect for broken 404

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Fixing mentions of 'Enterprise' to be 'Pro and Enterprise'

fix(user migration): correct edition error

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/redis-monitoring-integration.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Added an entry so customers can automatically send Redis Logs to NR using our new template file that's bundled with the OHI package.

Added Redis OHI Template Doc

---

src/announcements/docs-engage-banner.mdx

Draft engagement banner for #7615

chore: add OSS engagement banner to doc site

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

per convo with @helenapm and word-nerds.

(update)style: added service levels and workloads to caps page

---

src/announcements/docs-engage-banner.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
src/content/docs/new-relic-one/core-concepts/new-relic-lookout-monitor-your-estate-glance.mdx

Daily release/3 9 22 evening

---

src/content/docs/agile-handbook/sprint-mechanics/sprint-workflow-and-jira-boards.mdx
src/content/docs/style-guide/writing-docs/article-templates/whats-new-tech-writer-tasks.mdx
src/content/docs/style-guide/writing-docs/writer-workflow/github-intro.mdx

Here are some changes to reflect the new review workflow.

fix(style and agile guides): Add changes for new review workflow

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx

Fixing broken link noticed in https://github.com/newrelic/docs-website/issues/6537

fix(user mgmt): fix broken link

---

src/content/docs/security/security-privacy/compliance/hitrust.mdx

Added the official certification date for HITRUST, and incorporated suggested changes by Docs team.

Update official cert date, formatting

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4210.mdx

Release note for update 4.2.10
Edit as needed

release note for 4.2.10 release

---

src/content/docs/infrastructure/amazon-integrations/troubleshooting/aws-service-specific-api-rate-limiting.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/cannot-create-alert-condition-infrastructure-integration.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/cloudwatch-billing-increase.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/invalid-principal-error-unsupported-aws-regions.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/metric-data-delays-amazon-aws-integrations.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/no-data-appears-aws-integrations.mdx
src/content/docs/infrastructure/amazon-integrations/troubleshooting/no-data-metric-streams.mdx

fix(AWS): Fixing some wording

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx

Fixes https://github.com/newrelic/docs-website/issues/6532

fix(xrefs): hero request

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

After watching a customer call and working with solutions consultant @Dkairu, made some attempted improvements to user migration doc.

fix(user migration): some improvements

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

I ran the guide through google doc's spelling and grammar checker to fix various issues.
Spelling and grammar
Copied the whole page into google docs and used the spell checker, then copied in back into github.

Fix spelling and grammer issues

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-coe.mdx

I ran the guide through google doc's spelling and grammar checker to fix various issues.
Spelling and grammar

Fix Spelling and Grammar

---

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/hipaa.mdx
src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/iso.mdx
src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/soc2.mdx
src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/tisax.mdx
src/content/docs/security/security-privacy/compliance/data-encryption.mdx
src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
src/content/docs/security/security-privacy/compliance/hipaa-readiness-new-relic.mdx
src/content/docs/security/security-privacy/compliance/hitrust.mdx
src/content/docs/security/security-privacy/compliance/regulatory-audits-new-relic-services.mdx
src/nav/new-relic-security.yml

Fixing broken links for hitrust docs, and fixed some capitalization issues I saw

fix(hitrust): fixing broken links

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-baselining.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

Fix broken links and add clarity

Jhagan pre sko data gov improvements

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx

Adding v6.5.4 as Java 7 compatible

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

- fix `1e3` to get seconds from milliseconds
- sum first then divide

bug fixes for dashboard example JSON

---

src/content/docs/new-relic-one/install-configure/install-new-relic.mdx

NR Install: Tweaking title, paragraph

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql.mdx
src/nav/dashboards.yml

This PR adds a new doc page to live under https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language/
--
NRDB-3003

arrays in nrql doc

---

src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx

small duplicate word in AUM docs

---

gatsby-config.js

We accidentally merged the korean UI code before it was ready, this will revert that

Remove accidental kr locale addition

---

src/content/docs/logs/ui-data/obfuscation-ui.mdx

Just an idea for having a more top-level summary before getting into details
Just wanted to see if there's a way orient the user first, and then get into the details.

docs(obfuscation): Add preamble

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Alerts: Adding PagerDuty video

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql.mdx

There is a missing 's' in a sentence

Add a missing 's'

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Adding note that logged in users will be logged out when session expired when migration step #5 is completed.

fix(user migration): add note about session expire

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx

We explicitly state the versions tested

Changes on versions supported

---

src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx

This is a very minor edit because a customer didn't think this step was clear enough. Based on the Azure docs instructions - https://docs.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal

docs: clarify how to find app from Azure portal

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx

Add Missing Step to OpenTelemetry Lambda Guides

---

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx

Updated Docker supported versions

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx

We currently don't support SCRAM authentication

Added authentication limitation

---

src/content/docs/security/security-privacy/compliance/data-encryption.mdx

Imported from a forked repo created by @jaclowell.

feat(security): Updates to the data encryption doc

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Updated the Rabbitmq docs to explain how customers can leverage our new logging template file to automatically send logs to NR.

Updated Rabbitmq docs

---

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx

Update public minion IP documentation to add link to new production IP ranges

Update synthetics public minion IPs

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Based on customer calls, trying to improve these SCIM/SAML steps a bit

fix(user migration): clarifying scim steps

---

src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx

The Node.js agent team recently added a working example application for using log enrichers and log forwarders to load your logs in context data to New Relic One.

Added link to Node.js logs in context example application

---

src/content/docs/style-guide/images/embed-images.mdx

Updates style guide doc on adding images to files for aliased images
partially closes https://github.com/newrelic/docs-website/issues/6613

docs: update image style guide doc for aliased images

---

src/content/docs/style-guide/writing-strategies/install-docs-guidance.mdx
src/nav/style-guide.yml

This is an initial first draft of a new style guide doc to provide some guidance on which of our install methods we should point people to.

New style guide doc to provide internal guidance on our install methods

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx

fix(Serverless): Fix SAM/CloudFormation Language (Bad Copy-Paste)

---

src/content/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api.mdx

* Broken link to metric data types

fix(metrics): broken link to metric types

---

src/content/docs/using-new-relic/welcome-new-relic/get-started/networks.mdx

Adds a synthetics URL to let customers know that they must allow this for autocomplete functionality in our NR1 view.

Add Network Section

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx

chore(Kafka OHI): Added redirect

---

src/content/docs/data-apis/manage-data/view-system-limits.mdx
src/content/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup.mdx
src/content/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring.mdx
src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx
src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/updated-optimizations-for-entity-registration-limits.mdx

* We updated the way we handle metrics from new resources when we detect a large amount of new entities to be registered. We are publicly documenting the limits and behavior.

feat(cloud-int): enforcing system limits

---

src/content/docs/using-new-relic/welcome-new-relic/get-started/networks.mdx

Tweaks to Networks doc

---

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx

Add missing description about Symfony 5 support 
* Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.
Implemented in this PR - https://github.com/newrelic/newrelic-php-agent/pull/256

Add support for Symfony 5

---

src/content/docs/style-guide/writing-docs/processes-procedures/use-content-types-text-formats.mdx

Fix simple typo

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4211.mdx

PR for new release note version 4.2.11 
edit as needed

release note for version 4.2.11

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
src/content/docs/accounts/accounts/saml-single-sign/saml-service-providers.mdx
src/nav/accounts.yml

DOC-7780. Work done: 
* Add links to Google SAML SSO for original user model
* Clarifying PingOne isn't available for AUM
* Various readability edits for SAML & AUM requirements

fix(user mgmt): improve scim/saml

---

src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx

Only one Trace Observer can be deploy per region per parent account.

Add context to Trace Observer restrictions

---

src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx

Only one trace observer can be created per AWS region and parent account structure.

Adding context to Trace Observer restrictions

---

src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx

Fix upgrade command

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload.mdx

fix(Alerts): Removed text output option

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1240.mdx

infrastructure-agent release-notes 1.24.0

---

src/content/docs/logs/troubleshooting/find-issues-cause-or-impact-surrounding-logs.mdx

fix(Surrounding logs): No icon

---

src/content/docs/style-guide/writing-docs/writer-workflow/set-up-local.mdx
src/content/docs/style-guide/writing-docs/writer-workflow/tech-writer-workflow.mdx
src/nav/style-guide.yml

I hope this fills a bit of the gap in our set up for new hires.

feat(style guide): New doc about getting set up to build the site locally

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

Some back ticks `` in the code block that shouldn't be there

fix: removing unnecessary backticks

---

src/content/docs/data-apis/manage-data/view-system-limits.mdx
src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
src/content/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits.mdx
src/content/docs/logs/troubleshooting/log-message-truncated.mdx
src/nav/distributed-tracing.yml

https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/introduction-event-api/#limits
https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes/#requirements
https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts/#attribute-lengths

docs: add limit attr key/value length

---

src/i18n/nav/kr.json

Update Korean Nav file with translation

---

src/content/docs/logs/ui-data/built-log-parsing-rules.mdx

Adding an entry into our default parsing rules showing how to leverage our default parsing rule for Rabbitmq

Adding Rabbitmq default parsing rule

---

src/i18n/translations/kr/translation.json

Small translation updates

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/cx-improve-page-load.mdx
src/content/docs/new-relic-solutions/observability-maturity/customer-experience/cx-improve-web-uptime.mdx
src/content/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-baselining.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-forecasting.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-growth.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-intro.mdx

Fix a variety of minor style inconsistencies across the observability maturity docs

style(OMA): Improve formatting consistency

---

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx

Identified while analyzing the docs survey.

fix(NerdGraph): Added link, other minor corrections

---

src/i18n/nav/kr.json

Remove English duplicates: Account setup from previous version

20220324 Nav updates. 

---

src/content/docs/infrastructure/infrastructure-integrations/get-started/use-integration-data-new-relic-dashboards.mdx

fix(EH link): needed full URL

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-9-1.mdx

Node.js Agent v8.9.1 Release Notes

Node.js Agent v8.9.1 Release Notes

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/outlier-detection-nrql-alert.mdx
src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx

Fixes https://github.com/newrelic/docs-website/issues/6764

fix(Outlier EOL): Callout

---

src/content/docs/logs/forward-logs/cloudflare-logpush-forwarding.mdx

Linking the quickstart and blog post where readers can learn more about the partnership with Cloudflare

Adding additional resources to "What's Next"

---

src/content/docs/logs/get-started/new-relics-log-management-security-privacy.mdx
src/content/docs/logs/ui-data/obfuscation-ui.mdx
src/nav/logs.yml

Ready for peer review but please do not merge. Thanks!

style(obfus): prep for ga

---

src/content/docs/codestream/codestream-integrations/notifications.mdx
src/content/docs/codestream/codestream-settings/account-settings.mdx

We added a new setting to control PR notifications, but also noticed that the article was in need of a little overhaul.

Update Notifications article

---

src/content/whats-new/2022/03/whats- new-3-28-pagerduty-integration.md

This post can be published ASAP.
If formatting is correct, it does not require PMM approval - the post was created and submitted by Kai Rostcheck (PMM).

feat(whats-new): PagerDuty integration

---

src/content/whats-new/2022/03/whats- new-3-28-pagerduty-integration.md

Recent pagerduty what's new post was very messed up, fixing bulletpoints and video embed code.

fix(whats-new): fixing brokenness

---

src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md
src/content/whats-new/2022/03/whats-new-03-28-futurestack-22.md

Change title, and set this post to the featured one.

fix(whats new): set FS to featured

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx

Old beta is already deprecated removing references

Removing mentions to old beta

---

src/content/docs/release-notes/service-levels-release-notes/service-levels-20220330.mdx

We're GAing the service levels capability, with a few additions such as the new views and tags. The product docs have already been updated.

New release note to announce the GA

---

src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx

Fixes https://github.com/newrelic/docs-website/issues/6600

fix(Log forwarders): Clarify options

---

src/content/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data.mdx
src/content/docs/data-apis/ingest-apis/event-api/introduction-event-api.mdx
src/content/docs/data-apis/manage-data/manage-data-retention.mdx
src/content/docs/data-apis/manage-data/view-system-limits.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx

Assorted changes, including: 
* Fixing '4096 bytes' to be '4096 characters' for some attribute limits docs
* Implementing some peer edits about data limits UI changes
* StatsD: removing out of date info about metric api limits
* K8s: adding info about support for containers

A series of small-ish changes

---

src/content/docs/apis/nerdgraph/examples/create-widgets-dashboards-api.mdx

Changes " `visualizatio`n" to " `visualization`"

Changes formatting

---

src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx

Support SMEs suggested making the options more visible.

style(Sections): SME request

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-slm.mdx

Removing the initial callout, as the capability is fully supported now.

Service levels are GA

---

src/content/docs/data-apis/custom-data/custom-events/report-custom-event-data.mdx

Fixed a broken link on the /report-custom-event-data page.
* _Fixes a broken link on [this](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/report-custom-event-data) page._
* _Found no open issues relating to this._

Fix broken link

---

src/data/whats-new-ids.json

This is a second evening merge to push up the "What's new" ID to get the post into the UI.

whats-new: updated ids

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-baselining.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

- Added `When to use` callouts for several NRQL operators added in the previous PR.
- We added exercise questions to the baselining and optimizing sections of the guide.  This brings us closer in alignment to the workshop that we will be doing at SKO in April.

chore(oma-data-gov): Added exercise questions to baselining and optimizing sections

---

src/content/docs/data-apis/understand-data/event-data/events-reported-browser-monitoring.mdx

Fix link to createTracer API

---

src/content/docs/style-guide/writing-docs/writer-workflow/tech-writer-workflow.mdx

I wanted to get some content here. It's kind of a placeholder. There may be other useful information we want to add here, but I think this is a good place to start.

feat(style guide): Added a note about GitHub permissions

---

src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx

Some slight improvements to wording and recommendations for permissions-related lack of access to NR.

fix(factors access): some improvements to wording

---

src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx

Fixes inline images in a jp doc that didn't get any style prop added and were multi-line
Related to #6908 
**Before**
**After**

Fix inline images in jp file

---

src/content/docs/apm/agents/net-agent/troubleshooting/lock-contention-appdomain-getdata.mdx
src/nav/apm.yml

Creates a new article of interest for .NET Agent customers experiencing high lock contention in instrumented applications.

Create troubleshooting article for lock contention in .NET Framework applications (publish with 9.7)

---

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9700.mdx

* Adds the release notes for .NET Agent version 9.7.0.

.NET Agent v9.7.0 release notes

---

src/components/TechTile.js

TechTile has wonky images due to the image import changes, this should update the styling

Update mdxType for techtile

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx

fix(Serverless): Fix AMD64 Layer ARNs

---

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx

feat(synthetics): Added references to the new runtime and upgrade methods

feat(synthetics): Added new runtime to manage runtimes doc

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2.mdx

* Adding a note explaining a new capability in StatsD integration.

feat(statsd): add unix socket support

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx
src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1241.mdx

Infrastructure agent 1.24.1 release notes & updates to docs

---

src/content/whats-new/2022/04/whats-new-04-06-api-monitoring-postman.md

This is a PR to change the position of the link for the integration.

Change link position for i/o

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-baselining.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-coe.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-intro.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

There was a very important code block broken (possibly after some recent mass-formatting updates).
I fixed that code block and made a few re-wording change.
Here is an image of the block as it must appear:
Please don't alter the code block or indentation on that one.  There is syntax in that code block that requires the `-` character and unless it is fully left justified there are problems (see current live site).
In addition I made some final wording changes prior to the presentation of this guide at next week's SKO.

chore(oma-data-gov): Fix broken code block

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx

Reverts newrelic/docs-website#6921 as per @mangulonr's request.

Revert "Update kubernetes-integration-compatibility-requirements.mdx"

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration.mdx

Updated TAS supported versions

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-chrome100.mdx
src/nav/synthetics.yml

This is a work in progress, but needs merged into the synthetics-runtime-22 branch only so I can continue working with @akristen on doc updates related to the new synthetics release.

feat(synthetics): Added runtime details for Chrome 100 runtime (hold to publish)

---

src/content/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx

feat(obfuscation): add xref

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-forecasting.mdx
src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

Removes rogue `div` tags from two files to fix serialization error when uploading for translation.
https://github.com/newrelic/docs-website/runs/5843652586?check_suite_focus=true

fix: remove rogue div tags

---

src/content/docs/release-notes/logs-release-notes/logs-22-04-04.mdx

feat(Release note): APM lic

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71000175.mdx

Fix broken internal link

---

src/content/docs/apm/agents/python-agent/supported-features/python-codestream-integration.mdx

Fix links - missing forward slash

---

src/content/docs/synthetics/synthetic-monitoring/getting-started/types-synthetic-monitors.mdx

Changes "...your certificates need renewed." to "...your certificates need to be renewed."

Fixes grammar error

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

Added a "data optimization plan template" lined to google doc https://docs.google.com/spreadsheets/d/1CimLpALwl1Z9f41vzbNWx00bGcED9XPV3s4ROqVEnr0/edit#gid=0

Added data optimization plan template

---

src/content/docs/data-apis/understand-data/new-relic-data-types.mdx

no need to capitalize metrics, events, logs, and traces here

---

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx

- Updating IP range listing for EU accounts

Update Synthetics EU IP range listing

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Adds `variant` prop to icon `img` components to fix styling and link issues

fix: add variant prop to tech tiles to fix styling and link issues

---

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/slm-implementation-guide.mdx

Service Level Management is not a proper noun. Should be lowercase. Same with service level objectives, service level agreements, service level indicators, and service levels.

Service Level Management is not a proper noun. Should be lowercase.

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-mq-integration.mdx

Update AWS MQ documentation to include supported MQ Engines and advise on next steps if one is using rabbitmq

Update AWS MQ documentation to include supported MQ Engines

---

src/nav/telemetry-data-platform.yml

Third attempt to do this (having 'CLA not signed' issue)

Fixing tdp nav file issues

---

src/content/whats-new/2022/04/whats-new-4-18-HITRUST.md

Publish: 4/11 in the morning
No PMM manager review required

feat(whats-new): HITRUST (publish 04-11-22 a.m.)

---

src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx

Correct .NET Agent Azure Site Extension paths

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-best-practices.mdx

Add (short) advance notice that we intend to update the OTLP version from `v0.10.0` to `v0.16.0`.

feat(OpenTelemetry): Add intent to upgrade OTLP notice.

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows.mdx
src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
src/content/docs/apm/agents/manage-apm-agents/agent-data/agent-attributes.mdx
src/content/docs/data-apis/convert-to-metrics/creating-metric-rules-requirements-tips.mdx
src/content/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui.mdx
src/content/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide.mdx
src/content/docs/query-your-data/explore-query-data/query-builder/query-builder-basic-mode.mdx
src/content/docs/query-your-data/explore-query-data/query-builder/use-advanced-nrql-mode-query-data.mdx
src/content/docs/query-your-data/explore-query-data/use-charts/chart-types.mdx
src/data-dictionary/events/Transaction/http.statusCode.md
src/data-dictionary/events/Transaction/httpResponseCode.md
src/data-dictionary/events/Transaction/https.statusText.md

Based on issue https://github.com/newrelic/docs-website/issues/7005. And on convo with node team. Work done: 
added two new attributes to data dictionary. 
Put a reference to the other attribute in the equivalent attributes in data dictionary
changed some example NRQL to use the newer attribute

fix(data dict): add missing http entries

---

src/content/docs/licenses/product-or-service-licenses/new-relic-synthetics/new-relic-synthetics-licenses.mdx

Updated selenium-webdriver version and added got.

feat(synthetics): Updated OSS license details

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Based on liaison work reviewing migration guide, some improvements

fix(user migration): some clarifications

---

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx

From issue https://github.com/newrelic/docs-website/issues/7006.

fix(snmp): removing collapsers in intro

---

scripts/actions/__tests__/check-job-progress.test.js
scripts/actions/check-job-progress.js
scripts/actions/fetch-and-deserialize.js
scripts/actions/send-and-update-translation-queue.js
scripts/actions/utils/translation-monitoring.js
scripts/actions/utils/vendor-request.js

add instrumentation for translation workflow

---

src/data/whats-new-ids.json

This is a follow up merge to get the updated IDs for UI.

What's new: updated ids

---

src/content/whats-new/2022/04/whats-new-4-13-hitrust.md

This post was pulled back on April 12, but it is scheduled to be re-posted on April 13th.

What's new post about HITRUST (Re-publish on 04/13/22 in Pacific AM)

---

src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx

* Update add_method_tracer to talk about comparison with transaction tracer
* Add class method example to add_transaction_tracer
The Ruby agent team was mobbing and this file came up in our discussion 
N/A

chore: Ruby agent team updates to examples and usage

---

src/content/whats-new/2022/04/whats-new-4-14-runtime.md

* This PR notifies the community of the new synthetics runtime
* Still need to add the Youtube embed link in this doc

"Whats new" synthetics nextgen runtime (publish ETA 04-14-22)

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

This is a PR to replace PR #7063 that failed the CLA check.

Fix two OMA typos

---

src/content/whats-new/2022/04/whats-new-4-14-codestream-code-level-metrics.md

add what's new for code level metrics, please publish morning PST.

feat(whats-new): add code level metrics, publish 4/14

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

fixed example with outdated term.

bug fix - we no longer say "Edge"

---

src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx

In this doc update, I've added a wistia link demo video under Error Notifier

Added a demo video

---

src/content/docs/apm/agents/c-sdk/instrumentation/enable-distributed-tracing-your-c-applications.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/instrument-errors-c-sdk.mdx
src/content/docs/apm/agents/go-agent/features/enable-distributed-tracing-your-go-applications.mdx
src/content/docs/apm/agents/go-agent/instrumentation/instrument-go-transactions.mdx
src/content/docs/apm/agents/php-agent/features/distributed-tracing-php-agent.mdx

style(LiC): Delete outdated screenshots

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Hi!
I removed a comment related to our Atlassian-Jira integration, as we have fixed an issue we were having and it is not relevant anymore!

Update for the Atlassian-Jira integration doc

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx

- replace legacy commands with appropriate commands for new runtime

fix: update commands to new names

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
src/content/docs/apm/apm-ui-pages/monitoring/apm-summary-page-view-transaction-apdex-usage-data.mdx
src/content/docs/apm/apm-ui-pages/monitoring/databases-page-view-operations-throughput-response-time.mdx
src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

style(EOL callout): Q1 FY23

---

src/content/docs/apm/agents/java-agent/troubleshooting/large-number-false-positive-security-vulnerabilities.mdx

Improves the wording on the false positives security vulnerabilities page.

chore(java): Update wording on false positives troubleshooting page

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx

chore(K8s): Fixed link

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/whats-new/2022/04/whats-new-4-14-data-updates.md

Edits to existing whats-new post, clarifying more about the data price increase change.

fix(whats-new): edit to price increase wording

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

From user migration meetings, a clarification about the importance of choosing right user migration method at start.

fix(user migration): adding to auto vs guided

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx

Added instructions for customers to use the default logging template that will be included with the Mongodb OHI install/update.

Added Doc for Logging Template

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx

- bold elements should each reside on their own line

attempting to fix missing line breaks

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1242.mdx

Add release notes for infrastructure agent 1.24.2

feat: add release notes for infra agent 1.24.2

---

src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx

style(copyedit): manual not old per SME

---

src/data-dictionary/events/ProcessSample/commandName.md

Adds some context of the command name in Linux environments.

feat: add information about infra agent ProcessSample command name

---

src/content/whats-new/2022/04/whats-new-4-20-removal-of-estimated-costs.md

@zuluecho9 will be handling this Friday morning. Coinciding with this https://github.com/newrelic/docs-website/pull/7173.

 Apr 22, Friday morning: Whats-new: Removal of estimated cost

---

src/content/docs/apm/agents/c-sdk/get-started/apm-security-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/get-started/c-sdk-compatibility-requirements.mdx
src/content/docs/apm/agents/c-sdk/get-started/introduction-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/install-configure/c-sdk-configuration.mdx
src/content/docs/apm/agents/c-sdk/install-configure/docker-other-container-environments-install-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/install-configure/install-c-sdk-compile-link-your-code.mdx
src/content/docs/apm/agents/c-sdk/install-configure/uninstall-remove-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/install-configure/update-your-c-sdk-library.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/enable-distributed-tracing-your-c-applications.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/guide-using-c-sdk-api.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/instrument-errors-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/instrument-transactions-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/instrument-your-app-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/instrumentation/use-default-or-custom-attributes-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/troubleshooting/generate-logs-troubleshooting-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/troubleshooting/no-data-appears-c-sdk.mdx

style(EOL C-SDK): Add callout

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx

* The functions added are currently not supported for NRQL alerting. Conditions registered using these functions will yield incorrect results.

fix: add banned functions for NRQL alerting

---

src/content/whats-new/2022/04/whats-new-4-20-removal-of-estimated-costs.md

Fixing links in the 'estimated cost removal' whats new.

fix(whats-new): fixing links

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
src/content/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence.mdx
src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
src/content/docs/data-apis/manage-data/calculate-data-ingest.mdx
src/data-dictionary/events/NrConsumption/estimatedCost.md

DOC-7903. Noticed a couple more I'd missed. And adding deprecation note to data dict entry.

fix(estimated cost removal): some more

---

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests-legacy.mdx
src/nav/synthetics.yml

(I am working with @akristen on these changes)
- Created a new legacy scripted API page to refer to the older runtime
- Updated the current scripted API page for the new runtime

feat(synthetics): Scripted API doc and examples for the new runtime

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

[https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing/#optimization-through-configuration](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing/#optimization-through-configuration) under the collapsible Mobile section.
Reported in #7221

Update Data Governance Optimize for Android 

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-kubernetes-proxy.mdx

feat: Adding config K8s New Relic Metrics Adapter with a proxy

---

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx

Got some internal feedback that "several" in the intro is ambiguous: Several users? Several keys? Tweaking the intro to create a bit more clarity there.

style(api keys): Incorporate some copy feedback

---

src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx

Added missing closing brace `}`

---

src/content/docs/logs/ui-data/query-syntax-logs.mdx

Trying to make it clearer where/how to quote
* We had a question in #help-logging about how to quote wildcards: https://newrelic.slack.com/archives/CEQGKUQ80/p1650917583457799

Update logging syntax clarifying quoting

---

src/content/docs/new-relic-solutions/new-relic-solutions/create-application-baselines.mdx

Fix Cloud Migration Link

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-java.mdx

We've had customers ask about this. Adding an explanation.

Fix(Serverless): Add Explanation Regarding Fragmented Distributed Traces

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx

Fixes issue #7238 with the addition of some additional line breaks.

Added line breaks

---

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx

Updating K8s version requirements, clarifying and changing the structure
> Before merging we would need to review as well from our side

[k8sVersions] supported versions

---

src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx
src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx

feat(Disable automatic): Link to new doc

---

src/content/docs/apm/agents/manage-apm-agents/configuration/high-security-mode.mdx

I noticed this table did not yet include a mention of log events. @barbnewrelic

chore: Add log event forwarding to high security table

---

src/content/docs/logs/logs-context/disable-automatic-logging.mdx

Updated links to specific agent procedures for disabling automatic logging.

chore(logs in context) - updated links

---

src/data/homepage.yml

Updated the link to point to https://docs.newrelic.com/docs/new-relic-one/install-configure/install-new-relic

feat(homepage): Updated "Start ingesting data" link

---

src/content/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api.mdx

Add note regarding Admin API Key

---

src/content/docs/apis/nerdgraph/examples/provisions-your-subscriptions-nerdgraph.mdx
src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/introduction-mobile-handled-exceptions.mdx
src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-event-trail.mdx

Fixing https://github.com/newrelic/docs-website/issues/7330.

fix(mobile): removing ref to subscription

---

src/content/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes.mdx

Changing limit wording for DPM and Cardinality

---

src/content/docs/apm/agents/net-agent/other-features/net-performance-metrics.mdx

.NET Performance Metrics styling

---

src/content/docs/mobile-monitoring/new-relic-mobile-ios/installation/ios-manual-installation.mdx

Update iOS release notes link

---

src/i18n/content/jp/docs/browser/browser-monitoring/getting-started/browser-summary-page.mdx

An image was deleted along with its import but the image was still being referenced in the file

Remove image reference

---

src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx

Fix typo in java-configure-logs-context-all.mdx

---

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx

fix https://github.com/newrelic/nri-kubernetes/issues/255
Adding missing metrics to nodeSample

feat(k8sMetrics): update missing metrics

---

src/content/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration.mdx

Removes roles that are being removed from the integration installers.
https://github.com/newrelic/nri-ecs/pull/69

Update roles for nri-ecs

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx

* What problems does this PR solve? - update document to include AGP 7 updates

[Mobile-7472] Include AGP 7 updates

---

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-as-code-guide.mdx
src/content/docs/new-relic-solutions/overview.mdx
src/data/homepage.yml

Few typos, and a change of 'attribute dictionary' to 'data dictionary'

fix(guides): typos

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-kubernetes-proxy.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-events-integration.mdx

We are preparing to GA the Kubernetes v3 integration and this is a draft PR where we will iterate the docs before releasing the new version.

GA Kubernetes v3 integration

---

src/content/docs/apm/agents/nodejs-agent/hosting-services/install-new-relic-nodejs-agent-gae-flexible-environment.mdx
src/content/docs/apm/agents/python-agent/hosting-services/python-agent-heroku.mdx

chore(apm): added redirects

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Minor changes to links, title and wording - reducing clicks to downloads

Tarball agent log forwarding

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux.mdx

Now that the log forwarding for tarball install is added, we can link to it

What's next - enable log forwarding

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
src/content/docs/new-relic-solutions/new-relic-one/core-concepts/use-tags-help-organize-find-your-data.mdx

Informs users they can now add tags to alert conditions via the UI

feat: Add alert condition tagging instructions

---

src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
src/content/docs/logs/logs-context/logs-in-context.mdx

feat(new video): as of may 2022

---

src/content/docs/style-guide/writing-strategies/writing-inclusive-content.mdx
src/nav/style-guide.yml

This page was a cross-New Relic project.

style(inclusive language): This commit is the agreed on content

---

src/content/docs/errors-inbox/errors-inbox.mdx

The email notifications feature will be rolled out this week! Submitting a separate PR with the docs for the new feature shortly.

Remove email notifications coming soon callout

---

src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/get-logs-version.mdx

WHERE containerName = 'newrelic-infra'  is incorrect. Should be:
WHERE containerName = 'newrelic-infrastructure'

Correct NRQL for Infra container

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

Documents a new config feature of the integration
https://github.com/newrelic/nri-oracledb/pull/97

doc: add SKIP_METRICS_GROUPS config

---

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
src/content/docs/apm/agents/php-agent/features/distributed-tracing-php-agent.mdx

Adjust documentation to reflect that DT will be on by default.
Add additional clarity for troubleshooting.

feat(php): dt by default

---

src/content/docs/style-guide/word-choice/usage-dictionary.mdx

Clarify at @rhetoric101 's suggestion

chore(style guide): Clarify version number references

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/expanded-anomaly-detection.mdx

There are no more sign ups for expanded anomaly detection

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

update dashboard json example

---

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk.mdx

Solves uninstall issues of the infra-agent in AWS Elastic Beanstalk: https://github.com/newrelic/infrastructure-agent/issues/1134

feat: add uninstall procedure for infra-agent beanstalk

---

src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx

Updated Java config snippets to be more complete/transparent.

chore(logs in context) - update Java config snippets

---

src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx

Updated .NET config snippets to be more complete/transparent.

chore(logs in context) - update .NET config snippets

---

src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx
src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic.mdx

Fixing formatting in original user model doc. 
Fixing broken link in OTel docs

Couple small changes

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/specify-when-alerts-create-incidents.mdx

Replaced old terminology with new terminology, and added a callout at the top which links to an article explaining the new.

Replace old terminology with new

---

src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx

style(logs)

---

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx

style(core)

---

src/content/docs/errors-inbox/errors-inbox.mdx

Tiny fix - OpenTelemetry is one word

---

src/content/whats-new/2022/05/whats-new-5-10-ei-otel.md

add what's new post for errors inbox otel support tomorrow morning 9am pst.

Publish 5/10: errors inbox(whats-new): add ei otel post

---

src/content/docs/apm/agents/c-sdk/get-started/introduction-c-sdk.mdx
src/content/docs/apm/agents/c-sdk/get-started/otel_cpp_example.mdx
src/nav/apm.yml

From @zuluecho9: Related to DOC-7958. This is a WIP by their team. They'll let us know when they're ready for us to review. Leaving this in hero triage column for that reason. 
Original description: With the upcoming EOL of the c-sdk provides a clear example to steer users to c++ otel.

C++ Otel Example

---

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic.mdx

This is a fix of a broken link and a fix that indents code snippets in a procedure.

Fix indentation of snippets and fix link to endpoints

---

src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-210.mdx

Updating the release notes for the new release of the Diagnostics CLI

Add Diagnostics Release Notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx

Couple changes related to deprecation of current month estimated cost.

fix(pricing): edit to deprecation notes

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
src/content/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management.mdx
src/nav/accounts.yml

new(account/user mgmt tutorial): new doc

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

Additional step required to enable integration for slack private channels
* What problems does this PR solve? Clarifying requirements to use private slack channels. Private Channels without the New Relic app doesn't display in the dropdown option when configuring a slack integration.

Slack Private Channels

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-kubernetes-proxy.mdx

Added back the content lost from PR #7269.

feat(k8): added back content

---

src/content/docs/errors-inbox/error-limiting.mdx

Adding an additional troubleshooting message.

---

src/content/docs/apm/transactions/transaction-traces/introduction-transaction-traces.mdx

Just fixing a typo in the product name "Synthetics" :)

fix: Typo in "Synthetics"

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions.mdx

This is a PR to restore an earlier version of this doc because the latest version wasn't ready for publication.

Restore earlier nrai-correlation doc

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

Some formatting consistency fixes

style(nrql syntax): Minor formatting fixes

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx

chore(hero): Delete duplicate step

---

src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx

Intro to NR included no references to NPM

fix(intro to NR): Add references to network monitoring

---

src/content/docs/mobile-monitoring/new-relic-monitoring-react-native/react-native-installation.mdx

Correct spelling of a variable name at step two of React Native Installation guide

docs: correct spelling variable name

---

src/content/docs/query-your-data/explore-query-data/query-builder/nrql-console.mdx

- GA, EAP is over
- Now is disabled by default

New details about NRQL console

---

src/content/docs/style-guide/images/embed-images.mdx

feat(style guide): Removed semicolon from import statement 

---

src/content/docs/release-notes/mobile-release-notes/xcframework-release-notes/xcframework-agent-735.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests-legacy.mdx
src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
src/nav/synthetics.yml

Some updates to our Scripted API docs are needed since the runtime launch. This PR is a place where @bpeckNR and I will be working on draft content. :)

Synthetics follow up

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-otel-applications-kubernetes.mdx

This is a minor follow-up to the publication of the new collector information about K8s.

Clean up bullet list in collector doc for K8s

---

src/content/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs.mdx
src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
src/content/docs/errors-inbox/errors-inbox.mdx
src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
src/content/docs/logs/logs-context/disable-automatic-logging.mdx
src/content/docs/logs/logs-context/logs-in-context.mdx
src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-11-0.mdx

For DOC-7921. Followup for Node.js release notes https://github.com/newrelic/docs-website/pull/7575 and updated Node.js logs in context doc https://github.com/newrelic/docs-website/pull/7458

style(Nodejs LiC): Update xrefs

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions.mdx

Since we pulled back the original NRAI correlation changes in PR #7511, this is a PR to publish those original changes when the product is ready.

Restore AI correlation changes in public doc (Publication date TBD)

---

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx

adding Korean manual translation

---

src/content/docs/new-relic-solutions/observability-maturity/customer-experience/customer-experience-quality-foundation-guide.mdx

Chore: Customer experience quality foundation updated to direct the reader to the quickstarts instead of the oma-resource-center

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-11-1.mdx

Node.js Agent v8.11.1 Release Notes

Node.js Agent v8.11.1 Release Notes

---

src/content/docs/apm/agents/net-agent/attributes/net-attribute-examples.mdx

docs: add language identifiers for xml

---

src/content/docs/apm/agents/net-agent/attributes/enable-disable-attributes-net.mdx

docs: add xml language identifiers

---

src/content/docs/apm/agents/net-agent/troubleshooting/no-browser-data-appears-net.mdx

docs: add xml lang identifier

---

src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx

docs: add shell cmd lang identifier

---

src/content/docs/apm/agents/net-agent/troubleshooting/net-agent-reports-handled-errors.mdx

The C# was indented a little funny.

docs: format code and add lang identifiers

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/nav/accounts.yml

Assorted small edits related to peer edits.

fix(user tutorial): peer edits

---

src/content/docs/apm/agents/java-agent/additional-installation/install-new-relic-java-agent-docker.mdx

The docs refer to an 'enabled' configuration, but I think the setting has been updated to 'agent_enabled' according to the sample yaml file.

docs: Update 'enabled' configuration to 'agent enabled'

---

src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx

This PR adds the correct Logs TCP endpoint for EU region accounts.
The endpoint is already available and being used but it's not on the documentation.
No

Add logs TCP endpoint for EU region accounts

---

src/content/docs/new-relic-solutions/get-started/networks.mdx

feat(nrsolutions): added alternative port

---

src/content/docs/licenses/overview.mdx

brand update

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/user-settings.mdx
src/nav/alerts-and-applied-intelligence.yml

This is for the grace period and inactive issue settings.

A new draft for the AI settings page (DOC-7867)

---

src/content/docs/logs/logs-context/configure-logs-context-go.mdx

docs: add golang identifier to codeblocks

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/specify-when-alerts-create-incidents.mdx

Changed the rest of this doc last week but forgot the title
Issue preference nomenclature has changed, as well. Edited to reflect that.

Change title and description, change names

---

src/content/docs/mlops/get-started/intro-mlops.mdx

machine learning operations is not a proper noun. removed capitalization to be consistent with style guide

machine learning operations should be lowercase

---

src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag.mdx
src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag.mdx
src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-220.mdx

This documents the release of version 2.2.0 of the Diagnostics CLI, adding a new command line flag `-include`. Also cleaning up related documentation and removing invalid command line flags.

feat: Updating Diagnostics CLI docs for v2.2.0

---

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx

* Corrected some sample code highlighting issues
* Updated references to max_stored_samples

Updating Java Logs in Context feature and config pages

---

src/content/whats-new/2022/05/whats-new-5-18
src/content/whats-new/2022/05/whats-new-5-18.md

This post needs to go live at 8:00AM PST on Wednesday, May 18. 
This post does not need to be reviewed by a PMM.
There are no image files, just an embedded youtube video.

"What's New" FutureStack livestream (Publish 8:00 am PST May 18, 2022)

---

src/content/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic.mdx
src/data/whats-new-ids.json

Daily release/5 18 22 noonish

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence.mdx

I added two demos to the environment section of the doc.

Added demos

---

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx

I added a new demo for Event Bridge under the AWS Event Bridge collapser.

Added demo wistia link

---

src/content/whats-new/2022/05/whats-new-05-18-k8s-v3-integration.md

No PMM review required.
No image associated with this post.
Please publish at 9 am PST on 5/18

5/18: feat(whats-new): add v3-integration post

---

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-puppet.mdx

See https://forge.puppet.com/modules/newrelic/newrelic_infra

Updated requirements to match docs on Puppet Forge

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1250.mdx

Release notes for the new infra agent version

infrastructure-agent release-notes 1.25.0

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration.mdx

This PR is documenting the new flag TIMEOUT that has been added to the Newrelic Consul Integration.

Add the new timeout flag to the consul documentation

---

.github/workflows/manual-add-files-to-translation-queue.yml

fix: Add missing $

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3870.mdx

* Adds in release notes for the latest version of the New Relic for iOS app

doc: Add in release notes for version 3.87.0 of the iOS app

---

package.json
yarn.lock

Upgrading to the latest theme version

fix: theme bump

---

src/content/docs/new-relic-solutions/new-relic-one/install-configure/install-new-relic.mdx

Replace stacked nerdlet page with I/O page.

Change EU url for i/o

---

src/content/docs/accounts/accounts-billing/general-account-settings/intro-account-settings.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Assorted small edits from across day.

Zach's small edits may 20

---

src/components/Select.js

Closes https://github.com/newrelic/docs-website/issues/7718

Specify font and color for select options in firefox

---

src/content/docs/apm/agents/net-agent/installation/update-net-agent.mdx

docs: add language identifiers to code

---

src/layouts/MainLayout.js

also added the antialiasing style zack suggested which stops the font from looking bold at all weights

Increase font from 16 to 18px

---

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts.mdx

- Originally reported under #7091 
- Fixes the REST API example provided in the public docs

docs(Alerts): Fix REST API example for #7091

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

removed `--devel`  as it is not needed anymore

---

src/templates/whatsNew.js

Add edit page button to whats new pages

---

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Small typo sing -> using

---

src/components/HomepageBanner.js
src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Fixing some docs links to the UI install pages

---

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence.mdx

I just changed singletone to singleton as it was a spelling error.

Corrected spelling

---

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/use-tags-help-organize-find-your-data.mdx

Fix some awkward nesting and indentation

style(tags): Fix indentation issues

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4320.mdx

Mobile apps release notes for Android app v4.3.2

---

src/content/docs/logs/troubleshooting/find-issues-cause-or-impact-surrounding-logs.mdx

docs: Update Solution in Surround Logs feature
Step 4 solution in https://docs.newrelic.com/docs/logs/troubleshooting/find-issues-cause-or-impact-surrounding-logs/ is no longer accurate.
I worked with NR support (https://support.newrelic.com/s/case/5008W00000oaArHQAU/trouble-with-the-surrounding-logs-feature) to find a clearer way to explain this feature.
Also added a Step 5 so that it is clear to users what the expected behavior will be after clicking "Show surrounding logs"

docs: Update Solution in Surround Logs feature

---

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx

Fix for issue in DOC-7839
Closes #6533

chore(node.js): Fix broken anchor links (DOC-7839)

---

src/content/whats-new/2020/10/applied-intelligence-now-features-accelerated-suggested-decisions.md
src/data-dictionary/events/NrAiSignal/NrAiSignal.event-definition.md

Fix the last two instances of alerts branding for https://newrelic.atlassian.net/browse/DOC-6132

style(alerts): Fix some old alerts branding

---

src/content/docs/codestream/start-here/codestream-new-relic.mdx

CodeStream is no longer a preview.

feat(CodeStream): Removed preview callout

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1260.mdx

Release notes for the infrastructure agent 1.26.0 (hold for release 05-26-22)

---

src/nav/root.yml

Update sidebar number of quickstarts and integrations from 450 to 470 

---

src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx

I'm not sure this will work, these are not used often and my code editor doesn't recognize them. I also made some minor edits to page like capitalization and backticks.

docs: expermiment with razor/aspx lang identifiers

---

src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx

Remove unused span

---

gatsby-config.js
src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx

A quick followup to #7795 @brnhensley

feat(browser): Add razor language syntax

---

src/content/docs/accounts/accounts-billing/account-setup/downgradecancel-account.mdx
src/content/docs/accounts/accounts-billing/account-structure/account-id.mdx
src/content/docs/accounts/accounts-billing/account-structure/add-accounts.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
src/content/docs/accounts/accounts/automated-user-management/tutorial-manage-users-groups-scim.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
src/content/docs/apis/nerdgraph/examples/nerdgraph-user-mgmt.mdx

'Organization and access' UI was changed to 'Access management'.

fix(user mgmt): change UI to 'access mgmt'

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-13-1.mdx

Node.js Agent v8.13.1 Release Notes

Node.js Agent v8.13.1 Release Notes

---

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx

fix: add expected status code env variable

---

src/components/FindYourQuickstart.js

Requested by @louisleungk 
Updates the number of quickstarts on the home page

fix(home): update number of quickstarts

---

src/components/FindYourQuickstart.js
src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx

Daily release/5 31 22

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1270.mdx

Release notes for the new infra agent version

newrelic-infra-agent 1.27.0

---

src/content/docs/release-notes/mobile-release-notes/xcframework-release-notes/xcframework-agent-736.mdx

Added iOS XCFramework Agent version 7.3.6 release notes.

---

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx

ref:
* https://nodejs.org/en/about/releases/
* https://github.com/newrelic/node-newrelic/releases/tag/v7.0.0

docs: add details around Node 14 support

---

src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx

- works with new newrelic.com website

Update scripted browser example

---

src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx

New 'active sessions limit reached' message on login.

feature(active sessions): new doc addition

---

src/components/FindYourQuickstart.js
src/i18n/translations/en/translation.json
src/pages/index.js

adding a `pageTitle` to the `translations.json` for en

fix: add home page title to translations json file

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

fix: query typos

---

src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide.mdx

Fixes https://github.com/newrelic/docs-website/issues/7839

fix(hero): broken link

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx

Small typo fix

---

src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx

From help-documentation slack. The "What is observability" blog post pointed to https://docs.newrelic.com/docs/full-stack-observability but there was no redirect. See also DOC-7617

chore(Hero): Add redirect URLs

---

src/content/docs/logs/ui-data/obfuscation-ui.mdx

Request to add more clarification that some obfuscation is automatically done.

fix(log obfuscation): clarify some obfuscation already done

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx

Remove strange self-referential links

chore(k8s): Remove self-referential collapser links

---

src/content/docs/logs/ui-data/built-log-parsing-rules.mdx

style(Hero): Consistency

---

src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx
src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-660.mdx

* What problems does this PR solve? - Update dexguard support version for release 6.6.0

[Mobile-7496] Update dexguard support version (hold for v6.6.0)

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/data-apis/manage-data/manage-data-retention.mdx

Work done: 
Adding Data Plus column so data retention is more comparable. 
Finessing description of how Data Plus adjusts retention.

fix(retention): clarifying DP retention

---

src/content/docs/data-apis/manage-data/manage-data-retention.mdx

Fixing based on https://github.com/newrelic/docs-website/issues/7820

fix(retention): adding edition required

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-14-0.mdx

Node.js Agent v8.14.0 Release Notes

Node.js Agent v8.14.0 Release Notes

---

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx

AWS Linux 2 has been modified to Amazon Linux 2.

Correct OS name

---

src/content/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits.mdx

Fixes https://github.com/newrelic/docs-website/issues/7539

style(Trace limits): Added link to h2

---

src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx

Fixes a small mistake in APM intro

quick intro fix

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx

Based on issue https://github.com/newrelic/docs-website/issues/7714

fix(rabbitmq): link to explain settings

---

src/nav/browser.yml

chore(Browser API): delete nonexistent page

---

src/content/docs/codestream/how-use-codestream/performance-monitoring.mdx

A few other minor edits for clarity. Thanks!

Don't use possessive New Relic's

---

src/content/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent.mdx

Fixes a couple of poorly formatted links

chore(PHP): Fix messed-up links

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx

Adding troubleshootings steps as other integrations

doc: add vsphere troubleshooting 

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4400.mdx

New Relic Android app release notes for v4.4.0

---

src/content/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring.mdx

This is a follow-up PR to GitHub issue #7748.

fix(Browser): Insert new row for PageViewTiming

---

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring.mdx
src/data-dictionary/events/ContainerSample/cpuLimitCores.md
src/data-dictionary/events/ContainerSample/cpuShares.md

Closes https://github.com/newrelic/nri-docker/issues/85.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add support for cgroups V2 and refine a couple of metric descriptions.

Add docker support for cgroups V2

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx

was getting NodeAffinity: got "boolean", expected "map" error with the previous option.

affinity set to false instead on nodeAffinity

---

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1271.mdx

Release notes for infrastructure agent 1.27.1

---

src/content/docs/logs/ui-data/query-syntax-logs.mdx

See https://discuss.newrelic.com/t/does-the-logger-allow-search-query-params/182059/2

feat(Logs query): Example

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71200176.mdx

Adds python agent release notes for v7.12.0.176

Add Python Agent Release v7.12.0.176

---

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx

Do not merge. Once the corresponding features of the agent are released the PR will be updated to remove the draft state.

feat: new infra agent log options

---

src/components/HomepageBanner.js

closes https://github.com/newrelic/docs-website/issues/7871

Make banner button white on hover

---

src/components/HomepageBanner.js
src/layouts/MainLayout.js

Japanese and Korean characters are spilling out of the banner on mobile, this updates the height so it can grow as needed

Make banner height dynamic

---

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
src/content/docs/security/security-privacy/compliance/hipaa-readiness-new-relic.mdx

Added to HIPAA and FedRAMP docs about the Data Plus requirement. After talking to Fedramp SMEs, copied wording from fedramp to HIPAA doc.

Data Plus: add to HIPAA and FedRAMP docs

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
src/content/docs/data-apis/manage-data/view-system-limits.mdx
src/content/docs/synthetics/synthetic-monitoring/using-monitors/monitor-limits.mdx
src/nav/synthetics.yml

Liaison work, updating pricing and synthetics docs to make the synthetic check limits more clear. 
Also adding in data plus price point.

fix(synthetics): making limits more clear

---

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71200176.mdx

* Slight corrections to release notes. Blacklist settings have never appeared in the agent, avoiding confusion by removing the mention of them.

Python Release Notes Corrections

---

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-14-1.mdx

Node.js Agent v8.14.1 Release Notes

Node.js Agent v8.14.1 Release Notes

---

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/manage-pixie-memory.mdx
src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/get-pixie-logs.mdx
src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/high-memory-consumption.mdx
src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/pods-frequently-oomkilled.mdx
src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/pods-stuck-pending.mdx
src/content/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/get-logs-version.mdx
src/nav/kubernetes-pixie.yml

Adds a troubleshooting section to the Pixie docs.

(feat)Pixie: add troubleshooting section

---

src/content/docs/apm/agents/python-agent/supported-features/python-codestream-integration.mdx
src/data-dictionary/events/Span/code.filepath.md
src/data-dictionary/events/Span/code.function.md
src/data-dictionary/events/Span/code.lineno.md
src/data-dictionary/events/Span/code.namespace.md

This PR updates links in the data dictionary and Python agent CodeStream integration docs.

Fix broken CodeStream links.

---

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3065.mdx

cpm release notes for release 3.0.65

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
src/content/docs/data-apis/manage-data/calculate-data-ingest.mdx
src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx
src/content/docs/logs/get-started/get-started-log-management.mdx
src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx

Disregard. Liaison work of adding more links to cost estimate doc

Add more links to important cost estimate tool

---

src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
src/content/docs/errors-inbox/errors-inbox.mdx
src/content/docs/logs/logs-context/disable-automatic-logging.mdx
src/content/docs/logs/logs-context/logs-in-context.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71200176.mdx

Minor consistency edits for NR-18670

style(Python logs in context): xrefs

---

package.json
scripts/getNavForTranslation.js

This is a script for generating a list of all nav titles to be sent for translation

chore: Add translation nav script

---

src/i18n/nav/kr.json

Updated JSON file for Korean site.

Updated KR nav file

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx
src/content/docs/logs/ui-data/built-log-parsing-rules.mdx

Cassandra default parsing rule

---

src/data/external-redirects.json

Updates docs.newrelic.com/jira jira template shortlink for new jira instance

chore(redirects): Update jira shortlink

---

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/browser-monitoring-nodejs-agent.mdx

We don't have `pug`/`jade` as an identifier option yet, but I put it there for if it's added in the future.

docs: format code and add identifiers

---

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-vm-measurements.mdx

docs: cmd line formatting

---

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-v1-custom-instrumentation-legacy.mdx

Hopefully nobody is using this page anymore, but it can at least be pretty

docs: add semicolons and identifiers

---

src/content/docs/distributed-tracing/infinite-tracing/introduction-infinite-tracing.mdx

This update removes "advanced" and any language that implies that Infinite Tracing is a more complex product.

Update Intro to Infinite Tracing

---

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx

Remove bonus "script" reference

---

src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx

Add a note that calls out egress costs that can result from infinite tracing.

Update Technical distributed tracing details

---

src/content/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api.mdx

Update query to export Dashboard and create troubleshooting section.
* This PR has the follow up changes suggested by @mufaddal7. We (Dashboard team)  completed his suggestion, covering the missing use cases. 
* We also added a troubleshoot section for a common timeout error.  
https://github.com/newrelic/docs-website/pull/5774

Update query to export Dashboard

---

src/content/docs/apm/agents/java-agent/guided-install/java-guided-installation.mdx

fix(Java Agent): advanced usage updates pointing to interactive install

---

src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx

fix(global support): made changes requested by Gayle

---

package.json
yarn.lock

chore: bump theme to 6.2.0

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx

Additions related to tiered pricing for billable users, which is set to go out 6/15 for some customers. Confirm release is going out before publish.

Tiered pricing (Publish on 6/15/2022)

---

src/content/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api.mdx

Add source map applicationID guidance 

---

src/i18n/content/kr/docs/errors-inbox/errors-inbox.mdx

Fixed title

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-780.mdx

Please do no merge until 2022-06-16
Java Agent 7.8.0 Release notes

Create java-agent-780.mdx | Publish 06-16

---

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx

Updates for Java Agent 7.8.0 Release | Merge 6/16

---

src/content/docs/browser/single-page-app-monitoring/get-started/introduction-single-page-app-monitoring.mdx
src/content/docs/style-guide/writing-docs/article-templates/api-tutorial-template.mdx
src/i18n/nav/kr.json
src/nav/apm.yml

I was looking for something else and ran across this annoying typo.

style(typo): Compatability

---

src/content/docs/codestream/how-use-codestream/performance-monitoring.mdx
src/content/docs/codestream/how-use-codestream/pull-requests.mdx

1. Added some additional requirements for code-level metrics.
2. Removed an extraneous section of the pull requests article that I completely overlooked in my previous update.

Additional reqs for CLM

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

change "New Relic One" product name to "New Relic" in some places in the table that were missed

change "New Relic One" product name to "New Relic"

---

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx

- used vs free for swap memory

improve swap chart

---

src/content/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing.mdx
src/content/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-and-dt.mdx
src/content/docs/mobile-monitoring/new-relic-mobile-ios/get-started/new-relic-ios-and-dt.mdx
src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/configure-serverless-monitoring-aws-lambda.mdx

We want to highlight Infinite Tracing as a recommended feature.

Highlight Infinite Tracing

---

src/content/docs/style-guide/writing-docs/writer-workflow/github-intro.mdx

Made some clarity edits in our style guide for hero'ing. :)

feat(style guide): added clarity on docs issue candidate, removed backticks on hero

---

src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx

docs: add language identifiers to codeblocks

---

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring.mdx

style(mobile): typo edit

---

src/content/docs/logs/logs-context/disable-automatic-logging.mdx

The current expression is translated by machine translation into a very negative sentence, and it is translated in such a way that automatic log forwarding should not be used.
Therefore, we have changed it to a more easily translatable English sentence.

Correction of wording

---

src/content/docs/apm/agents/go-agent/installation/install-new-relic-go.mdx

docs: add language indetifiers

---

src/content/docs/apm/agents/go-agent/configuration/go-agent-logging.mdx

docs: add go lang indentifier

---

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx

Signed-off-by: Alvaro Cabanas <acabanas@newrelic.com>
Co-authored-by: carlossscastro <ccastro@newrelic.com>
This PR adds documentation on configuring namespace filters to our Kubernetes integration.
This feature will be released soon.

Adding namespace filters to K8s integration

---

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-780.mdx

* What problems does this PR solve?  Fix download link

Fix Java Agent 7.8.0 download link

---

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
src/content/docs/synthetics/synthetic-monitoring/using-monitors/monitor-limits.mdx

Clarifying about synthetic limits for editions
Clarifying that user migration loses old roles and they must set up new ones

fix(user mgmt): various liaison changes

---

src/content/docs/accounts/accounts/saml-single-sign/saml-service-providers.mdx

Adding 'recommended' to the email bypass in SAML docs, not 'optional'.

fix(saml): email bypass

---

src/content/docs/style-guide/formatting/code-examples.mdx

We need to clarify how writers and contributors can confirm that the site supports their language formatting.

Revise prism information

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx

Fixes https://github.com/newrelic/docs-website/pull/6637

style(typo): Old PR

---

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/understand-use-data/overview.mdx

For New Relic style and brand voice, we don't use "New Relic's".

minor changes for style (don't use New Relic's)

---

src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx

previously missed instances of New Relic One changed to New Relic

---

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx

Add capabilities to create-stack example

---

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx

Add note about AWS Elastic Beanstalk compatibility for .NET

---

src/content/docs/codestream/how-use-codestream/performance-monitoring.mdx

Additional code-level metrics requirements.

More CLM requirements

---

src/content/docs/data-apis/manage-data/view-system-limits.mdx

* APM apps/services: 10K per second - This does not really help. Either we add some explanation on what this meant or remove this. AFAIK, the agents continue to report at various harvest cycles. So the per second part is something that does not really explain what it is
* What problems does this PR solve? - Clarity in documentation
links to related docs, screenshots, etc. - Added details

Remove - APM apps / services per second

---

src/content/whats-new/2022/06/whats-new-6-23-node-python-apm-agents-logs-update.md

Please publish the morning of 6/23/2022
Node.js and Python APM agents will include automatic logs in context.
This will inform our customer of potential billing impact of the changes and what actions they need to take before and after the change.
NOTE: This post doesn't need a review by a product marketing manager

"What's new" APM Node & Python agents (Publish the morning of 6/23/2022)

---

src/content/docs/infrastructure/host-integrations/host-integrations-list/nfs-monitoring-integration.mdx

* Customer feedback: added info showing how to disable NFS integration.

How to disable NFS integration

---

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-albnlb-monitoring-integration.mdx

Add requestcountpertarget to aws docs

---

src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx

Quick browser typo fix

---

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx

Add CSP consideration for src-image

---

src/content/docs/new-relic-solutions/observability-maturity/innovation-growth/development-release-quality-guide.mdx

Minor fixes to release quality

---

src/i18n/translations/en/translation.json
src/pages/index.js

add popular search words to translation files

fix: add popular search items to translations json

---

src/content/docs/apm/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent-api.mdx

According to Liz Baker this should work with prism
https://newrelic.slack.com/archives/C0DSGL3FZ/p1656088120286569?thread_ts=1655750707.035529&cid=C0DSGL3FZ
It doesn't work in the GitHub preview so I'm waiting for a build to see if this works properly in the live site

docs: fix language identifier, aspx->aspnet

---

src/content/docs/apm/agents/net-agent/net-agent-api/getagent.mdx
src/content/docs/apm/agents/net-agent/net-agent-api/getlinkingmetadata-net-agent-api.mdx

docs: add language identifiers

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx

- Use of "limited support" phrase could induce to confusion, as we use the same words elsewhere to mean "unsupported"

k8s/controlplane: clarify wording on managed clusters

---

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4500.mdx

New Relic for Android app release notes: v4.5.0

---

src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx
src/content/docs/alerts-applied-intelligence/notifications/intro-notifications.mdx
src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
src/nav/telemetry-data-platform.yml

LInks to new AI nerdgraph docs from AI docs. 
Fixing messed up nav link

June 27   zach - some small changes

---

src/content/docs/browser/new-relic-browser/troubleshooting/troubleshooting-session-trace-collection.mdx

Adding a link from this troubleshooting doc to the subject matter page.
The current troubleshooting page does not link to the page describing the topic of this troubleshooting. 

Add link to subject matter

---

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/data-governance.mdx

Added some additional information about the data discarded when namespaces are excluded.

More information about namespaces filtering

---

src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
src/nav/telemetry-data-platform.yml

new(historical data exports): new doc

---

src/content/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration.mdx

Clarifying installation sentence

 Clarifying installation sentence ecs

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx
src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx

Better explanation. 
Additional callout to user migration doc.

fix(capabilities): fix explanation

---

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx

Suggest segmenting data into multiple accounts to enable creation of data boundaries.

Segmenting data into multiple accounts

---

src/content/docs/apm/agents/python-agent/getting-started/instrumented-python-packages.mdx
src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71400177.mdx

This PR adds release notes for 7.14.0.177 and updates the python instrumented packages list.

Python agent release  7.14.0.177
