newrelic/docs-website

package.json, scripts/fetch-docs.js, yarn.lock
A small script that gets a JSON representation of different content types from the docs site and creates `mdx` files for each. The implementation has a lot of gaps, but it should serve as a starting point and can help us think through upcoming hurdles.
The general flow for this script is:
1. Get the docs. We're using `node-fetch` library to help make the request.
2. Create the directory structure. Turn the URL path into a directory structure (excluding the slug).
3. Create a file for each doc.
4. Create frontmatter based on content type. We have some _very_ basic fields based on the proposed MDX files.
5. Add the content to the file.
6. 🎉 
* Closes #52
=> Prototype Script To Fetch Docs & Create MDX Files

scripts/constants.js, scripts/fetch-docs.js
Rather than using a hard-coded set of IDs, the script can now fetch a batch of docs by content type. This is done by using a new endpoint available in the dev instance (`/list`).
The script now brings over 10 of each content type. Gatsby will start, but there is some additional cleanup that needs to be done to these new files (out of the scope of this PR).
=> Dynamically fetch docs

package.json, scripts/constants.js, scripts/convert-docs.js, scripts/converters/to-markdown.js, scripts/create-directories.js, scripts/fetch-docs.js, scripts/migrate.js, scripts/utils/get-categories.js
This PR moves the logic for our migration script into separate files, sets up a `yarn migrate` script, and makes it easier to convert docs to _other_ formats.
This is a hefty PR, but it's mostly just moving the existing logic around.
=> Migration Script Refactor

scripts/convert-docs.js, scripts/converters/to-json.js, scripts/create-index-pages.js
Adds support for converting docs into JSON (rather than markdown). This is done for any doc with the `type` of `attribute_definition`. This also prevents index pages for being created for those directories.
In an upcoming MMF, we should look at how we want to display these on the site. It would be nice if Gatsby could serve the JSON.
* Closes #46
=> Support for Attribute Definitions

scripts/constants.js, scripts/convert-docs.js, scripts/converters/to-markdown.js
Closes #53 
I created a new JSON resource type for `landing_page` (similar in shape to `page` resource) and updated the migrate script to request content from that resource and create index.mdx files in same directory it would normally write the file. This runs before the script automatically creates index files, so the script skips writing an index file when it finds an existing index file.
I wonder if it might be good to eventually add something in the script that says if there's already an `index.mdx` file, create another file that contains the menu and call it something like `index-toc.mdx`.
For now, the landing pages just use the `basicPage` template.
=> Add authored directory index pages

package.json, scripts/utils/codemod/jsx.js
Simplifies the JSX transform by using @babel/core instead of the separate babel packages. This also means the codemods will be fully compatible as a babel plugin.
=> Simplify JSX codemod transform

package.json, scripts/converters/to-markdown.js, yarn.lock
Keep `<div>`, `<table>`, and `<dl>` tags in the markdown files during migration. These will be used to convert into components later on.
* Closes #33
* feat: converting problematic HTML to JSX
* chore: keeping `dl` tags for future component work
=> Convert HTML to JSX during migration

src/components/MDXContainer.js, src/templates/basicDoc.js, src/templates/releaseNote.js, src/templates/releaseNotePlatform.js, src/templates/whatsNew.js
Closes  #68 
Adds an `MDXContainer` component that will be used to wrap the markdown content with styles + usable components.
=> Create an MDXContainer component that wraps markdown

package.json, src/components/MDXContainer.js, yarn.lock
* Adds `<Callout />` component to `MDXContainer`
* Bumps `@newrelic/gatsby-theme-newrelic` to current version to use newly added `<Callout />` component
Note that when using it in a .mdx file you have to pass the variant prop as a string and not the static variable.
=> feat: add callout to MDXContainer via theme

scripts/utils/htmlToMarkdown.js, src/content/docs/agents/go-agent/index.mdx, src/content/docs/agents/java-agent/index.mdx, src/content/docs/agents/net-agent/index.mdx, src/content/docs/agents/nodejs-agent/index.mdx, src/content/docs/agents/php-agent/index.mdx, src/content/docs/agents/python-agent/index.mdx, src/content/docs/agents/ruby-agent/index.mdx, src/content/docs/alerts-applied-intelligence/index.mdx, src/content/docs/infrastructure/index.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/android-app/android-app-ui.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/ios-app/introduction-ios-mobile-app.mdx, src/content/docs/plugins/index.mdx
Ensures icons remain inside the `i` tag with the `className` to ensure we can migrate these more easily in the future.
=> Keep icons inside the `i` tag

codemods/clamshells.js, codemods/index.js, codemods/utils/mdxast.js, scripts/utils/migrate/html-to-markdown.js, src/content/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-infrastructure/no-data-appears-infrastructure.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/android-app/introduction-new-relic-android-app.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/authentication-alerts/alerting-new-relic-mobile-apps.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/authentication-alerts/user-settings-authentication.mdx
Closes #81 
Adds a codemod to migrate clamshells over to the `Collapser` component.
=> Clamshell migration

amplify.yml, gatsby-config.js, plugins/gatsby-source-data-dictionary/gatsby-node.js, src/pages/attribute-dictionary.js
Related to #248
When creating data dictionary event nodes, some data was skipped if there was no
event definition for an event. This PR ensures that an event definition is
created for events listed from attributes that have no associated definition.
This PR also consolidates the JSON endpoint that lists data dictionary
definitions.
=> Handle events without event definitions

scripts/utils/constants.js, scripts/utils/migrate/docs-api.js, scripts/utils/migrate/fetch-docs.js
Partially addresses #301 and #256 
Paginates the docs results from the API so that we can pull in more than 1 page of data. Also specifies to pull in all whats new content. Note that this PR does not pull in additional content yet as that will be addressed in a separate PR.
=> Add ability to pull in paginated data

gatsby-config.js, gatsby-node.js, package.json, src/templates/whatsNew.js, yarn.lock
Partially addresses #289
Updates GraphQL queries for whats new pages to use markdown remark. Ensures images are rendered on the whats new pages. Ensures pages are created via the createPages API for each whats new page.
=> Updates due to whats new pages as regular markdown pages

gatsby-config.js
Closes #365 
Adds query to config to output whats new ids in json
Fixes query for whats new json to use allMarkdownRemark instead of allMdx﻿
=> Add endpoint for Whats New IDs

plugins/gatsby-source-nav/gatsby-node.js
Adds an overview link to the "What's new" nav so that users can navigate back to the timeline after visiting a post.
=> Add overview link to whats new nav

package.json, yarn.lock
Some of the dependencies of our dependencies had security vulnerabilities. To combat this sort of thing, yarn provides two helpful commands: `yarn audit` to see the vulnerabilities in the entire dependency tree and `resolutions` within the `package.json`. [Resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) allows us to specify which versions of dependencies we would like our repo to use (even if we're not directly using them ourselves).
`yarn audit` should return no vulnerabilities. `yarn develop` should still be working as intended.
* Relates to https://github.com/newrelic/developer-website/issues/794
If relevant, add screenshots here.
=> Fix vulnerable packages used by dependencies

gatsby-node.js
Closes #401 
Generates `fileRelativePath` from `fileAbsolutePath` in `markdownRemark` nodes and adds it to the context which is then used in the footer to populate the Edit this page link.
=> Fix edit link on What's New pages

src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-proguard-or-dexguard-android-apps.mdx
The configuration of DexGuard has change in 9.x. DexGuard 8.x is still in use so both are included.
=> chore: update DexGuard configuration for 9.x

src/components/MarkdownContainer.js, src/templates/releaseNote.js
Update the release note template to match a design similar to the whats new posts.
=> Release note template

amplify.yml
Add `public/static` and `.cache` directories to Amplify's cache on build in an attempt to speed them up.
=> cache builds to speed them up

amplify.yml
Remove code that removes `node_modules` before a build. This was put in place temporarily to fix a hyrdation issue when upgrading the version of Gatsby. We should have enough time for this to propagate everywhere, so we should be safe to remove this.
=> Remove code that removes node_modules during build

scripts/migrate.js, src/nav/accounts.yml, src/nav/agents.yml, src/nav/alerts-and-applied-intelligence.yml, src/nav/create-integrations.yml, src/nav/full-stack-observability.yml, src/nav/insights.yml, src/nav/integrations.yml, src/nav/licenses.yml, src/nav/new-relic-in-practice.yml, src/nav/new-relic-only.yml, src/nav/new-relic-partnerships.yml, src/nav/new-relic-security.yml, src/nav/new-relic-solutions.yml, src/nav/release-notes.yml, src/nav/telemetry-data-platform.yml
Partially closes #349 
This PR updates the migration script to sort Drupal nodes (authored content) by the `order` field which is read from Drupal's weight in term field. This applies to basic pages, troubleshooting, and api docs.
It also updates the migration script to update the sort of common subdirectories (get started to the top and troubleshooting to the bottom). Ordering the remaining directories is likely best handled either via instruction sets on migration OR by directly editing the nav .yml files to the proper order.
There looks to be some slight ordering issues in .mdx content links. Moving the `.sort()` for directories first fixes that, but mis-orders troubleshooting directories. ¯\_(ツ)_/¯
=> Update migration script to account for sort order

src/templates/apiIndexPage.js
Small change to sort api doc list on api index pages alphabetically by title (which for api docs is their method name) so it's easier to scan.
* #390
=> Sort api doc list alphabetically on index pages

src/components/TableOfContents.js, src/templates/basicDoc.js
Adds the right rail to pages using the `basicDoc` template. This requires adjustments to the template and our table of contents component.
* Closes #270
=> Add "Right Rail" to Mobile View

src/pages/attribute-dictionary.js
Adds the ability to deep link to specific events and individual attributes on the [attribute dictionary page](https://docs-preview.newrelic.com/attribute-dictionary/). The "link" icon (🔗 ) appears on hover [like we have for section headers](https://github.com/newrelic/docs-website/pull/464).
Most of the line changes are indentation, might want to turn off whitespace when reviewing this PR.
* Closes #343
**Event (hover)**
**Attribute (hover)**
=> Deep Link Specific Attributes and Events

src/pages/attribute-dictionary.js
closes #351 
can refresh the page with query parameters specified and the attribute dictionary will show the correct event and attribute! This bug only shows up on build so you might want to either build locally or wait til amplify builds the page.
=> Refresh attribute dictionary bug

gatsby-node.js, package.json, yarn.lock
This PR bumps the theme from [`v1.17.1` to `v1.18.1`](https://github.com/newrelic/gatsby-theme-newrelic/compare/v1.17.1...v1.18.1).
=> Update Theme Version

plugins/gatsby-remark-custom-heading-ids/index.js, plugins/gatsby-remark-custom-heading-ids/utils/heading.js, src/components/TableOfContents.js
Closes #493 
Fixes the table of contents links on pages that render a table of contents to strip the custom ID from the text and use the custom ID for linking.
**Before**
**After**
=> Fix table of contents link text/href on content pages

scripts/utils/migrate/instruction-set.js, scripts/utils/migrate/migrate-nav-structure.js, src/nav/agents.yml, src/nav/alerts-and-applied-intelligence.yml, src/nav/create-integrations.yml, src/nav/full-stack-observability.yml, src/nav/integrations.yml, src/nav/new-relic-in-practice.yml, src/nav/new-relic-only.yml, src/nav/new-relic-partnerships.yml
The agent release link was populating in the wrong place during the migration. This PR fixes this issue and ensures the links populate in the proper nav yaml file.
=> Fix nav migration

src/i18n/translations/en/translation.json, src/pages/404.js, src/pages/attribute-dictionary.js, src/pages/whats-new.js
Closes #527 
Implements `i18next` via the theme for 404, whats-new, and attribute-dictionary pages.
No Japanese translations currently exist for that content, so just English was added.
=> Add translations for 404, whats-new, attribute-dictionary

.github/workflows/validate-pr.yml
Creates a simple workflow that runs `yarn build:production` and `yarn test --passWithNoTests` whenever a PR is created into the `develop` or `main` branches. This can be used as a way to validate whether a PR is good to be merged in and will be our "source of truth" check (rather than relying on Amplify).
I'm not sure if this will get kicked off when I create this PR, but you can run this locally with the help of [act](https://github.com/nektos/act).
* Closes #518
=> PR validation workflow (gatsby build)

.github/workflows/validate-pr.yml
This is a followup to #554. Unfortunately #554 was failing Amplify builds for [some weird reason](https://github.com/newrelic/docs-website/pull/554#issuecomment-759757675). This PR adds back just the GitHub workflow caching to speed up the PR build check.
=> Cache Gatsby folders for GitHub actions

package.json, scripts/migrate.js, yarn.lock
Removes `cli-progress` module from migration. Seemed to be hanging my migration script so it wouldn't complete. Added basic logger messages in its stead.
=> Remove migration CLI progress bar

scripts/actions/__tests__/__snapshots__/serialize-mdx.test.js.snap, scripts/actions/__tests__/kitchen-sink.mdx, scripts/actions/deserialize-html.js, scripts/actions/serialize-mdx.js, scripts/actions/utils/handlers.js
Serializes code block content into an HTML attribute rather than leaving the text. This ensures that translators ignore the code in a code block as we do not want this translated.
=> Serialize code blocks without the embedded code

scripts/utils/migrate/instruction-set.js, src/nav/alerts-and-applied-intelligence.yml
Closes #584
Updates the migration instruction set to point the alerts and AI page to a real page instead of a 404 page.
=> Update Alerts and AI link to point to actual page instead of 404

.github/workflows/validate-pr.yml
Changes the cache key and combine paths based on this suggestion: https://dev.to/danielbayerlein/incremental-gatsby-builds-with-github-actions-2p7o
Also enables incremental builds in GitHub actions.
=> Try a different cache key

src/i18n/translations/en/translation.json, src/pages/index.js
The intro paragraph on the homepage didn't include a space before the "Intro to New Relic" link. This PR updates the intro paragraphs to match the latest on the current docs site.
=> Fix intro paragraph

.github/workflows/build-cache.yml
I came to the revelation that I think our cache isn't populating because we have no cache built for our develop branch. Currently, we only build and populate the cache when a PR is opened. According to [GitHub's documentation](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action) on the cache action:
> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually `main`). For example, a cache created on the default branch would be accessible from any pull request. Also, if the branch `feature-b` has the base branch `feature-a`, a workflow triggered on `feature-b` would have access to caches created in the default branch …
=> chore: add workflow to build and cache the site on pushes to develop branch

src/pages/attribute-dictionary.js
This PR adds a colon after Data Source on the attributes dictionary page.
=> chore: added Austin's colon

.github/workflows/build-cache.yml, .github/workflows/get-slugs-to-translate.yml, .github/workflows/validate-pr.yml
Rather than caching the yarn cache directory, this PR will now cache the node modules directory and only install depdencies if there is a cache miss. This should speed up the relevant GitHub actions that rely on node modules.
Here is a great article that talks about it: https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
=> Speed up installation of node modules in GH actions

src/nav/attribute-dictionary.yml
this PR attempts to fix the issue with the `https://docs-preview.newrelic.com/attribute-dictionary`  not loading when a user clicks on Attributes Dictionary from the left nav by added a trailing slash.
Also the PR attempts to add a single navigation element for Events.
Both of these things aren't working at the moment.
=> added page title and path

src/announcements/beta-banner.mdx
this PR removed the migration count from the announcement banner and also changed the end date until 3/3/21
=> chore: removed docs migration count

src/components/TableOfContents.js
Closes #443
Fixes the issue of the table of contents links not scrolling the page to the proper section until the user clicked twice.
=> Fix double click issue for table of contents in right rail

scripts/actions/add-files-to-translation-queue.js
If there is an empty file queue, the slugs would not get updated and the job would not fail. This makes sure that the job fails and it also be able to get the updated queue when there's no files in the current queue.
=> Checks for empty file queue

amplify.yml
Closes #553
Enables Gatsby incremental builds on Amplify and fixes the Gatsby cache path
=> Enable incremental builds and fix gatsby cache for build

src/templates/whatsNew.js
Closes #671
Adds the learn more and getting started links to the whats new posts.
=> Add learn more and getting started links to whats new posts

codemods/fencedCodeBlock.js, scripts/actions/serialize-mdx.js
Pulls in the logic from the gatsby-plugin jerel created in this PR: https://github.com/newrelic/docs-website/pull/686/files to correctly parse fenced code blocks
=> Serializes fenced codeblocks correctly

plugins/gatsby-plugin-auto-index-pages/gatsby-node.js, scripts/migrate.js, scripts/utils/migrate/taxonomy-redirects.js, src/data/taxonomy-redirects.json
Sets up redirects for _Taxonomy_ (index pages in Gatsby).
* Closes #364
=> Taxonomy Redirects

.github/stale.yml
This PR updates stalebot to exclude the label roadmap from stalebot's relentless pursuit.
=> chore: update to stale bot config

scripts/actions/remove-completed-batch.js
When a translation job is complete, we remove the "context" files from our translation vendor's platform. However, when we upload files, the vendor will make a _second_ "context" from the uploaded file. This PR ensures that we're removing _all_ context associated with a particular page.
* Closes #796
=> Remove all translation context when job is complete

src/content/docs/agents/net-agent/installation/introduction-net-agent-install.mdx
Closes #803 
This removes the redirect in the frontmatter for the .NET intro install doc that prevented accessing the page for the .NET install for Windows  link. The redirect was disabled in Drupal, but our migration doesn't check for that (super rare for redirects to be disabled). 
This was removed from prod/dev Drupal and migration was re-run to ensure it was removed.
=> Fix erroneous redirect on .NET install doc

COMPONENT_GUIDE.md
This PR clarifies that the docs site only use global components.
=> chore: updated component guide

plugins/gatsby-plugin-generate-doc-json/utils/handlers.js
Remove paragraphs from table pieces, `html-react-parser` on the nr1-help-xp side is having trouble parsing the table with the `<p>` tags in between
=> Remove paragraphs from table components

plugins/gatsby-plugin-generate-doc-json/gatsby-node.js
Currently PR builds emit a bunch of warnings related to querying `childImageSharp` on files that will return null. This PR attempts to silence those warnings by querying for image through allImageSharp.
=> Switch query to prevent sharp warnings on build

src/pages/index.js
Closes #846
Updates the sign up tile style on the home page to make it pop a bit more.
=> Update sign up tile style

src/components/SEO.js, src/layouts/MainLayout.js, src/pages/attribute-dictionary.js, src/pages/whats-new.js, src/templates/apiLandingPage.js, src/templates/docPage.js, src/templates/indexPage.js, src/templates/landingPage.js, src/templates/releaseNote.js, src/templates/releaseNoteLandingPage.js, src/templates/tableOfContents.js, src/templates/whatsNew.js
Creates a `SEO` component that extends the theme with docs-site-specific meta content (so that we don't need to constantly update a ton of files).
Also adds the site verification code for docs.newrelic.com.
* Closes #791
=> Add Google Search Console verification

scripts/utils/migrate/taxonomy-redirects.js, src/data/taxonomy-redirects.json
Closes #758, closes #804
This supports redirecting dummy docs (like those in agent docs that link to that agent's release note index page AND view all agent API methods links) that link to an index page.
Uses a new migration API resource to get a Drupal node's URL alias given the node URI in the redirect data.
=> Create redirects for more dummy docs to tax term / index paths

src/content/docs/new-relic-only/drupal-configuration/page-components/manage-content-footers.mdx, src/content/docs/new-relic-only/tech-writer-style-guide/processes-procedures/edit-images.mdx, src/content/docs/new-relic-only/tech-writer-style-guide/processes-procedures/embed-images.mdx, src/manual-edits/content/docs/new-relic-only/tech-writer-style-guide/processes-procedures/edit-images.mdx, src/manual-edits/content/docs/new-relic-only/tech-writer-style-guide/processes-procedures/embed-images.mdx
We don't want to get a ton of emails from people. We prefer people create GitHub issues.
Because the style guide docs will be public, we don't want people emailing our Docs email address. This is a minor update.
=> Removed the docs@newrelic.com email address

plugins/gatsby-plugin-auto-index-pages/gatsby-node.js
Closes #565
Adds necessary graphql query and swaps out a title of a page if a translated version exists for each locale when creating auto index pages via `gatsby-plugin-auto-index-pages`. It also adds the locale slug for each link.
=> Use translated titles on locale auto index pages

.github/workflows/release.yml
Adds [`newrelic/deployment-marker-action@v1`](https://github.com/newrelic/deployment-marker-action) to a new workflow that is triggered whenever a PR into main is merged (or a release is published). This relies on credentials which are already added to the repository secrets.
The `applicationId` is for our [browser application](https://staging.one.nr/0LkjnevlRo1).
We may want to consider adding a slack message that gets triggered on release as well, but it's outside the scope of this PR.
* Closes #644
=> Add New Relic deployment marker action

gatsby-node.js, plugins/gatsby-source-nav/gatsby-node.js, src/components/SubNavigation.js, src/layouts/MainLayout.js, src/manual-edits/nav/attribute-dictionary.yml, src/nav/attribute-dictionary.yml
Closes #908
The attribute dictionary page only has a single link and does not need the filter input. This PR adds the ability to disable the filter input for a nav by adding a `filterable: false` property to the nav
=> Remove nav filter from attribute dictionary page

gatsby-browser.js, gatsby/on-route-update.js
Closes #788
Instrument requests that contain a hash in the URL. Will only instrument hash
requests when the page first loads, or navigating to a different page with a
hash.
=> Instrument hash requests

src/pages/attribute-dictionary.js
Closes #882
The feedback widget was missing on the right rail for the attribute dictionary
page. This adds it back.
=> Add feedback to right rail on attribute dictionary page

scripts/utils/migrate/instruction-set.js, src/manual-edits/content/docs/agents/net-agent/net-agent-api/index.mdx, src/manual-edits/content/docs/release-notes/agent-release-notes/net-release-notes/index.mdx, src/nav/full-stack-observability.yml, src/nav/new-relic-in-practice.yml
Closes #940
Update nav migration instructions to set NR in Practice to link to https://docs-preview.newrelic.com/docs/using-new-relic . The previous path led to a 404 page. 
Also included are redirects to existing index pages in `manual-edits` that I must've missed. And on migration a single quote came through un-encoded which looked legit to me so committed it.
=> Update NR in Practice nav path

plugins/gatsby-source-nav/gatsby-node.js, src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/index.mdx, src/content/docs/release-notes/index.mdx, src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/index.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/index.mdx, src/manual-edits/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/index.mdx, src/manual-edits/content/docs/release-notes/index.mdx, src/manual-edits/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/index.mdx, src/manual-edits/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/index.mdx, src/templates/releaseNote.js
Sets up support for #892. Updates nav and `releaseNote.js` template so `version` isn't required for a release note (cloud integrations do not have a version number).
Adds dummy doc and original platform release note index link to redirects in the index.mdx files for each directory. Adds those index.mdx files on migration via `manual-edits`.
Example of a cloud integration release note will look like (the subject / name will actually be `New Relic infrastructure cloud integration`)
=> Account for new release notes, optional version number

plugins/gatsby-plugin-generate-doc-json/gatsby-node.js, plugins/gatsby-plugin-generate-doc-json/utils/handlers.js
the docs json was not building because of not checking the node.parent existance when checking for whether the element is a block element. This PR now checks for that, as well as errors when the generate-doc-json fails to build
=> generate-docs-json checks for node parent 

src/components/Select.js
Fixes the text color for the `<option>` elements on the data dictionary (when in dark mode). See screenshots.
* Closes #907
**Before**
**After**
=> Update Data Dictionary dropdown color in Firefox

src/content/docs/alerts-applied-intelligence/index.mdx
We found this incorrect link during the Docs team test.
=> Updated the Learn about AI tile to point to a better place

plugins/gatsby-source-nav/gatsby-node.js, src/layouts/MainLayout.js
Closes #877
Ensures table of contents pages created from root nav links generate the content for the page. Currently these are blank for TDP, AI, and FSO table of contents pages.
=> Fix empty root table of contents pages

plugins/gatsby-source-nav/gatsby-node.js
Closes #974
This PR updates the sorting of the release notes nav by case insensitive alpha. Also compares against word-only characters to ensure release notes such as `.NET` show up with the `n`s.
=> Sort release notes nav as case insensitive

plugins/gatsby-plugin-generate-doc-json/utils/handlers.js
removes leading slash from `srcUrl` so that the hashmap works :)
=> Remove leading slash

gatsby-config.js, gatsby-node.js
Closes #963
Japanese redirects are currently not working, and result in a 404. This PR ensures that redirects are created for localized pages by using the redirects frontmatter in the English doc to create a redirect for its associated locale page.
=> Ensure redirects are created for each locale

amplify.yml
Builds in Amplify are still taking a while, even for small edits. This tries another attempt at moving the env variable inline with the build command.
=> Try moving incremental build variable inline with build command

src/content/docs/agents/net-agent/index.mdx, src/content/docs/serverless-function-monitoring/index.mdx
Currently the homepage tile for serverless goes to a giant index page. This PR creates a micro-landing-page for serverless.
@rhetoric101 rocks. Thanks for helping me crank this thing out!
=> Create serverless landing page

gatsby-config.js, package.json, yarn.lock
Updates the logic that determines which docs to fetch related resources for to include all basic doc pages, troubleshooting, and api doc pages.
=> Add actual logic for fetching related content

gatsby-config.js
Closes #962
Now that we are going live, we need to make sure the site is crawlable. Use the default options from the theme.
=> Use default robots config

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Correct a typo in the browser endpoint section.
=> Correct typo in fedramp-compliant-endpoints.mdx

README.md
The "Contributors guide" link in the README referred to `https://github.com/newrelic/docs-website/blob/readme-update/CONTRIBUTING.md`, which returns a 404.  This PR removes the reference to the (no longer extant?) `readme-update` branch.  It also uses one consist reference to CONTRIBUTING.md; there are currently (3) different references in the page.
=> fix broken link for "Contributors guide"

src/pages/index.js
Closes #1013
Adds links to the section titles on the home page to make it easier to navigate to the landing page.
=> Link the TDP, FSO, AI headings to their respective landing pages

plugins/gatsby-plugin-generate-doc-json/gatsby-node.js, plugins/gatsby-plugin-generate-doc-json/utils/handlers.js, src/content/docs/release-notes/mobile-release-notes/android-release-notes/index.mdx, src/content/docs/release-notes/mobile-release-notes/ios-release-notes/index.mdx
This is just a temporary fix to avoid `Object` being rendered as the title :) 
We also will need to eventually handle TechTiles. I will add this all in an issue to follow up. 
Avoids this problem ^^
=> Nr1 help fixes - turn jsx titles to text and add two redirects

src/nav/agents.yml
Our Infrastructure Agent was missing from the Agents list :( so I added it :)
The Infrastructure Agent docs were missing from the Agents list
N/A
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
=> Added Infrastructure Agent to the Agents list

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-2-0-0.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-2-0-1.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-2-1-0.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-2-2-0.mdx, src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-2-3-0.mdx
This PR ports release notes for nri-kubernetes from the [release notes page](https://github.com/newrelic/nri-kubernetes/releases).
Some other release notes pages had a `redirects` attribute in the front matter, but I do not know what this is used for. Please tell me if you want me to add this back.
=> release notes: add missing release notes for k8s

gatsby-config.js, plugins/gatsby-plugin-generate-json/gatsby-node.js
Wasn't building because html was being used instead of htmlAST. This also now causes the build to fail if the json isn't generated, which is important because we would like to know when our json isn't being served (as some services rely on it).
=> Use htmlAST instead of html in whats-new json

CONTRIBUTING.md
Previously, I had removed the "What's new?" section out of Contributing.md and into the style guide. Alas, I forgot to remove the manual table of contents entries. So, I just removed the following TOC entries:
- [Adding a what's new post](#adding-a-whats-new-post)
- [What's new post frontmatter example](#whats-new-post-frontmatter-example)
=> PR for any tech writers: Updated TOC in CONTRIBUTING.md

src/content/docs/release-notes/agent-release-notes/ruby-release-notes/index.mdx
The ruby release notes page was missing a redirect. This issue was posted in the #documentation channel
=> Add missing ruby release notes redirect 

src/content/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api.mdx, src/data/whats-new-ids.json
Two links in this doc had problems: they were pointing to the same doc. I confirmed with Brian Peck that these two links should point to a lower section in the same doc called “Script API for scripted browser and API test monitors.”
Also, this commit included a bonus change that I didn't create for `src > data > whats-new-ids.json`.   @jerelmiller said I should commit this.
=> Hero edit: Corrected two links in "Manage synthetic monitors via REST API"

rehype-plugins/utils/addAbsoluteImagePath.js
Sets the image `.properties` rather than setting the `.src` directly (which has no effect).
=> Update image src properties

src/content/docs/insights/event-data-sources/insights-api/insights-dashboard-api.mdx
Per [this thread](https://discuss.newrelic.com/t/100354) on the Explorers Hub community forum, a new field—`grid_column_count`—was added to the dashboard's data definition schema. For ease of consistent reference, this implementation should be reflected in the official documentation as well.
In the following places:
* In the "Example dashboard schema" code snippet, added `"grid_column_count": 3|12`.
* In the "Dashboard data definitions" table, added data element entry for `grid_column_count`.
Follow-up checks for the reviewer:
* Confirm whether type is actually `Integer` or some other numeric type like `Long`.
* Confirm whether values other than 3 and 12 are supported in any capacity.
* Amend the "Important" and "Caution" call-outs regarding dashboard's widget size limits and column …
=> Added schema definition for `grid_column_count`

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action.mdx, src/content/docs/browser/new-relic-browser/browser-agent-spa-api/index.mdx
When Googling "New Relic Browser API" and clicking on the first result, I'm taken to a page at https://docs.newrelic.com/docs/browser/browser-monitoring/browser-agent-spa-api, which results in a 404. This page lives at https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api. This PR adds the necessary redirect to ensure the page does not 404.
=> Add redirect to browser API page

rehype-plugins/utils/addAbsoluteImagePath.js
Closes #1125 
The `src` attribute on images has been fixed on What's new posts, but the `srcset` property is still using relative paths. Browsers that support this property are still showing a broken images. This PR ensures the `srcset` is updated to use the absolute images URLs.
=> Ensure srcset property uses absolute image path

plugins/gatsby-source-data-dictionary/gatsby-node.js
Closes #1087
Search results still yield links to individual data dictionary event pages. This PR adds redirects for `/attribute-dictionary/<event-name>` URLs to the new attribute dictionary page. We currently have them in place for attributes but forgot to add them for events themselves.
=> Create redirects for data dictionary event pages

.github/workflows/issue-pr-triage.yml
This PR is to add a github action to route issues and prs with labels of `content` or `localization` to the correct boards. 
I tested using [act](https://github.com/nektos/act) and when running 
act  issues and act pull_request  the action ran ok, but threw this error, which I thought was related to the fact no label was passed in my test, if there are better ways to test this just let me know.
[Auto-triage to project boards/Triage to Content Project      ]   ❌  Error in if: expression - Triages NEW issues and NEW pull requests to the Content Project
Error: TypeError: Cannot access member 'labels' of undefined
=> chore: added gitub action for issue routing

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-billing-monitoring-integration.mdx
Added verbiage for the billing alerts permission. A customer had a question about why we need that permission and we don't tell them in the docs. This should help bring clarity to that issue.
Explain why you're proposing this change. If there's an existing GitHub issue 
related to your change, please link to it.
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
=> Billing Alerts Update

src/nav/attribute-dictionary.yml
Please test this locally! I tested locally but it's a big enough change I think a second set of eyes would be goodl.
Taxonomy names should be lower case.
=> Sentence case attribute dictionary

.github/workflows/issue-pr-triage.yml
This PR adds the github opensource_bot_token to the github action in order for the action to work correctly.
=> chore: added Gh token to action

src/content/docs/release-notes/agent-release-notes/c-sdk-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/index.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/index.mdx, src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/index.mdx
Someone reported in #documentation that the old root/index pages for agent release notes are missing redirects. 
I found the new URLs by playing around in the old Drupal-based docs-dev site.
Opening as draft because I still need to test the redirects locally.
=> Adding missing agent RN redirects

src/pages/whats-new.js, src/templates/releaseNoteLandingPage.js
Reduces the space between timeline events for whatsnew and releasenotes 
closes #911
=> Reduces the space between timeline events

src/components/MDXButton.js, src/components/MDXButtonGroup.js, src/components/MDXContainer.js, src/content/docs/agents/c-sdk/get-started/introduction-c-sdk.mdx, src/content/docs/agents/go-agent/get-started/introduction-new-relic-go.mdx, src/content/docs/agents/java-agent/getting-started/introduction-new-relic-java.mdx, src/content/docs/agents/python-agent/getting-started/introduction-new-relic-python.mdx, src/content/docs/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx, src/content/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration.mdx, src/content/docs/integrations/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx
We want to make all buttons center on the docs site! If there's more than one button, we will want to have them both centered in a row. This PR creates two components: `MDXButton` which is a wrapper around the `Button` component and `MDXButtonGroup` which creates a `ButtonGroup` component to be used to wrap two buttons. This PR also changes all the buttons to match this pattern! The details of this was specified by austin in [this slack thread](https://newrelic.slack.com/archives/C017ZNASGUX/p1614889222478200) to handle these two cases.
=> Provides wrapper around buttons in mdx docs

gatsby-node.js, src/components/SEO.js, src/templates/apiLandingPage.js, src/templates/docPage.js, src/templates/indexPage.js, src/templates/landingPage.js, src/templates/releaseNote.js, src/templates/releaseNoteLandingPage.js, src/templates/tableOfContents.js, src/templates/whatsNew.js
closes #1191  after it is deployed and we trigger a recrawl. 
Disables swiftype robots by a meta-tag when the page generated automatically rather than from a localized mdx page. According to the [documentation](https://swiftype.com/documentation/site-search/crawler-configuration/meta-tags#swiftbot) when added to the page this will override all other swiftype meta tags on the page (which is what we want, so it doesn't really matter that if in the SEO component there's any ones being added or elsewhere). This will make sure that when a user is searching in Japanese they will get a page that has actual japanese content on it.
=> Add meta tag to disable swiftype robots on auto-generated localized pages

src/components/SEO.js
The template used to generate the title of a page (that swiftype then indexes and NR1 Help XP then uses as its title when rendering content) is: `Title of page | New Relic Documentation`. This may make for weird matching when querying against the `title` field or displaying those titles in NR1 Help XP. In other contexts, we may want to keep the site name at the end (ex, a Slack link preview).
This updates the `<SEO>` component to explicitly set the swiftype `title` field.
=> Explicilty set page title for swiftype

src/content/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing.mdx
The [original product based pricing doc](https://docs.newrelic.com/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing/) was redirecting to itself. This PR removes that redirect.
Closes #1227.
=> Removed redirect pointing to same doc

src/components/SEO.js
Looks like swiftype may not have liked the data type. I _think_ it should be a string instead of text
=> fix: change data type for swiftype title

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
"The following link won't work and it doesn't seem to be possible to view the old documentation 
https://docs.newrelic.com/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing/"
This seems to be another redirect issue on the pricing pages. The link should take you to the original product based pricing page, but it instead redirects you to the NR1 pricing page.  I scanned through them and this should be the last of the fixes.
=> Removed redirect from original pricing plan to new pricing plan

.github/workflows/issue-pr-triage.yml
This PR changes the logic to move ALL issues and PRS to the content project board per @austin-schaefer request.
=> chore: changes triage logic

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-713.mdx
Adding release notes for v7.1.3 we just shipped.
=> chore: adds release notes for node agent v7.1.3

src/content/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
There was a minor, incorrect formatting issue on a link on the K8S installation page in the update section.  It entailed reversing the order of parens and square brackets in the markdown for the link text and in-page link.
This fix was tested in my local environment.  Please see the below screen captures of rendered HTML before the fix in this PR and after.
No, this is a simple content change
=> K8s link fix

.github/workflows/issue-pr-triage.yml
Turns out `github.event` is a reference to an object, so the workflow was not run correctly for new issues/PRs. Since we only want to run the action on NEW PRs and issues, this simplifies the condition to only run on the `opened` action regardless of whether it is an issue or PR. This should fix the issue triage.
=> Fix issue/PR triage when they are open

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
As I was looking at [this NRQL doc](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/), I noticed some of the collapsers included a `\` before the optional arguments where `[` was used. I believe this was due to our migration process and something that we forgot to remove when moving it to the `title` attribute. This PR removes those stray `\` characters to provide better clarity so someone doesn't assume this is part of the NRQL itself.
=> Remove unneeded escape characters from NRQL function doc collapsers

codemods/utils/mdxast.js, plugins/gatsby-plugin-generate-doc-json/gatsby-node.js, plugins/gatsby-plugin-generate-doc-json/utils/handlers.js, plugins/gatsby-plugin-generate-doc-json/utils/jsxImagesToChildren.js
This allows for titles for Collapsers and icons Tech Tiles to be rendered in the in-product help xp. Before this gets merged in, there will need to be some work on the side of the in-help-xp to handle the collapser titles as children and support for tech tiles in general. 
In the future (when react 17 is up and running in the product) we should move away from this and try to serve the mdx and use mdx in the product to render the components! but that's a thing for the future :)
=> Renders inline jsx as children of component for collapsers and tech tiles

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
The `getField` section on the [NRQL functions doc](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-get-field) contained examples that are not captured inside of the collapser (see screenshot). This PR moves the examples into the collapser after the table.
=> chore: Move getField examples into the collapser

src/content/docs/agents/java-agent/configuration/configuring-your-ssl-certificates.mdx
previous link was not navigating to the `SSL Certificate` term in the glossary
Explain why you're proposing this change. If there's an existing GitHub issue 
related to your change, please link to it.
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
=> fixes link to certificate glossary term

src/content/docs/integrations/host-integrations/host-integrations-list/snmp-monitoring-integration.mdx
We support Windows again.
Closes #1215 
We released SNMP integration 1.3.0 which adds support for Windows (.msi package released).
=> Adding back the Windows installation instructions

.github/workflows/validate-pr.yml
Currently we run a build on PRs merging into develop and again when releasing develop to main. The build from develop -> main is unnecessary and adds a lot of time to releases. This PR adjusts the action so the build job is only run on PRs to develop
Closes #1209
=> Only run build in PR validation for merges to develop, not main

src/content/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration.mdx
Defaults for user and pass for nri-jmx were rolled back to `""` in this PR [#57](https://github.com/newrelic/nri-jmx/pull/57)
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/) 
=> fix: set nri-jmx defaults for user and pass to empty string

src/nav/full-stack-observability.yml
Closes #1276 . This PR changes the links under Types of Integrations to point towards the relevant lists.
=> Links now point to lists

package.json, src/components/SEO.js, yarn.lock
Bumps theme version to use updated `<SEO>` theme component that sets swiftype meta tag based on `siteMetadata.siteUrl`. Supports setting separate `type` value for localized pages.
- https://github.com/newrelic/docs-website/issues/1204
=> Set swiftype type via theme's updated SEO component

.github/pull_request_template.md
This PR adds a message in Japanese as a markdown comment explaining we don't accept PRs for Japanese content at this time.
=> chore: japanese message on PR template

src/content/docs/security/security-privacy/information-security/security-bulletins.mdx
Just a very small edit to remove a bullet linking to RSS feed, which is not currently supported. No peer or tech review needed.
=> Removed broken RSS feed link

src/pages/whats-new.js, src/utils/constants.js
Adds a swiftype meta tag for `document_type` set to `views_page_content` (same as attribute dictionary) so we can apply some filtering for searches. Any page with dynamic content used this value in Drupal, so we want to match that for now. 
These kinds of pages tend to add noise to search results since they're dynamic and essentially list content. And the jp namespaced pages contain a lot of English content, so if users' searches match this page, they will see duplicate records (unless we update search UI to be a fully localized experience)
https://github.com/newrelic/docs-website/issues/1191
=> Add swiftype document_type to whats new page

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
When the ability to create a NRQL alert directly from a chart is released, some elements of NRQL that worked in the charting context won't be appropriate for creating an alert condition. This PR adds a section that covers the most common disallowed elements and how to achieve the same effect in an alerting context.
We're planning to link to this from the error message in the Alerts Condition Builder UI when SINCE, UNTIL, etc are entered into the query field. SEE NR Jira AINTER-7731 for details.
No, just text
=> add section to create-nrql-alert-conditions.mdx

src/content/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
Add "Infinite Tracing on Alpine Linux" to the list of unsupported features.
See this issue in the .NET Agent repo: https://github.com/newrelic/newrelic-dotnet-agent/issues/289
A community contributor suggested that we update this docs page with this issue.
=> Update unavailable features

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/scripted-browser-examples.mdx
The Community Forum link in the Tip callout is no longer valid. Recommend linking to Quickstart Synthetics library and Level Up Relic Solutions.
Explain why you're proposing this change. If there's an existing GitHub issue
related to your change, please link to it.
=> Fix broken link in Tip callout

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83901.mdx
Adding release notes for .NET Agent version 8.39.1.
=> Add release notes for .NET Agent 8.39.1

src/content/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-distributed-trace-data-tutorial.mdx, src/content/docs/understand-dependencies/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api.mdx, src/data-dictionary/events/SyntheticCheck/timestamp.md, src/data-dictionary/events/TransactionError/timestamp.md
[Unix time](https://en.wikipedia.org/wiki/Unix_time) is the most common usage.
=> Change obscure "epoch milliseconds" to "unix time"

src/content/docs/understand-dependencies/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing.mdx
Indentation was wrong for the `infinite_tracing` config yaml example which made it look like it was supposed to be nested under the `distributed_tracing` config stanza.
=> Fix indentation for Java yaml infinite_tracing config

src/content/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
The Drupal to Gatsby migration left out the preparation section of the Kafka integration, which I just restored.
This PR is related to GitHub issue https://github.com/newrelic/docs-website/issues/1123.
The review just needs to compare the content in this PR with the content here:
https://docs-dev.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration#prepare-for-install
=> Restored lost preparation section that was dropped in the Gatsby migration

src/content/docs/agents/java-agent/heroku/java-agent-heroku.mdx, src/content/docs/agents/java-agent/heroku/java-agent-scala-heroku.mdx, src/content/docs/agents/nodejs-agent/hosting-services/nodejs-agent-heroku.mdx, src/content/docs/agents/php-agent/advanced-installation/php-agent-heroku.mdx, src/content/docs/agents/python-agent/hosting-services/python-agent-heroku.mdx, src/content/docs/agents/ruby-agent/installation/ruby-agent-heroku.mdx
Added correct [`https://elements.heroku.com/addons/newrelic`](https://elements.heroku.com/addons/newrelic) or [`https://elements.heroku.com/addons/newrelic#planselector`](https://elements.heroku.com/addons/newrelic#planselector) link in place of truncated `//addons.heroku.com/newrelic#plan_selector` in response to [https://github.com/newrelic/docs-website/issues/1441](https://github.com/newrelic/docs-website/issues/1441). 
n/a
no
=> Fixed mangled link that was 404ing

src/content/docs/style-guide/article-templates/create-release-notes.mdx
Quick addition stating that release note PRs might take a few hours to render on the docs site. Added since release notes are blockers for some teams.
=> Added line explaining buffer period between release notes PR and public build

src/content/docs/agents/ruby-agent/getting-started/migration-7x-guide.mdx, src/nav/agents.yml
Added a new page 'Ruby Agent 6.x to 7.x Migration Guide' to help customer upgrade to version 7x.
This guide covers the major changes between 6.x and 7.x series of the Ruby Agent, issues that may be encountered in upgrading and how to migrate successfully to 7.x.
=> Added Ruby Agent 7.0 Migration Guide

src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-600.mdx
The formatting of the release notes for the v6.0.0 Android agent is incorrect w/ respect to the code block for demonstrating the new build variant exclusion feature. It looks fine on the New Relic site, but the links do not work for the headers. 
No
No
=> Fix Android Agent v6.0.0 Release Notes Formatting

src/content/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration.mdx
This PR fixes a typo in one postgresql argument name, as per the code:
https://github.com/newrelic/nri-postgresql/blob/23cb38f05efdec3dd39b4804ded1ef6a7f70f5c5/src/args/argument_list.go#L21
=> integrations/postgresql: fix typo in parameter name

src/content/docs/integrations/amazon-integrations/get-started/integrations-managed-policies.mdx
Users of Cloud integrations have to add the permission `emr:ListInstanceFleets` to work as expected.
=> chore: add missing permission in EMR

.github/workflows/check-translations-and-deserialize.yml, .github/workflows/send-content-to-translate.yml
This PR enabled the translation workflows to run at regular intervals:
* Send content to be translated _every Thrusday at 1am_
* Check the status of translation queues _every day at 12pm_
The translation vendor user, project, and secret have already been upated in the "secrets" section of the repository.
I left the `workflow_dispatch` event so that we could manually trigger each action (just in case we want to manually send content sooner than Thursday).
=> Enable automatic translation workflow

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-7-2-0.mdx
Added release note for Node agent v7.2.0 we just shipped.
**Please Note: this is testing out the naming strategy discussed in another GitHub issue to verify there are no issues and use going forward if works. as expected**
Please see discussion here: https://github.com/newrelic/docs-website/issues/1255
I don't have yard installed or I would have attempted to run locally.
=> chore: adds release notes for Node agent v7.2.0.

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1160.mdx
We are planing to release a new version of newrelic infrastructure agent [1.16.0](https://github.com/newrelic/infrastructure-agent/releases/tag/1.16.0)
=> docs: add infrastructure agent release notes for version 1.16.0

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
As mentioned in #documentation, https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer/ is not working and needs to be replaced by https://layers.newrelic-external.com/.
Tested locally.
=> Fixed layer link

plugins/gatsby-plugin-auto-index-pages/gatsby-node.js, plugins/gatsby-source-nav/gatsby-node.js, src/components/SEO.js, src/data/taxonomy-redirects.json, src/templates/indexPage.js
Originally it seemed like redirects were not working via `gatsby-plugin-auto-index-pages`, but the issue was a gotcha in the way we attach nav menus (loaded into gatsby via `nav/*.yml` files). This updates the logic when resolving which nav to add to a given page at a slug to not add one if the page is a programmatically generated page (not authored .mdx driving it)
Every page has a `nav` object in its data via `MainLayout` query, which passes it a slug and either gets back a nav menu object based on one of the nav .yml files OR null. That's set via `gatsby-source-nav` via a resolver that looks for the slug in all the `NavYaml` data in graphql (which is loaded via nav .yml files). We do that to know what left nav menu to show so a user stays in context when clicking on links in a …
=> Fix taxonomy redirects

src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api.mdx, src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partnership-accounts-users-subscriptions.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partner-api-reference.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-account-object.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-keys.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-sub-account-object.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-subscription-object.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-user-object.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-billing-integration-api.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/product-buckets.mdx, src/content/docs/new-relic-partnerships/partnerships/partner-api/typical-integration-example.mdx, src/nav/new-relic-partnerships.yml
For release March 24 afternoon. 
This is regarding changes for the Partnership API that pertain to restrictions for customer partnerships on the New Relic One pricing plan or the New Relic One user model (so four total audiences of all combinations of those). It doesn't apply to true partners (aka resellers, managed service providers) just customer partnerships. Main scope of work: 
Edits in the 'Intro to Partnership API' doc: adding more info about requirements and restrictions. 
For every doc in this category: putting in prominent notes about reading requirements before use. 
Edits in the `account object` doc: putting in various callouts regarding the attributes that are restricted dependent on pricing plan or account/user model. The other two objects (users object and subscription …
=> DOC-6579 Partnership API changes 

src/content/docs/agents/java-agent/attributes/java-agent-attributes.mdx, src/content/docs/agents/net-agent/net-agent-api/addcustomparameter-net-agent-api.mdx, src/content/docs/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/content/docs/agents/php-agent/php-agent-api/newrelic_add_custom_parameter.mdx, src/content/docs/agents/php-agent/php-agent-api/newrelicaddcustomspanparameter-php-agent-api.mdx, src/content/docs/agents/python-agent/attributes/python-agent-attributes.mdx, src/content/docs/agents/python-agent/python-agent-api/addcustomparameter-python-agent-api.mdx, src/content/docs/agents/python-agent/python-agent-api/addcustomparameters-python-agent-api.mdx, src/content/docs/agents/python-agent/python-agent-api/addcustomspanattribute-python-agent-api.mdx, src/content/docs/agents/python-agent/python-agent-api/recordcustomevent-python-agent-api.mdx, src/content/docs/agents/ruby-agent/attributes/ruby-agent-attributes.mdx, src/content/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action.mdx, src/content/docs/insights/event-data-sources/custom-events/apm-report-custom-events-attributes.mdx
As mentioned in #documentation, the link https://docs.newrelic.com/docs/insights/nrql-new-relic-query-language/nrql-resources/nrql-reserved-words/ no longer works.
I've started a sweep to replace it for https://docs.newrelic.com/docs/insights/event-data-sources/custom-events/data-requirements-limits-custom-event-data/#reserved-words. I want to double check with @barbnewrelic this is the right doc before I finish the sweep, I've changed 3 instances so far.
=> Replaced link for reserved words

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
The section incorrectly specified that comparing data starting 3pm with 'four hours ago' would compare against 1pm data. The timing is actually relative to the SINCE clause, so the data being compared would be from four hours before 3pm (i.e. 11am).
Explain why you're proposing this change. If there's an existing GitHub issue
related to your change, please link to it.
=> Fixed COMPARE WITH description

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Highlighting that enable_process_metrics is now enabled by default when using the Guided Install
The new Guided Install flow is setting enable_process_metric enabled by default. This helps new New Relic customers experience all NR1 features around process monitoring.
Some customers asked if Guided Install is enabling process monitoring by default in the infrastructure agent. 
=> Guided Install now enabled process monitoring

src/utils/getAgentName.js
Currently https://docs.newrelic.com/api/agent-release-notes.json outputs entries for both `nodejs` and `node` as well as `.net` and `dotnet`. This PR simplifies these entries and renames `.net` and `node` to `dotnet` and `nodejs`. This is in line with the naming used in a previous service
=> Add rename logic to getAgentName

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-users/usage-queries-alerts.mdx
This PR updates the language of the usage alerting page:
* Removes invalid `SINCE` clause from NRQL example
* Clarifies time window language to outline relationship to hourly usage/consumption events
=> fix: Corrects NRQL query and adds evaulation clarification

src/content/docs/style-guide/processes-procedures/update-left-navigation-pane.mdx
The directory is technically a local thing, the URL is just a convenience so people can find it on the web.
=> More accurate directory name

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
Adds ssl-checker to list of supported 3rd party modules for latest Synthetic Monitor Version
The Synthetics Runtime will be adding support for a new 3rd party module for the latest runtime, so we'd like to disclose that package in our documentation
N/A
=> Add ssl-checker to supported 3rd party modules

src/components/Watermark.js
This is a quick-fix for #1599. This does not close it as we should also look into changing the colors/contrast, but it works as a stop-gap. 
This simply increases the size of the watermark font from `8rem` to `18rem`
=> fix: Increase watermark size

src/content/docs/style-guide/article-templates/create-release-notes.mdx
Fixes the broken "What's new style guidelines" link at the top of the 'create-relase-notes' page.
Current link 404s.
=> Fixes 'whats new' link on release note template page.

src/content/docs/style-guide/article-templates/create-release-notes.mdx
Adding  a note per internal conversation [here](https://newrelic.slack.com/archives/C119L74HL/p1616620102034800?thread_ts=1616615375.033200&cid=C119L74HL) and external conversation here: https://github.com/newrelic/docs-website/issues/1255.
The note didn't really seem like it should be a super special callout like tips/warnings/etc. so I just used a quote formatting but y'all may decide you want styled different or not at all. Also, open to language or general changes too if you'd like approached a different way.
=> Adds release note naming convention note.

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1161.mdx
* `newrelic-fluent-bit-output` included in the last released agent was with wrong version.
=> fix: newrelic-fluent-bit-output released version

src/content/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
The migration from Drupal had dropped several changes in the Kafka doc. In a previous [PR] (https://github.com/newrelic/docs-website/pull/1388), I had restored the missing "preparation" section that was missing, but I overlooked two troubleshooting sections further down in the document. 
This PR is to restore those two troubleshooting sections:
* JMX connection errors
* Kerberos authentication failing
Closes #1123
=> Second kafka pr for issue 1123

src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx
The `completeTransactionsOnThread` service config section could not be linked to because the collapser ID was incorrect.
=> Fix issue with collapser ID

src/content/docs/new-relic-one/use-new-relic-one/get-started/introduction-new-relic-one.mdx
Mark is meant for code https://docs.newrelic.com/docs/style-guide/writing-guidelines/code-formatting-guidelines-var-mark/
=> Remove unorthodox use of <mark> in inline text

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx
Link https://discuss.newrelic.com/tags/c/support-products-agents/synthetics/synthetics-script is leading to a 404 not found page right now.
Replaced it with what seems like the equivalent.
N/A
N/A
=> Updated "Script repository" link because it 404s

src/content/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview.mdx, src/content/whats-new/2021/03/guided-java-net.md
This March 31 what's new post had an invalid URL. I added a redirect for it.
=> Added a redirect to a broken what's new link

scripts/actions/utils/handlers.js, scripts/utils/migrate/get-serialized-i18n-content.js
This PR adds a script that can be run to grab the serialized HTML version of all the MDX files that are being translated. Our translation vendor needed _all_ the files (EN and JP) to build up their database.
The serialization logic was already in place (it's how we send them content via GH Actions). While working on this, I found a few different components that didn't have methods for serializing / deserializing. I've added those as part of this PR, since they're needed for the script to run successfully.
* Relates to #995
=> Script for fetching all translated content (serialized)

src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts.mdx
Removing links value from JSON example. This is no longer supported
The links URL is no longer returned by the Infra Alert API
=> chore: Update rest-api-calls-new-relic-infrastructure-alerts.mdx

src/content/docs/browser/index.mdx, src/nav/full-stack-observability.yml
In the migration from Drupal to Gatsby, the docs related to single-page apps were not included in the left navigation. Evidently, the migration just moved navigation sub-category item " Browser monitoring." 
To fix this, I moved the navigation category "Browser monitoring" down one level and created a sibling category of "Single page app monitoring." I then created the main navigation node for these related topics as "Browser" and is a sibling to other main topics, such as APM and Logs.
The one thing that doesn't quite match Drupal is that when you go to "View all Browser docs," you'll see that I had to rename the landing page from "Browser monitoring" to just "Browser" to avoid two stacked, identical headers on that TOC page. So, the new browser landing page now just says "Browser"; I …
=> Restore "Single page apps" to left navigation panel

plugins/gatsby-plugin-auto-index-pages/gatsby-node.js, src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-700.mdx
Link should point to the parent release notes page, not a specific (first) version
* What problems does this PR solve? prevents users from downloading incorrect version of XCFramework agent or from having to take extra steps to get to the most recent version
=> Update link in ios-agent-700.mdx

CONTRIBUTING.md
* The content had things in reverse. If the user is cloning & working
in the the fork, then they need to connect to the public repo.
* Also switched steps 5,6 since I think that is the usual workflow.
Starting from develop, pull in changes, then cut a new branch.
Related issue: #1063
=> chore: update private edits section

.github/workflows/release.yml
Comments out the release workflow which depends on tags. We can uncomment this once we have some kind of versioning in place 
closes https://github.com/newrelic/docs-website/issues/1682
=> Disable deployment marker action until we've got versioning

src/content/docs/mobile-monitoring/new-relic-mobile-android/api-guides/android-agent-configuration-feature-flags.mdx
A contributor mentioned in issue 1664 that there was a an incorrect API:
"withCrashReporting(true)" needed to be replaced by "withCrashReportingEnabled(true)"
I confirmed this with an SME.
closes #1664
=> Per GitHub issue 1664, updated code snippet.

src/content/docs/browser/browser-monitoring/getting-started/browser-summary-page.mdx
This is an interim fix to remove references to the depreciated Apdex chart, but the page will need more edits to update screenshots and add references to newer functionality.
=> Trying to remove apdex references

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1162.mdx
This PR addresses new infrastructure agent release of version 1.16.2. This release is a bit special as we are doing it in a granular way. We may ask to update this page several times during the release process.
=> infrastructure agent 1.16.2 release notes

plugins/gatsby-plugin-release-note-rss/gatsby-node.js
The current GUIDs for our release notes RSS feeds can change, causing downstream issues for consumers of these feeds.
This PR makes the GUID deterministic and based on the subject of the release note and the version.
Closes #1271
=> fix: make rss guids deterministic

gatsby-node.js, plugins/gatsby-plugin-auto-index-pages/gatsby-node.js
The warnings are due to us creating pages without trailing slashes in docs-website, then in the theme the trailing slash is added. When we do a hot reload, we recreate pages without trailing slashes (like before), which produces this produces the warning we see.
To remediate this, added trailing slashes to the places where we use createPage in docs-website and set the path of the page.
Resolves #1385
=> Fix warnings on hot reload

.github/workflows/build-with-swiftype-content.yml, gatsby-config.js
Enables the "Build with swiftype" workflow to run twice a week and ensures that we're only showing related resources for the same language.
[Here](https://github.com/newrelic/docs-website/runs/2282202029?check_suite_focus=true) is an example of a successuful run of this workflow. I've also run this a few times on my machine (with one page, some pages, and all pages). I haven't run into any issues from _Swiftype_ so I think this work is...ready?
* Closes #1353
=> Enabling related resources

src/nav/telemetry-data-platform.yml
This restores the API category into the taxonomy. 
Please wait to review this until the Amplify preview is finished so we can test it easier!
=> Fixing the restoration of API do taxonomy

.github/workflows/release.yml
Adds an action that will fire whenever a PR is merged into `main` that does the following:
1. Gets the number of PRs merged into the `main` branch.
2. Creates a release tagged with the #.
3. Sends a deployment marker to New Relic (with the new tag name).
I opted to do _all_ merges into `main` rather than the merges since we launched the site. This number is fairly arbitrary and I thought it would be best to simplify our workflow. Since the site has been open source from the very begining, starting the count from the first merge makes sense.
Along the same lines, I decided to reach for `gh` rather than running `git` commands. Unfortunately, I wasn't able to test these commands using _act_, but I've run them all locally and I can confirm that they work.
* Closes #1049
* Closes #1410
=> Publish a release when merging into `main`

.github/workflows/build-with-swiftype-content.yml
workflow is failing due to invalid cron syntax. should be good now.
Resolves #1773
=> fix: error in cron configuration

src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
We had a broken link to a table of contents page in the trace observer instructions (step 6) in the following page:
https://docs.newrelic.com/docs/distributed-tracing/infinite-tracing/set-trace-observer/
=> Fixed broken link in trace observer step.

src/content/docs/integrations/google-cloud-platform-integrations/get-started/integrations-custom-roles.mdx
For monitoring GCP Cloud Integrations we now require new permission that is required to monitor all services
=> Update required permissions for GCP

src/data/taxonomy-redirects.json
For doc-6691, I looked at lines 2-80 in the spreadsheet of 404 errors related to pages that don't have front matter redirects. These are handled in `taxononomy-redirects.json`. 
I corrected most of the entries, but I also inserted some questions in the spreadsheet.
=> Doc 6691 fix 404s part 1

src/data/whats-new-ids.json
In a previous PR for this logs "What's new" post, I had to remove the JSON id to resolve a problem with duplicate IDs. Since this post won't work correctly in the UI without an ID, I created this follow-up branch.
Reviewer: Please just confirm that you can see this new What's new" post and take a look at the `whats-new-ids.json` file to confirm that you don't see any duplicates in the neighborhood of this latest entry.
=> Rebuilt this project to re-create the json ID

src/content/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing.mdx
Latest version of the Node agent has a fix for a memory leak introduced when Infinite Tracing was enabled. Changed minimum required version for Node agent to require an agent version that includes this fix:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-7-3-0/
=> chore: Change Node agent min. required version for ∞T

src/templates/releaseNoteLandingPage.js
Includes `inlineCode` node type to include in an agent's release note landing page excerpt. These excerpts are plain text, so the inline code style won't be used. But this at least preserves some important context in the excerpt.
- Resolves #1793 
[Java agent 6.4.2 excerpt](http://localhost:8000/docs/release-notes/agent-release-notes/java-release-notes/)
=> Fix: Include inlineCode elements in release notes excerpts

src/content/docs/logs/enable-log-management-new-relic/logs-context-java/java-configure-log4j-1x.mdx
I created an issue here:
https://github.com/newrelic/docs-website/issues/1805
The 2nd precondition listed on the extension project's readme wasn't included on the docs page.  It generated a support ticket.  This change just adds a bullet point for that missing precondition.
https://github.com/newrelic/java-log-extensions/tree/main/log4j1#preconditions
compare to
https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-java/java-configure-log4j-1x/#compatibility-requirements-log4j-1
no
=> Add additional pre-condition for log4j1.x Usage

src/content/docs/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
A Docs hero request came in about how it's not possible to select the code methods for copy/pasting. I've added code boxes for these API headers in each of the collapser sections so it's possible in some fashion.
=> This makes it easier to copy and paste these API headers

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-cloudwatch-logs.mdx
It adds a missing configuration field for the `aws-log-ingestion` lambda, which allows the customer to run it in debug mode.
The PR should be self-explanatory as it explains what is this config field for.
=> Adds documentation for DEBUG_LOGGING_ENABLED environment variable configuration in aws-log-ingestion lambda

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-7-3-1.mdx
Added release notes for the v7.3.1 release of the Node.js agent.
Did add a special call-out to highlight a part of the note that I've seen in other documentation. Assuming works on release notes as well.
=> chore: adds release notes for Node.js agent v7.3.1.

.github/workflows/release.yml
A previous fix to the Github release workflow is [still failing](https://github.com/newrelic/docs-website/actions/runs/752715586). We think this is due to incorrect permissions with the `GH_TOKEN` provided. This PR updates the code to use `GITHUB_TOKEN` which [should be available](https://github.blog/2021-03-11-scripting-with-github-cli/#using-gh-in-github-actions) from the actions environment.
* Closes #1819 (hopefully)
=> Fixing release workflow (again)

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
The documentation says:
> The log forwarding feature is not supported on containerized agents.
However in the next section, it provides a link to instructions on how to install the containerized agent. 
This is confusing so I've removed the link.
No
=> Remove link to install unsupported agent (forward-your-logs-using-infrastructure-agent.mdx)

.github/workflows/release.yml
Updates our release workflow so that the title of the release is the same as the version name. Without this, the release title was the last commit.
The last time the release workflow ran, [it failed](https://github.com/newrelic/docs-website/runs/2355397196?check_suite_focus=true). It doesn't look like this was an issue with our workflow, but rather an issue with Github actions (it never made it to our step). I'll monitor it :eyes:
=> Use tag name for release name

.github/workflows/release.yml
This PR swaps a flag used in our github release action which was previously causing an issue (using `wc` `-L` counts the length of the longest line while `-l` counts the number of lines ). also updates the release logic to only count merged PRs (not including every closed PR) and starts the count from march 1st
=> chore: Adjust gh cli command

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-alerts-policies.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-examples.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-loss-signal-gap-filling.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-nrql-condition-alerts.mdx, src/content/docs/apis/get-started/intro-apis/introduction-new-relic-apis.mdx, src/content/docs/apis/nerdgraph/examples/configure-infinite-tracing-graphql.mdx, src/content/docs/apis/nerdgraph/examples/create-widgets-dashboards-api.mdx, src/content/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api.mdx, src/content/docs/apis/nerdgraph/examples/export-import-dashboards-using-api.mdx, src/content/docs/apis/nerdgraph/examples/golden-metrics-entities-nerdgraph-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-cloud-integrations-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-distributed-trace-data-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-relationships-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial.mdx, src/content/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys.mdx, src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/content/docs/apis/nerdgraph/tutorials/nerdgraph-workloads-api-tutorials.mdx, src/content/docs/apis/nerdgraph/tutorials/provisions-your-subscriptions-nerdgraph.mdx, src/nav/alerts-and-applied-intelligence.yml, src/nav/telemetry-data-platform.yml
Asking @rhetoric101 if he wants to do review on this. See jira for details. Basically overhauled the intro doc, making it easier to understand what NerdGraph is, and how it works, and using simpler, more direct language, and including a helpful video. I also added all the assorted NerdGraph tutorials in one place in the intro doc, because previously we didn't have the full list there (as they are a bit scattered throughout docs site). And I retitled all nerdgraph-related docs and changed their short titles to make them all more aligned.
=> Doc 6677 - Improvements to NerdGraph intro and nav

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/save-browser-spa-api.mdx
This PR includes a temporary fix to a code block on one of our pages. For some reason, this one code block is being evaluated as valid JS. I was not able to determine _why_ this was happening, since no other javascript block behaves this way and I was unable to reproduce this effect elsewhere.
* Closes #1873
=> Resolve console error with Browser SPA page

src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx, src/content/docs/insights/event-data-sources/default-events/default-events-reported-new-relic-products.mdx, src/content/docs/insights/event-data-sources/default-events/events-reported-apm.mdx, src/content/docs/insights/event-data-sources/default-events/events-reported-browser-monitoring.mdx, src/content/docs/insights/event-data-sources/default-events/events-reported-mobile-monitoring.mdx, src/content/docs/insights/event-data-sources/default-events/events-reported-synthetic-monitoring.mdx, src/content/docs/insights/event-data-sources/default-events/nrauditevent-event-data-query-examples.mdx, src/content/docs/insights/event-data-sources/default-events/query-account-audit-logs-nrauditevent.mdx
Based on https://github.com/newrelic/docs-website/pull/1895, manually fixing broken links. But this is larger issue we need to create a jira for, because all data dictionary links, including specific attribute links, were broken in the migration.
=> Fix broken data dictionary links in default events docs

src/content/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic.mdx
We have a great definition of "entity" but it seemed a little buried. I moved it next to the first mention of "entity".
=> Moved definition next to first mention of entities

src/content/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx, src/content/docs/agents/php-agent/installation/php-agent-installation-aws-linux-redhat-centos.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9170300.mdx
READY for publication: Updating PHP agent documentation and release notes to reflect the PHP 9.17 release.
=> Add documentation for PHP 9.17 release

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
We've been collecting feedback after the initial launch of the AWS CloudWatch Metric Streams integration. 
Changes:
- Add section to guide customers that want to migrate from polling integrations
- Add section explaining how to import Dashboards from Quickstarts
- Added formal named used by Amazon: AWS CloudWatch Metric Streams (plural)
- Considerations when using dimensional format vs events-based query format
No
=> AWS metric stream integration: post-ga updates

src/content/docs/agents/ruby-agent/background-jobs/resque-instrumentation.mdx
While looking at [this doc](https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/resque-instrumentation/), I noticed the code block did not include syntax highlighting, and the indentation was pretty wonky. This PR updates the code block to add ruby syntax highlighting and fix the indentation.
=> Add syntax highlighting and fix indentation on code block

src/content/docs/logs/log-management/ui-data/data-partitions.mdx
Data partitions is a "go forward" feature which does not affect logs that have already been written to NRDB. We've received a few customer inquiries on this point, updating the docs for clarity.
=> Add "go forward" callout

src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic.mdx, src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-architecture-recipes.mdx, src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start.mdx, src/content/docs/integrations/open-source-telemetry-integrations/troubleshooting/troubleshoot-opentelemetry-exporter.mdx
A follow up from #1907.  For more details see DOC-6641. @rvanderwal-newrelic, please review!
This changes language around the pre-release to reference the OTLP endpoint, not the OTLP exporter, which is slightly ambiguous. In other places, I've tried to be more clear that we mean [the OTLP exporter in the OpenTelemetry collector](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter).
=> Clarify use of pre-release OTLP endpoint

gatsby-config.js
Adds google tag manager config to start tracking via google when not using tessen.
=> Add google tag manager config

package.json, yarn.lock
Fixes a bug in the `gatsby-theme-newrelic` dependency where it wasn't sending the referral field to segment.
Partly closes https://github.com/newrelic/docs-website/issues/1816
=> fix: referrer field not being sent on sign up

plugins/gatsby-plugin-auto-index-pages/gatsby-node.js, src/utils/__tests__/findDeepIndex.text.js, src/utils/__tests__/sortIndexPage.test.js, src/utils/findDeepIndex.js, src/utils/sortIndexPage.js
Improves the sort order of our automatically generated index pages by applying the following updates (in order):
1. Sort the sections alphabetically (by section title)
2. Sort the links within the section alphabetically (by title)
3. Sort the sections by their relative position in the site navigation
4. Sort the links within the section by their relative position in the navigation
For steps 3 and 4, we're using the first navigation file that the script finds that includes the link (in the event that there are multiple nav configuration files).
I'm creating a draft PR in case I'm unable to wrap up the work. I've taken a TDD approach to solving the issue, since there are multiple edge cases that I wanted to ensure we caught. Here is my current progress:
* Closes #566
**Before**
**After**
=> Improve index page sort order

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
Adding a link to AWS documentation that shows users which AWS services and namespaces are currently supported
Nope
=> link to CloudWatch docs for AWS namespace support

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
We would like to start linking to the official NR Helm Chart repo for customers to retrieve the CPM (Containerized Private Minion) Helm charts. We're currently linking to a Synthetics owned Helm chart repo, but would like to start the process of deprecating it in favor of the official NR Helm chart repo found [here](https://github.com/newrelic/helm-charts).
No
=> Update Helm chart URL to point to official New Relic Helm chart repo

.github/workflows/release.yml
This PR removes the new relic deployment marker as it doesn't work for non-APM applications.
=> chore: removed deployment marker

.github/workflows/build-with-swiftype-content.yml, .github/workflows/update-whats-new-ids.yml, gatsby-node.js, package.json, scripts/actions/generate-whats-new-ids.js
This PR adds a workflow to generate whats new IDs used for the `https://docs.newrelic.com/api/nr1/content/nr1-announcements.json` endpoint. Previously we generated these during the build, which meant new IDs lived in memory until someone ran a local build and committed those changes. This will get rid of the process on build and run it in a workflow that occurs on PRs to main. This way new IDs should get committed as necessary on each release
Closes https://github.com/newrelic/docs-website/issues/1561
=> Create whats new ID workflow

.github/workflows/update-whats-new-ids.yml
We recently attempted to update the Github tokens used in our workflows (#2037 and #2030). It turns out that the original token we had in place may have been accurate, but the bot user didn't have the right _permission_ in the repository. Since neither of the token updates we did yesterday worked, I'm reverting those updates and will explore giving the bot the correct permissions.
=> Reverting back to the opensource bot token

.github/workflows/update-whats-new-ids.yml
This workflow disables and reenables branch protection. Previously it was setting enforce_admins to true which was turning on branch protection for admins when we'd agreed not to enforce that. This corrects it to false
=> Edit branch protection reenablement

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9171301.mdx
This includes the release notes for PHP agent 9.17.1. The release is targeted for 4/28/21.
=> PHP agent 9.17.1 release notes

src/content/docs/accounts/accounts-billing/account-setup/account-id.mdx
Realized this doc didn't have right instructions for users on New Relic One (v2) user model.
=> Small edit to account ID doc, correcting wrongness

.github/workflows/build-with-swiftype-content.yml
Like we did in #2045, we'd like to keep using the `OPENSOURCE_BOT_TOKEN` for our workflows that require altering branch protection.
=> Revert token for swiftype workflow

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
`unique` is not a function, but `uniques` is
=> Fixing typo in NRQL `tuple` description

src/content/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration.mdx
The return values of some MySQL cluster status metrics resulted in `Yes`, `No`, or `Connecting` rather than documented `boolean` values. The PR addresses this documentation inconsistency and provides a reference to current documentation for the MySQL status command that provides the metrics.
=> Updating the value types to match the MySQL documentation.

src/content/docs/agents/go-agent/instrumentation/go-agent-attributes.mdx
This anchor was a duplicate of the one above it. I've adjusted the name so it'll link to the correct section.
=> Fix anchor in Go attributes documentation

src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic.mdx
This PR fixes two broken links to external sites from the OpenTelemetry introduction.
=> Corrected two broken links to external sites.

src/components/DataDictionaryFilter.js
Fixes issue where if you filter on an attribute (via query param OR by selecting it in the right menu), then change the Data Type or Data Source filters, the filtered attribute isn't cleared and remains in state / query params. I'm pretty sure we always want to clear any filtered attribute when changing to a different Data Type / Data Source.
Current behavior
https://user-images.githubusercontent.com/2952843/116760489-e2970200-a9c9-11eb-9af2-dca0dd4a4b12.mov
PR behavior
https://user-images.githubusercontent.com/2952843/116760568-1e31cc00-a9ca-11eb-9b4f-d6e1f4b301d9.mov
=> Fix: Reset any filtered attribute when changing data type / data source filters

gatsby-config.js
Makes images in `.md` and `.mdx` files link to their original file so they can be viewed in original resolution / size. GIFs not supported in this work.
* check JSON endpoints that include HTML to ensure it won't cause any issues rendering in NR1 (what's new, NR1 Help XP, translation serialization)
* [What's New post](https://pr-2001.d1vx4w5vgyla4s.amplifyapp.com/whats-new/2021/04/log-part/)
* [MDX page with image](https://pr-2001.d1vx4w5vgyla4s.amplifyapp.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide/)
* short term fix for https://github.com/newrelic/docs-website/issues/850
=> Link image to original

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/alert-custom-violation-descriptions.mdx
The `Mentioning users...` section had the same `href` as `Create description...NRQL` , so just edited the reference in the md page
=> fix: RightRail rendering list items with the same href

src/content/docs/agents/manage-apm-agents/agent-data/agent-attributes.mdx
This request came from an internal contributor who pointed out that we had two broken links. While I was in the neighborhood, I removed a bunch of absolute path prefixes, too.
=> Corrected Node and PHP links and removed URL prefixes in other links

.github/workflows/update-whats-new-ids.yml
The latest version of `to-vfile` converts it to a ESM module, we are not ready for that update. This PR pins the version to 6.1.0.
=> fix: lock down to-vfile version

src/content/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/alerts-conditions-api-field-names.mdx
Here's the problem this fixes: The docs incorrectly state that the `fill_option` field requires  "Last known value” but  API Explorer throws an error.
I checked with the hero in alerts and confirmed that this is incorrect. At the hero's suggestion, I borrowed the descriptions for these fields from the [UI doc](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/#data-gaps).
I got a sign-off from the hero in alerts for my proposed revision.
I could use a formatting review.
=> Corrected "last_value"  for API and borrowed descriptions from the UI doc.

src/content/docs/style-guide/processes-procedures/use-content-types-text-formats.mdx
The frontmatter field is `type` and not `contentType`. Also, added brief info about default value if omitted from an .mdx file.
=> Use `type` instead of `contentType`

src/content/docs/style-guide/processes-procedures/update-left-navigation-pane.mdx, src/layouts/MainLayout.js
Allow nesting of up to 6 levels deep in the navigation and document it.
This is in preparation of work being done in https://github.com/newrelic/docs-website/pull/2119
=> increase and document nav nesting levels

src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx
We were alerted to this by a notice in the documentation channel.
=> Remove link for a section that's not in doc

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3720.mdx
Add in the latest release of the New Relic for iOS mobile app, version 3.72.0.
=> Add in ios mobile app release note 3.72.0

src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx
Adding missing redirect to 'intro to querying data' doc
=> Adding missing redirect

gatsby-config.js
The `contribute` link in the right nav of the docs site currently links to `contributing.md`. 
This PR changes that link to point towards our content contribution style guide doc, since we migrated all the info in #1853.
=> Change contributing url to style guide

src/content/docs/style-guide/writing-guidelines/create-edit-content.mdx
(This is from @austin-schaefer 's training account)
I believe cutting the intro here makes the info more accessible. The focus here is content, not code.
=> Cut intro paragraph to just focus on content edits

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/enable-log-management-new-relic.mdx
Heroku log streaming and the syslog TCP endpoint were missing from the list of available log forwarding solutions.
=> Add Heroku Log Streaming and Syslog

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
Ubuntu 14 is not supported anymore in the infrastructure agent. 
Ubuntu 14.04 has reached EOL in 2019.
=> Remove unsupported Ubuntu 14 (EOL)

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
An internal contributor pointed out a google search result pointed to a 404. This PR adds a redirect for the page to this doc.
=> Added missing redirect

gatsby-config.js, package.json, yarn.lock
To enable splits, AKA A/B testing, a new button component has been added to the theme's header. This PR updates to that version of the theme and sets up the required configuration values.
Closes newrelic/gatsby-theme-newrelic/issues/356
=> feat: Update theme to include split(a/b) testing

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/fluentd-plugin-log-forwarding.mdx
Build was broken due to some missing collapser tags, this fixes them.
=> Fix broken build due to missing tags

src/content/docs/apis/nerdgraph/examples/create-widgets-dashboards-api.mdx
A few Insights docs are giving 404, this PR fixes those.
So far I'm redirecting Insights API related docs to https://docs.newrelic.com/docs/apis/nerdgraph/examples/create-widgets-dashboards-api/
=> Adding a few redirects for Insights docs

package.json, yarn.lock
Updates our gatsby theme to 2.2.2 which includes a reduction in console warnings and whitespace wrapping in codeblocks
Closes https://github.com/newrelic/docs-website/issues/1138
Specific pages to check in the preview from issue https://github.com/newrelic/docs-website/issues/1138:
`/docs/integrations/amazon-integrations/get-started/aws-integrations-metrics`
`/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/#configure-algorithmia`
=> Update gatsby theme

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/incident-intelligence-destination-examples.mdx
Updated the URL variable so that the incident URL comes in as a clickable URL instead of plaint text.
=> Updated URL Variable

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/logstash-plugin-log-forwarding.mdx
`logstash-pluing` v1.2.0 introduce a new setting to configure max retries when ingesting logs to NR. I'm adding this information on our public doc.
=> docs: add logstash max retries configuration

src/content/docs/query-your-data/explore-query-data/use-charts/chart-types.mdx
When doing DOC-6819, Insights cat deprecation, realized I'd forgot to add back this 'pie chart percentage' doc into the pie chart section.
=> Add pie chart troubleshooting to pie chart section

.gitignore
Since changing the swiftype resource fetch process we want to gitignore the file created on build and not check it in (it's too large anyway). seems it wasn't actually getting ignored so this alters the path to the file
=> Update gitignore path to swiftype-resources

src/content/docs/apis/insights-apis/insights-dashboard-api.mdx, src/content/docs/apis/insights-apis/query-insights-event-data-api.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx, src/content/docs/query-your-data/explore-query-data/get-started/introduction-data-explorer.mdx, src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx, src/content/docs/telemetry-data-platform/ingest-apis/introduction-event-api.mdx, src/content/docs/telemetry-data-platform/understand-data/new-relic-data-types.mdx
For DOC-6819, missed some Insights category level redirects. Added them into various docs for this one.
=> Missing few Insights redirects

src/content/docs/distributed-tracing/infinite-tracing/introduction-infinite-tracing.mdx
This link was leading to a `404`
=> chore: changed Trace API link

src/content/docs/telemetry-data-platform/ingest-apis/metric-api-limits-restricted-attributes.mdx
Updated the Additional account conditions links so they take the user to the correct section. Currently the links are dead because they point to a link that doesn't work.
=> Updated Addl Considerations Link

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action.mdx
Adds spaces to `<a>` tag in code block to prevent parsing and rendering as HTML link. This is supposed to be part of the example and not rendered as a link, like we do in other code blocks.
Closes https://github.com/newrelic/docs-website/issues/2193
The first example in this doc has a link that should just show the `<a>` code as is: http://localhost:8000/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action/#examples
=> Fix code block example to display a tag and not render html link

src/data/homepage.yml
Note for reviewer: Please pull down and test locally, since this change affects the homepage.
* The order of the integrations tiles on the homepage were intended to reflect importance
* There are so many tiles, though, that the order isn't intuitive to the reader
* This PR switches order for each section to simple alpha order
**Before**:
**After**:
=> Rank homepage integrations in alpha order

src/content/docs/telemetry-data-platform/get-started/introduction-new-relic-data-ingest-apis-sdks.mdx
=> chore: fixing Trace API link

gatsby-config.js, package.json, yarn.lock
Adds [gatsby-plugin-gatsby-cloud](https://www.gatsbyjs.com/plugins/gatsby-plugin-gatsby-cloud/) to `gatsby-config.js`. This is a recommended plugin for any Gatsby site being hosted on their platform.
* Relates to #1933
=> Add Gatsby Cloud plugin

src/content/docs/style-guide/quick-reference/collapsers.mdx
The `h` shortcut doesn't work on the new site (to my chagrin)
=> Keyboard shortcut that no longer works

src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx, src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
Removed a google doc link that it was thought we didn't need, and rephrased some stuff in the 'User migration' doc. 
Added missing redirect
=> Some small changes

src/data-dictionary/events/DistributedTraceSummary/newRelic.traceFiler.type.md, src/data-dictionary/events/DistributedTraceSummary/newRelic.traceFilter.type.md
Original version is missing a 't'. Changed 'newRelic.traceFiler.type' to 'newRelic.traceFilter.type'. 
Example of span JSON data including this attribute:
` "events": [
{
"category": "generic",
"duration.ms": 1.7349720001220703,
"entity.guid": "MTU2NDk3OXxBUE18QVBQTElDQVRJT058OTQ1NzIwMTE4",
"entity.name": "My application (Development)",
"entityGuid": "MTU2NDk3OXxBUE18QVBQTElDQVRJT058OTQ1NzIwMTE4",
"id": "b31939a4a3bb8b36",
"name": "View/layouts/application/Rendering",
"newRelic.ingestPoint": "api.infiniteTracing",
"newRelic.traceFilter.type": "random",
"parent.id": "14b94d4d9a9c3f69",
"priority": 0.855915,
"service.name": "My application (Development)",
"timestamp": 1620941516809,
"trace.id": "ecfad11074c88453423a4d1c691322dc",
"transactionId": "dc044101e165800b",
"type": "Span"
},`
As …
=> Fix 'Filter' spelling

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
As reported in #2177, the guided install instructions for AWS Metric Streams are misleading. Synching with @josemore 
and updating doc accordingly.
=> Updating guided install instructions

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/update-or-disable-policies-conditions.mdx
New Relic account admins can remove the ability to delete a policy condition. I thought this collapser section could use a tip to that effect.
=> Added a tip related to policy condition deletion

src/content/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic.mdx
Describe how to delete an APM app using the UI (new capability as of May 18 or 19). Also describe the same process for Mobile and Browser apps, which has existed (undocumented) for longer.
Contact ralph@newrelic.com with any questions about timing deployment of this edit :)
=> APM apps/services can now be deleted from the UI

README.md, gatsby-config.js, src/content/docs/apis/insights-apis/insights-dashboard-api.mdx, src/content/docs/apis/nerdgraph/examples/create-widgets-dashboards-api.mdx, src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/dashboards-api-migration-insights-api-nerdgraph.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/transition-new-relic-one-insights.mdx, src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx, src/nav/new-relic-one.yml
* Adding some mapping tables in the Insights API -> NR1 dashboards API migration doc
* Also updating the new dashboards API examples so people can copy/paste and start playing around
* Adding some callouts to drive people to the migration doc in case they are coming from Insights
* In the context of the Insights dashboards API being EOLed soon, help Insights API users migrate to the new dashboards API
=> Add mapping tables plus real examples in insights api migration guide

gatsby-config.js, src/content/docs/distributed-tracing/index.mdx
When I made a new landing page for distributed tracing, I didn't add this redirect from the observability solutions navigation tree. So, this should fix the navigation tree that has a redirect to distributed tracing.
To test this, go to Full-Stack-Observability > Observer everything > Observability solutions > Distributed tracing.
=> Added a redirect from observability solutions that got dropped.

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
I identified some minor issues with a hero edit (https://github.com/newrelic/docs-website/commit/8f43de32325329dc10f5ea4035cef6c7926a0cd7) while re-visiting some of my old docs (hi team! Miss you!).
I changed the order of the requirements to give more visibility to the OpenSSL requirement and edited the OpenSSL line to make it shorter: the statement about operating systems releases prior to year 2016 is overly specific, in my opinion.
=> Fix for secondary log forwarding requirements

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
Hi!
This PR removes some dependencies from the docs that are not needed anymore on the infra-agent for enable logging:
- Microsoft Visual C++ Redistributable is not needed anymore since version 1.12.4 for Windows.
=> Removing logging dependecies that are not needed anymore from docs

src/pages/index.js
The amount of available integrations didn't match in the UI, as reported in #2388. This PR corrects this.
=> Corrected amount of integrations

src/content/docs/integrations/kubernetes-integration/installation/configure-control-plane-monitoring.mdx
Closes #2375.
This redirect was preventing access to the Configure Kubernetes with a proxy doc in the left nav. I removed it.
=> Removed redirect preventing access to a doc in the left nav

amplify.yml
Our builds are not getting deployed on AWS Amplify. Their engineering team suspects that this is due to our builds taking longer than an hour (presumably, we are given an authorization token that expires after an hour). This change was suggested as a possible way to help with the problem while they continue to look into the problem.
=> Adjust Amplify build settings

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/vector-output-sink-log-forwarding.mdx
Updated the sample config file to include a line for encoding. That's required to get vector to work. I also deleted the data_dir lines from the config since that entry caused an error with vector on startup. Removing that line fixes the issue. It's also redundant since that data_dir entry comes with the default vector.toml file. Last, I updated the vector.conf file to accurately reflect the file having a .toml extension, not a .conf extension.
[conventional commit …
=> Updated vector config samples

.github/workflows/release.yml
This is so that the `Get release notes` step can pull data on more than 1 commit
=> fix: increase fetch-depth of action

.github/workflows/send-content-to-translate.yml
This PR changes the translation cron job to run on 1st and 15th of a month. this cron config can be validated here:
`https://crontab.guru/#0_1_1,15_*_*`
=> chore: changes cron job

package.json, yarn.lock
Fixes unexpected 404 network requests when prefetching and preloading resources for redirected pages
For example page ( `/docs/agents/c-sdk/`):
Before:
After:
Remaining 404 responses are not related to redirects - those 2 on this page are for:
1) The link to image (`![c-sdk-transactions1-crop.png](./images/c-sdk-transactions1-crop_1.png "c-sdk-transactions1-crop.png")`) that seems to try to use `gatsby-link` for link (didn't investigate this part yet)
2) this one is actually valid 404 - there's link that point to not existing page that also doesn't have redirect (`/docs/insights/using-insights-ui/getting-started/introduction-new-relic-i …
=> chore: bump gatsby to 3.5.1

src/content/docs/apm/apm-ui-pages/error-analytics/errors-page-find-fix-verify-problems.mdx
This issue was raised in documentation. Evidently this redirect was missing. I found it over in Drupal.
You can test this redirect by going to these two pages:
* /docs/accounts/original-accounts-billing/product-based-pricing/overview-data-retention-components/#components-trace-data
* /docs/agents/ruby-agent/configuration/ruby-agent-configuration#disable_sinatra_auto_middleware
=> This APM analytics redirect should fix a bunch of broken links

src/data/taxonomy-redirects.json, src/nav/full-stack-observability.yml
Per notification in the documentation channel that these were broken.
=> Redirecting the taxonomy for two files - Azure and GCP

src/content/docs/integrations/host-integrations/host-integrations-list/statsd-monitoring-integration.mdx
Added a note and link to the EOL communication for the StatsD v1 on-host integration. 
Customers should migrate to v2.
=> StatsD v1 integration EOL June 1st 2021

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60400157.mdx
Our original release notes included a note about server side configuration not being released which is no longer applicable. This PR removes that note and fixes a few additional typos.
=>  Add minor updates to python agent 6.4.0 release notes.

src/content/whats-new/2020/10/alerting-loss-signal-detection-configurable-gap-filling-strategies.md
Fixed erroneous instructions on where to go to find Gap Filling and Loss of Signal
=> Fix erroneous info

scripts/actions/add-files-to-translation-queue.js
Updates the translation queue script to filter out removed files before trying to read their contents to process them.
=> Fix translation script to disregard removed files

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
links to "Intro to APIs" were going to NRQL page. This removes the redirect to NRQL, to ensure people get to the proper API page.
=> redirect fix to address documentation channel feedback

src/content/whats-new/2021/05/programmability-fs.md
This PR is a follow up the the original 'What's new?" PR #2438 that I had to pull back. I had merged that too soon into develop yesterday, so I pulled it back. 
This PR re-stages this certification post to be released on May 27th. I left the original gif in develop so I only needed to re-publish this document.
=> Restoring the original certification announcement for May 27th.

.github/workflows/check-translations-and-deserialize.yml, scripts/actions/check-job-progress.js
This adds output to the `fetch-deserialize` step which runs the `check-job-progress.js` script. If we have no batches of files to pull down and commit, we don't want to run most of the subsequent steps (git committing/PR-ing, removing batches from the queue).
Closes https://github.com/newrelic/docs-website/issues/2419
=> Avoid apparent workflow failure when no changes to commit

src/content/docs/query-your-data/explore-query-data/use-charts/chart-refresh-rates.mdx, src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx, src/nav/new-relic-in-practice.yml
Moving content, related to changes made on recent jira DOC-6819 that I needed to follow up on. Moved 'Chart refresh rates' out of query limits doc and into its own doc.
=> Chart refresh rates 

src/content/docs/agents/php-agent/installation/php-agent-installation-tar-file.mdx
This PR is based on this GitHub issue: #2740
Tell us what you need
https://docs.newrelic.com/php-agent-installation-redhat-and-centos/
URL is not available , getting 404 page not found
Anything else you'd like to share?
URL found on this page "https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-tar-file/"
click on hyperlink "RPM Page" in the second line
Same is for "Debian package" hyperlink on "https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-tar-file/"
hyperlink url : https://docs.newrelic.com/php-agent-installation-ubuntu-and-debian/
Doc information (don't delete this section)
https://docs.newrelic.com/php-agent-installation-redhat-and-centos/
OS: Windows 10
Browser: Chrome 90.0.4430.212
Device: Unknown
=> Corrected two PHP links based on pages I found in the old Drupal site.

src/content/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
While looking at issue #2420, I noticed that the heading "Automatically instrumented frameworks and libraries" includes the same phrase as the child collapser "Frameworks and libraries." I discussed with engineers, and they are OK with this change of the heading:
OLD: Automatically instrumented frameworks and libraries 
NEW:  Built-in instrumentation
=> Changed section heading for clarification.

src/content/docs/distributed-tracing/concepts/distributed-tracing-planning-guide.mdx
It turns out that legacy service maps don't work with Mobile distributed tracing, so I inserted "legacy" to differentiate the type of service maps that don't work.
=> GitHub issue 2157: Clarify service map functionality for Mobile distributed tracing.

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
Looks like I missed syslog when i moved the content into a collapse group. Also moved the sample config to its own section since I accidentally put the header for it under fluentbit. Should be fixed now :)
=> Fixing some collapser issues

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx, src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Infrastructure agent will be available for arm64 machines with standard linux package setup.
* This PR updates the manual installation steps and support matrix to explain arm64 support.
* Support is limited to infra-agent and few additional integrations (no log-fwd, no OHIs at the moment). 
=> Infra agent support for arm64

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/incident-intelligence-destination-examples.mdx
The only difference is the triple quotes ””” for parsing the 'description' field properly. This was a string escaping problem in the description field.
=> OpsGenie schema needed to have a syntax update

src/content/docs/apis/intro-apis/introduction-new-relic-apis.mdx, src/content/docs/full-stack-observability/instrument-everything/develop-own-integrations/flex-integration-dummy.mdx, src/content/docs/integrations/host-integrations/host-integrations-list/flex-integration-tool-build-your-own-integration.mdx, src/nav/full-stack-observability.yml, src/nav/telemetry-data-platform.yml
This was fixing a couple broken links: https://docs.newrelic.com/docs/apis/get-started/intro-apis/introduction-new-relic-apis/ and https://docs.newrelic.com/docs/full-stack-observability/instrument-everything/develop-your-own-integrations/new-relic-apis/, and also fixing some TDP nav file paths that were wrong. Also instituting an edit to create a 'Develop your own integrations' index view.
=> Some FSO and TDP nav work

src/content/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
The OracleDB integration will fail to collect more than 200 tablespaces. When the user's environment has more than this amount, it is required to restrict collection using the (previously undocumented) `tablespaces` argument.
This PR documents this parameter and its usage.
No
=> nri-oracle: document usage of `tablespaces` argument

src/content/docs/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
This PR add a callout to a specific config that is overwritten by server config instead of env variables. See #2546 for more context.
=> Add order of precedence callout to ruby config

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* We recently added support for ARM architecture. 
* We validated that it's actually not needed to determine the amd or arm64 architecture for Ubuntu and Debian since this will be automatically detected. 
* Removed unnecessary params to determine the right architecture in docs.
=> Unnecessary arch params on Debian & Ubuntu

src/nav/full-stack-observability.yml
It's weird having an install doc at the bottom of the category, after delete/disable docs
=> Fix sort order for Browser AMP doc

.github/workflows/release.yml, scripts/actions/release-notes.py
Previously it was just comparing latest main to latest develop which shows no results because this is run after the merge. I changed it to compare the tag of the previous release with latest develop to get commits since then.
=> chore: now compares last release to latest develop

scripts/actions/check-job-progress.js, scripts/actions/utils/vendor-request.js
The workflow that checks the status of ongoing translation jobs (and makes a PR back into `develop`) was not picking up the most recent translation jobs. This was due to a few missed edge-cases. This PR should add some extra checks to ensure that the workflow will run successfully.
In addition, I spent a little effort cleaning up the comments and adding some better logging so we can more easily troubleshoot this workflow in the future.
* Closes #2404 (when merged into `main` and the workflow runs)
=> Fixes & updates to translation workflow

src/content/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration.mdx, src/content/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration.mdx
Added an entry for mysql installation on Windows. NR hosts the windows .msi file on our download site but we don't have directions for it in our docs. The docs explicity required a linux host which isn't true so I cleaned up that verbiage as well. For both files i just updated our links to the download site to default to https since we don't redirect there from http links.
in your commit messages and pull …
=> mysql and postgres doc update

src/content/docs/agents/ruby-agent/features/new-relic-browser-ruby-agent.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-710.mdx
**NOTE:** This PR supersedes #2397 
This PR adds the release notes for the upcoming release of the ruby agent, 7.1.0., and also adds a section to the browser monitoring page about our new support for CSP nonces.
**Please don't merge this PR until we are ready to release.** @amhuntsman will provide release updates.
No, only content changes
=> Updates for upcoming ruby agent release 7.1.0

package.json, yarn.lock
The latest release of the `gatsby-theme-newrelic` has been updated to handle cookies and localStorage being blocked. This gets us up to that version.
Closes #2293
=> fix: bump theme to version that handles blocked cookies

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Nested queries with `WITH METRIC FORMAT` cannot be used to set a NRQL condition. For more details, see [Doc6871](https://newrelic.atlassian.net/browse/DOC-6871).
=> DOC-6871 - Nested queries limitation

src/content/docs/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
I'm not sure how the formatting will all look on the main docs site... I tried to add less than/greater than symbol to an xml blob but it's not easy to see if it's working properly with the github preview tool.
* I ran through the Dotnet agent Linux install instructions for Azure Web Apps and I'm not sure if Azure changed, or Visual Studio changed... but the steps required to get this going weren't clear from the existing documentation.
* I tried to add some missing less than/greater than symbols in sample XML fragments, but it's not clear if this will render properly on the main site.
* I added a new env var that I had to set to get things going
* I added a note about needing to manually copy the newrelic.config file out of the nuget package contents in to my application as visual studio …
=> Update dotnet agent installation instructions for Linux based Azure Web Apps

src/content/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits.mdx, src/content/docs/logs/log-management/log-api/introduction-log-api.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic.mdx, src/content/docs/telemetry-data-platform/ingest-apis/introduction-event-api.mdx, src/content/docs/telemetry-data-platform/ingest-apis/metric-api-limits-restricted-attributes.mdx
* Add a synthesis section to the Entities' documentation, explaining our reserved attributes.
* Add entity reserved attributes as restricted attributes on the relevant Ingestion APIs docs.
I checked how the changes look locally as instructed in the README. 
No, only documentation changes.
=> Add entity synthesis section and restricted attributes

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60401158.mdx
This PR adds release notes for Python Agent v6.4.1.158.
=> Add Python Agent release notes v6.4.1.158 

src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx
This update fixes the destination path for customer modules on the Synthetics - Kubernetes Containerized Private Minion (CPM) installation docs. Refer to https://discuss.newrelic.com/t/deploy-cpm-on-kubernetes-pod-fails-to-start-with-custom-modules/145992/2 for the issue that was raised.
No
=> fix: destination path reference for K8s CPM custom modules

.github/workflows/release.yml, scripts/actions/release-notes.py
If there is an error getting any details from the commit object, the code will now catch these and continue with the loop instead of failing
I also refactored some of the `release.yml` workflow.
It will now grab the actual latest tag from a release rather than calculating it from the number of merges to `main`, so if a release fails, the next release won't look for a tag that failed to create,and will include all changes since the last release tag.
=> fix: catch errors in release notes failure

src/content/docs/agents/net-agent/attributes/net-agent-attributes.mdx, src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-84000.mdx
1. The .NET agent team is completing the Http Request Header Capture work and expecting to release this feature next week. This PR updates the configuration doc with the new configuration `allowAllHeaders`. 
2. Fix incorrect link.
No
=> Add http request headers capture feature

src/nav/full-stack-observability.yml
It was full on broken. Because there's only one doc in that category, I just made Get started point to that one doc.
This is the broken link I updated: https://docs.newrelic.com/docs/serverless-function-monitoring/azure-functions-monitoring/get-started/
=> Fixing that Get started link in the left nav (hero request)

src/content/docs/distributed-tracing/concepts/introduction-distributed-tracing.mdx
As part of testing the migration of changes from the private docs site, I am fixing a poor image title.
Reviewer: please hover over the image to confirm that the title is no longer the filename.
=> Changed image title from filename to meaningful title.

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Removed limitation on EU datacenter (now fully available for customers)
* Add required mandatory output format to be Open Telemetry 0.7
=> AWS metric streams: New EU endpoint and clarification on output format

src/content/docs/browser/new-relic-browser/troubleshooting/not-seeing-specific-page-or-endpoint-names-browser-data.mdx
Include sentence that makes it clear that this behavior also shows up in some SPA data, not just PageView and Ajax Request browser data.
=> This behavior also shows up in SPA data

src/data-dictionary/events/SystemSample/memoryCachedBytes.md, src/data-dictionary/events/SystemSample/memorySharedBytes.md, src/data-dictionary/events/SystemSample/memorySlabBytes.md
Adding infra-agent new memory metrics released in last 1.18.1 version https://github.com/newrelic/infrastructure-agent/releases/tag/1.18.1
=> infra-agent: new memory metrics for linux hosts

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action.mdx, src/content/docs/telemetry-data-platform/custom-data/custom-events/report-browser-monitoring-custom-events-attributes.mdx
Closes #2661.
With the recent release of the Browser agent, the PageAction event limit has been increased to 120.
=> Updated PageAction limit to 120

src/content/docs/synthetics/synthetic-monitoring/getting-started/types-synthetic-monitors.mdx
This was requested by the Synthetics PMM. It adds the two new monitors to the list of monitors in our docs.
=> Add broken links and certificate monitors to table

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Adjusted link so the link for Infra will take you to the fedramp setting in Infra's config page.
=> Fixed link to fedramp settings for Infrastructure (under Log API)

src/content/docs/integrations/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx, src/content/docs/integrations/kubernetes-integration/installation/install-fargate-integration.mdx, src/content/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx, src/nav/integrations.yml
Here are the changes to check for this re-publishing of the EKS Fargate docs:
* In the left navigation pane, you should see an entry for EKS Fargate. You can check this by loading this page: /docs/integrations/kubernetes-integration/installation/install-fargate-integration
* In the compatibility doc, you should see "or Fargate" in the main table: /docs/integrations/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements/
* In the installation overview, you should see a new collapser (2nd one) for EKS Fargate with a link to the new Fargate page: /docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure/
* A new beta doc for EKS Fargate: /docs/integrations/kubernetes-integration/installation/install-fargate-integration/ …
=> Re-publish the EKS Fargate beta docs

src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-architecture-recipes.mdx
This is another test of transferring branches from the private repo to the public repo. This image title fix is minor, but still a valid change that we should review and publish.
=> Inserted more meaningful OpenTelemetry image title as a test of the private repo.

src/content/docs/integrations/infrastructure-integrations/get-started/introduction-infrastructure-integrations.mdx, src/data/taxonomy-redirects.json, src/nav/full-stack-observability.yml
The Fargate team noticed several broken links. Here are the fixes:
* In `full-stack-observability.yml`, under **Infrastructure monitoring > Get started**, the link for **Get Integrations** was failing: `/docs/infrastructure/new-relic-infrastructure/getting-started/infrastructure-integrations`. Now it is this to get around a redirect issue: `/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring`.
* `/docs/integrations/infrastructure-integrations/get-started/introduction-infrastructure-integrations.mdx` had this bad link in the table under **On-host integrations**: `https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/`. To get around this failing redirect, I changed it to this: …
=> Made fixes for broken links found by the Fargate team.

scripts/actions/deserialize-html.js
This is to stop it converting single line strings to use `>-` when over 80 characters long
=> chore: add infinite lineWidth to yaml deserializer

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx, src/content/docs/apis/rest-api-v2/api-explorer-v2/introduction-new-relics-rest-api-explorer.mdx, src/content/docs/apis/rest-api-v2/api-explorer-v2/use-api-explorer.mdx
Changes around recent change where v1 users who aren't Owners or Admins no longer have access to REST API key.
=> Some slight changes around REST API admin

src/content/docs/telemetry-data-platform/understand-data/new-relic-data-types.mdx
Line 731 = * To increase the availability of your event data for querying/charting, you can [turn events into metrics](/docs/accounts/accounts/data-management).
The link: https://docs.newrelic.com/docs/accounts/accounts/data-management/
Results in 404
Propose changes= No sure where it should send the customer, as like which link it should sent to.
=> Line 731  404 error

src/content/docs/accounts/install-new-relic/partner-based-installation/heroku-install-new-relic-add.mdx
Adding users to the Heroku add-on causes New Relic users to automatically be created. Removing users from the Heroku app does not automatically remove the New Relic users. This can cause undesirable behavior.
Update the documentation to advise Heroku admins to manually remove the New Relic user after removing the user from the Heroku add-on.
No
=> Add caution about removing users from the Heroku add-on

src/content/docs/style-guide/quick-reference/capitalization.mdx, src/content/docs/style-guide/writing-guidelines/screenshots-images.mdx
Added our sentence case policy for diagrams in both the "Capitalization" and "Screenshots and images" docs.
=> Add sentence case policy for diagrams

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-700.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-701.mdx
This commit adds the release notes for Java agent release 7.0.1 as well as a known issue on version 7.0.0.
No.
=> Java agent Release 7.0.1

src/data/taxonomy-redirects.json, src/nav/integrations.yml
Steps to reproduce:
1. Go to `https://docs.newrelic.com/docs/integrations/`
2. Scroll down and click on **Kubernetes plugin for Logs** and note the 404
Discussion:
The fix I chose for this, based on feedback from a colleague, was to simply remove the "path" line from `integrations.yml` for `Kubernetes plugin for Logs`. Now, if you go to  `https://docs.newrelic.com/docs/integrations/`, you should see the following if you scroll down the page, but `Kubernetes plugin for Logs` is no longer a link (just the child `Get Kubernetes log data`.
Kubernetes plugin for Logs
Get Kubernetes log data
=> Trying to fix 404 from link on integrations auto-generated page.

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-701.mdx
Release notes  page for Java agent 7.0.1 was missing the download link.
No
=> Add download link to Java agent 7.0.1 release notes

src/content/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration.mdx
Adding `db.maxconnections` metric.
This metric has been added and will be released in the next version of the integration, as soon as the this doc update is published
=> Updating postgresql-monitoring-integration

.github/workflows/check-translations-and-deserialize.yml, scripts/actions/__tests__/fetch-and-deserialize.test.js, scripts/actions/check-job-progress.js, scripts/actions/fetch-and-deserialize.js
* added logic to copy over images for translated docs. also added in
paths for skipping over already copied images, & ignoring directories
with no images.
Resolves: #2288
=> chore: copy over images for translated docs

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Add a note explaining that only the NREUM.info block needs update
Tweak error_beacon to errorBeacon to match property name
Provides a small note regarding which beacon props need updated for fedramp support.  Support has confirmed that the values in NREUM.info block override the default values in the nr loader script.
=> Update fedramp browser copy/paste instructions

src/content/docs/integrations/kubernetes-integration/installation/install-fargate-integration.mdx
We received feedback that the "(beta)" designation in the title made it look like the doc was in beta-not the feature. 
To fix this, I removed that from the heading and inserted a more explicit callout.
=> Removed "beta" from heading in EKS Fargate doc

src/content/docs/logs/log-management/log-api/introduction-log-api.mdx
Updated the placement of a warning about calling the logs API from within code, and added some more information as to why we recommend what we do
=> CHORE: Update introduction-log-api.mdx

src/content/docs/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
This PR updates our autogenerated config documentation. This updates the wording on `browser_monitoring.auto_instrument` config option to clarify the default value, also we updated links to use markdown instead of html.
I also added html comments to mark what sections are auto generated from the agent so it's easier to tell. (There used to be comments that showed the section was generated, but it seems like it went missing since the move to git for the docs site)
no
=> Update ruby agent configuration

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-health-monitoring-integration.mdx
* AWS Health events received are now published as NR1 events so that customers can create widget and alert conditions based on them. Previously, events were only available as inventory data (which cannot be queried). 
=> AWSHealth now publishes NR1 events

.github/workflows/fetch-swiftype-content.yml, .github/workflows/pr-triage.yml, .github/workflows/release.yml, .github/workflows/update-whats-new-ids.yml, .github/workflows/validate-pr.yml
* updated workflow & job names to better describe what is happening, and better indicate if a particular check can be ignored.
Resolves: #2613
=> chore: update workflow & job names

scripts/actions/utils/handlers.js
Updates to the frontmatter during translation were not being pulled into the frontmatter for localized files, this fixes that.
=> fix: update frontmatter after translation

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
Memory should be specified in units of GiB since memory modules contain multiples of 1024 bytes (powers of base 2).
- https://en.wikipedia.org/wiki/Gigabyte#:~:text=the%20capacity%20of%20modern%20computer%20random%20access%20memory%20devices%2C%20such%20as%20dimm%20modules%2C%20is%20always%20a%20multiple%20of%20a%20power%20of%201024
- https://en.wikipedia.org/wiki/Gigabyte#Base_2_(binary)
This aligns our Docker requirements with our Kubernetes requirements section which already correctly specifies memory in base 2 units using Kubernete's Mi or Gi.
Correct units on memory to match industry standards.
https://en.wikipedia.org/wiki/Byte#History_of_the_conflicting_definitions
=> Correct memory units from GB to GiB

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60403160.mdx
This PR adds release notes for Python Agent v6.4.3.160.
=> Add python agent release notes for v6.04.03.160.

src/content/docs/mobile-monitoring/mobile-monitoring-ui/network-pages/http-errors-network-failure-analysis.mdx
The UI elements still say "View in Insights", but this changes the doc to not otherwise refer to that EOL'ed product, and instead point to dashboards and the query builder.
=> Remove references to Insights in Mobile HTTP errors

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
Cleaned up some of the examples, adjusted the " Enable log forwarding using the infrastructure agent " section to be more accurate, added some additional clarifying lines to the configuration steps.
=> Various tweaks and update examples for log sources

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-baseline-alert-conditions.mdx
Not so much how, as where you go.
I pulled the UI path from out of the image caption. I think this redundancy is ok.
=> Added clarity about creating baseline conditions

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
As an engineer working in the platform, I was unsure what conditions needed to be met for a loss of signal violation to automatically close. Does the signal need to resume and maintain across the chosen expiration window? Does it immediately resume once it's detected?  I tested this with a synthetics monitor and the violation closed immediately once a new data point was detected. Hopefully this can help  our customers who have similar questions.
No! 😅
=> Clarify violation close for LoS violations

src/content/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing.mdx
Adding mention to the `traceparent` and `tracestate` headers introduced by agent version 1173.
=> Support for the w3c trace context headers

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Documents the minimal permissions required on the AWS Account / Role in order to use the AWS Metric Stream integration. 
* Feedback from support / field, customers willing to understand what's the impact if they cannot enable the broad "ReadyOnlyAccess" permission on the AWS role. 
=> Document min permissions for AWS metric streams

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
* All on-host integrations are now published and ready to be used on ARM64 architectures (e.g. Graviton 2 AWS hosts).
=> OHIs now available for arm64 architecture

src/content/docs/telemetry-data-platform/custom-data/custom-events/report-custom-event-data.mdx, src/content/docs/telemetry-data-platform/get-started/introduction-new-relic-data-ingest-apis-sdks.mdx, src/content/docs/using-new-relic/data/customize-data/collect-custom-attributes.mdx
Some quick work: 
Giving a couple more links to the 'Intro to custom data' doc. 
Reducing some redundant content that was in two places and pointing to 'custom data' doc. 
Giving more context for how one recommended path was going into the UI to get started with New Relic.
=> Some 'custom data' related edits

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx, src/content/docs/integrations/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs.mdx, src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
As part of the epic to install fluent-bit package as an infrastructure-agent dependency, the Amazon Linux 2 repository location is being changed.
=> Updated infrastructure-agent Amazon Linux 2 repository location

src/content/docs/logs/log-management/ui-data/find-unusual-logs-log-patterns.mdx
**TL;DR** : This PR tries to get attention regarding feature availability.
As a NewRelic consumer living in the EU region, many times I tried to use a feature that was not yet available in my region. It is not a big deal by itself, however I think this should be more obvious.
From my experience, users (including me) are not "reading" the doc. They are parsing it for keywords before focusing on a specific section. Using a `callout` can save some time and troubles.
=> Emphasis Log patterns note regarding EU region

src/content/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx
This link extended over three ¶s. Probably an issue in the migration script.
=> Fix malformed links

src/content/docs/integrations/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring.mdx
The updated link has the actual procedure for disconnecting AWS integration.
Closes #2896
=> Updated a link to a more appropriate location

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Moved the image before the code block so the image is visible.
=> Fixed broken image in NRQL syntax, clauses, and functions

src/content/docs/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx, src/content/docs/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-720.mdx
* Added configuration options for expected errors
* updated existing links from Ruby API to error collector config section
Update docs for Ruby Agent 7.2.0 release.
Adds configuration options for expected errors which are introduced in this release. Updates links to general information on expected errors - previously the Ruby link pointed to the API docs for expected errors.
Also did some clean up on deprecated options - removed duplicate "deprecate"s adjacent to each other.
No.
**NOTE:** Please do not merge until Ruby Agent 7.2.0 is released (which should be soon this week).
=> Ruby Agent 7.2.0 release

src/content/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations.mdx
- `MINION_VSE_PASSWORD` does not exist
- Corrected to `MINION_VSE_PASSPHRASE`
* What problems does this PR solve? Wrong env var was listed in docs.
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration/#docker-env-config
=> fix: MINION_VSE_PASSPHRASE

src/components/RootNavigation.js, src/pages/index.js
On our landing page, some parts of the text mentioned 360 integrations instead of 370.
=> Updating to 370 integrations

.github/workflows/update-whats-new-ids.yml
* this action currently does not trigger workflow push event. adding
`persist-credentials: false` should let it trigger the event, and
limiting the type to `opened` is to prevent the action from triggering
the workflow endlessly when a change is pushed.
Resolves: #2932
=> fix for stalled workflows

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
Fixing a typo
Fixing a typo in this:
> Use the inclusion and exclusion filters in CloudWatch Metric Stream is order to select which services / namespaces are being collected.
"is order" should be "in order".
Also changed "in CloudWatch Metric Stream" to "in the CloudWatch Metric Stream"
No
=> Fixing typo

src/content/docs/query-your-data/explore-query-data/dashboards/dashboards-api.mdx
Small fix in the limits of a widget. In this case the maximum column a widget can have.
=> Increase max layout column of a widget

scripts/actions/add-files-to-translation-queue.js, scripts/actions/check-for-outdated-translations.js, scripts/actions/utils/__tests__/github-api-helpers.test.js, scripts/actions/utils/github-api-helpers.js
Update `add-files-to-translation-queue.js` to handle paginated results from the Github API and abstract that logic.
=> Handle paginated results from the Github API

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
* Ubuntu 20 is supported for log-fwd in infra-agent since late 2020.
=> Ubuntu 20 is supported for log-fwd in infra-agent

src/content/docs/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
This is a clarification of the Java configuration document. This change should go out when we announce Java Flight Recorder real time profiling that is on-by-default on July 8, 2021.
=> Added changes based on new JFR "on-by-default."

.prettierrc.js, scripts/actions/__tests__/send-and-update-translation-queue.test.js, scripts/actions/send-and-update-translation-queue.js
This PR is for allowing the send translation workflow to handle files that are queued for translation, but dont exist due to being renamed or deleted in a separate edit. 
The way this is done is to ignore getting the content for those documents. This prevents them from being sent for translation, which also removes them from the queue, since only failed uploads are left on the queue.
Resolves: #2931
=> enable translation workflow to handle 'sending' documents that dont exist

src/content/docs/agents/java-agent/additional-installation/wildfly-installation-java.mdx
Closes #2994
There was a missing quotation mark at the end of a code block.
=> Added missing quotation mark

src/content/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format.mdx
Newer config format does not support `arguments` for CLI args.
=> fix: infra agent config args

src/content/docs/accounts/accounts-billing/account-setup/new-relic-license-key.mdx, src/content/docs/accounts/accounts/saml-single-sign/delete-sso-configuration.mdx, src/content/docs/apis/intro-apis/new-relic-api-keys.mdx, src/content/docs/telemetry-data-platform/ingest-apis/introduction-event-api.mdx
Noticed a couple bad mentions of 'Account settings' UI page, which isn't available for v2 users. So I fixed that. 
I'm out next week so if someone can merge this for me, apprciated.
=> Some removals of 'Account settings UI page' references

.github/workflows/get-slugs-to-translate.yml
A quick PR to add the GITHUB_TOKEN to the add-files-translation-queue job
=> fix: add github token to job

src/content/docs/logs/enable-log-management-new-relic/logs-context-net/net-configure-nlog.mdx
To coincide with our release of NewRelic.LogEnrichers.NLog 1.2.0 that adds support for pulling in data from different contexts, I updated the configuration section of the .NET NLog page to show how to enable the new contexts.  I also updated some of the wording in the examples.
No.
Resolves: newrelic/newrelic-logenricher-dotnet#106
=> chore: Updated .NET NLog config instructions

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-14-0.mdx
Please review these release notes for the 3.14.0 release for the go agent.
=> Release notes for Go Agent v3.14.0

src/templates/releaseNoteLandingPage.js
The release notes currently grab a portion of the markdown for a given note and render it as a string for a preview. The library we're using to stringify the elements concatenates list items with no space. This adds logic to render list items with periods and spaces 
Closes https://github.com/newrelic/docs-website/issues/2714
=> Use space between list items in release note preview

src/content/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api.mdx
Removing the single-paged use case to export dashboards as PDF. This is not valid anymore, and users should follow the same process regardless the amount of pages.
After the homogenization of dashboards, avoid user errors when exporting single-paged dashboards.
=> Remove export single-paged dashboards

src/content/docs/full-stack-observability/observe-everything/get-started/pixie-account-link.mdx, src/nav/full-stack-observability.yml
This adds a doc for Auto-telemetry with Pixie beta users to upgrade their accounts for use with the generally available version.
=> Pixie beta users doc

src/content/docs/agents/java-agent/features/real-time-profiling-java-using-jfr-metrics.mdx
JFR daemon Java compatibility specified a Java version without specifying the vendor.
This caused confusion as costumers tried to use another vendor's Java at a version higher than the specified but it wouldn't work.
The link was removed as it led the user to the same information in a different page.
No
=> chore: Update Java compatibility of the JFR daemon

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-users/usage-queries-alerts.mdx, src/content/docs/accounts/new-relic-account-usage/getting-started-usage/apm-host-based-subscription-usage.mdx, src/content/docs/accounts/new-relic-account-usage/getting-started-usage/insights-subscription-usage.mdx, src/content/docs/accounts/new-relic-account-usage/getting-started-usage/mobile-subscription-usage.mdx, src/content/docs/accounts/original-accounts-billing/original-product-based-pricing/switch-new-models.mdx, src/content/docs/agents/manage-apm-agents/configuration/enable-configurable-security-policies.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts.mdx, src/content/docs/apis/intro-apis/introduction-new-relic-apis.mdx, src/content/docs/apis/intro-apis/new-relic-api-keys.mdx, src/content/docs/apm/transactions/cross-application-traces/troubleshoot-cross-application-tracing.mdx, src/content/docs/integrations/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx, src/content/docs/integrations/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx, src/content/docs/licenses/license-information/general-usage-licenses/new-relic-data-usage-limits-policies.mdx, src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx, src/content/docs/telemetry-data-platform/custom-data/custom-events/data-requirements-limits-custom-event-data.mdx, src/content/docs/telemetry-data-platform/manage-data/view-system-limits.mdx, src/content/docs/telemetry-data-platform/understand-data/event-data/query-account-audit-logs-nrauditevent.mdx
Noticed there were a few remaining 'sub-account' refs, not sure how I missed em. Edited them away.
=> Removing 'sub-account' language

src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx, src/content/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits.mdx, src/content/docs/licenses/license-information/general-usage-licenses/new-relic-data-usage-limits-policies.mdx
I initially made these per-account rate limiting changes over a month ago on the private site. While I waited for signoff, the branch got stale. So, to speed up the migration, I just manually moved these over when I received SME confirmation that we can push these out.
Here's what to review:
DOC #1 (Trace API general requirements and limits)
* Migrated four of the limits entries from the table over to New Relic data usage limits and policies. As I understand it, the remaining rows were either already in the main limits doc or the rows were unrelated to limits.
* The table had two miscellaneous items unrelated to limits, so I moved the HTTPS requirement as just a a modifier in the first section about endpoints. I dropped the obfuscation comment because I couldn’t find a better spot, and …
=> Per-account trace rate limits

src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx, src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
[Synthetic monitor public minion IPs] was updated to /docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips
Old link pointed to /docs/synthetics/synthetic-public-minion-ips
=> Fixed link to list of Public IPs

src/content/docs/auto-telemetry-pixie/pixie-data-security-overview.mdx
Fix small heading typo in Pixie doc
=> Fix typo (`upate` s/be `update`) | Pixie security doc

src/components/DataDictionaryFilter.js, src/pages/attribute-dictionary.js
Replaces the filter for selecting a specific attribute with a text input to search for attributes by name. Just matches on any instance of the search string in the attribute name. It lower cases the search string and the attribute names when matching.
Adds ability to apply filters by typing `enter`.
Closes https://github.com/newrelic/docs-website/issues/626
https://user-images.githubusercontent.com/2952843/125660278-2a5aed92-3364-4001-802c-9507f4e3255a.mp4
=> Support searching by attribute name in data dictionary

src/content/docs/apis/nerdgraph/examples/golden-metrics-entities-nerdgraph-api-tutorial.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic.mdx, src/content/whats-new/2021/03/kubernetes-whats-new.md, src/i18n/content/jp/docs/new-relic-one/use-new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts.mdx, src/i18n/content/jp/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic.mdx
Update references to the entity-definitions repository after its graduation out of the newrelic-experimental org
This PR fixes outdated links to the newrelic-experimental organization for entity type definitions. You can see an example of outdated link on the [Find and explore entities section of the What is an entity in New Relic? page](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic/#find)
=> Update references to the entity-definitions repository

plugins/gatsby-source-nav/gatsby-node.js
When deciding which nav to show for a given page, the path is compared against the top level navs of the site. This was previously done in whatever order the query returned. This PR explicitly sorts the list so that we can always be sure which nav is used.
=> chore: sort top level nav list before comparison

package.json, yarn.lock
Bump theme to v2.5. 
https://github.com/newrelic/gatsby-theme-newrelic/releases/tag/v2.5.0
=> Bump theme to v2.5

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed.mdx
All conditions now have TTL's applied to them. It is no longer allowed to have a condition without a TTL. The default value for infrastructure conditions is 24 hours. 0 (disabled) is no longer allowed. If a user sends 0, we will replace it with 24.
The Infra UI is being updated this week. The enable/disable checkbox is being removed and the default value will be 24. The user must use the default or change it to a pre-defined value.
=> Updated Infra related time limits

src/content/docs/telemetry-data-platform/ingest-apis/report-metrics-metric-api.mdx
Small change, removing that timestamp must be in miliseconds and linking to that section for more info.
=> Clarifying Metric API timestamp units accepted

src/content/docs/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx
The configuration method `ignore_url_regexes` only prevents Transaction events reporting and not spans/traces. Related to:
* https://newrelic.atlassian.net/browse/GTSE-10084
Note: there is no engineering response in the above Jira as we discussed this in GTS pairing and determined this is how the configuration method is expected to work. Feel free to ping #ruby-agent or #gts-ruby for any questions!
Since new releases of the Ruby agent will overwrite any edits to the docs site [configuration page](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/#rules-ignore_url_regexes), I submitted a Github issue to the Ruby team to specify this in the configuration doc:
https://github.com/newrelic/newrelic-ruby-agent/issues/729 …
=> Clarify limits of ignoring through configuration

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
This is an important tip for customers who really need a value of 0 to make their NRQL condition work.
=> Update NRQL query order-of-operations section

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx, src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx, src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
Assorted build up of edits to these docs, per liaison work. Edits include: 
Clarifying that setting time zone in identity provider app is important for AUM. 
Clarifying that once they toggle AUM for an auth domain, they can't toggle it off. 
Clarifying that when they use SSO, their users don't get emails about password/login from NR; that's through their identity provider.
=> A few SSO and AUM edits

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
Warning for "Network drives are not supported by Fluent Bit’s tail plugin"
References:
[File tailing doesn't work on NFS-mounted files](https://github.com/fluent/fluent-bit/issues/3111)
Zendesk TT:https://newrelic.zendesk.com/agent/tickets/461546
Salck channel for reference where documentation updates was required: https://newrelic.slack.com/archives/C026H6RUVPZ/p1626863912011100
in your commit messages and …
=> Add some where in this page an warning message.

.github/workflows/check-translations-and-deserialize.yml, scripts/actions/check-job-progress.js, scripts/actions/remove-completed-batch.js, scripts/actions/translation_workflow/models/typedefs.js
- Closes #3078 
- Changes scripts called in .`check-translations-and-deserialize.yml` to replace calls to old database functions with new functions in `scripts/actions/translation_workflow/database.js`
- At the end of the workflow, updates job statuses to "IN_REVIEW"
=> Update completed translation workflow to use new database calls

src/content/docs/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/agents/ruby-agent/getting-started/migration-7x-guide.mdx, src/content/docs/agents/ruby-agent/troubleshooting/systemstackerror-stack-level-too-deep.mdx
This PR updates the stack level too deep troubleshooting page for the ruby agent. What was there before was pretty outdated, and referenced ruby versions we no longer support. I've updated the page with instructions on how to troubleshoot the stack level too deep errors in the agent for 7.0+. I've also updated our migration guide for ruby agent version 7.0 to link to the troubleshooting guide, and updated instructions on reporting conflicts on github.
Also, this pr closes https://github.com/newrelic/newrelic-ruby-agent/issues/723 by removing the entity_guid config option from documentation.
No
in your commit messages and pull …
=> Stack level too deep update

src/content/docs/agents/ruby-agent/api-guides/guide-using-ruby-agent-api.mdx
Corrects 'cross-account' to 'cross-application'
API method `add_request_headers()` add 'cross-application' headers to external requests - here is the documentation for this method:
https://rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent/Transaction/ExternalRequestSegment#add_request_headers-instance_method
=> Corrects 'cross-account' to 'cross-application'

src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts.mdx
Howdy Docs team - updating the example here for the Host Not Reporting condition type to include the optional no_trigger_on toggle. This enables the setting 'Don't trigger alerts for hosts that perform a clean shutdown'
* The current Rest API for Infra Conditions docs don't reflect an important setting that is available in the UI, and via API. The API part is (until now) undocumented.
=> Updating HNR to include the no_trigger_on toggle

src/content/docs/style-guide/processes-procedures/include-a-doc-in-multiple-menus.mdx
Went looking for this doc today and realized it would help to mention this shorthand.
=> Use word "dummy doc" in referring to multiple menus

src/content/docs/agents/python-agent/installation/standard-python-agent-install.mdx
This was a request from a customer who said he was unable to find the Python Lambda doc from the standard Python installation doc. He ended up over in our blogs for a solution. So, I inserted a link to AWS Lambda in the standard installation doc.
=> Added link to AWS Lambda per customer comment.

src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/alert-infrastructure-processes.mdx
Process Running (PR) alert conditions are being migrated to use NRQL (Willamette pipeline). This move will mean that they can no longer tell if a process failed to start when a host is spun up. I have tried to remove all references to that sort of behavior, since PR conditions will change to being more "Process NO LONGER running."
I feel like these changes will not need to be applied until we move the PR condition types over to Willamette (happening soon, but has not happened yet). On the other hand, these don't feel like breaking changes to the document, so could be published immediately without any impact (I think).
Please do send me a DM in Slack (@shenry) if you have any questions about these changes.
* Add any context that will help us review your …
=> Small changes to doc

src/content/docs/logs/log-management/log-api/introduction-log-api.mdx
Heard from CSM today that our logs weren't showing up because our timestamps were older than 48 hours. Not sure this would have helped, but felt it should be called out.
=> Added callout for timestamp logic

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
Updated the .Net Agent's provided AWS Lambda async example with better guidelines inline with new support.
=> Update .Net Lambda async doc example

src/content/docs/integrations/kubernetes-integration/installation/install-fargate-integration.mdx, src/content/docs/style-guide/processes-procedures/use-content-types-text-formats.mdx, src/content/docs/style-guide/quick-reference/callouts.mdx
After a meeting about how to flag beta docs, we settled on having a custom callout. 
Reviewer, please look at the following:
* Changes in the style guide topic about callouts that now explains how to create a custom callout.
* Link from the data types doc in the style guide that explains we no longer use watermarks for beta docs.
* An update to the EKS Fargate beta callout so it now follows the new pattern.
=> Explanation of how to create custom docs callouts

src/nav/full-stack-observability.yml, src/nav/new-relic-one.yml
Just a few fixes, including: 
Putting correct URLs in for some docs in 'Instrument everything' category
Changing some long nav file docs titles from long to short titles in New Relic One nav file
=> Assorted taxonomy/nav file fixes

src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
This doc includes a lot of CTAs and noise. Reducing some of the noise to help highlight the key flow for new users.
=> Reduce link fatigue in Intro to APM doc

src/content/docs/integrations/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx
This is a PR for GitHub issue @3245. The old link was redirecting to a different page and the anchor was ignored.
Closes #3245
It appears the #3246 is a duplicate and might be able to be closed.
=> Corrected the link to validate injection of metadata.

src/content/docs/new-relic-solutions/new-relic-solutions/measure-devops-success/set-proactive-alerting-understand-respond-performance-issues.mdx
It turns out we had a doc that still references an Insights routine for setting up alerts. I removed this based on SME input, but we'll need to update the query examples as soon as the new table is available. I created DOC-7187 to track that effort.
=> Remove link to blog about Insights and alerts

src/content/docs/agents/ruby-agent/troubleshooting/incompatible-gems.mdx
This PR resolves the Ruby Agent issue [Add makara to list of incompatible gems #507](https://github.com/newrelic/newrelic-ruby-agent/issues/507)
* Adds detail about the problem/solution based on the [Zendesk Ticket 325320](https://newrelic.zendesk.com/agent/tickets/325320)
* Updates some grammar and style inconsistencies on the page
No
=> Add makara to Ruby Agent's Incompatible Gems

src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx
In private dashboards, everything s hidden for the rest of users, except the metadata. I've added a little point clarifying that. 
See UIWRITE-1261 for more details.
=> Added metadata exception in dashboards permissions.

src/content/docs/synthetics/synthetic-monitoring/getting-started/security-synthetic-monitoring.mdx
This PR simply fix what seems to be a very small typo from _Tt does not ..._ to _It does not ..._ on the _Security for synthetic monitoring_ page.
=> fix: some small typo

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-0-0.mdx
adds release notes for Node.js agent release v8.0.0.
=> chore: adds release notes for Node.js agent release v8.0.0.

src/content/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx, src/content/docs/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx
For Node agent version 8.0.0 release, this PR updates the Upgrade Node Agent and Node Agent compatibility docs.
=> chore: update node agent compaitility and upgrade notes for Node agent v8 release.

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/outlier-detection-nrql-alert.mdx
Removing the facet limit ", and can only facet on one attribute. Queries that facet on more than one attribute won't work." Multiple facets are supported
* Existing Doc is out of date
* Got a note from Product Manager that multiple facets are supported for outlier conditions
No.
=> Remove facet Limit part of NRQL query rules and limits

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql.mdx
* Feedback from customers: updating the note about AWS not being supported. There are two AWS integrations: polling (not supported) and metric streams (supported). 
=> Explaining AWS metric stream is supported

src/nav/telemetry-data-platform.yml
=> Sort order: Metric API first in list of MELT APIs

src/content/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
Remove a tip callout referencing a 2017+ version of Kafka
=> Remove very old compatibility callout

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-examples.mdx
closes #3211
We already have a doc on using NerdGraph with notification channels, so all we need to do is link to it.
=> Added links to other alerts NerdGraph docs

.github/workflows/issue-triage.yml, .github/workflows/pr-triage.yml
We recently updated our docs board column names, which broke the auto-triaging. 
This PR updates the triage actions with the new column names.
=> Update auto-triage with new column name

src/nav/alerts-and-applied-intelligence.yml
The New Relic Alerts nav category was missing a path in the nav yaml.
I'm hoping this fixes it.
=> There was a missing nav category path

src/content/docs/accounts/accounts-billing/general-account-settings/manage-data.mdx, src/content/docs/telemetry-data-platform/manage-data/manage-your-data.mdx, src/nav/accounts.yml
We were having a problem with the 'Manage data' doc ref addition in the accounts doc section; it was essentially stealing the location from the real location, so that when you clicked it, instead of going to the place it actually was located (in 'Manage your data' docs section) it was remaining in the accounts docs section, and that wasn't good at all. This is due to some known issues in how the sidebar/nav files work and we may fix that but in meantime I fixed this with a more old-fashioned dummy doc fix. 
Please merge this if it looks fine.
=> Adding dummy doc to fix sidebar issue

src/content/docs/apis/nerdgraph/examples/nerdgraph-relationships-api-tutorial.mdx
We're in the process of deprecating the `relationships` API in favour of the new `relatedEntities` one. For this reason, I've updated the docs to remove the reference to the soon-to-be-deprecated `relationships` API. 
=> Update relationship API tutorial section with the new API 

src/content/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management.mdx
Using a domain for examples is tremendously dangerous. `example.com` was created specifically for this purpose and is routable across the internet, so we should use it.
=> Change from test.com to example.com

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/fluentd-plugin-log-forwarding.mdx
This PR adds more information about how to configure fluentd when forwarding logs to NR and also show the customer what is the default buffer configuration when using the newrelic fluentd output plugin.
No
=> Add buffer tune-up section to fluentd docs

src/content/docs/logs/log-management/log-api/introduction-log-api.mdx
in message field json parsing example, key-value data between message and parsed json did not match: login-service --> my-service.
=> fixed typo in message json parsing example

src/content/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations.mdx
- line breaks for `docker run` commands needs `\`
- K8s commands don't typically use line breaks
=> fix: formatting of commands

src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1190.mdx
Infrastructure agent release notes update to add explanation on "recommends" dependencies.
=> infra agent 1.19.0 release notes: recommends explanation

src/nav/attribute-dictionary.yml
@zuluecho9's request.
In general, we refer to the "attribute dictionary" as the "data dictionary". I've updated the link text to reflect that. Please note: I have not updated the URL.
=> Change attribute dictionary link text to data dictionary

src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-620.mdx
This PR reverts #3353, which reverted an accidental early publish. 
Tl;DR: This publishes the 6.2.0 android agent release. 
Reverts newrelic/docs-website#3353
=> Release Updates for Android Agent 6.2.0 release

scripts/actions/__tests__/send-and-update-translation-queue.test.js, scripts/actions/send-and-update-translation-queue.js
These changes are some minor adjustments which we identified after we executed the send workflow. 
In particular:
* remove usage of `ERRORED` status. for this first run, we saw many files encounter this status due to failed uploads that were retryable. its likely we will encounter this scenario again, so rather than manually resetting state to PENDING, we would rather it just stay that way. in the future, we can figure out how to better incorporate the ERRORED state.
* upload files serially. we are hitting an api limit doing concurrent file uploads. the easiest path forward for now is to just upload them serially. this does decrease performance, but that is something we have plenty to give, especially if it reduces manual toil.
* provide the translation.slug if a file fails to upload just …
=> minor fixes for translation

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx, src/content/docs/telemetry-data-platform/manage-data/query-limits.mdx
Links to information on how to view your limits from the NRQL rate limits page.
Updates the callout in the Query system limits page to reflect that resource metrics now also include API query rate limits.
=> Add more API rate limiting details

src/content/docs/agents/ruby-agent/installation/install-new-relic-ruby-agent.mdx
In order to use Infinite Tracing with Sinatra apps (that are not also using Rails) the customer would need to manually call the New Relic gem AND the Infinite Tracing gem, or use `Bundler.require`.
The wording in my edit may be a little clunky now and may need rephrasing. The basics are, for customers with Sinatra apps:
* For Infinite Tracing, they  _must_ either call `Bundler.require` OR `require 'newrelic_rpm'` and `require 'newrelic/infinite_tracing'`
* If Infinite Tracing is not configured and the agent is greater than/equal to v6.11 (released June 2020), then including `require 'newrelic/infinite_tracing'` will do nothing so it won't hurt to include it even if the customer has no intention to use ∞T
* If the customer attempts to add `require 'newrelic/infinite_tracing'` with an agent …
=> Add Infinite Tracing gem requirement for Sinatra

src/content/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-service-fabric-monitoring-integration.mdx
* Azure communicated the [service is no longer available](https://azure.microsoft.com/en-us/updates/azure-service-fabric-mesh-preview-retirement/).
* We had disabled the integration and we'll proceed to remove this documentation by end of the quarter.  
=> Integration disabled given Azure has retired the service

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/customize-your-webhook-payload.mdx
This fixes a small typo within the Microsoft Teams Webhook example, on the "Acknowledge incident" button. The Webhook variable is correct, but the button label has a typo.,
No.
=> Fix typo on Microsoft Team Webhook example

plugins/gatsby-plugin-generate-doc-json/utils/handlers.js
Adds handler to local plugin that outputs JSON for each .mdx file in `src/content/docs` that includes html in the `body` field. The handler converts Video component to html `<iframe>`.
https://docswebsitedevelop-clangfixvideoembeddocjson.gtsb.io/docs/new-relic-one/use-new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts.json
Closes https://github.com/newrelic/docs-website/issues/3376
=> Add handler to convert Video component to html that's included in json output

package.json
Reboot script to easily clean out the cache when running into problems with local builds.
=> Added a reboot script

gatsby-config.js, src/content/whats-new/2020/07/overall-new-relic-one-experience-updates.md, src/content/whats-new/2020/09/new-relic-one-has-dark-mode.md, src/content/whats-new/2020/12/recap-top-10-new-observability-features-you-need-know.md, src/pages/whats-new.js
This PR contains small updates to change `<video>` elements to `<iframe>` in whats new posts. Disables swiftype explicitly for whats new landing because it was somehow showing in NR1 Help XP and really shouldn't show in search. 
Lastly, triggers cache clean to fix pr validation failures.
=> Clean cache, update video elems to iframe, disable swiftype for whats new landing

src/content/docs/integrations/kubernetes-integration/troubleshooting/get-logs-version.mdx
This PR addresses the request in Issue 3183
I added this section: http://localhost:8000/docs/integrations/kubernetes-integration/troubleshooting/get-logs-version/#verbose-helm
Question: Do we need steps like 5-9 from the previous section on verbose logs using a manifest file?
=> Added verbose logs instructions for helm installs

src/content/docs/agents/net-agent/troubleshooting/profiler-conflicts.mdx
Adds to documentation an issue I ran into trying to setup a New Relic agent on Windows. There was already an environment variable set from an old installation of JetBrains dotCover and it was preventing the New Relic agent from working -- this is its GUID.
=> adds GUID for JetBrains' dotCover profiler

plugins/gatsby-plugin-generate-doc-json/utils/handlers.js
Updates the inline style on the wrapper div for iframe to set same max-width as the NR1 Help XP nerdlet sets on many (but not all elements).
Will submit PR to add style rule in the nerdlet so we can eventually remove this inline style
- Related to https://github.com/newrelic/docs-website/pull/3378
- https://source.datanerd.us/nr1-dev-experience/nr1-help-xp/pull/123
=> Update video embeds to match width of other elements

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/violation-event-attributes.mdx
We'll be changing the nomenclature, and this is already reflected in our event types' names. In order to proactively head off confusion and prepare users for the coming change, I inserted this little informational tidbit the first time we refer to the event by name.
=> Preparing users for the possibly jarring nomenclature change

src/content/docs/agents/net-agent/configuration/net-agent-configuration.mdx
Call out .NET Agent versions that support expected errors configuration settings.
=> Call out .NET Agent versions that support expected errors configuration settings.

src/content/docs/agents/python-agent/python-agent-api/recordexception-python-agent-api.mdx
Just because a function is deprecated doesn't mean the documentation isn't still useful to those who
haven't updated their dependencies yet.
See #3467
=> Reintroduce docs for deprecated record_exception

src/content/docs/logs/log-management/log-api/introduction-log-api.mdx
This PR just update the log api documentation to indicate a new query parameter that the customer could use to authentication (this means, send their Api-Key in a query parameter)
No
=> Logging 5518 add api key query parameters log api

src/content/docs/agents/net-agent/installation/install-net-agent-linux.mdx
Update .NET agent documentation to remove un-needed warning about BOM.
Resolves: https://github.com/newrelic/docs-website/issues/3472
=> Update outdated .net documentation

src/content/docs/logs/log-management/ui-data/drop-data-drop-filter-rules.mdx
https://newrelic.atlassian.net/browse/LOGGING-5959
Some smart person discovered that we had a copy/paste error in our docs for drop filters, and had the incorrect permission listed.
=> LOGGING-5959: Fix permissions for drop filter rules

src/content/docs/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx
Updates the Java Kafka documentation to update an example code that used deprecated methods.
Also adds new parameters that can be used for the instrumentation.
No
=> chore: Updating Java's Kafka documentation

src/content/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration.mdx
The `renamed_commands` integration argument has been merged and was part of [v1.7.0](https://github.com/newrelic/nri-redis/releases/tag/v1.7.0).
The release is 10 days old (Aug 4th 2021), I'm unsure what the protocol is for feature addition (whether to put a `>=v1.7.0` annotation in the documentation.
Closes https://github.com/newrelic/nri-redis/issues/116
=> Document `renamed_commands` integration argument

src/content/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview.mdx, src/content/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration.mdx
Guided install no longer supports the JMX integration. I've removed mention of them.
closes #3487 and closes #3492 
I've also removed the Support APM agents section. Until we support more than one APM agent, this section doesn't really make sense.
=> Guided install updates.

src/content/docs/integrations/host-integrations/installation/container-auto-discovery-host-integrations.mdx
Usually we will have ${discovery.private.ip} and only if public ip attached to container we could use ${discovery.ip}.
* Update documentation
=> Infrastructure agent - Update docker discovery snippet

.github/ISSUE_TEMPLATE/content-issue.md, .github/ISSUE_TEMPLATE/site-bug-report.md, .github/ISSUE_TEMPLATE/site-enhancement.md, .github/pull_request_template.md
Remove mentions of Relic Recharge week from templates.
=> Remove "Relic Recharge" from PR/issue templates

src/content/docs/agents/net-agent/getting-started/8x-to-9x-agent-migration-guide.mdx, src/nav/full-stack-observability.yml
This is the migration guide mentioned in https://newrelic.atlassian.net/browse/DOC-7023
The draft in GDocs is here: https://docs.google.com/document/d/1BCCgm_OAtt-1Eea-_o-Nb7mhJBuXYoOSsSim_HhMlog/edit#
I am not sure if I got the table formatting correct.  I copied the syntax from an existing .NET agent document, but the Markdown preview in VSCode doesn't look like what I'm going for.  If there's a better/more standard way to format this kind of information for our users, let me know.  (Also, if you know of a tool which can show me what these .mdx files look like when rendered in the docs site, that would also be great.)
=> .NET Agent 8.x to 9.x migration guide

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9180302.mdx
This includes the release notes for PHP agent `9.18.0`. The release is targeted for `8/18/21`.
=> PHP 9.18.0 release notes

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration.mdx
The Lambda team confirmed this link shouldn't be there and needs to be removed. Since I was at it, I fixed other links as well.
Originally reported in #3533.
=> Removed link to Lambda@Edge

src/content/docs/browser/single-page-app-monitoring/troubleshooting/missing-route-changes-spa-agent.mdx
As reported in #documentation, the doc was a little outdated. The Browser team has confirmed this is still on the works so I'm tweaking the dates since the rest is still relevant.
=> Updated dates to 2021

src/pages/index.js
Now that the event has started, we don't need the banner anymore.
=> Remove banner from landing page

gatsby-config.js
Adds config option for gatsby cloud plugin to change referrer-policy from `same-origin` to `strict-origin`.
Partially addresses https://github.com/newrelic/gatsby-theme-newrelic/issues/437
=> Change referrer policy to expose referrer for external link clicks

src/content/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial.mdx
Tested adding tags to APM agent through UI and NerdGraph, both did not take effect until I restarted my service and then only applied to new, incoming data.
I did check with Browser support team, this is not needed for Browser: https://newrelic.slack.com/archives/C7GUYJZ5E/p1629406376045100
Infra team did not get back to me so only including APM for now: https://newrelic.slack.com/archives/C7HGFBZMH/p1629406484141500
=> Add instruction to restart APM services after making changes to tags

src/content/docs/apm/new-relic-apm/apdex/change-your-apdex-settings.mdx
This is a PR to clarify that Apdex threshold settings are only visible when an app is actively reporting data.
Closes issue #3458.
=> Clarified when Apdex settings are visible

src/content/docs/auto-telemetry-pixie/get-started-auto-telemetry-pixie.mdx
Closes #3462
Rather than duplicating the content in this doc, I thought it best to link to the Pixie technical requirements doc.
=> Added link to the Pixie requirements doc

src/content/docs/agents/ruby-agent/getting-started/migration-8x-guide.mdx, src/nav/full-stack-observability.yml
This PR adds a migration guide for the ruby agent next major release detailing the changes present in 8.0. 
no
=> Add ruby agent 8 migration guide

src/content/docs/new-relic-one/use-new-relic-one/workloads/use-workloads.mdx
It was using the wrong ID for the section it was linking to. I updated the URL to use the correct ID for the collapser.
=> Fixed a broken URL

src/content/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
One of our solutions consultants called out that it stated we only support v1 and v2 of connect.  We also started supporting the connect router in this PR: https://github.com/newrelic/node-newrelic/pull/847. Which will go out shortly(possibly as 8.2.0) of the Node.js agent.
=> fix: removed versions and stating we do not support connect routing

src/content/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
We noted that there's not really a Pixie mention in the Kubernetes integration install doc. This adds a little info and link.
=> Added a link to the Pixie docs from the main install page.

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/configure-serverless-monitoring-aws-lambda.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-aws-lambda-monitoring.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-example.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/set-up-cloudwatch-logs.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda.mdx, src/nav/full-stack-observability.yml
Loosely related to DOC-7184, where I'm investigating our 'nav and sidebar' tech writer how-to content. I fixed the Lambda category; was pretty messy, with typo of 'path' in nav file, a landing page `index` file that should have been a doc, clarifying doc titles and improving intros, and a few more things. Should work okay now. 
For review, just click around that Lambda category and make sure it seems okay structurally.
=> Fixing Lambda category 

src/content/docs/logs/enable-log-management-new-relic/configure-logs-context/c-sdk-configure-logs-context.mdx, src/content/docs/logs/enable-log-management-new-relic/configure-logs-context/configure-logs-context-apm-agents.mdx, src/nav/full-stack-observability.yml
C SDK was never documented for logs in context. This adds a new doc in the streamlined LiC taxonomy, which will also include the other APM agents.
=> LIC for C SDK

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-6081164.mdx
This PR adds release notes for Python Agent v6.8.1.164.
=> Add Python agent release notes v6.8.1.164

src/data-dictionary/events/PageViewTiming/PageViewTiming.event-definition.md, src/data-dictionary/events/PageViewTiming/pageHide.md
Based on issue https://github.com/newrelic/docs-website/issues/3062, added pageHide attribute and improved PageViewTiming description. @urbiz-nr you were assigned via random assignment so just a heads up: I couldn't get the new attribute to show up in my local build but I know with data dictionary there are cache issues, but maybe the gatsby preview build will show it.
=> Adding to PageViewTiming event in data dictionary

.github/auto_assign.yml
I misspelled my own username in the action. This fixes it!
=> Fix usernames in auto-assign reviewer action

src/content/docs/integrations/infrastructure-integrations/get-started/introduction-infrastructure-integrations.mdx, src/nav/accounts.yml, src/nav/full-stack-observability.yml, src/nav/integrations.yml
We had an issue where, if a category URL (like /docs/browser) associated with an index mdx file (landing page) was being used in multiple places in the same nav file (as this one was in FSO category), the 'See all docs' on the landing page would get confused and load the wrong category (e.g., use a different part of the nav file where that URL was located). 
I am going to file a deven request, after talking to @roadlittledawn, about being able to set/override the primary/main category of nav to use for one-off cases like this, but in mean time I did a fix that got rid of the duplicated URLs in the nav file and replaced them with table of contents URLs (e.g., /docs/browser/table-of-contents).
=> Fixing some table-of-contents views

src/content/docs/apis/nerdgraph/examples/nerdgraph-relationships-api-tutorial.mdx, src/content/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic.mdx
See DOC-7191 for details. Synopsis of changes: 
* Added links to the github repo where our entity definitions live and explained what info is there.
* Made some general improvements, to help with flow of doc (links to different section and such), and to improve description of what an entity is to reflect current functionality.
=> Updating 'entity' doc with TTL & general improvements - DOC-7191

src/nav/full-stack-observability.yml
Does what it says on the tin.
Of note, we previously had documentation for this stuff but it was [recently removed](https://github.com/newrelic/docs-website/pull/3670).
=> Add missing path to create index page for "Observe Everything"

src/nav/full-stack-observability.yml
Someone changed something in folders so the category URL was no longer working. So this will remove path and make that category header not clickable and just an expander/collapser. Which is okay for now, better than the broken category link. We say now in style guide that it's acceptable to have a nonclickable category for categories that are just assemblies of docs that "live" in other locations. 
Also fixed a bad mobile-monitoring URL.
=> Fixing bad category URL

src/nav/new-relic-solutions.yml
- Noticed an  extra link while working on DOC-7092.
- Also renaming the left nav to Solutions and best practices to match what's in there.
Tried locally, works ok.
=> Solutions - remove link and update nav name

src/content/docs/accounts/accounts/automated-user-management/tutorial-manage-users-groups-scim.mdx
In the SCIM documentation for the section describing how to create SCIM Groups, the callout incorrectly referred to the "user ID" where it should be "group ID".
=> Fix Typo In SCIM Documentation

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
AWS now supports a Python 3.9 runtime for Lambda. The New Relic Python agent also supports it, so we've added Python 3.9 Lambda layers, and added 3.9 support to our serverless-newrelic-lambda-layers plugin for the Serverless framework.
=> Adding Python. 3.9 support to requirements

src/content/docs/infrastructure/install-infrastructure-agent/macos-installation/install-infrastructure-monitoring-agent-macos.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
- Fixed typo for installing the `newrelic-infra-agent` in macOS
- Removed nodejs v10 support for AWS Lambda
=> Fixed typo & remove unsupported NodeJS version

src/content/docs/integrations/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx
Examples include Prometheus standalone and Prometheus on Kubernetes using a specific Helm chart. Also brings out a caveat of other helm charts
=> Add allow and deny list examples for remote write

src/content/docs/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-15-0.mdx
This is new release notes, and also an additional section in the list of integrations for the agent.
=> Release notes for Go Agent v3.15.0

src/content/docs/integrations/host-integrations/host-integrations-list/varnish-cache-monitoring-integration.mdx
Redesigning the VARNISH integration configuration section.
Add a table with the config options
Add example configurations
=> chore: adjusting varnish config and content

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/alert-custom-violation-descriptions.mdx, src/content/docs/browser/new-relic-browser/browser-agent-spa-api/setcustomattribute-browser-agent-api.mdx, src/content/docs/integrations/prometheus-integrations/install-configure-remote-write/prometheus-remote-write-integration.mdx, src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx, src/content/docs/new-relic-partnerships/partner-integration-guide/getting-started/support-resources-new-relic-partners.mdx, src/content/docs/security/index.mdx, src/content/docs/style-guide/article-templates/basic-doc-template.mdx, src/content/docs/style-guide/article-templates/create-release-notes.mdx, src/content/docs/style-guide/article-templates/whats-new-style-guidelines.mdx, src/content/docs/style-guide/processes-procedures/docs-site-edit-checklist.mdx, src/content/docs/style-guide/processes-procedures/embed-videos.mdx, src/content/docs/style-guide/processes-procedures/use-content-types-text-formats.mdx, src/content/docs/style-guide/quick-reference/callouts.mdx, src/content/docs/style-guide/quick-reference/tables.mdx, src/content/docs/style-guide/quick-reference/usage-dictionary.mdx, src/content/docs/style-guide/writing-guidelines/create-edit-content.mdx, src/content/docs/style-guide/writing-guidelines/docs-translation.mdx, src/content/docs/style-guide/writing-guidelines/five-questions-help-write-docs.mdx, src/content/docs/style-guide/writing-guidelines/hyperlinks.mdx, src/content/docs/style-guide/writing-guidelines/levels-headings.mdx, src/content/docs/style-guide/writing-guidelines/screenshots-images.mdx, src/content/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal.mdx
* Improve intro paragraph by removing redundant sentences
* Clarify how to refer to the docs site itself, and what the best linking styles are
=> fix(style guide): Clarify how to refer to the docs site itself

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/new-relic-one-user-model-understand-user-structure.mdx
Clarifying the two different 'log'-related entries in the user type capabalities list
=> Small edit to user type capabilities

src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx
Removes `<br/>` elements from table in one file that was causing error when trying to serialize the HTML to upload to translation vendor. I believe we want to follow markdown syntax inside of `<td>` elements as much as possible.
I tested locally and serialization seemed to work with these changes.
Related to [this recent failure](https://github.com/newrelic/docs-website/runs/3479407196?check_suite_focus=true#step:6:66).
=> Remove break elements to prevent serialization error

src/content/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration.mdx
Redesigning the Kafka integration configuration section.
Add a table with the config options and separate the configuration by the 3 kind of instances that can be set in order to get the different samples
Add example configurations
Add more information with clarifications about different aspects of the integration that use to appear as tickets by GTS.
=> Kafka v4 config samples and improvements

src/content/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
Redesigning the RabbitMQ integration configuration section.
Add a table with the config options
Add example configurations
=> RabbitMQ adapt documentation to config V4

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-2-0.mdx, src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-3-0.mdx
* added release notes for Nodejs agent v8.2.0 and v8.3.0
=> chore: added release notes for Node Agent v8.2.0 and v8.3.0

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
As reported in #3875, the description of latest doesn't have a link.
Tried locally, works fine.
=> Added link to latest function

src/content/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
Small fix in Oracle DB doc that still had a reference to Mysql by mistake
=> fix typo in oracle integration doc

src/content/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui.mdx
Hello, Justin Schrader from the DT team here. We've released a new feature allowing uses to see OTEL span events & errors.
- docs update for DT span details
=> Update docs for otel span errors and exceptions

src/content/docs/integrations/amazon-integrations/get-started/aws-integrations-metrics.mdx
* This page is automatically generated based on conversion files we have for AWS API Polling integrations. We want to remove the beta callout and mention the full list of metrics should now be obtained from AWS (all metrics can be ingested with metric streams). 
=> Removing beta and adding note about all AWS metrics supported

src/content/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Deprecate CAT in Node.js agent documentation.
* Notes deprecation.
* Recommends DT and shares transition doc.
* Updates default config values for CAT and DT.
=> chore: deprecate CAT in Node.js agent documentation.

src/content/docs/infrastructure/infrastructure-alerts/infrastructure-alert-conditions/create-infrastructure-host-not-reporting-condition.mdx
Add "tagging" method of stopping a host from opening HNR violations
=> Add "tagging" method

src/content/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Updating compatibility since the Java agent is no longer compatible with the latest gRPC release.
No
=> chore: Updating gRPC compatibility

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
As reported in #documentation, the example for the Infra proxy settings is misleading.
=> Fixing Infra proxy settings example

src/content/docs/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
This configuration property had 2 entries and they were conflicting.
Removing the erroneous one.
No
=> chore: java configuration - removing conflicting duplicate entry

src/content/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration.mdx
Redesigning the JMX integration configuration section.
Add a table with the config options
Add example configurations
=> JMX : Add config V4 examples and reformat args

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence.mdx
While infrequent, when customers inevitably reach out to NR Support to move their II environment to another account, engineering has informed us (NR Support) that this is not actually possible and the customer needs to delete the environment via the incidentIntelligenceEnvironmentDeleteEnvironment NerdGraph API, then re-create it in the UI on the account that they want.
Since deleting the environment is not the same as moving the environment (there are configurations lost in deleting), I'm proposing that we simply take out mention of "moving" their environment completely.
* If your issue relates to an existing GitHub issue, please link …
=> Remove "need to change environment" bullet point

src/content/docs/agents/net-agent/troubleshooting/no-stack-traces-dotnet.mdx, src/nav/full-stack-observability.yml
We are missing .net agent specific documentation for the requirement to call NoticeError in some situations when stack traces are desired. 
Resolves: newrelic/newrelic-dotnet-agent#681
No
=> Add new page about calling NoticeError to get stack traces in .NET Agent

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
* New Relic has added the ability to select a FedRAMP compliant observer as of 9/17/2021 and these changes reflect that updated support, removing the old wording about it not being supported.
=> Update docs for infinite tracing FedRAMP support

src/content/docs/security/security-privacy/compliance/regulatory-audits-new-relic-services.mdx
In looking at https://github.com/newrelic/docs-website/releases/tag/release-09.09.2021-12.38 , specifically this commit : https://github.com/newrelic/docs-website/commit/26d0a42d490f2f2b900cdbadee7fa565de98ab3e, it looks like AWS Metric Streams was updated from being FedRAMP Moderate supported feature to not being supported.  This was released on Sept 9th.
It's valuable to know when this page was updated so that we can review supported/unsupported functionality and adjust as needed.
No, this is a simple documentation change.
=> Update last modified date on page

src/content/docs/agents/ruby-agent/installation/ruby-agent-installation-rails-plugin.mdx
Fix named anchor shown on [`update the newrelic.yml` subtitle](https://docs.newrelic.com/docs/agents/ruby-agent/installation/ruby-agent-installation-rails-plugin/#update-the-newrelicyml-file-updating_newrelicyml)
Original document
Document that I modified
#3962 
=> chore: 'update the newrelic.yml' named anchor shown on subtitle

src/content/docs/logs/log-management/troubleshooting/json-message-not-parsed.mdx, src/nav/full-stack-observability.yml
The JSON parsing troubleshooting doc was in the path /new-relic-logs/troubleshooting, which makes no sense. Moved it into the troubleshooting cat and updated the fso yml file
=> chore(Logs): Move doc in taxonomy

src/content/docs/agents/java-agent/configuration/java-agent-config-file-template.mdx
JFR feature was added to the agent some time ago, but the configuration template file was not updated with the respective params.
This adds those params.
Sorry for the removal of white space.
No
=> chore: Java agent - adding missing JFR properties in config file

src/data-dictionary/events/NrAiIncident/violationUuId.md
This addresses a gap in the deprecation of NrAiIncident.violationUuId started in https://github.com/newrelic/docs-website/pull/3435.
No
=> Deprecate violationUuId

src/content/docs/release-notes/logs-release-notes/logs-21-08-30.mdx
The new docs have been published, so I've added links and made some minor style guide edits
=> fix(Logs): Links to new docs

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
This link mentions simulating SQL joins, but redirects to a page about nested aggregation. Further, NRDB does NOT support joins so the text of the link is misleading.
=> Removing incorrect link.

src/content/docs/style-guide/writer-workflow/tech-writer-workflow.mdx, src/content/docs/style-guide/writing-guidelines/create-edit-content.mdx
* Shuffle order of h2s in several style guide docs to surface more universally applicable info
* Simplify text for edit procedure to make it look less hard
* Reduce and simplify text related to licenses, scheduling edits, and private site. These procedures are uncommon, and giving them so much screen real estate makes things seem a bit hard
=> fix(style guide): Improve "edit doc" instructions

src/content/docs/style-guide/quick-reference/bold-or-code-not-italics.mdx
Don't think we need a special rule about bold for agent lists
=> fix(style guide): Remove prescriptive note that agent lists use bold

src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-concepts.mdx
This is a PR to remove a confusing link to the NRQL pages and replace it with individual links to the derivative() and latest() functions.
=> Removed spurious link and added two new links.

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
- Add link to newer example in Extension repo.
- More clearly communicate where examples live.
=> update example links

src/content/docs/integrations/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic.mdx
Adding New Relic's directory customer id for customer's with strict organization policies.
Some customers have strict organization constrains which may restrict the ability to add the New Relic owned service account to their GCP Org. Providing this ID will allow customers with this type of configuration to unblock adding the service account
https://cloud.google.com/resource-manager/docs/organization-policy/restricting-domains
Internal Slack conversation: https://newrelic.slack.com/archives/C03HARJSV/p1632501770341100
No
If you're changing site code (rather than …
=> GCP add NR domain id for strict org policies

src/content/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent.mdx
Updated the infra log forwarder doc to exclude Debian 11. This edit fixes https://github.com/newrelic/docs-website/issues/4062
=> fix(Logs): Debian 11 not supported

src/content/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration.mdx
Small correction to our postgres ohi doc which by mistake was still referencing mongodb on the samples
=> small correction to postgres ohi doc

src/content/docs/agents/net-agent/net-agent-api/set-application-name.mdx
This clarifies the intended and recommended use for the SetApplicationName API provided by the .NET Agent. The intention is to avoid some problematic usage seen by GTS.
NOPE! :)
=> Add intentions/recommendations for .NET app name API

src/content/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
7.3.0 Releases on 9/30.  These are updates to the Java Agent compatibility docs related to the 7.3.0 release.
=> Java Agent 7.3.0 release changes

src/content/docs/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
Customer questioned weather the parameters for the `shutdown()` method were optional or not, our Github API documentation makes this more clear and includes a parameter not listed on the docs site:
http://newrelic.github.io/node-newrelic/docs/API.html#shutdown
Reformatted to match the Github format - although it has been awhile since I did any HTML so may need some fixes!
No
=> Add optional parameter and reformat

src/content/docs/integrations/elastic-container-service-integration/understand-use-data/ecs-integration-recommended-alert-conditions.mdx
You are now reporting a cpuUsedCoresPercent metric which I've confirmed is equivalent to cpuUsedCores/cpuLimitCores. Due to that, you should actually be able to query the cpuUsedCoresPercent metric directly. 
`cpuUsed` doesn't exist
See my support ticket Request #472305
No
=> Update High CPU usage alert condition

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/addtotrace-browser-agent-api.mdx
Include harvest cycle limit
This informs API users of a limitation. 
Yes, [the harvest cycle limitation is mentioned here](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1026/#:~:text=Adjusted%20PageAction%20limits,events%20per%20harvest.). 
none that I know of
=> Update addToTrace doc

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
Looks like the AWS Kinesis Firehose steps have had some minor updates. You no longer select third party service, you can select New Relic directly.
=> Minor Update to AWS Cloudwatch Metric stream doc

src/content/docs/using-new-relic/cross-product-functions/install-configure/networks.mdx
There's a timestamp at the top of this doc that wasn't changed for the latest new IPs
=> chore(networks): Update last modified date for IPs

src/content/docs/telemetry-data-platform/understand-data/event-data/nrauditevent-event-data-query-examples.mdx
I've edited the id of a collapsible section, so the anchor link refers to workloads instead of synthetics.
It seems a minor fix although I don't know if there are direct links that take here. Perhaps the Docs team has statistics about the origin of clicks and knows?
=> Minor fix: anchor identifier

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Delay/timer actually works entirely differently than the old evaluation offset, so I needed to change this sentence to reflect the new reality.
=> Small change to wording

src/content/docs/infrastructure/install-infrastructure-agent/manage-your-agent/infrastructure-agent-performance-overhead.mdx
* Adding a new benchmark scenario running default infra-agent on default EC2 AL2 instance (AMD vs ARM) as a reference for customers adoption ARM instances.
=> Add benchmark example for ARM64

README.md, src/content/docs/mobile-monitoring/mobile-monitoring-ui/network-pages/http-requests-page.mdx
Removing references to features no longer supported in the Mobile APM UI
* Add any context that will help us review your changes
This is the docs page being modified: https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/network-pages/http-requests-page/#non-enterprise-http-requests
Annotated pieces of image are features of Legacy Cross Application Tracing, and will no longer be available.
Nope
=> Remove mobile legacy cat

src/content/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream.mdx
* Adding inventory as a limitation in the CloudWatch metric stream integration.  
=> AWS metric stream inventory not available

.github/ISSUE_TEMPLATE/content-issue.md, .github/ISSUE_TEMPLATE/site-bug-report.md, .github/ISSUE_TEMPLATE/site-enhancement.md, .github/pull_request_template.md
* Further simplifies issue template for content issues
* Requests conventional commits for all PRs (content and eng PRs, rather than just eng)
* Changes the default heading size in issues and PRs to an h2 rather than an h3. The reason is a small boost to editor ergonomics: Docs on the docs site use h2s by default.
=> style(PR/issue templates): Simplify issue templates and switch to H2s

src/content/docs/browser/new-relic-browser/configuration/filter-ajax-request-events.mdx, src/nav/full-stack-observability.yml
The Browser Agent team is going to release a new version of the agent in the near future which increases the total number of AjaxRequest events captured. As part of this work, we added a new configuration to the UI to allow customers to specify a set of URLs which should not be recorded as AjaxRequest events.
The goal of this doc is to provide a reference on how to use this feature and provide support a resource to share with customers if they receive tickets.
We will need to leave this PR in draft form until the agent is publicly released (currently it is in testing in Staging) and we can update the doc with the correct agent version.
=> Add Browser Filter AjaxRequest Event doc

src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx, src/content/docs/accounts/accounts/account-maintenance/change-passwords-user-preferences.mdx
We had a request to remove some old support emails from our docs. This should remove them all!
=> fix: remove old support emails

src/content/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests.mdx
Related to: 
• Previous hero work requesting fix to private locations requirements - no longer requires requesting access to the feature
• Hero work for https://github.com/newrelic/docs-website/issues/4225: adding clarification about where to find 'add secure credential' button (although there may be a UI glitch around this, but it was reported).
=> fix(synth): edit to UI & req sections

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-alerts-policies.mdx
The NerdGraph API for Alerts Policies recently added support for `name` and `nameLike` searches. This adds an example for using the `nameLike` search criterion.
=> docs(Alerts): add NerdGraph example for searching Alert Policies by name

src/content/docs/network-performance-monitoring/setup-performance-monitoring/advanced-config.mdx
ref: https://github.com/kentik/ktranslate/pull/151
Updating notes on SNMP Trap config to show latest supported options for v1 and v3; referenced in the source PR above.
CC: @x8a
=> chore: updating with trap support of v1 and v3

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-nrql-condition-alerts.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-alert-conditions.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/update-or-disable-policies-conditions.mdx
Alerts released the stream aggregation methods last week and we have been going through the public docs to get them up-to-date with the new features. The streaming methods effectively deprecate evaluation offset so we’ve been trying to get the examples and other associated docs to reflect the new state-of-the-art. While I’ve been in there making these changes, I’ve been cleaning up anything else that appears to be out-of-date or otherwise misrepresents how it all works.
List of updates related to Streaming Methods release:
- big update + clean-up in REST API docs
- fixes some typos in GraphQL examples
- clean up formatting of code examples
-  remove references to Plugin alerts (EOL'ed a while ago!)
- other misc. typo fixes and clean-up
=> docs(Alerts): more updates related to Streaming Methods release

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-5-0.mdx
Adds release notes for Node.js agent v8.5.0 which shipped today.
=> chore: adds release notes for Node.js agent v8.5.0.

src/content/docs/integrations/open-source-telemetry-integrations/opentelemetry/view-your-opentelemetry-data-new-relic.mdx
Changing `#trx` to `#transactions` on the heading — "transactions" is the exact name of the nerdlet that provides this functionality, so by using the correct name here, we can link directly to this section of the docs from the app.
This comes into play when a user hasn't yet set up their instrumentation for Transactions yet; In the "empty state," the app will provide a link they can follow directly to these docs to help them get everything set up. (https://newrelic.atlassian.net/browse/APPEXP-3104)
links to related docs, screenshots, …
=> chore: change Transactions heading id

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
Per customer request, this doc is now updated to point out that Request is deprecated and to recommend SSL.
=> fix(synthetics): customer request to call out some things

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/scripted-browser-examples.mdx
Example mentions waiting up to 20 seconds. 2000ms is 2 seconds.
Fixed a typo in scripted browser examples page: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/scripted-browser-examples/
=> Update 2000 to 20000

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts.mdx
changed `aggregation_timer` to `aggregation_delay`, since the former was incorrect for the recommendation given.
=> Used wrong word in recommendation

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/tvos-application-licenses.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-tvos-release-notes/newrelic-tvos-2010.mdx
* Adds in 2.1.0 release note for AppleTV New Relic App
* Update licenses to latest version.
=> docs: Add in 2.1.0 release note for New Relic Apple TV app.

scripts/actions/generate-whats-new-ids.js
We have a script to generate new whats new IDs, but it didn't include any cleanup for what's new posts that get deleted. 
the `nr1-announcements` end-point doesn't care about this because it only matches IDs to existing posts, but the `nr1-announcements/ids` endpoint grabs the entire ID list which includes the deleted posts. this is was causing issue in the whats new nerdlet since they rely on the `/ids` endpoint to know when to delete a post
=> Add whats new id deletion logic

src/content/docs/infrastructure/amazon-integrations/troubleshooting/aws-service-specific-api-rate-limiting.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx
=> chore(frontmatter): Fix two duplicate redirects

src/content/docs/errors-inbox/errors-inbox.mdx
This implements some updates to the errors inbox doc as requested by the PMM.
Reviewer, I would just focus on typos and briefly scanning the rest. I have a JIRA to take a deep look and rework this doc in the next sprint.
=> chore: errors inbox updates

src/content/docs/errors-inbox/errors-inbox.mdx
Requesting @bradleycamacho as reviewer because errors inbox. In addition to the copy edits, I think we might want to take a fresh look at the metadescription, it feels pretty salesy:
> New Relic errors inbox is an error tracking solution designed to put you in the driver’s seat when it comes to detecting, triaging, and resolving errors across your full application stack.
=> chore(errors inbox): Copyedit formatting and style

gatsby-config.js, package.json, src/@newrelic/gatsby-theme-newrelic/components/NavItem.js, yarn.lock
Shadows the theme's `NavItem` component and does not set a URL in the `to` prop if the item has children (aka, not a leaf node 🤓 ). 
Closes https://github.com/newrelic/docs-website/issues/4516
https://user-images.githubusercontent.com/2952843/138965143-9a4f5d52-503b-421a-814e-30565d4d46db.mp4
=> Disable clickable links to auto index / landing pages in left nav

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/streaming-alerts-key-terms-concepts.mdx
Changed some of the wording on this page, and added a big callout since customers were breaking their alert setups by using EVent Flow at the wrong time.
=> A few small edits to the trigger descriptions

src/content/docs/data-apis/manage-data/drop-data-using-nerdgraph.mdx
This is a beta feature we are planning to pilot that will give customers more control over their cardinality by allowing them to drop attributes off of rollup data but keep it on the raw data that can be queried in the near term.
I tried to link to as many relevant docs as I could. We don't have much on the `RAW` keyword other than the [Tip on this doc](https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics/), which I do link to. I tried to have each section of the doc for the other drop rule types represented in this beta feature section so that once GA'd this should be pretty simply integrated into the format of the rest of the doc. I felt it was more clear to keep all the beta content together rather than sprinkle it throughout the document.
=> feat(drop-rules): Add beta feature documentation to drop attributes on aggregates

src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx
It's not clear that NRQL Rate Limits also apply to NRQL queries made through NerdGraph.
=> Link to NRQL Rate Limits from NerdGraph NRQL Tutorial

src/content/docs/apm/agents/java-agent/installation/install-java-agent.mdx, src/content/docs/apm/agents/net-agent/installation/install-net-agent-linux.mdx, src/content/docs/apm/agents/net-agent/installation/install-net-agent-windows.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx, src/content/docs/apm/agents/php-agent/installation/php-agent-installation-overview.mdx, src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx, src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/install-infrastructure-monitoring-agent-windows.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx, yarn.lock
This PR prepares a handful of agent pages for A/B tests. I used buttons consistently in these pages for new account and guided install links.
=> fix(agent install pages): prepped for A/B test. Added buttons.

src/nav/apm.yml, src/nav/mobile.yml
I removed a dummy link about adding custom data in the iOS navigation taxonomy.
Also, I renamed a few links for consistency.
=> Left navigation follow ups

.github/workflows/auto-comment.yml
This adds a blank line to the auto-comment bot for clarity.
=> fix: add blank line to auto-comment bot for clarity

src/content/docs/style-guide/writer-workflow/github-intro.mdx
This adds instructions on how to access the file history for docs pre-IA rework.
=> fix: Add pre-IA history access instructions

src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx
The anchor for the `Environment variables for monitoring .NET Framework applications` collapsor, it was set to the linux anchor.
* What problems does this PR solve? broken anchor
links to related docs, screenshots, etc. n/a
* If your issue relates to an existing GitHub issue, please link to it. n/a
=> Fixing the anchor

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* This callout is outdated. The full standard agent is now supported on Graviton/ARM. Keeping the callout to highlight the custom installation via tarball is still not officially supported.
=> Changing callout on infra-agent tarball install

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload.mdx
* Clarifies that the Alerts webhook metadata value is an object rather than a string
* In response to customer report that this was not clear
=> docs: clarify webhoook metadata format

src/content/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx
Hi there,
Really enjoy reading through these docs!
Stumbled on the synthetics-minion helm chart [here](https://github.com/newrelic/helm-charts/tree/master/charts/synthetics-minion) and saw that there seems to be a lot more options listed for configuration of the containerized private minion than what is currently displayed via the docs so I figured I'd whip up a small PR to create more parity between the two.
But!  I may be totally off, and perhaps some things aren't shouldn't be carried over into the docs :sweat_smile: 
Super willing to iterate, adjust, or even close this PR if these items aren't needed!
Big kudos to everyone that has spent so much time making these docs as awesome as they are!
=> Updating Kubernetes CPM Configuration Options Displayed

src/content/docs/alerts-applied-intelligence/applied-intelligence/mlops-integrations/algorithmia-mlops-integration.mdx, src/content/docs/alerts-applied-intelligence/applied-intelligence/mlops-integrations/datarobot-mlops-integration.mdx, src/nav/alerts-and-applied-intelligence.yml
Per request of Guy Fighel (GVP of AIOps), I have changed the Algorithmia name to Datarobot since Datarobot acquired Algorithmia. I wasn't sure how to handle links though since the Algorithmia site is still up and functioning. 
Acquisition information can be found at link below:
https://www.datarobot.com/news/press/datarobot-is-acquiring-algorithmia-enhancing-leading-mlops-architecture-for-the-enterprise/
=> Changing Algorithmia Name

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda.mdx
As reported in #documentation, the link to the CLI tool explanation in https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda/ takes the reader to a wrong doc. Fixing this with the PR.
=> Fixing wrong link to CLI doc

src/content/docs/apm/agents/java-agent/api-guides/guide-using-java-agent-api.mdx
As reported in #4654, the info about `headers` is somewhat hidden in the [Java agent API guide](https://docs.newrelic.com/docs/apm/agents/java-agent/api-guides/guide-using-java-agent-api/). This PR fixes this, and adds a link to an example.
=> chore(Java agent API): Highlighted info on headers

src/content/docs/logs/log-management/log-api/introduction-log-api.mdx, src/content/docs/logs/log-management/ui-data/long-logs-blobs.mdx
From wizards-logging 11-05-21. Added info about how we use blobs if length exceeds 4096 characters.
=> fix(Log API): Added info about blobs

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
The NRQL query in the existing example in invalid for most users (there is no SyntheticsEvent by default). If someone copies and pastes that code into their account, it will fail.
=> Replace NRQL in GET example with working query

src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx, src/nav/new-relic-solutions.yml
When I was working on previous changes in #4614, I had a git conflict and mistakenly overrode changes in #4625.
This PR corrects those capitalization overwrites, as well as changes the name of the file to "introduction.mdx" instead of "index.mds." The name change is because that file is no longer on a parent node.
The reviewer should make sure that the following two headings are now sentence case in the navigation:
"Observability maturity"
" Uptime, performance & reliability"
Also, please confirm that the redirect from the old index.mdx resolves to the introduction topic: /docs/new-relic-solutions/observability-maturity
=> Fix mistake observability maturity conflict override

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
Based on GitHub issue #4704, I corrected the yaml indentation in the Java configuration file doc. I confirmed with the Java team that the spacing should always use two spaces in our examples.
=> Correct Java agent configuration file examples using inconsistent indentation

src/nav/new-relic-solutions.yml
Related to https://github.com/newrelic/docs-website/pull/4733, I had forgotten to remove an ampersand in the left navigation.
Here is how the left navigation link looks now: Uptime, performance, and reliability.
=> Remove ampersand in left navigation

src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx
This request came in via documentation slack channel and was confirmed by the agent hero.
=> fix(vsphere VM): Added "sample" to entity names where it was missing

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx, src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx, src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx, src/content/docs/accounts/accounts/automated-user-management/roles-permissions-automated-user-management.mdx
Few things: 
For Okta doc, added info about creating groups in okta. 
More generally, added in AUM requirements a note about wanting to figure out groups on identity provider side before implementing AUM. 
Added info in Okta doc about recent change that they need to create a 'variable' field.
=> fix(aum): add info to okta about creating groups

src/content/docs/mobile-apps/new-relic-mobile-apps/android-app/introduction-new-relic-android-app.mdx, src/content/docs/mobile-apps/new-relic-mobile-apps/ios-app/install-new-relic-ios-mobile-app.mdx, src/data/homepage.yml, src/i18n/translations/en/translation.json, src/i18n/translations/jp/translation.json, src/pages/index.js
* I noticed the home page does not have any links to our new relic mobile apps, and it was quite impossible to know we have them, and in addition find any docs (except for release notes)
* View additional section under integration on the index page
* https://newrelic.atlassian.net/browse/MOBAPPS-4233
* I also updated the minimum os versions required, since those have changed for the mobile apps.
=> feat: Add new relic mobile apps to the front index page of docs

src/content/docs/apis/intro-apis/introduction-new-relic-apis.mdx, src/i18n/content/jp/docs/apis/get-started/intro-apis/introduction-new-relic-apis.mdx, src/i18n/content/jp/docs/apis/intro-apis/introduction-new-relic-apis.mdx
As reported in #4768, and as verified with the Browser team, removing references to Unity, which has been discontinued.
=> Removing links to Unity

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
It was previously unclear as to whether or not the `sendDataOnExit` configuration option actually initiated a harvest cycle. This change clarifies the impact of this configuration option.
=> Improve documentation for .NET agent configuration

src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx
The existing docker example for windows .NET framework apps no longer worked and needed to be updated. Improvements include:
- Agent installer is downloaded directly from New Relic
- Agent installer is now deleted after installation
- The source docker image references the new microsoft mcr registry
=> Fix sample Dockerfile for .NET Agent Framework Apps

src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx
The Windows .NET Core docker example needed `powershell.exe` to be prepended to several commands.  The example now dynamically downloads the agent as well
=> Improve windows .net core docker example

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
This change is to be more explicit about the restrictions of user keys and what happens when an associated user is deleted.
This PR is to provide clarity on the usage of user API keys, so users can view our docs to understand what will happen to API requests if a user key is deactivated.
Some of this, like deletion, is covered in the NerdGraph API tutorial: https://docs.newrelic.com/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys/
N/A
=> Add additional user key information

src/nav/integrations.yml
The left navigation link to Istio under "More integrations" wasn't removed when the Istio Adapter directory was removed. This is a clean-up task.
=> Remove Istio nav link since content directory is already gone

src/content/docs/style-guide/writer-workflow/github-troubleshooting.mdx
This adds an example of yarn-verify to our style guide.
=> fix: add yarn-verify example
