- src/content/docs/alerts-applied-intelligence/notifications/destinations.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-api-notifications-channels.mdx
> Added destination snooze docs

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
* This PR fixes some small issues with version ranges previously mentioned, to make the documentation more accurate. Also added references to some instrumentation that was recently added but not previously updated.
> Java agent compatibility page updates

- src/content/docs/logs/ui-data/find-unusual-logs-log-patterns.mdx
The sentence to be removed implies functionality that doesn't actually exist in the product and should be a feature request. Can provide additional details about removal upon request.
The Configure patterns button only supports enabling/disabling. You can't add additional patterns.
> Remove misleading sentence

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/service-characterization-optimize-telemetry-data-guide.mdx
Fix bad link format
Small edits to capabilities doc
> fix(capabilities): small edits

- gatsby-config.js
- package.json
- yarn.lock
> Update theme and add sign up config

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
Added docs reference and updated the Log API endpoint for FedRAMP customers
> Added FedRAMP endpoint

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Note from zuluecho9: these can go live thursday morning, unless we hear otherwise. Would appreciate glance from hero just in case we missed something obvious.
New NRQL functions, string() and concat(), are scheduled for GA on 6/30
NerdLife post when these went into Beta/Limited Preview:  https://nerdlife.datanerd.us/new-relic/nrql-string-functions-now-in-beta-0fbf57ed-2dea-4f54-bc2f-a2008136fcf5
> June 30 publish: new string() and concat() NRQL functions

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/subqueries-in-nrql.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nested-aggregation-make-ordered-computations-single-query.mdx
- src/nav/dashboards.yml
Note from zuluecho9: these can go live thursday morning, unless we hear otherwise. Would appreciate glance from hero just in case we missed something obvious. 
Subqueries are scheduled for GA on 6/30
Initiative Brief:  https://docs.google.com/document/d/1NcHmvEHO9a52cHK1212FLaITa7X3kbEjwp9NUTh7MVU/edit#heading=h.5x0d5h95i329
NerdLife subqueries Alpha post:  https://nerdlife.datanerd.us/new-relic/introducing-the-new-nrql-feature-subqueries-alpha-59f73c00-bafc-4407-a301-778a22d2472a
NerdLife subqueries Beta post:  https://nerdlife.datanerd.us/new-relic/nrql-subqueries-now-in-beta-312e8272-b542-4982-ad94-1f6c7be76981
* If your issue …
> June 30 - new NRQL subqueries

- src/content/whats-new/2022/05/whats-new-05-25-fs-recap-blog.md
fix(delete isFeatured true): Do not publish until 06-30-2022
See https://github.com/newrelic/docs-website/pull/7755
> Publish on 06-30-2022: Update whats-new-05-25-fs-recap-blog.md

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
This is Kevin Downs, New Relic PMM for infrastructure - kdowns@newrelic.com.
I updated the EKS-Anywhere to EKS Anywhere to match AWS naming. I also added EKS Anywhere on bare metal as we support it.
Can this change be made on June 30th please - that is the date AWS will add the Amazon EKS Anywhere on bare metal service.
> Added EKS Anywhere on bare metal (Publish on 6/30/2022 with "What's new")

- src/content/whats-new/2022/06/whats-new-06-30-zebrium-log-root-cause.md
> 06/30 - feat(whats-new): Zebrium integration

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
> Small spacing and punctuation updates

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1274.mdx
Release notes for agent 1.27.4
> docs: add infra agent release notes 1.27.4

- src/content/whats-new/2022/06/whats-new-06-30-zebrium-log-root-cause.md
Fix curly quotes in title and check whether YouTube runs. Reported in help-documentation channel that https://github.com/newrelic/docs-website/pull/8215 was not intended to publish with morning merge.
> style(Hero): Zebrium What's New

- src/content/docs/logs/logs-context/disable-automatic-logging.mdx
Fixes https://github.com/newrelic/docs-website/issues/7700
> fix(Hero): Clarify server-side

- src/data/external-redirects.json
to test, just click https://docswebsitedevelop-jiralinktweak2.gtsb.io/jira
> chore(jira redirect): Add user story, acceptance criteria

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
> Specify RabbitMQ version is for client library 

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-s3-monitoring-integration.mdx
> Update aws s3 metric filter instructions 

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
We just added some documentation for subqueries and some unnecessary tags are making it into the rendered page. These can be removed.
> Unnecessary tags

- src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx
> Removing EU Codestream disclaimer as it now supported in the EU as well

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/zip-assisted-install-infrastructure-agent-windows.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/zip-manual-install-infrastructure-agent-windows.mdx
* Add docs on how to verify checksums for tar.gz and zip
> Update tar.gz, zip infra-agent installation with checksums verification

- src/content/whats-new/2022/07/whats-new-07-06-nrql-subqueries.md
> "What's new" NRQL subqueries announcement (Publish 9:00 AM on 7/6/2022)

- src/content/whats-new/2022/07/whats-new-07-06-nrql-subqueries.md
Adding a link to the Explorers Hub post from the PM
> Add discussion post link

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
> Update capture() regex guidance

- src/content/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic.mdx
> chore(style guide): update voice page with new traits

- src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-670.mdx
[NR-24574]
* This commit provides basic release notes for the latest Android agent release.
* [Release story](https://issues.newrelic.com/browse/NR-24574)
> feat(android agent): Android 6.7.0 release notes

- src/content/docs/data-apis/manage-data/manage-your-data.mdx
changing New Relic's to New Relic per style guide https://docs.newrelic.com/docs/style-guide/capitalization/product-capability-feature-usage/
> changing New Relic's to New Relic per style guide

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
We gathered information around the impact of Inspected Count hitting the rate limit within an account and how will different components of NewRelic be impacted from a customer experience point of view. Here are the details:
https://newrelic.slack.com/archives/C01508Q2879/p1656433937163829
https://newrelic.slack.com/archives/C01508Q2879/p1657187781242109
* What problems does this PR solve? - Better clarity in documentation
> Updated Impact of Inspected Count rate limit

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- add charts and organize page
- set default `accountId` to 0.
- replace `location` with `locationLabel` for readability
> Improve SyntheticRequest page

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-15-0.mdx
Node.js Agent v8.15.0 Release Notes
> Node.js Agent v8.15.0 Release Notes

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4010.mdx
* Add in release note for New Relic for iOS version 4.1.0.
> doc: Add in release note for New Relic for iOS version 4.1.0.

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4600.mdx
> Release notes: New Relic for Android v4.6.0

- src/content/docs/agile-handbook/appendices/ticket-best-practices.mdx
> fix(agile best practices): updated user stories

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
changed "New Relic's" to "the New Relic" to follow the style guide: https://docs.newrelic.com/docs/style-guide/capitalization/product-capability-feature-usage/
> changed "New Relic's" to "the New Relic"

- src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/investigate-mobile-app-crash-report.mdx
- src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-native-reporting.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/android-agent-configuration-feature-flags.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-crash-reporting.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-native-crash-reporting.mdx
- src/data-dictionary/events/MobileCrash/MobileCrash.event-definition.md
- src/data-dictionary/events/MobileCrash/crashException.md
- src/nav/mobile.yml
* Android native reporting adds an additional level of crash instrumentation. Low-level _signals_ and other unhandled exceptions will now be caught and reported through the legacy Android agent. In addition, the agent will make all attempts to detect and report _Application Not Responding_ (ANR) conditions. 
There is minimal setup and configuration, but what is required is detail in this commit.
We've provided the basic outline of docs this feature will need. It's hoped this will be enough inform users on the basics of the feature, and help them get the new feature added to their apps.
* [Release story](https://issues.newrelic.com/browse/NR-24574)
> feat(android native reporting): initial document setup

- src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-4-0.mdx
Adds documentation for new metrics introduced when supporting k8s v1.23 & 1.24
https://github.com/newrelic/nri-kubernetes/issues/455
> Add new metrics for k8s 1.23 & 1.24

- src/content/docs/accounts/accounts/automated-user-management/azure-ad-scimsso-application-configuration.mdx
Fixes https://github.com/newrelic/docs-website/issues/8397
> fix(Hero): Button label

- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
changing the title here from "Recommended for large organizations: Understand user management concepts" to "Understand user management concepts"
New Relic now recommends that all our customers move to v2. A title like this causes hesitation among customers to move to the v2 model.
> Changing sub title

- src/content/docs/style-guide/writing-strategies/install-docs-guidance.mdx
- src/nav/style-guide.yml
Tweaks title to avoid this doc showing up in google search so easily
> chore(style guide): Tweak doc title to avoid SEO confusion

- src/content/docs/browser/browser-monitoring/getting-started/browser-summary-page.mdx
- src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
For NR-27689. Added more details about core web vitals but still need to drastically reduce the sheer amount of info in this doc.
> feat(Browser intro): Rewrite

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-4-0.mdx
Following https://github.com/newrelic/docs-website/pull/8205/files#r916841787.
> Improve k8s release notes

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts.mdx
- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
- src/content/docs/apm/agents/java-agent/installation/include-java-agent-jvm-argument.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent.mdx
- src/content/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction.mdx
- src/content/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent.mdx
- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
- src/content/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
- src/content/docs/logs/forward-logs/aws-lambda-sending-logs-s3.mdx
Added Korean tag for human translation.
> Update to Korean human translation workflow.

- src/content/docs/accounts/accounts/account-maintenance/change-your-new-relic-account-name.mdx
- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
Add to user migration doc clarifying that editing auth domain isn't possible. 
Add info about renaming accounts via UI
> User mgmt - some small changes

- src/content/docs/mobile-monitoring/new-relic-mobile-ios/configuration/retrieve-dsyms-bitcode-apps.mdx
https://github.com/newrelic/docs-website/issues/1592
Fixes the problems stated in this issue based on current (7/12/2022) App Store connect layout.
> Update download dsym section

- src/content/docs/infrastructure/host-integrations/installation/secrets-management.mdx
Example configurations were using outdated format. Updated to v4.
> Updated config examples to v4 layout

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Edited to include new sections 'FedRAMP Inheritance' and 'FedRAMP-compliant endpoints' sections (immediately above the existing 'Overview of data sources' section), as requested by ProdOps and validated by product management.
> Update to fedramp-compliant-endpoint doc

- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-221.mdx
These are the release notes for our latest changes
> fix: Diagnostics CLI Release Notes v2.1.1

- src/content/docs/style-guide/writing-docs/writer-workflow/set-up-local.mdx
This is a documentation update for building a smaller part of the docs site locally
> Update local setup doc

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1275.mdx
> docs: add infra agent release notes 1.27.5

- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
This revision provides two enhancements
- Gives some `bytecountestimate()` examples for logs
- Gives some information on using the APM agent's log sampling environment variable
> fix: more help on log volume mgmt

- src/content/docs/apm/agents/java-agent/getting-started/introduction-new-relic-java.mdx
- src/content/docs/apm/agents/java-agent/getting-started/monitor-your-java-app.mdx
- src/content/docs/apm/agents/java-agent/installation/java-install-overview.mdx
We weren't getting much response from this so we'll work on another way to get some feedback from our readers.
> fix(APM): Removed embedded Google survey

- .github/CODEOWNERS
Adds docs eng as reviewers for any PRs that modify package.json
> chore: add package json to docs eng codeowner

- src/content/docs/release-notes/mobile-release-notes/xcframework-release-notes/xcframework-agent-737.mdx
> Added release notes for iOS XCFramework version 7.3.7

- package.json
- yarn.lock
> Bump theme to latest version

- src/content/whats-new/2022/07/whats-new-07-14-fedramp-logs-update.md
FedRAMP compliant accounts will start collecting application logs in context automatically, starting August 12th
> feat(whats-new): add fedramp logs WN post (publish 07-14-22)

- src/content/docs/style-guide/writing-docs/writer-workflow/set-up-local.mdx
> fix(style guide): Typo

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
I added a demo video to the steps users can take after filtering their query. The demo wistia link can be found here: https://newrelic.wistia.com/medias/8sp8qupnie
> Added demo video

- src/content/docs/apm/agents/go-agent/installation/install-new-relic-go.mdx
It gives an example of what the import statement looks like when adding the go agent to your package. This helps less experienced golang programmers install the agent.
> fix(go-agent): add an example of how to import the agent

- src/content/docs/data-apis/manage-data/nrintegrationerror.mdx
* Minor update since nrIntegrationError can also be generated from Infrastructure.
> Adding Infrastructure category to NrIntegrationError docs

- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-4-1.mdx
Release notes for https://github.com/newrelic/nri-kubernetes/releases/tag/v3.4.1
> feat(k8s): new release notes

- src/content/whats-new/2022/07/whats-new-07-15-infra-RUM-in-context.md
Can go out anytime on 7/15 or later as feature is already live.
Does not need review by a PMM since PMM is the author.
> feat(whats-new): infra and RUM in context

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/accounts/original-accounts-billing/original-product-based-pricing/switch-new-models.mdx
- src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
- src/content/docs/data-apis/manage-data/calculate-data-ingest.mdx
- src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx
- src/content/docs/data-apis/manage-data/manage-your-data.mdx
- src/content/docs/logs/get-started/get-started-log-management.mdx
- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
Fixing links to cost estimator resource
> fix(cost estimator): replace links

- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
New Relic mandates every v1 account to move to v2. So this part of the doc is going to create unnecessary confusion.
> Remove -> Determine if you should migrate users

- src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-trace-observer-monitoring.mdx
> Updates to rename the New Relic Edge app

- src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx
> Updates to rename New Relic Edge app

- src/content/docs/apis/nerdgraph/examples/configure-infinite-tracing-graphql.mdx
> Update to rename New Relic Edge app

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
We need to clarify the situation when there's no data coming in for a workflow test.
> Clarify workflow test when there's no customer data

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-16-0.mdx
Node.js Agent v8.16.0 Release Notes
> Node.js Agent v8.16.0 Release Notes

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
This one's for @rhetoric101 ;)
> chore(style guide): Clarify version references

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx
> Fix link to legacy tests doc

- src/content/docs/logs/logs-context/configure-logs-context-python.mdx
Updated documentation for Option 2 so that is very clear to disable the logging forwarding.
> forwarding.enabled should be false for Option 2

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71600178.mdx
This PR adds additional information to the Python agent 7.16.0.178 release notes.
> Update Python Agent release notes.

- src/data-dictionary/events/BrowserInteraction/sessionTraceId.md
Based on https://github.com/newrelic/docs-website/issues/8565.
> fix(browser dict): add new item traceSessionId

- src/content/docs/browser/browser-monitoring/getting-started/browser-summary-page.mdx
> fix(Browser summary): Rewrite to reflect current UI

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
> Added the events API to the endpoint chart

- src/content/docs/style-guide/writing-strategies/install-docs-guidance.mdx
A style guide update that attempts to clarify (for our writers) the difference between the public I/O page and the Add data page in the UI. 
I can add more info here about why I made this change, for example.
Reviewer: This is a minor change. What do you think?
I want to know if I've succeeded in clarifying this difference.
> feat(style guide): Clarifying the difference between public I/O and add data in the UI (NR-23312)

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
- src/content/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page.mdx
- src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-trace-observer-monitoring.mdx
- src/content/docs/errors-inbox/errors-inbox.mdx
- src/content/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-monitoring-email-notifications.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/view-ping-monitor-results.mdx
- src/content/whats-new/2022/01/whats-new-01-12-core-user-type.md
Updated URL from one.newrelic.com  to https://one.newrelic.com
* Fixing page error.
> Update URL to New Relic product

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-fargate-integration.mdx
Changed release type from "Beta" to "Public preview" following the new guidelines proposed by Product Operations
> Change released type

- src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx
> Updated OS supported

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1280.mdx
Infra agent release notes for version 1.28.0
> docs: add infra agent release notes 1.28.0

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Remove an ancient usage dictionary entry
> style(style guide): Remove old "NR ONLY" from usage dic

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/apis/nerdgraph/examples/async-queries-nrql-tutorial.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial.mdx
- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
- src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
- src/nav/telemetry-data-platform.yml
NR-34814
Work: 
New 'Async query' doc in NerdGraph category
Links to it from Data Plus section and from 'query duration limit' doc.
> new(async query): new NG doc

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
- src/content/docs/new-relic-solutions/get-started/networks.mdx
- src/data-dictionary/events/BrowserInteraction/sessionTraceId.md
sessionTraceId: edit definition
Tiered pricing: move section to main billing doc
Addition to 'Networks' doc for TLS 1.2 update
In billing doc, changed 'annual pool of funds' to more general 'contract' language
> Zach's small changes branch

- src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-and-dt.mdx
> docs: fix broken link

- gatsby-config.js
- src/install/config/java/config.yaml
- src/install/mdx/java/component.mdx
Sources files for graphql update
> NR-37024 - Source mdx/yaml files

- src/content/whats-new/2022/07/whats-new-7-29-infra-new-entity-tabs.md
The single host entity view has been updated to add three new tabs - Network, Process, and Storage.
> "Whats-new" new infrastructure entity tabs 07-27-2022

- src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx
> style(OMA): Fix indent

- package.json
- yarn.lock
> fix: update logo viewBox

- src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
https://github.com/newrelic/node-newrelic/blob/0532769c15425dc6f941797a70c6bb8f3095eae3/api.js#L384-L395
> docs: +more noticeError info from the sourcecode

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-17-0.mdx
Node.js Agent v8.17.0 Release Notes
> Node.js Agent v8.17.0 Release Notes

- src/content/whats-new/2022/07/whats-new-07-28-TLS-EOL.md
From @zuluecho9: I reviewed this and made some edits, should be good to go morning of July 28. 
EOL(whats-new): TLS 1.2 requirement
Specify the date and the time window when it should be published: morning, July 28th 2022.
Transport Layer Security (TLS) New Relic will be updating the TLS requirements for all endpoints to a minimum of version TLS 1.2 or above effective October 24, 2022.
> July 28: What's new: Add files via upload

- src/nav/new-relic-security.yml
Removes a useless category bucket
> fix(security): move nav over one category to the left

- src/content/docs/data-apis/custom-data/sap-integration.mdx
We had a request to add limits to SAP doc. The limits are based on pricing edition.
> fix(SAP): add limits

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
Please use this exact language that has gone through reviews and approvals. Thank you!
> Updated "Note" verbiage under Inheritance section

- src/content/docs/apm/agents/net-agent/azure-installation/azure-web-apps-using-always-no-data-appears.mdx
- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-cloud-services.mdx
- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-service-fabric.mdx
- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
Added language identifiers to .NET azure docs 
> docs: add lang identifiers

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4020.mdx
* Adds latest release notes for New Relic for iOS version 4.2.0
> Docs/add 4.2.0 New Relic for ios release notes

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Fix some strange indents in the compatibility doc, and remove some unnecessary line breaks
> style(java): Indents in compatibility doc

- src/content/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent.mdx
- src/content/docs/apm/agents/php-agent/getting-started/introduction-new-relic-php.mdx
- src/content/docs/style-guide/writing-docs/article-templates/whats-new-tech-writer-tasks.mdx
First set of work corresponds to this filed issue: https://github.com/newrelic/docs-website/issues/8646 
- Added redirect to the Intro to monitoring for PHP.
- Removed the initial link because it was redundant / plinko.
Second set of work corresponds to the What's new? process for tech writers. 
- Added clarity steps for What's new? post based on ~training today
> feat(apm, style guide): Added redirect, removed a redundant link, made edits to tech writer process

- src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
- src/content/docs/apm/agents/java-agent/getting-started/monitor-your-java-app.mdx
- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
- src/content/docs/apm/agents/python-agent/getting-started/introduction-new-relic-python.mdx
- src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
- src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
- src/content/docs/infrastructure/elastic-container-service-integration/get-started/introduction-amazon-ecs-integration.mdx
- src/content/docs/logs/get-started/get-started-log-management.mdx
- src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx
- src/content/docs/new-relic-solutions/new-relic-one/install-configure/install-new-relic.mdx
Added "-kr" for human translation for Korean for 11 files.
> Added HT tag to 11 files for KR

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx
Missing `cacert` field in etcd mtls instructions
> Add cacert field

- src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
Updated demo video to new demo using new wistia link. Update should be live by Monday
> AUGUST 1 2022 - MORNING. Video demo of new email notification capability in 'Workflows'

- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
- src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
- src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
- src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx
- src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx
- src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
- src/content/docs/infrastructure/infrastructure-monitoring/get-started/infrastructure-agent-eol-policy.mdx
- src/content/docs/licenses/end-of-life/notification-changes-new-relic-saas-features-distributed-software.mdx
- src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
- src/nav/apm.yml
- src/nav/browser.yml
- src/nav/infrastructure.yml
- src/nav/mobile.yml
> feat(EOL policy update): For NR30807

- gatsby-config.js
We had a contributor ask us to add "batch" as a code fence.
> Add batch to list of code fences

- src/content/docs/apis/rest-api-v2/application-examples-v2/change-alias-your-application-v2.mdx
- src/content/docs/apm/agents/c-sdk/install-configure/uninstall-remove-c-sdk.mdx
- src/content/docs/apm/agents/c-sdk/instrumentation/guide-using-c-sdk-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/guide-using-net-agent-api.mdx
- src/content/docs/apm/agents/php-agent/installation/php-agent-installation-tar-file.mdx
- src/content/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration.mdx
- src/content/docs/infrastructure/host-integrations/troubleshooting/not-seeing-host-integration-data.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-puppet.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/configuration/config-file-template-newrelic-infrayml.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-agent.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/windows-installation/install-infrastructure-monitoring-agent-windows.mdx
- src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx
- src/content/docs/new-relic-solutions/new-relic-one/workloads/workload-status-configuration.mdx
- src/content/docs/new-relic-solutions/new-relic-one/workloads/workload-status-views-notifications.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
Fixes for various weird grammar and poorly written metadescriptions
> Lame metadesc fixes

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
Tiny cosmetic to fix a capitalization error
Preview link: https://docswebsitedevelop-austinschaeferpatch686507.gtsb.io/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/
> style(k8s): Fix EU tile name

- src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
> style(Hero): fix spacing

- src/content/docs/release-notes/index.mdx
* Fixes an alphabetical order issue with the tiles
* Removes tvOS entry since it's so old; also filed ticket (NR-38721) to remove that content
> style(release notes): Fix tile order, delete tvOS

- src/components/AppInfoConfigOption.js
> Add AppInfoConfigOption

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-0.mdx
* Code-Level Metrics are now available for instrumented transactions. This is off by default but once enabled via `ConfigCodeLevelMetricsEnabled(true)` transactions will include information about the location in the source code where `StartTransaction` was invoked.
* Adds information about where in your source code transaction traces originated.
* See the Go Agent documentation for details on [configuring](https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config) Code-Level Metrics and how to [instrument](https://docs.newrelic.com/docs/apm/agents/go-agent/instrumentation/go-agent-code-level-metrics-instrument) your code using them.
* New V2 logs in context plugin is available for Logrus, packed with all the features you didn't know you wanted:
* …
> Release notes for Go Agent Release v3.18.0

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts.mdx
- src/content/docs/alerts-applied-intelligence/transition-guide.mdx
- src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx
- src/content/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/how-use-service-maps.mdx
- src/content/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/introduction-service-maps.mdx
- src/content/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/service-maps-apm.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
> feat(EOL notices): Q2 FY23 NR-30380

- src/content/docs/logs/ui-data/parsing.mdx
Remove link to outdated NerdByte for creating parsing rules
> Updating NR parsing docs

- src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/error-optimization.mdx
- src/nav/new-relic-solutions.yml
Hey docs team - error tracking optimization is a new Observability Maturity use case.  This initial pull request is an MVP - after this goes out I will follow up in V2 with links, images, and readability improvements.
> Oma error optimization

- src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx
follow-up work to https://github.com/newrelic/docs-website/pull/8714
> fix(OM): add new error guide to intro

- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
Logs in context features:
- logrus plugin
- local log decorationg for logrus plugin only (for now)
> go agent logurs release

- src/content/docs/apm/transactions/transaction-traces/transaction-traces-trace-details-page.mdx
Added link to PHP transaction tracer configuration.
Removed references to C SDK as this product has been deprecated:
https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744
> Update transaction traces details page

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-17-1.mdx
Node.js Agent v8.17.1 Release Notes
> Node.js Agent v8.17.1 Release Notes

- .github/auto_assign.yml
- .github/workflows/auto-assign-reviewer.yml
Reverts newrelic/docs-website#6492
This re-implements our auto assigned reviews based on our team's last retro.
> Reimplement auto assigned review

- src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
- src/content/docs/apm/agents/java-agent/custom-instrumentation/circuit-breaker-java-custom-instrumentation.mdx
- src/content/docs/browser/new-relic-browser/configuration/group-browser-metrics-urls.mdx
- src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/android-sdk-api-guide.mdx
> Zach small changes aug 3

- .github/auto_assign.yml
> Add austin

- src/content/docs/apm/agents/net-agent/custom-instrumentation/custom-instrumentation-attributes-net.mdx
I created some examples off the custom XML examples to show someone how this works, so I added it to this doc for others to use.  Please let me know if this formatting is poor
> docs: add example code

- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71400177.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71600178.mdx
This PR corrects the support statement for the last two python agent releases.
> Update oldest supported version in Python release notes.

- src/content/whats-new/2022/07/whats-new-7-29-infra-new-entity-tabs.md
I _think_ that the wistia video in this [whats new post](https://docs.newrelic.com/whats-new/2022/07/whats-new-7-29-infra-new-entity-tabs/) isn't loading (when navigating from somewhere in the site) because the scripts aren't loading when using gatsby's router, trying an iframe instead
> Use iframe with styled div

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/streaming-alerts-key-terms-concepts.mdx
> Fix relative link

- src/content/docs/apm/agents/php-agent/troubleshooting/generating-logs-troubleshooting-php.mdx
> Changes log locations

- src/content/docs/alerts-applied-intelligence/notifications/intro-notifications.mdx
fix of https://github.com/newrelic/docs-website/issues/8594
> fix(notifications): add security info

- src/content/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-sub-account-object.mdx
- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
Added @homelessbirds's new 'Welcome to New Relic' doc that was accidentally reverted in https://github.com/newrelic/docs-website/pull/8356/files. 
Also added fix to Partnership API sub-account creation call
> fix(welcome doc): new doc

- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
- src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx
- src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
> feat(Addl EOL from SME): Go, PHP, Python

- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-18-0.mdx
Corrects the 3.18.0 release date in the release notes.
> Fix(Go agent): corrected release date

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-0-0.mdx
Node.js Agent v9.0.0 Release Notes
> Node.js Agent v9.0.0 Release Notes

- src/content/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing.mdx
Clarified W3C in trace headers. Also restructured the doc. (I can't help myself.) Fixes https://github.com/newrelic/docs-website/issues/3050
> fix(Browser DT): W3C

- .github/workflows/auto-comment.yml
GH action to notify about Relic Recharge week
See also #8803.
> chore(.GITHUB): GH action to notify about recharge week

- src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Adds docs for configuring rsyslog with compression
https://docs.newrelic.com/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic/#rsyslog
> rsyslog-compression

- src/content/docs/new-relic-solutions/get-started/networks.mdx
Fixes https://github.com/newrelic/docs-website/issues/5950
> fix(Browser clarify): NR-37606

- src/content/docs/apm/agents/java-agent/custom-instrumentation/java-instrumentation-xml.mdx
Reported in help-documentation 08-05-22
> chore(Hero): anchor link

- src/content/docs/logs/ui-data/parsing.mdx
Accidentally merged PR  https://github.com/newrelic/docs-website/pull/8561 without double-checking my edits.
> fix(Hero): Typo, sorry

- src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_ignore_transaction.mdx
- src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_set_user_attributes.mdx
- src/content/docs/apm/agents/php-agent/php-agent-api/newrelicacceptdistributedtracepayload-php-agent-api.mdx
- src/content/docs/apm/agents/php-agent/php-agent-api/newrelicacceptdistributedtracepayloadhttpsafe-php-agent-api.mdx
- src/content/docs/apm/agents/php-agent/php-agent-api/newreliccreatedistributedtracepayload-php-agent-api.mdx
Cleaned up code that was running together on single lines, made a new codeblock out of text and added lang identifiers. This should all just improve readability.
> Update some PHP docs

- src/content/docs/apis/nerdgraph/examples/nerdgraph-slm.mdx
- src/content/docs/service-level-management/create-slm.mdx
- src/content/docs/service-level-management/faqs-slm.mdx
* What problems does this PR solve? Just formatting for prettiness and readability.
> Formatting and language identifiers added to SLO/SLI code

- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
- src/content/docs/logs/logs-context/disable-automatic-logging.mdx
- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Like in the Node and Java versions of this page, having the supported frameworks visibly listed at the top is helpful for support and customers
> docs: update logs in context pages

- src/content/docs/new-relic-solutions/new-relic-one/ui-data/metric-normalization-rules.mdx
> docs: move line for readability

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
> update compatibility for play framework

- src/content/docs/style-guide/writing-strategies/five-questions-help-write-docs.mdx
> chore(style guide): Update 5Qs w/ new brand values

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-find-entities.mdx
Adds info on how to filter entities using tags, and includes a link to the other doc I just submitted a PR for that adds info on how to add custom tags to entities. 
I pulled in info from existing docs. 
> Adds a section on how to view entities using tags

- src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx
- src/content/docs/apm/agents/manage-apm-agents/configuration/high-security-mode.mdx
- src/content/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby.mdx
- src/content/docs/distributed-tracing/concepts/introduction-distributed-tracing.mdx
- src/content/docs/errors-inbox/error-external-services.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- src/content/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag.mdx
PR for issues related to 8/15 hero work
> hero pr 8/15

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Reported in https://github.com/newrelic/docs-website/issues/8806. Added details for booleans to NRQL operators section.
> fix(nrql): adding booleans

- src/content/docs/errors-inbox/error-external-services.mdx
Added instructional youtube video to show how to connect errors inbox with Jira to create jira tickets
> Add video to Jira integration section

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4620.mdx
new release note for android app update 
edit as needed
> add release note for 4.6.2 release

- src/content/docs/apm/new-relic-apm/getting-started/get-started-logs-context.mdx
> feat(Auto LiC): Known limitations

- src/pages/index.js
> chore: test change in home page

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Fixing a typo - Changing "thew" to "the"
> fix: Typo 

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
This clarifies the requirements to use in agent automatic log forwarding
> Clarify supported logging framework versions for in agent log forwarding

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1281.mdx
> NewRelic infrastructure agent 1.28.1 release notes

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx
Synthetic Simple Browser Response Validation only looks at the DOM, and not the rendered page.
> Specify Synthetic Simple Browser Response Validation

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/style-guide/word-choice/pricing-language-guidelines.mdx
Work related to: 
Clarifying that free tier has some different limits than Standard
Clarifying that Standard is separate from free tier
Some style guide edits related to above.
> fix(free tier): clarifying what limits free tier has

- src/content/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/diagnostics-cli-225.mdx
Release notes for new Diag CLI release
> Diagnostics CLI Release Notes 2.2.5

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup.mdx
> Update JS link to correct otlp grpc exporter

- src/nav/apm.yml
Renames the top level APM category
> Rename APM cat 1

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1282.mdx
> NewRelic infrastructure agent 1.28.2 release notes

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
Due to unsigned CLA, reverting newrelic/docs-website#8896 so I can add that work back in myself.
> Revert "Updated cumulativetodelta/metrics"

- src/content/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes.mdx
We want to make it clear that NaN and infinity metric values will result in dropped data.
> fix(MetricAPI): NaN and infinity value handling

- src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx
- src/content/docs/distributed-tracing/trace-api/trace-api-decorate-spans-attributes.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-external-services-page.mdx
A customer opened an issue with us asking why they weren't seeing any data on their External Services page. We noticed that they weren't passing the correct attributes, and we further noticed that the docs did not contain information on what attributes were required. This PR aims to correct that.
> Attribute requirements for External Services

- src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx
- src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
- Adjusted wording of a few sections
- Made it clearer that both IP list and IP range lists should be accounted for
- Added details for additional IP ranges that will be added later in the year
> feat(synthetic IPs): Added details for additional IP ranges

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
> fix(query data limits): clarify & improve readability

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4030.mdx
* Adds in release notes for the 4.3.0 version of the iOS app
> docs: add in release notes for 4.3.0 version of the iOS mobile app

- .github/auto_assign.yml
Removes @barbnewrelic from auto assign list
> Remove Barb from auto assign list

- src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> add v9.0.1

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-0-1.mdx
Node.js Agent v9.0.1 Release Notes
> Node.js Agent v9.0.1 Release Notes

- src/content/docs/mlops/get-started/intro-mlops.mdx
changing the order of whats most important to users and what is used most
> change order

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
> docs: cleaned up code and added lang identifiers

- src/content/docs/new-relic-solutions/get-started/glossary.mdx
> fix glossary link

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
- src/content/docs/apm/agents/ruby-agent/background-jobs/monitor-ruby-background-processes.mdx
> chore: fix typo, updated workflow something or other

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1283.mdx
Release notes for infrastructure agent 1.28.3
> add release notes for infra agent 1.28.3

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-0-2.mdx
Node.js Agent v9.0.2 Release Notes
> Node.js Agent v9.0.2 Release Notes

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
- src/nav/accounts.yml
> Add info on exceeding free tier data ingest limit

- src/content/docs/accounts/original-accounts-billing/original-users-roles/overview-user-models.mdx
- src/content/docs/licenses/license-information/usage-plans/new-relic-one-usage-plan-descriptions.mdx
> Daily release/aug 25  2022 8 07

- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Updating the docs to include guidance for customers using managed db services from Azure and AWS.
> Added Azure and AWS Sample

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-configs.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-troubleshooting.mdx
> Add language identifiers to otel docs

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
Add OTel to user type table, under APM. Few other tweaks to clarify using that table.
This should be able to be published morning of Aug 26 unless we hear otherwise.
> Aug 26 morning: Add OTel to user type table

- src/content/whats-new/2022/08/whats-new-08-26-collaboration-limited-preview.md
Date and the time window when it should be published: 08-26-2022 Morning 
I am a PMM, this post does not need PMM review. 
One request: Can I get confirmation that the wistia video embed code works as intended? Thanks!
> feat(whats new): collaboration limited preview

- src/nav/new-relic-solutions.yml
Experiment of moving up 'quick launch guide' in nav to see how it affects traffic.
> fix(quick launch): move up nav

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed.mdx
Fixes a broken relative link reported in hero channel
> fix(AI): Fix broken relative link

- src/content/docs/logs/logs-context/logs-in-context.mdx
Clarify that logs in context also works with OpenTelemetry.
> Add OpenTelemetry to main logs in context page

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1284.mdx
Adds release notes for infrastructure-agent 1.28.4
> release notes for infrastructure agent 1.28.4

- src/content/whats-new/2022/08/whats-new-08-29-dbmarlin-quickstart.md
Just a small change. Can wait until next merge. Thank you!
> Add link to quickstart in "get started" section

- src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
This PR adds documentation for the new cancel endpoint for historical exports.
> add cancel export documentation

- src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
Added new demo video using a Wistia link to the Mobile Push Destination section
> Added wistia link

- src/components/InstallNextSteps.js
(From the figma file)
Positive feedback design: 
Negative feedback design:
> Update java install feedback component

- src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/apollo-server-plugin-nodejs.mdx
* Closes https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/133
> fix(node agent): Document the minimum version of Apollo Server that we support

- src/content/docs/browser/new-relic-browser/troubleshooting/get-browser-side-troubleshooting-details-har-file.mdx
> fix(support): broken link

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- add a few useful charts
- ignore locations that start with AWS_
> Improve dashboard JSON

- src/content/docs/data-apis/manage-data/manage-data-retention.mdx
Also cleaned up alphabetical order!
> Added network data retention

- src/content/docs/logs/ui-data/parsing.mdx
Fixing typo in example log record for json parsing
> Update parsing.mdx to fix minor typo

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
> chore(.NET): fix typo

- src/content/whats-new/2022/08/whats-new-08-31-wayscript-integration.md
> feat(whats-new): Add WayScript integration post

- src/content/docs/style-guide/writing-docs/writer-workflow/tech-writer-workflow.mdx
Quick fix to clarify importance of `from_tw` label
> fix: clarify importance of from_tw label

- src/data-dictionary/events/NrAiIncident/closeCause.md
> fix(data dictionary ): added descriptions

- src/content/docs/apm/agents/net-agent/configuration/distributed-tracing-net-agent.mdx
> docs: add xml identifier

- src/content/docs/distributed-tracing/ui-data/query-distributed-trace-data.mdx
> docs: add sql identifiers

- src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1218.mdx
Release notes for v1218 release --> https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1218
> browser-agent-v1218 Release Notes

- src/content/docs/logs/forward-logs/enable-log-management-new-relic.mdx
- src/nav/logs.yml
Add fastly and akamai instruction links to log forwarding section.
> Log nav additions

- src/@newrelic/gatsby-theme-newrelic/icons/feather.js
- src/components/AnimatedFeatherIcon.js
- src/components/TileSelect/TileCollapser.js
cayla saved the day with react spring!
> Fix collapser bug

- package.json
- src/components/InstallNextSteps.js
- src/pages/install/{installConfig.agentName}.js
- yarn.lock
- ~Get rid of feedback part of component??~ - my opinion was to keep the create an issue just in case a user gets blocked and doesn't scroll to the end of the page, at least they have a pathway to create an issue 
https://issues.newrelic.com/browse/NR-44518
> Page tools right sidebar with headings and contributing guidelines

- src/pages/install/{installConfig.agentName}.js
tessen categories need to be sentence case, some events were silently failing
> Tessen fix

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
just clarifying what happens to captured headers
> docs: allowAllHeaders apply to spans & transactions

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-4700.mdx
> New Relic for Android release notes v4.7.0

- src/content/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
This is a PR to fix the issues raised in GitHub issue #9105
> Remove duplicate redirect and remove link

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
> feat(logs): agent captures log message

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx
> chore(ai): added redirect

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
Tweaking content and layout for the O4G (nonprofit program) page for clarity
> Tweaking O4G Program Benefits section content and layout for clarity

- src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1219.mdx
This PR represents the changelog for Browser Agent v1219 Release Notes
> v1219 Release Notes

- src/content/docs/apm/distributed-tracing/trace-api/troubleshooting-missing-trace-api-data.mdx
I just made the queries prettier
> docs: add sql identifier to examples

- package.json
- src/@newrelic/gatsby-theme-newrelic/icons/logo/newrelic.js
- src/components/TechTile.js
- yarn.lock
> Update NR logo on Release Notes page

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
NR-39735. Slated to go out Sept 7 morning, but we should confirm that first.
> Sept 7 morning (prob): Add note about 60 days free support

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/violation-event-attributes.mdx
> no longer beta

- src/content/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api.mdx
Somehow a comment about indentation needing to be removed made it into the docs.
> Removed dev comment

- src/content/docs/accounts/original-accounts-billing/original-users-roles/user-migration.mdx
This is a PR to clarify why some migrated users might still see multiple accounts when they go to log in.
> Explain why multiple logins appear

- scripts/actions/fetch-and-deserialize.js
Reverts newrelic/docs-website#9169
> Revert "Temporarily ignore files missing from db"

- src/content/docs/style-guide/ui-writing/abbreviations-and-acronyms.mdx
- src/content/docs/style-guide/ui-writing/alert-status-language.mdx
- src/content/docs/style-guide/ui-writing/button-labels.mdx
- src/content/docs/style-guide/ui-writing/capitalization.mdx
- src/content/docs/style-guide/ui-writing/chart-names.mdx
- src/content/docs/style-guide/ui-writing/contractions.mdx
- src/content/docs/style-guide/ui-writing/emojis.mdx
- src/content/docs/style-guide/ui-writing/empty-states.mdx
- src/content/docs/style-guide/ui-writing/error-messages.mdx
- src/content/docs/style-guide/ui-writing/formatting.mdx
- src/content/docs/style-guide/ui-writing/links.mdx
- src/content/docs/style-guide/ui-writing/numbers-dates-and-times.mdx
- src/content/docs/style-guide/ui-writing/places-and-names.mdx
- src/content/docs/style-guide/ui-writing/plurals.mdx
- src/content/docs/style-guide/ui-writing/punctuation.mdx
- src/content/docs/style-guide/ui-writing/ranges-and-spans.mdx
- src/content/docs/style-guide/ui-writing/tooltips.mdx
- src/content/docs/style-guide/ui-writing/ui-writing-style.mdx
- src/content/docs/style-guide/ui-writing/units-of-measurement.mdx
- src/content/docs/style-guide/ui-writing/variables-and-placeholders.mdx
- src/nav/style-guide.yml
This brings in pages on UI writing style that are currently in the One Core style guide.
> style guide: Adding UI writing style

- src/content/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes.mdx
The lower bound limit was not correct as it stands today.
> fix(Metrics): Make lower bound cardinality limit accurate

- src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
> correct release date for 8.9.1

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/create-anomaly-alert-conditions.mdx
> chore(alerts): added redirect

- src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-004.mdx
Add release notes for react native release 0.0.4.
> Add release notes for react native release 0.0.4

- src/content/docs/release-notes/service-levels-release-notes/service-levels-20220909.mdx
> feat(rn): added release note

- src/content/docs/agile-handbook/appendices/backlog-review.mdx
- src/content/docs/agile-handbook/sprint-mechanics/meetings-and-ceremonies.mdx
- src/content/docs/agile-handbook/sprint-mechanics/planning-poker.mdx
> fix(agile handbook): Made scrum updates to the agile handbook

- src/content/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic.mdx
> fix(ui writing ): made changes requested

- src/content/docs/alerts-applied-intelligence/applied-intelligence/anomaly-detection/anomaly-detection-applied-intelligence.mdx
- src/content/docs/alerts-applied-intelligence/transition-guide.mdx
> fix(anomaly fix ): changed language and added a callout

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions.mdx
This PR adds a description table for NRAI correlation product's global decisions.
> Add description table for correlation global decisions

- src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx
Added example for multi instance config
> Feat(vSphere): Add multiple instance example

- src/content/docs/alerts-applied-intelligence/applied-intelligence/anomaly-detection/anomaly-detection-applied-intelligence.mdx
- src/content/docs/alerts-applied-intelligence/transition-guide.mdx
> fix(anomaly transition guide): edited transition guide

- src/content/docs/logs/ui-data/parsing.mdx
Updated the language in the doc to be more descriptive of what happens during the parsing phase as well as the syntax of the parsing clause.
> Updated json parsing verbiage

- src/content/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-alloydb-monitoring-integration.mdx
- src/content/docs/infrastructure/google-cloud-platform-integrations/get-started/gcp-integration-metrics.mdx
- src/nav/infrastructure.yml
Adding documentation for GCP AlloyDB integration
> AlloyDB documentation

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition.mdx
> fix(anomaly fix): fixed anomaly description

- src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
- src/content/docs/apm/agents/python-agent/web-frameworks-servers/hypercorn.mdx
- src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80100180.mdx
- src/nav/apm.yml
* Adds python agent release notes for v8.1.0.180.
* Adds documentation for Hypercorn, a newly supported ASGI web server.
> Add Python Agent Release v8.1.0.180

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
Updating EOL versions for .NET Agent 10.1.0
> docs: Update for release 10.1.0

- src/content/docs/accounts/accounts-billing/account-structure/new-relic-account-structure.mdx
- src/content/docs/new-relic-solutions/new-relic-one/install-configure/update-new-relic-agent.mdx
Adding additional reason about separating billing to add-account section
> fix(accounts): add reason to add account

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
Removing integration NumPy, as it's been removed from our roadmap
> feat(apm): removed numpy as a library per sme

- src/content/docs/style-guide/writing-docs/writer-workflow/github-history.mdx
Small formatting tweaks for consistency with style guide
> style(style guide): Formatting on GH history doc

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1291.mdx
Infra Agent 1.29.1 Release Notes
> Infra Agent 1.29.1 Release Notes

- src/content/docs/data-apis/ingest-apis/event-api/introduction-event-api.mdx
Was getting a 403 error and it took me some time to figure out that I was using a User Key vs the License Key that I needed to use. Proposing an update to the docs to make this more clear for the next person
> Update Events API Docs

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-0-3.mdx
Node.js Agent v9.0.3 Release Notes
> Node.js Agent v9.0.3 Release Notes

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-apprunner.mdx
- src/nav/infrastructure.yml
This creates an AWS Apprunner docs for NR-40620. 
Still a WIP
> chore(infra):Create AWS Apprunner doc

- src/content/whats-new/2022/09/whats-new-9-14-historical-data-exports.md
* Compliance needs as well data warehousing
* Historical Data Exports is released on 9-14-2022
> Sept 14 - feat(whats-new): add historical data exports

- src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4040.mdx
Adds in new release notes for the New Relic iOS mobile application.
> docs: add in release notes for NR mobile iOS 4.4.0

- src/content/docs/infrastructure/host-integrations/host-integrations-list/haproxy-monitoring-integration.mdx
Mis-formatted link reported in https://issues.newrelic.com/browse/NEWRELIC-3195
> chore(OHI): Fix broken link from NEWRELIC-3195

- src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-managing-users.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
- src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide.mdx
- src/content/docs/service-level-management/create-slm.mdx
- src/content/docs/service-level-management/faqs-slm.mdx
- src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
- src/nav/accounts.yml
Clarifications to login problems 'multiple accounts' issue
Adding link to OM SLM guide from SLM docs
> Assorted small changes sept 13

- src/content/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings.mdx
> fix: replace ticket with case

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-sys-dist.mdx
- src/nav/infrastructure.yml
> fix: rename agent tile and move doc

- src/components/InstallFeedback.js
- src/components/InstallNextSteps.js
- src/components/MDXContainer.js
- src/install/java/whatsNext.mdx
- src/pages/install/{installConfig.agentName}.js
* Changes `TabsPage` to `TabsPageItem`
* Fixes coloring of troubleshooting link and adds link to mdx file
* Fixes wrapping of feedback thumbsup / thumsbdown
> Various install page ui fixes 

- src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx
> update browser releases - NR-49242

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/view-simple-scripted-monitor-results.mdx
Take Screenshot URL was broken, updated to fix.
> Updated the take screenshot URL

- src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx
Updating EOL, given the new release.
> chore(Java): EOL versions

- src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3066.mdx
These are the release notes for our CPM release
This tells users what changes our updated version has
> feat: Release notes for private minion 3.0.66

- src/content/docs/mlops/integrations/dagshub-mlops-integration.mdx
> fix(dagshub): added link

- src/content/whats-new/2022/09/whats-new-09-16-ui-default-on-30day.md
Publish Date and Time: 09/16 morning
I am a PMM, this post does not need review by a PMM.
> 9/16-AM: "What's new" new ui "default-on" 30 day notice

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-maintenance-monitoring.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/troubleshoot-private-locations.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
- src/nav/synthetics.yml
Adding initial documentation for synthetics job manager while working with @akristen. **Do not merge yet.** A few additional adjustments will be needed at launch.
> feat(Synthetics job manager): Initial docs

- src/content/docs/mobile-monitoring/new-relic-mobile-ios/installation/spm-installation.mdx
Adds troubleshooting section to SPM installation docs for iOS Agent.
> NR-50152: iOS SPM Troubleshooting section added

- src/nav/synthetics.yml
> synthetics yml moves

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-maintenance-monitoring.mdx
- minor fix to newly released docs page
> Remove "replace me" comment

- src/content/docs/new-relic-solutions/get-started/implementation-guide-instrument.mdx
Adding something to implementation guide.
> fix(impl guide): browser edits

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- set name to synthetics job manager
- remove use of "customer"
- fix spacing
> Naming and wording fixes

- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Just updated the title of the drop down to explicitly show the example is for AWS RDS/Aurora and Azure Flexible instances.
> Updated AWS/Azure Wording

- src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-005.mdx
Release Notes for React Native Agent 0.0.5
> Adding Release Notes for React Native Agent 0.0.5

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Instance level database section was outdated.
> Clean up out of sync versions for database

- src/content/docs/style-guide/writing-docs/writer-workflow/github-troubleshooting.mdx
> feat(style): Minor header fix

- src/content/docs/new-relic-solutions/get-started/implementation-guide-alerting-proactive-solutions.mdx
Adding an example table showing how one might plan out alerting notifications
> fix(onboarding): alert table

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Added instructions and a sample file for mysql as well as updated the equivalent postresql wording to match the mysql directions so that they're both explicit in what's required.
> Added MySQL Azure and AWS instructions

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- Fixing broken link to the job manager configuration page 
- Updating additional link to remove reliance on a redirect
> fix(job manager): Broken links

- src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/new-gcp-alloydb-integrations.mdx
Adding the contents of #9159 to the release notes
> AlloyDB to release notes

- src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8101.mdx
> fix: incorrect date

- src/content/docs/accounts/accounts-billing/account-setup/choose-your-data-center.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/eligibility-guidelines-new-relic-nonprofit-program.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
- src/content/docs/accounts/accounts/account-maintenance/change-passwords-user-preferences.mdx
- src/content/docs/accounts/accounts/account-maintenance/set-session-timeouts.mdx
- src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
- src/content/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration.mdx
- src/content/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management.mdx
- src/content/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing.mdx
- src/content/docs/errors-inbox/error-external-services.mdx
- src/content/docs/instrumentation-editor-instrument-net-ui.mdx
A few small changes, some replacements of 'New Relic's', a couple other things
> Assorted small changes sept 21

- scripts/actions/fetch-and-deserialize.js
Reverts newrelic/docs-website#9411
> Revert "Temporary file ignore list"

- src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration.mdx
> Added support for Tanzu Application Service v2.13.

- src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-maintenance-monitoring.mdx
- src/content/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations.mdx
Fixed additional broken links for job manager related documentation
> fix(job manager): Fixed additional broken links

- src/content/docs/new-relic-solutions/new-relic-one/ui-data/maps-in-context.mdx
Microsoft style guide says to capitalize the first letter of any list following a colon.
> feat(maps): style guide grammar edits

- src/content/docs/accounts/accounts-billing/general-account-settings/intro-account-settings.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/billing-ui.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
- src/content/docs/accounts/original-accounts-billing/original-product-based-pricing/overview-pricing-models.mdx
- src/content/docs/new-relic-solutions/get-started/glossary.mdx
- src/nav/accounts.yml
Flattened billing nav and restructured some docs and retitled some docs, for simplicity.
> fix(pricing): assorted fixes

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-1-0.mdx
Node.js Agent v9.1.0 Release Notes
> Node.js Agent v9.1.0 Release Notes

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/apm-metric-alert-conditions.mdx
> remove duplicate line

- src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx
Ready to be reviewed, but to be **merged we should wait** for https://github.com/newrelic/newrelic-prometheus-exporters-packages/pull/110 since the name of the parameter could still change
Moreover, there are few changes than it seems, it is simply moving two sections around
> feat(ibmmq): mTLS support

- src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/synthetic-monitoring-best-practices-guide.mdx
- Take advantage of features of our new runtime on Chrome 100+
> Update scripted browser example to use async/await

- src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/powerdns-monitoring-integration.mdx
> Fix ibmmq readme and IDs of collapsers

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
> Docs: add minimum version for logs in context

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
Do not merge - working with @akristen 
Added K8s sizing description.
> feat(job manager): Added K8s sizing details

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot.mdx
> fix: removed inaccurate wording

- src/content/docs/agile-handbook/heroing/what-is-a-hero.mdx
Draft info for our new user feedback triage/routing process
> feat: draft user feedback triage info

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- src/content/docs/synthetics/synthetic-monitoring/troubleshooting/runtime-upgrade-troubleshooting.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/new-runtime.mdx
- src/nav/synthetics.yml
Added a troubleshooting doc to address common confusions and errors for synthetics runtime upgrades.
> feat(runtime troubleshooting): Synthetics runtime troubleshooting

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
> Tiny wording change to match new terminology

- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-custom-instrumentation-annotation-example-app.mdx
it won't work for the first example because of the hyperlinks
> docs: add java lang identifier

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1300.mdx
Infra Agent 1.30.0 Release Notes
> Infra Agent 1.30.0 Release Notes

- src/content/docs/style-guide/ui-writing/numbers-dates-and-times.mdx
This applies to the UI writing style.
> Fix to style guide: update date and time

- src/content/docs/service-level-management/alerts-slm.mdx
> fix: wrap math in code

- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-instrumenting-example-app-external-datastore-calls-dt.mdx
I also corrected the indentation which was wonky from cutting/pasting the doc together
> docs: add lang identifiers to example code

- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
docs:  Correct URL link for agents and integrations here https://docs.newrelic.com/docs/infrastructure/host-integrations/get-started/introduction-host-integrations/
> Correct URL for agent integrations

- src/content/docs/browser/new-relic-browser/browser-agent-spa-api/createtracer-browser-spa-api.mdx
> feat(browser): edit according to UI

- src/content/docs/apm/agents/python-agent/supported-features/python-graphQL.mdx
> docs: add graphql lang identifiers

- src/content/docs/apm/agents/net-agent/custom-instrumentation/add-detail-transactions-xml-net.mdx
> docs: format code & add lang identifiers

- src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3067.mdx
Adds release notes for the most recent CPM release
> chore: add release notes for minion release 3.0.67

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1310.mdx
* Infra Agent 1.31.0 Release Notes
* Added header to 1.30.0 release notes
> Infra Agent 1.31.0 Release Notes

- src/content/docs/apm/agents/net-agent/configuration/name-your-net-application.mdx
app.config, web.config and newrelic.config are usually case sensitive file names, so I updated them in the headers (which I'm sure didn't bother anyone but me). Since I was here I added the xml language identifiers to make the code more readable.
> docs: lowercase file names & add land identifiers

- src/content/docs/apm/agents/go-agent/installation/install-new-relic-go.mdx
- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup.mdx
> fix(APM): fixed golang version & typo

- src/content/docs/infrastructure/host-integrations/host-integrations-list/f5-monitoring-integration.mdx
> chore(F5): fixed broken link

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Needed to add additional install procedures to get the dashboard for ADO.NET. I've added a table as a temporary(?) fix.
> RELEASE: 9/30; ADO.net and C# integration

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Reverts newrelic/docs-website#9460. Rolling back some changes due to product not being ready.
> Revert "RELEASE: 9/30; ADO.net and C# integration"

- src/content/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration.mdx
Ibmmq passwordLess authentication
> feat(ibmmq): passwordless authentication

- src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx
> feat(OHI): removed troubleshooting section

- src/install/config/java.yaml
The old step 6 wasn't valid for Docker, so I updated the YAML file to remove it.
> fix(java): removed weird step from Docker

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx
- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-2-0-314.mdx
Updates for the PHP agent v10.2.0:
* Add 'PHP agent v10.2.0' release notes
* Update PHP agent EOL policy
> PHP agent release 10.2.0 (Maybe publish October 3rd or 4th?)

- gatsby-config.js
- package.json
- plugins/gatsby-source-nav/gatsby-node.js
- src/@newrelic/gatsby-theme-newrelic/components/NavItem.js
- src/components/RootNavigation.js
- src/layouts/MainLayout.js
- src/nav/new-relic-solutions.yml
- src/nav/root.yml
- src/pages/index.js
- yarn.lock
This includes a theme update and updates the general design but not the hierarchy of the nav items themselves
> Update nav design pt. 1

- src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
Some issues fixed reported by SMEs, and also attempt to fix this https://github.com/newrelic/docs-website/issues/8578
> fix(logs tcp): fixing errors

- src/content/docs/apm/agents/net-agent/custom-instrumentation/query-naming.mdx
> docs: add csharp lang identifier

- src/content/docs/alerts-applied-intelligence/overview.mdx
Based on updates across NR AIOps docs, this paragraph was requested to be moved to this page by Shachar because it is currently on the "Getting Started with Incident Intelligence" page, which will be removed completely.
> Add EU info to Intro

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions.mdx
Based on updates across NR AIOps docs, this paragraph was requested to be moved to this page by Shachar because it is currently on the "Getting Started with Incident Intelligence" page, which will be removed completely.
> Add sources to this page

- src/content/docs/logs/ui-data/use-logs-ui.mdx
added a section on the features we allow access to for basic users. This question comes up consistently so wanted to document the basic user capabilities.
> Added Logs UI Permissions

- scripts/verifyInstallPage.js
Now verifies that step and override filePaths actually point to real files and that overrides always have a selectedOptions key
> Add more checks to script

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/monitor-limits.mdx
Added multiple example queries for the NrDailyUsage event to help customers view their synthetics usage.
> feat(synthetics usage): Added queries to view synthetics consumption

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
> docs: fix two broken otel links

- src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
- src/content/docs/apm/agents/go-agent/instrumentation/go-agent-code-level-metrics-instrument.mdx
Documents additions to the Go Agent's code-level metrics to include caching functionality that will be introduced at the next release. Also describes other minor improvements introduced to the agent's CLM support.
> Feat(Go agent) document new caching clm features

- src/nav/synthetics.yml
Quick wins in the synthetics nav xo
> Minor changes to synth nav

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Reverts newrelic/docs-website#9574 so that I can merge ADO.Net doc and make it live
> Revert "Revert "RELEASE: 9/30; ADO.net and C# integration""

- gatsby-config.js
- package.json
- src/pages/attribute-dictionary.js
- src/templates/docPage.js
- yarn.lock
replaces simplefeedback component with complexfeedback
> Add complex feedback

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-2-0.mdx
Add release notes for the .Net agent v10.2.0 .
> Add release notes for the .Net agent v10.2.0 .

- src/content/whats-new/2022/09/Nerdgraph-org-user-mgmt_2022-10-06
- src/content/whats-new/2022/09/whats-new-09-30-nerdgraph-org-user-mgmt.md
Announcing new NerdGraph org and user management functionalities. Please backdate this to September 30th to match other related comms. I am a PMM, so this post does not require PMM review. Thank you!
> What's new: nerdgraph org user mgmt update

- src/i18n/translations/jp/translation.json
Updated strings for JP home page. related to https://github.com/newrelic/docs-website/issues/9673
> Update JP JSON

- src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-2-0.mdx
Node.js Agent v9.2.0 Release Notes
> Node.js Agent v9.2.0 Release Notes

- src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220.mdx
Release notes for [v1220](https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1220) of Browser Agent
> Browser Agent v1220 release notes

- src/data/whats-new-ids.json
> Daily release/oct 7  2022 9 10

- src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx
- Add troubleshooting steps for common issue due to two integrations.
- Include query we use to determine if a Lambda function is instrumented.
- Include links to relevant docs and resources.
> Lambda function not instrumented

- src/content/docs/style-guide/writing-docs/article-templates/prometheus-template
- src/content/docs/style-guide/writing-docs/article-templates/prometheus-template.mdx
- src/nav/style-guide.yml
Adding a template for the 16 Prometheus new integrations.
> feat(Prometheus template): Adding a template

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/Issues-and-Incident-management-and-response.mdx
- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence.mdx
- src/nav/alerts-and-applied-intelligence.yml
We need to restore this so that we can figure out the best way to move forward with this doc, even though it's out of date.
> Restore old get started with incident intelligence doc

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/billing-ui.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
Some small edits to usage/billing doc.
> fix(user count): clarify usage

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
Added the line "...and data retention" to the Billing Administration setting
> Added "and data retention" to Billing

- src/content/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container.mdx
> fix(.net docker): improvements

- src/content/docs/apm/agents/net-agent/net-agent-api/ignore-apdex.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/ignore-transaction.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/incrementcounter-net-agent-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/recordcustomevent-net-agent-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/recordmetric-net-agent-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/recordresponsetimemetric-net-agent-api.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/set-application-name.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/set-transaction-uri.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/set-user-parameters.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/start-agent.mdx
- src/content/docs/apm/agents/net-agent/net-agent-api/tracemetadata-net-agent-api-0.mdx
Add syntax highlighting to .NET API code, for better readability.
> docs: Add syntax highlighting to .NET API code

- scripts/actions/fetch-and-deserialize.js
Reverts newrelic/docs-website#9704
> Revert "Temp ignore files deleted from DB"

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
these ignore rules are confusing so I added the actual default values from the `default.js`, to hopefully clarify how to use this field.
> docs: added the literal default values

- src/content/docs/apm/agents/net-agent/troubleshooting/azure-pipelines-wipes-out-newrelicazurewebsitesextension-directories.mdx
> adocs: put code in a block for readability

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Clarify JS capitalization since this is often wrong.
> style(style guide): JavaScript capitalization

- src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-006.mdx
React Native release 0.0.6 release notes
> Added React Native Release notes for 0.0.6

- src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
https://github.com/newrelic/docs-website/issues/9611 update from this
> chore(content): removed broken link

- src/components/NavFooter.js
- src/components/RootNavigation.js
- src/layouts/MainLayout.js
- src/nav/root.yml
https://user-images.githubusercontent.com/26727669/195189987-c6784c87-af23-4e55-860b-58fff9c1990c.mov
Creates the sticky nav footer, video shows the various states, styles, and functionality.
> Sticky Nav Footer Component

- gatsby-config.js
- package.json
- src/@newrelic/gatsby-theme-newrelic/components/NavItem.js
- src/components/NavFooter.js
- src/components/RootNavigation.js
- src/layouts/MainLayout.js
- yarn.lock
scales back the width and makes the nav scroll to the current page on load
> Nav updates

- src/content/docs/accounts/accounts/automated-user-management/automated-user-provisioning-single-sign.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
liaison work: updating AUM doc about identity provider `suspended` state.
> fix(aum): add `suspended` note

- scripts/actions/fetch-and-deserialize.js
accidentally deleted this file from HT yesterday while fixing machine translation so now it needs to be ignored
> Ignore file deleted from db

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
- src/content/docs/accounts/original-accounts-billing/original-data-retention/event-data-retention-original-pricing-plan.mdx
- src/content/docs/licenses/license-information/faq/new-relic-one-pricing-plan-frequently-asked-questions.mdx
- src/content/docs/licenses/license-information/usage-plans/new-relic-one-usage-plan-descriptions.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
liaison work related to updating license docs with fact that apof is deprecated.
> fix(usage plan): edits re: APOF

- src/install/config/java.yaml
- src/install/java/agentConfig.mdx
- src/install/java/frameworkInstallation/default.mdx
- src/install/java/frameworkInstallation/jetty.mdx
- src/install/java/license.mdx
- src/install/java/whatsNext.mdx
Making some tweaks and improvements.
> Updates to Java branching doc (NR-56333)

- src/i18n/translations/en/translation.json
- src/pages/index.js
Simple swap of data dictionary for Java install on homepage, to see if we generate more clicks/traffic/usage of new Java install page.
> test(homepage): Swap data dict for Java install

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
> Spelling correction

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
based on feedgback in https://github.com/newrelic/docs-website/issues/9781
> fix(nrql): add alert mentions

- src/content/whats-new/2022/10/whats-new-10-13-nrql-productivity-improvements.md
Missing subtitle/summary on the post
> Add summary to What's New post on NRQL variables, etc.

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-view-your-data.mdx
Improved descriptions of what you can do with each UI page.
Included an overall statement on how we use semantic conventions to power the UIs, so users can understand why data might not be showing up as expected.
> Note semantic conventions, tweak page descriptions

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1320.mdx
Clone of https://github.com/newrelic/docs-website/pull/9775
> fix(infra release): 1.32.0

- scripts/actions/fetch-and-deserialize.js
Reverts newrelic/docs-website#9755
> Revert "Ignore file deleted from db"

- src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
Puma 6 was recently released, which the Ruby agent supports. Updating documentation.
> Ruby agent supports Puma 6

- src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
> docs: +lang identifiers and code in backticks

- src/content/docs/release-notes/mobile-release-notes/react-native-release-notes/react-native-agent-007.mdx
Release notes for hotfix for react native agent 0.0.7.
> release notes for react-native-agent 0.0.7

- src/content/docs/logs/ui-data/parsing.mdx
> fix(parsing): update definition

- src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
- src/data-dictionary/events/SyntheticsPrivateLocationStatus/checksPending.md
- src/data-dictionary/events/SyntheticsPrivateLocationStatus/jobManagerHeavyweightJobs.md
- src/data-dictionary/events/SyntheticsPrivateLocationStatus/minionHeavyweightJobs.md
- src/data-dictionary/events/SyntheticsPrivateLocationStatus/pingJobs.md
- Added new SyntheticsPrivateLocationStatus attributes to the data dictionary
- Clarified checksPending attribute on the SyntheticsPrivateLocationStatus event in the data dictionary
- Added new SyntheticsPrivateLocationStatus attributes to the private location monitoring doc
> feat(checksPending): Explained new attributes

- src/content/whats-new/2022/10/whats-new-10-17-new-ui-ga.md
Date & time to post: 10/17 Morning
Users will log on Monday (10/17) to a new UI (starting 5:30am PST), so it's really important this goes out as early as possible on Monday morning! Thanks!
I'm a PMM, this post does not need PMM review :)
> feat(whats-new): new ui GA (Publish morning 10/17)

- src/content/docs/apm/agents/java-agent/configuration/java-agent-error-configuration.mdx
The removed apis can not be configured as expected.
> Correct expected errors behavior

- src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-app-launch-time-android-apps.mdx
* What problems does this PR solve?  - doc enhancement
> Authorities need to be unique

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-3-0.mdx
Node.js Agent v9.3.0 Release Notes
> Node.js Agent v9.3.0 Release Notes

- src/content/docs/style-guide/ui-writing/variables-and-placeholders.mdx
Added some info about placeholders as per UI writing team decision.
> improvement, style guide, UI copy info

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx
Added mysql windows log template steps to enable.
> Added mysql windows log template

- src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
This doc entry is for the new windows rabbitmq logging template file.
> Rabbitmq Windows logging template docs

- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
> fix(node agent): syntax error

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Just for this week. Next week will be 3000.
> fix(node agent): custom event limit back to 1000

- src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/diagnostics-beginner-guide.mdx
Some more edit to the RED guide
> fix(OM RED): some edits

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot.mdx
> docs: added validation step for console logs

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-transactions-page.mdx
Update the page's docs for this release: https://docs.newrelic.com/whats-new/2022/10/whats-new-otel-txn-metrics
> Metrics support in Transactions

- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-mysql-flexible-server-monitoring-integration.mdx
- src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-postgresql-flexible-server-monitoring-integration.mdx
- src/nav/infrastructure.yml
* It adds doc for a new upcoming integration for Azure Flexible database metrics from the Cloud Integrations team. 
* See original doc for Flexible servers from Azure here https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview.
* The feature isn't GA yet. Talk to me on slack for coordination on when to merge pls 🥺
* Original doc for the metrics from Azure is available here https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftdbformysqlfle …
> feat(Azure Flexible Databases): added doc for new integration to Flexible type Azure databases

- src/nav/root.yml
Zach making some structural changes to root nav for experimental purposes, see how it looks
> fix(root): structure edit to root nav

- src/content/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring.mdx
* What problems does this PR solve? Updates incomplete instructions for adding IAM roles.
> Update to Infra docs explaining Integration

- src/content/docs/style-guide/images/embed-images.mdx
- src/content/docs/style-guide/images/screenshots-images.mdx
Adds clearer image naming conventions.
> feat(style guide): Add image naming conventions

- src/content/whats-new/2022/10/whats-new-10-20-VM-Public-Preview-Tiral.md
New Relic vulnerability management public preview 90-day free trial now available. Access actionable security insights alongside your telemetry data with no additional configuration.
* What problems does this PR solve? Announce a new product feature
links to related docs, screenshots, etc.? https://newrelic.com/blog/nerdlog/vulnerability-management-public-preview
> whats-new-10-20-VM-Public-Preview-Tiral

- src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/scripted-browser-examples.mdx
Addressing https://github.com/newrelic/docs-website/issues/9614
> feat(content) update old link per 9614

- src/content/docs/vulnerability-management/integrations/intro.mdx
> chore(vm): add io links to tiles

- src/content/docs/release-notes/mobile-release-notes/xcframework-release-notes/xcframework-agent-740.mdx
Added release notes for iOS XCFramework Agent 7.4.0
> Added release notes for version 7.4.0

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-database-page.mdx
More "what can I do?" language, to include links to traces. More clear description of required attributes' relationship to OTel spec, and formatting consistent with other recent doc updates.
> Databases: More about what you can do

- src/content/docs/vulnerability-management/overview.mdx
> fix(vm): update user reqs

- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
@a-sassman caught this bolded colon and I fixed it
> fix(intro): unbolded colon in first bullet

- src/i18n/translations/en/translation.json
- src/nav/root.yml
Tweaks homepage to say 500+ quickstarts instead of 470+
> chore(homepage): We have 500 quickstarts now!

- src/content/docs/licenses/license-information/other-licenses/services-licenses.mdx
Update the documentation license page with the geoip2 library being used.
> Update license page with geoip2 library

- src/nav/accounts.yml
- src/nav/alerts-and-applied-intelligence.yml
- src/nav/apm.yml
- src/nav/browser.yml
- src/nav/codestream.yml
- src/nav/dashboards.yml
- src/nav/distributed-tracing.yml
- src/nav/infrastructure.yml
- src/nav/integrations.yml
- src/nav/kubernetes-pixie.yml
- src/nav/new-relic-partnerships.yml
- src/nav/serverless-function-monitoring.yml
- src/nav/synthetics.yml
- src/nav/telemetry-data-platform.yml
I have decided it is time for consistency on this. Apologies to @zuluecho9 b/c I know this will cause you pain.
> style(nav): `Intro` to `Introduction` everywhere

- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
> Fixed typos and minor updates for clarity

- src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/azure-flex-database-integration.mdx
* It adds an entry in https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/ to announce availability of new Azure PostreSQL and MySQL flexible servers
* This feature is already GA. Documentation for PostgreSQL flexible server is [here](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-database-postgresql-flexible-server-monitoring-integration/), and for MySQL flexible server is …
> Added release note for Azure PostgreSQL and MySQL flex server integrations

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx
Removed Atlas support due new requirements we won't support until new version is released.
> Removed MongoDB Atlas support

- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
> Fixing some spelling issues

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-api/intro-alerts-api.mdx
- src/content/docs/codestream/start-here/what-is-codestream.mdx
- src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api.mdx
Follow-up to #9949 , I forgot to address titles in frontmatter
> chore(titles): Change `Intro` to `Introduction`

- src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration.mdx
> Added support for Tanzu Application Service v3.0.

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
Added some notes on a possible error that users might see when running the command from step 5.
> Add note about pod security policies issue

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
> chore(logs): Remove old video and related copy

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries.mdx
> fix(nrql): changed timing

- src/content/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction.mdx
> chore(apm): update browser Apdex mentions

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Closes #1639
Confirmed in https://pkg.go.dev/github.com/newrelic/infrastructure-agent/pkg/config
> fix(infra): fix plugin name

- src/content/docs/apm/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api.mdx
- src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
- src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
We have merged a new API for forwarding logs, so let's document it more!
* https://github.com/newrelic/node-newrelic/pull/1380
> Node.js agent log forwarding API

- src/content/docs/apm/agents/ruby-agent/attributes/ruby-attribute-examples.mdx
> fix(ruby): Address GH issue #2567

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot.mdx
fix: typo Consigure -> Configure
> fix: typo on opentelemetry jenkins monitoring page

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows.mdx
In this edit, I've added a section to clarify how workflows are triggered alongside a table with different examples of what happens when evens specific type of events trigger. The original doc with information can be found here https://docs.google.com/document/d/17NEVQUBKtj1JqtbdeO7mxCW_I2qyEP826mLjGi4tNio/edit
> Workflow trigger table addition

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts.mdx
> Fix policy name character limit

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/manage-your-agent/infrastructure-agent-behavior.mdx
Added the new logging retry variable to the configuration settings page and also to the agent behavior page.
> Added logging retry to config

- src/data-dictionary/events/SystemSample/memoryBuffers.md
- src/data-dictionary/events/SystemSample/memoryKernelFree.md
Added new memory metrics to Infra Agent
> NEWRELIC-4300 Infra Agent: Added new memory metrics

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
- src/data-dictionary/events/SystemSample/ntpOffset.md
Added new metric to the Infra Agent.
* config option
* metric description
> NEWRELIC-3025 Infra Agent: Added ntp metric

- package.json
- scripts/validate-install/schema.js
- scripts/verifyInstallPage.js
- yarn.lock
Using [superstruct](https://docs.superstructjs.org/) in order to validate the types
```
yarn verify-install-page java
```
> Validate install yaml

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updating compatible versions for some .NET Agent frameworks after our latest round of testing updates.
> .NET Agent compatibility updates

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-5-0.mdx
Node.js Agent v9.5.0 Release Notes
> Node.js Agent v9.5.0 Release Notes

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql.mdx
> fix: Arrays are now supported with uniques(), uniqueCount(), and latest()

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
> fix(removed Laravel): removed EOL framework

- src/content/docs/logs/forward-logs/cloudflare-logpush-forwarding.mdx
Customers need to add an API key each Cloudflare zone in a multi zone setup.
https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#keys-ui
> Clarify Important note about Cloudflare zones

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-1163.mdx
- src/content/docs/style-guide/writing-docs/writer-workflow/tech-writer-workflow.mdx
Fixes a few small contraction issues I ran into while reading our style guide
> fix(style): small contraction pass

- src/nav/new-relic-security.yml
Now that we have a security offering, we need to ensure consistent language around our data security vs security capabilities
> chore(security): update left hand title for category

- src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
Adds vulnerability management to the style guide
> chore(style): add vulnerability management to style guide

- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-3-0.mdx
Add release notes for .NET Agent v10.3.0
> Add release notes for .NET Agent v10.3.0

- src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
add 9.3.0, 9.4.0, 9.5.0, and remove out of support releases
> update node.js eol table

- src/content/docs/vulnerability-management/integrations/security-data-api.mdx
> fix(vm): through typo

- src/content/docs/vulnerability-management/dev-workflow.mdx
> fix(vm): vuln typo

- src/content/docs/synthetics/synthetic-monitoring/administration/compare-page-load-performance-browser-synthetic-monitoring.mdx
> docs: format the javascript +language identifiers to code

- src/content/docs/browser/new-relic-browser/configuration/filter-ajax-request-events.mdx
> docs: add sql syntax hightlighting

- src/content/docs/apm/agents/manage-apm-agents/app-naming/use-multiple-names-app.mdx
> docs: add language identifiers to configs

- src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx
- formulae to help obtain baseline values
- describe relationship between these settings and effects on running non-ping jobs
> Add completions and parallelism formulae

- src/content/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent.mdx
This PR updates the Python agent compatibility docs with Python version and agent support information.
> Update Python agent compatibility docs.

- src/nav/licenses.yml
> fix(license): add VM doc to licenses taxonomy

- src/content/docs/style-guide/writing-docs/writer-workflow/useful-scripts.mdx
- src/nav/style-guide.yml
I thought it would be helpful to document these useful scripts in one place.
> The useful scripts what our lovely engineering team has made for us

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts.mdx
This doc is fairly old, and the values (and some table entries) will need to be revisited within the next quarter or two.
> Update targets limit

- src/content/docs/agile-handbook/sprint-mechanics/planning-poker.mdx
I couldn't handle not following Fibonnaci for one number
> chore(agile handbook): 20 to 21

- src/content/docs/apis/nerdgraph/examples/nerdgraph-api-workflows.mdx
> Add Copy workflow id button to docs

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1331.mdx
Infra Agent 1.32.0 Release Notes
> docs: added release notes for infrastructure-agent 1.33.1

- src/content/docs/vulnerability-management/security-workflow.mdx
Fixes a repeated image in a doc
> fix(VM): fix repeated image

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
- src/nav/style-guide.yml
Fixed a couple broken links and removed a duplicate nav item
> Minor style guide fixes

- src/content/docs/logs/logs-context/configure-logs-context-go.mdx
- src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-0.mdx
> go agent v3.20.0 release

- src/content/docs/vulnerability-management/dev-workflow.mdx
- src/content/docs/vulnerability-management/integrations/aws.mdx
- src/content/docs/vulnerability-management/integrations/intro.mdx
- src/content/docs/vulnerability-management/security-workflow.mdx
Implements various feedback from @austin-schaefer
> fix(vm): various peer feedback

- .github/auto_assign.yml
> feat(workflow): add BCN writers to auto review action

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
originated with https://github.com/newrelic/docs-website/issues/10153
> fix(saml support): remove links

- src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx
- src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
- src/content/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model.mdx
- src/content/docs/licenses/license-information/faq/new-relic-one-pricing-plan-frequently-asked-questions.mdx
Liaison work involving: 
Move the sessions/IP-address limit to 'Factors affecting access' doc
Restructure that doc a little bit
Point to that limit from a couple other docs
> Clarify session/IP limits and move to better location

- src/content/docs/accounts/accounts-billing/account-structure/factors-affecting-access-features-data.mdx
- src/nav/accounts.yml
fixing a wrong format header, and some minor other stuff while at it
> fix(factors access): fixing header

- gatsby-config.js
- package.json
- yarn.lock
Adds some tessen updates from the theme, updates recaptcha for the feedback service to use the correct client side token.
> fix: bump theme, update recaptcha env var

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
The Node.js agent didn't have feature parity between configuration values and env vars for those configuration values. We now do.  I also added some explanation around complex data types as env vars.
[Agent PR](https://github.com/newrelic/node-newrelic/pull/1399)
> Updated Node.js env vars

- src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3068.mdx
> chore: add release notes for minion release 3.0.68

- src/nav/alerts-applied-intelligence.yml
> fix(alerts): removing doc from nav to hide it from users

- src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
* What problems does this PR solve? - Update EOL for android agent
> [NR-63304] EOL updates for android

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1330.mdx
- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1331.mdx
- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1332.mdx
Fixes https://issues.newrelic.com/browse/NEWRELIC-4834
> chore(infra release notes): Broken update links

- src/content/docs/agile-handbook/heroing/what-is-a-hero.mdx
preview: https://docswebsitedevelop-austinschaeferpatch619641.gtsb.io/docs/agile-handbook/heroing/what-is-a-hero/#route-and-triage-user-feedback
> chore(agile handbook): Fix indent issue

- src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
* Updates Python Agent EOL page with new version releases, and removes old version.
> Python Agent EOL Updates

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx
- src/content/docs/apm/agents/c-sdk/get-started/otel_cpp_example.mdx
- src/content/docs/apm/agents/manage-apm-agents/agent-data/real-time-streaming.mdx
- src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-vm-measurements.mdx
- src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide.mdx
- src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-one.mdx
- src/content/docs/new-relic-solutions/new-relic-one/ui-data/basic-ui-features.mdx
- src/content/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data.mdx
- src/content/docs/query-your-data/explore-query-data/query-builder/use-advanced-promql-style-mode-query-data.mdx
- src/content/whats-new/2021/06/extract-data-regex.md
Fixes weird pathing reported in https://issues.newrelic.com/browse/NR-51303
> chore(pathing): Old "query your data" pathing

- src/content/docs/infrastructure/prometheus-integrations/troubleshooting/compare-rw-data-sent-billed-bytes.mdx
The function is bytecountestimate not bytescountestimate
> Fix bytecountestimate typo

- src/content/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent.mdx
Fixes https://issues.newrelic.com/browse/NR-39797
> chore(ruby): Fix config file step (NR-39797)

- src/content/docs/licenses/license-information/usage-plans/new-relic-one-usage-plan-descriptions.mdx
- src/content/docs/synthetics/synthetic-monitoring/using-monitors/monitor-limits.mdx
liaison work: update synth price/rules
> Update synth price and details

- src/content/docs/accounts/accounts-billing/account-setup/multiple-logins-found.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
liaison work: 
clarify that user mgmt roles are additive, and
Add a sentence about the new user record switcher and how it makes you reauthenticate to NR
> fix(roles): clarify they're additive

- src/nav/accounts.yml
- src/nav/alerts-applied-intelligence.yml
- src/nav/apm.yml
- src/nav/browser.yml
- src/nav/codestream.yml
- src/nav/distributed-tracing.yml
- src/nav/infrastructure.yml
- src/nav/kubernetes-pixie.yml
- src/nav/logs.yml
- src/nav/mlops.yml
- src/nav/mobile-monitoring.yml
- src/nav/serverless-function-monitoring.yml
- src/nav/synthetics.yml
Attempt to make some nav stuff less nested, especially in the beginning areas of the navs
> fix(navs): flattening some stuff

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
Added support for deb/rpm installs and split requirements for Docker and host-based installs
Updating network flows deployment requirements for host-based installs
> Updated deployment & security requirements

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
Update for host-based ktranslate for Network Syslogs
> Update requirements for host-based install

- src/content/docs/accounts/accounts-billing/general-account-settings/intro-account-settings.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
> fix(user mgmt): add detail to 'add users'

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-6-0.mdx
Node.js Agent v9.6.0 Release Notes
> Node.js Agent v9.6.0 Release Notes

- src/content/docs/security/security-privacy/compliance/hipaa-readiness-new-relic.mdx
Reorganized some sections, added clarifications
> Continuity updates

- src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
Updated the [FILTER] example in the doc to add some more uses cases
> Updated FB FILTER section

- src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx
- src/nav/infrastructure.yml
Adds a new doc written by @4demos
> Lambda telemetry extension for aws

- src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx
> fix(streaming data): add aws procedure

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/specify-when-alerts-create-incidents.mdx
Changed a couple of terms to the new ones (violation/incident, incident preference/issue preference)
> Clean up terminology

- src/content/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic.mdx
fixing repeated instance of 'transparent'
> (chore)Style Guide: voice strategies typo fix

- src/content/docs/service-level-management/create-slm.mdx
Work done: 
Based on feedback in https://github.com/newrelic/docs-website/issues/8684, clarifying that service levels only work for a specific account in a multi-account org.
> fix(workloads): clarify single-account fxnality

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-0.mdx
Node.js Agent v9.7.0 Release Notes
> Node.js Agent v9.7.0 Release Notes

- src/content/docs/apm/agents/python-agent/supported-features/python-event-loop-diagnostics.mdx
- src/content/docs/apm/apm-ui-pages/monitoring/kubernetes-summary-page.mdx
- src/content/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-apps-summary-page.mdx
- src/content/docs/vulnerability-management/dev-workflow.mdx
> chore(symphony): updating random pathing kerfuffles

- src/content/docs/apm/agents/manage-apm-agents/agent-data/agent-attributes.mdx
- src/content/docs/style-guide/formatting/ui-paths.mdx
I used a second table because it was easier for a first draft. Open to other ways of organizing the information.
Looking for other examples of UI pathing conventions, too.
> feat(style guide): updated UI pathing

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/cloud-flow-logs/gcp-vpc-flow-log-monitoring.mdx
Added mention that this is a limited preview
> fix: limited preview

- src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-7.11.1.mdx
Maintenance release for java agent
This page can be merged at anytime.
> Create java agent 7.11.1 file

- src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx
updates for maintenance release
> Update java agent eol

- src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
I am working with the PHP team PM to update the compatibility and support statement for the PHP agent.
This is a work in progress so I will mark it as a draft PR.
I will contact the docs team on slack when we are ready to have it reviewed.
> fix(PHP agent): Update compatibility and support statement

- src/content/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx
- src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
Updates EOL policy matrix.
Adds new nrpgx5 integration to support table.
> Feat(Go Agent) added EOL updates and new integration

- src/content/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api.mdx
- src/content/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api.mdx
> Added a few details about service.name attribute

- src/content/docs/style-guide/ui-writing/abbreviations-and-acronyms.mdx
Looks like a couple sub-bullets lost their indent.
> Indent sub-bullets.

- src/content/whats-new/2022/11/whats-new-11-15-pixie-entities.md
> typo in the link for getting started

- src/content/docs/apis/nerdgraph/examples/nerdgraph-workloads-api-tutorials.mdx
> docs(workloads): corrected the terraform URL

- src/i18n/nav/kr.json
> Updated Korean Nav

- src/content/docs/vulnerability-management/overview.mdx
> fix(vm): account type fix

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
- src/content/docs/apm/agents/php-agent/getting-started/monitor-your-php-app.mdx
- src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-activemq.mdx
- src/content/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-apache-flink.mdx
- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx
- src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
- src/content/docs/new-relic-solutions/get-started/implementation-guide-instrument.mdx
- src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
- src/content/docs/new-relic-solutions/get-started/quick-launch-guide.mdx
- src/content/docs/new-relic-solutions/new-relic-one/install-configure/install-new-relic.mdx
- src/content/docs/style-guide/writing-strategies/install-docs-guidance.mdx
- src/content/whats-new/2022/03/whats-new-03-03-azure-gcp-logs-campaign.md
- src/content/whats-new/2022/04/whats-new-04-28-april-io-roundup.md
- src/install/java/download/aws.mdx
Fixing links for 65463, first pass. Waiting for missing links from dev on spreadsheet.
> chore(doc site 65463): fixing links first pass

- src/i18n/nav/kr.json
We just updated the kr nav json but the locale was valued as jp by accident. this is a find and replace back to kr
> Revert accidental locale swap

- src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
We now support a few additional types of netflow data. This PR adds them into the docs
> Adding new supported netflow types

- src/content/docs/network-performance-monitoring/troubleshooting/chtimes-error.mdx
- src/nav/network-performance-monitoring.yml
Adding a new troubleshooting document for an error customers have encountered
> Add: Create chtimes-error.mdx

- src/content/docs/network-performance-monitoring/troubleshooting/snmp-data-gaps.mdx
- src/nav/network-performance-monitoring.yml
Adding a new network troubleshooting doc for cases of data gaps
> Add:snmp-data-gaps.mdx

- src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/calico-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/cockroach-db-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/core-dns-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/etcd-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/ingress-controller-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/integrations-list-intro.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/redis-integration.mdx
- src/content/docs/infrastructure/prometheus-integrations/integrations-list/traefik-integration.mdx
Added empty files to publish hidden docs and unblock the work on the Quickstarts.
> Prometheus empty files

- src/content/docs/logs/get-started/new-relics-log-management-security-privacy.mdx
- It mentions the new Log Obfuscation feature in the "legacy" automatic obfuscation docs.
- Wraps important paragraphs in Callouts.
> Reference the new Log Obfuscation feature in the automatic log obfuscation

- src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-config.mdx
Fixed links that were looping to the same section the link originated from. They should now go to relevant places in the docs.
> chore(Infrastructure): Mysql ics link fix

- src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Reflects the new cap on Spring jms and spring webflux
> Update compatibility for spring modules

- src/content/docs/new-relic-solutions/get-started/implementation-guide-instrument.mdx
* APM best practice link leads to the wrong page
> APM best practice link points to CodeStream

- src/content/docs/new-relic-solutions/get-started/glossary.mdx
We didn't have a definition before, whoa! @akristen FYI
> External services definition & related references

- src/content/docs/data-apis/get-started/nrdb-horsepower-under-hood.mdx
Noticed a typo transposing R with D.
> NDRB -> NRDB

- src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
Fix a weird collapser issue in config docs
> style(php): Fix config blocks

- src/content/docs/apm/agents/nodejs-agent/getting-started/monitor-your-nodejs-app.mdx
- src/content/docs/apm/new-relic-apm/getting-started/introduction-apm.mdx
- src/content/docs/new-relic-solutions/new-relic-one/install-configure/install-new-relic.mdx
Updating the remaining 5 links from the spreadsheet. This should close us out for this story.
> fix(docs): Updated outstanding links from spreadsheet (65463)

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/user-settings.mdx
Cleaned up verbiage based on feedback from Shinji Matsukawa and added some clarification to callout about incident/issue TTL settings.
> Clean up verbiage, clarify callout

- src/content/docs/apis/nerdgraph/examples/nerdgraph-historical-data-export.mdx
- src/content/docs/data-apis/understand-data/metric-data/metric-data-type.mdx
- src/content/docs/data-apis/understand-data/metric-data/query-metric-data-type.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Fixes include: 
Remove placeholder in requirements section. 
Fix account-containing URL. 
Add some more cross-links about getField and Metric fields
> A few small fixes

- src/content/docs/apm/new-relic-apm/maintenance/disable-apm-agent.mdx
> style(APM agents): Clarified that disabling is the same as turning off

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx
Improves structure of doc, fixes clumsy language, hopefully clarifies issue in https://issues.newrelic.com/browse/NR-66093
> style(infra): Improve strucutre, address NR-66093

- src/content/docs/apm/agents/net-agent/installation/install-net-agent-windows.mdx
- src/content/docs/apm/agents/net-agent/troubleshooting/no-data-appears-net.mdx
Attempt to clear up .net non-IIS install/TS process
> fix(.net): some TW edits based on feedback

- src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-config.mdx
- src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx
A customer pointed us that we were missing the Windows installation procedure. This PR should fix the issue.
> Add Windows installation guide to Nginx integration (NR-68231)

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial.mdx
- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-manage-groups.mdx
- src/content/docs/apis/nerdgraph/examples/nerdgraph-manage-users.mdx
Came in as liaison work: updating docs to reflect that customers can add/delete users now with nerdgraph
> fix(nerdgraph): add/delete users

- src/content/docs/release-notes/index.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/index.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.33.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.36.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.46.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.65.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.68.mdx
This PR is to add new release notes for Synthetics. The Node Browser runtime is part of our new runtime that we implemented and something that customers can download via DockerHub, hence we have now need release notes for this so that customers can easily understand differences between versions. 
This is the ticket in our sprint to do this work: [NR-46940](https://issues.newrelic.com/browse/NR-46940)
> Feature: Node Browser Runtime Release Notes

- src/content/docs/style-guide/writing-docs/article-templates/branching-doc-guide.mdx
I added some info about our new YAML verify script and what it checks for.
> feat(style): Updated branching guide doc with info about the verify YAML script

- src/content/docs/licenses/license-information/usage-plans/new-relic-one-usage-plan-descriptions.mdx
> Update to not reference to "this order" as this is not an Order

- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
Added a line to explain what you can do with Markdown, as well as a video
> Add video to Markdown editor section

- src/content/docs/release-notes/index.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/index.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.17.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.19.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.20.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.21.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.23.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.25.mdx
This PR is to add new release notes for Synthetics. The Node Api runtime is part of our new runtime that we implemented and something that customers can download via DockerHub, hence we have now need release notes for this so that customers can easily understand differences between versions. 
This is the ticket in our sprint to do this work: [NR-46939](https://issues.newrelic.com/browse/NR-46939)
> Merge ASAP: Node Api Runtime Release Notes

- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
- src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
After talking with Sebastián Galiano, I've added _Color customization_ and _Units customization_ to the [Customize your charts](https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/use-your-charts#customize-charts) section.
> feat(Charts): adding color and units customization

- src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-configuration-management-tools.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
- src/nav/infrastructure.yml
Adding Ansible according to [this doc](https://docs.google.com/document/d/1G4aMd3eHviNxI4MgwJD6CBmHs5wLhegzkRNbt0jI3lw/edit#).
See [NR-55706](https://issues.newrelic.com/browse/NR-55706)
> Nr 55706 ansible chef puppet

- src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-191.mdx
- src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-206.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.21.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.25.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.46.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.65.mdx
- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.68.mdx
This PR is just to fix some grammar errors and the Node API and Node api issue that was mentioned in the help channel: https://newrelic.slack.com/archives/C0DSGL3FZ/p1669625446112459. 
> Fix: Grammatical Changes to different Synthetics Release Notes

- src/content/whats-new/2022/11/whats-new-11-08-hcp-consul-quickstart.md
Updated docs link to internal docs rather than GH
> Update docs link for HCP Consul What's New (11-08)

- src/content/whats-new/2022/11/whats-new-11-30-dashboard-template-variables.md
Hello,
Please publish this What's New on the morning of 11/30. Thank you! This does not require the review of a PMM.
> What's new:  dashboard template variables (Publish 11/30/2022 in tandem with  #10457)

- src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
To be fixed:
Then content has to be inside the snippet. But found it to be outside. Hence raising this PR in an attempt to fix this.
> Observed that the code is out of the snippet

- src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
The following sections were added to `https://github.com/newrelic/docs-website/edit/develop/src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx`:
- Color customization
- Units customization
But not removed from `https://github.com/newrelic/docs-website/edit/develop/src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx`. This PR is to remove it from it so that is not duplicated.
* If your issue relates to an existing GitHub issue, …
> Remove duplicated information

- src/content/docs/infrastructure/prometheus-integrations/integrations-list/cockroach-db-integration.mdx
Fixing the indentation of the yaml file.
> chore(prometheus): indentation

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
> chore: fix typos

- .github/auto_assign.yml
Adds @a-sassman and @jeff-colucci to review action
> feat(review): add jeff and ally to action

- src/content/docs/apm/agents/manage-apm-agents/configuration/high-security-mode.mdx
Closes #9314 
Confirmed in #java-agent that this parenthetical has no special meaning.
> fix(HSM): Clarify Java agent defaults

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Fixed missing ids for 4 entries on the tables in this doc
> fix(NRQL syntax): fixed missing ids to enable linking (63970)

- gatsby-config.js
- gatsby-node.js
Reverts newrelic/docs-website#10358
> Revert "feat: remove all redirects with urls that have trailing slash, enable…"

- src/templates/releaseNoteLandingPage.js
Instead of querying for `mdxAST` and traversing that to pull out some elements' text values, use the type provided by default. Using the AST is likely expensive because it's big AND release notes are most numerous on site.
TBD on how much the improvement to build time here is. i assume whatever is behind the `excerpt` is doing something similar.
Closes https://issues.newrelic.com/browse/NR-69230
> Refactor how we generate release note excerpt on landing pages

- src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/changes-since-v3.mdx
- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-4-2.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-5-0.mdx
- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-6-0.mdx
Duplicate PR of https://github.com/newrelic/docs-website/pull/10425 as it's from a forked repository.
> Update KSM docs

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
* What problems does this PR solve? Adds an explanation of the quirks when updating the KSM version.
> Upgrade KSM v2 quirks

- src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/setup-prometheus-agent.mdx
Adding a clarification regarding duplicated data
> feat(prom-agent): duplicated data alert

- src/content/docs/release-notes/synthetics-release-notes/node-api-runtime-release-notes/node-api-runtime-1.1.27.mdx
Creates release notes for 1.1.27
What is included in the release: https://source.datanerd.us/synthetics/synthetics-node-api-runtime/compare/release-63...release-64
> chore: Create release notes for 1.1.27 api-runtime

- src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.74.mdx
Creates release notes for new version.
https://source.datanerd.us/synthetics/synthetics-node-browser-runtime/compare/release-143...release-146 the release last change doesn't need to be included in release notes as it is not customer facing.
> chore: Add release notes for new browser runtime

- src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
Add SLES 15.4 support for infra-agent docs
> added infra-agent install guide for suse 15.4

- src/content/docs/style-guide/writing-strategies/nav-best-practices.mdx
- src/nav/style-guide.yml
Reader, let's talk :)
Still to do: Add a real-world example of a before/after nav improvement.
> A new nav best practices doc

- src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
I made this typo in a PR yesterday... oops
> chore: fix typo

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration.mdx
> fix(k8): add redirect

- src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
- src/nav/style-guide.yml
This fixes two errors introduced when two commits were pushed up directly to develop.
Fixes:
- https://github.com/newrelic/docs-website/commit/76da3a049ba78b1571737b12716dc4995a73b341
- https://github.com/newrelic/docs-website/commit/b68a6052660891a553612ac230fe4a1f5273b3b5
> Fix develop

- src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
There was some confusion about the JSON stanza Infinite Tracing was configured in with the Node.js agent. This PR clarifies where in the Node.js agent Infinite Tracing is configured, and also makes the Distributed Tracing requirement a secondary line item, not front and center.
> NR-69920 clarify infinite tracing config Node.js

- src/content/docs/style-guide/ui-writing/punctuation.mdx
Added information about how we use forward slashes (/).
> Style guide addition to Punctuation page.

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1350.mdx
Release notes for infrastructure agent 1.35.0
> docs: infra agent 1.35.0 release notes

- .github/auto_assign.yml
> chore(review): remove Austin

- src/content/docs/synthetics/synthetic-monitoring/getting-started/monitor-limits.mdx
> feat(content): added redirect

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
> fix(docs): removed duplicated preview collapser

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
> Style guide addition to Usage page.

- src/content/docs/new-relic-solutions/get-started/quick-launch-guide.mdx
> fix(quick launch guide): Remove redundant copy

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-1.mdx
Node.js Agent v9.7.1 Release Notes
> Node.js Agent v9.7.1 Release Notes

- src/content/docs/accounts/accounts/automated-user-management/onelogin-scimsso-application-configuration.mdx
Removed a repeated word.
This PR comes from this one: https://github.com/newrelic/docs-website/pull/10599
The user didn't want to sign the CLA, so I opened this one for fixing the error.
> fix(accounts): removed a repeated word

- src/content/whats-new/2022/12/whats-new-12-06-nm-new-install-methods.md
Minor addition to network monitoring install supporting additional linux deb/npm and removes dependency on docker containers.
> feat(whats-new): add npm new install linux deb/npm (Publish: 12/07/2022 morning)

- src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/apm-best-practices-guide.mdx
Fixes broken link and missing link on apm best practices
> fix(apm-best-practices): fixed broken link to puppet, chef and added ansible

- src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
- src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-4-0.mdx
Release notes and docs changes for .NET Agent 10.4.0,
> Dotnet release v10.4.0

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-2.mdx
Node.js Agent v9.7.2 Release Notes
> Node.js Agent v9.7.2 Release Notes

- src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx
Corrected accidental word duplication and disambiguated which account number should be entered at that step.
> docs: Minor clarification/correction to account entry step

- src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
> chore: add language identifiers to code

- src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
please hold off on merge until we release support for 1.25, pending either 12/07 or 12/12
> Update kubernetes-integration-compatibility-requirements.mdx (Tentative publication dates: 12/7 or 12/12)

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
please hold off on merge until we release support for 1.25, pending either 12/07 or 12/12
> Update kubernetes-integration-install-configure.mdx (Tentative publication dates: 12/7 or 12/12)

- src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
please hold off on merge until we release support for 1.25, pending either 12/07 or 12/12
> Update install-kubernetes-integration-using-helm.mdx (Tentative publication dates: 12/7 or 12/12)

- src/components/InstallFeedback.js
these two events will show up as TDOC_LeaveAComment_feedbackInstallClick and TDOC_Comment_installFeedbackSubmitted
> Add tessen categories

- src/content/docs/errors-inbox/error-users-impacted.mdx
Minor wording revisions
Just fixing some awkward wording in this docs page :)
> fix: revise wording for user impact docs

- src/content/docs/mlops/bring-your-own/mlops-byo.mdx
> Comment out out dated sections

- src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-6-0.mdx
* What problems does this PR solve? Add missing release notes point.
> Update k8s 3.6.0 docs

- src/content/docs/data-apis/custom-data/custom-events/report-custom-event-data.mdx
Awaiting feedback from other SMEs but I think what we have here covers the original ticket in an acceptable capacity
> feat(APIs): added new using custom events section

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more.mdx
PR for hero edits for noon merge
> feat(accounts): add bullet point

- src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts.mdx
- src/content/docs/synthetics/synthetic-monitoring/getting-started/monitor-limits.mdx
Clarifies which timestamp is used to calculate synthetics usage details.
> fix(synthetics-usage): Clarify usage timestamps

- src/content/docs/data-apis/understand-data/new-relic-data-types.mdx
- src/content/docs/new-relic-solutions/new-relic-one/introduction-new-relic-one.mdx
- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language.mdx
Broken links, mostly on https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language/
> fix: Fix broken links on the NRQL intro page

- src/content/docs/logs/logs-context/disable-automatic-logging.mdx
Partially addresses user feedback in NR-65567
> style(logs): Improve structure of "disable log"

- src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux.mdx
Fixing this PR: https://github.com/newrelic/docs-website/pull/10664/files
> fix(infra): typo

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-3.mdx
Node.js Agent v9.7.3 Release Notes
> Node.js Agent v9.7.3 Release Notes

- src/content/docs/mlops/bring-your-own/mlops-byo.mdx
> Bring your own data V1

- src/content/docs/logs/ui-data/parsing.mdx
Update Parsing.mdx section to remove references to Grok Debugger external site which is no longer working
Remove link to YouTube video which shows how to use Grok Debugger site to test Grok Patterns
Add link to Github link with our supported Grok patterns
> Update grok sections

- src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-4-0-316.mdx
php agent v10.4.0.316 was released yesterday.
> feat(php): 10.4 release notes

- src/content/whats-new/2022/12/whats-new-12-08-errors-inbox-users-impacted-traces-in-context-slack.md
* What problems does this PR solve? Product Announcment 
> feat(whats-new): Errors inbox updates (Publication date: 12/15 9am)

- src/content/docs/apm/apm-ui-pages/monitoring/databases-page-view-operations-throughput-response-time.mdx
Fixes a couple stray paths.
@akristen : Can we do a check to see if this is a one-off or if there are more lurking old paths like this?
> chore(pathing): Fix APM database path

- src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
> chose: add syntax highlighting

- src/content/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1360.mdx
Release notes for infrastructure agent 1.36.0
> docs: infra agent 1.36.0 release notes

- src/nav/apm.yml
> fix(Ruby): nav reorganization

- src/content/docs/logs/ui-data/parsing.mdx
We had some weird merge conflict issues in dev/main and completely dropped changes on the file, this adds em back
> Add back changes

- src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-4.mdx
Node.js Agent v9.7.4 Release Notes
> Node.js Agent v9.7.4 Release Notes

- src/content/docs/style-guide/ui-writing/units-of-measurement.mdx
We didn't have an entry for requests per second in the style guide. This updates that.
> UI writing style - update - rps

- src/content/docs/apm/agents/apm-no-stack-traces.mdx
> Update no stack trace scenario documentation.

- src/content/docs/style-guide/capitalization/product-capability-feature-usage.mdx
Corrected/revised external link on "Products and capabilities" page (line 20) of Style Guide.
> Revised external trademarks link

- src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-math-using-select.mdx
These were probably introduced as part of merge conflict resolution of https://github.com/newrelic/docs-website/pull/6908
> chore: Fix some misplaced paragraphs

- src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation.mdx
@akristen I'm adding you as a review on this minor change. This is related to Jira NR-66161
> fix(Java): Added clarity about annotations and defaults

- src/content/docs/vulnerability-management/integrations/aws.mdx
Adds missing content for eventbridge step
> feat(vulnerability-management): add eventbridge content

- src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
> docs: fix broken header

- src/i18n/nav/jp.json
> Update Japan Nav

- src/content/docs/logs/ui-data/built-log-parsing-rules.mdx
Update Grok Debugger link in Built-in parsing rules section
> Update Grok debugger link

- src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
On a spelunking through the Java agent code, I discovered that these were available but not documented.
> fix: add azure, gcp, pcf, and kubernetes configs

- src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
mostly just making the indentation consistent. I also added `ini` code type to env vars, I think it looks nice, but if you don't like it I'll remove it.
> chore: minor code cleanup

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Added "page views" to Usage page in our style guide.
> Added entry to Usage page in style guide

- src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Added entry ("web page") to Usage page in our style guide.
<
> Added entry to Usage page in our style guide

- src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-find-entities.mdx
This came in as a customer Jira: https://issues.newrelic.com/browse/NR-74797
> Fix broken resources link in OpenTelemetry

- src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/create-anomaly-alert-conditions.mdx
- src/content/docs/logs/ui-data/find-unusual-logs-log-patterns.mdx
Fixing a broken link on the [Put the platform to work with patterns](https://docs.newrelic.com/docs/logs/ui-data/find-unusual-logs-log-patterns/#platform) section inside the [Discover value in log data with patterns](https://docs.newrelic.com/docs/logs/ui-data/find-unusual-logs-log-patterns/) page.
> chore(Alerts): fixing a broken link

- src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps.mdx
Added a small section about how to update with the Azure extension.
> docs: updating with extension added

- src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-coe.mdx
Add video to OMA CoE guide and edits to style that weren't done originally
> Add video to oma co e guide

- src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
Work done: 
Improvements to the user type table, including more clear language and briefer descriptions
Clarifying that if something isn't mentioned in table, it requires full platform user
Removing some 'limited availability' language for 'core user'
> fix(user type): improving user type doc

- src/content/docs/data-apis/manage-data/manage-data-retention.mdx
- src/content/docs/licenses/license-information/usage-plans/new-relic-one-usage-plan-descriptions.mdx
Changes: 
Added VM price to list price table
Attempted to fix lack of '30 days' from data retention entry in list price table
> Vm pricing updates

- src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
> Update infra agent troubleshooting

- src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
- Added node-vault module
- Added otpauth module
- Updated module versions to match current runtime
> feat(syntheticsModuleUpdate): Added modules and updated versions

- src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx
- src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/observability-coe.mdx
Reverts newrelic/docs-website#10855
> Revert "Add video to oma co e guide"

- src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
Linked the public locations text to a list of all public locations.
> fix(public locations): Added a link to the list of all public locations

- gatsby-node.js
dsg turns on
dsg turns off
you can't explain that
> Enable DSG

- src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
> fix(api keys): clarifying copying keys

- src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx
> clarifying message to reader, New Relic style & voice

- src/i18n/nav/jp.json
- src/i18n/nav/kr.json
> Update to the JP and KR Nav

- src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
> Log retry update

- src/content/docs/new-relic-solutions/new-relic-one/ui-data/collaborate/collaborate-with-teammates.mdx
- src/content/docs/new-relic-solutions/new-relic-one/ui-data/collaborate/collaboration-slack-integration.mdx
Changing link from preview to public docs site.
> fix(collaboration): fixing link

- src/content/docs/apm/agents/java-agent/heroku/java-agent-heroku.mdx
> chore: fix xml indentation, add lang identifier

- src/content/docs/vulnerability-management/integrations/aws.mdx
> feat(aws): broken link

- src/content/docs/security/security-privacy/compliance/hitrust.mdx
Updating the date for our HITRUST certification. We got the final report - looking good!
> Updating certification date

- src/content/docs/apm/agents/apm-no-stack-traces.mdx
- src/nav/apm.yml
> fix(apm): add stack trace doc to taxonomy

- src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx
> fixed a typo

- src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
small clarification added to clearly identify support for stacked bar charts; based on comments from @miguelsancheznewrelic in PR #10916
> fix: add clarification to chart types

- src/content/docs/apis/nerdgraph/examples/nerdgraph-dashboards.mdx
Update limits for number of pages in a dashboard and number of widgets in a page.
> feat(dashboards): NR-70204 - Update limits for pages and widgets

- src/content/docs/vulnerability-management/integrations/intro.mdx
Updates outdated agent compatibility matrix
> feat(vm): update agent compatability

- src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/diagnostics-beginner-guide.mdx
Work done: 
clamshelled some stuff for easier scanning
fixed some typos
> Om diag guide fixes

- src/content/whats-new/2023/01/whats-new-01-10-collaboration-public-preview.md
Publish 01/10 morning
I'm a PMM, this doesn't need PMM review. Thanks!
> Whats new 01-10 collaboration public preview
