src/content/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic.mdx
`properties` works on the docs site now, but one codeblock didn't have it
=> docs: add filetype to codeblock where it's missing

gatsby-config.js, src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
I'm not sure if we recognize `.ini` file types in markdown, but I added them just in case
=> docs: +lang identifiers

src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-core-agent-linux.mdx
Command should be:
xargs --null --max-args=1 < /proc/<var>PID</var>/environ | grep "CORECLR_"
per our post here: https://discuss.newrelic.com/t/relic-solution-net-core-agent-installation-troubleshooting-in-linux/69965
When running just args, I get a command not found message. The command works when using xargs.
=> Correct command to check for environment variables

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/advanced-configuration/manage-pixie-memory.mdx
Previous wording could have been interpreted as saying that _all_ Pixie telemetry data is persisted in New Relic. Added some additional verbiage to clarify that it's only a subset of data.
=> Minor updates for clarity

src/content/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips.mdx, src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
Clarified a few sections of the synthetics IP and new synthetics IP documentation. I also updated this to indicate that the new IP ranges are now included in the IP range JSON files.
=> fix(syntheticIPs): Clarified IP docs

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
We are adding a few new environment variables to the .NET agent to control if and when data is sent during shutdown.
=> Add documentation about new environment variables in .NET Agent

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
Customers now attempting to use the request module in scripted API runtimes will receive our request like implementation of the got module instead.
=> feat(request module): Request module compatibility details

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
The winlog fluentbit plugin can only collect Classic Windows Events. Attempting to collect others will silently collect the Application log and set the channel on the event incorrectly.
See https://github.com/fluent/fluent-bit/issues/3383
Using winlog on the newer Windows Event Logs causes some weird behavior that's difficult to pin down, this call out will help highlight the behavior.  …
=> Add a callout to the older winlog plugin about classic events

scripts/actions/utils/handlers.js
I _thought_ i added i18n handlers for new `InstallFeedback` component, but i guess i didn't. We'll want that in place so i18n workflows don't break
Related to https://github.com/newrelic/docs-website/pull/9244
=> chore: add handler for install feedback component for i18n

src/pages/attribute-dictionary.js, src/pages/install/{installConfig.agentName}.js, src/pages/whats-new.js, src/templates/docPage.js, src/templates/landingPage.js, src/templates/releaseNote.js, src/templates/releaseNoteLandingPage.js, src/templates/whatsNew.js
Adds custom attribute to Browser `PageAction` and `PageView` events to explicitly identify the type of page for more reliable querying.
Partiuclarly useful when querying data for new install UI pages generated via `src/pages/install/{installConfig.agentName}.js`
Also removes tessen tracking for when a step is made active because it's very noisy and likely not very useful
Kinda just making up a nomenclature, but I thought it could be useful to categorize pages first as:
* Interactive
* Pages that change based on user input
* Dynamic
* Pages where content on the page updates automatically / dynamically based on where data is sourced
* Template
* Page of templated content rendered via a template in `src/templates`
Then just try to match file names mostly so it's obvious what template or page …
=> Add custom attribute to identify type of page

src/content/docs/apm/agents/java-agent/api-guides/java-agent-api-instrumenting-example-app-external-datastore-calls-dt.mdx, src/nav/apm.yml
We had an outdated URL and title in the API section of the Java instructions. I updated the title and the URL.
=> Replace CAT reference with DT reference in nav

src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4042.mdx
The latest version of the iOS mobile app has been release, so this PR updates our release notes.
=> docs: Add New Relic for iOS 4.4.2 release notes

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/macos-installation/install-infrastructure-monitoring-agent-macos.mdx
* Starting with infrastructure agent 1.30.0, macos is supported on Apple silicon too (M1, M2 processors).
=> feat: infra-agent macos arm support

src/content/docs/apm/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent-api.mdx
The .NET agent had a customer wanting to use the GetBrowserTimingHeader() API in a Blazor Webassembly application.  Unfortunately we don' t support that scenario.  This PR updates our API doc to call out that incompatibility, as well as provide correct instructions for how to use the API for a Blazor Server application, which we do support.
I also changed the code type for the Razor (not Blazor) instructions to be cshtml as that is the actual file type in that case.
=> Add blazor to getbrowsertimingheader api

src/content/docs/apm/agents/net-agent/other-features/net-codestream-integration.mdx
Codestream will be enabled by default in the .NET agent, as of version 10.2.0 (unreleased currently).
=> Update .NET Codestream documentation

src/install/config/java.yaml
The Java team asked that we remove this redirect.
=> feat(java): removed redirect to jvm arguments doc

gatsby-node.js
Had an issue where the 404 page template was being applied to pages that had "404" anywhere in the file name.  This will update the layout once again if the URL is one that exists in the "/docs/" page routing and is not getting a 404 from gatsby.  I thought this wouldn't work at first since the url doesn't get updated when you get a 404, but it seems like when the 404 page is displayed this doesn't update the layout.
https://issues.newrelic.com/browse/NEWRELIC-3231
BEFORE:
AFTER:
to test, go to the build and enter the slug: `/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-4042`
Then, go to a page that doesn't exist to see the 404 page working correctly :)
=> Regex to update layouts on pages that exist

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities.mdx
This feature is obsolete. It was replaced two years ago by Saved Views, and we finally got rid of the last references to it. 
See account-auth-and-access/authorization_management_service#1198
=> Removing reference to Logging's Saved Queries

src/content/docs/infrastructure/manage-your-data/data-instrumentation/host-integrations-metrics.mdx, src/data-dictionary/events/SystemSample/uptime.md
Ready to review, it adds the documentation of a new infra-agent metric: uptime
=> docs: infra agent uptime metric

src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
Since releasing the in-agent log forwarding and local decoration features, the .NET agent has had several customers using Sitecore CMS wondering why their Sitecore logs weren't being forwarded (or decorated) by the agent.  Unfortunately Sitecore uses an older version of log4net with different assembly and class names that our log4net instrumentation does not match at the present time.  This PR updates the relevant doc to specifically warn users about Sitecore's log4net being unsupported.
=> Add callout re: Sitecore log4net incompatibility

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
Now the default is 30k, up from 1k.
Memory can be increased, but in my testing, it's a very slight
increase. It depends on the complexity of the custom events and the
rate at which they are being generated.
The server will soon only accept a maximum of 100k custom events per
minute, so that's also a hard limit for the agent.
=> Update custom event limit

src/content/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics.mdx
The synthetics UI and APIs no longer allow you to modify the Apdex T value used in the SLA report. I clarified the documentation and referred to the NRQL apdex function if an Apdex value is needed.
=> fix(synthetics apdex): Removed references for editing Apdex T

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/Issues-and-Incident-management-and-response.mdx
This was a hero request asking that we find the doc behind this failing link that was actually a redirect: /docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/
=> Fix redirect

src/content/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration.mdx
While theoretically we can still support all those versions as the communication protocol has not changed and we should still be able to monitor them, we have lost the possibility to test them as there are no installers available for them.
Microsft does not support these versions so we are dropping support for them too.
=> Drop old MSSQL versions

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
data comes from this doc: https://newrelic.github.io/node-newrelic/docs/API.html#shutdown
added a new table for the parameters above the table of 'options'. Feel free make this look better or suggest changes. `callback` is optional but that was not made clear on this doc.
=> docs: add info about `shutdown` callback

src/content/docs/data-apis/convert-to-metrics/create-metrics-other-data-types.mdx
We enforce a 50k per 30 second window cardinality limit, not per 24 hours.  Updating docs to reflect that.
=> fix(Metrics): Fixing time window in query

src/content/docs/network-performance-monitoring/troubleshooting/meraki-controller-no-data.mdx, src/nav/network-performance-monitoring.yml
adding a new troubleshooting doc for [EXT-MERAKI_CONTROLLER](https://github.com/newrelic/entity-definitions/tree/main/definitions/ext-meraki_controller) entities missing data in Network Monitoring.
=> feat: new troubleshooting doc for meraki controller

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80201.mdx
* Adds release notes for Python Agent v8.2.1 and updates EOL policy for Python agent versions.
=> Add python agent v8.2.1 release notes

src/pages/install/{installConfig.agentName}.js
Adds custom attribute to explicitly identify the agent name for all events that Tessen forwards via our Browser agent  events (`PageView` and `PageAction`).
Currently, not all events have the `agentName` set which causes you to have rely on a URL path based attribute like `path`, `currentUrl`, or `pageUrl` which have some issues as well. `path` is not available on all events and the page can resolve with a trailing slash or without, which makes it filtering or faceting on `currentUrl` or `pageUrl` a little difficult / confusing. Additionally, it wasn't clear when to use `pageUrl` vs `currentUrl` in various queries. And relying on url path forces you to account for:
* prod vs dev
* localized pages
if `agentName` is set via Tessen call, it's maintained when data is reported as expected. I …
=> feat(analytics): add agent name to all events that fire on install ui page

scripts/actions/fetch-and-deserialize.js
This includes the install files we weren't ready to translate and some compromised files that were marked in progress when they shouldn't have been
=> Temp ignore files deleted from DB

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-comparison.mdx
SLM is not in beta, and with metrics support now has comparable features between OTel and NR agent, minus the per-entity UI.
The "Live instrumentation" had accidental copy-paste content; replaced that with appropriate description. Added "Custom instrumentation" feature for Java.
=> Update SLM, move instrumentation features

src/content/docs/apm/agents/net-agent/troubleshooting/missing-couchbase-metrics-net.mdx
`GetAsync`(string key) doesn't really make sense, it would normally be written `GetAsync(string key)` with the parameters included
=> docs: put backticks around the entire method name

src/nav/kubernetes-pixie.yml
Removes redundant information from documentation, avoids confusion.
[Current Docs Page](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring)
( Notice the two highlights in the page nav menu )
I removed the second occurrence in the list, not sure what the preferred ordering is on the page. Let me know if it's better to keep the second item instead.
=> docs: remove duplicate page entry

src/content/docs/apm/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/es-modules.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
**What problems does this PR solve?**
* Creates documentation explaining how custom instrumentation works for ES module applications, including caveats about `newrelic.instrumentLoadedModule`
**Add any context that will help us review your changes such as testing notes,
links to related docs, screenshots, etc.**
* Due to the nature of ES modules, we had to add a new configuration value that allows customers to inject their custom instrumentation definition into our ES module loader. This PR documents that configuration value, and also updates our newly created ESM documentation to link to our custom instrumentation example application. It also documents that `newrelic.instrumentLoadedModule` does not work in ESM apps, due to immutability of module bindings after load.
**If your issue …
=> NEWRELIC-3777 add docs for custom instrumentation in ESM

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Changes on ADO.NET's Additional configuration description
1. Applied link to "restart your infrastructure agent" text
2. Changed ADO.net to ADO.NET in the 4th point
=> Added link to "restart your infrastructure agent"

src/content/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic.mdx
`entityDelete` cannot delete entities of type BROWSER-APPLICATION: https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial/#delete-entities
=> Remove instructions to use NerdGraph to delete Browser applications

src/content/docs/data-apis/manage-data/manage-data-retention.mdx, src/content/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works.mdx, src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx
Removes hashes from redirect url paths because they're unnecessary. And could cause weird build issues (at least it did in netlify)
=> fix: remove unnecessary hashes from redirect paths

src/content/docs/apm/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs.mdx
`tls.SLAB_BUFFER_SIZE` appears to be pretty old and no longer a thing. there is no mention of it in that link, and googling the phrase only brings up very old docs (Node 0.x) as well as this page on docs.NR and a 2014 stack overflow. I couldn't figure out what the updated version might be though.
=> docs: put code in backticks

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-summary-page.mdx
The choice of presenting the 'server' role for a service (vs. 'client', etc.) is not always clear, so calling that out here with references to the OTel data model.
Adding a note on metrics along with a known limitation.
=> Metrics/spans, semantic conventions, server/client distinction

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-find-entities.mdx
- Moved the sections on finding your entity next to each other and made one a sub-section of the other
- Added a tip callout for global search, with specific advice for OTel services
- Cleaned up language about the overall page being about both finding entities and filtering data
- Consistent formatting for numbered lists
- Fixed name of External services
=> Refer to global search, reorder "find your entity" parts

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
Unicode left double qoutation marks and right double qoutation marks in the sample YAML snippet when copied to use was not matching process names and resulted in a quite lot of debugging effort  to get the process filtering working from Infrastructure agents from Windows hosts. The sample yaml snippets should be updated with Neutral double qoutation marks (vertical) to prevent such issues
=> Neutral double qoutation marks to be used for string defined inside the `include_matching_metrics:`

src/content/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations.mdx
This allows one to see if monitors on a particular runtime are contributing to queue growth. This can happen if:
- Monitors are set to the new runtimes (Chrome 100+, Node 16+) without having a [Synthetics Job Manager](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager/) to process those jobs for a private location.
- Monitors are set to the legacy runtimes (Chrome 72-, Node 10-) without having a [Containerized Private Minion](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms/#start) to process those jobs for a private location.
The new queues are:
- `pingJobs`
- `jobManagerHeavyweightJobs`
- `minionHeavyweightJobs`
=> Add new queues to SyntheticsPrivateLocationStatus

src/content/docs/more-integrations/grafana-integrations/set-configure/configure-new-relic-prometheus-data-source-grafana.mdx
This updates the link to our doc about the insights key query. Previously, the link went to the general API keys doc, which is very confusing due to the multiple types of keys. 
Updating this link will improve the user experience by making it clearer which key they need. (Prompted by a customer who got confused by this and used a browser key, which of course did not work.)
=> Updates link for insights query key

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
This adds a note about Insights query keys. The collapser title states it is not recommended, but it is the key you need to use to configure NR as a Prometheus data source for Grafana (per this [doc](https://docs.newrelic.com/docs/more-integrations/grafana-integrations/set-configure/configure-new-relic-prometheus-data-source-grafana/). 
This should help create a better user experience for users when they're looking to use/create an insights query key for this integration. 
Slack thread [here](https://newrelic.slack.com/archives/CH292BVUZ/p1665507210032249) on the above with the team that owns Prometheus remote write.
=> Add a note about Insights query keys

src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
This doc currently serializes into html with a p tag wrapping a whole table, adding the new line will prevent that behavior
=> Add new line to prevent serialization issues

src/content/docs/new-relic-solutions/new-relic-one/ui-data/metric-normalization-rules.mdx
Hello! I'm a 1st shift TSE on the APM team! There is an order field that is used to determine the precedence of created normalization rules, and has been a source of confusion for customers and support engineers. I've spoken with members of the 3rd shift TSE's who are working on the new MGI UI and they've confirmed that a lower number means higher precedence. I think this should be added to the docs!
=> add "Order" to available fields and explain that lower number = higher precedence. 

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx, src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx
Also, the future for enabling log forwarding by default is now!
* New release, new instrumentation: https://github.com/newrelic/docs-website/pull/9837
=> fix(node agent): document that bunyan is now an instrumented library

src/data-dictionary/events/PageView/asnLatitude.md, src/data-dictionary/events/PageView/asnLongitude.md
Those were recently added to the platform
Related to NR-54990
Added Mobile events references to asnLatitude/asnLongitude description to reflect latest platform changes
=> Adding asnLatitude, asnLongitude attributes to Mobile events to documentation

src/content/docs/apm/agents/nodejs-agent/installation-configuration/distributed-tracing-nodejs-agent.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
There was some confusion these docs caused with a customer, in [7.2.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-7-2-0/) we updated the default config that customers can copy as an example to have DT enabled, but DT was not always enabled by default until [8.3.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-3-0/)
This PR uses the correct version number for DT enabled by default.
Closes [NEWRELIC-4620](https://issues.newrelic.com/browse/NEWRELIC-4620)
=> NEWRELIC-4620 - Nodejs Agent: correct version for DT enabled by default

src/content/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices.mdx, src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/apm-best-practices-guide.mdx
Added references
* Reference link to AQM from alerts best practices guide.
* Reference link to RED from APM best practices guide.
Both guides are more technical bias, where users may also be looking for more process bias provided by the OMA documents.
=> added references to oma where needed

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
The length() function was documented for arrays (on src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql.mdx) but not for strings.
https://issues.newrelic.com/browse/NR-58642
=> fix: NR-58642: Add documentation of the length() function for strings

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* Updated install instructions for Amazon Linux 2022, the .repo url is different.
=> chore(infra-agent): Amazon Linux 2022 repo url

src/content/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration.mdx
**What problems does this PR solve?**
The Prometheus integration install page doesn’t explain how to set up remote write for developers who use the Prometheus Operator (which most on Kubernetes do). This PR adds those instructions.
=> fix(Prometheus Integration): add Prometheus operator instructions to install guide. 

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
As part of the .NET agent team's October 2022 "core technology update" milestone, we've tested our agent's support for the latest MongoDB .NET clients and want to update our documentation accordingly.  I also simplified a wording, fixed a typo and adjusted an indentation.
=> Update supported versions of mongocsharpdriver and MongoDB.Driver

package.json, scripts/checkForOrphanImports.js
A little script that will check for:
- images that are being imported but have no matching image
- variable names used in an img src attribute that are not imported at the top of the file
`yarn check-image-imports`
=> Add image import check script

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
missing `'` closing the string
=> docs: fix typo

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
A 14 minute long video makes the `basic process` seem very long and complex. This PR moves the video towards the bottom and surfaces the shorter 7 step action items.
=> Move logs video 

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
This adds configuration of the module dependency metrics feature to the Go agent docs.
=> Feat(Go agent): add module dependency metrics configuration

src/content/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config.mdx
This updates the configuration options for code level metrics in the go agent as of v3.20.0.
=> Feat(Go Agent): updated clm configuration info

src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts.mdx
API example used a `list` query parameter, which doesn't exist. Updated to use `limit` instead.
=> fix: Correct query parameter

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
I moved "Preview" entry, which was after "app name vs. app alias," to the "P" entries.
=> Made revision to Style Guide on Usage page

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80300.mdx
This PR adds release notes for Python agent release v8.3.0.
=> Add python agent release notes for v8.3.0

src/content/docs/logs/logs-context/configure-logs-context-ruby.mdx
The documentation states that it may be the default in a future release, but it was made the default in the release following the one in which it was added. This patch clarifies that.
=> docs: Add version information for default log forwarding in Ruby.

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This will increase the custom event limit to 3,000 to align with 9.5.0 of Node.js agent which is shipping today
=> fix: NR-54396 updated custom event limit for node.js agent to 3000

src/content/docs/synthetics/new-relic-synthetics/pages/synthetics-results-access-individual-monitor-runs.mdx
Fixes a small typo in a meta description
=> fix(synth): fix small typo

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220.mdx
This PR updates the Browser Agent 1220 release doc.  The browser agent team has decided to no longer include arbitrary internal release dates, as they are misleading and not always applicable to our deploy process.
=> Update 1220 release notes

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/install-auto-telemetry-pixie.mdx
Fix typo in heading.
This makes it easier to read.
=> chore - typo in heading

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-jvms-page.mdx
Thanks to @jack-berg and others in the OTel community, the JVM runtime metrics are documented in the semantic conventions, so let's refer to them here.
=> JVM runtime metrics are specified now

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/noticeerror-browser-agent-api.mdx
The `#promise-js` id attribute is used twice. This PR fixes the 2nd occurrence by renaming the id to a new, unique value so then it fixes the ability to directly link to the "Capturing custom attributes example" heading of the page.
=> fix(noticeError): dedupe anchor id

src/content/whats-new/2022/10/whats-new-10-12-streaming-data-exports.md
Prob Oct 19 or later, waiting to hear from SMEs.
@zuluecho9 will review. 
*Streaming data export releases on 10-12-2022, we will delay the launch announcement.
*Data Plus exclusive feature
*This requires AWS Kinesis Firehose (must be AWS customer in this instance)
*Doc page link is not live, I put the github commit repo link
=> Oct 31: whats-new: add streaming data export

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-alerts.mdx
Refer to the new nav name for Explorer. Consistency in the links to further alerts docs, since they go to the same place.
=> Fix references to some UI elements

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx
Updates the supported version table for the Go agent to add the current 3.20.0 release and remove now-EOLed versions.
=> chore(go agent): update EOL version matrix

src/pages/attribute-dictionary.js
This Clipping could be seen in the Attribute Dictionary at widths less than 1240px:
This PR will fix this by changing the "position" field on Attribute headers to "initial" on screen widths less than 1240px.
=> Add margins so entries in attribute-dictionary don't clip

scripts/checkForOrphanImports.js
A common issue encountered in .mdx files regards the formatting of imports, and specifically, the need for a line of whitespace between each import. This PR adds a check for this whitespace to the `check-image-imports` script, and prints the file name and offending lines when that whitespace is not found. You can execute this using `yarn check-image-imports`.
=> chore: Add import spacing check to check-image-imports script

src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx
Adds latest releases to iOS mobile EOL doc and highlights the 7.4.0 iOS/XCFramework as latest.
https://issues.newrelic.com/browse/NR-62961
=> (mobile) NR-62961: Update EOL doc for iOS version (mobile-agents-eol-policy.mdx)

src/content/docs/apis/nerdgraph/examples/golden-metrics-entities-nerdgraph-api-tutorial.mdx
I formatted most of the code, but left the blocks with lots of inline `<vars>` intact for demo purposes. I also changed the `ENTITY-GUID` and `ExampleGUID` to what we use more often in the docs, `ENTITY_GUID` just because 🤷 .
=> chore: format and add syntax highlighting to code

src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
Apache Kafka 0.10, 0.11, 1.0 and 1.1 are now EOL for Apache Kafka on Heroku. The current recommended version is 2.2.1 or above.
=> Fixed version details

src/components/SEO.js
The 'docs/style-guide' and 'docs/agile-handbook' page categories can muddy search results, leading to confusion. This PR will exclude these pages search results altogether by instructing swiftype not to index them. The affected pages will have to be re-crawled for this to take effect.
=> chore: Exclude style-guide and agile-handbook from search results

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
Added updated requirements to deb/rpm install, including a new package source. Updated security table and split out install requirements for Linux host & Docker host.
Expands documentation to support new rpm and deb installs of the ktranslate agent for network monitoring.
=> ktranslate for SNMP - support for package deployments

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
Doc update from PHP team to improve accuracy of frameworks supported by INI option.  Currently a draft document will communicate when it is finalized by moving from draft status.
=> fix(PHP agent): Update framework INI options

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-0.mdx
In the 3.20.0 release, the release note document had an incorrect metadata header. This corrects that error.
=> Fix(Go agent): corrected release note metadata

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This configuration option was removed in node release v9.6.0 and is no longer needed in the agent.
=> fix(node agent): remove hide_internals config option

src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx
Updated the fb example to show the FILTER block in with the INPUT and OUTPUT blocks in step 4. Also removed the section on associating logs with entities since it's redundant to the example in step 4. We also don't explain to customer why associating logs with entities is  important so removed that verbiage entirely.
=> Updated fb example

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
It's very analogous to a similar flag for HTTP status codes, except nothing is ignored by default here.
=> fix(node agent): document new grpc.ignore_status_codes flag

src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx
The Ruby agent supports Excon v0.19.0+. Update docs to reflect.
=> Update minimum support Excon version

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
Update the .NET Core agent compatibility/support doc to include .NET 7.0, which GAed last week.
=> .NET 7.0 updates

src/content/docs/browser/new-relic-browser/browser-agent-spa-api/createtracer-browser-spa-api.mdx
To address user feedback from https://issues.newrelic.com/browse/NR-64616, I spoke with a browser SME (Grady Ellison) who said the UI reference to view browserTiming is based on the old UI. He also said there's no longer a consistent place in the new UI to see these browserTiming events. So I removed the UI reference in the doc - hopefully this will reduce confusion.
=> Remove UI instruction

scripts/removeUnusedImages.js
Now that we have mdx with image imports in the install folder we need to expand the script to check there. This updates it to check all of the src folder so we don't need to worry about any folders with mdx we might add in the future
=> Check entire src folder for img imports when deleting unused images

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This is referring to custom attributes, but the use of 'parameters' make a use think this is about query parameters, a different thing altogether. This language was updated in the API, but I think this was just a holdover from before that change.
=> chore: custom parameters -> custom attributes

src/content/docs/infrastructure/google-cloud-platform-integrations/getting-started/polling-intervals-gcp-integrations.mdx
Page was referring to AWS in the short description. Updated this reference and changed an anchor link to point to the one on the page instead of an AWS one.
=> fix reference to cloud provider

gatsby-config.js
Part of the work to remove Split IO configs from all our Gatsby sites.
=> Remove Spllt I/O config

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8130.mdx
Something went wrong when I created https://github.com/newrelic/docs-website/pull/10308/
Please review this PR instead! 
This PR updates the documentation corresponding with the Ruby agent's 8.13.0 release
Our hopes are to release tomorrow before the code freeze takes place
If our release is unable to be completed tomorrow, this PR should not be merged
Also, this release included a reorganization of our configuration options. The large diff is due to the locations of many settings being swapped.
=> chore(release): Update docs for Ruby agent 8.13.0

src/content/docs/apm/agents/ruby-agent/features/record-deployments-ruby-agent.mdx
PR https://github.com/newrelic/newrelic-ruby-agent/pull/1461 added support for deployment recording using a customer's user API key. This update was missing from the document.
=> chore: Add instructions for user API key

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-1.mdx
Release 3.20.1 of the Go agent (release notes)
=> Feat(Go agent) release 3.20.1 release notes

src/content/docs/apm/agents/go-agent/instrumentation/go-agent-code-level-metrics-instrument.mdx
Go agent release 3.20.1 corrects pluralization of some method function names. This updates the docs to match.
=> Fix(Go Agent)correct pluralization of function names

.github/CODEOWNERS
Removes John Kinmouth from What's New codeowners and adds Kevin Downs instead
=> fix(codeowners): add kevin remove john

src/content/docs/mlops/integrations/dagshub-mlops-integration.mdx
This is a replacement for https://github.com/newrelic/docs-website/pull/9300/files because we weren't able to get a signed CLA.
=> Fix DagsHub link (Publish on 11/18/2022)

src/content/docs/distributed-tracing/concepts/distributed-tracing-planning-guide.mdx, src/content/docs/distributed-tracing/infinite-tracing/infinite-tracing-configure-trace-observer-monitoring.mdx, src/content/docs/distributed-tracing/infinite-tracing/set-trace-observer.mdx, src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
I am not in the office, but could someone review this and get it published on 11/18/2022? We have already had some customers stumbling over these navigation links.
=> Distributed tracing: Reverse planning sections and fix links (Publish on 11/18/2022)

src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8130.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8131.mdx
Update docs for Ruby agent release v8.13.1. 
**NOTE**: Please merge on Monday, November 21, 2022 (This can go out with the typical morning merge around 9:00 am pacific time)
=> Update docs for Ruby agent v8.13.1 (Publish on Nov 21, 2022 with morning merge)

src/content/docs/apm/agents/net-agent/net-agent-api/incrementcounter-net-agent-api.mdx
Clarifies naming confusion reported in https://issues.newrelic.com/browse/NR-65573
=> chore(.NET): Clarify custom metric naming NR-65573

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/introduction-applied-intelligence.mdx
This PR addresses a renaming. Proactive detection is now know as anomaly detection, so the word proactive has been replaced with anomaly.
It may be better to retain the original anchor, in addition to the new anchor, to preserve existing links.
=> docs: replace references to proactive detection with anomaly detection

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
The env var reference guide was a broken link, changed it to `#environment-variable-type-reference-guide`
=> bug: fix Env Var Reference  link

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/define-custom-metrics-alert-condition.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx
https://issues.newrelic.com/browse/NR-54573
NRQL Alert Conditions will _soon_ no longer require critical threshold. NRQL Alert Conditions will allow critical thresholds to be optional.
Upcoming UI changes to the Condition Builder. Users will soon have an updated threshold building experience. They will be able to create NRQL Alert conditions with only warning thresholds. 
=> fix: Critical threshold is optional

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/attributes/nodejs-agent-attributes.mdx, src/content/docs/apm/agents/nodejs-agent/getting-started/apm-agent-security-nodejs.mdx
At some point in the distant past (circa 2018) the way we capture request parameters changed, but our documentation just wasn't properly updated to reflect this. Let's finally fix this, since now, four years later, someone tried to make sense of it, failed, and told us about it.
Closes NEWRELIC-5477
=> fix(node agent): properly document how to set up request parameters

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
Just a simple example of the basic idea of how to use this function.
* Closes #3560
* Corresponding PR for our repo and therefore the API docs at https://github.com/newrelic/node-newrelic/pull/1437/
=> fix (node agent): add noticeError example

src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
The link for `TransactionEvents.MaxSamplesStored` was linking to `TransactionEvents.Enabled`
=> chore: fix section link for TransactionEvents.MaxSamplesStored

src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/index.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-160.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-162.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-166.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-168.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-172.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-183.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-191.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-204.mdx, src/content/docs/release-notes/synthetics-release-notes/job-manager-release-notes/job-manager-release-206.mdx
Change the job manager title to work around the `v` that gets added by the  `version #`
=> Merge ASAP: edit to 'job manager' doc title

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration.mdx
Modifying the introduction page to Kubernetes:
- Updating the intro paragraph.
- Updating the [Get started: Install the Kubernetes integration](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/introduction-kubernetes-integration#install) section.
- Adding the info that is inside the _Navigate all your Kubernetes events_ inside the _Why it matters_ section. 
- Removing the _Navigate all your Kubernetes events_ title.
This is the ticket: [NR-64587](https://issues.newrelic.com/browse/NR-64587)
=> style(kubernetes): updating the entire page

scripts/validate-install/schema.js
We updated our verification script to also verify all mdx files but we didn't add a catch when reading those files which caused errors in them to fall back to the config yaml catch. This PR adds a catch at the mdx file level so we can get logging on which file is erroring instead of the red herring fallback to the config yaml
It also makes the redirects value in the config yaml optional 🎉
=> Update install script

src/content/docs/apm/agents/net-agent/troubleshooting/no-data-appears-after-disabling-tls-10.mdx
`reg` files use the same syntax highlighting as `ini` in Notepad++. `ini` highlighting was added to the docs site recently so this should colorize properly..
=> chore: add syntax highlighting

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
Net-Ping is no longer a supported module in the Chrome 100 runtime hence this PR is to update the docs to show that. Here a link to the Jira Ticket in our sprint that explains why we are doing this: [NR-65559](https://issues.newrelic.com/browse/NR-65559)
=> chore: net-ping is no longer a supported module for Chrome 100

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/apollo-server-plugin-nodejs.mdx
The list of modules was missing a few listed in this plugin's github README, so I added them: https://github.com/newrelic/newrelic-node-apollo-server-plugin
\
=> chore: update list of modules

src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3070.mdx, src/content/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3071.mdx, src/content/docs/release-notes/synthetics-release-notes/node-browser-runtime-release-notes/node-browser-runtime-1.1.70.mdx
* What problems does this PR solve? Adds release notes for synthetics services that were released today.
Today we released CPM 3.0.70 and node-browser-runtime 1.1.70
=> chore: add release notes for minion 3.0.70 and node-browser-runtime 1.1.70

package.json, yarn.lock
We made an update to the way the feedback form submits page urls.
This is a bump from 6.13.5 to 6.13.8. I did not notice any breaking changes locally.
=> Update theme version to 6.13.8

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
The link _User-related style_  link under the [users section](https://docs.newrelic.com/docs/style-guide/word-choice/usage-dictionary/#users) is a broken link.
=> Fixing a broken link

src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx
Unfortunately, I can't see exactly how my changes will look like, in preview it seems that the ordered list doesn't work as expected (an item per line) inside the tip callout.
What I wanted to do is to show users that the changes in the time picker in a dashboard affect to all charts, however, if they want 1 or many charts to not be affected by the time picker they can configure those charts by:
1. Click edit chart 
2. Change the setting of the "Ignore time picker" under Dashboard options 
3. Save the query After that, the chart won't update after interactions with the time picker
You can find more information here https://newrelic.com/blog/how-to-relic/dashboard-chart-customizations 
in your …
=> Add information about time agnostic widets

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
This came as a recommendation from a customer on a support ticket:
> The default value for maximumSamplesStored is 10000 and the description text says:
> > “The maximum number of samples to store in memory at once”
> Maybe you can update the documentation with the below description since that was more understandable:
> > “The maximumSamplesStored configuration options set a limit to the amount of data that the agent can hold in memory between uploads to NR1. This mean the default value of 10000 for transactionEvents will allow the agent to hold in memory 10000 transactions at one time, which acts as a cap the amount they can send. You can think of it as the maximum transactions the agent can send per minute.”
I simplified the text but please feel free to make any further improvements you …
=> chore: clarify the use of `maximumSamplesStored`

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux.mdx
docs: update the example to remove the hardcoded architecture (amd64) and use the variable instead.
=> docs: update shell script example

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/use-tags-help-organize-find-your-data.mdx
Describe the various ways tags can be automatically applied to entities. There is a bias toward service entities here, so any more detail on hosts or other entities might be nice. I don't think the doc has to be completely exhaustive, though. Would appreciate a review from @erabug @josemore @jlegoff 
Also make it a little more clear that tags go on entities, while attributes go on data.
=> Add section on automated sources of tags

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-0-0.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-1-0.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9700.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9710.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9800.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9810.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9900.mdx
There was a issue with our Microsoft.Extensions.Logging that requires a notice to be added to the release notes for a range .NET Agent versions.   We are also updating the changelog in our repo to match ones in this PR.
bug [#1230](https://github.com/newrelic/newrelic-dotnet-agent/issues/1230)
fixed in PR [#1237](https://github.com/newrelic/newrelic-dotnet-agent/pull/1237)
=> **ON HOLD: WILL LET DOCS TEAM KNOW WHEN READY TO MERGE*** chore: Update .NET Agent release notes for 9.7 to 10.1 with a notice

src/content/docs/network-performance-monitoring/setup-performance-monitoring/cloud-flow-logs/aws-vpc-flow-log-monitoring.mdx
The documentation for AWS VPC Flow Logs currently has a few rough edges that need to be smoothed out.  Reference https://issues.newrelic.com/browse/NR-62033
Prerequisites section talks about using ARNs for things that are not ARNs.  Rearranged prerequisites so items correspond to the appropriate heading. The "Set up Amazon VPC Flow Logs monitoring in New Relic" section points users to an IO page which then goes back to the install wizard. I removed the link out to the Instant Observability page and go directly to the install wizard.
Changed:
Docs -> Instant Observability page outside NR1 -> Quickstart page in NR1 -> Intermediate screen -> wizard simplified to this
Docs -> Wizard
in your commit …
=> Updates to VPC flow log install documentation

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Moved "x" entry before "you" entry, and revised one of the examples under "x" entry.
=> Style guide addition to Usage page

src/content/docs/apm/agents/python-agent/python-agent-api/recordlogevent-python-agent-api.mdx
This PR corrects the python agent version in which the record_log_event is publicly available.
=> Fix agent version in record_log_event docs.

src/content/docs/data-apis/custom-data/custom-events/report-browser-monitoring-custom-events-attributes.mdx
=> chore: fix typo

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Add Windows Server 2022 and Windows 11 to the list of operating systems we support running the .NET Agent on.
=> .NET Agent: update list of supported operating systems

src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/android-agent-configuration-feature-flags.mdx
Updated the default value for different Android agent crash reporting flags and wrote a description for `withCrashReportingEnabled()` to reflect current implementation.
=> Update android crash reporting flag

src/content/docs/network-performance-monitoring/setup-performance-monitoring/cloud-flow-logs/gcp-vpc-flow-log-monitoring.mdx
GCP Flow Logs are being released to GA tomorrow so we're ready to remove this "Limited Preview" label
=> Remove "Limited Preview" label (merge before 9am 12/15)

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8140.mdx
content related to New Relic Ruby agent v8.14.0, which offers a new configuration parameter
=> updates for Ruby agent v8.14.0 (9am 12/15 publish)

src/content/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards.mdx
The UI labels appear to have changed for dashboard permission on the create and edit dashboard pages. This commit updates the documentation to reflect the current dashboard permission labels.
Screenshot of current labels on the create/edit dashboard pages.
=> Update dashboard permission labels to match UI

src/content/docs/licenses/license-information/referenced-policies/security-policy.mdx
This was a pain point in user research—users getting stuck in this policy page when they're really looking for a general overview of how we approach security.
cc @jjang-nr , minor change to the security policy page to x-ref the .com friendly overview.
=> fix(security policy): X-ref to .com page

src/content/docs/logs/forward-logs/heroku-log-forwarding.mdx
The code examples had typos and the `<var>`s were showing as plain text.
The `$` cmd prompt is added when you make format the code as `shell` or `bash`, so it was there twice:
=> chore: fix code examples

src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/introduction-alerts.mdx
This removes references to the Events page and Classic Notification channels, which will soon EOL.  It replaces terms where possible.
=> Removing Alerts Classic references

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-2.mdx
Corrects the release date and git link for the 3.20.2 Go agent release
=> Fix(Go Agent): corrected release date

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8140.mdx
Ruby agent 8.14.0 introduced `defer_rails_initialization` to toggle some code for a bugfix.
This fix is run during the initialization process, before configs are applied so using the config has no value at this time.
https://github.com/newrelic/newrelic-ruby-agent/issues/662 
https://github.com/newrelic/newrelic-ruby-agent/pull/1702
cc @homelessbirds
=> chore: Document broken config

src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_record_datastore_segment.mdx
This change make it clear that a special character ('/') should not be used with certain parameters for the `newrelic_record_datastore_segment()` PHP agent API call.
=> fix(PHP agent): Clarify newrelic_record_datastore_segment string restrictions

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/subqueries-in-nrql.mdx
Clarify behavior of subqueries and time picker
Currently, the docs aren't clear on the interaction between the time picker and subqueries. Since time pickers override SINCE/UNTIL in subqueries, clarifying the docs here will help people understand the expected behavior.
https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard/#dash-time-picker
=> docs: Update subqueries-in-nrql.mdx

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition.mdx
Warning incidents can now open issues just like critical incidents can -- there is functionally no longer any difference between the two (besides the color of the traffic light yellow/red depending on priority level of incident warning/critical).
=> Clarify warning threshold

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
I fixed a bunch of small things like:
- indentation being inconsistent (3 spaces for example). 
- spaces between `key = "something"` in XML which isn't usually done
- added `ini` as a code type for env vars. It looks nice where I've seen it elsewhere, so I figured I'd add it here while I was at it.
=> chore: minor code cleanup, added missing config option for fedramp

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Revised "observability as code" entry in Usage page. Currently, appears as "Observability as code"; it should be lowercase "o".
=> Minor revision in Usage page in style guide

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
I moved the section for CAT below DT and 8T, we want customers to use those instead but the deprecated option was presented first in the doc. I also added a note about that deprecation, and updated the default value for the CAT setting to `false`.
I also added an 8T link in the navigation links.
=> fix: CAT is deprecated

src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
Added syntax highlighting to code examples and did some small cleanup for consistency. For example making default values always in backticks, or (none) without backticks. Fixed a few stray typos.
`ini` as a syntax highlighting example looks good in the .NET docs but it's kind of a taste choice for env vars. I can remove it if anyone objects
=> chore: add syntax highlighting & minor cleanup

src/content/docs/infrastructure/infrastructure-monitoring/get-started/infrastructure-agent-eol-policy.mdx
* Suggesting more details on the EOL policy for the infra agent (feel free to rewrite). The policy is: releases after July-2022 (starting with 1.28.0) are supported for one year, older releases (before July 2022) have a two-year support cycle.
=> fix(infra-agent): support dates

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-ansible.mdx
* The version param has been deprecated long time in the ansible repo for the infra-agent. We are removing this from doc to avoid confusion until there's an alternative param.
=> fix(infra-agent): version param deprecated

scripts/actions/__tests__/kitchen-sink.mdx, src/content/docs/style-guide/formatting/code-examples.mdx
This was work to: 
* Update style guide with better guidance on customer-specific value placeholders, which previously we said to use `<var>` tags for, but now we have to update because those tags disable code syntax highlighting. 
* I left in room to use `<var>` tags if we really want to and are okay with there not being syntax highlighting, but main guidance is to avoid var tags almost entirely.  
Questions: 
* Is saying to include 'INSERT' in placeholder text too much? Is it enough to just say 'YOUR_X...'? Or would it be more helpful to say 'INSERT_YOUR_X...' ? On one hand, getting rid of `<var>` tag makes it so that the placeholders are harder to recognize, so having 'INSERT' would help make things more clear in that regard. On other hand, it would take up more room.
=> fix(style guide): update var tag guidance

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
- curl should use -fsSL options to retry on failure, silent, show errors, and redirect if needed
- Ubuntu 22.04 needs to use `gpg` instead of `apt-key` to store the key in a different location
- `echo` is more user friendly than `printf` since it adds a line break
=> Update curl and printf commands

plugins/gatsby-source-install-config/gatsby-node.js, src/install/config/demo.yaml, src/install/demo/dropdown2/addStep.mdx, src/pages/install/{installConfig.agentName}.js
this adds a boolean to overrides called addStep. setting it to true will cause the step to not render unless the options defined in the override are selected
=> Conditionally add install steps

src/content/docs/apm/agents/apm-no-stack-traces.mdx
A template for new general APM category 'No stack traces' doc, that will be useful for all language agents. This was requested by someone in documentation slack channel.
=> new(apm no stack traces): new doc

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
Work done: 
Make it clearer that one permission is about changing contract for retention, and other is for adjusting within the contract for specific data or specific accounts.
=> fix(retention): clarify caps

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
- remove Debian 8 and 9 because they are EOL
- update curl command to use gpg due to deprecated apt-key
=> Updates to Debian

src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx
small fix to update the scope of the "units customization" to include area charts, not bar charts (which are not time series and don't have this option).
=> fix: update option from bar to area chart for units

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
Reverts newrelic/docs-website#10621
I'm a Unified API engineer reverting an incorrect change in the docs. https://api.newrelic.com/graphql is the endpoint used for requests. https://api.newrelic.com/graphiql is the API explorer UI and doesn't accept POST requests or API key auth.
=> Revert "Updated the graphql URL"

src/content/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent.mdx
The MacOS configuration file location differs by chipset. On a Mac with a Silicon processor, /usr/local/etc/.. doesn't exist.
Added chipset clarification to label of current location and the location for Macs with Silicon processors.
=> Update MacOS infra agent filepath

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx
This adds templates for PagerDuty, OpsGenie, VictorOps and xMatters.  It also updates and corrects several of the existing mapping and webhook template entries.  Finally, it updates the table to be more consumable since many of the notes weren't helpful or descriptive and that column took room away from the expressions.
=> Adding and updating templates

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
sumOfSquares is a timeslice field that can be retrieved using getField, but it's not in the docs
https://staging.onenr.io/0M8jqPn0GRl 
https://issues.newrelic.com/browse/NR-77684
=> fix: NR-77864 Add sumOfSquares to the list of timeslice fields for getField()

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8150.mdx
**We're anticipating a release on Monday, January 9. Please hold this PR until the release is ready.**
* Updates documentation for the Ruby agent's 8.15.0 release
* EOL Policy
* Release notes
* Configuration options 
* Checks the "Requirements and Supported Frameworks" documentation to update additional library major versions we've supported for a while
cc @homelessbirds
=> AM JANUARY 9 -- chore: Update Ruby agent documentation for 8.15.0 release

src/content/docs/logs/ui-data/parsing.mdx
Add two missing } on the grok expression examples (Thanks @marcelschlapfer)
Just fix the grok expression to work as it should.
No
=> fix: adding trailing "}" to grok expression examples

src/content/docs/apm/agents/manage-apm-agents/app-naming/use-multiple-names-app.mdx
Work done: 
* Removed outdated 'Manage Insights data' reference, as that UI no longer exists. Replaced with reference to drop data. 
* Clarified there are other options that may be preferable due to the duplicate data issue.
=> multiple app names doc: remove 'manage insights data'

src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp-moderate.mdx, src/content/docs/security/security-privacy/compliance/certificates-standards-regulations/soc2.mdx, src/content/docs/security/security-privacy/compliance/regulatory-audits-new-relic-services.mdx
-- Updating our Certifications and Regs documents since we have our SOC 2 Type 2 reports. This last cycle covered both NR1 and Pixie, updating and adjusting dates accordingly.
=> Updating Certification dates for SOC2 + FedRAMP

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1221.mdx
Update Dec 29 2022: team had been blocked from deploying. 
Release notes update for Browser Agent release version 1221.
=> chore: Browser Agent 1221 Release - 1/9 12pm

src/templates/docPage.js
this changes the GraphQL query for the docPage template to use the `tableOfContents` field instead of `mdxAST`. `tableOfContents` is a less expensive field to access since it doesn't require the AST to be generated for every MDX page, but it does take more string parsing to get usable data
=> switch from `mdxAST` to `tableOfContents`

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-comparison.mdx
Service map is now in production for OTel services, so we have parity now with APM agents.
=> Service maps now supported for OTel services

src/components/TileSelect/TileOption.js, src/components/TileSelect/TileSelect.js
We had some tiles with overflowing contents, this wraps the text within tiles so they don't become super long
=> Fix tile select css bug

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
Per discussion with Alicia, Amy, and Michelle, added the following terms to Usage page in style guide: AIOps, DevOps, InfoSec, and InfraOps.
=> Added new terms to Usage page

src/install/config/java.yaml
I mistakenly had removed the conditional second step (app server selections) after you initially choose Maven or Gradle in the first step. This simply adds them back. For example, if you select "Maven" in the first question, you'll get a second question about which application server you want to use and the relevant app server details show up later in the steps.
=> Java branching: Re-add step 2 for maven and gradle selections

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
It is not clear how facets are selected for COMPARE WITH NRQL queries.  This PR adds an info box explaining that the SINCE...UNTIL time range is used when selecting facets for the result and not the prior time range being compared.
https://issues.newrelic.com/browse/NR-41039
=> fix: add caveat regarding facet selection for COMPARE WITH queries

src/components/NavFooter.js, src/i18n/translations/en/translation.json, src/i18n/translations/jp/translation.json, src/i18n/translations/kr/translation.json
The 'see our 500+ quickstarts' nav footer was hardcoded in english, this adds it to the translation json so it can be dynamic instead
=> Add translate functionality to nav footer

.github/CODEOWNERS
Updates code owners file to try to catch as many relevant file types as possible for docs engineering review.
You [cannot negate pattern matches](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) unfortunately, so it seems you'd have to specify all files/dirs you want to own.
I also updated the docs eng team setting to auto assign two people from the team via round robin. seemed to work on this PR at least 😬
=> chore: update codeowners for docs eng files to review

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications.mdx
Add clarifying callout that specifies that the values are case-sensitive. I am uncertain if this should be a tip or a warning (probably warning), but I can no longer find the docs on callouts. Please change if you deem it necessary!
=> Add clarifying callout

src/content/docs/logs/logs-context/net-configure-logs-context-all.mdx
The current .NET local log decoration for JSON instructions are not correct.  This updates them with better information while we determine a better method of setting up the JSON format.
This removes the examples for JSON since they don't work and instead informs the customer that some custom work will be required.  We are hoping to address this in future and provide a better example or maybe a full project.
=> chore: Update .NET local log decoration JSON instructions

src/content/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions.mdx, src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation.mdx, src/content/docs/apm/agents/ruby-agent/api-guides/ruby-custom-metrics.mdx, src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
The ruby agent team tested the procedures on this page with Rails7. Remove the callout warning.
=> Remove Rails7 callout

gatsby-config.js
per gatsby docs: "'no-cache' permits a cache to serve cached content as long as it validates the cache freshness first"
we're having a lot of client side cache issues right now, hopefully this will clear some of that up
=> Set no-cache on all page headers

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
* Remove the line "List of services from the simple definitions (synthesis rules):" from the entity list
* My IDE just removed automatically some trailing spaces.
=> Remove `simple definitions` distinction in entity list

src/content/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details.mdx, src/data-dictionary/events/PageViewTiming/cumulativeLayoutShift.md, src/data-dictionary/events/PageViewTiming/firstContentfulPaint.md, src/data-dictionary/events/PageViewTiming/firstInputDelay.md, src/data-dictionary/events/PageViewTiming/firstInteraction.md, src/data-dictionary/events/PageViewTiming/firstPaint.md, src/data-dictionary/events/PageViewTiming/interactionType.md, src/data-dictionary/events/PageViewTiming/largestContentfulPaint.md
There are some inaccuracies and redundancy around the current browser agent's page view timings and details. This PR cleans them up as a basis for future work to add more.
n/a
n/a
=> docs: Update page view timings in dictionary (BA current rls)

src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx
We are releasing a new version of nri-elasticsearch which adds support for newer versions.
This PR updates the supported versions requirements section to elastic v7.x and v8.x, removes 4 metrics that are already deprecated and adds a small note on 4 other metrics that are deprecated only on elastic version 8. We still support them on version 7
=> updates elasticsearch supported versions

scripts/validate-install/schema.js, vale.ini
This has a couple of housekeeping items 🧹 
1. Update vale to only look in the src/content folder (mostly to ignore i18n)
2. Update the verify install script schema with the new isConditionalStep override type
=> Update vale and verify-install script

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/attributes/nodejs-agent-attributes.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx, src/content/docs/logs/logs-context/configure-logs-context-nodejs.mdx, src/i18n/content/jp/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/i18n/content/jp/docs/apm/agents/nodejs-agent/attributes/nodejs-agent-attributes.mdx, src/i18n/content/jp/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx, src/i18n/content/jp/docs/logs/logs-context/configure-logs-context-nodejs.mdx, src/i18n/content/kr/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/i18n/content/kr/docs/apm/agents/nodejs-agent/attributes/nodejs-agent-attributes.mdx, src/i18n/content/kr/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent.mdx, src/i18n/content/kr/docs/logs/logs-context/configure-logs-context-nodejs.mdx
* Our team had to change how we deploy our auto-generated API docs and URLs no longer work with `/docs` in the href.
=> fix: updated links to node-newrelic api docs to strip /docs

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Adds notice to .NET Agent configuration for app pools setting that lets folks know that the seeing only works for in-process IIS hosted applications. 
This is related to the following bugs:
https://github.com/newrelic/newrelic-dotnet-agent/issues/1353 or https://issues.newrelic.com/browse/NEWRELIC-6368
=> fix: Add notice to .NET Agent configuration for app pools setting

gatsby-config.js, package.json, yarn.lock
bumps theme to 4.16.0 and adds `newRelicRequestingServicesHeader` theme option so Tessen events will include a `loggedIn` field
=> chore: bump theme to 4.16.0

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
* This removes an example URL that won't work for FedRAMP customers. 
* I overlooked this change from https://github.com/newrelic/docs-website/pull/10975 and am fixing it here. 
=> fix(OTel): remove port 443 example from HTTP

src/content/docs/style-guide/writing-docs/processes-procedures/rename-or-redirect-document.mdx
Added this URL that doesn't work (https://docs.newrelic.com/docs/style-guide/rename-or-redirect-document/) to the [Rename or redirect a document](https://docs.newrelic.com/docs/style-guide/writing-docs/processes-procedures/rename-or-redirect-document/) page.
=> fix(Style Guide): Fixed a URL

src/content/docs/logs/log-api/introduction-log-api.mdx
* What problem do this PR solve?
There are some restrictions to query `appId` attribute on logs, so this PR adds a line of info under attributes that has a restriction.
=> feat(logging): Add info about restricted attribute name appId behaviour

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-baseline-ingest-guide.mdx
Seems like `entityType` no longer works but `eventType()` does.
working example:
```
FROM Mobile, MobileRequest, MobileRequestError, MobileSession, MobileHandleException, MobileCrash select rate(bytecountestimate() / 10e8, 1 day) as 'GB Ingest' facet appName, eventType() limit 100 TIMESERIES since 1 day ago
```
=> fix: change `eventType()` to `entityType()`

src/content/docs/apm/agents/net-agent/custom-instrumentation/create-transactions-xml-net.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Updates the .NET Agent documentation to describe a new custom instrumentation feature some new framework compatibilities. These changes will be valid with Agent 10.6.0, due to be released tomorrow (1/24/23).
=> Documenting new .NET version filtering feature

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration.mdx
Removing the spans removes some extra styling, but I don't think it affects the readability of the text. 
with span
without
=> fix: remove unsupported html elements

gatsby-config.js, src/components/MDXContainer.js
the scroll was scrolling to the point on the page where the header would be if all of the images had a height of 0. i think this was happening because the scroll height was getting calculated before the images had loaded due to lazy loading. turning that off seems to fix the issue completely 
example page:
old: https://docs.newrelic.com/docs/codestream/how-use-codestream/performance-monitoring/#investigating-errors
new: https://docswebsitedevelop-lizturnofflazyload.gatsbyjs.io/docs/codestream/how-use-codestream/performance-monitoring/#investigating-errors
=> Remove img lazy load to fix scroll

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
Adds 10.6.0 to EOL list, removes one older version that has reached EOL.
=> Releasing .NET Agent 10.6.0

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/service-characterization-optimize-telemetry-data-guide.mdx
=> chore: update links to correct locations

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx, src/content/docs/change-tracking/change-tracking-introduction.mdx, src/nav/apm.yml
Here are some fast-follow fixes from today's change tracking docs:
* Fix the link in the left navigation for the old deployment marker feature under APM.
* Clarify the anchor links in the third paragraph of the introduction to change tracking.
* Add change tracking as an item to the table in the introduction to NerdGraph.
=> Add change tracking topics to GraphQL tutorial list, and fix links

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-6-0.mdx
Adds missing StackExchange.Redis feature to release notes.
=> fix:Add missing change to .NET 10.6.0 release

src/content/whats-new/2023/01/whats-new-1-25-in-synthetics-pricing.md
This post provides updates on synthetics monitoring pricing, with synthetics checks now available above the free usage limit for a rate of $.005 per check. It should be posted as soon as possible and does not need additional review by another product marketing manager.
=> feat(whats-new): synthetics checks pricing update

src/content/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations.mdx, src/content/docs/infrastructure/microsoft-azure-integrations/get-started/introduction-azure-monitoring-integrations.mdx, src/nav/infrastructure.yml
Liaison work: 
Making better general landing page for our azure-related offerings. 
Moving stuff from 'intro to azure integrations' into the 'set up azure integrations' and making that more of the landing page/intro for the azure infra integrations
=> Improve azure intro doc 

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/alerts-ai-overview-page.mdx
both are deprecated and only a few customers would still have it for a short duration.
Environment link was broken (the referenced section was already  removed)
=> removing notion of environments & configuration

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor.mdx
This fixes the broken link `Azure Monitor metrics Documentation`
=> Define redirect on Azure Monitor Integration docs

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
Some liaison work: clarify what 'All product admin' role and 'Admin' group really mean, and make it clearer that they lack the 'administration settings'.
=> fix(user mgmt): clarify admin access

src/@newrelic/gatsby-theme-newrelic/components/NavItem.js
=> fix: nudge navitem padding

src/nav/alerts-applied-intelligence.yml
I deleted two deprecated docs in [this PR](https://github.com/newrelic/docs-website/pull/10979/files) but neglected to delete them from the nav. Fixing here.
=> fix(alerts ): fixing broken nav links

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
=> (81695) style(Sonic): Optimize API keys

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition.mdx
Removed an `iframe` to use the `Video` component to ensure machine translation workflows will run.
=> fix: remove iframe for Video component

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Update documentation for supporting up to 24 hour threshold durations.
* This new support is scheduled to go live on January 31st, 2023.
* Updated any references to the maximum threshold duration, which were limited to the gap filling section.
=> Update create-nrql-alert-conditions.mdx (Please merge on Jan. 31st)

src/content/docs/apm/agents/nodejs-agent/installation-configuration/enable-source-maps, src/content/docs/apm/agents/nodejs-agent/installation-configuration/enable-source-maps.mdx, src/nav/apm.yml
Transpiled applications in JS will show error traces pointing to built files. A developer reading these will have to translate these to understand which part of the source code was involved in the error. Node.js, however, supports enabling source maps, so that error traces can display files, line numbers, and function names from source code instead of built/transpiled/minified code. This produces a much more useful error trace.
Closes NEWRELIC-5806
=> Added page documenting Node.js source map support

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Add 2.19.0 to the list of verified compatible MongoDB.Driver versions for the .NET Agent.
=> .NET Agent: Add 2.19.0 to list of verified compatible MongoDB.Driver versions

src/content/docs/new-relic-solutions/observability-maturity/introduction.mdx
Work done: 
* Added mention of implementation guide, clarifying that beginners should go there
* Added introductory context for each of the four value driver sections
* Took out link to style guide 'OM guide template', as I'm not sure we want to encourage customers to do that (and don't think they ever will do it) and replaced that with note about giving ideas/comments using feedback button
=> OM section: improve intro section

src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/browser-monitoring-nodejs-agent.mdx, src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-instrumentation.mdx, src/content/docs/apm/agents/nodejs-agent/hosting-services/nodejs-agent-heroku.mdx, src/content/docs/apm/agents/nodejs-agent/hosting-services/nodejs-agent-microsoft-azure.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent-docker.mdx, src/content/docs/apm/agents/nodejs-agent/troubleshooting/troubleshoot-your-nodejs-installation.mdx
We have many places in our Node.js agent that still refer to manually editing your app and adding `require('newrelic')`.  The preferred way to do this now is via the `-r` flag to the Node.js runtime.  I updated all instances and still called out the legacy method in places where applicable.
=> fix: clean up references to require("newrelic") in favor of -r

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-20-3.mdx
The previous 3.20.3 release notes doc had incorrect metadata. This corrects that so the correct release note shows as current.
=> FIX(Go agent) Release notes for 3.20.3 metadata correction

src/content/whats-new/2023/02/what-new-02-01-tls-eol.md
what's new announcing end of life for tls 1.0/1.1 requiring tls 1.2+.  Post should be done on 2 Feb 2023 to keep in calendar line with EOL activity on that day.
=> whats new: tls eol feb2 23

src/content/docs/logs/log-api/introduction-log-api.mdx
Adds documentation around ISO8601 timestamp support for Logs
N/A
N/A
=> Adds support for ISO8601 timestamps in logs

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx
This PR updates the CSP section of the browser agent compatibility requirements doc, as recommended in https://issues.newrelic.com/browse/NR-77599 .  It was missing a route for EU customers.  But beyond this, the list of domains was getting long and could be included as `*.nr-data.net` if desired.  All specific subdomains should still be configurable if the `*` does not meet the customer's needs.
This PR also fixes an error in our "supported versions" in the same document.
=> [FIX] CSP recommendations in Browser Compatibility Document

gatsby-config.js, gatsby-node.js, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8150.mdx
* The [FY23Q4 Agent Update Recommendations project (Internal)](https://newrelic.atlassian.net/wiki/spaces/TDP/pages/2700443968/APM+Agent+Updates+Recommendations+CDD) needs new fields added to agent release notes.
* Ticket: https://issues.newrelic.com/browse/NR-84934 
Preview link for agent-releases JSON: https://docswebsitedevelop-kaylareopelledocswebsiteagentu.gatsbyjs.io/api/agent-release-notes.json 
Example front matter for agent release note MDX:
```mdx
---
subject: Ruby agent
releaseDate: '2022-12-14'
version: 8.14.0
downloadLink: 'https://rubygems.org/downloads/newrelic_rpm-8.14.0.gem'
features: ['first feature', 'second feature']
bugs: ['first bug']
security: ['first security']
ingest: ['first ingest','second ingest','third ingest']
---
```
Example new entry in agent-releases JSON: …
=> feat (agent release notes): add new fields

src/content/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph.mdx
* Running the curl command with `https://api.newrelic.com/graphiql` does not work.
* Changing from `https://api.newrelic.com/graphiql` to `https://api.newrelic.com/graphql` works. Verified on my own terminal.
=> docs: Change curl command destination

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Updates to the PHP agent compatibility page clarifying Codestream/CLM support as well as recommended PHP versions.
=> fix(PHP agent): Add Codestream/CLM to compat page

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-requirements-supported-frameworks.mdx, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8160.mdx
The Ruby agent team is preparing to release version 8.16.0. This PR includes relevant documentation updates.
=> chore (ruby agent): Content for version 8.16.0

src/content/docs/vulnerability-management/integrations/intro.mdx
This PR fixes the minimum version of the Ruby agent required for New Relic's Runtime SCA to operate
=> fix: Update Ruby APM agent version supported by Vuln Mgmt

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
Clarifying because 'Marker' as a namespace wouldn't be clear what it is
=> fix(retention): add link to change tracking

.github/workflows/release.yml
Adds a step on the release github workflow (when PRs close to `main`) to send a deploy marker to New Relic. Uses the release tag created in earlier step as release version name.
I also added the two required env vars to repo secrets:
* `NEW_RELIC_API_KEY_DEPLOY_MARKERS`: created new user key specifically for this
* `NEW_RELIC_DEPLOYMENT_ENTITY_GUID`: added the entity guid for prod app so we can see those markers alongside prod data in NR UI
- https://docs.newrelic.com/docs/change-tracking/ci-cd/change-tracking-github-actions/
=> chore: add new relic deploy marker step on releasePRs

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
PHP agent team is EOL'ing PHP 5.5 and 5.6 in June 2023 and this change adds this information to the compatibility page.
=> Php 55 56 eol

package.json, yarn.lock
this fixes the collapser visibility bug
=> chore: bump theme to 6.16.4

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx
In the 'Update your synthetic monitors', the current tip implies that not including the runtime will downgrade a monitor. However, you have to instead include runtime and set the attributes to empty strings ("") to downgrade the monitor.
'Update your synthetic monitors' section does not cover the use-case for downgrading monitors
Was told this by Engineering, verified in my test account
=> Changes 'tip' to cover third use-case

.github/workflows/release.yml
Recent deploy marker job failed on release workflow.
I believe because our entity is behind staging. Seems like we be able to use `staging` as region for CLI to send request to right place.
- https://github.com/newrelic/docs-website/actions/runs/4119431190/jobs/7113085120
- https://github.com/newrelic/deployment-marker-action
- https://docs.newrelic.com/docs/change-tracking/ci-cd/change-tracking-github-actions/
- https://github.com/newrelic/docs-website/pull/11411
=> chore: remove new relic deploy marker job

src/nav/apm.yml
The Node.js agent navigation tree had a link to the introduction to distributed tracing page under "Extend your instrumentation," but that meant that the left nav would light up for both Node.js and for the introduction to distributed tracing. Since we already have a distributed tracing topic under "Install and configure," I suggest we remove this left-navigation link.
=> Remove unwanted link in Node.js agent to distributed tracing introduction

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx, src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1224.mdx
These release notes coincide with our roll-out of v1224 of the browser agent. The release date on our repo is February 8 (today) and the roll-out is targeted to begin Friday, February 9.
=> Browser agent release v1224

src/content/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction.mdx
This doc referred to a video that was missing. I added it back in.
=> fix(APM): Added missing video that the doc references

gatsby-config.js, gatsby-node.js, src/content/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-8150.mdx
This is a followup to [the original PR](https://github.com/newrelic/docs-website/pull/11306) that added four new fields to the front matter of agent release notes. This PR updates two field names to be pluralized for consistency.
`feature` -> `features`
`bug` -> `bugs`
@clarkmcadoo @LizBaker @roadlittledawn
=> fix (agent release notes): update front matter field names 

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-comparison.mdx
We added support for deployment markers for OTel recently. This PR updates the deployment markers section to reflect this change.
However, I need stakeholders to weigh in on what to update the status icon to -- it's not full parity with NR APM, because NR APM will also show deployment markers on Transaction and DB charts, whereas it's only available for the three Summary charts for OTel services.
=> Updates deployment markers support for OTel

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80600.mdx
* Add release notes for version 8.6.0 of the Python Agent.
* Deprecate version 5.4.1.134.
READY FOR REVIEW
MERGE WITH MORNING RELEASE Feb 10th 2023.
=> Feb 10 AM: new Python Release 8.6.0 docs

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-kafka-confluentcloud.mdx
The `$` prompt symbol is placed by the code formatting in the final docs page. We don't need to include it in the Markdown code block.
Confusion about what commands to run
=> [Bug] Update opentelemetry-collector-kafka-confluentcloud.mdx

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Support for the Kohana framework was removed in PHP agent release 9.17 and this fix removes it from the compatibility page.
=> chore(PHP agent): Remove Kohana from supported frameworks

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
Removing reference to unsupported Kohana framework for PHP agent.
=> chore(PHP agent): Remove kohana framework from config docs

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
This updates the release name to `newrelic-bundle` as seen in the chart docs and elsewhere: https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle#configure-components
The chart release name must be referenced in other Helm commands used throughout the lifecycle of the deployment, and other docs use `newrelic-bundle` for the release name.
Reference to release name in nri-bundle chart docs: https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle#configure-components
N/A
=> [Chore] Update install-kubernetes-integration-using-helm.mdx

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1225.mdx
Removes a section from the browser agent v1225 release notes. The redacted text does not accurately reflect the release.
=> Edit out an incorrect release note

src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-6-0-318.mdx
The PHP agent team is working on releasing the agent with code level metrics (CLM) on by default.
Currently this release is planned for Monday, February 13th.
This PR handles the Release Notes for this 10.6.0 release, as well as updates the EOL matrix for PHP Agents.
This PR is in conjunction with #11391
=> Release 2/13: Php agent release 10.6

src/content/docs/apm/agents/python-agent/getting-started/instrumented-python-packages.mdx
This PR remove the Maximum Package Version column from the instrumented database table in the Python Agent docs (since now they are all at "latest")
=> Remove Maximum Package Version from Python Agent docs

scripts/actions/utils/handlers.js, src/components/DocTile.js, src/components/MDXContainer.js, src/pages/index.js
This moves the doc tile component out of the index page and adds an optional wrapper for formatting.
passing `numbered` to the wrapper will auto number the tiles, but you can also pass a number to individual tiles (not used in the wrapper) via a `number` prop. there is also a label prop which takes an object with text and a color.
tested serialization and deserialization without issue
=> Move doc tile component

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx
This was supposed to be a small fix that got out of hand. I made a lot small improvements like
- add missing punctuation
-  wrapping code in backticks
- add syntax highlighting to one codeblock
- tried to make our style consistent. In yaml you don't need to use `""` for most strings unless they contain special chars like `\` or `,`
- so I removed `"` where they aren't needed (since we went back and forth) and added them where they would be needed (like where lists containing `,`)
=> chore: lots of minor improvements

src/content/docs/style-guide/ui-writing/button-labels.mdx
Changed "New Relic One" to "the New Relic platform."
=> Corrected use of "New Relic"

src/content/docs/new-relic-solutions/best-practices-guides/cx-improve-page-load.mdx, src/content/docs/new-relic-solutions/best-practices-guides/cx-improve-web-uptime.mdx, src/content/docs/new-relic-solutions/best-practices-guides/full-stack-observability/overview-best-practices.mdx, src/content/docs/new-relic-solutions/overview.mdx, src/nav/alerts-applied-intelligence.yml, src/nav/apm.yml, src/nav/browser.yml, src/nav/new-relic-solutions.yml
NR-84528
Work done: 
Remove best practice guides from 'Guides' nav
Create 'Overview of best practice guides' that links out to the docs
=> fix(best practice guides): new overview doc

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
Adds 10.7.0 to EOL list, and removes 2 older versions that have reached EOL.
=> Releasing .NET Agent 10.7.0

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
Added a note about the IP ranges being reserved for New Relic use only.
=> chore(synth IPs): Added clarification

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-get-started-intro.mdx
Here's the Jira for this: NR-88389
=> OpenTelemetry: Fix link to Java tutorial from intro to setup

src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/set-max-event-pool-size.mdx
"When the pool size limit is reached, the New Relic Android agent will begin sampling events, discarding some old and some new events, until the pool of events are transmitted with the next harvest cycle." 
This line is repeated. Removed one entry.
=> Deduping few lines

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-10-7-0.mdx
Add release notes for the .NET Agent 10.7.0 release.
=> Add release notes for .net agent 10.7.0

src/templates/docPage.js
Conditionally rendering the docs template based on having mounted means swiftype doesn't get access to tags set within the docs page seo component etc. we're removing this for now and working on a fix
=> Remove banner from doc page

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts.mdx
This doc had previously displayed the wrong endpoint for listing location failure conditions. I've added the correct one (instead of passing `policy_id` as a parameter, you include it in the URL).
=> fix: Correct URL for listing location failure conditions

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80700.mdx
Add release notes and documentation for version 8.7.0 of the Python Agent.
* Add release notes for 8.7.0.
* Update EOL table and deprecate old version.
* Fix previous version release date.
* TODO: Add batching and compression configuration options to configuration docs.
=> 02/17/23 - Release Python Agent 8.7.0

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
Update the .NET Agent compatibility and support document (for .NET Framework only) to document our instrumentation support for MSMQ.  No specific version information is called out because MSMQ client support is built in to .NET Framework.
=> Add MSMQ support to compatibility doc

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm.mdx
Fix the indent of step3 of "Install the Kubernetes integration using Helm" make the aforementioned indent to be consistent to the one in the "Configure the integration" on the same page
=> Update indents of install-kubernetes-integration-using-helm.mdx

src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx
The legacy runtime upgrade UI has been deprecated.
=> chore(removeLegacy): Removed legacy runtime upgrade details

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx
There is not precedence between user type and access control configuration, it is an intersection calculation. A user must have access both from their user type and their access control configuration.
=> Correct wording about user type access

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx
Update browser support versions with link to same resource the browser agent team uses to determine tests to run, this gives the customer accurate insight on which specific browsers are supported.
This PR updates the supported browser versions UL items with links to the resource that is used by the browser agent team to determine test support.
Gives clarity to customers on which exact browser versions are being described
=> Update browser support versions with link

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-13-2.mdx, src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-4-0.mdx
The team automating upgrade processes noticed we forgot to add release notes for some past releases.  This backfills it
=> fix: backfilling release notes we missed from previous releases

src/content/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2.mdx
* Customer feedback: statsD documentation missing a link to statsD Helm chart.
=> Added link to statsD helm chart

src/content/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic.mdx, src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/setup-prometheus-agent.mdx
Prometheus Agent doesn't scrape by default anymore Prometheus integrations in the guided install
=> Modify Prometheus Agent data ingest default option

src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts.mdx, src/content/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices.mdx
- Also update to incident/issue nomenclature
* Recent changes to the alerts product now allows for conditions to have _only_ a warning threshold (critical is no longer required, but at least one threshold is)
* Also updates from old "violation/incident" nomenclature to updated "incident/issue" nomenclature
=> docs(Alerts): Update information about thresholds

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-puppet.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-ansible.mdx, src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-using-chef.mdx
* These IaC integrations had an old reference to "learn more" from the github repo. We don't have this callout in other integrations and it's confusing for customers.
=> Removing support via Github reference in ansible/puppet/chef

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet.mdx
Removed at the recommendation of  @alanwest, we copied these required runtimes from other outside docs and they are almost certainly our of date because lambda now accepts more versions of .NET. It was decided it's better to allow the linked docs to tell customers what is acceptable.
=> fix: removed required .net runtimes

src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-optimize-ingest-guide.mdx
The Kubernetes Integration v3 and above allows filtering which namespaces are scraped by labelling them. By default all namespaces are scraped.  This PR adds instructions to the guide on how to use this feature.
=> feat: Add K8s namespace filtering instructions

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx
Infrastructure agent for macOS 13 (Ventura): https://issues.newrelic.com/browse/NEWRELIC-6820
=> docs: add macos Ventura 13 support for infrastructure agent

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-800.mdx
Modify the *important* section of the Java agent 8.0.0 release notes to suggest updating to v8.0.1, that corrects the issue.
=> (Publish 9AM PST on 2/23/23) Update Java Agent 8.0.0 release notes

src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
More work based on changes made in https://github.com/newrelic/docs-website/pull/11652/files and https://github.com/newrelic/docs-website/pull/11648/files
Basically: we previously described user type as taking 'precedence' over roles, but this isn't true; both roles and user type work in concert to determine permissions. You can be restricted by either one, in practice.
=> fix(user mgmt concepts): clarifying type vs roles

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-traces.mdx
This PR updates our OpenTelemetry best practices for tracing to clarify how resource attributes are handled. This was done as a result of at least one customer being surprised when they compared the size of tracing data in NRDB compared to the payload being sent in.
=> Update documentation to make note of resource attribute decoration on spans

src/content/docs/codestream/troubleshooting/security.mdx, src/nav/codestream.yml
In a month or two when we launch unified identity, the codestream.com website will be going away and we need to find a new home for our /security page. I know that this may not be the perfect spot, but it should do for now. Once CodeStream is fully migrated to the NR platform later in the year the page will go away.
=> Add security article

src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx
This PR adds [a clarifying note](https://github.com/newrelic/docs-website/issues/10686) about the usage of `apdex_t` for the Python Agent
=> Add clarifying note for apdex_t usage in Python Agent

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx, src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1226.mdx
Release notes for Browser Agent release 1226
Note: I accidentally merged the original PR too soon, so this a duplicate of https://github.com/newrelic/docs-website/pull/11659.
=> ON HOLD (scheduled for February 22nd) docs: Browser Agent Release 1226

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors.mdx
Issues with clicking on the the link to download the host file.  Browser appears to download and delete immediately, or take a long time to verify download.  Using HTTPS instead of HTTP, the file downloads immediately, as expected.
=> fix: link to host file should be HTTPS

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
In order for the Entity Status Daemon (ESD) to find the associated Synthetic monitor, the ESD needs an entityGuid to be returned as part of the data gathered by the alert condition query. Moving the identifying attribute out of the `filter()` function will accomplish this and allow the monitor's status to turn red or green rather than remain grey in Synthetics.
=> fix: the ESD needs an entityGuid to be returned

src/content/docs/logs/ui-data/drop-data-drop-filter-rules.mdx
`source` is not a public attribute available to customers in NerdGraph on drop rule creation. Its usage should not be recommended in this document.
* Removes the recommendation of a NerdGraph input field that is not available to the customers in the described scenario 
* The document recommends setting a `source` attribute while creating a new drop rule in NerdGraph but such input field is not available in `nrqlDropRulesCreate`: 
* If your issue relates to an existing GitHub issue, please link to …
=> Fix: Update drop-data-drop-filter-rules.mdx

src/content/docs/apm/agents/net-agent/other-installation/net-agent-install-resources.mdx
* What problems does this PR solve? The website was talking about setting an app name, but the example was related to setting a license key
Context for environment variable: https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/app-naming/name-your-application/
=> docs: Use NEW_RELIC_APP_NAME in example code

src/content/docs/synthetics/synthetic-monitoring/using-monitors/device-emulation.mdx
Added the version of job manager required to use device emulation on private locations.
=> fix(DeviceEmulation): Added job manager version requirements

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
duplicated section ID like `paragrp-enabled` made linking impossible in some places
=> fix: section IDs duplicates corrected

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
The PHP team would like to correct the minimum GLIBC version supported for the PHP agent.  We have determined the value we used was too new as the operating systems we say we support use older versions than 2.35.  The new minimum version is from Centos 7 which is a supported OS and uses the oldest GLIBC of any of the ones we support.
=> fix(PHP agent): Correct minimum glibc version supported

src/content/docs/apm/agents/python-agent/getting-started/python-agent-eol-policy.mdx
The Python agent EOL table included several outdated agent versions. This PR removes those unsupported agent versions.
=> Remove unsupported Python agent versions from EOL table.

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60401158.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60402159.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60403160.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60404161.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60800163.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-61000165.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70000166.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70200167.mdx
This PR adds metadata to the Python Agent for versions 6.4.1.158-7.2.0.167 of the agent.
=> Add metadata backfill to Python Agent

src/data/nav-footer-cta.json
this adds a json object with regex for the APM intro doc that isn't under the /docs/apm path
=> chore: add json for apm js doc pathname

src/pages/introduction-apm.js
We were having an issue where, upon redirecting from the original mdx url, another gatsby-focus-wrapper would get injected into the DOM and instead of being a wrapper, would render text. this code removes the 2nd wrapper via #gatsby-focus-wrapper
to QA:
visit, `/docs/apm/new-relic-apm/getting-started/introduction-apm/` and look at the bottom of the screen after the redirect
a thread i saw for how this isn't configurable - https://github.com/gatsbyjs/gatsby/issues/7310
=> gatsby-focus-wrapper renders twice

src/content/docs/apis/intro-apis/new-relic-api-keys.mdx
The section on user keys is ambiguous enough to potentially mislead a customer into thinking that the REST API supports cross-account user key authentication. However, our REST API endpoints only recognize a user key as being associated with its root account.
This edit attempts to clarify that point.
=> fix: Update new-relic-api-keys.mdx

src/utils/getAgentName.js
Right now the release notes under synthetics with 'node' in the subject are getting grabbed as part of the release notes json under the node agent. we should probably rewrite this but in the interest of time this is a quick fix
to test: 
check out the json at /api/agent-release-notes.json and command f for any of these versions:
(they may show up for other agents with overlapping version but none should show up under nodejs)
```
{
"date": "2022-09-23",
"version": "1.1.19"
},
{
"date": "2022-09-15",
"version": "1.1.17"
},
{
"date": "2022-10-04",
"version": "1.1.21"
},
{
"date": "2022-11-10",
"version": "1.1.25"
},
{
"date": "2022-10-04",
"version": "1.1.20"
},
{
"date": "2023-01-17",
"version": "1.1.31"
},
{
"date": "2023-01-17",
"version": "1.1.76"
},
{
"date": "2022-10-14",
"version": …
```
=> fix: Ignore synthetics node subjects

src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
The documented strategy for calling the method is wrong.
=> chore: Add correct class prefix to class method

src/content/docs/alerts-applied-intelligence/new-relic-alerts/get-started/choose-your-aggregation-method.mdx
Our docs provide a clear, concise example for the particular scenario in which you'd want to use the cadence aggregation method. However, we immediately follow it up with a contradictory statement:
> If you're currently using cadence, choose one of the other aggregation methods.
This edit softens the statement to note that we only advise against cadence outside of the case mentioned above it. Before going any further, though, I'd like @HenryTech to give this approach a review from his standpoint.
=> fix: Update choose-your-aggregation-method.mdx

src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-04x-or-lower.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050.mdx, src/nav/synthetics.yml
- The intro to scripted browser link was pointing to a synthetics intro page instead
- Added a reference to this doc and the helpful examples it contains from our browser runtime reference pages
=> fix(IntroLink): Fixed scripted browser intro link

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx, src/content/docs/apm/agents/php-agent/getting-started/php-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-7-0-319.mdx
This PR handles the necessary updates to our Release Notes, Compatibility page, and EOL table for the upcoming 10.7.0 PHP Agent release.
This release is currently planned for 03/08.
=> Release 03/08 - Php agent 10.7.0 release

src/content/docs/style-guide/ui-writing/punctuation.mdx, src/content/docs/style-guide/ui-writing/ranges-and-spans.mdx
Our style guide docs state that we should use en dashes for ranges and spans, but the docs themselves don't actually use en dashes in the examples. This PR fixes that. 🙂
=> fix(style-guide): Use en dashes as described

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Move where clause after select to fix syntax error.
Fixed a NRQL syntax error in the docs.
=> Fix synthetic alert syntax error

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions.mdx
Fixed incorrect NRQL syntax in a query example (`FROM` should not follow `WHERE`).
=> fix: Revise query example in NRQL conditions doc

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx
Our support team was recently confused about whether we still support .NET agent version 6.27.0, since it was not listed in this EOL policy document.  This PR adds it to the bottom of the list (replacing an old 8.x version that is past its EOL date) along with a footnote explaining the somewhat unusual EOL date. 
Our team's current understanding is that we continue to support the latest 6.x agent for customers who are still using .NET Framework 3.5, which Microsoft says it will support until January 2029.
Note: This probably isn't the right way to do a footnote, could somebody from the docs team suggest a better way?
=> Add 6x agent to eol policy

src/content/whats-new/2023/03/whats-new-03-09-clm-javaphpnodego.md
What's New Post set to go out on March 9 2023 - announcing code-level metrics for the remaining APM agents. Morning preferred.
I'm a PMM so does not require further review.
=> March 9th: feat(whats-new): clm for java php node go post

src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/disable-features.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/enable-features.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/record-handled-exception.mdx
https://issues.newrelic.com/browse/NR-91529
I added a callout to address confusion around recordHandledException in Swift code. 
I also didn't like the way the callout for disable and enable feature looked so I changed it.
=> Added a callout explaining not to use recordHandledException with Swift

src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-components.mdx
Fix reference to `newrelic-infrastructure` chart. As the next sentence makes clear, the actual daemonsets are nrk8s-kubelet and nrk8s-controlplane.
=> [chore] Update kubernetes-components.mdx

package.json, yarn.lock
Fixes trailing slash being added to search bar on 404 page
to QA: go to `/apache` and click into the search bar
=> fix: theme bump to fix 404 search slash issue

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
The Prisma instrumentation for the Node agent is a little idiosyncratic, so I turned the list into a table where I can add a Notes column to explain the idiosyncracy.
Closes NEWRELIC-6383.
=> feat(node agent): add Prisma as another supported datastore

src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-configuration.mdx, src/content/docs/synthetics/synthetic-monitoring/private-locations/job-manager-transition-guide.mdx
- Removed the limitation for custom job timeouts from the job manager transition guide
- Added config details for CHECK_TIMEOUT (Docker) and globals.checkTimeout (K8s) to the job manager configuration guide
=> feat(synth): Support custom job timeouts on Job Manager

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/arrays-in-nrql.mdx
string in NRQL are with single quote , double quote is invalid syntax
=> fixing quotes on contains

src/content/docs/alerts-applied-intelligence/notifications/notification-integrations.mdx
Removed a duplicated screenshot from the [PagerDuty section](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#pagerduty/).
=> fix(Alerts): Removing a duplicated screenshot

src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx
The tabs here were accidentally set as `### H3s`, leading to strange rendering and a poor viewing experience. This removes the header styling from them.
=> fix(sonic): Make tabs non-headers

src/content/docs/codestream/how-use-codestream/pull-requests.mdx
Link to #minimum changed to #minimum-qualifiers
=> Fix broken anchor link

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Spring Boot is not a library in and of itself.  It is a collection of Spring modules.  Our instrumentation targets certain libraries/modules and we provide instrumentation for a range of versions for some individual libraries.  It is misleading to say we support Spring Boot X, because we do not provide instrumentation for every library in Spring Boot.   Instead, we should list the libraries for which we provide instrumentation, along with the range of versions.  Removing this Spring Boot line achieves that.
links to related docs, …
=> Remove Spring Boot support designation

src/components/ToggleView/ToggleSelector.js, src/components/Tooltip.js, src/pages/index.js
In order to only show the tooltip on the `defaultView` on the initial page load only, we are considering these cases:
* User logged in, no selected view in storage -> renders `defaultView` -> show tooltip
* User logged in, `newUserView` saved in storage -> user toggles `defaultView` -> don't show tooltip
* User not logged in, no selected view in storage -> user toggles `defaultView` -> don't show tooltip
* User not logged in, `defaultView` saved in storage -> show tooltip
=> Only show tooltip on default view

src/utils/__tests__/getEOLDate.test.js, src/utils/getEOLDate.js
Created a new function called `getEOLDate()` that will programatically generate an EOL date based on a piece of software's release date and our EOL policy, which is described
[here](https://docs.newrelic.com/docs/licenses/end-of-life/notification-changes-new-relic-saas-features-distributed-software/#impact).
Function accepts two inputs: the first is the release date of the piece of software. The function assumes this input is a string in yyyy-MM-dd format. Second input is an override EOL date. If passed, the function will favor this EOL date over the generated one.
The intent of this function is to allow this repo to programatically generate the various EOL pages it supports, to ease the release process burden on NR developers (updating HTML programatically is hard and humans can forget …
=> feat: add function to generate EOL date

src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-12-0.mdx, src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-12-1.mdx
v9.12.1 of the Node Agent was published successfully today, March 15, 2023. 
We attempted a release of v9.12.0 yesterday, though that was not successfully published due to a problem in the NPM publishing process. Whatever that problem was, it continued to affect 9.12.0, so we've consolidated its release notes into the new patch release.
=> Node Agent release notes v9.12.1

src/content/docs/mlops/get-started/intro-mlops.mdx, src/templates/docPage.js
conditionally renders the banner based on logged in status and whether the user has previously dismissed the banner. only does so after mount, this fixes the hydration issue
https://docswebsitedevelop-sunnyfixsignupbanner.gatsbyjs.io/docs/mlops/get-started/intro-mlops/
=> add back signup banner

src/content/docs/apm/agents/ruby-agent/installation/ruby-agent-heroku.mdx, src/content/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring.mdx
Fix a typo in https://docs.newrelic.com/docs/apm/agents/ruby-agent/installation/ruby-agent-heroku/#configuring
=> chore(apm): fix typo in ruby-agent

src/content/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux.mdx
* AWS released Amazon Linux 2023, infra-agent release [1.39.0](https://github.com/newrelic/infrastructure-agent/releases/tag/1.39.0) adds support for it.
=> (Publish 3/16) Adding support for Amazon Linux 2023

src/content/docs/change-tracking/ci-cd/change-tracking-github-actions.mdx
https://github.com/newrelic/deployment-marker-action/releases/tag/v2.3.0
What problems does this PR solve?
* Updates `https://docs.newrelic.com/docs/change-tracking/ci-cd/change-tracking-github-actions/` page to follow updates from [the upstream `newrelic/deployment-marker-action`](https://github.com/newrelic/deployment-marker-action): 
* https://github.com/newrelic/deployment-marker-action/releases/tag/v2.3.0
=> chore: update tracking gha (action 2.1.0 -> 2.3.0)

src/content/docs/apm/agents/java-agent/custom-instrumentation/messaging-framework-instrumentation.mdx
Also fixed a strange line of code
```jv
if (recs.count() == 0) {
} else {
for (ConsumerRecord<String, String> rec : recs) {
processRec(rec);
}
}
```
to
```jv
if (recs.count() > 0) {
for (ConsumerRecord<String, String> rec : recs) {
processRec(rec);
}
}
```
=> chore: add language identifiers

gatsby-config.js, package.json, yarn.lock
Adds theme options to only generate a sitemap if in production. And to generate a robots.txt file that disallows crawling pages if not in production.
Unfortunately [gatsby cloud access controls](https://support.gatsbyjs.com/hc/en-us/articles/360056430174-Access-Control) only apply to build previews and not the hosted site.
Tested via theme demo site build and no sitemap was generated.
Includes theme bump that excludes `/embed` pages from sitemap for good measure.
This may / may not be full solution to google indexing docs-dev.newrelic.com. we may need to add meta robot noindex tags to all pages if in staging site or add auth or something else ¯\_(ツ)_/¯
- https://github.com/newrelic/gatsby-theme-newrelic/pull/899
- https://developers.google.com/search/docs/crawling-indexing/robots/intro
- …
=> fix: add theme config options for sitemap generation and robots

src/content/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration.mdx
SELECT cluster.datacenter, fullHostname, cluster.name, cluster.rack, entityName, hostStatus, (db.loadBytes /10e3) AS 'kb db.loadBytes' FROM CassandraSample 
https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/tools/nodetool/toolsStatus.html
https://cassandra.apache.org/doc/latest/cassandra/troubleshooting/use_nodetool.html
An example of a common cli output for Cassandra written in NRQL format
https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/tools/nodetool/toolsStatus.html …
=> Giving Example of how to use NRQL for nodetool

src/content/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration.mdx
Removing the Open Preview callout as the integration [has been promoted to GA](https://github.com/newrelic/infrastructure-agent/releases/tag/1.39.1).
=> Remove open preview callout nri-winservice

src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-manual-install-infrastructure-agent-linux.mdx
Currently, the architecture in the manual installation one-liner is set to `amd64` . This PR replaces it with the `ARCH` variable.
=> infra_agent: fix manual installation arch

src/content/docs/infrastructure/host-integrations/host-integrations-list/ansible-controller-integration.mdx
Modified the link to the observability page from https://newrelic.com/instant-observability/ansible to https://newrelic.com/instant-observability/ansible-automation-controller
=> Incorrect link to Ansible Automation page

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-62700.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8266300.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8271390.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8280.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-82900.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83000.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83100.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83200.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83902.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-84010.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-84100.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-84110.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9000.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9100.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9110.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9200.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9500.mdx
Adds `features`, `bugs`, and `security` fields to front matter in release notes for currently supported versions of the .NET Agent.
Note: There will be a second PR with additional updated release notes.
=> .NET Agent metadata update

gatsby-node.js, plugins/gatsby-plugin-generate-doc-json/gatsby-node.js, src/content/docs/more-integrations/terraform/terraform-intro.mdx, src/content/docs/more-integrations/terraform/terraform-modules.mdx, src/content/docs/more-integrations/terraform/terragrunt.mdx, src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx, src/content/docs/style-guide/structure/steps.mdx, src/i18n/content/jp/docs/more-integrations/terraform/terraform-intro.mdx, src/i18n/content/jp/docs/more-integrations/terraform/terraform-modules.mdx, src/i18n/content/jp/docs/more-integrations/terraform/terragrunt.mdx, src/i18n/content/kr/docs/more-integrations/terraform/terraform-intro.mdx, src/i18n/content/kr/docs/more-integrations/terraform/terraform-modules.mdx, src/i18n/content/kr/docs/more-integrations/terraform/terragrunt.mdx, src/templates/docPage.js, src/utils/constants.js
Now that we are using embed pages in nr1-help-xp, we don't have to care about new components going through our DLS. 
This PR
* removes all isTutorial type logic
* removes all uses of the isTutorial frontmatter in MDX
* Updates the style-guide
=> chore: remove isTutorial logic and frontmatter

src/content/docs/browser/browser-monitoring/getting-started/browser-agent-eol-policy.mdx, src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-v1228.mdx
- Adds release notes for browser agent version 1227.
- Adds EOL entry for browser agent version 1227.
=> Browser agent v1228 release notes & EOL

src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing.mdx
some clarifications, for non-Core user billing model, how we refer to 'monthly provisioned user'.
=> fix(original user pricing): clarify 'monthly prov user'

src/content/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph.mdx
From support, the allowed values for `regionCode` in the `accountManagementCreateAccount` mutation are missing.
- add mutation example with `regionCode`
- note the valid values are `us01` and `eu01`
- remove note about only one region being allowed (that's not always true)
=> fix(manage-accounts-nerdgraph): document regionCode argument

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60401158.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60402159.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60403160.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60404161.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-6060162.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60800163.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-6081164.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-61000165.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70000166.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70200167.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70201168.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70202169.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70203170.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70204171.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70400172.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70800174.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71000175.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71200176.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71400177.mdx
This PR adds new front matter to a portion of python agent release notes. 
cc: @clarkmcadoo @roadlittledawn
=> Add front matter to python agent release notes 6.4.1.158 to 7.14.0.177.

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5120140.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5121141.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5140142.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5141144.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5160145.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5161146.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5162147.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5180148.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-5200149.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60400157.mdx
* Adds metadata for python agent release versions v5.12.0.140 - v5.20.0.149, and v6.4.0.157.
* Requires review from docs engineering team.
=> Add Python Agent Metadata

src/components/DocTile.js, src/components/HomepageSlabs.js
adds a `variant` prop with `default`, `labs`, and `light` as the variants, and a `title` prop. removes the `forceLightMode` prop on DocTile in favor of the `variant` prop on DocTiles. i made sure that `numbered`, `title`, and `label` play nice together across all the `variant`s
=> feat: add `variant`s to DocTiles

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
A new version of Oracle r2dbc was released and is incompatible with the Java agent.
=> chore(Java): capping supported version of oracle r2dbc

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71600178.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80000179.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80100180.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80200181.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80201.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80300.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80400.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80500.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80600.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80700.mdx, src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80701.mdx
This PR backfills the final portion of Python agent release notes with front matter metadata.
=> Backfill Python agent release notes v7.16.0.178 to 8.7.0

src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure.mdx
- Add OpenShift v4.12 to the support compatibility matrix.
- Update the "Setup mTLS for ECTD with OpenShift" with working steps and improve the existing one with examples..
- Add additional service account setting for control plane.
=> Change docs to support OpenShift v4.12

src/content/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring.mdx
Per hero request:
> The code snippet for the “Wait for a page element” section shows the waitForAndFindElement method being used with $webDriver, which is deprecated on the new runtime
Updated snippet from @bpeckNR
=> feat(synthetics): updated script per hero request

src/content/docs/apm/agents/net-agent/net-agent-api/itransaction.mdx
Adds documentation for a new `SetUserId` method available in the .NET Agent API.
**Please do not merge until after 4pm Pacific time today (3/28)!**
=> docs: update .net agent api docs to include new SetUserId method

src/content/docs/data-apis/understand-data/metric-data/query-apm-metric-timeslice-data-nrql.mdx
Clarify metric units for timeslice metrics
Clarify metric unit for timeslice metrics
The units are taken from this query 
```
FROM Metric SELECT metricName, metricUnit WHERE appName = 'YOUR_APP_NAME' and metricName IN ('apm.service.cpu.usertime.utilization','apm.service.datastore.operation.duration','apm.service.error.count','apm.service.external.host.duration','apm.service.instance.count','apm.service.memory.physical','apm.service.transaction.apdex','apm.service.transaction.duration','apm.service …
```
=> docs: clarify metric units for timeslice metrics

src/content/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-8-0-323.mdx
Our previous release notes had the incorrect build number. This changes the number from 320 to 323
=> fix: set the 10.8 release build number to the correct number

src/content/docs/apm/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api.mdx, src/content/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api.mdx
New API methods support new Errors Inbox functionality: `setErrorGroupCallback` and `setUserId`.
=> Error fingerprinting/user tracking API methods for Node agent

src/content/docs/apm/agents/go-agent/get-started/go-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-21-0.mdx
Errors inbox release for GO agent -- > targeting EOD today.
=> feat(apm:go-agent): 3.21.0 release

src/content/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api.mdx, src/content/docs/apm/agents/go-agent/configuration/go-agent-configuration.mdx
Note from @zuluecho9: This should coincide with Go Agent release 3.21.0 release, estimated end of March some time. 
Document the user tracking and error group callback features added to errors inbox in the APM Go agent.
=> (end of March) Go agent - User Tracking and Error Groups

src/content/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips.mdx
The migration to the new IP space for legacy monitors has already been done. Removing outdated info from the synthetics ip informational page. 
=> Removing out of date Synthetics IP info.

src/content/docs/errors-inbox/error-users-impacted.mdx
Correct me if I am wrong @elucus but we only have four agents who have documented user tracking with errors inbox:
Go
Node
Python
Ruby
**Missing:**
.Net
Java (pending on 4.13)
PHP
This PR contains all the documented user tracking information and is ready for review.
=> fix(errors inbox): adding user tracking

src/content/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected.mdx, src/content/docs/apm/agents/ruby-agent/api-guides/sending-handled-errors-new-relic.mdx
Ready for review!
Correct me if I am wrong @elucus but we only have four agents who have documented error fingerprinting with errors inbox:
- Go
- Node
- Python
- Ruby
**Missing:**
- .Net
- Java (pending on 4.13)
- PHP
=> fix(errors inbox): fingerprinting changes

src/content/docs/apm/agents/php-agent/php-agent-api/newrelicgettracemetadata.mdx
This PR corrects the return value's keys listed in the documentation.  These keys actually have underscores - not periods - as seen in the example code immediately below.
=> fix: Correct return value keys

package.json, src/components/DocTile.js, yarn.lock
`children` was coming in as an object if there's only 1 node in the parent element instead of an array
=> fix: ensures children is an array for DocTiles

src/content/docs/apm/agents/nodejs-agent/hosting-services/nodejs-agent-heroku.mdx
Our docs site automatically adds a `$` when it's a `shell` or `bash` code block. Those aren't to be typed, they are an indicator of it being a command line:
=> fix: remove `$` from cmds

src/content/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview.mdx
I also wrapped the rest of the command lines in backticks and made the API key/Account ID stand-ins consistent (removed the `<>` from one code block)
I'm not positive if docs.newrelic recognizes `powershell` code blocks, but we can add it if it's not yet recognized.
=> chore: add language identifiers for syntax highlighting

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Windows event logs obtained with the winevtlog log source on Windows Server prior to 2019 will have empty/NULL values for the `message` attribute.
Inform users of incompatibility of winevtlog
=> Add warning about winevtlog log type compatibility

src/content/docs/new-relic-solutions/get-started/networks.mdx
Added AWS Static IP blocks for Outbound ALERT notifications Services.  Marked which are for the legacy Private Data Centers, and which are for the AWS data centers.
=> Added AWS Static IP blocks for Outbound ALERT notifications

package.json, yarn.lock
This version of `react-spring` was breaking our install pages and some release notes pages
=> fix: revert react-spring version

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
Neil tested out this line and found it was inaccurate:
> If the agent is disabled in the local or global newrelic.config, the NewRelic.AgentEnabled settings in these files will be ignored.
--
> The docs appear to be incorrect. After setting the global newrelic.config to `agentEnabled="false"` and adding `"NewRelic.AgentEnabled": "false"` settings to the appsettings.json I get this:
```log
2023-04-12 17:26:19,056 NewRelic  DEBUG: [pid: 2272, tid: 1] Reading value from appsettings.json and appsettings.*.json: 'NewRelic.AgentEnabled=false'
2023-04-12 17:26:19,252 NewRelic  ERROR: [pid: 2272, tid: 1] There was an error initializing the agent: System.Exception: The New Relic agent is disabled.  Update   to re-enable it.
at NewRelic.Agent.Core.AgentManager.AssertAgentEnabled(configuration …
```
=> fix: enabling in web/app config does work

src/content/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx
This is an edit for the Java Agent Kafka docs so it is more consistent with the new release notes for the 8.1 release of the Java Agent.
=> (4/13) Update Kafka doc for Java Agent 8.1 release notes consistency

package.json, yarn.lock
Tessen and the Browser agent seem to be working and on the desired versions.
=> fix: update theme to latest version for gatsby-plugin-newrelic updates

src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new.mdx
Clarify the Atlas users still need to use a hosted environment to run the agent_integration
=> Improve MongoDB Atlas requirements

src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/shut-down.mdx
The Shutdown file had a redirect that was identical to the current file location. This seemed to be preventing the left navigation from working correctly.
=> Remove unnecessary redirect.

src/pages/index.js
Reverting to the video homepage layout resulted in the search input on the default view accidentally getting removed. This brings it back.
=> fix: bring back tessen tracking on default homepage SearchInput

src/content/docs/logs/ui-data/parsing.mdx
It fixes a GROK pattern example that is wrapped in double quotes, if you copy/paste that without removing them, it won't work. So removing them.
N/A
N/A
=> docs(logging): Fix sample grok parsing rule

src/content/docs/style-guide/writing-docs/processes-procedures/create-edit-content.mdx
We had a help-documentation comment telling us that there were two failing links in the guide to creating new docs.
=> Remove obsolete links to clones and templates

src/content/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration.mdx, src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx
The Ruby agent is releasing version 9.2.0. The release notes are in a separate PR. This PR:
* Updates config options  
* Updates EOL policy page 
This is ready to merge/deploy.
=> chore(ruby agent): Update docs for 9.2.0 release

scripts/convertPNGs.mjs
also:
- adds some error handling
- only checks for MD/JS in `src/` (previously running this with the `--global` flag would go through node_modules 😩)
- fixes a bug with the markdown references not being updated when running with the `--global` flag
=> include jpgs in webp conversion script

src/components/TileSelect/TileOption.js
The css that was in there wasn't actually affecting anything. I moved it out of the nested img selector and adjusted it a bit. here's an example where i pulled in some random pngs for demo purposes:
=> fix: Adjust TileLogo css

src/content/docs/data-apis/understand-data/event-data/events-reported-mobile-monitoring.mdx
* What problems does this PR solve? - Update docs, we have moved mobilebreadcrumb from custom events to New Relic events.
=> MobileBreadcrumb is now a New Relic event

src/content/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs.mdx, src/content/docs/logs/log-api/introduction-log-api.mdx
It remove and environment variable from the docs that is not being used and is not required.
* Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.
The lambda code already provides a way of inferring the endpoint by the provided license key.
=> docs(logging): remove NR_LOGGING_ENDPOINT env

src/content/docs/change-tracking/change-tracking-view-analyze.mdx
This was a hold-over from the preview, so I am removing the word "preview."
=> Remove "preview" from left nav reference

src/content/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-cloud-services.mdx, src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx, src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx, src/content/docs/apm/agents/net-agent/other-installation/understanding-net-agent-environment-variables.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-core-agent-linux.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-windows.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/resolve-net-scom-conflicts.mdx, src/nav/apm.yml
This PR attempts to address some confusion about how the .NET agent uses required environment variables, and the correct values of those variables, reported by both our customers and our support team.  It has the following changes:
- Introduce a new document that gives an overview of how the required env vars are used by the agent, as well as correct values for common installation scenarios
- Link to this new document from multiple places around the rest of the .NET agent docs that reference required environment variables
- A few minor tweaks
I'm creating this PR in draft state initially to solicit feedback from the rest of the .NET agent team.  I would also appreciate any feedback from the docs team on the general formatting of the new document (I know it's pretty long and could probably …
=> feat: .NET Agent environment variables explainer doc

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx
It clarifies how to configure the integration in a cluster environment.
=> fix cluster documentation config for rabbitmq integration

src/content/docs/network-performance-monitoring/get-started/network-performance-monitoring-guide.mdx, src/nav/network-performance-monitoring.yml
This is a copy of the [Network Performance Monitoring Lab](https://developer.newrelic.com/collect-data/network-performance-monitoring) from the developer site, as part of the migration.
=> migrated NPM lab from developer site

src/content/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration.mdx, src/content/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements.mdx
The rabbitmq integration has a non documented limitation regarding the maximum amount of queues that can be collected. this PR documents that
=> rabbitmq queue size limitation (NR-107429)

src/nav/apm.yml
Removed the trailing slash on the nav path on the [Understanding required .NET agent environment variables](https://docs.newrelic.com/docs/apm/agents/net-agent/other-installation/understanding-net-agent-environment-variables/)
=> chore(Net agent): Removed the trailing slash on the nav path

src/content/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors.mdx
Description:
This pull request fixes a broken link in the add/edit monitor doc. The original link was pointing to a page that no longer exists, so I updated it to the new URL. The new link directs users to the correct page with the relevant information. The broken link is also referenced in the attribute dictionary under syntheticsType, with hyperlink Types of synthetic monitors
Changes Made:
Updated the broken link to the new URL
Tested the link to ensure it is working as expected
Testing:
Clicked on the updated link to verify it directs to the correct page.
=> Updated broken link

src/content/docs/apm/agents/python-agent/back-end-services/python-agent-celery.mdx, src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx, src/content/docs/apm/agents/python-agent/python-agent-api/registerapplication-python-agent-api.mdx, src/content/docs/apm/agents/python-agent/troubleshooting/activate-application-warning-python.mdx, src/install/python/python-agent-non-web-apps.mdx
* Add additional info and clarify causes of active application warning.
* Add in note about not being able to monitor the main process of celery.
* Clarify under what circumstance startup_timeout should be used.
=> Fixup docs

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
This PR edits a bullet point that caused some confusion around whether editing retention can be done per-namespace: yes, it can be edited per-namespace as long as you're editing within your contractual limits, but no it cannot when you're adding additional data retention beyond your existing contract ("increasing retention" was found to be a bit vague).
=> [NR-82890] Namespace retention contradiction

src/data-dictionary/events/ProcessSample/netIoTotalReceivedPackets.md, src/data-dictionary/events/ProcessSample/netIoTotalSentPackets.md
Two attributes show in the processSample dictionary, but they do not show up in product at all and per dev conversation they should have been deleted long ago.
Internal Slack reference https://newrelic.slack.com/archives/CK58517B6/p1588722673340200
=> chore: Remove Process sample netio metrics

src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-metrics.mdx
links with this format lose the in-page link when you open them in a new tab:
```
docs/agents/nodejs-agent/supported-features/nodejs-agent-api/#record_metric
```
That results in the `#record_metric` being lost when it redirects to our newer URL patterns (only when opened in new tabs). This link does not do that
```
/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/#record_metric
```
=> chore: update API links

src/content/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-810.mdx
The Kafka Streams config example in Java agent's 8.1.0 release notes had an error in it.
=> chore(Java): Fix Kafka Streams config example

src/content/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql.mdx
Infra Shimming has a limitation when the customers try to use LIKE to filter infra metric names.
Ticket: https://issues.newrelic.com/browse/NEWRELIC-6218
=> infrastructure dimensional metrics: metric name limitation

src/content/docs/apm/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs.mdx
`tls.SLAB_BUFFER_SIZE` was removed from node over 5 years ago and this is no longer relevant to the agent according to the node engineering team
=> fix: remove section for tls buffer

src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx, src/content/docs/synthetics/synthetic-monitoring/private-locations/install-job-manager.mdx, src/data-dictionary/events/SyntheticCheck/timestamp.md, src/data-dictionary/events/SyntheticRequest/sslCertificateExpirationDaysRemaining.md, src/data-dictionary/events/SyntheticRequest/sslCertificateExpirationMs.md, src/data-dictionary/events/SyntheticRequest/sslCertificationExpirationDaysRemaining.md, src/data-dictionary/events/SyntheticRequest/timeStamp.md
- Added clarifications that AMD64 / x86_64 processors are required for CPM and Job Manager installs
- Removed a duplicate and incorrectly named timestamp attribute from SyntheticRequest, adding SyntheticRequest to the event types of the timestamp attribute used for SyntheticCheck
- Clarified when sslCertificateExpiration attributes are created
- Fixed typos in the name of sslCertificateExpirationDaysRemaining
- Clarified the description of sslCertficiateExpiration related attributes
=> fix(synthetics): add multiple clarifications

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-events-integration.mdx
Fixed typo 'mentrics' - should be 'metrics'.
Typo in anchor link
Old link: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-events-integration/#events-mentrics
=> [Chore] Fix typo in anchor link

src/components/ErrorBoundary.js, src/components/ErrorBoundaryCC.js, src/components/ErrorMessage.js, src/pages/attribute-dictionary.js, src/pages/index.js, src/pages/install/{installConfig.agentName}.js, src/pages/introduction-apm.js, src/pages/whats-new.js, src/templates/docPage.js, src/templates/embedPage.js, src/templates/releaseNote.js, src/templates/whatsNew.js
This adds an error boundary component that can wrap our templates and js pages should there be a js error. it'll render a message in the UI and sent a browser event that we can use for alerts.
from [react's docs](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) "There is currently no way to write an error boundary as a function component". it's a little inconvenient, but since you can't use hooks in class components i'm passing the tessen call through
example event:
UI:
=> Add error boundary

src/nav/serverless-function-monitoring.yml
The Dot-Net and Java tutorials have been in the UI section for a while, but they really should have been listed under the "Enable" section.
There was no need to update any redirects because I didn't move the actual files. Instead, I just moved the entries in the nav file.
=> Move Dot-Net and Java tutorials into Enable section

src/content/docs/apm/agents/net-agent/azure-installation/azure-pipelines-wipes-out-newrelicazurewebsitesextension-directories.mdx, src/content/docs/apm/agents/net-agent/azure-installation/azure-web-apps-using-always-no-data-appears.mdx, src/content/docs/apm/agents/net-agent/azure-installation/no-data-reporting-microsoft-application-insights.mdx, src/nav/apm.yml
We had a request in help-documentation to move this troubleshooting doc out of the main troubleshooting section and into the Azure installation section.
=> Move Azure troubleshooting doc to installation

src/content/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api.mdx
Based on SME feedback in hero channel, we need to change the single quotation marks in the curl headers to double quotation marks to enable variable expansion. This doesn't follow the pattern in our other examples where we don't assume variable expansion and just ask users to insert literal values in the script. Alas, we are leaving this pattern here and just substituting the quotation marks.
Since the URLs embedded in the code snippet use double quotation marks, I just switched the `<a href` to use single quotation marks. This allow us to avoid having nested double quotation marks.
=> Correct variable expansion for Api-Key

src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data.mdx
We recently added `K8sCronJobSample` and `K8sJobSample`. This PR adds them to a docs page for discoverability.
=> fix: Add K8sCronjobSample, K8sJobSample to Find and Use your K8s data page

src/content/docs/apm/agents/ruby-agent/getting-started/ruby-agent-eol-policy.mdx
The Ruby agent needed to quickly follow the release of 9.2.1 with another bugfix, for version 9.2.2
This PR adds the new version to the EOL policy. A separate PR will be made for the release notes.
=> chore(ruby): Add row for version 9.2.2

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Nest.js is actually already mostly supported, we just never really tried to see if it works or not.
=> fix (node agent): mention Nest.js as another supported framework

src/content/docs/kubernetes-pixie/auto-telemetry-pixie/troubleshooting/get-pixie-logs.mdx
Updated the permalink from: https://github.com/wreckedred/pixie-diag
To:
https://github.com/newrelic-experimental/k8s-diag-utilities/tree/main/pixie-diag
=> [chore]  - Update get-pixie-logs to updated pixie diag repo

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Update to list Java 20 support for Agent v8.2.0 which will be release Wed May 3, 2023
=> May 3 - Update compatibility-requirements-java-agent.mdx to list Java 20 support

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx, src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-811.mdx
from @zuluecho9 May 3: still draft, they'll let us know when ready.
These are updated docs for the Java Agent 8.2.0 release
=> Java agent 8.2.0 release (Aiming for May 3, 2024)

src/content/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy.mdx
There are earlier Java Agent versions that are still supported that are not listed. This PR will re-list them.
=> Java agent eol old versions

src/content/docs/style-guide/writing-docs/article-templates/whats-new-template.mdx
For our large code snippet, we need an additional line return to enable the back tick formatting. We have added this line return. Without this extra line return, the code snippet was being rendered as regular text (with headings). So, step #2 should have a large code snippet showing a markdown file--not rendered markdown.
=> Fix large code snippet in "What's new" instructions

src/content/docs/data-apis/ingest-apis/event-api/introduction-event-api.mdx
The limit is strictly on bytes now; there's no longer a limit on the number of events in a request.
=> Remove 2k limit

src/content/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph.mdx, src/content/docs/apis/nerdgraph/examples/mobile-monitoring-config-nerdgraph.mdx, src/nav/telemetry-data-platform.yml
Moved some docs into a new subcategory of 'Agent config' in NerdGraph for easier findability.
=> fix(nerdgraph): add 'agent config' cat

src/content/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api.mdx
Removed an outdated video from this page: [NerdGraph tutorial: Export dashboards as files](https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/)
=> fix(NerdGraph): Removed an outdated video

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
`attribute` is confusing here when it really should be `metric_name`.  Also including all args in the top level example like the other functions in this list instead of a separate nested example.
=> fix: Make cardinality() doc more clear and consistent

src/content/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues.mdx
The example on how to enable kafka-streams-spans is confusing so I decided to simplify it for customers.
=> Simplify example on how to enable kafka-streams spans

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
The .NET agent is releasing instrumentation for Elasticsearch clients in agent version 10.10.0.  This PR updates the agent's compatibility and support documentation with information on the versions supported and tested.
=> Add supported datastore client versions for Elasticsearch

src/content/docs/browser/new-relic-browser/browser-apis/seterrorhandler.mdx
Update browser setErrorHandler api page to account for new functionality post v1.230.0 rollout.
=> docs: Update setErrorHandler api for EI fingerprinting

src/layouts/MainLayout.js
The nav icon click tracking was added while we were using the personal homepage layout and so this got lost when we switched back to the video layout.
=> fix: add back tessen tracking to nav open/close clicks

src/data-dictionary/events/ContainerSample/StorageDataAvailableBytes.md, src/data-dictionary/events/ContainerSample/StorageDataTotalBytes.md, src/data-dictionary/events/ContainerSample/StorageDataUsagePercent.md, src/data-dictionary/events/ContainerSample/StorageDataUsedBytes.md, src/data-dictionary/events/ContainerSample/StorageMetadataAvailableBytes.md, src/data-dictionary/events/ContainerSample/StorageMetadataTotalBytes.md, src/data-dictionary/events/ContainerSample/StorageMetadataUsagePercent.md, src/data-dictionary/events/ContainerSample/StorageMetadataUsedBytes.md
A few metrics from `ContainerSample` data dictionary are based on a Docker storage backend that is deprecated.
=> Deprecate docker storage metrics (NR-108207)

src/content/docs/logs/troubleshooting/log-message-truncated.mdx
Add query to show how to find those logs that might have a truncated message field.
Responsive to a customer feedback request.
=> Fix missing quote and add a helpful query

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx, src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx
these redirects cause a `too much recursion` error because they redirect to the same path as the file
=> remove redirects to same page URL

src/content/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration.mdx
- Mention up front that logs can be collected
- In "Compatibility and requirements"
- Fix a bad link to the wrong section
- Add a missing mention of Windows as a host OS
- Fix using an inconsistent verb tense ("Enable" rather than "Enabling")
- Line up the Linux log configuration command with the description of the step, rather than calling it out as an "Example", to be consistent with the other steps
- Added logs installation instructions to the Windows drop-down section
- Link to Logs UI in "Find and use data"
FYI @marcelschlapfer @lchapman4 @mculmone
=> Improve nginx docs for logs use case

src/content/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk.mdx
* Updating based on customer feedback, Amazon Linux 1 is EOL, Amazon Linux 2023 is now GA.
=> Updating supported Amazon Linux versions

src/content/docs/apis/nerdgraph/examples/nerdgraph-synthetics-tutorial.mdx, src/content/docs/synthetics/synthetic-monitoring/scripting-monitors/import-nodejs-modules.mdx, src/content/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes.mdx, src/data-dictionary/events/SyntheticCheck/browserVersion.md
- Changed all references for Chrome 100 in Synthetics to Chrome 100+
- Added Chrome 112 to the runtime documentation
- Added the new browserVersion attribute.
=> feat(ChromeUpgrade): Upgrade Chrome version used in Synthetics

src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx
* There's a sign-up note that seems to be out of context in the Infra Agent upgrade documentation. Removed.
=> fix: remove out of context sign-up note

src/content/docs/apm/agents/nodejs-agent/getting-started/nodejs-agent-eol-policy.mdx
Adds our two newest Node.js agent versions and removes versions that have fallen into EOL
=> chore: update Node.js APM EOL page

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
Added a new configuration parameter `use-ansi` for infrastructure agent and Fluent Bit integration.
The new parameter is related to this [pull-request](https://github.com/newrelic/infrastructure-agent/pull/1661) pending on reviewing and merging by CAOS team.
=> New use-ansi config parameter for infra-agent and Fluent Bit

.github/workflows/agent-release-notes.yml
also updated the names of the secrets, since we were already using the old names for different access keys
=> add `--upload` flag to releaseNotes script

src/templates/releaseNote.js, src/templates/releaseNoteLandingPage.js
`excerpt` was only 140 characters.
some release notes on the summary page are v similar at the beginning, this should help to differentiate them
=> `excerpt` -> `body` on releaseNoteLandingPage

.husky/pre-commit
Temporarily disabling husky as its throwing errors for some of the writers using Github Desktop
=> fix: Turn off husky.

src/content/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/kubernetes-integration-3-12-0.mdx
This PR updates the release notes for the Kubernetes integration docs.
=> Add release notes for Kubernetes integration v.3.12.0

src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx
I had pushed up a fix earlier to left-justify two sentences, but alas, the fix didn't work. This should fix them.
=> Logs: Left-justify two sentences by removing spaces

src/content/docs/apm/agents/net-agent/other-features/net-performance-metrics.mdx
We finally have a real APM UI page for .NET CLR (VM) performance metrics.  This PR updates the documentation about these metrics to point users to the new UI.
=> Update .NET Performance Metrics documentation to point to new UI page

src/content/docs/new-relic-solutions/get-started/networks.mdx
IP range limitations does not apply for Azure Monitor integration. Azure Monitor GA is going live on May 23rd. Please approve this change on the GA date.
=> May 23 - Update networks doc for the Azure Monitor release

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx
* Relationships among entities have a ttl that is used to remove/expire relationships for entities that no longer exist or just relationships that are not valid anymore. This PR adds a small comment to provide this information.
=> NR-85304 Document relationships ttl

src/components/SEO.js
adds extra urls for pages that will have VWO script:
- /docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing
- /docs/licenses/license-information/usage-plans/new-relic-usage-plan
- /docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing
- /docs/accounts/accounts-billing/new-relic-one-user-management/user-type
In the build preview, you can see this script on these pages but not others. 👍
=> chore: add additional pages to VWO script

src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-chatbot-monitor-integration.mdx, src/nav/infrastructure.yml
Asana Task - https://app.asana.com/0/1202974982230192/1202975068291765
Partnership Engineering Team - 
- Added AWS-chatbot Entity
- AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud.
- Entity PR Which is raised & Merged -
- https://github.com/newrelic/entity-definitions/pull/1083
- https://source.datanerd.us/entity-platform/entity-type-ui-definitions-service/pull/370
=> Aws chatbot

src/content/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring.mdx, src/content/docs/browser/new-relic-browser/troubleshooting/mootools-related-errors.mdx, src/nav/browser.yml
This PR adds info about browser agent compatibility with the MooTools library, and about troubleshooting errors encountered when using the MooTools library in combination with the browser agent. Compatibility language is updated to address both frameworks and libraries, and to address general conflicts with libraries that modify native JavaScript mechanics.
See [NEWRELIC-8754](https://issues.newrelic.com/browse/NEWRELIC-8754).
=> chore: Add MooTools compatibility info

src/content/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1.232.1.mdx
The un-deploy note is no longer needed with the release of 1.233.0.
=> chore: Update browser-agent-v1.232.1.mdx

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts.mdx
Fixed a broken link on the [Understand the state of your system with the health (alert) status](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts/#alert-status) section.
=> fix(NR One): Fixed a broken link

scripts/verify_mdx.js, src/components/DocTile.js, src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx, src/content/docs/apm/agents/python-agent/python-agent-api/noticeerror-python-agent-api.mdx
This reverts the light/dark mode colors for the default DocTile to be like they were before we added variants during VSU work. Like [here](https://docswebsite-dailyreleasedec192022216.gatsbyjs.io/). We needed to be a little extra explicit in our background definitions so the tile wasn't falling back to the Surface component styling in some cases.
=> chore: Doctile uses correct background colors

src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx, src/content/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-745.mdx
I added the iOS agent 7.4.5 release notes and some information about new feature flags in the release.
Release to go out on May 31 2023
=> Publish 5/31: Added feature flags and release notes for Mobile 7.4.5 release May 31 2023

src/components/SEO.js
Applies same changes as this [PR](https://github.com/newrelic/docs-website/pull/13182/files) that adds VWO script on four signups pages. 
We will also need to either remove gatsby cloud auth on docs-dev temporarily OR give VWO engineers the auth key to access that site.
- https://github.com/newrelic/docs-website/pull/13217
- https://github.com/newrelic/docs-website/pull/13182/files
=> content: re-add vwo on signup pages to repro issue

src/content/docs/security/security-privacy/compliance/fedramp-compliant-endpoints.mdx
The AWS Metric Streams is not listed on the Services Not In Scope on this page (https://docs.newrelic.com/docs/security/security-privacy/compliance/certificates-standards-regulations/fedramp-moderate/#not-scope) anymore, so I think we should remove it on the FEDRAMP Compliant Endpoint page too.  This PR removes that "EXCEPTION" verbiage to be consistent across the documentation.
=> Remove Exception on AWS Metric Streams

gatsby-config.js
We no longer want to generate json during the gatsby build
=> feat: remove release-notes json generation from build

package.json, scripts/transformDataDictionary.mjs, yarn.lock
this script transforms the data for events and attributes so that events list attributes they have, rather than individual attributes listing different events they belong to
it also assumes that attributes inside a folder automatically belong to their parent event, so the event definition doesn't need to specify attributes within its own folder
- from the root project dir, run `scripts/transformDataDictionary.mjs`
- `src/data-dictionary/events/` should be updated with the new format
=> add tranform for data-dictionary events

src/install/python/python-agent-uvicorn-docker.mdx
=> docs(python): fix typo in agent installation instructions

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-10-2-0.mdx
Supersedes #13376, this has the corrected frontmatter for 10.2.0 release notes
=> chore: add Node.js Agent v10.2.0 Release Notes

src/content/docs/alerts-applied-intelligence/notifications/message-templates.mdx
[Jira ticket](https://issues.newrelic.com/browse/NR-88982) - NR-88982.
Adding information about the timezone helper for handlebars used in notifications channels payload.
=> feat(message-templates): Add details about the timezone handlebars helper

src/content/docs/new-relic-solutions/get-started/networks.mdx
This removes the "Private Data Center" vs "AWS" labels from the "Alerts webhooks, api.newrelic.com, cloud integrations, and ticketing integrations" section. The origin of outbound hooks is not directly controlled by the customer, so the labels are unnecessary and can be a source of confusion.
=> Remove IP range specific labels from Network Traffic doc

src/content/docs/kubernetes-pixie/kubernetes-integration/installation/upgrading-kubernetes.mdx
Standardize release name to match guided install, as `newrelic-bundle`
The release name must be used when referring to a Helm chart in the CLI. If the release name doesn't match the initial installation, it could cause confusion.
Other docs seem to also use `newrelic-bundle`, agreeing with the guided install.
=> [chore] Update upgrading-kubernetes.mdx

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx
Fixing the `NEW_RELIC_TRUSTED_ACCOUNT_KEY` so it doesn't include a period at the end.
=> docs: fix NEW_RELIC_TRUSTED_ACCOUNT_KEY variable name

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Updated the `facet...order by` clause to specify the `ASC` and `DESC` modifiers can't be used.
Request added in the help-documentation channel.
=> feat(NRQL): Updated the facet order by clause

src/content/docs/style-guide/structure/tabs.mdx
Noticed with @ally-sassman that we didn't have practical examples of tabs
Preview link: https://docswebsitedevelop-austinschaeferpatch9.gatsbyjs.io/docs/style-guide/structure/tabs/
=> chore(style guide): Add/improve tabs example syntax

src/content/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic.mdx
The ability to configure TTL is only for New Relic internal teams that are publishing relationships. For customers it would be more accurate rephrasing this as "The TTL can vary from 10 minutes up to 3 days depending on the relationship type."
https://newrelic.slack.com/archives/CH5MLECNN/p1686557214192059?thread_ts=1686080986.483239&cid=CH5MLECNN
=> More accurately reflect entity TTL for customers

src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring.mdx
Per a Github issue + jira ticket that the docs team received, added some context to manual set up.
=> feat(NPM): clarify where to put license key and account ID

src/content/docs/apm/agents/net-agent/troubleshooting/Minimal APIs endpoints appear as one transaction (.NET).mdx, src/nav/apm.yml
The original PR was giving Gatsby some build issues, maybe due to an out of date fork. Went ahead and added that content to a new branch to sidestep eng troubleshooting.
Existing PR:
https://github.com/newrelic/docs-website/pull/13492
I've already gotten SME approval on this content.
NOTE TO SELF FOR 6/14:
Need to change name of .mdx file in vs code so it aligns with the pathing in the yml file
=> feat(dotnet): added troubleshooting doc and updated yml per PR13492

src/content/docs/infrastructure/host-integrations/host-integrations-list/active-directory-integration.mdx, src/content/docs/infrastructure/host-integrations/host-integrations-list/snowflake-integration.mdx
adding callouts to infrastructure integrations that have open source categorization
=> chore: add oss tips to integrations

src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags.mdx
This PR addresses [this](https://issues.newrelic.com/browse/NR-96383) ticket for removing an experimental networking feature flag from the documentation.
=> Removed deprecated experimental networking flag

src/content/docs/mobile-monitoring/new-relic-mobile-cordova-phonegap/get-started-with-cordova-monitoring.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx, src/content/docs/release-notes/index.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-100.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-110.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-111.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-120.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/capacitor-agent-121.mdx, src/content/docs/release-notes/mobile-release-notes/capacitor-release-notes/index.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-600.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-601.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-602.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-610.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-620.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/cordova-agent-621.mdx, src/content/docs/release-notes/mobile-release-notes/cordova-release-notes/index.mdx, src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx, src/i18n/content/kr/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor.mdx, src/i18n/nav/jp.json, src/i18n/nav/kr.json, src/nav/mobile-monitoring.yml
Replaces all references from Cordova plugin/Capacitor plugin to be Cordova agent/Capacitor agent.
=> update hybrid plugins to be called agents

src/content/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-media-services-monitoring-integration.mdx
Cleaning up the metrics table
* What problems does this PR solve? - just cleaning up an html table list of metrics that had an erroneous malformed row.
=> fix: clean up metrics table contents and mis-matched row

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx, src/content/docs/network-performance-monitoring/troubleshooting/snmp-discovery-no-devices.mdx
adding some notes to better explain issues with discovery job timeouts using the network monitoring agent.
=> chore: adding notes on CIDR sizing recommendations

src/content/docs/data-apis/manage-data/manage-data-retention.mdx
Remove enforcing of retention limits on March 31st section since most accounts are already in compliance.
In this PR, the section about capping retention at the contracted max by March 31st is removed since most accounts have already been capped and are in compliance.
=> fix: update manage-data-retention.mdx

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-attributes.mdx
This behavior is currently undocumented and has come up in support cases. Documenting it to help users self discover the limit.
cc @alanwest
=> Update opentelemetry-best-practices-attributes.mdx with attribute array limits

scripts/transformDataDictionary.mjs
several attributes have the same name across different events, so there were collisions here that meant some events had missing attributes and some events had extra attributes
=> use qualified names in attribute map

.github/workflows/validate-pr.yml
currently, pr validation checks will not run on feature branches until they are merged into develop. This adds a branch name pattern to allow them to run
=> update workflow permissions for feat branches

src/content/docs/accounts/install-new-relic/partner-based-installation/heroku-install-new-relic-add.mdx, src/content/docs/apm/agents/java-agent/heroku/java-agent-heroku.mdx, src/content/docs/apm/agents/php-agent/advanced-installation/php-agent-heroku.mdx, src/content/docs/apm/agents/python-agent/hosting-services/python-agent-heroku.mdx
I also fixed some formatting and put code/filenames in backticks instead of BOLD, which is more consistent with the rest of our docs
=> chore: add language identifiers to heroku docs

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Fixes a typo in the if() statement nrql example: [Use with AND and OR](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-if).
Replace non-standard apostrophes: ’ with '.  This allows the query to run without error.
=> Correct typo in if() function example

src/content/docs/new-relic-solutions/get-started/glossary.mdx, src/content/docs/new-relic-solutions/new-relic-one/workloads/create-workloads.mdx, src/content/docs/new-relic-solutions/new-relic-one/workloads/use-workloads.mdx, src/content/docs/new-relic-solutions/new-relic-one/workloads/workload-status-views-notifications.mdx, src/content/docs/new-relic-solutions/new-relic-one/workloads/workloads-isolate-resolve-incidents-faster.mdx, src/content/docs/service-level-management/alerts-slm.mdx, src/nav/new-relic-solutions.yml
Work done: 
Related to NR-126848, which was about adding mention of errors inbox aspect of workloads, but also while I was in there, decided to: 
* Improve some confusing wordings about workloads and simplify it
* Move 'create workloads' content into its own doc, and separate it from 'workloads UI'
Also will be creating jira because I noticed the docs are quite out of date with new workloads UI
=> fix(workloads): some improvements

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
This PR contains several updates to verified compatible versions of .NET libraries instrumented by the .NET agent.  One of the updates is specific to agent version 10.12.0, which is being released today (Monday, 6/26/23).
=> .NET Agent documentation updates for release version 10.12.0

src/content/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/migration-to-workflows.mdx
The incident_id is now being generated differently, to ensure it's on all notifications.
=> Updating incident_id expectations

.github/workflows/agent-release-notes.yml
the release notes workflow runs on merge to main which results in the json being immediately updated and builds taking up to 40min. this means in the product a release note can show up with a link to a docs page that hasn't gone live yet. this makes the workflow run around 7pm pdt which should be well after the last release of the day and hopefully avoid any more temporary 404s
=> Make workflow run on a cron

src/content/docs/apm/apm-ui-pages/events/thread-profiler-tool.mdx
In Tree settings, show: Web Request and Background options have been deprecated for a long time: see Slack thread in NR-115632 called "Reference to how bucketing hasn't worked since Java agent 3.21". There is a fix in the backlog to remove these options: NR-115632. Will need to remove this note about Other when fix is deployed. But in the meantime we should mention that these two options don't work for Java.
=> Update thread-profiler-tool.mdx to show Java-specific notes

src/content/docs/tutorial-peak-demand/autoscale-your-infra.mdx, src/content/docs/tutorial-peak-demand/create-quality-alerts.mdx, src/content/docs/tutorial-peak-demand/find-your-baseline.mdx, src/content/docs/tutorial-peak-demand/get-started.mdx, src/content/docs/tutorial-peak-demand/organize-data-workloads.mdx
Fixes some broken redirects by removing an extra `/` at the beginning of the redirect frontmatter.
=> fix(tutorial): fix redirects

src/content/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-install.mdx
Currently, the link is going to [this k8s documentation](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements/), but it should go to the corresponding [monitoring services section](/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes), where JMX is listed as one of the compatible services.
=> fix: link to monitor services in k8s

src/pages/attribute-dictionary.js, src/pages/install/{installConfig.agentName}.js, src/templates/docPage.js
this improves readability when a user has a larger font size selected
my default font size is 20px so these have always been kinda squooshed
=> use `rem`s for right column width

src/content/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/create-edit-or-find-alert-policy.mdx, src/content/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts.mdx, src/content/docs/data-apis/manage-data/view-system-limits.mdx, src/content/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide.mdx, src/nav/alerts-applied-intelligence.yml
NR-129249
Preview builds for relevant pages:
Alert limit doc: https://docswebsitedevelop-newalertlimit.gatsbyjs.io/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/rules-limits-alerts/
Main system limit doc (at bottom of table): https://docswebsitedevelop-newalertlimit.gatsbyjs.io/docs/data-apis/manage-data/view-system-limits/#all_products
Work done: 
Add alerting limit to the 'alert limits/rules' doc. Added it to table, and then added more info in a new section at bottom of page. 
Add ref to that from the general 'system limits' doc. 
Restructured the org of alert nav a bit, because: a) the rules/limits doc was under the 'classic' category and that seemed a mistake. Moved that into a section with the 'General settings UI' and named that section 'Administration and limits' …
=> fix(alerting): new limit, structure

scripts/actions/__tests__/__snapshots__/serialize-mdx.test.js.snap, scripts/actions/__tests__/serialize-mdx.test.js, scripts/actions/utils/serialization-helpers.js
This serializer was breaking because an apostrophe was getting changed into a double quote. this updates the regex to only change the outer most quotes of the prop values into double quotes
You can test this by serializing and deserializing this component (previously broken)
```
<UserJourneyControls
nextStep={{path: "/docs/tutorial-dd-migration/making-the-switch/", title: "Next step", body: "Learn more about New Relic's other features and what you need to make the switch from Datadog"}}
previousStep={{path: "/docs/tutorial-dd-migration/installing-monitor/", title: "Previous step", body: "Learn more about ingesting data to monitor"}}
/>
```
=> fix: Update regex in serializer to only convert outer quotes

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx, src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/troubleshooting/troubleshoot-enabling-serverless-monitoring-aws-lambda.mdx
DO NOT MERGE without coordinating with @jmartin4563, dependent on release of https://github.com/newrelic/newrelic-lambda-layers/pull/156
Documents the newly added NEW_RELIC_USE_ESM environment variable. This variable is used by the Node.js Lambda Layer to determine whether or not to use `require` vs `import` when wrapping a customer's function to capture instrumentation. When set to `true`, the wrapper will use `import` and will be asynchronous, and when absent or `false`, will use `require` and by synchronous.
* https://github.com/newrelic/newrelic-lambda-layers/pull/156
=> Publish 06/29: feat: update nodejs lambda docs to include NEW_RELIC_USE_ESM

src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-new-relic-gradle-plugin.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-proguard-or-dexguard-android-apps.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/get-started/mobile-agents-eol-policy.mdx, src/content/docs/release-notes/mobile-release-notes/android-release-notes/android-700.mdx
* What problems does this PR solve? - Android agent v7.0.0 release notes & doc updates
1. AGP 8 support
2. Config cache support
3. Compatibility doc update
4. Release note callout to indicate minimum Gradle and AGP version upgrades
=> Android agent v7.0.0 release notes & doc updates

src/install/npm/network-flow/linux-eu.mdx, src/install/npm/network-flow/linux-us.mdx, src/install/npm/snmp/linux-eu.mdx, src/install/npm/snmp/linux-us.mdx, src/install/npm/snmp/linux-usfedramp.mdx, src/install/npm/syslog/linux-eu.mdx, src/install/npm/syslog/linux-us-fedramp.mdx, src/install/npm/syslog/linux-us.mdx
The package manager installation for KTranslate uses packagecloud.io for hosting deb and RPM packages but packagecloud.io will sometimes returns redirects to a specific CloudFront distribution (should remain consistent per [their docs](https://packagecloud.io/docs/security#:~:text=d28dx6y1hfq314.cloudfront.net)).
Customers who want to use the package manager installation method with minimum network permissions will also need to add that CloudFront distribution
=> Document additional CDN in network prereqs

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload.mdx
Fixing code inside the [Webhook format example](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/#MS-Teams-example) section.
Replaced this:
`"text": "<img src="{{ violationChartUrl }}" alt="Incident Chart">"`
with this:
`"text": "{{#if violationChartUrl}} <img src=\"{{ violationChartUrl }}\" alt=\"Incident Chart\"> {{else}} N/A {{/if}}"`
=> fix(Alerts): Fixed code inside the Microsoft Teams example

src/content/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration.mdx
Add new metrics to the nri-postgresql integration. 
The new version has been released so the PR is ready to merge after review/approval.
=> Add new metrics to nri-postgresql

src/content/whats-new/2023/06/whats-new-06-13-wpm.md
Fixing a what's new link that had double `https://` in the get started frontmatter
=> fixing url

src/content/docs/accounts/accounts-billing/account-setup/login-options.mdx, src/content/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems.mdx, src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks.mdx
New option for creating NR org or logging in via GitHub, alongside Google options. Along with this, we wanted to document some caveats for social login, which we added to the login troubleshooting doc.
=> fix(login): new Github social login

src/content/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration.mdx
1.14.0 was released in Dec 2020
=> chore(kafka): Remove old version requirement

src/pages/attribute-dictionary.js
Sort each event's table by attribute name in alph order.
**Before**
**After**
=> fix(attribute-dictionary): apply alpha sort to attribute tables

src/content/docs/apm/agents/net-agent/azure-installation/debugging-agent-azure.mdx, src/content/docs/apm/agents/net-agent/other-installation/understanding-net-agent-environment-variables.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/cocreateinstance-errors-no-profiler-log.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-core-agent-linux.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/debugging-net-windows.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/lock-contention-appdomain-getdata.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx
I added some syntax highlighting to other docs while I was at it
=> fix: CORECLR_ENABLE_PROFILING env var for Core apps

src/layouts/MainLayout.js
on mobile, the div was covering the entire screen,
making the site unusable.
on desktop, the div had a fairly wide width that was preventing
clicks on anything under it, either in the nav or on the page
this fix hides it completely on mobile and makes the width 0px
on desktop, which doesn't cover anything underneath
=> fix nav collapser div covering content

src/content/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/AWS-polling-to-AWS-CW-MetricStreams-Migration
This is the new feature for migrating AWS Polling integrations to AWS Cloudwatch Metric Streams through a migrate button which replicates AWS Polling namespaces for Cloudwatch Metric Streams through a customised CloudFormation Template
=> PUBLISH: 7/18; Release notes: Create AWS-polling-to-AWS-CW-MetricStreams-Migration

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx
We've discovered the the ARM64 version of our .NET agent does not work on Alpine Linux.  This PR updates our documentation with that information.
=> .NET Agent: add exception for Alpine Linux under ARM64 support statement

src/content/docs/style-guide/writing-docs/processes-procedures/create-edit-content.mdx, src/content/docs/style-guide/writing-docs/processes-procedures/understand-edit-docs-site-structure.mdx, src/nav/style-guide.yml
Adds the syntax for left nav labels and rearranges some of the style guide nav. The style guide needs larger edits, but I think the nav edits make it a bit easier to find content and improve the titles by making them closer to the actual content of the doc.
=> feat(style): add label syntax + style guide structure edits

src/content/docs/change-tracking/change-tracking-view-analyze.mdx
Removes the event query param that was sending users to a blank attribute dictionary
=> fix: Remove event query param for attribute dictionary link

src/content/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview.mdx
Adds a couple of recipes and updates the text to match the new recipes. It used to be only on host integrations but now also contains some agents (infra, APM)
=> Added missing recipes on guided install page

src/components/MDXContainer.js
- small refactor on img props, including styling, in MDX Container
features added via theme update*:
- Add max height for MDX images at 550px
- Provides 'unbound' class  for `<img>` to unset this style
*Docs will be updated with these theme changes along with the upcoming upgrade to Gatsby v5
=> Add max height on MDX images

src/content/docs/style-guide/word-choice/usage-dictionary.mdx
A clarification in style guide about how we treat AWS product names that can also be used more informally.
=> fix(usage dict): AWS guidance addition

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Extra arguments on the sum() function will cause the query to fail. Removing the incorrect "Arguments after the first will be ignored." stement.
=> Remove sum's incorrect "ignored" argument reference

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core.mdx, src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
We've (.NET agent team) made some updates to our integration tests for Elasticsearch client instrumentation and want to update our documentation around supported and verified compatible versions of these libraries.
=> .NET Agent: Update verified compatible versions of Elastic clients

src/content/docs/apm/agents/net-agent/troubleshooting/profiler-conflicts.mdx, src/content/docs/apm/agents/net-agent/troubleshooting/resolve-net-scom-conflicts.mdx
powershell and shell have slightly different syntax rules, and this codeblock was displaying the strings as broken, because of missing escape chars `\` before the `"`. I tested this command in powershell and it's valid though without the escape. So to correct the highlighting I changed it to a powershell cmd. 
Examples:
Shelll:
```shell
$value = "COR_ENABLE_PROFILING=1","COR_PROFILER={71DA0A04-7777-4EC6-9643-7D28B46A8A41}","NEWRELIC_INSTALL_PATH=C:\Program Files\New Relic\.NET Agent\","CORECLR_ENABLE_PROFILING=1","CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}","CORECLR_NEWRELIC_HOME=C:\ProgramData\New Relic\.NET Agent\"
```
Powershell:
```powershell
$value = "COR_ENABLE_PROFILING=1","COR_PROFILER={71DA0A04-7777-4EC6-9643-7D28B46A8A41}","NEWRELIC_INSTALL_PATH=C:\Program Files\New …
```
=> fix: powershell, not shell

src/content/docs/new-relic-solutions/get-started/networks.mdx
NR-144829
work done: 
Reformatted table to have different capability sections. 
Added an easy-to-copy list of endpoints below the table (although redundant, this will apparently help customers who just want a list of things to enable)
Moved up the main endpoints to be at the top. 
Build: https://docswebsitedevelop-updatenetworksdocimprovedorgan.gatsbyjs.io/docs/new-relic-solutions/get-started/networks/#new-relic-endpoints
=> Update networks doc  - improved organization

src/content/docs/data-apis/ingest-apis/security-data-api.mdx
The curl command to send data to the Security Data API had some formatting issues that prevented it from executing. I got some help from an SME to correct this. I used the version that's being placed in the Marketplace UI, so the prompts are slightly different than the original.
I've tested this on my own account.
=> Security Data API: Correct curl command to make it runnable

src/content/docs/infrastructure/manage-your-data/data-instrumentation/apm-data-infrastructure-monitoring.mdx, src/content/docs/infrastructure/new-relic-infrastructure/troubleshooting/apm-data-missing-infrastructure.mdx
* The documentation around requirements for the infra-table on the APM Summary page were out of date, leading some users to not complete required steps and sometimes to not realize they can access the feature.
* This feature now uses the related entities feature similar to service maps to fetch relationships across accounts, thus eliminating the requirement that a host and APM agent are on the same account
* This feature now covers k8s entities as well, however [additional …
=> feat: Update docs for infra/apm linkage on APM summary page

src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx
This step is no longer needed as the in-product wizard will properly populate the proxy settings into the necessary file
=> Remove manual proxy configuration step

src/content/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements.mdx
Update the PHP Agent Compatibility page support Callout with EOL notice for PHP 7.0 and 7.1. 
Remove message regarding 5.5 and 5.6 EOL.
=> chore(php): update compatibility support callout

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics.mdx
We received some feedback that the best practices for OTLP metrics ingest weren't clear with regard to the handling of the `startTimeUnixNanos` field for cumulative metrics. I've updated the docs to address the gap and refreshed the link to the relevant portion of the OpenTelemetry specification.
=> fix(otlp metrics): clarify startTimeUnixNanos behavior for cumulative metrics

src/content/docs/apis/nerdgraph/nerdgraph-usage-limits.mdx, src/content/docs/apis/rest-api-v2/basic-functions/api-overload-protection-handling-429-errors.mdx, src/content/docs/data-apis/manage-data/view-system-limits.mdx, src/nav/telemetry-data-platform.yml
NerdGraph will be enforcing concurrent request limits soon, this documentation is a reference for customers and support in the event they see a 429 response from the GraphQL API.
@vosechu, a review would be welcome if you have a moment to spare.
=> Add note on GraphQL usage limits

src/data/attribute-dictionary.json
* Documents that the `entityGuid` attribute exists on various other Browser-related event types as exemplified by [this query](https://onenr.io/0ERzoOzLAjr)
=> feat(Data Dictionary): Add entityGuid to more Browser events

src/content/docs/apm/agents/net-agent/net-agent-api/guide-using-net-agent-api.mdx
This PR updates some links in the .NET Agent's public API usage guide to point to current (non-deprecated) APIs.
=> .NET Agent API usage guide: update links for DT APIs to non-obsolete versions

src/content/docs/codestream/how-use-codestream/pull-requests.mdx, src/content/docs/codestream/troubleshooting/jira-server-integration.mdx
when `wrapping text in backticks` escape chars like `\` show up as plain text.
I also add lang identifiers to codeblock. `ini` works well on github, not sure how well it will work on docs-website
=> fix: remove plain text escape chars `\`

src/content/docs/logs/ui-data/parsing.mdx
Clarifying that log parsing rules are unordered.
=> docs: Adding note that Logging parsing rules are unordered

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx, src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx
It's often missed that automatic browser monitoring only works for .NET framework
=> Update .NET browser monitoring info

src/content/docs/apm/agents/net-agent/install-guides/install-net-agent-using-nuget.mdx, src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx, src/content/docs/distributed-tracing/troubleshooting/missing-trace-data.mdx
Added info about an undocumented configuration option to set the amount of infinite tracing spans the agent will hold in memory before dropping them. [Other agents suggest setting this to 100k](https://docs.newrelic.com/docs/distributed-tracing/troubleshooting/missing-trace-data/#spans), so that's the number I used in this doc.
- https://github.com/newrelic/node-newrelic/blob/9be213963938ba9bbfac251ba594952a964631bc/lib/config/default.js#L1103-L1124
I'd like to include a maximum value and the time period for these queues (it might be 60 seconds or 5 seconds (12 times a minute), different agents send on different periods).
Maximum value seems to not be a regular number, but a payload size so I'm not sure I can add one. I'm requesting that the node team look this over to confirm my changes.
=> add: config option for 8T span resevoir

src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring.mdx
This PR updates the compatibility docs for lambda with supported runtimes for Node and Python.
=> Updated supported runtimes list for lambdas.

gatsby-node.js, package.json, yarn.lock
override graphql tableOfContents
- gatsby-plugin-mdx does not provide a way to configure options for mdast-util-toc
- this lets us pass in a parents option so we can include headings under JSX, in this case Steps
=> Steps headers in PageTools

src/content/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration.mdx
This Callout tag was uncapitalized which meant it didn't render an actual callout. It also broke the translation workflow since it doesn't recognize that tag
=> Capitalize Callout component tag

src/content/docs/browser/new-relic-browser/browser-apis/setApplicationVersion.mdx, src/nav/browser.yml
This PR adds documentation for a new browser agent API method: `setApplicationVersion`.  This method is being released as part of 1.238.0, which will roll out to end this week.
- This a new method that currently has no usage documented
- https://issues.newrelic.com/browse/NR-150940
=> feat: add documentation for setApplicationVersion

src/content/docs/new-relic-solutions/get-started/networks.mdx, src/content/whats-new/2023/06/whats-new-06-23-synthetics-horde-ip-changes.md
The IP range change for the Synthetics Horde endpoints has been moved from today (Aug 22) to tomorrow (Aug 23). This updates the date references in the networks doc and in the original what's new post.
=> (Publish 8/23) chore(Horde): Update target date for IP range changes

gatsby-node.js, scripts/releaseNotes.mjs, src/components/EolPage.js
- gives release note authors the option to specify an eolDate in frontmatter that overrides the default generated one
- these changes apply to eolPage.js as well as the generated release-notes.json
v6.26.0 shows the January eol date instead of September
I modified the releaseNotes.mjs script to write to a file locally and got these results:
generated json for the release note with specified eolDate:
```json
{
"agent": "dotnet",
"date": "2020-09-15",
"downloadLink": "https://download.newrelic.com/dot_net_agent/6.x_release/",
"version": "6.26.0.0",
"features": null,
"bugs": null,
"security": null,
"description": "Notes The 6.x agent supports legacy frameworks...",
"eolDate": "2029-01-09"
},
```
generated json for another release note with the default generated eolDate that adds 3 years is …
=> feat: add eolDate frontmatter type

src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-62600.mdx
Overrides the default `eolDate` for the .NET Agent v6.26.0 release to reflect extended support for that version.
=> docs: Add explicit eolDate to frontmatter for .NET Agent v6.26.0 (publish with EOL dev feature from doc eng)

src/content/docs/style-guide/writing-docs/article-templates/whats-new-tech-writer-tasks.mdx
Clarifies that reviewing What's New posts is the responsibility of the daily hero and not the hero of the release date.
=> chore(style): clarify hero responsibilities

src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
A bunch of aggregator NRQL functions are in the non-aggregators section of the NRQL Reference page, and there's one non-aggregator in the aggregators section.  I've moved them to the appropriate sections.
=> fix: Move aggregators out of non-aggregators section and vice versa

src/content/docs/logs/forward-logs/azure-log-forwarding.mdx
It fixes the wording for the Microsoft Azure log forwarding integrations. These integrations were referring to an old UI component that has changed its naming from "Add more data sources" to "Add data". Also, the instructions were pointing to the "top right of the page", and this has now been physically moved to the left sidebar.
=> Fix wording in Azure log forwarding integrations docs

src/content/docs/apm/agents/net-agent/getting-started/net-agent-eol-policy.mdx, src/content/docs/release-notes/agent-release-notes/net-release-notes/net-agent-62700.mdx
To clear up some confusion about which 6.x version of the .NET Agent is still supported, we're adding an `eolDate` override to the frontmatter for 6.27 as we've previously done for 6.26 -- essentially, either of those two versions will have long-term support until January of 2029.
=> chore: Add eolDate override for .NET Agent v6.27.0.0 release notes.

src/content/docs/infrastructure/infrastructure-ui-pages/infrastructure-inventory-page-search-your-entire-infrastructure.mdx
* Added a note explaining that "com.newrelic.winpkg" is an infrastructure agent built-in integration that's available on Windows to collect inventory data.
=> added: infra-agent winpkg integration note

src/content/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration.mdx
This default value was wrong, you can check the default value here: 
- https://github.com/newrelic/node-newrelic/blob/3f494f8ad8dd1350fbe034e9c4a582a40228bc45/lib/config/default.js#L696
=> fix: default for browser monitoring

src/content/docs/apm/agents/nodejs-agent/getting-started/monitor-your-nodejs-app.mdx
The markdown link was in plain text:
also the startup instructions were mixing up the old suggested way or requiring the agent and the new way. You can't add a startup cmd you your app's code
=> fix: typo and startup instructions

src/content/docs/browser/new-relic-browser/troubleshooting/troubleshoot-ajax-data-collection.mdx, src/nav/browser.yml
This PR updates the ajax missing data troubleshooting doc. The browser agent has supported capturing `fetch` for some time and has made strides in the data we expose on the window to help with troubleshooting agent initialization.
Also fixed a bug in the sidebar menu where click on the link for `page-load-timing-resources/instrumentation-browser-monitoring` would completely collapse the sidebar menu.
=> chore: Update browser ajax data troubleshooting

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
As of v11.1.0 of newrelic Node.js agent it now supports fetch and undici by default.  I updated the docs to call this out and mention the mininum version support.
**Note**: We just released 11.1.0 so the release notes PR(#14519) has not yet been merged.
=> docs: added support for fetch and undici as of v11.1.0 of Node.js agent

src/content/docs/release-notes/agent-release-notes/java-release-notes/java-agent-860.mdx
This specific item relates to a bad release of a library. Since older versions of the agent are compatible with the same versions, this item should be removed to avoid confusion.
=> chore(java): removing unimportant item from release notes

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-java.mdx
The counter is referenced in the next section with a different name.
=> Fix counter variable name

src/content/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework.mdx
There is no content changed. The .NET Framework version is the most important info in this doc, and most likely info people come here looking for, but it's buried midway down the page. So I moved it to the top, like we do in [the .NET Core doc](https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core/), alphabetically it should be here anyway.
=> chore: move framework versions

src/install/mysql/whatsNext.mdx
Fixed broken link in the description for cluster.slaveRunning.
=> Fixed broken replication slave link

src/content/docs/logs/ui-data/parsing.mdx
Added two new configuration parameters, `keepAttributes` and `noPrefix`, for the JSON grok type used for parsing JSON log messages that are mixed with plain text.
=> feat(logging): new configuration options for JSON grok type

src/content/docs/apm/agents/php-agent/frameworks-libraries/guzzle.mdx
The oldest supported agent version is now 7.0 so updating this page to reflect that.
=> [MERGE 9/13] Updates guzzle.mdx agent support info

scripts/actions/webdriver-desktop.mjs
Add some additional sleep functions to when the web driver navigates to a different url.  Removes some old logging
=> fix: add a sleep to home page url

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
The documentation currently states that the default value for the interval of NTP requests is 15 minutes but it does not contain the fact that the minimum value is 15 minutes as well (see the [source code](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/metrics/ntp.go#L19)).
Moreover, the following behaviour
```
Between intervals, the last known offset is reported.
```
causes a misunderstanding from the customer perspective especially if they set the interval below 15 minutes.
What they see in New Relic is that every minute an `NTP offset value` is being sent from the infra agent where all the values are exactly the same for 15 minutes long and they suddenly change in the next 15 minute interval.
With this PR, that misunderstanding can be clarified.
=> Add minimum value info as well as default one

src/content/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes.mdx
This PR adds more clarity around why the Metric API might drop a large numeric value where we provided no details before. 
I had considered adding a link to the Wiki page on double precision floats but decided against it. 
https://en.wikipedia.org/wiki/Double-precision_floating-point_format
=> fix: improve documentation around Metric API double precision limits

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts.mdx
* The OTel community changed the host.id attribute to be disabled by default (v0.82.0 or greater). Adding it back to be enabled in the recommended config for host monitoring.
=> [fix] OTel host.id is disabled by default

.github/workflows/agent-release-notes.yml, scripts/releaseNotes.mjs
Changes the ref to `main` that the workflow checks out when generating release note JSON.
When using `develop` there's a chance that any new release notes in `develop` are not yet deployed to prod, but downstream deps (agent upgrade nerdlet) will use data in JSON and display release note info that isn't yet live. for example, links to site will 404 for relevant release note until it's live.
Also changed `releaseNotes.mjs` to write to a file instead of log to console. the JSON logged overflows viewable/searchable console and needed to analyze full JSON. I suppose I also could have just written output to file. Defer to y'all if we want that to be default or not.
Mitigates  https://issues.newrelic.com/browse/NR-155603
=> fix(actions): checkout main branch to generate release notes

src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_set_error_group_callback.mdx, src/content/docs/apm/agents/php-agent/php-agent-api/newrelic_set_user_id.mdx, src/nav/apm.yml
Addition of API documentation for the new API calls implemented as part of the Errors Inbox Improvement effort. 
The new APIs are:
- `newrelic_set_error_group_callback`, allowing a user to register a callback with the PHP Agent that will return a custom error group name when invoked by the agent during the handling of an error.
- `newrelic_set_user_id`, allowing an application to set a unique user ID string that associates an individual user with the current transaction.
Depends on https://github.com/newrelic/docs-website/pull/14640
=> [MERGE 9/20] feat(php-agent): Errors Inbox Improvement API Documentation

src/components/DataDictionaryFilter.js
previously, the `dataSources` property on `event`s was just an array of strings, but now it's an array of objects with the property `name`, since that's what the GraphQL service returns.
this change fixes the logic to account for that
=> fix: `dataSource` check for filter

src/content/docs/apm/agents/python-agent/supported-features/python-mlops.mdx
This PR adds a callout to privacy settings that exist within the new MLOps feature for Python Agent v9.1.0
=> Add callout to privacy settings

src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx
adding a missing setting option to the advanced config tables for network monitoring
=> chore: add missing setting option

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction.mdx
The OTel Logs Bridge API, Logs SDK, and Log Data Model are all stable.
See: https://github.com/open-telemetry/opentelemetry-specification/pull/3376
=> chore: Update logs specification stability

src/content/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90100.mdx
This PR adds release notes for Python Agent v9.1.0. If this could be merged on 9/26/23, that would coordinate with our release schedule. Thanks!
=> Add release notes for python agent v9.1.0 (PLEASE MERGE SEPT 26TH AM)

src/content/docs/apis/nerdgraph/examples/nerdgraph-streaming-export.mdx
* Jira ticket: NR-164732
* Currently, the documentation for export compression says that users will save on "egress COGS" while using it. This is incorrect terminology, they will actually save on ingress costs. This PR corrects the mistake.
=> docs: Minor streaming export compression correction

src/content/docs/alerts-applied-intelligence/overview.mdx, src/content/docs/browser/new-relic-browser/browser-apis/noticeerror.mdx, src/content/docs/browser/new-relic-browser/installation/update-browser-agent.mdx, src/content/docs/data-apis/convert-to-metrics/analyze-monitor-data-trends-metrics.mdx, src/content/docs/data-apis/custom-data/get-custom-data-from-any-source.mdx, src/content/docs/distributed-tracing/concepts/quick-start.mdx, src/content/docs/errors-inbox/errors-inbox.mdx, src/content/docs/infrastructure/infrastructure-ui-pages/infra-hosts-ui-page.mdx, src/content/docs/infrastructure/install-infrastructure-agent/linux-installation/container-instrumentation-infrastructure-monitoring.mdx, src/content/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data.mdx, src/content/docs/infrastructure/microsoft-azure-integrations/get-started/introduction-azure-monitoring-integrations.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-android/get-started/introduction-new-relic-mobile-android.mdx, src/content/docs/mobile-monitoring/new-relic-mobile-ios/installation/cocoapods-installation.mdx, src/content/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/mobile-sdk-api-guide.mdx, src/content/docs/new-relic-solutions/get-started/intro-new-relic.mdx, src/content/docs/new-relic-solutions/new-relic-one/install-configure/update-new-relic-agent.mdx, src/content/docs/query-your-data/explore-query-data/use-charts/use-your-charts.mdx, src/content/docs/style-guide/writing-strategies/introduction-style-guide.mdx, src/content/docs/tutorial-create-alerts/create-new-relic-alerts.mdx, src/content/docs/tutorial-innovation-and-growth/development-quality-mgmt.mdx
This updates the top 404 pages with proper redirects. Some of the top 50 seem to have redirects and therefore would not be reflected here.
=> update top 404s with redirects to proper docs

src/content/docs/licenses/product-or-service-licenses/mobile-app-licenses/ios-application-licenses.mdx, src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-5060.mdx
* Updates to latest licenses for the iOS mobile app
* Adds in release notes for the latest version
=> docs: New Relic iOS 5.6.0 and license update

src/content/docs/apm/agents/go-agent/get-started/go-agent-compatibility-requirements.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-25-0.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-25-1.mdx, src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-26-0.mdx
Updates release notes and compatibility matrix for the Go Agent 3.26.0 release.
=> Update Go Agent release notes for 3.26.0

src/content/docs/logs/ui-data/parsing.mdx
Removed this text `The limit is not a fixed value; it scales up or down proportionally to the volume of data stored daily by the account and the environment size that is subsequently allocated to support that customer.` from the [Parsing log data](https://docs.newrelic.com/docs/logs/ui-data/parsing/#limits) page.
Requested in the #help-documentation channel by Alexander Mosher.
=> fix(Logs): Removed a confused text about the limit

src/content/docs/data-apis/convert-to-metrics/create-metrics-other-data-types.mdx, src/content/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions.mdx
Because of a request from Alexander Mosher in the help-documentation channel, added an important note about E2M rules in these sections:
- [WITH ... AS clause (NRQL variables)](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#with-as-nrql-var)
- [Step 1. Create NRQL query rule](https://docs.newrelic.com/docs/data-apis/convert-to-metrics/create-metrics-other-data-types/#create-nrql)
=> feat(NRQL): Added important note about E2M rules

src/nav/infrastructure.yml
* We recently added https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration/ but it's not listed in the on-host integrations list.
=> nvidia gpu integration added to on-host integrations nav

src/content/docs/apm/agents/php-agent/configuration/php-agent-configuration.mdx, src/content/docs/logs/logs-context/configure-logs-context-php.mdx
The PHP agent will be adding APM log decoration and this PR adds the configuration information needed to use the feature.  It is modeled after the [.Net ](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/) documentation.
**I would appreciate a review of this PR but please to no merge these changes until I've given the go ahead.**
=> [Publish 10/03/2023] chore(PHP agent): Adds log decoration docs

src/content/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent.mdx
Updated the [Compatibility and requirements for the Java agent](https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/#jvm) page. Removed Java 5 and Java 6 from the table.
This has been requested in the `help-documentation` channel.
=> fix(Java agent): Removed Java 5 and Java 6

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* Based on customer feedback, re-grouping NTP metrics together in a specific section so that's easier to understand.
=> fix: re-group ntp

src/content/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-agent.mdx
With the new fleet deployment solutions for the CLI install, our docs list uninstall methods for infrastructure agents deployed with Ansible, Chef, and Puppet. However, this documentation refers to the previous packages published by the infrastructure team, not the CLI install packages published by Virtuoso.
As the CLI does not support uninstall at this time, and as the docs point to the new A/C/P solutions from Virtuoso, I'm proposing to delete the out-of-date uninstall instructions for the infrastructure agent for A/C/P to prevent confusion in the short term about the use of these products.
=> chore(infrastructure): Remove uninstall instructions for CLI fleet deployment

src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/understand-technical-concepts/streaming-alerts-key-terms-concepts.mdx
The top end of the duration was incorrect.
=> Alerts: Correct duration end

src/content/docs/apm/agents/python-agent/python-agent-api/seterrrorgroupcallback-python-agent-api.mdx
* Fixes documentation around Python agent's error_group_callback to reflect the real arguments accepted.
=> fix: Fix Arguments to Python error_group_callback

src/content/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-11-0-0.mdx
We missed a changelog entry for 11.0.0. This updates it accordingly.
=> chore: updated 11.0.0 release notes for Node.js agent, we missed a line item during release

src/content/docs/change-tracking/change-tracking-view-analyze.mdx
This PR adds a maxWidth attribute to left-justified images that are not shrinking when the viewport is decreased.
@homelessbirds the way to test this is to make the browser narrow and just scroll up and down to make sure no images run into the right gutter.
=> Set max width of left-justified images

src/content/docs/vulnerability-management/overview.mdx
My understanding is FedRamp is now authorized  for VM as of Oct 1, 2023 so removing the FedRAMP restriction from this page now.
=> Removing FedRAMP restriction from VM Get Started Page

src/content/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.mdx
Line 34, "The following are proposed time ranges. The actual release date may vary.", didn't belong there. It looked like a copy/paste error. The line is repeated further down on line 61 and looks to make sense in that location.
=> fix: Node agent compatibility typo

src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
* The infrastructure agent provides an optional setting to enable a status / health check point.
=> feat: Added infra agent status endpoint settings

src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx
This PR documents a new environment variable added in .NET Agent v10.18.0, which is being released on 10/17/2023.
=> docs: Documents the NEW_RELIC_HIGH_SECURITY environment variable added in v10.18.0

src/content/docs/browser/new-relic-browser/browser-apis/setcustomattribute.mdx
This PR updates the browser agent setCustomAttribute() API docs to indicate support of allowing boolean-type data as an accepted value.
=> feat: Add support for boolean values in setCustomAttribute api

src/content/docs/browser/browser-monitoring/browser-pro-features/ajax-page-identify-time-consuming-calls.mdx, src/content/docs/browser/new-relic-browser/troubleshooting/troubleshoot-graphql-collection.mdx, src/data/attribute-dictionary.json, src/nav/browser.yml
This PR updates a few AjaxRequest related docs to describe GraphQL metadata that has recently been introduced by the Browser Agent in [v1.245.0](https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1.245.0)
=> feat: update AJAX docs to describe new GQL properties

src/content/docs/release-notes/agent-release-notes/go-release-notes/go-agent-3-27-0.mdx
Release change log for go agent version 3.27.0. Expected release EOD today.
=> feat: release 3.27.0 go agent:

src/content/docs/apm/agents/ruby-agent/attributes/ruby-agent-attributes.mdx
* The `capture_params` configuration option is not deprecated
* Roda instrumentation will capture params
cc @fallwith, @hannahramadan, @tannalynn
=> chore: Update ruby-agent-attributes.mdx

src/content/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/setup-prometheus-agent.mdx
The Prometheus Agent docs have `annotation` in many places where it should read `annotations` in the configuration.  This PR updates the examples to a working configuration.
Tested and confirmed that filtering requires the configuration `annotations` and will not work with `annotation`.
Please also see the Prometheus agent [chart values file](https://github.com/newrelic/newrelic-prometheus-configurator/blob/main/charts/newrelic-prometheus-agent/values.yaml) which documents the `annotations` usage.
=> [fix] Update setup-prometheus-agent.mdx

src/content/docs/data-apis/understand-data/event-data/events-reported-mobile-monitoring.mdx
**[Ticket](https://new-relic.atlassian.net/browse/NR-149337): Update docs**
1. Add MobileUserAction event type
2. There is no attribute associated with this event type, no need to update data dictionary
**More details:**
Original doc issue reported [here](https://github.com/newrelic/docs-website/issues/7309)
Slack report [here](https://newrelic.slack.com/archives/C01FKANDWJU/p1691467402396239)
=> [NR-149337] Add MobileUserAction event type

src/content/docs/change-tracking/change-tracking-graphql.mdx
The doc went back and forth from `groupId` to `groupID`. I'm not positive if `groupID` is a problem, but I made it consistent with the way I know works.
=> fix: groupID to groupId

src/content/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api.mdx
The `[output]` in the bash codeblock should format those lines as output, without the `$` which indicates input
How it looks now:
what my change will do:
=> chore: format output lines in bash codeblock

src/content/docs/apm/agents/nodejs-agent/installation-configuration/enable-source-maps.mdx
see this PR to see what the change will do
https://github.com/newrelic/docs-website/pull/14959
=> chore: format the terminal errors as output instead of input

src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-tutorial-python.mdx
The environment variables for the metrics exporter as defined [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md#opentelemetry-metrics-exporter---otlp) now use new values for temporality preference and histogram aggregation. This PR updates the Python OpenTelemetry tutorial to use the new values but keep the intended behaviour.
=> Update the python opentelemetry example to use current environment variable values

src/content/docs/browser/new-relic-browser/configuration/browser-app-settings-page.mdx, src/content/docs/browser/new-relic-browser/configuration/obfuscate-browser-agent-data.mdx, src/nav/browser.yml
This PR adds documentation about the Browser Agent's obfuscation configurations.  This was first introduced [over a year ago](https://github.com/newrelic/newrelic-browser-agent/releases?q=obfuscate&expanded=true) but has gone undocumented up until now.
=> feat: add obfuscation documentation

src/content/docs/errors-inbox/browser-tab.mdx
I found the typo in the docs while I was following them.
In two places word "error" is spelled as "errror".
=> fix: update browser-tab.mdx - fixed typo in word "error"

src/content/docs/browser/new-relic-browser/browser-apis/using-browser-apis.mdx
This PR:
* Updates the browser API summary page to include descriptions for new(er) APIs that have been added to the docs site, but not accounted for here.
* Updates each item to link to the relevant api doc
=> feat: Update api summary page to include new info and links to relevant pages

src/content/docs/infrastructure/host-integrations/host-integrations-list/varnish-cache-monitoring-integration.mdx
It fixes a typo in varnish configuration description
The `params` file was deprecated in varnish 6 and versions above. Check [upgrading to varnish 6 docs](https://varnish-cache.org/docs/6.0/whats-new/upgrading-6.0.html#services) for details.
=> fix: varnish configuration description typo

src/data/attribute-dictionary.json
This PR updates the data dictionary to note that INP shows as "seconds (s)" instead of "milliseconds (ms)"
=> fix: inp shows as seconds in NR1 not ms
